<?php
		
		/* UTF-8 TEST
		
			中文汉字漢字
		
		*/
				
				/* EnglishMisspellingsWords_F
					
					Class for English-Misspellings for all words beginning with : F.
					
				*/

	class EnglishMisspellingsWords_F {
			/* __construct($args)
			
				Constructor.
				
				Nothing to do here.
			
			*/
			
		public function __construct($args) {
			return TRUE;
		}
		
			/* EnglishMisspellingsWords()
			
				List of English misspellings for words starting with : F.
			
			*/

		public function EnglishMisspellingsWords() {
			return [
				'fabricant'=>[
					'fabricent',
				],
				'face'=>[
					'face face',
					'face face face',
				],
				'faceless'=>[
					'faceles',
				],
				'facetely'=>[
					'facetly',
				],
				'facetious'=>[
					'fascitious',
					'facetous',
				],
				'facetiously'=>[
					'facetously',
				],
				'facies'=>[
					'faceis',
					'facis',
				],
				'facilely'=>[
					'facilly',
				],
				'facilitate'=>[
					'faciliate',
				],
				'facilitated'=>[
					'faciliated',
				],
				'facilities'=>[
					'facilites',
				],
				'facility'=>[
					'facillity',
					'faculity',
				],
				'facsimile'=>[
					'facimile',
					'facsimilie',
				],
				'facsimileing'=>[
					'facsimilieng',
				],
				'fact'=>[
					'fact fact',
					'fact fact fact',
				],
				'fact-checker'=>[
					'factchecker',
				],
				'factious'=>[
					'factous',
				],
				'factiously'=>[
					'factously',
				],
				'factitious'=>[
					'factitous',
				],
				'factitiously'=>[
					'factitously',
				],
				'factitively'=>[
					'factitivly',
				],
				'factual'=>[
					'factaul',
				],
				'factualism'=>[
					'factaulism',
				],
				'factualists'=>[
					'factaulists',
				],
				'factualness'=>[
					'factaulness',
				],
				'factualnesses'=>[
					'factaulnesses',
				],
				'facultatively'=>[
					'facultativly',
				],
				'fadable'=>[
					'fadible',
				],
				'fadein'=>[
					'fadien',
				],
				'fadeins'=>[
					'fadiens',
				],
				'faerie'=>[
					'faerei',
					'faeri',
				],
				'faggot'=>[
					'fagot',
				],
				'faggoting'=>[
					'fagoting',
				],
				'faggotings'=>[
					'fagotings',
				],
				'faggotries'=>[
					'fagotries',
				],
				'faggy'=>[
					'fagy',
				],
				'fahlband'=>[
					'falband',
				],
				'fahlbands'=>[
					'falbands',
				],
				'fahrenheit'=>[
					'farenheit',
				],
				'faience'=>[
					'faiance',
				],
				'failing'=>[
					'faling',
				],
				'failure'=>[
					'faliure',
				],
				'faineance'=>[
					'faineence',
				],
				'fainer'=>[
					'fainir',
				],
				'fainthearted'=>[
					'faint-hearted',
				],
				'faintheartedly'=>[
					'fainthertedly',
				],
				'fair'=>[
					'fair fair',
					'fair fair fair',
				],
				'fairly'=>[
					'afairly',
					'fairally',
					'fairaly',
					'fairely',
					'fairlly',
				],
				'faithful'=>[
					'faithfull',
				],
				'faithlessly'=>[
					'faithlessally',
					'faithlessaly',
					'faithlessely',
					'faithlesslly',
				],
				'falafel'=>[
					'falafal',
				],
				'faleshood'=>[
					'falshood',
				],
				'fall'=>[
					'fall fall',
					'fall fall fall',
					'fal',
				],
				'fallacious'=>[
					'falacious',
					'fallacous',
				],
				'fallaciously'=>[
					'fallacously',
				],
				'fallacy'=>[
					'falacy',
					'fallasy',
				],
				'fallback'=>[
					'falback',
				],
				'fallen'=>[
					'falled',
					'falen',
				],
				'fallible'=>[
					'falible',
					'fallable',
				],
				'falloff'=>[
					'faloff',
				],
				'fallout'=>[
					'falout',
				],
				'fallow'=>[
					'falow',
				],
				'falsely'=>[
					'falsley',
					'falsly',
				],
				'falter'=>[
					'faulter',
				],
				'familiar'=>[
					'familar',
					'familliar',
					'familier',
				],
				'families'=>[
					'familes',
					'famillies',
					'familys',
					'larnilies',
				],
				'family'=>[
					'famaly',
					'familiy',
					'familly',
					'family family',
					'family family family',
					'famially',
					'famialy',
					'famiely',
				],
				'famine'=>[
					'famini',
				],
				'famous'=>[
					'famos',
					'famous famous',
					'famous famous famous',
					'famouse',
					'famout',
					'famus',
					'fanmous ',
					'fomous',
				],
				'famously'=>[
					'fameousely',
					'fameously',
					'famousely',
					'famousally',
					'famousaly',
					'famouslly',
				],
				'fanaticism'=>[
					'fanatism',
				],
				'fancier'=>[
					'fanceir',
					'fancir',
				],
				'fancy'=>[
					'fansy',
				],
				'fanjinghshan'=>[
					'fanjingshan',
				],
				'fanny'=>[
					'fany',
				],
				'fantabulous'=>[
					'fentabulous',
				],
				'fantail'=>[
					'fentail',
				],
				'fantasia'=>[
					'fentasia',
				],
				'fantasist'=>[
					'fentasist',
				],
				'fantasize'=>[
					'fentasize',
				],
				'fantastic'=>[
					'fentastic',
				],
				'fantasticality'=>[
					'fentasticality',
				],
				'fantasticate'=>[
					'fentasticate',
				],
				'fantasticating'=>[
					'fentasticating',
				],
				'fantastication'=>[
					'fentastication',
				],
				'fantastications'=>[
					'fentastications',
				],
				'fantasticoes'=>[
					'fentasticoes',
				],
				'fantasy'=>[
					'fantacy',
					'fentasy',
				],
				'fantasyland'=>[
					'fentasyland',
				],
				'fantasylands'=>[
					'fentasylands',
				],
				'fantoccini'=>[
					'fantoccina',
					'fantocini',
				],
				'fantod'=>[
					'fentod',
				],
				'fantom'=>[
					'fentom',
				],
				'fantômas'=>[
					'fantomas',
				],
				'fanzine'=>[
					'fanzini',
				],
				'far'=>[
					'far far',
					'far far far',
				],
				'far fetched'=>[
					'farfetched',
				],
				'far-reaching'=>[
					'farreaching',
				],
				'farceur'=>[
					'farcer',
				],
				'farcy'=>[
					'farsy',
				],
				'farewell'=>[
					'fairwell',
					'farewel',
				],
				'farina'=>[
					'farini',
				],
				'farinaceous'=>[
					'fariniceous',
				],
				'farkleberries'=>[
					'farkleberies',
				],
				'farkleberry'=>[
					'farklebery',
				],
				'farm'=>[
					'farm farm',
					'farm farm farm',
				],
				'farmers'=>[
					'hrmers',
				],
				'farmstead'=>[
					'farmsted',
				],
				'farraginous'=>[
					'faraginous',
				],
				'farrago'=>[
					'farago',
				],
				'farrier'=>[
					'farreir',
					'farier',
					'farrir',
				],
				'farrow'=>[
					'farow',
				],
				'farseeing'=>[
					'farseieng',
				],
				'farsightedly'=>[
					'farsightedally',
					'farsightedaly',
					'farsightedely',
					'farsightedlly',
				],
				'farsightedness'=>[
					'farsightednes',
				],
				'fasces'=>[
					'faces',
					'facses',
					'fases',
				],
				'fascia'=>[
					'facia',
					'facsia',
					'fasia',
				],
				'fascicle'=>[
					'facicle',
					'facsicle',
					'fasicle',
				],
				'fascicular'=>[
					'fasciculer',
				],
				'fasciculated'=>[
					'faciculated',
					'facsiculated',
					'fasiculated',
				],
				'fasciculations'=>[
					'faciculations',
					'facsiculations',
					'fasiculations',
				],
				'fasciitis'=>[
					'faciitis',
					'facsiitis',
					'fasiitis',
				],
				'fascinate'=>[
					'facinate',
					'fasinate',
					'facsinate',
					'fascinite',
				],
				'fascinating'=>[
					'facinating',
					'facsinating',
					'fasciniting',
					'fasinating',
				],
				'fascination'=>[
					'facination',
					'facsination',
					'fascinition',
					'fasination',
				],
				'fascinator'=>[
					'fascinitor',
				],
				'fascioliases'=>[
					'facioliases',
					'facsioliases',
					'fasioliases',
				],
				'fascioliasis'=>[
					'facioliasis',
					'facsioliasis',
					'fasioliasis',
				],
				'fascism'=>[
					'faschism',
					'fashism',
					'facism',
					'facsism',
					'fasism',
				],
				'fascist'=>[
					'facist',
					'facsist',
					'fasist',
				],
				'fashion'=>[
					'fasion',
				],
				'fashionable'=>[
					'fashionible',
				],
				'fashionmonger'=>[
					'fashiomonger',
					'fashiononger',
				],
				'fashionmongers'=>[
					'fashiomongers',
					'fashionongers',
				],
				'fashious'=>[
					'fashous',
				],
				'fast'=>[
					'fast fast',
					'fast fast fast',
				],
				'fastball'=>[
					'fastbal',
				],
				'fastened'=>[
					'fastend',
				],
				'fastidious'=>[
					'fastidous',
				],
				'fastidiously'=>[
					'fastidously',
				],
				'fastuous'=>[
					'fastous',
				],
				'fat'=>[
					'fat fat',
					'fat fat fat',
				],
				'fatalistically'=>[
					'fatalisticalally',
					'fatalisticalaly',
					'fatalisticalely',
					'fatalisticallly',
				],
				'fatalities'=>[
					'fatalies',
					'fatalites',
				],
				'fatally'=>[
					'fataly',
					'fately',
					'fatalally',
					'fatalaly',
					'fatalely',
					'fatallly',
				],
				'fatheadednesses'=>[
					'fathedednesses',
				],
				'father'=>[
					'father father',
					'father father father',
				],
				'fatherless'=>[
					'fatherles',
				],
				'fatherlinesses'=>[
					'fatherlinisses',
				],
				'fatherly'=>[
					'fatherally',
					'fatheraly',
					'fatherely',
					'fatherlly',
				],
				'fatigabilities'=>[
					'fatigabiliteis',
					'fatigabilitis',
				],
				'fatigable'=>[
					'fatigible',
				],
				'fatly'=>[
					'fatally',
					'fataly',
					'fatlly',
				],
				'fattened'=>[
					'fattend',
				],
				'fatter than'=>[
					'fatter then',
				],
				'fatuous'=>[
					'fatous',
				],
				'fatuously'=>[
					'fatously',
				],
				'fatuousness'=>[
					'fatousness',
				],
				'fatuousnesses'=>[
					'fatousnesses',
				],
				'faultlessly'=>[
					'faultlessally',
					'faultlessaly',
					'faultlessely',
					'faultlesslly',
				],
				'favonian'=>[
					'favonan',
				],
				'favor'=>[
					'favor favor',
					'favor favor favor',
				],
				'favorable'=>[
					'favorible',
				],
				'feal'=>[
					'fel',
				],
				'fear'=>[
					'fear fear',
					'fear fear fear',
					'feer',
					'fer',
				],
				'feared'=>[
					'feard',
				],
				'fearful'=>[
					'ferful',
				],
				'fearless'=>[
					'fearles',
					'ferless',
				],
				'fearlessnesses'=>[
					'ferlessnesses',
				],
				'fearsome'=>[
					'fersome',
				],
				'fearsomely'=>[
					'fearsomly',
				],
				'fearsomenesses'=>[
					'fersomenesses',
				],
				'feasance'=>[
					'feasence',
				],
				'feasibility'=>[
					'feasability',
				],
				'feasible'=>[
					'feasable',
					'fesible',
				],
				'feast'=>[
					'fest',
				],
				'feat'=>[
					'fet',
				],
				'feather'=>[
					'fether',
				],
				'featherbedding'=>[
					'fetherbedding',
				],
				'featherbeddings'=>[
					'fetherbeddings',
				],
				'featherbrain'=>[
					'fetherbrain',
				],
				'featherbrained'=>[
					'featherbrainid',
					'fetherbrained',
				],
				'feathered'=>[
					'fethered',
				],
				'featheredge'=>[
					'featherege',
				],
				'featheredged'=>[
					'feathereged',
				],
				'featheredges'=>[
					'feathereges',
				],
				'featherheaded'=>[
					'featherheded',
				],
				'feathering'=>[
					'fethering',
				],
				'featherstitch'=>[
					'fetherstitch',
				],
				'featherstitched'=>[
					'fetherstitched',
				],
				'featherstitches'=>[
					'fetherstitches',
				],
				'featherweight'=>[
					'featherwieght',
					'fetherweight',
				],
				'featherweights'=>[
					'featherwieghts',
					'fetherweights',
				],
				'feature'=>[
					'feauture',
					'feture',
				],
				'featured'=>[
					'fetured',
				],
				'featureless'=>[
					'featureles',
					'fetureless',
				],
				'features'=>[
					'featurs',
				],
				'featurette'=>[
					'feturette',
				],
				'february'=>[
					'fabruary',
					'febrary',
					'febraury',
					'februaury',
					'februrary',
					'februray',
					'februsry',
					'febuary',
					'feburary',
					'feburuary',
					'ferbruary',
					'ferbuary',
					'ferburary',
				],
				'feculence'=>[
					'feculance',
				],
				'fed'=>[
					'feeded',
				],
				'federacy'=>[
					'federasy',
				],
				'federally'=>[
					'federaly',
				],
				'federated'=>[
					'fed-erated',
				],
				'federatively'=>[
					'federativly',
				],
				'feed'=>[
					'feed feed',
					'feed feed feed',
				],
				'feeing'=>[
					'feieng',
				],
				'feel'=>[
					'feel feel',
					'feel feel feel',
					'fiel',
				],
				'feelings'=>[
					'feeings',
				],
				'feels'=>[
					'fiels',
				],
				'feet'=>[
					'feet feet',
					'feet feet feet',
					'feets',
				],
				'feign'=>[
					'fiegn',
				],
				'feigned'=>[
					'fiegned',
				],
				'feigner'=>[
					'fiegner',
				],
				'feigns'=>[
					'fiegns',
				],
				'feijoa'=>[
					'fiejoa',
				],
				'feijoas'=>[
					'fiejoas',
				],
				'feint'=>[
					'fient',
				],
				'feinted'=>[
					'fiented',
				],
				'feints'=>[
					'fients',
				],
				'feirie'=>[
					'fierie',
				],
				'feist'=>[
					'fiest',
				],
				'feistiness'=>[
					'fiestiness',
				],
				'feistinesses'=>[
					'fiestinesses',
				],
				'feists'=>[
					'fiests',
				],
				'feisty'=>[
					'fiesty',
				],
				'feldspar'=>[
					'feldsper',
				],
				'feldspars'=>[
					'feldspers',
				],
				'feline'=>[
					'felini',
				],
				'felinely'=>[
					'felinly',
				],
				'fell'=>[
					'fell fell',
					'fell fell fell',
					'fel',
				],
				'fella'=>[
					'fela',
				],
				'fellah'=>[
					'fella',
				],
				'fellaheen'=>[
					'fellaeen',
				],
				'fellahin'=>[
					'fellain',
				],
				'fellahs'=>[
					'fellas',
				],
				'feller'=>[
					'feler',
				],
				'fellow'=>[
					'felow',
				],
				'fellowly'=>[
					'fellowally',
					'fellowaly',
					'fellowely',
					'fellowlly',
				],
				'fellowship'=>[
					'felowship',
				],
				'fellowshipped'=>[
					'fellowshiped',
				],
				'fellowshipping'=>[
					'fellowshiping',
				],
				'felly'=>[
					'felally',
					'felaly',
					'fellly',
					'fely',
				],
				'felonious'=>[
					'felonous',
				],
				'feloniously'=>[
					'feloniousally',
					'feloniousaly',
					'feloniousely',
					'feloniouslly',
					'felonously',
				],
				'felspar'=>[
					'felsper',
				],
				'felspars'=>[
					'felspers',
				],
				'felt'=>[
					'feeled',
					'felt felt',
					'felt felt felt',
				],
				'felucca'=>[
					'feluca',
				],
				'feluccas'=>[
					'felucas',
				],
				'feminacy'=>[
					'feminasy',
				],
				'feminazi'=>[
					'feminizi',
				],
				'feminie'=>[
					'feminae',
				],
				'feminine'=>[
					'feminane',
					'feminini',
				],
				'femininely'=>[
					'femininly',
				],
				'feminineness'=>[
					'feminaneness',
				],
				'femininenesses'=>[
					'feminanenesses',
					'feminininesses',
				],
				'femininities'=>[
					'femininaties',
				],
				'femininity'=>[
					'femininaty',
				],
				'feminise'=>[
					'feminase',
				],
				'feminism'=>[
					'feminasm',
				],
				'feminist'=>[
					'feminast',
				],
				'feminity'=>[
					'feminaty',
				],
				'feminization'=>[
					'feminazation',
				],
				'feminizations'=>[
					'feminazations',
				],
				'feminize'=>[
					'feminaze',
				],
				'femme'=>[
					'femne',
				],
				'femmes'=>[
					'femnes',
				],
				'femora'=>[
					'femoura',
				],
				'femoral'=>[
					'femoural',
				],
				'fencible'=>[
					'fencable',
				],
				'fennec'=>[
					'fenec',
				],
				'fennel'=>[
					'fenel',
				],
				'fenny'=>[
					'feny',
				],
				'fentanyl'=>[
					'fantanyl',
				],
				'feodary'=>[
					'feodery',
				],
				'ferine'=>[
					'ferini',
				],
				'ferly'=>[
					'ferally',
					'feraly',
					'ferlly',
				],
				'ferment'=>[
					'fermant',
				],
				'fermentation'=>[
					'fermantation',
				],
				'fermentations'=>[
					'fermantations',
				],
				'fermentative'=>[
					'fermantative',
				],
				'fermé la gueule'=>[
					'ferme la gueule',
					'fermé ta gueule',
				],
				'fernandez'=>[
					'fernadez',
				],
				'ferocious'=>[
					'ferocous',
				],
				'ferociously'=>[
					'ferociousally',
					'ferociousaly',
					'ferociousely',
					'ferociouslly',
					'ferocously',
				],
				'ferrate'=>[
					'ferate',
				],
				'ferredoxin'=>[
					'feredoxin',
				],
				'ferrel'=>[
					'ferel',
				],
				'ferret'=>[
					'feret',
				],
				'ferriage'=>[
					'feriage',
				],
				'ferric'=>[
					'feric',
				],
				'ferricyanide'=>[
					'fericyanide',
				],
				'ferricyanides'=>[
					'fericyanides',
				],
				'ferriferous'=>[
					'feriferous',
				],
				'ferrimagnetic'=>[
					'ferimagnetic',
				],
				'ferrimagnetism'=>[
					'ferimagnetism',
				],
				'ferrimagnetisms'=>[
					'ferimagnetisms',
				],
				'ferrite'=>[
					'ferite',
				],
				'ferritin'=>[
					'feritin',
				],
				'ferrocene'=>[
					'ferocene',
				],
				'ferroconcrete'=>[
					'feroconcrete',
				],
				'ferroconcretes'=>[
					'feroconcretes',
				],
				'ferrocyanide'=>[
					'ferocyanide',
				],
				'ferrocyanides'=>[
					'ferocyanides',
				],
				'ferroelectric'=>[
					'feroelectric',
				],
				'ferroelectrics'=>[
					'feroelectrics',
				],
				'ferromagnesian'=>[
					'feromagnesian',
					'ferromagnesan',
				],
				'ferromagnet'=>[
					'feromagnet',
				],
				'ferromagnetic'=>[
					'feromagnetic',
				],
				'ferromagnetism'=>[
					'feromagnetism',
				],
				'ferromagnetisms'=>[
					'feromagnetisms',
				],
				'ferromanganese'=>[
					'feromanganese',
				],
				'ferromanganeses'=>[
					'feromanganeses',
				],
				'ferrosilicon'=>[
					'ferosilicon',
				],
				'ferrosilicons'=>[
					'ferosilicons',
				],
				'ferrotype'=>[
					'ferotype',
				],
				'ferrous'=>[
					'ferous',
				],
				'ferruginous'=>[
					'feruginous',
				],
				'ferrule'=>[
					'ferule',
				],
				'ferrum'=>[
					'ferum',
				],
				'ferry'=>[
					'fery',
				],
				'ferryboat'=>[
					'feryboat',
				],
				'fertile'=>[
					'furtile',
				],
				'fertilely'=>[
					'fertilly',
				],
				'fervency'=>[
					'fervensy',
				],
				'fervent'=>[
					'ferevent',
					'fervant',
				],
				'fervently'=>[
					'ferventally',
					'ferventaly',
					'ferventely',
					'ferventlly',
				],
				'fescennine'=>[
					'fescenine',
				],
				'fescue'=>[
					'fecsue',
					'fecue',
					'fesue',
				],
				'fess'=>[
					'fes',
				],
				'fesse'=>[
					'fese',
				],
				'festinate'=>[
					'festinite',
				],
				'festinately'=>[
					'festinatly',
				],
				'fetidly'=>[
					'fetidally',
					'fetidaly',
					'fetidely',
					'fetidlly',
				],
				'fetoprotein'=>[
					'fetoprotien',
				],
				'fetoproteins'=>[
					'fetoprotiens',
				],
				'fettuccine'=>[
					'fettuccini',
					'fettucine',
				],
				'fettuccini'=>[
					'fettucini',
				],
				'feuar'=>[
					'feaur',
					'feuer',
				],
				'feuars'=>[
					'feaurs',
				],
				'feud'=>[
					'fued',
				],
				'feudal'=>[
					'fuedal',
				],
				'feudary'=>[
					'feudery',
				],
				'few'=>[
					'few few',
					'few few few',
				],
				'fewer'=>[
					'tewer',
				],
				'feyly'=>[
					'feyally',
					'feyaly',
					'feylly',
				],
				'fiance'=>[
					'fience',
				],
				'fiar'=>[
					'fier',
				],
				'fiasco'=>[
					'fiaco',
					'fiacso',
					'fiaso',
				],
				'fibbed'=>[
					'fibed',
				],
				'fibber'=>[
					'fiber',
				],
				'fiberglass'=>[
					'fiberglas',
				],
				'fibranne'=>[
					'fibrane',
				],
				'fibreglass'=>[
					'fibreglas',
				],
				'fibrillar'=>[
					'fibriller',
				],
				'fibrillation'=>[
					'fibrilation',
				],
				'fibrovascular'=>[
					'fibrovacsular',
					'fibrovacular',
					'fibrovasculer',
					'fibrovasular',
				],
				'fiction'=>[
					'fictin',
				],
				'fictional'=>[
					'ficitional',
					'fictonal',
				],
				'fictionalities'=>[
					'fictionaliteis',
					'fictionalitis',
				],
				'fictionally'=>[
					'ficitionally',
				],
				'fictitious'=>[
					'ficticious',
					'fictious',
					'fictous',
					'fictitous',
				],
				'fictitiously'=>[
					'fictitously',
				],
				'fiddler'=>[
					'fillder',
				],
				'fiddly'=>[
					'fiddally',
					'fiddaly',
					'fiddely',
					'fiddlly',
				],
				'fideism'=>[
					'fidiesm',
				],
				'fideist'=>[
					'fidiest',
				],
				'fidgetinesses'=>[
					'fidgetinisses',
				],
				'fiduciary'=>[
					'fiduciery',
				],
				'fie'=>[
					'fei',
				],
				'fief'=>[
					'feif',
				],
				'fiefdom'=>[
					'feifdom',
					'fifdom',
				],
				'field'=>[
					'feild',
					'field field',
					'field field field',
					'fild',
				],
				'field of'=>[
					'filed of',
				],
				'fielder'=>[
					'feilder',
					'filder',
				],
				'fieldfare'=>[
					'feildfare',
					'fildfare',
				],
				'fields'=>[
					'fileds',
				],
				'fieldstone'=>[
					'feildstone',
					'fildstone',
				],
				'fieldstripped'=>[
					'fieldstriped',
				],
				'fieldstripping'=>[
					'feildstripping',
					'fieldstriping',
					'fildstripping',
				],
				'fieldwork'=>[
					'feildwork',
					'fildwork',
				],
				'fiend'=>[
					'feind',
					'find',
				],
				'fiendish'=>[
					'feindish',
					'findish',
				],
				'fiendishnesses'=>[
					'feindishnesses',
					'findishnesses',
				],
				'fierce'=>[
					'feirce',
					'firce',
				],
				'fiercely'=>[
					'fearcely',
					'fiercly',
				],
				'fiery'=>[
					'feiry',
					'firey',
					'firy',
				],
				'fiesta'=>[
					'feista',
					'fista',
				],
				'fifteen-year-old boy'=>[
					'fifteen year old boy',
				],
				'fifteenth'=>[
					'fifteanth',
				],
				'fifth'=>[
					'fith',
				],
				'fifties'=>[
					'fiftys',
				],
				'fiftieth'=>[
					'fifteith',
					'fiftith',
				],
				'fifty'=>[
					'fify',
					'fil\'ty',
				],
				'fig'=>[
					'fig fig',
					'fig fig fig',
				],
				'fight'=>[
					'fight fight',
					'fight fight fight',
					'figth',
				],
				'fighting'=>[
					'fightings',
				],
				'figment'=>[
					'figmant',
				],
				'figuratively'=>[
					'figurativly',
				],
				'figure'=>[
					'figure figure',
					'figure figure figure',
				],
				'figurehead'=>[
					'figurehed',
				],
				'figurine'=>[
					'figurini',
				],
				'filagreeing'=>[
					'filagreieng',
				],
				'filament'=>[
					'filiament',
					'fillament',
					'filamant',
				],
				'filamentary'=>[
					'filamentery',
				],
				'filar'=>[
					'filer',
				],
				'filarian'=>[
					'filaran',
				],
				'filigreeing'=>[
					'filigreieng',
				],
				'filiopietistic'=>[
					'filiopeitistic',
					'filiopitistic',
				],
				'filipina'=>[
					'fillipina',
				],
				'filipino'=>[
					'fillipino',
					'philipino',
					'philippino',
					'phillipino',
					'phillippino',
				],
				'filipino-occupied'=>[
					'filipino occupied',
				],
				'fill'=>[
					'fill fill',
					'fill fill fill',
					'fil',
				],
				'fillagreeing'=>[
					'fillagreieng',
				],
				'filled'=>[
					'fulled',
				],
				'filler'=>[
					'filer',
				],
				'fillet'=>[
					'filet',
				],
				'filling'=>[
					'filing',
				],
				'fillip'=>[
					'filip',
				],
				'filly'=>[
					'filally',
					'filaly',
					'fillly',
					'fily',
				],
				'filmmaker'=>[
					'filmaker',
					'filmnaker',
				],
				'filmmakers'=>[
					'filmakers',
					'filmnakers',
				],
				'filmmaking'=>[
					'filmaking',
					'filmnaking',
				],
				'filterable'=>[
					'filterible',
				],
				'filtrable'=>[
					'filtrible',
				],
				'finable'=>[
					'finible',
				],
				'finagle'=>[
					'finigle',
				],
				'final'=>[
					'fianl',
					'final final',
					'final final final',
					'finil',
				],
				'finale'=>[
					'finile',
				],
				'finalism'=>[
					'finilism',
				],
				'finalist'=>[
					'finilist',
				],
				'finality'=>[
					'finility',
				],
				'finalize'=>[
					'finilize',
				],
				'finally'=>[
					'fianlly',
					'finaly',
					'finnally',
					'finnaly',
				],
				'finals'=>[
					'finils',
				],
				'finance'=>[
					'finaance',
					'finence',
					'finince',
				],
				'finances'=>[
					'finaances',
				],
				'financial'=>[
					'finaancial',
					'finacial',
					'finanial',
					'finincial',
				],
				'financially'=>[
					'financialy',
				],
				'financier'=>[
					'finacier',
					'financeir',
					'financir',
					'finincier',
				],
				'find'=>[
					'fidn',
					'find find',
					'find find find',
				],
				'find out'=>[
					'findout',
				],
				'fine'=>[
					'fine fine',
					'fine fine fine',
				],
				'fined'=>[
					'finid',
				],
				'finely'=>[
					'fineally',
					'finealy',
					'fineely',
					'finelly',
					'finily',
					'finly',
				],
				'finer'=>[
					'finir',
				],
				'finery'=>[
					'finiry',
				],
				'fines'=>[
					'finis',
				],
				'finesse'=>[
					'finese',
					'finisse',
				],
				'finest'=>[
					'finist',
				],
				'finger'=>[
					'finger finger',
					'finger finger finger',
				],
				'finial'=>[
					'finaal',
				],
				'finialed'=>[
					'finaaled',
				],
				'finials'=>[
					'finaals',
				],
				'finical'=>[
					'finacal',
				],
				'finicalness'=>[
					'finacalness',
				],
				'finicalnesses'=>[
					'finacalnesses',
				],
				'finickin'=>[
					'finackin',
				],
				'finickiness'=>[
					'finackiness',
				],
				'finickinesses'=>[
					'finackinesses',
					'finickinisses',
				],
				'finicking'=>[
					'finacking',
				],
				'finicky'=>[
					'finacky',
				],
				'finikin'=>[
					'finakin',
				],
				'fining'=>[
					'finang',
				],
				'finings'=>[
					'finangs',
				],
				'finis'=>[
					'finas',
				],
				'finises'=>[
					'finases',
				],
				'finish'=>[
					'finish finish',
					'finish finish finish',
					'finash',
				],
				'finished'=>[
					'finnished',
					'finshed',
					'finashed',
				],
				'finisher'=>[
					'finnisher',
					'finasher',
				],
				'finishes'=>[
					'finashes',
				],
				'finite'=>[
					'finate',
				],
				'finitely'=>[
					'finately',
					'finitly',
				],
				'finitenesses'=>[
					'finatenesses',
				],
				'finites'=>[
					'finates',
				],
				'finito'=>[
					'finato',
				],
				'finitude'=>[
					'finatude',
				],
				'finmark'=>[
					'fimark',
					'finark',
				],
				'finned'=>[
					'fined',
				],
				'finnickiest'=>[
					'finickiest',
				],
				'finnish-occupied'=>[
					'finnish occupied',
				],
				'finnmark'=>[
					'finmark',
					'finnark',
				],
				'finnmarks'=>[
					'finmarks',
					'finnarks',
				],
				'finny'=>[
					'finy',
				],
				'finocchio'=>[
					'finochio',
				],
				'finocchios'=>[
					'finochios',
				],
				'fipple'=>[
					'fiple',
				],
				'fire'=>[
					'fire fire',
					'fire fire fire',
				],
				'fire-breathing'=>[
					'firebreathing',
				],
				'firearm'=>[
					'fire arm',
					'firerm',
				],
				'fireball'=>[
					'firebal',
				],
				'firefly'=>[
					'firefally',
					'firefaly',
					'firefely',
					'fireflly',
				],
				'fireguard'=>[
					'firegaurd',
				],
				'firewall'=>[
					'firewal',
				],
				'firry'=>[
					'firy',
				],
				'first'=>[
					'E7irst',
					'first first',
					'first first first',
					'firt',
					'firts',
					'frist',
				],
				'firstly'=>[
					'firstally',
					'firstaly',
					'firstely',
					'firstlly',
				],
				'fisc'=>[
					'fic',
					'fics',
					'fis',
				],
				'fiscal'=>[
					'fical',
					'ficsal',
					'fisal',
				],
				'fiscs'=>[
					'fics',
					'ficss',
					'fiss',
				],
				'fish'=>[
					'fish fish',
					'fish fish fish',
				],
				'fishes'=>[
					'fishs',
				],
				'fission'=>[
					'fision',
				],
				'fissionable'=>[
					'fisionable',
					'fissionible',
				],
				'fissiparous'=>[
					'fisiparous',
					'fissiperous',
				],
				'fissiparousness'=>[
					'fissiperousness',
				],
				'fissure'=>[
					'fisure',
				],
				'fit'=>[
					'fit fit',
					'fit fit fit',
				],
				'fitly'=>[
					'fitally',
					'fitaly',
					'fitlly',
				],
				'fitment'=>[
					'fitmant',
				],
				'fitness'=>[
					'fitnes',
				],
				'five'=>[
					'five five',
					'five five five',
				],
				'fixable'=>[
					'fixible',
				],
				'fixedly'=>[
					'fixedally',
					'fixedaly',
					'fixedely',
					'fixedlly',
				],
				'fixture'=>[
					'fixure',
				],
				'fizzling'=>[
					'fizziling',
				],
				'flabbergast'=>[
					'flabergast',
				],
				'flabbergasted'=>[
					'flabergasted',
				],
				'flabbergasting'=>[
					'flabergasting',
				],
				'flabbergasts'=>[
					'flabergasts',
				],
				'flabbier'=>[
					'flabier',
				],
				'flabbiest'=>[
					'flabiest',
				],
				'flabbily'=>[
					'flabily',
				],
				'flabbiness'=>[
					'flabiness',
				],
				'flabbinesses'=>[
					'flabinesses',
				],
				'flabby'=>[
					'flaby',
				],
				'flaccid'=>[
					'flacid',
				],
				'flaccidities'=>[
					'flacidities',
				],
				'flaccidity'=>[
					'flacidity',
				],
				'flaccidly'=>[
					'flacidly',
				],
				'flagellant'=>[
					'flagellent',
				],
				'flagellantisms'=>[
					'flagellentisms',
				],
				'flagellar'=>[
					'flageller',
				],
				'flagellated'=>[
					'flagelated',
				],
				'flagellation'=>[
					'flagelation',
				],
				'flagged'=>[
					'flaged',
				],
				'flaggiest'=>[
					'flagiest',
				],
				'flagging'=>[
					'flaging',
				],
				'flaggingly'=>[
					'flagingly',
				],
				'flaggings'=>[
					'flagings',
				],
				'flagitious'=>[
					'flagitous',
				],
				'flagitiously'=>[
					'flagitously',
				],
				'flagrance'=>[
					'flagrence',
				],
				'flagrancy'=>[
					'flagransy',
				],
				'flagrant'=>[
					'flagrent',
				],
				'flamboyance'=>[
					'flamboyence',
				],
				'flamboyancy'=>[
					'flamboyansy',
				],
				'flamboyant'=>[
					'flamboyent',
				],
				'flamboyantly'=>[
					'flamboyently',
				],
				'flamingo'=>[
					'flamigo',
				],
				'flammabilities'=>[
					'flammabiliteis',
					'flammabilitis',
					'flamnabilities',
				],
				'flammable'=>[
					'flammible',
					'flamnable',
				],
				'flammables'=>[
					'flamnables',
				],
				'flaneur'=>[
					'flaner',
				],
				'flannel'=>[
					'flanel',
				],
				'flannelette'=>[
					'flanelette',
				],
				'flannelettes'=>[
					'flanelettes',
				],
				'flannelled'=>[
					'flanelled',
				],
				'flannelling'=>[
					'flanelling',
				],
				'flannelmouthed'=>[
					'flanelmouthed',
				],
				'flappable'=>[
					'flapable',
					'flappible',
				],
				'flapper'=>[
					'flaper',
				],
				'flappers'=>[
					'flapers',
				],
				'flappier'=>[
					'flapier',
				],
				'flapping'=>[
					'flaping',
				],
				'flappy'=>[
					'flapy',
				],
				'flat'=>[
					'flat flat',
					'flat flat flat',
				],
				'flat-backed instrument'=>[
					'flat backed instrument',
				],
				'flatcar'=>[
					'flatcer',
				],
				'flattened'=>[
					'flattend',
				],
				'flattery'=>[
					'flattary',
				],
				'flatulence'=>[
					'flatulance',
				],
				'flatulency'=>[
					'flatulensy',
				],
				'flavoprotein'=>[
					'flavoprotien',
				],
				'flavoproteins'=>[
					'flavoprotiens',
				],
				'flawless'=>[
					'flawles',
				],
				'flea'=>[
					'fle',
				],
				'fleahopper'=>[
					'fleaopper',
				],
				'fleahoppers'=>[
					'fleahopers',
					'fleaoppers',
				],
				'fled'=>[
					'fleed',
				],
				'fledge'=>[
					'flege',
				],
				'fledged'=>[
					'fleged',
				],
				'fledges'=>[
					'fleges',
				],
				'fleecy'=>[
					'fleesy',
				],
				'fleeing'=>[
					'fleieng',
				],
				'flehmened'=>[
					'flehmend',
				],
				'fleishig'=>[
					'flieshig',
				],
				'flemish'=>[
					'flemmish',
				],
				'flense'=>[
					'flence',
				],
				'fleshly'=>[
					'fleshally',
					'fleshaly',
					'fleshely',
					'fleshlly',
				],
				'fleury joseph crépin'=>[
					'fleury-joseph crépin',
				],
				'flexibility'=>[
					'flexability',
				],
				'flexible'=>[
					'flexable',
				],
				'flexuose'=>[
					'flexose',
				],
				'flexuous'=>[
					'flexous',
				],
				'flibbertigibbet'=>[
					'flibbertigibet',
				],
				'flied'=>[
					'fleid',
					'flid',
				],
				'flier'=>[
					'fleir',
					'flir',
				],
				'flies'=>[
					'fleis',
					'flys',
					'flis',
				],
				'flightinesses'=>[
					'flightinisses',
				],
				'flimflammeries'=>[
					'flimflammereis',
					'flimflammeris',
					'flimflamneries',
				],
				'flimsy'=>[
					'flimcy',
				],
				'flipflopping'=>[
					'flipfloping',
				],
				'flippancy'=>[
					'flippansy',
				],
				'flippant'=>[
					'flipant',
					'flippent',
				],
				'flipper'=>[
					'fliper',
				],
				'flippy'=>[
					'flipy',
				],
				'flirtatious'=>[
					'flirtatous',
				],
				'flirtatiously'=>[
					'flirtatiousally',
					'flirtatiousaly',
					'flirtatiousely',
					'flirtatiouslly',
					'flirtatously',
				],
				'flocced'=>[
					'floced',
				],
				'flocci'=>[
					'floci',
				],
				'floccing'=>[
					'flocing',
				],
				'floccose'=>[
					'flocose',
				],
				'flocculant'=>[
					'flocculent',
					'floculant',
				],
				'flocculants'=>[
					'floculants',
				],
				'flocculate'=>[
					'floculate',
				],
				'flocculated'=>[
					'floculated',
				],
				'flocculates'=>[
					'floculates',
				],
				'flocculating'=>[
					'floculating',
				],
				'flocculation'=>[
					'floculation',
				],
				'flocculations'=>[
					'floculations',
				],
				'flocculator'=>[
					'floculator',
				],
				'flocculators'=>[
					'floculators',
				],
				'floccule'=>[
					'flocule',
				],
				'flocculent'=>[
					'floculent',
				],
				'floccules'=>[
					'flocules',
				],
				'flocculi'=>[
					'floculi',
				],
				'flocculus'=>[
					'floculus',
				],
				'floccus'=>[
					'flocus',
				],
				'floggable'=>[
					'flogable',
				],
				'floggings'=>[
					'flogings',
				],
				'floor'=>[
					'floor floor',
					'floor floor floor',
				],
				'floosy'=>[
					'floocy',
				],
				'floppinesses'=>[
					'flopinesses',
				],
				'floppy'=>[
					'flopy',
				],
				'florence'=>[
					'florance',
				],
				'florescence'=>[
					'florecence',
					'florecsence',
					'florescance',
					'floresence',
				],
				'florescences'=>[
					'florecences',
					'florecsences',
					'floresences',
				],
				'florida'=>[
					'florda',
				],
				'floss'=>[
					'flos',
				],
				'flossy'=>[
					'floscy',
					'flosy',
				],
				'flotation'=>[
					'floatation',
				],
				'flotilla'=>[
					'floatilla',
					'flotila',
				],
				'flotillas'=>[
					'floatillas',
				],
				'flouncy'=>[
					'flounsy',
				],
				'flourish'=>[
					'fluorish',
				],
				'flourishing'=>[
					'florishing',
					'fourlishing',
				],
				'flow'=>[
					'flow flow',
					'flow flow flow',
				],
				'flower'=>[
					'flower flower',
					'flower flower flower',
				],
				'flowerinesses'=>[
					'flowerinisses',
				],
				'flown'=>[
					'flewn',
				],
				'flubbers'=>[
					'flubers',
				],
				'flubbing'=>[
					'flubing',
				],
				'fluctuate'=>[
					'fluxuate',
					'fluctaute',
				],
				'fluctuating'=>[
					'fluctauting',
				],
				'fluctuation'=>[
					'fluctaution',
				],
				'fluctuational'=>[
					'fluctautional',
				],
				'fluency'=>[
					'fluensy',
				],
				'fluent'=>[
					'fluant',
				],
				'fluently'=>[
					'fluentally',
					'fluentaly',
					'fluentely',
					'fluentlly',
				],
				'fluidly'=>[
					'fluidally',
					'fluidaly',
					'fluidely',
					'fluidlly',
				],
				'flummeries'=>[
					'flumneries',
				],
				'flummery'=>[
					'flumnery',
				],
				'flummox'=>[
					'flumnox',
				],
				'flummoxing'=>[
					'flumnoxing',
				],
				'fluor'=>[
					'flor',
				],
				'fluorene'=>[
					'florene',
				],
				'fluorenes'=>[
					'florenes',
				],
				'fluoresce'=>[
					'floresce',
					'fluorece',
					'fluorecse',
					'fluorese',
				],
				'fluoresced'=>[
					'floresced',
				],
				'fluorescein'=>[
					'florescein',
					'fluorecein',
					'fluorecsein',
					'fluorescien',
					'fluoresein',
				],
				'fluoresceins'=>[
					'floresceins',
					'fluoreceins',
					'fluorecseins',
					'fluoresciens',
					'fluoreseins',
				],
				'fluorescence'=>[
					'flourescence',
					'florescence',
					'fluorecence',
					'fluorecsence',
					'fluorescance',
					'fluoresence',
				],
				'fluorescences'=>[
					'florescences',
				],
				'fluorescent'=>[
					'flourescent',
					'florescent',
					'fluorecent',
					'fluorecsent',
					'fluorescant',
					'fluoresent',
				],
				'fluorescents'=>[
					'florescents',
					'fluorecents',
					'fluorecsents',
					'fluoresents',
				],
				'fluorescer'=>[
					'florescer',
				],
				'fluorescers'=>[
					'florescers',
				],
				'fluoresces'=>[
					'floresces',
				],
				'fluorescing'=>[
					'florescing',
				],
				'fluoric'=>[
					'floric',
				],
				'fluorid'=>[
					'florid',
				],
				'fluoridate'=>[
					'floridate',
				],
				'fluoridated'=>[
					'floridated',
				],
				'fluoridates'=>[
					'floridates',
				],
				'fluoridating'=>[
					'floridating',
				],
				'fluoridation'=>[
					'floridation',
				],
				'fluoridations'=>[
					'floridations',
				],
				'fluoride'=>[
					'floride',
					'flouride',
				],
				'fluorides'=>[
					'florides',
				],
				'fluorids'=>[
					'florids',
				],
				'fluorimeter'=>[
					'florimeter',
				],
				'fluorimeters'=>[
					'florimeters',
				],
				'fluorimetric'=>[
					'florimetric',
				],
				'fluorimetries'=>[
					'florimetries',
				],
				'fluorimetry'=>[
					'florimetry',
				],
				'fluorin'=>[
					'florin',
				],
				'fluorinate'=>[
					'florinate',
					'fluorinite',
				],
				'fluorinated'=>[
					'florinated',
				],
				'fluorinates'=>[
					'florinates',
				],
				'fluorinating'=>[
					'florinating',
				],
				'fluorination'=>[
					'florination',
					'fluorinition',
				],
				'fluorinations'=>[
					'florinations',
				],
				'fluorine'=>[
					'flourine',
					'florine',
					'fluorini',
				],
				'fluorines'=>[
					'florines',
				],
				'fluorins'=>[
					'florins',
				],
				'fluorite'=>[
					'florite',
				],
				'fluorites'=>[
					'florites',
				],
				'fluorocarbon'=>[
					'florocarbon',
				],
				'fluorocarbons'=>[
					'florocarbons',
				],
				'fluorochrome'=>[
					'florochrome',
				],
				'fluorochromes'=>[
					'florochromes',
				],
				'fluorographic'=>[
					'florographic',
				],
				'fluorographies'=>[
					'fluorographeis',
					'florographies',
					'fluorographis',
				],
				'fluorography'=>[
					'florography',
				],
				'fluorometer'=>[
					'florometer',
				],
				'fluorometers'=>[
					'florometers',
				],
				'fluorometric'=>[
					'florometric',
				],
				'fluorometries'=>[
					'florometries',
				],
				'fluorometry'=>[
					'florometry',
				],
				'fluoroscope'=>[
					'floroscope',
					'fluorocope',
					'fluorocsope',
					'fluorosope',
				],
				'fluoroscoped'=>[
					'floroscoped',
					'fluorocoped',
					'fluorocsoped',
					'fluorosoped',
				],
				'fluoroscopes'=>[
					'floroscopes',
					'fluorocopes',
					'fluorocsopes',
					'fluorosopes',
				],
				'fluoroscopic'=>[
					'floroscopic',
					'fluorocopic',
					'fluorocsopic',
					'fluorosopic',
				],
				'fluoroscopies'=>[
					'floroscopies',
				],
				'fluoroscoping'=>[
					'floroscoping',
				],
				'fluoroscopist'=>[
					'floroscopist',
				],
				'fluoroscopists'=>[
					'floroscopists',
					'fluorocopists',
					'fluorocsopists',
					'fluorosopists',
				],
				'fluoroscopy'=>[
					'flouroscopy',
					'fluroscopy',
					'floroscopy',
					'fluorocopy',
					'fluorocsopy',
					'fluorosopy',
				],
				'fluoroses'=>[
					'floroses',
				],
				'fluorosis'=>[
					'florosis',
				],
				'fluorotic'=>[
					'florotic',
				],
				'fluorouracil'=>[
					'florouracil',
				],
				'fluorouracils'=>[
					'florouracils',
				],
				'fluors'=>[
					'flors',
				],
				'fluorspar'=>[
					'florspar',
					'fluorsper',
				],
				'fluorspars'=>[
					'florspars',
				],
				'fluoxetine'=>[
					'floxetine',
					'fluoxetini',
				],
				'fluoxetines'=>[
					'floxetines',
				],
				'fluphenazine'=>[
					'fluphenazini',
				],
				'fluphenazines'=>[
					'fluphenazinis',
				],
				'flurry'=>[
					'flury',
				],
				'fluttery'=>[
					'fluttary',
				],
				'fly'=>[
					'fly fly',
					'fly fly fly',
				],
				'flyable'=>[
					'flyible',
				],
				'flysch'=>[
					'flych',
					'flycsh',
					'flysh',
				],
				'flyweight'=>[
					'flywieght',
				],
				'flyweights'=>[
					'flywieghts',
				],
				'fobbed'=>[
					'fobed',
				],
				'focaccia'=>[
					'focacia',
				],
				'focaccias'=>[
					'focacias',
				],
				'focus'=>[
					'focuse',
				],
				'focusing'=>[
					'focuisng',
				],
				'fogginess'=>[
					'foginess',
				],
				'fogginesses'=>[
					'foginesses',
				],
				'foggy'=>[
					'fogy',
				],
				'foible'=>[
					'foable',
				],
				'foined'=>[
					'foinid',
				],
				'foining'=>[
					'foinang',
				],
				'foliage'=>[
					'foilage',
				],
				'foliar'=>[
					'folar',
					'folier',
				],
				'folious'=>[
					'folous',
				],
				'folk group'=>[
					'folkgroup',
				],
				'folk song'=>[
					'folksong',
				],
				'folk songs'=>[
					'folksongs',
				],
				'folkie'=>[
					'folkei',
					'folki',
				],
				'folklore'=>[
					'falklore',
				],
				'folksy'=>[
					'folkcy',
				],
				'follicle'=>[
					'folicle',
				],
				'follicular'=>[
					'folicular',
					'folliculer',
				],
				'folliculitis'=>[
					'foliculitis',
				],
				'follow'=>[
					'follow follow',
					'follow follow follow',
					'folow',
				],
				'followed'=>[
					'follewed',
					'folowed',
				],
				'followed suit'=>[
					'followed suite',
				],
				'follower'=>[
					'folower',
				],
				'followership'=>[
					'folowership',
				],
				'following'=>[
					'follovving',
					'followin',
					'folowing',
				],
				'follows'=>[
					'folows',
				],
				'followup'=>[
					'followup-up',
				],
				'folly'=>[
					'folally',
					'folaly',
					'follly',
					'foly',
				],
				'fomalhaut'=>[
					'formalhaut',
				],
				'foment'=>[
					'fomant',
				],
				'fondant'=>[
					'fondent',
				],
				'fondants'=>[
					'fondents',
				],
				'fondness'=>[
					'fondnes',
				],
				'fontina'=>[
					'fontini',
				],
				'food'=>[
					'food food',
					'food food food',
				],
				'foodie'=>[
					'foodei',
					'foodi',
				],
				'foolhardiness'=>[
					'foolhardiniss',
				],
				'foolhardinesses'=>[
					'foolhardinisses',
				],
				'foolish'=>[
					'oolish',
				],
				'foolscap'=>[
					'foolcap',
					'foolcsap',
					'foolsap',
				],
				'foot'=>[
					'foot foot',
					'foot foot foot',
				],
				'footage'=>[
					'fottage',
				],
				'football'=>[
					'footbal',
				],
				'footdragger'=>[
					'footdrager',
				],
				'footdraggers'=>[
					'footdragers',
				],
				'footgear'=>[
					'footgeer',
				],
				'foothill'=>[
					'foothil',
				],
				'footnote'=>[
					'footenote',
				],
				'footsie'=>[
					'footsei',
					'footsi',
				],
				'footslogged'=>[
					'footsloged',
				],
				'footslogger'=>[
					'footsloger',
				],
				'footsloggers'=>[
					'footslogers',
				],
				'footslogging'=>[
					'footsloging',
				],
				'footsy'=>[
					'footcy',
				],
				'footwall'=>[
					'footwal',
				],
				'footwear'=>[
					'footware',
					'footweer',
					'footwer',
				],
				'foppery'=>[
					'fopery',
				],
				'foppish'=>[
					'fopish',
				],
				'foppishnesses'=>[
					'fopishnesses',
				],
				'for'=>[
					'fo',
					'foor',
					'for for',
					'for for for',
				],
				'for the'=>[
					'fo the',
					'forthe',
					'fot the',
					'fro the',
					'ofr the',
				],
				'forage'=>[
					'foage',
				],
				'foraged'=>[
					'foaged',
				],
				'forager'=>[
					'foager',
				],
				'foragers'=>[
					'foagers',
				],
				'forages'=>[
					'foages',
				],
				'foraging'=>[
					'foaging',
				],
				'foram'=>[
					'foam',
				],
				'foramen'=>[
					'foamen',
				],
				'foramens'=>[
					'foamens',
				],
				'foramina'=>[
					'foamina',
					'foramini',
				],
				'foraminifer'=>[
					'foaminifer',
					'foraminafer',
				],
				'foraminifera'=>[
					'foaminifera',
					'foraminafera',
				],
				'foraminiferal'=>[
					'foaminiferal',
					'foraminaferal',
				],
				'foraminiferan'=>[
					'foaminiferan',
					'foraminaferan',
				],
				'foraminiferans'=>[
					'foaminiferans',
					'foraminaferans',
				],
				'foraminifers'=>[
					'foaminifers',
					'foraminafers',
				],
				'foraminous'=>[
					'foaminous',
				],
				'forams'=>[
					'foams',
				],
				'foray'=>[
					'foay',
				],
				'forayed'=>[
					'foayed',
				],
				'forayer'=>[
					'foayer',
				],
				'forayers'=>[
					'foayers',
				],
				'foraying'=>[
					'foaying',
				],
				'forays'=>[
					'foays',
				],
				'forbad'=>[
					'forebad',
					'fobad',
				],
				'forbade'=>[
					'forbidded',
					'forbode',
					'forebade',
					'fobade',
				],
				'forbare'=>[
					'fobare',
				],
				'forbear'=>[
					'fobear',
					'forbeer',
				],
				'forbearance'=>[
					'fobearance',
					'forbearence',
					'forberance',
				],
				'forbearances'=>[
					'fobearances',
				],
				'forbearers'=>[
					'fobearers',
				],
				'forbearing'=>[
					'fobearing',
				],
				'forbears'=>[
					'fobears',
				],
				'forbid'=>[
					'forebid',
					'fobid',
				],
				'forbidal'=>[
					'fobidal',
				],
				'forbiddance'=>[
					'fobiddance',
					'forbiddence',
				],
				'forbiddances'=>[
					'fobiddances',
				],
				'forbidden'=>[
					'forebidden',
					'fobidden',
				],
				'forbidders'=>[
					'fobidders',
				],
				'forbidding'=>[
					'fobidding',
				],
				'forbiddingly'=>[
					'fobiddingly',
				],
				'forbids'=>[
					'fobids',
				],
				'forbode'=>[
					'fobode',
				],
				'forboded'=>[
					'foboded',
				],
				'forbodes'=>[
					'fobodes',
				],
				'forbore'=>[
					'fobore',
				],
				'forborne'=>[
					'foborne',
				],
				'forbs'=>[
					'fobs',
				],
				'forby'=>[
					'foby',
				],
				'forbye'=>[
					'fobye',
				],
				'force'=>[
					'force force',
					'force force force',
					'foce',
				],
				'forced'=>[
					'foced',
				],
				'forcedly'=>[
					'focedly',
				],
				'forceful'=>[
					'foceful',
				],
				'forcefully'=>[
					'focefully',
				],
				'forcefulness'=>[
					'focefulness',
				],
				'forcefulnesses'=>[
					'focefulnesses',
				],
				'forcemeat'=>[
					'focemeat',
				],
				'forcemeats'=>[
					'focemeats',
				],
				'forceps'=>[
					'foreceps',
					'foceps',
				],
				'forcepslike'=>[
					'focepslike',
				],
				'forcer'=>[
					'focer',
				],
				'forcers'=>[
					'focers',
				],
				'forces'=>[
					'focres',
					'orces',
					'foces',
				],
				'forcible'=>[
					'focible',
					'forcable',
				],
				'forcibleness'=>[
					'focibleness',
				],
				'forciblenesses'=>[
					'fociblenesses',
				],
				'forcing'=>[
					'focing',
				],
				'forded'=>[
					'foded',
				],
				'fordid'=>[
					'fodid',
				],
				'fording'=>[
					'foding',
				],
				'fordo'=>[
					'fodo',
				],
				'fordoes'=>[
					'fodoes',
				],
				'fordone'=>[
					'fodone',
				],
				'fords'=>[
					'fods',
				],
				'forearm'=>[
					'foearm',
					'forerm',
				],
				'forearming'=>[
					'foearming',
				],
				'forearms'=>[
					'foearms',
				],
				'forebay'=>[
					'foebay',
				],
				'forebays'=>[
					'foebays',
				],
				'forebear'=>[
					'foebear',
					'forebeer',
				],
				'forebode'=>[
					'forbode',
					'foebode',
				],
				'foreboders'=>[
					'foeboders',
				],
				'forebodies'=>[
					'foebodies',
				],
				'foreboding'=>[
					'foeboding',
				],
				'forebodingly'=>[
					'foebodingly',
				],
				'forebodingness'=>[
					'foebodingness',
				],
				'forebodings'=>[
					'foebodings',
				],
				'forebrain'=>[
					'foebrain',
				],
				'forebrains'=>[
					'foebrains',
				],
				'foreby'=>[
					'foeby',
				],
				'forebye'=>[
					'foebye',
				],
				'forecaddie'=>[
					'forecaddei',
					'foecaddie',
					'forecaddi',
				],
				'forecaddies'=>[
					'foecaddies',
				],
				'forecast'=>[
					'forcast',
					'foecast',
				],
				'forecastable'=>[
					'foecastable',
				],
				'forecasted'=>[
					'forcasted',
					'foecasted',
				],
				'forecaster'=>[
					'foecaster',
				],
				'forecasters'=>[
					'foecasters',
				],
				'forecasting'=>[
					'forcasting',
					'foecasting',
				],
				'forecastle'=>[
					'foecastle',
				],
				'forecastles'=>[
					'foecastles',
				],
				'forecheck'=>[
					'foecheck',
				],
				'forechecked'=>[
					'foechecked',
				],
				'forechecker'=>[
					'foechecker',
				],
				'forecheckers'=>[
					'foecheckers',
				],
				'forechecking'=>[
					'foechecking',
				],
				'forechecks'=>[
					'foechecks',
				],
				'foreclose'=>[
					'forclose',
					'foeclose',
				],
				'foreclosed'=>[
					'foeclosed',
				],
				'forecloses'=>[
					'foecloses',
				],
				'foreclosing'=>[
					'foeclosing',
				],
				'foreclosure'=>[
					'forclosure',
					'foeclosure',
				],
				'foreclosures'=>[
					'foeclosures',
				],
				'forecourt'=>[
					'foecourt',
				],
				'forecourts'=>[
					'foecourts',
				],
				'foredating'=>[
					'foedating',
				],
				'foredeck'=>[
					'foedeck',
				],
				'foredid'=>[
					'foedid',
				],
				'foredo'=>[
					'foedo',
				],
				'foredoes'=>[
					'foedoes',
				],
				'foredone'=>[
					'foedone',
				],
				'foredoom'=>[
					'foedoom',
				],
				'foredoomed'=>[
					'foedoomed',
				],
				'foredooming'=>[
					'foedooming',
				],
				'foreface'=>[
					'foeface',
				],
				'forefather'=>[
					'foefather',
				],
				'forefathers'=>[
					'foefathers',
				],
				'forefeel'=>[
					'foefeel',
				],
				'forefeeling'=>[
					'foefeeling',
				],
				'forefeet'=>[
					'foefeet',
				],
				'forefelt'=>[
					'foefelt',
				],
				'forefend'=>[
					'foefend',
				],
				'forefended'=>[
					'foefended',
				],
				'forefending'=>[
					'foefending',
				],
				'forefinger'=>[
					'foefinger',
				],
				'forefingers'=>[
					'foefingers',
				],
				'forefoot'=>[
					'foefoot',
				],
				'forefront'=>[
					'foefront',
				],
				'forefronts'=>[
					'foefronts',
				],
				'foregather'=>[
					'foegather',
				],
				'foregathered'=>[
					'foegathered',
				],
				'foregathering'=>[
					'foegathering',
				],
				'foregathers'=>[
					'foegathers',
				],
				'forego'=>[
					'foego',
				],
				'foregoer'=>[
					'foegoer',
				],
				'foregoes'=>[
					'foegoes',
				],
				'foregoing'=>[
					'foegoing',
				],
				'foregone'=>[
					'foegone',
				],
				'foreground'=>[
					'foeground',
				],
				'foregrounded'=>[
					'foegrounded',
				],
				'foregrounding'=>[
					'foegrounding',
				],
				'foregrounds'=>[
					'foegrounds',
				],
				'foregut'=>[
					'foegut',
				],
				'foreguts'=>[
					'foeguts',
				],
				'forehand'=>[
					'foehand',
				],
				'forehanded'=>[
					'foehanded',
				],
				'forehandedly'=>[
					'foehandedly',
					'forehandedally',
					'forehandedaly',
					'forehandedely',
					'forehandedlly',
				],
				'forehandedness'=>[
					'foehandedness',
				],
				'forehead'=>[
					'forhead',
					'foehead',
					'forehed',
				],
				'forehoof'=>[
					'foehoof',
				],
				'forehooves'=>[
					'foehooves',
				],
				'foreign'=>[
					'foriegn',
					'forign',
					'foeign',
				],
				'foreigner'=>[
					'foriegner',
					'foeigner',
				],
				'foreigners'=>[
					'foeigners',
					'foriegners',
				],
				'foreignism'=>[
					'foeignism',
					'foriegnism',
				],
				'foreignisms'=>[
					'foeignisms',
					'foriegnisms',
				],
				'foreignness'=>[
					'foeignness',
					'foreigness',
					'foriegnness',
				],
				'foreignnesses'=>[
					'foeignnesses',
					'foreignesses',
					'foriegnnesses',
				],
				'forejudge'=>[
					'foejudge',
				],
				'forejudged'=>[
					'foejudged',
				],
				'forejudges'=>[
					'foejudges',
				],
				'forejudging'=>[
					'foejudging',
				],
				'foreknew'=>[
					'foeknew',
				],
				'foreknow'=>[
					'foeknow',
					'forekow',
				],
				'foreknowing'=>[
					'foeknowing',
					'forekowing',
				],
				'foreknowledge'=>[
					'foeknowledge',
					'foreknowlege',
					'forekowledge',
				],
				'foreknowledges'=>[
					'foeknowledges',
					'foreknowleges',
					'forekowledges',
				],
				'foreknown'=>[
					'foeknown',
					'forekown',
				],
				'foreknows'=>[
					'forekows',
				],
				'foreladies'=>[
					'foeladies',
				],
				'forelady'=>[
					'foelady',
				],
				'foreland'=>[
					'foeland',
				],
				'foreleg'=>[
					'foeleg',
				],
				'forelegs'=>[
					'foelegs',
				],
				'forelimb'=>[
					'foelimb',
				],
				'forelock'=>[
					'foelock',
				],
				'forelocked'=>[
					'foelocked',
				],
				'forelocking'=>[
					'foelocking',
				],
				'forelocks'=>[
					'foelocks',
				],
				'foreman'=>[
					'foeman',
				],
				'foremanship'=>[
					'foemanship',
				],
				'foremanships'=>[
					'foemanships',
				],
				'foremast'=>[
					'foemast',
				],
				'foremasts'=>[
					'foemasts',
				],
				'foremen'=>[
					'foemen',
				],
				'foremilk'=>[
					'foemilk',
				],
				'foremilks'=>[
					'foemilks',
				],
				'foremost'=>[
					'formost',
					'foemost',
				],
				'foremother'=>[
					'foemother',
				],
				'foremothers'=>[
					'foemothers',
				],
				'forename'=>[
					'foename',
				],
				'forenamed'=>[
					'foenamed',
				],
				'forenames'=>[
					'foenames',
				],
				'forenoon'=>[
					'foenoon',
				],
				'forenoons'=>[
					'foenoons',
				],
				'forensic'=>[
					'foensic',
				],
				'forensically'=>[
					'foensically',
				],
				'forensics'=>[
					'foensics',
				],
				'foreordain'=>[
					'foeordain',
				],
				'foreordained'=>[
					'foeordained',
				],
				'foreordaining'=>[
					'foeordaining',
					'foreordainang',
				],
				'foreordains'=>[
					'foeordains',
				],
				'foreordination'=>[
					'foeordination',
				],
				'foreordinations'=>[
					'foeordinations',
					'foreordinitions',
				],
				'forepart'=>[
					'foepart',
					'forepert',
				],
				'foreparts'=>[
					'foeparts',
					'foreperts',
				],
				'forepassed'=>[
					'foepassed',
				],
				'forepast'=>[
					'foepast',
				],
				'forepaw'=>[
					'foepaw',
				],
				'forepaws'=>[
					'foepaws',
				],
				'forepeak'=>[
					'foepeak',
				],
				'forepeaks'=>[
					'foepeaks',
				],
				'foreplay'=>[
					'foeplay',
				],
				'foreplays'=>[
					'foeplays',
				],
				'forequarter'=>[
					'foequarter',
					'foreqaurter',
				],
				'forequarters'=>[
					'foequarters',
					'foreqaurters',
				],
				'foreran'=>[
					'foeran',
				],
				'forerank'=>[
					'foerank',
				],
				'foreranks'=>[
					'foeranks',
				],
				'forereach'=>[
					'foereach',
				],
				'forereached'=>[
					'foereached',
				],
				'forereaches'=>[
					'foereaches',
				],
				'forereaching'=>[
					'foereaching',
				],
				'forerun'=>[
					'foerun',
				],
				'forerunner'=>[
					'for-runner',
					'forrunner',
					'forunner',
					'foerunner',
					'foreruner',
				],
				'forerunners'=>[
					'forrunners',
					'foerunners',
					'foreruners',
				],
				'forerunning'=>[
					'foerunning',
					'foreruning',
				],
				'foreruns'=>[
					'foeruns',
				],
				'fores'=>[
					'foes',
				],
				'foresaid'=>[
					'foesaid',
				],
				'foresail'=>[
					'foesail',
				],
				'foresaw'=>[
					'forsaw',
					'foesaw',
				],
				'foresee'=>[
					'forsee',
					'foesee',
				],
				'foreseeability'=>[
					'foeseeability',
					'foreseebility',
				],
				'foreseeable'=>[
					'forseeable',
					'foeseeable',
				],
				'foreseeing'=>[
					'foeseeing',
					'foreseieng',
				],
				'foreseen'=>[
					'forseen',
					'foeseen',
				],
				'foreseer'=>[
					'foeseer',
				],
				'foresees'=>[
					'foesees',
				],
				'foreshadow'=>[
					'forshadow',
					'foeshadow',
				],
				'foreshadowed'=>[
					'foeshadowed',
				],
				'foreshadower'=>[
					'foeshadower',
				],
				'foreshadowers'=>[
					'foeshadowers',
				],
				'foreshadowing'=>[
					'foeshadowing',
				],
				'foreshadows'=>[
					'foeshadows',
				],
				'foreshank'=>[
					'foeshank',
				],
				'foreshanks'=>[
					'foeshanks',
				],
				'foresheet'=>[
					'foesheet',
				],
				'foresheets'=>[
					'foesheets',
				],
				'foreshock'=>[
					'foeshock',
				],
				'foreshocks'=>[
					'foeshocks',
				],
				'foreshore'=>[
					'forshore',
					'foeshore',
				],
				'foreshores'=>[
					'foeshores',
				],
				'foreshorten'=>[
					'foeshorten',
				],
				'foreshortened'=>[
					'foeshortened',
					'foreshortend',
				],
				'foreshortening'=>[
					'foeshortening',
				],
				'foreshortens'=>[
					'foeshortens',
				],
				'foreshow'=>[
					'foeshow',
				],
				'foreshowed'=>[
					'foeshowed',
				],
				'foreshowing'=>[
					'foeshowing',
				],
				'foreshown'=>[
					'foeshown',
				],
				'foreside'=>[
					'foeside',
				],
				'foresight'=>[
					'forsight',
					'foesight',
				],
				'foresighted'=>[
					'foesighted',
				],
				'foresightedly'=>[
					'foesightedly',
				],
				'foresightedness'=>[
					'foesightedness',
				],
				'foresightful'=>[
					'foesightful',
				],
				'foresights'=>[
					'foesights',
				],
				'foreskin'=>[
					'foeskin',
				],
				'forespake'=>[
					'foespake',
				],
				'forespeak'=>[
					'foespeak',
				],
				'forespeaking'=>[
					'foespeaking',
				],
				'forespeaks'=>[
					'foespeaks',
				],
				'forespoke'=>[
					'foespoke',
				],
				'forespoken'=>[
					'foespoken',
				],
				'forest'=>[
					'forest forest',
					'forest forest forest',
					'forrest',
					'foest',
				],
				'forestage'=>[
					'foestage',
				],
				'forestages'=>[
					'foestages',
				],
				'forestall'=>[
					'forstall',
					'foestall',
					'forestal',
				],
				'forestalled'=>[
					'foestalled',
				],
				'forestaller'=>[
					'foestaller',
				],
				'forestallers'=>[
					'foestallers',
				],
				'forestalling'=>[
					'foestalling',
				],
				'forestallment'=>[
					'foestallment',
					'forestallmant',
				],
				'forestallments'=>[
					'foestallments',
				],
				'forestalls'=>[
					'foestalls',
				],
				'forestation'=>[
					'foestation',
				],
				'forestations'=>[
					'foestations',
				],
				'forestay'=>[
					'foestay',
				],
				'forestays'=>[
					'foestays',
				],
				'forestaysail'=>[
					'foestaysail',
				],
				'forestaysails'=>[
					'foestaysails',
				],
				'forester'=>[
					'foester',
				],
				'foresters'=>[
					'foesters',
				],
				'forestial'=>[
					'foestial',
				],
				'foresting'=>[
					'foesting',
				],
				'forestland'=>[
					'foestland',
				],
				'forestlands'=>[
					'foestlands',
				],
				'forestries'=>[
					'foestries',
				],
				'forestry'=>[
					'foestry',
				],
				'forests'=>[
					'foests',
				],
				'foreswear'=>[
					'foeswear',
					'foresweer',
				],
				'foreswearing'=>[
					'foeswearing',
				],
				'foreswears'=>[
					'foeswears',
				],
				'foreswore'=>[
					'foeswore',
				],
				'foresworn'=>[
					'foesworn',
				],
				'foretaste'=>[
					'foetaste',
				],
				'foretasted'=>[
					'foetasted',
				],
				'foretastes'=>[
					'foetastes',
				],
				'foretasting'=>[
					'foetasting',
				],
				'foreteeth'=>[
					'foeteeth',
				],
				'foretell'=>[
					'fortell',
					'foetell',
				],
				'foreteller'=>[
					'foeteller',
				],
				'foretellers'=>[
					'foetellers',
				],
				'foretelling'=>[
					'foetelling',
				],
				'foretells'=>[
					'foetells',
				],
				'forethought'=>[
					'foethought',
				],
				'forethoughtful'=>[
					'foethoughtful',
				],
				'forethoughts'=>[
					'foethoughts',
				],
				'foretimes'=>[
					'foetimes',
				],
				'foretoken'=>[
					'foetoken',
				],
				'foretokened'=>[
					'foetokened',
					'foretokend',
				],
				'foretokening'=>[
					'foetokening',
				],
				'foretokens'=>[
					'foetokens',
				],
				'foretold'=>[
					'foetold',
				],
				'foretooth'=>[
					'foetooth',
				],
				'foretop'=>[
					'foetop',
				],
				'foretopman'=>[
					'foetopman',
				],
				'foretopmen'=>[
					'foetopmen',
				],
				'forever'=>[
					'foever',
				],
				'forevermore'=>[
					'foevermore',
					'forevermoure',
				],
				'foreverness'=>[
					'foeverness',
				],
				'forevernesses'=>[
					'foevernesses',
				],
				'forewarn'=>[
					'forwarn',
					'foewarn',
				],
				'forewarned'=>[
					'foewarned',
				],
				'forewarning'=>[
					'foewarning',
				],
				'forewarns'=>[
					'foewarns',
				],
				'forewent'=>[
					'foewent',
				],
				'forewing'=>[
					'foewing',
				],
				'forewings'=>[
					'foewings',
				],
				'forewoman'=>[
					'foewoman',
				],
				'forewomen'=>[
					'foewomen',
				],
				'foreword'=>[
					'foreward',
					'forword',
					'foeword',
				],
				'forewords'=>[
					'foewords',
				],
				'foreworn'=>[
					'foeworn',
				],
				'foreyard'=>[
					'foeyard',
				],
				'foreyards'=>[
					'foeyards',
				],
				'forfeit'=>[
					'forefeit',
					'forefiet',
					'forfiet',
					'fofeit',
				],
				'forfeitable'=>[
					'fofeitable',
					'forfietable',
				],
				'forfeited'=>[
					'fofeited',
				],
				'forfeiter'=>[
					'fofeiter',
				],
				'forfeiters'=>[
					'fofeiters',
					'forfieters',
				],
				'forfeiting'=>[
					'fofeiting',
					'forfieting',
				],
				'forfeiture'=>[
					'forefieture',
					'forfieture',
					'fofeiture',
				],
				'forfeitures'=>[
					'fofeitures',
					'forfietures',
				],
				'forfend'=>[
					'fofend',
				],
				'forfended'=>[
					'fofended',
				],
				'forfending'=>[
					'fofending',
				],
				'forficate'=>[
					'foficate',
				],
				'forgat'=>[
					'fogat',
				],
				'forgather'=>[
					'fogather',
				],
				'forgathered'=>[
					'fogathered',
				],
				'forgathering'=>[
					'fogathering',
				],
				'forgathers'=>[
					'fogathers',
				],
				'forgave'=>[
					'fogave',
				],
				'forge'=>[
					'foge',
				],
				'forgeabilities'=>[
					'forgeabiliteis',
					'fogeabilities',
					'forgeabilitis',
					'forgebilities',
				],
				'forgeability'=>[
					'fogeability',
				],
				'forgeable'=>[
					'fogeable',
				],
				'forged'=>[
					'foged',
				],
				'forger'=>[
					'foger',
				],
				'forgeries'=>[
					'fogeries',
				],
				'forgers'=>[
					'fogers',
				],
				'forgery'=>[
					'fogery',
				],
				'forges'=>[
					'foges',
				],
				'forget'=>[
					'foreget',
					'foget',
				],
				'forgetful'=>[
					'fogetful',
				],
				'forgetfully'=>[
					'fogetfully',
				],
				'forgetfulness'=>[
					'fogetfulness',
				],
				'forgetfulnesses'=>[
					'fogetfulnesses',
				],
				'forgetive'=>[
					'fogetive',
				],
				'forgets'=>[
					'fogets',
				],
				'forgettable'=>[
					'fogettable',
					'forgettible',
				],
				'forgetter'=>[
					'fogetter',
				],
				'forgetters'=>[
					'fogetters',
				],
				'forgetting'=>[
					'fogetting',
				],
				'forging'=>[
					'foging',
				],
				'forgivable'=>[
					'fogivable',
				],
				'forgivably'=>[
					'fogivably',
				],
				'forgive'=>[
					'foregive',
					'fogive',
				],
				'forgiveness'=>[
					'fogiveness',
					'forgivenes',
				],
				'forgivenesses'=>[
					'fogivenesses',
				],
				'forgivers'=>[
					'fogivers',
				],
				'forgiving'=>[
					'fogiving',
				],
				'forgivingly'=>[
					'fogivingly',
				],
				'forgivingness'=>[
					'fogivingness',
				],
				'forgivingnesses'=>[
					'fogivingnesses',
				],
				'forgo'=>[
					'forego',
					'forgoe',
					'fogo',
				],
				'forgoer'=>[
					'fogoer',
				],
				'forgoes'=>[
					'fogoes',
				],
				'forgoing'=>[
					'foregoing',
				],
				'forgone'=>[
					'fogone',
				],
				'forgot'=>[
					'fogot',
				],
				'forgotten'=>[
					'fogotten',
				],
				'forint'=>[
					'foint',
				],
				'forints'=>[
					'foints',
				],
				'forjudge'=>[
					'fojudge',
				],
				'forjudged'=>[
					'fojudged',
				],
				'forjudges'=>[
					'fojudges',
				],
				'forjudging'=>[
					'fojudging',
				],
				'forkball'=>[
					'fokball',
				],
				'forkballs'=>[
					'fokballs',
				],
				'forked'=>[
					'foked',
				],
				'forker'=>[
					'foker',
				],
				'forkers'=>[
					'fokers',
				],
				'forkful'=>[
					'fokful',
				],
				'forkier'=>[
					'fokier',
				],
				'forkiness'=>[
					'fokiness',
				],
				'forkinesses'=>[
					'fokinesses',
				],
				'forking'=>[
					'foking',
				],
				'forklift'=>[
					'foklift',
				],
				'forklifted'=>[
					'foklifted',
				],
				'forklifting'=>[
					'foklifting',
				],
				'forklifts'=>[
					'foklifts',
				],
				'forks'=>[
					'foks',
				],
				'forky'=>[
					'foky',
				],
				'forlese'=>[
					'forelese',
				],
				'forlorn'=>[
					'forelorn',
					'folorn',
				],
				'forlorner'=>[
					'folorner',
				],
				'forlornest'=>[
					'folornest',
				],
				'forlornly'=>[
					'folornly',
					'forlornally',
					'forlornaly',
					'forlornely',
					'forlornlly',
				],
				'forlornness'=>[
					'folornness',
					'forlorness',
				],
				'forlornnesses'=>[
					'folornnesses',
					'forlornesses',
				],
				'form'=>[
					'form form',
					'form form form',
				],
				'formabilities'=>[
					'fomabilities',
				],
				'formability'=>[
					'fomability',
				],
				'formal'=>[
					'formall',
					'fomal',
				],
				'formaldehyde'=>[
					'fomaldehyde',
				],
				'formaldehydes'=>[
					'fomaldehydes',
				],
				'formalin'=>[
					'fomalin',
				],
				'formalins'=>[
					'fomalins',
				],
				'formalise'=>[
					'fomalise',
				],
				'formalised'=>[
					'fomalised',
				],
				'formalises'=>[
					'fomalises',
				],
				'formalising'=>[
					'fomalising',
				],
				'formalism'=>[
					'fomalism',
				],
				'formalisms'=>[
					'fomalisms',
				],
				'formalist'=>[
					'fomalist',
				],
				'formalistic'=>[
					'fomalistic',
				],
				'formalists'=>[
					'fomalists',
				],
				'formalities'=>[
					'fomalities',
				],
				'formality'=>[
					'fomality',
				],
				'formalizable'=>[
					'fomalizable',
				],
				'formalization'=>[
					'fomalization',
				],
				'formalizations'=>[
					'fomalizations',
				],
				'formalize'=>[
					'formallize',
					'fomalize',
				],
				'formalized'=>[
					'formallized',
					'fomalized',
				],
				'formalizer'=>[
					'fomalizer',
				],
				'formalizers'=>[
					'fomalizers',
				],
				'formalizes'=>[
					'fomalizes',
				],
				'formalizing'=>[
					'fomalizing',
				],
				'formally'=>[
					'formaly',
				],
				'formalness'=>[
					'fomalness',
				],
				'formalnesses'=>[
					'fomalnesses',
				],
				'formals'=>[
					'fomals',
				],
				'formamide'=>[
					'fomamide',
				],
				'formamides'=>[
					'fomamides',
				],
				'formant'=>[
					'fomant',
					'forment',
				],
				'format'=>[
					'fromat',
					'fomat',
				],
				'formate'=>[
					'fomate',
				],
				'formation'=>[
					'fomation',
				],
				'formative'=>[
					'fomative',
				],
				'formatively'=>[
					'fomatively',
					'formativly',
				],
				'formats'=>[
					'fomats',
				],
				'formatted'=>[
					'formated',
					'fomatted',
				],
				'formatter'=>[
					'fomatter',
				],
				'formatting'=>[
					'formating',
				],
				'forme'=>[
					'fome',
				],
				'formed'=>[
					'fromed',
					'fomed',
				],
				'formee'=>[
					'fomee',
				],
				'former'=>[
					'brmer',
					'fomer',
					'fromer',
				],
				'formerly'=>[
					'fomerly',
					'fromerly',
					'formerally',
					'formeraly',
					'formerely',
					'formerlly',
				],
				'formers'=>[
					'fomers',
				],
				'formes'=>[
					'fomes',
				],
				'formfitting'=>[
					'fomfitting',
				],
				'formful'=>[
					'fomful',
				],
				'formic'=>[
					'fomic',
				],
				'formica'=>[
					'fomica',
				],
				'formicaries'=>[
					'fomicaries',
				],
				'formicary'=>[
					'fomicary',
					'formicery',
				],
				'formidabilities'=>[
					'fomidabilities',
				],
				'formidability'=>[
					'fomidability',
				],
				'formidable'=>[
					'formidiable',
					'fomidable',
					'formidible',
				],
				'formidableness'=>[
					'fomidableness',
				],
				'formidably'=>[
					'fonnidably',
					'fomidably',
					'formidabally',
					'formidabaly',
					'formidabely',
					'formidablly',
				],
				'forming'=>[
					'froming',
					'foming',
				],
				'formless'=>[
					'fomless',
				],
				'formlessly'=>[
					'fomlessly',
				],
				'formlessness'=>[
					'fomlessness',
				],
				'formlessnesses'=>[
					'fomlessnesses',
				],
				'formol'=>[
					'fomol',
				],
				'formols'=>[
					'fomols',
				],
				'forms'=>[
					'foms',
				],
				'formula'=>[
					'forumla',
					'fomula',
				],
				'formulaic'=>[
					'fomulaic',
				],
				'formulaically'=>[
					'fomulaically',
				],
				'formularies'=>[
					'fomularies',
				],
				'formularization'=>[
					'fomularization',
				],
				'formularize'=>[
					'fomularize',
				],
				'formularized'=>[
					'fomularized',
				],
				'formularizer'=>[
					'fomularizer',
				],
				'formularizers'=>[
					'fomularizers',
				],
				'formularizes'=>[
					'fomularizes',
				],
				'formularizing'=>[
					'fomularizing',
				],
				'formulary'=>[
					'fomulary',
					'formulery',
				],
				'formulate'=>[
					'forumlate',
					'fomulate',
				],
				'formulated'=>[
					'fomulated',
				],
				'formulates'=>[
					'fomulates',
				],
				'formulating'=>[
					'fomulating',
				],
				'formulation'=>[
					'fomulation',
				],
				'formulations'=>[
					'fomulations',
				],
				'formulator'=>[
					'fomulator',
				],
				'formulators'=>[
					'fomulators',
				],
				'formulism'=>[
					'fomulism',
				],
				'formulisms'=>[
					'fomulisms',
				],
				'formulist'=>[
					'fomulist',
				],
				'formulists'=>[
					'fomulists',
				],
				'formulize'=>[
					'fomulize',
				],
				'formulized'=>[
					'fomulized',
				],
				'formulizes'=>[
					'fomulizes',
				],
				'formulizing'=>[
					'fomulizing',
				],
				'formwork'=>[
					'fomwork',
				],
				'formworks'=>[
					'fomworks',
				],
				'formyl'=>[
					'fomyl',
				],
				'formyls'=>[
					'fomyls',
				],
				'fornent'=>[
					'fonent',
				],
				'fornicate'=>[
					'fonicate',
				],
				'fornicated'=>[
					'fonicated',
				],
				'fornicates'=>[
					'fonicates',
				],
				'fornicating'=>[
					'fonicating',
				],
				'fornication'=>[
					'fonication',
				],
				'fornications'=>[
					'fonications',
				],
				'fornicator'=>[
					'fonicator',
				],
				'fornicators'=>[
					'fonicators',
				],
				'fornix'=>[
					'fonix',
				],
				'forrader'=>[
					'forader',
				],
				'forrit'=>[
					'forit',
				],
				'forsake'=>[
					'foresake',
					'fosake',
				],
				'forsaken'=>[
					'foresaken',
					'fosaken',
				],
				'forsaker'=>[
					'fosaker',
				],
				'forsakes'=>[
					'fosakes',
				],
				'forsook'=>[
					'foresook',
					'fosook',
				],
				'forsooth'=>[
					'fosooth',
				],
				'forspent'=>[
					'fospent',
				],
				'forswear'=>[
					'foreswear',
					'forsweer',
					'foswear',
				],
				'forswearing'=>[
					'foswearing',
				],
				'forswore'=>[
					'foswore',
				],
				'forsworn'=>[
					'fosworn',
				],
				'forsythia'=>[
					'fosythia',
				],
				'fortalice'=>[
					'fotalice',
				],
				'forte'=>[
					'fote',
				],
				'fortepiano'=>[
					'fotepiano',
				],
				'fortepianos'=>[
					'fotepianos',
				],
				'fortes'=>[
					'fotes',
				],
				'forth'=>[
					'fortb',
					'foth',
				],
				'forthcoming'=>[
					'fothcoming',
				],
				'forthright'=>[
					'fothright',
				],
				'forthrightly'=>[
					'fothrightly',
				],
				'forthrightness'=>[
					'fothrightness',
				],
				'forthrights'=>[
					'fothrights',
				],
				'forthwith'=>[
					'fortwith',
					'fothwith',
				],
				'forties'=>[
					'fortys',
					'fourties',
					'foties',
				],
				'fortieth'=>[
					'forteith',
					'fourtieth',
					'fortith',
					'fotieth',
				],
				'fortification'=>[
					'fotification',
				],
				'fortifications'=>[
					'fotifications',
				],
				'fortified'=>[
					'fortifed',
				],
				'fortify'=>[
					'fotify',
				],
				'fortis'=>[
					'fotis',
				],
				'fortissimo'=>[
					'fotissimo',
				],
				'fortissimos'=>[
					'fotissimos',
				],
				'fortitude'=>[
					'fotitude',
				],
				'fortnight'=>[
					'fotnight',
				],
				'fortnightlies'=>[
					'fotnightlies',
				],
				'fortnightly'=>[
					'fortnightally',
					'fortnightaly',
					'fortnightely',
					'fortnightlly',
					'fotnightly',
				],
				'fortress'=>[
					'fortres',
					'fotress',
				],
				'fortressing'=>[
					'fotressing',
				],
				'fortresslike'=>[
					'fotresslike',
				],
				'forts'=>[
					'fots',
				],
				'fortuitous'=>[
					'fotuitous',
				],
				'fortuitously'=>[
					'fotuitously',
				],
				'fortuitousness'=>[
					'fotuitousness',
				],
				'fortuity'=>[
					'fotuity',
				],
				'fortunate'=>[
					'fotunate',
				],
				'fortunately'=>[
					'fortuately',
					'fortunatly',
					'fotunately',
				],
				'fortunateness'=>[
					'fotunateness',
				],
				'fortunatenesses'=>[
					'fotunatenesses',
				],
				'fortune'=>[
					'fortime',
					'fotune',
				],
				'fortuned'=>[
					'fotuned',
				],
				'fortunes'=>[
					'fotunes',
				],
				'forty'=>[
					'fourty',
					'foty',
				],
				'fortyish'=>[
					'fotyish',
				],
				'forum'=>[
					'foum',
				],
				'forums'=>[
					'foums',
				],
				'forward'=>[
					'foreward',
					'forward forward',
					'forward forward forward',
					'foward',
				],
				'forwarder'=>[
					'fowarder',
				],
				'forwardness'=>[
					'fowardness',
				],
				'forwardnesses'=>[
					'fowardnesses',
				],
				'forwards'=>[
					'fowards',
				],
				'forwent'=>[
					'forewent',
					'fowent',
				],
				'forwhy'=>[
					'fowhy',
				],
				'forworn'=>[
					'foworn',
				],
				'forzandi'=>[
					'fozandi',
				],
				'forzando'=>[
					'fozando',
				],
				'forêt de champ'=>[
					'foret-de-champ',
				],
				'foss'=>[
					'fos',
				],
				'fossa'=>[
					'fosa',
				],
				'fosse'=>[
					'fose',
				],
				'fossil'=>[
					'fosil',
				],
				'fossiliferous'=>[
					'fosiliferous',
				],
				'fought'=>[
					'faught',
					'fighted',
					'fougth',
				],
				'found'=>[
					'foudn',
					'found found',
					'found found found',
				],
				'foundation'=>[
					'fundation',
				],
				'foundationally'=>[
					'foundationalally',
					'foundationalaly',
					'foundationalely',
					'foundationallly',
				],
				'foundries'=>[
					'foundaries',
				],
				'foundry'=>[
					'foundary',
				],
				'fountainhead'=>[
					'fountainhed',
				],
				'fountaining'=>[
					'fountainang',
				],
				'four'=>[
					'foru',
					'four four',
					'four four four',
				],
				'four-year-old boy'=>[
					'four year old boy',
				],
				'fourdrinier'=>[
					'fourdrinaer',
				],
				'fourdriniers'=>[
					'fourdrinaers',
				],
				'fourpence'=>[
					'fourpance',
				],
				'fourpennies'=>[
					'fourpenies',
				],
				'fourpenny'=>[
					'fourpeny',
				],
				'fourragere'=>[
					'fouragere',
				],
				'foursquare'=>[
					'foursqaure',
				],
				'fourteenth'=>[
					'fouteenth',
					'fourteanth',
				],
				'fourth'=>[
					'fourd',
				],
				'fourthly'=>[
					'fourthally',
					'fourthaly',
					'fourthely',
					'fourthlly',
				],
				'foveolar'=>[
					'foveoler',
				],
				'fraction'=>[
					'fraction fraction',
					'fraction fraction fraction',
				],
				'fractious'=>[
					'fractous',
				],
				'fractiously'=>[
					'fractously',
				],
				'fraggings'=>[
					'fragings',
				],
				'fragilely'=>[
					'fragilly',
				],
				'fragment'=>[
					'fragement',
					'fragmant',
				],
				'fragmentarily'=>[
					'fragmantarily',
				],
				'fragmentariness'=>[
					'fragmentariniss',
				],
				'fragmentary'=>[
					'fragmantary',
					'fragmentery',
				],
				'fragmentating'=>[
					'fragmantating',
				],
				'fragmentation'=>[
					'fragmantation',
				],
				'fragmentizing'=>[
					'fragmantizing',
				],
				'fragrance'=>[
					'fragrence',
				],
				'fragrancy'=>[
					'fragransy',
				],
				'fragrant'=>[
					'fragrent',
				],
				'franchise'=>[
					'francihse',
				],
				'franciscan'=>[
					'fransiscan',
				],
				'franciscans'=>[
					'fransiscans',
				],
				'frangibilities'=>[
					'frangibiliteis',
					'frangibilitis',
				],
				'frangible'=>[
					'frangable',
				],
				'frangipanni'=>[
					'frangipani',
				],
				'frankfurt'=>[
					'franfurt',
					'frankfart',
				],
				'frankincense'=>[
					'frankincence',
				],
				'franklinite'=>[
					'franklinate',
				],
				'franklinites'=>[
					'franklinates',
				],
				'frankly'=>[
					'frankally',
					'frankaly',
					'frankely',
					'franklly',
				],
				'frankpledge'=>[
					'frankplege',
				],
				'frankpledges'=>[
					'frankpleges',
				],
				'frantic'=>[
					'frentic',
				],
				'française'=>[
					'francaise',
					'françalse',
				],
				'françois'=>[
					'francois',
				],
				'frappe'=>[
					'frape',
				],
				'frass'=>[
					'fras',
				],
				'fraudulence'=>[
					'fraudulance',
				],
				'fraudulent'=>[
					'fraudulant',
				],
				'fraught'=>[
					'frought',
				],
				'freak'=>[
					'frek',
				],
				'freakishnesses'=>[
					'frekishnesses',
				],
				'fred'=>[
					'ferd',
				],
				'free'=>[
					'free free',
					'free free free',
					'freee',
				],
				'freebie'=>[
					'freebei',
					'freebi',
				],
				'freedom'=>[
					'freesom',
					'treedonl',
				],
				'freehandedly'=>[
					'freehandedally',
					'freehandedaly',
					'freehandedely',
					'freehandedlly',
				],
				'freeing'=>[
					'freieng',
				],
				'freelance'=>[
					'freelence',
				],
				'freely'=>[
					'frely',
				],
				'freight'=>[
					'frieght',
				],
				'freightage'=>[
					'frieghtage',
				],
				'freightages'=>[
					'frieghtages',
				],
				'freighter'=>[
					'frieghter',
				],
				'freighters'=>[
					'frieghters',
				],
				'freighting'=>[
					'frieghting',
				],
				'french'=>[
					'fernch',
					'frecnh',
					'frenc',
				],
				'french-occupied'=>[
					'french occupied',
				],
				'french-speaking canadians'=>[
					'french speaking canadians',
				],
				'frenular'=>[
					'frenuler',
				],
				'frenzied'=>[
					'frenzeid',
					'frenzid',
				],
				'frenziedly'=>[
					'frenziedally',
					'frenziedaly',
					'frenziedely',
					'frenziedlly',
				],
				'frequence'=>[
					'frequance',
				],
				'frequency'=>[
					'frequensy',
				],
				'frequent'=>[
					'freqent',
					'frequant',
				],
				'frequentation'=>[
					'frequantation',
				],
				'frequentative'=>[
					'frequantative',
				],
				'frequently'=>[
					'frequantly',
					'frequentally',
					'frequentaly',
					'frequentely',
					'frequentlly',
				],
				'fresco'=>[
					'freco',
					'frecso',
					'freso',
				],
				'fresh'=>[
					'fresb',
					'fresh fresh',
					'fresh fresh fresh',
				],
				'freshened'=>[
					'freshend',
				],
				'friable'=>[
					'friible',
				],
				'friar'=>[
					'frair',
					'frar',
					'frier',
				],
				'friary'=>[
					'friery',
				],
				'fribble'=>[
					'frible',
				],
				'fribbled'=>[
					'fribled',
				],
				'fribbler'=>[
					'fribler',
				],
				'fribblers'=>[
					'friblers',
				],
				'fribbles'=>[
					'fribles',
				],
				'fribbling'=>[
					'fribling',
				],
				'fricasseeing'=>[
					'fricasseieng',
				],
				'frick'=>[
					'fcick',
				],
				'frictionlessly'=>[
					'frictionlessally',
					'frictionlessaly',
					'frictionlessely',
					'frictionlesslly',
				],
				'fried'=>[
					'freid',
					'frid',
				],
				'friend'=>[
					'firend',
					'freind',
					'friend friend',
					'friend friend friend',
					'frind',
				],
				'friendlinesses'=>[
					'friendlinisses',
				],
				'friendly'=>[
					'freindly',
					'friendally',
					'friendaly',
					'friendely',
					'friendlly',
					'frindly',
				],
				'friends'=>[
					'frienda',
					'friens',
				],
				'friendship'=>[
					'firendship',
					'freindship',
					'frindship',
				],
				'frier'=>[
					'freir',
					'frir',
				],
				'fries'=>[
					'freis',
					'fris',
				],
				'frieze'=>[
					'freize',
					'frize',
				],
				'frigging'=>[
					'friging',
				],
				'frightened'=>[
					'frightend',
				],
				'frill'=>[
					'fril',
				],
				'frippery'=>[
					'fripery',
				],
				'friseur'=>[
					'friser',
				],
				'frisson'=>[
					'frison',
				],
				'fritillary'=>[
					'fritillery',
				],
				'frizzly'=>[
					'frizzally',
					'frizzaly',
					'frizzely',
					'frizzlly',
				],
				'frogged'=>[
					'froged',
				],
				'froggiest'=>[
					'frogiest',
				],
				'froggy'=>[
					'frogy',
				],
				'froghopper'=>[
					'froghoper',
				],
				'from'=>[
					'ffrom',
					'fomr',
					'from from',
					'from from from',
					'frrom',
				],
				'from a'=>[
					'fom a',
				],
				'from across the'=>[
					'from the across the',
				],
				'from an'=>[
					'fom an',
				],
				'from the'=>[
					'fom the',
					'from th',
					'fromt he',
					'fromthe',
					'fron the',
				],
				'frondeur'=>[
					'fronder',
				],
				'front'=>[
					'front front',
					'front front front',
				],
				'frontier'=>[
					'fronteir',
					'frontir',
				],
				'frontiersman'=>[
					'fronteirsman',
					'frontirsman',
				],
				'frontispiece'=>[
					'frontispeice',
					'frontpiece',
					'frontspiece',
					'frontispice',
				],
				'frontline'=>[
					'frontlini',
				],
				'frotteur'=>[
					'frotter',
				],
				'frowsy'=>[
					'frowcy',
				],
				'froze'=>[
					'freezed',
					'frozed',
				],
				'frozen'=>[
					'frozed',
				],
				'frozennesses'=>[
					'frozenesses',
				],
				'fructuous'=>[
					'fructous',
				],
				'fruit'=>[
					'friut',
					'fruit fruit',
					'fruit fruit fruit',
				],
				'fruit flies'=>[
					'fruitflies',
				],
				'fruitarian'=>[
					'fruitaran',
				],
				'fruition'=>[
					'fruiton',
					'frution',
				],
				'fruitless'=>[
					'fruitles',
				],
				'fruitlessly'=>[
					'fruitlessally',
					'fruitlessaly',
					'fruitlessely',
					'fruitlesslly',
				],
				'frustrate'=>[
					'fustrate',
				],
				'frustrated'=>[
					'frustated',
				],
				'frustum'=>[
					'frustrum',
				],
				'fryable'=>[
					'fryible',
				],
				'frère ennemi'=>[
					'frere ennemie',
				],
				'fubar'=>[
					'fuber',
				],
				'fubbed'=>[
					'fubed',
				],
				'fubsy'=>[
					'fubcy',
				],
				'fucoxanthin'=>[
					'fucoxenthin',
				],
				'fucoxanthins'=>[
					'fucoxenthins',
				],
				'fugacious'=>[
					'fugacous',
				],
				'fugged'=>[
					'fuged',
				],
				'fuggy'=>[
					'fugy',
				],
				'fugitively'=>[
					'fugitivly',
				],
				'fulfill'=>[
					'fufill',
					'fulfil',
					'fullfil',
					'fullfill',
				],
				'fulfilled'=>[
					'fufill',
					'fufilled',
				],
				'fulfilling'=>[
					'fufilling',
				],
				'fulfillment'=>[
					'lulfilllnellt',
				],
				'fulgently'=>[
					'fulgentally',
					'fulgentaly',
					'fulgentely',
					'fulgentlly',
				],
				'full'=>[
					'full full',
					'full full full',
					'ful',
				],
				'full-time'=>[
					'fulltime',
				],
				'fullback'=>[
					'fulback',
				],
				'fuller'=>[
					'fuler',
				],
				'fullness'=>[
					'fulness',
				],
				'fully'=>[
					'fulally',
					'fulaly',
					'fullly',
					'fuly',
				],
				'fulmar'=>[
					'fulmer',
				],
				'fulminant'=>[
					'fulminent',
					'fulminint',
				],
				'fulminate'=>[
					'fulminite',
				],
				'fumigant'=>[
					'fumigent',
				],
				'fun'=>[
					'fun fun',
					'fun fun fun',
				],
				'function'=>[
					'funtion',
				],
				'functionally'=>[
					'functionaly',
				],
				'functionary'=>[
					'functionery',
				],
				'fundamental'=>[
					'fundametal',
					'fundemental',
					'fundamantal',
				],
				'fundamentalism'=>[
					'fundamantalism',
				],
				'fundamentally'=>[
					'fundamentaly',
				],
				'funerary'=>[
					'funerery',
				],
				'fungi'=>[
					'funguses',
				],
				'fungible'=>[
					'fungable',
				],
				'funicular'=>[
					'funiculer',
				],
				'funnel'=>[
					'funel',
				],
				'funnelform'=>[
					'funelform',
				],
				'funneling'=>[
					'funeling',
				],
				'funnelled'=>[
					'funelled',
				],
				'funniness'=>[
					'funiness',
				],
				'funninesses'=>[
					'funinesses',
				],
				'funny'=>[
					'funy',
				],
				'funnyman'=>[
					'funyman',
				],
				'furane'=>[
					'fuane',
				],
				'furanes'=>[
					'fuanes',
				],
				'furanose'=>[
					'fuanose',
				],
				'furanoses'=>[
					'fuanoses',
				],
				'furanoside'=>[
					'fuanoside',
				],
				'furanosides'=>[
					'fuanosides',
				],
				'furans'=>[
					'fuans',
				],
				'furazolidone'=>[
					'fuazolidone',
				],
				'furbearer'=>[
					'fubearer',
				],
				'furbearers'=>[
					'fubearers',
				],
				'furbelow'=>[
					'fubelow',
				],
				'furbelowed'=>[
					'fubelowed',
				],
				'furbelowing'=>[
					'fubelowing',
				],
				'furbelows'=>[
					'fubelows',
				],
				'furbish'=>[
					'fubish',
				],
				'furbished'=>[
					'fubished',
				],
				'furbisher'=>[
					'fubisher',
				],
				'furbishers'=>[
					'fubishers',
				],
				'furbishes'=>[
					'fubishes',
				],
				'furbishing'=>[
					'fubishing',
				],
				'furcate'=>[
					'fucate',
				],
				'furcated'=>[
					'fucated',
				],
				'furcately'=>[
					'fucately',
					'furcatly',
				],
				'furcates'=>[
					'fucates',
				],
				'furcating'=>[
					'fucating',
				],
				'furcation'=>[
					'fucation',
				],
				'furcations'=>[
					'fucations',
				],
				'furcraea'=>[
					'fucraea',
				],
				'furcraeas'=>[
					'fucraeas',
				],
				'furcula'=>[
					'fucula',
				],
				'furculae'=>[
					'fuculae',
				],
				'furcular'=>[
					'fucular',
				],
				'furculum'=>[
					'fuculum',
				],
				'furfur'=>[
					'furfu',
				],
				'furfural'=>[
					'furfual',
				],
				'furfurals'=>[
					'furfuals',
				],
				'furfuran'=>[
					'furfuan',
				],
				'furfurans'=>[
					'furfuans',
				],
				'furfures'=>[
					'furfues',
				],
				'furibund'=>[
					'fuibund',
				],
				'furies'=>[
					'fuies',
				],
				'furioso'=>[
					'fuioso',
				],
				'furious'=>[
					'fuious',
					'furous',
				],
				'furiously'=>[
					'fuiously',
					'furously',
				],
				'furlable'=>[
					'fulable',
				],
				'furled'=>[
					'fuled',
				],
				'furler'=>[
					'fuler',
				],
				'furlers'=>[
					'fulers',
				],
				'furless'=>[
					'fuless',
				],
				'furling'=>[
					'fuling',
				],
				'furlong'=>[
					'fulong',
				],
				'furlongs'=>[
					'fulongs',
				],
				'furlough'=>[
					'fulough',
				],
				'furloughed'=>[
					'fuloughed',
				],
				'furloughing'=>[
					'fuloughing',
				],
				'furloughs'=>[
					'fuloughs',
				],
				'furmenties'=>[
					'fumenties',
				],
				'furmenty'=>[
					'fumenty',
				],
				'furmeties'=>[
					'fumeties',
				],
				'furmety'=>[
					'fumety',
				],
				'furmities'=>[
					'fumities',
				],
				'furmity'=>[
					'fumity',
				],
				'furnace'=>[
					'funace',
				],
				'furnaced'=>[
					'funaced',
				],
				'furnaces'=>[
					'funaces',
				],
				'furnacing'=>[
					'funacing',
				],
				'furnish'=>[
					'funish',
				],
				'furnished'=>[
					'funished',
				],
				'furnisher'=>[
					'funisher',
				],
				'furnishers'=>[
					'funishers',
				],
				'furnishes'=>[
					'funishes',
				],
				'furnishing'=>[
					'funishing',
				],
				'furnishings'=>[
					'funishings',
				],
				'furniture'=>[
					'furnature',
					'funiture',
				],
				'furnitures'=>[
					'funitures',
				],
				'furor'=>[
					'furore',
				],
				'furore'=>[
					'fuore',
				],
				'furores'=>[
					'fuores',
				],
				'furors'=>[
					'fuors',
				],
				'furosemide'=>[
					'fuosemide',
				],
				'furosemides'=>[
					'fuosemides',
				],
				'furred'=>[
					'fured',
				],
				'furrier'=>[
					'furier',
				],
				'furrieries'=>[
					'furieries',
				],
				'furriers'=>[
					'furiers',
				],
				'furriery'=>[
					'furiery',
				],
				'furriest'=>[
					'furiest',
				],
				'furrily'=>[
					'furily',
				],
				'furriner'=>[
					'furiner',
				],
				'furriners'=>[
					'furiners',
				],
				'furriness'=>[
					'furiness',
				],
				'furrinesses'=>[
					'furinesses',
				],
				'furring'=>[
					'furing',
				],
				'furrings'=>[
					'furings',
				],
				'furrow'=>[
					'furow',
				],
				'furrowed'=>[
					'furowed',
				],
				'furrower'=>[
					'furower',
				],
				'furrowers'=>[
					'furowers',
				],
				'furrowing'=>[
					'furowing',
				],
				'furrows'=>[
					'furows',
				],
				'furrowy'=>[
					'furowy',
				],
				'furry'=>[
					'fury',
				],
				'further'=>[
					'furhter',
					'furuther',
					'futher',
				],
				'furtherance'=>[
					'furtherence',
					'futherance',
				],
				'furtherances'=>[
					'futherances',
				],
				'furthered'=>[
					'futhered',
				],
				'furtherer'=>[
					'futherer',
				],
				'furtherers'=>[
					'futherers',
				],
				'furthering'=>[
					'futhering',
				],
				'furthermore'=>[
					'farthermore',
					'furhtermore',
					'furthemore',
					'furthrmore',
					'futhermore',
					'furthermoure',
				],
				'furthermost'=>[
					'futhermost',
				],
				'furthers'=>[
					'futhers',
				],
				'furthest'=>[
					'futhest',
				],
				'furtive'=>[
					'futive',
				],
				'furtively'=>[
					'futively',
				],
				'furtiveness'=>[
					'futiveness',
				],
				'furtivenesses'=>[
					'futivenesses',
				],
				'furuncle'=>[
					'fuuncle',
				],
				'furuncles'=>[
					'fuuncles',
				],
				'furunculoses'=>[
					'fuunculoses',
				],
				'furunculosis'=>[
					'fuunculosis',
				],
				'furzes'=>[
					'fuzes',
				],
				'furzier'=>[
					'fuzier',
				],
				'furziest'=>[
					'fuziest',
				],
				'fuse'=>[
					'fuze',
				],
				'fusibilities'=>[
					'fuisbilities',
				],
				'fusibility'=>[
					'fuisbility',
				],
				'fusible'=>[
					'fusable',
				],
				'fusiform'=>[
					'fuisform',
				],
				'fusileer'=>[
					'fuisleer',
				],
				'fusileers'=>[
					'fuisleers',
				],
				'fusilier'=>[
					'fusileir',
					'fuislier',
					'fusilir',
				],
				'fusiliers'=>[
					'fuisliers',
				],
				'fusillade'=>[
					'fuisllade',
				],
				'fusilladed'=>[
					'fuislladed',
				],
				'fusillades'=>[
					'fuisllades',
				],
				'fusillading'=>[
					'fuisllading',
				],
				'fusillis'=>[
					'fuisllis',
				],
				'fusing'=>[
					'fuzing',
				],
				'fusional'=>[
					'fuisonal',
				],
				'fusionism'=>[
					'fuisonism',
				],
				'fusionisms'=>[
					'fuisonisms',
				],
				'fusionist'=>[
					'fuisonist',
				],
				'fusionists'=>[
					'fuisonists',
				],
				'fuss'=>[
					'fus',
				],
				'fussy'=>[
					'fuscy',
					'fusy',
				],
				'fustian'=>[
					'fustan',
				],
				'futhark'=>[
					'futhroc',
				],
				'futilely'=>[
					'futilly',
				],
				'futilitarian'=>[
					'futilitaran',
				],
				'félix baloy'=>[
					'felix lavoy',
				],
			];
		}
	}

?>