<?php
		
		/* UTF-8 TEST
		
			中文汉字漢字
		
		*/
				
				/* EnglishMisspellingsWords_G
					
					Class for English-Misspellings for all words beginning with : G.
					
				*/

	class EnglishMisspellingsWords_G {
			/* __construct($args)
			
				Constructor.
				
				Nothing to do here.
			
			*/
			
		public function __construct($args) {
			return TRUE;
		}
		
			/* EnglishMisspellingsWords()
			
				List of English misspellings for words starting with : G.
			
			*/

		public function EnglishMisspellingsWords() {
			return [
				'gabbarts'=>[
					'gabarts',
				],
				'gabbed'=>[
					'gabed',
				],
				'gabber'=>[
					'gaber',
				],
				'gabbiest'=>[
					'gabiest',
				],
				'gabbiness'=>[
					'gabiness',
				],
				'gabbinesses'=>[
					'gabinesses',
				],
				'gabble'=>[
					'gable',
				],
				'gabblers'=>[
					'gablers',
				],
				'gabbling'=>[
					'gabling',
				],
				'gabbro'=>[
					'gabro',
				],
				'gabbroic'=>[
					'gabroic',
				],
				'gabbroid'=>[
					'gabroid',
				],
				'gabby'=>[
					'gaby',
				],
				'gabonese-occupied'=>[
					'gabonese occupied',
				],
				'gadfly'=>[
					'gadfally',
					'gadfaly',
					'gadfely',
					'gadflly',
				],
				'gadolinite'=>[
					'gadolinate',
				],
				'gadolinites'=>[
					'gadolinates',
				],
				'gadolinium'=>[
					'gadolinaum',
				],
				'gadoliniums'=>[
					'gadolinaums',
				],
				'gaeing'=>[
					'gaieng',
				],
				'gagged'=>[
					'gaged',
				],
				'gagger'=>[
					'gager',
				],
				'gaggle'=>[
					'gagle',
				],
				'gahnite'=>[
					'ganite',
				],
				'gahnites'=>[
					'ganites',
				],
				'gaiety'=>[
					'gaeity',
					'gaity',
				],
				'gaily'=>[
					'gaially',
					'gaialy',
					'gailly',
				],
				'gainable'=>[
					'gainible',
				],
				'gained'=>[
					'gainid',
				],
				'gainer'=>[
					'gainir',
				],
				'gaining'=>[
					'gainang',
				],
				'galabiyah'=>[
					'galabiya',
				],
				'galabiyahs'=>[
					'galabiyas',
				],
				'galactic'=>[
					'galatic',
				],
				'galactorrhea'=>[
					'galactorhea',
					'galactorrhe',
				],
				'galactorrheas'=>[
					'galactorheas',
				],
				'galactosamine'=>[
					'galactosamini',
				],
				'galactosamines'=>[
					'galactosaminis',
				],
				'galah'=>[
					'gala',
				],
				'galahs'=>[
					'galas',
				],
				'galapogos'=>[
					'galopogos',
				],
				'galatians'=>[
					'galations',
				],
				'gale'=>[
					'gae',
				],
				'galileo'=>[
					'gallileo',
				],
				'gall'=>[
					'gal',
				],
				'gallant'=>[
					'galliant',
					'galant',
					'gallent',
				],
				'gallantry'=>[
					'galantry',
					'gallentry',
				],
				'gallbladder'=>[
					'galbladder',
				],
				'gallein'=>[
					'gallien',
				],
				'galleon'=>[
					'galeon',
				],
				'galleria'=>[
					'galeria',
				],
				'galleries'=>[
					'gallerys',
				],
				'gallery'=>[
					'galllery',
					'galery',
				],
				'galley'=>[
					'galey',
				],
				'gallfly'=>[
					'gallfally',
					'gallfaly',
					'gallfely',
					'gallflly',
				],
				'galligaskins'=>[
					'galigaskins',
				],
				'gallimaufry'=>[
					'galimaufry',
				],
				'gallinaceous'=>[
					'galinaceous',
					'galliniceous',
				],
				'galling'=>[
					'galing',
				],
				'gallinipper'=>[
					'gallinapper',
					'galliniper',
				],
				'gallinippers'=>[
					'gallinappers',
					'gallinipers',
				],
				'gallium'=>[
					'galium',
				],
				'gallivanting'=>[
					'galliventing',
				],
				'gallon'=>[
					'galon',
				],
				'gallop'=>[
					'galop',
				],
				'galloping'=>[
					'galoping',
				],
				'gallows'=>[
					'galows',
				],
				'gally'=>[
					'galally',
					'galaly',
					'gallly',
				],
				'galvanoscope'=>[
					'galvanocope',
					'galvanocsope',
					'galvanosope',
				],
				'gambogian'=>[
					'gambogan',
				],
				'gambusia'=>[
					'gambuisa',
				],
				'gambusias'=>[
					'gambuisas',
				],
				'game'=>[
					'game game',
					'game game game',
				],
				'game boy'=>[
					'gameboy',
				],
				'gamely'=>[
					'gamly',
				],
				'gameplay'=>[
					'gamplay',
				],
				'gamesomely'=>[
					'gamesomly',
				],
				'gamine'=>[
					'gamini',
				],
				'gamma'=>[
					'gamna',
				],
				'gammas'=>[
					'gamnas',
				],
				'gammed'=>[
					'gamned',
				],
				'gammer'=>[
					'gamner',
				],
				'gammon'=>[
					'gamnon',
				],
				'gammy'=>[
					'gamny',
				],
				'gandhi'=>[
					'ghandi',
				],
				'gangliar'=>[
					'ganglar',
				],
				'gangly'=>[
					'gangally',
					'gangaly',
					'gangely',
					'ganglly',
				],
				'gangrened'=>[
					'gangrend',
				],
				'gangster'=>[
					'ganster',
				],
				'ganjah'=>[
					'ganja',
				],
				'ganjahs'=>[
					'ganjas',
				],
				'gannet'=>[
					'ganet',
				],
				'gannett center'=>[
					'gannet center',
				],
				'gannister'=>[
					'ganister',
				],
				'gantlet'=>[
					'gentlet',
				],
				'gantry'=>[
					'gentry',
				],
				'gappy'=>[
					'gapy',
				],
				'gardant'=>[
					'gardent',
				],
				'garden'=>[
					'garden garden',
					'garden garden garden',
				],
				'gardened'=>[
					'gardend',
				],
				'gargantua'=>[
					'gargantau',
					'gargentua',
				],
				'gargantuan'=>[
					'gargantaun',
					'gargentuan',
				],
				'garment'=>[
					'garmant',
				],
				'garnierite'=>[
					'garneirite',
					'garnirite',
				],
				'garnisheeing'=>[
					'garnisheieng',
				],
				'garred'=>[
					'gared',
				],
				'garret'=>[
					'garet',
				],
				'garrison'=>[
					'garisson',
					'garrision',
					'garrisson',
					'garison',
				],
				'garrisoned'=>[
					'garisoned',
				],
				'garron'=>[
					'garon',
				],
				'garrote'=>[
					'garote',
				],
				'garrotting'=>[
					'garotting',
				],
				'garrulity'=>[
					'garulity',
				],
				'garrulous'=>[
					'garulous',
				],
				'garrulousness'=>[
					'garulousness',
				],
				'garrulousnesses'=>[
					'garulousnesses',
				],
				'gas'=>[
					'gas gas',
					'gas gas gas',
				],
				'gascon'=>[
					'gacon',
					'gacson',
					'gason',
				],
				'gaseity'=>[
					'gasiety',
				],
				'gases'=>[
					'gasses',
				],
				'gasoline'=>[
					'gasolini',
				],
				'gassed'=>[
					'gased',
				],
				'gasser'=>[
					'gaser',
				],
				'gassy'=>[
					'gascy',
					'gasy',
				],
				'gastroduodenal'=>[
					'gastrododenal',
				],
				'gastroenteritis'=>[
					'gastroanteritis',
				],
				'gastronomically'=>[
					'gastronomicalally',
					'gastronomicalaly',
					'gastronomicalely',
					'gastronomicallly',
				],
				'gastroscopes'=>[
					'gastrocopes',
					'gastrocsopes',
					'gastrosopes',
				],
				'gastroscopic'=>[
					'gastrocopic',
					'gastrocsopic',
					'gastrosopic',
				],
				'gastroscopists'=>[
					'gastrocopists',
					'gastrocsopists',
					'gastrosopists',
				],
				'gastrovascular'=>[
					'gastrovacsular',
					'gastrovacular',
					'gastrovasculer',
					'gastrovasular',
				],
				'gastrular'=>[
					'gastruler',
				],
				'gather'=>[
					'gather gather',
					'gather gather gather',
				],
				'gathering'=>[
					'gethering',
				],
				'gauchely'=>[
					'gauchly',
				],
				'gauge'=>[
					'guage',
				],
				'gauleiters'=>[
					'gaulieters',
				],
				'gauss'=>[
					'gaus',
				],
				'gave'=>[
					'gave gave',
					'gave gave gave',
				],
				'gawsy'=>[
					'gawcy',
				],
				'gaydar'=>[
					'gayder',
				],
				'gayly'=>[
					'gayally',
					'gayaly',
					'gaylly',
				],
				'gazar'=>[
					'gazer',
				],
				'gazelle'=>[
					'gazele',
				],
				'geanticline'=>[
					'geanticlini',
					'geenticline',
				],
				'geanticlines'=>[
					'geenticlines',
				],
				'gear'=>[
					'geer',
					'ger',
				],
				'gearbox'=>[
					'gerbox',
				],
				'gearing'=>[
					'gering',
				],
				'geeing'=>[
					'geieng',
				],
				'gegenschein'=>[
					'gegenschien',
				],
				'gegenscheins'=>[
					'gegencheins',
					'gegencsheins',
					'gegenschiens',
					'gegensheins',
				],
				'geisha'=>[
					'giesha',
				],
				'geishas'=>[
					'gieshas',
				],
				'gelable'=>[
					'gelible',
				],
				'gelant'=>[
					'gelent',
				],
				'gelatinization'=>[
					'gelatinazation',
				],
				'gelatinizations'=>[
					'gelatinazations',
				],
				'gelatinize'=>[
					'gelatinaze',
				],
				'gelatinized'=>[
					'gelatinazed',
				],
				'gelatinizes'=>[
					'gelatinazes',
				],
				'gelatinizing'=>[
					'gelatinazing',
				],
				'gelidly'=>[
					'gelidally',
					'gelidaly',
					'gelidely',
					'gelidlly',
				],
				'gemeinschaft'=>[
					'gemeinchaft',
					'gemeincshaft',
					'gemeinshaft',
					'gemienschaft',
				],
				'gemeinschafts'=>[
					'gemienschafts',
				],
				'geminal'=>[
					'geminil',
				],
				'geminate'=>[
					'geminite',
				],
				'geminiani'=>[
					'geminani',
				],
				'gemma'=>[
					'gemna',
				],
				'gemmae'=>[
					'gemnae',
				],
				'gemmate'=>[
					'gemnate',
				],
				'gemmations'=>[
					'gemnations',
				],
				'gemmed'=>[
					'gemned',
				],
				'gemmology'=>[
					'gemnology',
				],
				'gemmule'=>[
					'gemnule',
				],
				'gemmy'=>[
					'gemny',
				],
				'gemutlichkeit'=>[
					'gemutlichkiet',
				],
				'gemutlichkeits'=>[
					'gemutlichkiets',
				],
				'gendarmerie'=>[
					'gendarmerei',
					'gendarmeri',
				],
				'genealogically'=>[
					'genelogically',
				],
				'genealogies'=>[
					'geneologies',
				],
				'genealogy'=>[
					'geneology',
					'genology',
					'genelogy',
				],
				'genera or genre'=>[
					'genra',
				],
				'generable'=>[
					'generible',
				],
				'general'=>[
					'genaral',
					'genarel',
					'genearl',
					'general general',
					'general general general',
					'genreal',
				],
				'generalcy'=>[
					'generalsy',
				],
				'generalissimo'=>[
					'generalisimo',
				],
				'generally'=>[
					'genarally',
					'generaly',
					'generelly',
					'genrally',
					'generalally',
					'generalaly',
					'generalely',
					'generallly',
				],
				'generationally'=>[
					'generationalally',
					'generationalaly',
					'generationalely',
					'generationallly',
				],
				'generator'=>[
					'generater',
				],
				'generic'=>[
					'generical',
				],
				'genesis'=>[
					'genisis',
				],
				'genie'=>[
					'genei',
					'geni',
				],
				'genisteins'=>[
					'genistiens',
				],
				'genitalia'=>[
					'genialia',
				],
				'genitourinary'=>[
					'genitourinery',
					'genitouriniry',
				],
				'genius or genus'=>[
					'genuis',
				],
				'gennakers'=>[
					'genakers',
				],
				'gent'=>[
					'gant',
				],
				'genteel'=>[
					'ganteel',
				],
				'gentes'=>[
					'gantes',
				],
				'gentian'=>[
					'gantian',
					'gentan',
				],
				'gentil'=>[
					'gantil',
				],
				'gentile'=>[
					'gantile',
				],
				'gentle'=>[
					'gentle gentle',
					'gentle gentle gentle',
					'gantle',
				],
				'gentleman'=>[
					'gantleman',
				],
				'gentlemanliness'=>[
					'gentlemanliniss',
				],
				'gentlemen\'s'=>[
					'gentlemens',
				],
				'gently'=>[
					'gantly',
				],
				'gentoo'=>[
					'gantoo',
				],
				'gentrification'=>[
					'gantrification',
				],
				'gentry'=>[
					'gantry',
				],
				'gents'=>[
					'gants',
				],
				'genua'=>[
					'genau',
				],
				'genuine'=>[
					'genuini',
				],
				'genuinely'=>[
					'genuinly',
				],
				'genuinen'=>[
					'genuirie',
				],
				'genuinenesses'=>[
					'genuininesses',
				],
				'geodesy'=>[
					'geodecy',
				],
				'geognosy'=>[
					'geognocy',
				],
				'geomancy'=>[
					'geomansy',
				],
				'geometrician'=>[
					'geometrican',
				],
				'geomorphic'=>[
					'geomourphic',
				],
				'geomorphologies'=>[
					'geomourphologies',
				],
				'geomorphologist'=>[
					'geomourphologist',
				],
				'geomorphology'=>[
					'geomourphology',
				],
				'geopolitician'=>[
					'geopolitican',
				],
				'geopressured'=>[
					'geopresured',
				],
				'george'=>[
					'goerge',
				],
				'georgian-occupied'=>[
					'georgian occupied',
				],
				'geoscience'=>[
					'geosceince',
					'geocience',
					'geocsience',
					'geosciance',
					'geoscince',
					'geosience',
				],
				'geoscientist'=>[
					'geocientist',
					'geocsientist',
					'geosientist',
				],
				'geoscientists'=>[
					'geosciantists',
				],
				'geostationary'=>[
					'geostationery',
				],
				'geosyncline'=>[
					'geosynclini',
				],
				'geotectonically'=>[
					'geotectonicalally',
					'geotectonicalaly',
					'geotectonicalely',
					'geotectonicallly',
				],
				'gerah'=>[
					'gera',
				],
				'gerahs'=>[
					'geras',
				],
				'gerent'=>[
					'gerant',
				],
				'geriatrician'=>[
					'geriatrican',
				],
				'german'=>[
					'geramn',
				],
				'german shepherd'=>[
					'german shepard',
					'german sheperd',
					'german shephard',
				],
				'german-occupied'=>[
					'german occupied',
				],
				'germanely'=>[
					'germanly',
				],
				'germinabilities'=>[
					'germinibilities',
				],
				'germinal'=>[
					'germinil',
				],
				'germinate'=>[
					'germinite',
				],
				'germinesses'=>[
					'germinisses',
				],
				'germplasm'=>[
					'germ-plasm',
				],
				'gerontocracy'=>[
					'gerontocrasy',
				],
				'gerontomorphic'=>[
					'gerontomourphic',
				],
				'gerrymander'=>[
					'gerymander',
				],
				'gerrymandered'=>[
					'gerymandered',
				],
				'gerrymandering'=>[
					'gerymandering',
				],
				'gesellschaft'=>[
					'gesellchaft',
					'gesellcshaft',
					'gesellshaft',
				],
				'gesso'=>[
					'geso',
				],
				'gesture'=>[
					'gseture',
				],
				'gesundheit'=>[
					'gesundhiet',
				],
				'get'=>[
					'get get',
					'get get get',
				],
				'getable'=>[
					'getible',
				],
				'gets'=>[
					'get\'s',
				],
				'getting'=>[
					'gettng',
				],
				'gewurztraminer'=>[
					'gewurztraminir',
				],
				'gewurztraminers'=>[
					'gewurztraminirs',
				],
				'ghanian-occupied'=>[
					'ghanian occupied',
				],
				'gharri'=>[
					'ghari',
				],
				'gharris'=>[
					'gharis',
				],
				'gharry'=>[
					'ghary',
				],
				'ghastlinesses'=>[
					'ghastlinisses',
				],
				'ghastly'=>[
					'ghastally',
					'ghastaly',
					'ghastely',
					'ghastlly',
				],
				'ghostlinesses'=>[
					'ghostlinisses',
				],
				'ghostly'=>[
					'ghostally',
					'ghostaly',
					'ghostely',
					'ghostlly',
				],
				'giant'=>[
					'gient',
					'jiant',
				],
				'giantess'=>[
					'gientess',
					'jiantess',
				],
				'giantesses'=>[
					'jiantesses',
				],
				'giantism'=>[
					'jiantism',
				],
				'giantisms'=>[
					'jiantisms',
				],
				'giantlike'=>[
					'jiantlike',
				],
				'giants'=>[
					'gients',
					'jiants',
				],
				'giaour'=>[
					'jiaour',
				],
				'giaours'=>[
					'jiaours',
				],
				'giardia'=>[
					'jiardia',
				],
				'giardias'=>[
					'jiardias',
				],
				'giardiases'=>[
					'jiardiases',
				],
				'giardiasis'=>[
					'jiardiasis',
				],
				'gibbed'=>[
					'gibed',
					'jibbed',
				],
				'gibber'=>[
					'giber',
					'jibber',
				],
				'gibbered'=>[
					'gibered',
					'jibbered',
				],
				'gibberellin'=>[
					'gibberelin',
					'giberellin',
					'jibberellin',
				],
				'gibberellins'=>[
					'giberellins',
					'jibberellins',
				],
				'gibbering'=>[
					'gibering',
					'jibbering',
				],
				'gibberish'=>[
					'giberish',
					'jibberish',
				],
				'gibberishes'=>[
					'giberishes',
					'jibberishes',
				],
				'gibbers'=>[
					'jibbers',
				],
				'gibbet'=>[
					'gibet',
					'jibbet',
				],
				'gibbeted'=>[
					'gibeted',
					'jibbeted',
				],
				'gibbeting'=>[
					'gibeting',
					'jibbeting',
				],
				'gibbets'=>[
					'jibbets',
				],
				'gibbetted'=>[
					'gibetted',
					'jibbetted',
				],
				'gibbetting'=>[
					'gibetting',
					'jibbetting',
				],
				'gibbing'=>[
					'jibbing',
				],
				'gibbon'=>[
					'gibon',
					'jibbon',
				],
				'gibbons'=>[
					'jibbons',
				],
				'gibbose'=>[
					'jibbose',
				],
				'gibbosities'=>[
					'gibosities',
					'jibbosities',
				],
				'gibbosity'=>[
					'gibosity',
					'jibbosity',
				],
				'gibbous'=>[
					'gibous',
					'jibbous',
				],
				'gibbously'=>[
					'gibously',
					'jibbously',
				],
				'gibbsite'=>[
					'gibsite',
					'jibbsite',
				],
				'gibbsites'=>[
					'gibsites',
					'jibbsites',
				],
				'gibed'=>[
					'jibed',
				],
				'giber'=>[
					'jiber',
				],
				'gibers'=>[
					'jibers',
				],
				'gibes'=>[
					'jibes',
				],
				'gibing'=>[
					'jibing',
				],
				'gibingly'=>[
					'jibingly',
				],
				'giblet'=>[
					'jiblet',
				],
				'giblets'=>[
					'jiblets',
				],
				'gibraltar'=>[
					'gibralter',
					'gibraltor',
				],
				'gibson'=>[
					'jibson',
				],
				'gibsons'=>[
					'jibsons',
				],
				'giddap'=>[
					'jiddap',
				],
				'giddied'=>[
					'jiddied',
				],
				'giddier'=>[
					'jiddier',
				],
				'giddies'=>[
					'jiddies',
				],
				'giddiest'=>[
					'jiddiest',
				],
				'giddily'=>[
					'jiddily',
				],
				'giddiness'=>[
					'jiddiness',
				],
				'giddinesses'=>[
					'jiddinesses',
				],
				'giddy'=>[
					'jiddy',
				],
				'giddyap'=>[
					'jiddyap',
				],
				'giddying'=>[
					'jiddying',
				],
				'giddyup'=>[
					'jiddyup',
				],
				'gie'=>[
					'gei',
				],
				'gied'=>[
					'geid',
				],
				'gieing'=>[
					'giieng',
					'jieing',
				],
				'gien'=>[
					'gein',
				],
				'gies'=>[
					'geis',
				],
				'giftable'=>[
					'giftible',
					'jiftable',
				],
				'giftables'=>[
					'jiftables',
				],
				'gifted'=>[
					'jifted',
				],
				'giftedly'=>[
					'jiftedly',
				],
				'giftedness'=>[
					'jiftedness',
				],
				'giftednesses'=>[
					'jiftednesses',
				],
				'giftee'=>[
					'jiftee',
				],
				'giftees'=>[
					'jiftees',
				],
				'gifting'=>[
					'jifting',
				],
				'giftless'=>[
					'jiftless',
				],
				'gifts'=>[
					'jifts',
				],
				'giftware'=>[
					'jiftware',
				],
				'giftwares'=>[
					'jiftwares',
				],
				'giftwrap'=>[
					'jiftwrap',
				],
				'giftwrapped'=>[
					'jiftwrapped',
				],
				'giftwrapping'=>[
					'giftwraping',
					'jiftwrapping',
				],
				'giftwraps'=>[
					'jiftwraps',
				],
				'gigabit'=>[
					'jigabit',
				],
				'gigabits'=>[
					'jigabits',
				],
				'gigabyte'=>[
					'jigabyte',
				],
				'gigabytes'=>[
					'jigabytes',
				],
				'gigacycle'=>[
					'jigacycle',
				],
				'gigacycles'=>[
					'jigacycles',
				],
				'gigaflop'=>[
					'jigaflop',
				],
				'gigaflops'=>[
					'jigaflops',
				],
				'gigahertz'=>[
					'gigaertz',
					'jigahertz',
				],
				'gigahertzes'=>[
					'gigaertzes',
					'jigahertzes',
				],
				'gigantean'=>[
					'jigantean',
				],
				'gigantesque'=>[
					'gigentesque',
					'jigantesque',
				],
				'gigantic'=>[
					'gigentic',
					'jigantic',
				],
				'gigantically'=>[
					'gigentically',
					'jigantically',
				],
				'gigantism'=>[
					'jigantism',
				],
				'gigantisms'=>[
					'jigantisms',
				],
				'gigas'=>[
					'jigas',
				],
				'gigaton'=>[
					'jigaton',
				],
				'gigatons'=>[
					'jigatons',
				],
				'gigawatt'=>[
					'jigawatt',
				],
				'gigawatts'=>[
					'jigawatts',
				],
				'gigged'=>[
					'giged',
					'jigged',
				],
				'gigging'=>[
					'gigjing',
				],
				'giggle'=>[
					'gigle',
					'jiggle',
				],
				'giggled'=>[
					'jiggled',
				],
				'giggler'=>[
					'jiggler',
				],
				'gigglers'=>[
					'jigglers',
				],
				'giggles'=>[
					'jiggles',
				],
				'gigglier'=>[
					'jigglier',
				],
				'giggliest'=>[
					'gigliest',
					'jiggliest',
				],
				'giggling'=>[
					'jiggling',
				],
				'gigglingly'=>[
					'jigglingly',
				],
				'giggly'=>[
					'jiggly',
				],
				'gighe'=>[
					'jighe',
				],
				'giglet'=>[
					'jiglet',
				],
				'giglets'=>[
					'jiglets',
				],
				'giglot'=>[
					'jiglot',
				],
				'giglots'=>[
					'jiglots',
				],
				'gigolo'=>[
					'jigolo',
				],
				'gigolos'=>[
					'jigolos',
				],
				'gigot'=>[
					'jigot',
				],
				'gigots'=>[
					'jigots',
				],
				'gigue'=>[
					'jigue',
				],
				'gigues'=>[
					'jigues',
				],
				'gilbert'=>[
					'jilbert',
				],
				'gilberts'=>[
					'jilberts',
				],
				'gilded'=>[
					'guilded',
					'jilded',
				],
				'gilder'=>[
					'jilder',
				],
				'gilders'=>[
					'jilders',
				],
				'gildhall'=>[
					'jildhall',
				],
				'gildhalls'=>[
					'jildhalls',
				],
				'gilding'=>[
					'jilding',
				],
				'gildings'=>[
					'jildings',
				],
				'gilds'=>[
					'jilds',
				],
				'gill'=>[
					'gil',
				],
				'gilled'=>[
					'jilled',
				],
				'giller'=>[
					'jiller',
				],
				'gillette'=>[
					'gilette',
					'gillete',
				],
				'gillie'=>[
					'gillei',
					'gilli',
					'jillie',
				],
				'gillied'=>[
					'jillied',
				],
				'gillies'=>[
					'jillies',
				],
				'gilling'=>[
					'jilling',
				],
				'gillnet'=>[
					'jillnet',
				],
				'gillnets'=>[
					'jillnets',
				],
				'gillnetted'=>[
					'jillnetted',
				],
				'gillnetter'=>[
					'jillnetter',
				],
				'gillnetters'=>[
					'jillnetters',
				],
				'gillnetting'=>[
					'jillnetting',
				],
				'gills'=>[
					'jills',
				],
				'gilly'=>[
					'gilally',
					'gilaly',
					'gillly',
					'jilly',
				],
				'gillyflower'=>[
					'jillyflower',
				],
				'gillyflowers'=>[
					'jillyflowers',
				],
				'gillying'=>[
					'jillying',
				],
				'gilthead'=>[
					'jilthead',
				],
				'giltheads'=>[
					'jiltheads',
				],
				'gilts'=>[
					'jilts',
				],
				'gimbal'=>[
					'jimbal',
				],
				'gimbaled'=>[
					'jimbaled',
				],
				'gimbaling'=>[
					'jimbaling',
				],
				'gimballed'=>[
					'jimballed',
				],
				'gimballing'=>[
					'jimballing',
				],
				'gimbals'=>[
					'jimbals',
				],
				'gimcrack'=>[
					'jimcrack',
				],
				'gimcrackeries'=>[
					'jimcrackeries',
				],
				'gimcrackery'=>[
					'jimcrackery',
				],
				'gimcracks'=>[
					'jimcracks',
				],
				'gimel'=>[
					'jimel',
				],
				'gimels'=>[
					'jimels',
				],
				'gimlet'=>[
					'jimlet',
				],
				'gimleted'=>[
					'jimleted',
				],
				'gimleting'=>[
					'jimleting',
				],
				'gimlets'=>[
					'jimlets',
				],
				'gimmal'=>[
					'gimnal',
					'jimmal',
				],
				'gimmals'=>[
					'jimmals',
				],
				'gimme'=>[
					'gimne',
					'jimme',
				],
				'gimmes'=>[
					'gimnes',
					'jimmes',
				],
				'gimmick'=>[
					'gimnick',
					'jimmick',
				],
				'gimmicked'=>[
					'jimmicked',
				],
				'gimmicking'=>[
					'gimnicking',
					'jimmicking',
				],
				'gimmickries'=>[
					'jimmickries',
				],
				'gimmickry'=>[
					'gimnickry',
					'jimmickry',
				],
				'gimmicks'=>[
					'jimmicks',
				],
				'gimmicky'=>[
					'jimmicky',
				],
				'gimmie'=>[
					'gimnie',
					'jimmie',
				],
				'gimmies'=>[
					'jimmies',
				],
				'gimped'=>[
					'jimped',
				],
				'gimpier'=>[
					'jimpier',
				],
				'gimping'=>[
					'jimping',
				],
				'gimps'=>[
					'jimps',
				],
				'gimpy'=>[
					'jimpy',
				],
				'gingal'=>[
					'jingal',
				],
				'gingall'=>[
					'jingall',
				],
				'gingalls'=>[
					'jingalls',
				],
				'gingals'=>[
					'jingals',
				],
				'gingeley'=>[
					'jingeley',
				],
				'gingeleys'=>[
					'jingeleys',
				],
				'gingeli'=>[
					'jingeli',
				],
				'gingelies'=>[
					'jingelies',
				],
				'gingelis'=>[
					'jingelis',
				],
				'gingelli'=>[
					'jingelli',
				],
				'gingellies'=>[
					'jingellies',
				],
				'gingellis'=>[
					'jingellis',
				],
				'gingelly'=>[
					'jingelly',
				],
				'gingely'=>[
					'gingly',
					'jingely',
				],
				'ginger'=>[
					'jinger',
				],
				'gingerbread'=>[
					'gingerbred',
					'jingerbread',
				],
				'gingerbreaded'=>[
					'jingerbreaded',
				],
				'gingerbreads'=>[
					'jingerbreads',
				],
				'gingerbready'=>[
					'jingerbready',
				],
				'gingered'=>[
					'jingered',
				],
				'gingering'=>[
					'jingering',
				],
				'gingerliness'=>[
					'gingerliniss',
					'jingerliness',
				],
				'gingerlinesses'=>[
					'gingerlinisses',
					'jingerlinesses',
				],
				'gingerly'=>[
					'gingerally',
					'gingeraly',
					'gingerely',
					'gingerlly',
					'jingerly',
				],
				'gingerroot'=>[
					'gingeroot',
					'jingerroot',
				],
				'gingerroots'=>[
					'jingerroots',
				],
				'gingers'=>[
					'jingers',
				],
				'gingersnap'=>[
					'jingersnap',
				],
				'gingersnaps'=>[
					'jingersnaps',
				],
				'gingery'=>[
					'jingery',
				],
				'gingham'=>[
					'jingham',
				],
				'ginghams'=>[
					'jinghams',
				],
				'gingili'=>[
					'ginjili',
				],
				'gingilis'=>[
					'ginjilis',
				],
				'gingilli'=>[
					'ginjilli',
				],
				'gingillis'=>[
					'ginjillis',
				],
				'gingiva'=>[
					'ginjiva',
				],
				'gingivae'=>[
					'ginjivae',
				],
				'gingival'=>[
					'ginjival',
				],
				'gingivectomies'=>[
					'ginjivectomies',
				],
				'gingivectomy'=>[
					'ginjivectomy',
				],
				'gingivitis'=>[
					'ginjivitis',
				],
				'gingivitises'=>[
					'ginjivitises',
				],
				'gingko'=>[
					'jingko',
				],
				'gingkoes'=>[
					'jingkoes',
				],
				'gingkos'=>[
					'jingkos',
				],
				'ginkgo'=>[
					'jinkgo',
				],
				'ginkgoes'=>[
					'jinkgoes',
				],
				'ginkgos'=>[
					'jinkgos',
				],
				'ginks'=>[
					'jinks',
				],
				'ginned'=>[
					'jinned',
				],
				'ginner'=>[
					'jinner',
				],
				'ginners'=>[
					'jinners',
				],
				'ginnier'=>[
					'jinnier',
				],
				'ginniest'=>[
					'jinniest',
				],
				'ginning'=>[
					'jinning',
				],
				'ginnings'=>[
					'jinnings',
				],
				'ginny'=>[
					'giny',
					'jinny',
				],
				'ginseng'=>[
					'jinseng',
				],
				'ginsengs'=>[
					'jinsengs',
				],
				'ginzo'=>[
					'jinzo',
				],
				'ginzoes'=>[
					'jinzoes',
				],
				'gipon'=>[
					'jipon',
				],
				'gipons'=>[
					'jipons',
				],
				'gipped'=>[
					'jipped',
				],
				'gipping'=>[
					'jipping',
				],
				'gipsied'=>[
					'jipsied',
				],
				'gipsies'=>[
					'jipsies',
				],
				'gipsy'=>[
					'gipcy',
					'jipsy',
				],
				'gipsying'=>[
					'jipsying',
				],
				'giraffe'=>[
					'jiraffe',
				],
				'giraffes'=>[
					'jiraffes',
				],
				'giraffish'=>[
					'jiraffish',
				],
				'girandola'=>[
					'jirandola',
				],
				'girandolas'=>[
					'jirandolas',
				],
				'girandole'=>[
					'jirandole',
				],
				'girandoles'=>[
					'jirandoles',
				],
				'girasol'=>[
					'jirasol',
				],
				'girasole'=>[
					'jirasole',
				],
				'girasoles'=>[
					'jirasoles',
				],
				'girasols'=>[
					'jirasols',
				],
				'girded'=>[
					'jirded',
				],
				'girder'=>[
					'jirder',
				],
				'girders'=>[
					'jirders',
				],
				'girding'=>[
					'jirding',
				],
				'girdingly'=>[
					'jirdingly',
				],
				'girdle'=>[
					'jirdle',
				],
				'girdled'=>[
					'jirdled',
				],
				'girdler'=>[
					'jirdler',
				],
				'girdlers'=>[
					'jirdlers',
				],
				'girdles'=>[
					'jirdles',
				],
				'girdling'=>[
					'jirdling',
				],
				'girds'=>[
					'jirds',
				],
				'girl'=>[
					'girl girl',
					'girl girl girl',
				],
				'girlfriend'=>[
					'girlfreind',
					'girlfrind',
					'jirlfriend',
				],
				'girlfriends'=>[
					'jirlfriends',
				],
				'girlhood'=>[
					'jirlhood',
				],
				'girlhoods'=>[
					'jirlhoods',
				],
				'girlie'=>[
					'girlei',
					'girli',
					'jirlie',
				],
				'girlier'=>[
					'jirlier',
				],
				'girlies'=>[
					'jirlies',
				],
				'girliest'=>[
					'jirliest',
				],
				'girlish'=>[
					'jirlish',
				],
				'girlishly'=>[
					'jirlishly',
				],
				'girlishness'=>[
					'jirlishness',
				],
				'girlishnesses'=>[
					'jirlishnesses',
				],
				'girls'=>[
					'giris',
					'jirls',
				],
				'girls\''=>[
					'girls\'s',
				],
				'girly'=>[
					'girally',
					'giraly',
					'girlly',
					'jirly',
				],
				'girned'=>[
					'jirned',
				],
				'girning'=>[
					'jirning',
				],
				'girns'=>[
					'jirns',
				],
				'girolle'=>[
					'jirolle',
				],
				'giron'=>[
					'jiron',
				],
				'girons'=>[
					'jirons',
				],
				'giros'=>[
					'jiros',
				],
				'girosol'=>[
					'jirosol',
				],
				'girosols'=>[
					'jirosols',
				],
				'girsh'=>[
					'jirsh',
				],
				'girshes'=>[
					'jirshes',
				],
				'girted'=>[
					'jirted',
				],
				'girth'=>[
					'jirth',
				],
				'girthed'=>[
					'jirthed',
				],
				'girthing'=>[
					'jirthing',
				],
				'girths'=>[
					'jirths',
				],
				'girting'=>[
					'jirting',
				],
				'girts'=>[
					'jirts',
				],
				'gisarme'=>[
					'jisarme',
				],
				'gisarmes'=>[
					'jisarmes',
				],
				'gismo'=>[
					'jismo',
				],
				'gismos'=>[
					'jismos',
				],
				'gists'=>[
					'jists',
				],
				'gitano'=>[
					'jitano',
				],
				'gitanos'=>[
					'jitanos',
				],
				'gites'=>[
					'jites',
				],
				'gitted'=>[
					'jitted',
				],
				'gittern'=>[
					'jittern',
				],
				'gitterns'=>[
					'jitterns',
				],
				'gitting'=>[
					'jitting',
				],
				'giulia'=>[
					'guilia',
				],
				'giuliani'=>[
					'giulani',
					'guiliani',
					'guliani',
				],
				'giulio'=>[
					'guilio',
				],
				'giuseppe'=>[
					'guiseppe',
				],
				'give'=>[
					'giue',
					'give give',
					'give give give',
				],
				'giveable'=>[
					'jiveable',
				],
				'giveaway'=>[
					'giveway',
					'jiveaway',
				],
				'giveaways'=>[
					'jiveaways',
				],
				'giveback'=>[
					'jiveback',
				],
				'givebacks'=>[
					'jivebacks',
				],
				'given'=>[
					'gived',
					'jiven',
				],
				'givens'=>[
					'jivens',
				],
				'giver'=>[
					'jiver',
				],
				'givers'=>[
					'jivers',
				],
				'gives'=>[
					'give\'s',
					'jives',
				],
				'giving'=>[
					'giveing',
					'jiving',
				],
				'gizmo'=>[
					'jizmo',
				],
				'gizmos'=>[
					'jizmos',
				],
				'gizzard'=>[
					'jizzard',
				],
				'gizzards'=>[
					'jizzards',
				],
				'glabellar'=>[
					'glabeller',
				],
				'glacier'=>[
					'glaceir',
					'glacir',
				],
				'glad'=>[
					'glad glad',
					'glad glad glad',
				],
				'gladdened'=>[
					'gladdend',
				],
				'gladiolar'=>[
					'gladioler',
				],
				'gladsomely'=>[
					'gladsomly',
				],
				'glamor'=>[
					'glamour',
				],
				'glamorise'=>[
					'glamourise',
				],
				'glamorised'=>[
					'glamourised',
				],
				'glamorises'=>[
					'glamourises',
				],
				'glamorising'=>[
					'glamourising',
				],
				'glamorization'=>[
					'glamourization',
				],
				'glamorizations'=>[
					'glamourizations',
				],
				'glamorize'=>[
					'glamourize',
				],
				'glamorized'=>[
					'glamourized',
				],
				'glamorizer'=>[
					'glamourizer',
				],
				'glamorizers'=>[
					'glamourizers',
				],
				'glamorizes'=>[
					'glamourizes',
				],
				'glamorizing'=>[
					'glamourizing',
				],
				'glamorous'=>[
					'glamourous',
				],
				'glamorously'=>[
					'glamourously',
				],
				'glamorousness'=>[
					'glamourousness',
				],
				'glamorousnesses'=>[
					'glamourousnesses',
				],
				'glamors'=>[
					'glamours',
				],
				'glance'=>[
					'glence',
				],
				'glandular'=>[
					'glanduler',
				],
				'glandularly'=>[
					'glandularally',
					'glandularaly',
					'glandularely',
					'glandularlly',
				],
				'glary'=>[
					'glery',
				],
				'glass'=>[
					'glass glass',
					'glass glass glass',
					'glas',
				],
				'glassware'=>[
					'glasware',
				],
				'glassy'=>[
					'glascy',
					'glasy',
				],
				'glazier'=>[
					'glazeir',
					'glazir',
				],
				'gleam'=>[
					'glem',
				],
				'glean'=>[
					'glen',
				],
				'gleization'=>[
					'gliezation',
				],
				'gleizations'=>[
					'gliezations',
				],
				'glibber'=>[
					'gliber',
				],
				'glimmer'=>[
					'glimner',
				],
				'glimmering'=>[
					'glimnering',
				],
				'glistened'=>[
					'glistend',
				],
				'glittery'=>[
					'glittary',
				],
				'global'=>[
					'globial',
				],
				'globalization'=>[
					'globlization',
				],
				'globbiest'=>[
					'globiest',
				],
				'globby'=>[
					'globy',
				],
				'globosely'=>[
					'globosly',
				],
				'globular'=>[
					'globuler',
				],
				'glockenspiel'=>[
					'glockenspeil',
					'glockenspil',
				],
				'glogg'=>[
					'glog',
				],
				'gloggs'=>[
					'glogs',
				],
				'glomerular'=>[
					'glomeruler',
				],
				'glomming'=>[
					'glomning',
				],
				'glorious'=>[
					'glorous',
				],
				'gloriously'=>[
					'glorously',
				],
				'gloss'=>[
					'glos',
				],
				'glossa'=>[
					'glosa',
				],
				'glossary'=>[
					'glosary',
					'glossery',
				],
				'glossolalia'=>[
					'glosolalia',
				],
				'glossy'=>[
					'gloscy',
					'glosy',
				],
				'gloxinia'=>[
					'gloxinaa',
				],
				'glucinic'=>[
					'glucinac',
				],
				'glucosamine'=>[
					'glucosamini',
				],
				'glued-back instrument'=>[
					'glue back instruments',
				],
				'glueing'=>[
					'gluieng',
				],
				'glummest'=>[
					'glumnest',
				],
				'gluon'=>[
					'glon',
				],
				'gluons'=>[
					'glons',
				],
				'glutamine'=>[
					'glutamini',
				],
				'glutei'=>[
					'glutie',
				],
				'glycine'=>[
					'glycini',
				],
				'glycoprotein'=>[
					'glycoprotien',
				],
				'glycoproteins'=>[
					'glycoprotiens',
				],
				'gnar'=>[
					'gner',
				],
				'gnarr'=>[
					'gnar',
				],
				'gnarred'=>[
					'gnared',
				],
				'gnarrs'=>[
					'gnars',
				],
				'gnathal'=>[
					'gnatal',
				],
				'gneiss'=>[
					'gneis',
					'gniess',
				],
				'gnocchi'=>[
					'gnochi',
				],
				'go'=>[
					'go go',
					'go go go',
				],
				'goalie'=>[
					'goalei',
					'goali',
				],
				'goanna'=>[
					'goana',
				],
				'gobbed'=>[
					'gobed',
				],
				'gobbet'=>[
					'gobet',
				],
				'gobbets'=>[
					'gobets',
				],
				'gobbing'=>[
					'gobing',
				],
				'gobble'=>[
					'goble',
				],
				'gobbled'=>[
					'gobled',
				],
				'gobbledegook'=>[
					'gobledegook',
				],
				'gobbledegooks'=>[
					'gobledegooks',
				],
				'gobbledygook'=>[
					'gobledygook',
				],
				'gobbledygooks'=>[
					'gobledygooks',
				],
				'gobbler'=>[
					'gobler',
				],
				'gobbles'=>[
					'gobles',
				],
				'goddess'=>[
					'goddes',
					'goddes', 'godess',
					'goddes\', \'godess',
					'godess',
				],
				'goddesses'=>[
					'godesses',
				],
				'godless'=>[
					'godles',
				],
				'godly'=>[
					'godally',
					'godaly',
					'godlly',
				],
				'godparent'=>[
					'godperent',
				],
				'godunov'=>[
					'godounov',
				],
				'goes'=>[
					'ges',
				],
				'goethe'=>[
					'gete',
				],
				'goggle'=>[
					'gogle',
				],
				'goggliest'=>[
					'gogliest',
				],
				'goggly'=>[
					'gogly',
				],
				'going'=>[
					'gogin',
					'goign',
					'gonig',
				],
				'gold'=>[
					'gold gold',
					'gold gold gold',
					'gqld',
				],
				'goldennesses'=>[
					'goldenesses',
				],
				'goldfield'=>[
					'goldfeild',
					'goldfild',
				],
				'golliwogg'=>[
					'golliwog',
				],
				'golly'=>[
					'golally',
					'golaly',
					'gollly',
					'goly',
				],
				'gondolier'=>[
					'gondoleir',
					'gondolir',
				],
				'gone'=>[
					'gone gone',
					'gone gone gone',
				],
				'gonococcal'=>[
					'gonococal',
				],
				'gonococci'=>[
					'gonococi',
				],
				'gonococcus'=>[
					'gonococus',
				],
				'gonorrhea'=>[
					'gonorhea',
					'gonorrhe',
					'gonourrhea',
				],
				'gonorrheal'=>[
					'gonorheal',
					'gonourrheal',
				],
				'gonorrheas'=>[
					'gonorheas',
					'gonourrheas',
				],
				'gonzález'=>[
					'gonzalez',
				],
				'good'=>[
					'good good',
					'good good good',
				],
				'good riddance'=>[
					'good riddens',
				],
				'goodbye'=>[
					'goodby',
				],
				'goodie'=>[
					'goodei',
					'goodi',
				],
				'goodly'=>[
					'goodally',
					'goodaly',
					'goodely',
					'goodlly',
				],
				'goodness'=>[
					'goodnes',
				],
				'goodwill'=>[
					'goodwil',
				],
				'googly'=>[
					'googally',
					'googaly',
					'googely',
					'googlly',
				],
				'goombah'=>[
					'goomba',
				],
				'goombahs'=>[
					'goombas',
				],
				'gooseberry'=>[
					'goosebery',
				],
				'goosy'=>[
					'goocy',
				],
				'gorgonian'=>[
					'gorgonan',
				],
				'gorilla'=>[
					'gorila',
				],
				'gorsy'=>[
					'gorcy',
				],
				'gossan'=>[
					'gosan',
				],
				'gossip'=>[
					'gosip',
				],
				'gossipmonger'=>[
					'gosipmonger',
				],
				'got'=>[
					'got got',
					'got got got',
				],
				'gothenburg'=>[
					'gothenberg',
				],
				'gottlieb'=>[
					'gottleib',
				],
				'gouache'=>[
					'goauche',
				],
				'gounaris'=>[
					'gounares',
				],
				'govern'=>[
					'govern govern',
					'govern govern govern',
				],
				'governance'=>[
					'governence',
				],
				'governed'=>[
					'goverened',
				],
				'governess'=>[
					'governes',
				],
				'governessy'=>[
					'governescy',
				],
				'government'=>[
					'govemment',
					'govenrment',
					'goverment',
					'governement',
					'governemnt',
					'governemt',
					'governent',
					'governmelnt',
					'governmen',
					'government government',
					'government government government',
					'governmet',
					'goverrment',
					'govorment',
					'govrenment',
					'governmant',
				],
				'governmental'=>[
					'govermental',
					'govormental',
					'governental',
				],
				'governmentalism'=>[
					'govermentalism',
					'governentalism',
				],
				'governmentalist'=>[
					'govermentalist',
					'governentalist',
				],
				'governmentalize'=>[
					'govermentalize',
					'governentalize',
				],
				'governmentally'=>[
					'governmentaly',
					'govermentally',
					'governentally',
					'governmentalally',
					'governmentalaly',
					'governmentalely',
					'governmentallly',
				],
				'governmentese'=>[
					'govermentese',
					'governentese',
					'governmantese',
				],
				'governmenteses'=>[
					'govermenteses',
					'governenteses',
				],
				'governments'=>[
					'goverments',
					'governents',
				],
				'governor'=>[
					'gouvener',
					'govemor',
					'govenor',
					'governer',
					'governour',
				],
				'governorate'=>[
					'governourate',
				],
				'governorates'=>[
					'governourates',
				],
				'governors'=>[
					'governours',
				],
				'governorship'=>[
					'governourship',
				],
				'governorships'=>[
					'governourships',
				],
				'grabbable'=>[
					'grabable',
				],
				'grabbed'=>[
					'grabed',
				],
				'grabber'=>[
					'graber',
				],
				'grabbiest'=>[
					'grabiest',
				],
				'grabbing'=>[
					'grabing',
				],
				'grabble'=>[
					'grable',
				],
				'grabblers'=>[
					'grablers',
				],
				'grabbling'=>[
					'grabling',
				],
				'grabby'=>[
					'graby',
				],
				'gracelessly'=>[
					'gracelessally',
					'gracelessaly',
					'gracelessely',
					'gracelesslly',
				],
				'gracious'=>[
					'gracous',
				],
				'graciously'=>[
					'gracously',
				],
				'gradient'=>[
					'gradeint',
					'gradiant',
					'gradint',
				],
				'gradual'=>[
					'gradaul',
				],
				'gradualism'=>[
					'gradaulism',
				],
				'gradualisms'=>[
					'gradaulisms',
				],
				'gradualists'=>[
					'gradaulists',
				],
				'gradually'=>[
					'gradualy',
				],
				'gradualness'=>[
					'gradaulness',
				],
				'gradualnesses'=>[
					'gradaulnesses',
				],
				'graduand'=>[
					'gradaund',
				],
				'graduate'=>[
					'gradaute',
				],
				'graduation'=>[
					'gradaution',
				],
				'graduations'=>[
					'gradautions',
				],
				'graffiti'=>[
					'graffitti',
					'grafitti',
				],
				'graham'=>[
					'graam',
				],
				'grahams'=>[
					'graams',
				],
				'grainier'=>[
					'grainaer',
				],
				'graininesses'=>[
					'grainanesses',
					'graininisses',
				],
				'graining'=>[
					'grainang',
				],
				'gramary'=>[
					'gramery',
				],
				'gramercy'=>[
					'gramersy',
				],
				'graminivorous'=>[
					'graminavorous',
				],
				'gramma'=>[
					'gramna',
				],
				'grammar'=>[
					'grammer',
					'gramnar',
				],
				'grammarian'=>[
					'grammaran',
					'gramnarian',
				],
				'grammarians'=>[
					'gramnarians',
				],
				'grammars'=>[
					'gramnars',
				],
				'grammatical'=>[
					'gramatical',
					'gramattical',
					'gramnatical',
				],
				'grammaticality'=>[
					'gramnaticality',
				],
				'grammatically'=>[
					'gramatically',
					'grammaticaly',
					'gramnatically',
				],
				'grammaticalness'=>[
					'gramnaticalness',
				],
				'gramme'=>[
					'gramne',
				],
				'granary'=>[
					'granery',
				],
				'grand'=>[
					'grand grand',
					'grand grand grand',
				],
				'grandchild'=>[
					'granchild',
				],
				'grandchildren'=>[
					'granchildren',
				],
				'granddaughter'=>[
					'grandaughter',
				],
				'grandeur'=>[
					'grandure',
					'grander',
				],
				'grandfather'=>[
					'grand-father',
					'granfather',
				],
				'grandfatherly'=>[
					'grandfatherally',
					'grandfatheraly',
					'grandfatherely',
					'grandfatherlly',
				],
				'grandiloquence'=>[
					'grandiloquance',
				],
				'grandiloquent'=>[
					'grandiloquant',
				],
				'grandiloquently'=>[
					'grandiloquentally',
					'grandiloquentaly',
					'grandiloquentely',
					'grandiloquentlly',
				],
				'grandiosely'=>[
					'grandiosly',
				],
				'grandly'=>[
					'grandally',
					'grandaly',
					'grandely',
					'grandlly',
				],
				'grandmother'=>[
					'granmother',
				],
				'grandmotherly'=>[
					'grandmotherally',
					'grandmotheraly',
					'grandmotherely',
					'grandmotherlly',
				],
				'grandniece'=>[
					'grandneice',
					'grandnice',
				],
				'grandparent'=>[
					'granparent',
					'grandparant',
					'grandperent',
				],
				'grandparental'=>[
					'grandperental',
				],
				'grandparenthood'=>[
					'grandperenthood',
				],
				'grandparents'=>[
					'grandperents',
				],
				'grandson'=>[
					'granson',
				],
				'granny'=>[
					'grany',
				],
				'grant'=>[
					'grent',
				],
				'grantee'=>[
					'grentee',
				],
				'grantor'=>[
					'grentor',
				],
				'grants'=>[
					'grents',
				],
				'grantsmanship'=>[
					'grentsmanship',
				],
				'grantsmanships'=>[
					'grentsmanships',
				],
				'granular'=>[
					'granuler',
				],
				'grapevine'=>[
					'grapevini',
				],
				'grappa'=>[
					'grapa',
				],
				'grapple'=>[
					'graple',
				],
				'grappling'=>[
					'grapling',
				],
				'grass'=>[
					'grass grass',
					'grass grass grass',
					'gras',
				],
				'grasshopper'=>[
					'grashopper',
					'grasshoper',
				],
				'grasshoppers'=>[
					'grasshopers',
				],
				'grassland'=>[
					'grasland',
				],
				'grassy'=>[
					'grascy',
					'grasy',
				],
				'grateful'=>[
					'gratefull',
					'greatful',
				],
				'gratefully'=>[
					'greatfully',
				],
				'gratineeing'=>[
					'gratineieng',
				],
				'gratuitous'=>[
					'gratuitious',
				],
				'gravelly'=>[
					'gravelally',
					'gravelaly',
					'gravelely',
					'gravellly',
					'gravely',
				],
				'gravely'=>[
					'gravly',
				],
				'gravimetrically'=>[
					'gravimetricalally',
					'gravimetricalaly',
					'gravimetricalely',
					'gravimetricallly',
				],
				'gray'=>[
					'gray gray',
					'gray gray gray',
				],
				'grease'=>[
					'grese',
				],
				'greasepaint'=>[
					'gresepaint',
				],
				'greasinesses'=>[
					'greasinisses',
				],
				'greasy'=>[
					'greacy',
					'gresy',
				],
				'great'=>[
					'gerat',
					'graet',
					'grat',
					'great great',
					'great great great',
					'gret',
				],
				'greatened'=>[
					'greatend',
				],
				'greater'=>[
					'gerater',
					'greter',
				],
				'greatest'=>[
					'geratest',
				],
				'greathearted'=>[
					'greatherted',
				],
				'greatheartedly'=>[
					'greathertedly',
				],
				'greatly'=>[
					'greately',
				],
				'grecian'=>[
					'greecian',
				],
				'greedinesses'=>[
					'greedinisses',
				],
				'greeing'=>[
					'greieng',
				],
				'greek-occupied'=>[
					'greek occupied',
				],
				'green'=>[
					'greeen',
					'green green',
					'green green green',
				],
				'greenbacks'=>[
					'greenbacs',
				],
				'greenbrier'=>[
					'greenbreir',
					'greenbrir',
				],
				'greened'=>[
					'greend',
				],
				'greenfield'=>[
					'greenfeild',
					'greenfild',
				],
				'greenfly'=>[
					'greenfally',
					'greenfaly',
					'greenfely',
					'greenflly',
				],
				'greenmail'=>[
					'greemail',
					'greenail',
				],
				'greenmailed'=>[
					'greemailed',
					'greenailed',
				],
				'greenmailer'=>[
					'greemailer',
					'greenailer',
				],
				'greenmailers'=>[
					'greemailers',
					'greenailers',
				],
				'greenmailing'=>[
					'greemailing',
					'greenailing',
				],
				'greenmails'=>[
					'greemails',
					'greenails',
				],
				'greenness'=>[
					'greeness',
				],
				'greennesses'=>[
					'greenesses',
				],
				'greensickness'=>[
					'greensicknes',
				],
				'greeted'=>[
					'greated',
				],
				'gregarious'=>[
					'gregarous',
				],
				'gregariously'=>[
					'gregarously',
				],
				'greige'=>[
					'griege',
				],
				'greiges'=>[
					'grieges',
				],
				'greisen'=>[
					'griesen',
				],
				'gremmies'=>[
					'gremnies',
				],
				'gremmy'=>[
					'gremny',
				],
				'grenadian-occupied'=>[
					'grenadian occupied',
				],
				'grenadier'=>[
					'grenadeir',
					'grenadir',
				],
				'grenadine'=>[
					'grenadini',
				],
				'grew'=>[
					'grew grew',
					'grew grew grew',
					'growed',
				],
				'gribble'=>[
					'grible',
				],
				'grief'=>[
					'greif',
					'grif',
				],
				'grievance'=>[
					'greivance',
					'greviance',
					'grivance',
					'grievence',
				],
				'grieve'=>[
					'greive',
					'grive',
				],
				'grievous'=>[
					'greivous',
					'greveous',
					'grevious',
					'grevous',
					'grivous',
				],
				'grievously'=>[
					'greivously',
					'greviously',
					'grivously',
				],
				'grill'=>[
					'gril',
				],
				'grille'=>[
					'grile',
				],
				'grimmest'=>[
					'grimnest',
				],
				'grippe'=>[
					'gripe',
				],
				'grislinesses'=>[
					'grislinisses',
				],
				'grisly'=>[
					'grisally',
					'grisaly',
					'grisely',
					'grislly',
				],
				'gristlinesses'=>[
					'gristlinisses',
				],
				'gristly'=>[
					'gristally',
					'gristaly',
					'gristely',
					'gristlly',
				],
				'grittinesses'=>[
					'grittinisses',
				],
				'grizzly'=>[
					'grizzally',
					'grizzaly',
					'grizzely',
					'grizzlly',
				],
				'groggiest'=>[
					'grogiest',
				],
				'grogginesses'=>[
					'grogginisses',
					'groginesses',
				],
				'groggy'=>[
					'grogy',
				],
				'groining'=>[
					'groinang',
				],
				'grommet'=>[
					'gromnet',
				],
				'grommets'=>[
					'gromnets',
				],
				'gross'=>[
					'gros',
				],
				'grossular'=>[
					'grossuler',
				],
				'grossularite'=>[
					'grosularite',
				],
				'grotesquely'=>[
					'grotesquly',
				],
				'grouchinesses'=>[
					'grouchinisses',
				],
				'ground'=>[
					'ground ground',
					'ground ground ground',
				],
				'ground-based'=>[
					'ground based',
				],
				'ground-mounted'=>[
					'ground mounted',
					'groundmounted',
				],
				'groundbreaker'=>[
					'groundbreker',
				],
				'groundbreakers'=>[
					'groundbrekers',
				],
				'groundbreaking'=>[
					'groundbreking',
				],
				'groundless'=>[
					'groundles',
				],
				'groundswell'=>[
					'groundswel',
				],
				'group'=>[
					'gorup',
					'gropu',
					'group group',
					'group group group',
				],
				'groupie'=>[
					'groupei',
					'groupi',
				],
				'groups'=>[
					'gorups',
				],
				'grousing'=>[
					'grouisng',
				],
				'grow'=>[
					'grow grow',
					'grow grow grow',
					'grwo',
				],
				'growlinesses'=>[
					'growlinisses',
				],
				'growth'=>[
					'growtb',
				],
				'growthinesses'=>[
					'growthinisses',
				],
				'grubbed'=>[
					'grubed',
				],
				'grubber'=>[
					'gruber',
				],
				'grubbiest'=>[
					'grubiest',
				],
				'grubbiness'=>[
					'grubiness',
				],
				'grubbinesses'=>[
					'grubbinisses',
					'grubinesses',
				],
				'grubby'=>[
					'gruby',
				],
				'gruesomely'=>[
					'gruesomly',
				],
				'grummet'=>[
					'grumnet',
				],
				'grummets'=>[
					'grumnets',
				],
				'grumpinesses'=>[
					'grumpinisses',
				],
				'guacamole'=>[
					'gaucamole',
				],
				'guacharo'=>[
					'gaucharo',
				],
				'guaco'=>[
					'gauco',
				],
				'guacos'=>[
					'gaucos',
				],
				'guaiac'=>[
					'gauiac',
				],
				'guaiacol'=>[
					'gauiacol',
				],
				'guaiacum'=>[
					'gauiacum',
				],
				'guan'=>[
					'gaun',
				],
				'guanabana'=>[
					'gaunabana',
				],
				'guanaco'=>[
					'gaunaco',
				],
				'guanay'=>[
					'gaunay',
				],
				'guanethidine'=>[
					'gaunethidine',
					'guanethidini',
				],
				'guanethidines'=>[
					'guanethidinis',
				],
				'guanidine'=>[
					'gaunidine',
					'guanidini',
				],
				'guanin'=>[
					'gaunin',
				],
				'guanine'=>[
					'gunanine',
					'gaunine',
					'guanini',
				],
				'guano'=>[
					'gauno',
				],
				'guanos'=>[
					'gaunos',
				],
				'guanosine'=>[
					'gaunosine',
					'guanosini',
				],
				'guans'=>[
					'gauns',
				],
				'guar'=>[
					'gaur',
					'guer',
				],
				'guarana'=>[
					'gaurana',
				],
				'guarani'=>[
					'gaurani',
				],
				'guarantee'=>[
					'garantee',
					'gaurantee',
					'gaurentee',
					'guarentee',
					'gurantee',
				],
				'guaranteed'=>[
					'garanteed',
					'gauranteed',
					'gaurenteed',
					'guarenteed',
					'guranteed',
				],
				'guaranteeing'=>[
					'guarenteeing',
					'guaranteieng',
				],
				'guarantees'=>[
					'garantees',
					'gaurantees',
					'gaurentees',
					'guarentees',
					'gurantees',
				],
				'guarantor'=>[
					'gaurantor',
					'guarentor',
				],
				'guaranty'=>[
					'gauranty',
					'guarenty',
				],
				'guaraná'=>[
					'gauarana',
					'guarana',
				],
				'guard'=>[
					'gaurd',
					'gaurds',
					'guard=gaurd',
					'gurad',
				],
				'guardant'=>[
					'gaurdant',
					'guardent',
				],
				'guardants'=>[
					'guardents',
				],
				'guarded'=>[
					'gaurded',
				],
				'guardhouse'=>[
					'gaurdhouse',
				],
				'guardian'=>[
					'gardian',
					'gaurdian',
					'guradian',
					'guardan',
				],
				'guarding'=>[
					'gaurding',
				],
				'guardrail'=>[
					'gaurdrail',
				],
				'guardroom'=>[
					'gaurdroom',
				],
				'guards'=>[
					'gaurds',
				],
				'guardsman'=>[
					'gaurdsman',
				],
				'guars'=>[
					'gaurs',
				],
				'guatemala'=>[
					'guatamala',
				],
				'guatemalan'=>[
					'guatamalan',
				],
				'guatemalan-occupied'=>[
					'guatemalan occupied',
				],
				'guava'=>[
					'gauva',
				],
				'guavas'=>[
					'gauvas',
				],
				'guayabera'=>[
					'gauyabera',
				],
				'guayule'=>[
					'gauyule',
				],
				'guerilla'=>[
					'guerila',
				],
				'guerrilla'=>[
					'guerilla',
					'guerrala',
					'guerralla',
					'guerrila',
					'guerrilal',
				],
				'guerrillas'=>[
					'guerillas',
					'guerralas',
					'guerrallas',
					'guerrilals',
					'guerrilas',
				],
				'guess'=>[
					'guess guess',
					'guess guess guess',
					'gues',
				],
				'guesstimate'=>[
					'guestimate',
				],
				'guesswork'=>[
					'gueswork',
				],
				'guest-starred'=>[
					'guest stared',
				],
				'guggle'=>[
					'gugle',
				],
				'guidance'=>[
					'guidence',
				],
				'guide'=>[
					'giude',
					'guide guide',
					'guide guide guide',
				],
				'guideline'=>[
					'guidelini',
				],
				'guild'=>[
					'guiid',
				],
				'guildhall'=>[
					'guildhal',
				],
				'guilelessly'=>[
					'guilelessally',
					'guilelessaly',
					'guilelessely',
					'guilelesslly',
				],
				'guillotine'=>[
					'guillotini',
					'guilotine',
				],
				'guillotining'=>[
					'guillotinang',
				],
				'guilt'=>[
					'giult',
				],
				'guiltinesses'=>[
					'guiltinisses',
				],
				'guiltlessly'=>[
					'guiltlessally',
					'guiltlessaly',
					'guiltlessely',
					'guiltlesslly',
				],
				'guinea'=>[
					'guine',
					'guinia',
				],
				'guinness'=>[
					'guiness',
				],
				'guitar'=>[
					'giutar',
					'guiter',
				],
				'guitar-like'=>[
					'guitar like',
				],
				'guitarist'=>[
					'guitarrist',
				],
				'gular'=>[
					'guler',
				],
				'gulf'=>[
					'gulph',
				],
				'gull'=>[
					'gul',
				],
				'gullet'=>[
					'gulet',
				],
				'gullible'=>[
					'gulible',
					'gullable',
				],
				'gully'=>[
					'gulally',
					'gulaly',
					'gullly',
					'guly',
				],
				'gumma'=>[
					'gumna',
				],
				'gummas'=>[
					'gumnas',
				],
				'gummed'=>[
					'gumned',
				],
				'gummer'=>[
					'gumner',
				],
				'gummiest'=>[
					'gumniest',
				],
				'gumminesses'=>[
					'gumninesses',
				],
				'gummite'=>[
					'gumnite',
				],
				'gummites'=>[
					'gumnites',
				],
				'gummose'=>[
					'gumnose',
				],
				'gummoses'=>[
					'gumnoses',
				],
				'gummosis'=>[
					'gumnosis',
				],
				'gummous'=>[
					'gumnous',
				],
				'gummy'=>[
					'gumny',
				],
				'gumptious'=>[
					'gumptous',
				],
				'gumshoeing'=>[
					'gumshoieng',
				],
				'gun'=>[
					'gun gun',
					'gun gun gun',
				],
				'gunman'=>[
					'guman',
					'gunan',
				],
				'gunmen'=>[
					'gumen',
					'gunen',
				],
				'gunmetal'=>[
					'gumetal',
					'gunetal',
				],
				'gunmetals'=>[
					'gumetals',
					'gunetals',
				],
				'gunnel'=>[
					'gunel',
				],
				'gunner'=>[
					'guner',
				],
				'gunneries'=>[
					'guneries',
				],
				'gunnery'=>[
					'gunery',
				],
				'gunning'=>[
					'guning',
				],
				'gunny'=>[
					'guny',
				],
				'gunnybags'=>[
					'gunybags',
				],
				'gunnysack'=>[
					'gunysack',
				],
				'gunrunner'=>[
					'gunruner',
				],
				'gunrunnings'=>[
					'gunrunings',
				],
				'guppy'=>[
					'gupy',
				],
				'gurries'=>[
					'guries',
				],
				'gurry'=>[
					'gury',
				],
				'gusset'=>[
					'guset',
				],
				'gussy'=>[
					'guscy',
					'gusy',
				],
				'gutsy'=>[
					'gutcy',
				],
				'guttery'=>[
					'guttary',
				],
				'guttural'=>[
					'guttaral',
					'gutteral',
				],
				'guyanese-occupied'=>[
					'guyanese occupied',
				],
				'gwine'=>[
					'gwini',
				],
				'gymnastics'=>[
					'gymastics',
					'gynmastics',
				],
				'gynandromorph'=>[
					'gynandromourph',
				],
				'gynandromorphic'=>[
					'gynandromourphic',
				],
				'gynandromorphs'=>[
					'gynandromourphs',
				],
				'gynandromorphy'=>[
					'gynandromourphy',
				],
				'gynecocracy'=>[
					'gynecocrasy',
				],
				'gypseian'=>[
					'gypsean',
				],
				'gypsy'=>[
					'gypcy',
				],
				'gyrate'=>[
					'girate',
				],
				'gyrated'=>[
					'girated',
				],
				'gyrates'=>[
					'girates',
				],
				'gyrating'=>[
					'girating',
				],
				'gyration'=>[
					'giration',
				],
				'gyrocompass'=>[
					'gyrocompas',
				],
				'gyrofrequency'=>[
					'gyrofrequensy',
				],
				'gyroscope'=>[
					'gyrocope',
					'gyrocsope',
					'gyrosope',
				],
				'gyroscopically'=>[
					'gyrocopically',
					'gyrocsopically',
					'gyrosopically',
				],
				'gómez correa'=>[
					'gómez-correa',
				],
				'güines'=>[
					'guines',
				],
				'güiro'=>[
					'guiro',
				],
			];
		}
	}

?>