<?php
		
		/* UTF-8 TEST
		
			中文汉字漢字
		
		*/
				
				/* EnglishMisspellingsWords_U
					
					Class for English-Misspellings for all words beginning with : U.
					
				*/

	class EnglishMisspellingsWords_U {
			/* __construct($args)
			
				Constructor.
				
				Nothing to do here.
			
			*/
			
		public function __construct($args) {
			return TRUE;
		}
		
			/* EnglishMisspellingsWords()
			
				List of English misspellings for words starting with : U.
			
			*/

		public function EnglishMisspellingsWords() {
			return [
				'u-boat'=>[
					'uboat',
				],
				'uakari'=>[
					'aukari',
				],
				'ubiquitous'=>[
					'ubiquitious',
				],
				'ugandan-occupied'=>[
					'ugandan occupied',
				],
				'uilleann pipes'=>[
					'uileann pipes',
				],
				'uintahite'=>[
					'uintaite',
				],
				'uintahites'=>[
					'uintaites',
				],
				'ukraine'=>[
					'ukraina',
					'ukrane',
				],
				'ukrainian'=>[
					'ukranian',
					'ukrianian',
				],
				'ukrainian-occupied'=>[
					'ukrainian occupied',
				],
				'ukulele'=>[
					'ukelele',
				],
				'ulnar'=>[
					'ulner',
				],
				'ultimacy'=>[
					'ultimasy',
				],
				'ultimate'=>[
					'ulitmate',
				],
				'ultimately'=>[
					'ultimatley',
					'ultimatly',
					'ultimitely',
					'ultimateally',
					'ultimatealy',
					'ultimateely',
					'ultimatelly',
				],
				'ultimatum'=>[
					'ultimatim',
					'ultimatium',
				],
				'ultracasual'=>[
					'ultracasaul',
				],
				'ultracautious'=>[
					'ultracautous',
				],
				'ultracentrifuge'=>[
					'ultracantrifuge',
				],
				'ultracommercial'=>[
					'ultracomnercial',
				],
				'ultradense'=>[
					'ultradence',
				],
				'ultradistance'=>[
					'ultradistence',
				],
				'ultraexclusive'=>[
					'ultraexcluisve',
				],
				'ultrafamiliar'=>[
					'ultrafamilar',
					'ultrafamilier',
				],
				'ultrafastidious'=>[
					'ultrafastidous',
				],
				'ultrafeminine'=>[
					'ultrafeminane',
				],
				'ultraglamorous'=>[
					'ultraglamourous',
				],
				'ultrahazardous'=>[
					'ultraazardous',
				],
				'ultraheat'=>[
					'ultraeat',
				],
				'ultraheated'=>[
					'ultraeated',
				],
				'ultraheating'=>[
					'ultraeating',
				],
				'ultraheats'=>[
					'ultraeats',
				],
				'ultrahigh'=>[
					'ultraigh',
				],
				'ultrahip'=>[
					'ultraip',
				],
				'ultrahot'=>[
					'ultraot',
				],
				'ultrahuman'=>[
					'ultrauman',
				],
				'ultramarine'=>[
					'ultramarini',
				],
				'ultramicroscope'=>[
					'ultramicrocope',
					'ultramicrocsope',
					'ultramicrosope',
				],
				'ultramilitant'=>[
					'ultramilitent',
				],
				'ultraminiature'=>[
					'ultraminaature',
				],
				'ultrareliable'=>[
					'ultrareliible',
				],
				'ultraserious'=>[
					'ultraserous',
				],
				'ultraviolence'=>[
					'ultraviolance',
				],
				'umbellar'=>[
					'umbeller',
				],
				'umbelliferous'=>[
					'umbeliferous',
				],
				'umbrella'=>[
					'umbrela',
				],
				'umm'=>[
					'umn',
				],
				'unabashed'=>[
					'unabased',
				],
				'unabated'=>[
					'unabatted',
				],
				'unabatedly'=>[
					'unabatedally',
					'unabatedaly',
					'unabatedely',
					'unabatedlly',
				],
				'unable'=>[
					'unible',
				],
				'unabusive'=>[
					'unabuisve',
				],
				'unaccented'=>[
					'unacented',
				],
				'unacceptability'=>[
					'unaceptability',
				],
				'unacceptable'=>[
					'unacceptible',
					'unaceptable',
				],
				'unacceptably'=>[
					'unacceptabally',
					'unacceptabaly',
					'unacceptabely',
					'unacceptablly',
				],
				'unacclimatized'=>[
					'unaclimatized',
				],
				'unaccommodated'=>[
					'unaccomnodated',
					'unacommodated',
				],
				'unaccommodating'=>[
					'unaccomnodating',
					'unacommodating',
				],
				'unaccompanied'=>[
					'unaccompaneid',
					'unaccompanid',
					'unacompanied',
				],
				'unaccountable'=>[
					'unaccountible',
					'unacountable',
				],
				'unaccountably'=>[
					'unacountably',
				],
				'unaccounted'=>[
					'unacounted',
				],
				'unaccredited'=>[
					'unacredited',
				],
				'unacculturated'=>[
					'unaculturated',
				],
				'unaccustomed'=>[
					'unacustomed',
				],
				'unaccustomedly'=>[
					'unacustomedly',
				],
				'unacknowledged'=>[
					'unacknowleged',
					'unackowledged',
				],
				'unacquainted'=>[
					'unacqauinted',
				],
				'unadaptable'=>[
					'unadaptible',
				],
				'unaddressed'=>[
					'unaddresed',
				],
				'unadeptly'=>[
					'unadeptally',
					'unadeptaly',
					'unadeptely',
					'unadeptlly',
				],
				'unadulteratedly'=>[
					'unadulteratedally',
					'unadulteratedaly',
					'unadulteratedely',
					'unadulteratedlly',
				],
				'unadventurous'=>[
					'unadvanturous',
				],
				'unaffected'=>[
					'uneffected',
				],
				'unaffectedly'=>[
					'unaffectedally',
					'unaffectedaly',
					'unaffectedely',
					'unaffectedlly',
				],
				'unaffordable'=>[
					'unaffordible',
				],
				'unaggressive'=>[
					'unaggresive',
					'unagressive',
				],
				'unalienable'=>[
					'unaleinable',
					'unalienible',
					'unalinable',
				],
				'unalleviated'=>[
					'unaleviated',
				],
				'unalterable'=>[
					'unalterible',
				],
				'unambiguous'=>[
					'unambigous',
				],
				'unambiguously'=>[
					'unambigously',
					'unambiguousally',
					'unambiguousaly',
					'unambiguousely',
					'unambiguouslly',
				],
				'unambitious'=>[
					'unambitous',
				],
				'unambivalent'=>[
					'unambivalant',
				],
				'unamiable'=>[
					'unamiible',
				],
				'unamortized'=>[
					'unamourtized',
				],
				'unamplified'=>[
					'unamplifeid',
					'unamplifid',
				],
				'unamusing'=>[
					'unamuisng',
				],
				'unanalyzable'=>[
					'unanalyzible',
				],
				'unanimous'=>[
					'unaminous',
				],
				'unannounced'=>[
					'unanounced',
				],
				'unanswerable'=>[
					'unanswerible',
				],
				'unanswerably'=>[
					'unanswerabally',
					'unanswerabaly',
					'unanswerabely',
					'unanswerablly',
				],
				'unanticipated'=>[
					'unenticipated',
				],
				'unanticipatedly'=>[
					'unanticipatedally',
					'unanticipatedaly',
					'unanticipatedely',
					'unanticipatedlly',
				],
				'unapparent'=>[
					'unaparent',
					'unapperent',
				],
				'unappealable'=>[
					'unapealable',
					'unappealible',
					'unappelable',
				],
				'unappealing'=>[
					'unapealing',
					'unappeling',
				],
				'unappealingly'=>[
					'unapealingly',
				],
				'unappeasable'=>[
					'unapeasable',
					'unappeasible',
					'unappesable',
				],
				'unappeasably'=>[
					'unappeasabally',
					'unappeasabaly',
					'unappeasabely',
					'unappeasablly',
				],
				'unappeased'=>[
					'unapeased',
				],
				'unappetizing'=>[
					'unapetizing',
				],
				'unappetizingly'=>[
					'unapetizingly',
				],
				'unapplied'=>[
					'unappleid',
					'unaplied',
					'unapplid',
				],
				'unappreciated'=>[
					'unapreciated',
				],
				'unappreciation'=>[
					'unapreciation',
				],
				'unappreciations'=>[
					'unapreciations',
				],
				'unappreciative'=>[
					'unapreciative',
				],
				'unapproachable'=>[
					'unapproachible',
					'unaproachable',
				],
				'unapproachably'=>[
					'unaproachably',
				],
				'unappropriated'=>[
					'unapropriated',
				],
				'unapproved'=>[
					'unaproved',
				],
				'unarguable'=>[
					'unargauble',
					'unarguible',
				],
				'unarmed'=>[
					'umarmed',
				],
				'unarmored'=>[
					'unarmoured',
				],
				'unary'=>[
					'unery',
				],
				'unassailable'=>[
					'unasailable',
					'unassailible',
				],
				'unassailably'=>[
					'unassailabally',
					'unassailabaly',
					'unassailabely',
					'unassailablly',
				],
				'unassembled'=>[
					'unasembled',
				],
				'unassertive'=>[
					'unasertive',
				],
				'unassertively'=>[
					'unassertivly',
				],
				'unassigned'=>[
					'unasigned',
				],
				'unassimilable'=>[
					'unassimilible',
				],
				'unassimilated'=>[
					'unasimilated',
				],
				'unassisted'=>[
					'unasisted',
				],
				'unassociated'=>[
					'unasociated',
				],
				'unassuageable'=>[
					'unassuageible',
				],
				'unassuaged'=>[
					'unassauged',
				],
				'unassuming'=>[
					'unasuming',
				],
				'unattainable'=>[
					'unattainible',
				],
				'unattractively'=>[
					'unattractivly',
				],
				'unattributable'=>[
					'unattributible',
				],
				'unavailable'=>[
					'unavalable',
					'unavaliable',
					'unavalible',
					'unavailible',
				],
				'unavoidable'=>[
					'unavoidible',
				],
				'unawakened'=>[
					'unawakend',
				],
				'unaware'=>[
					'unware',
				],
				'unawarely'=>[
					'unawarly',
				],
				'unbalance'=>[
					'unbalence',
				],
				'unbar'=>[
					'unber',
				],
				'unbear'=>[
					'unbeer',
				],
				'unbearable'=>[
					'unbearible',
					'unberable',
				],
				'unbeatable'=>[
					'unbeatible',
					'unbetable',
				],
				'unbeaten'=>[
					'unbeten',
				],
				'unbeknown'=>[
					'unbekown',
				],
				'unbeknownst'=>[
					'unbekownst',
				],
				'unbelief'=>[
					'unbeleif',
					'unbelif',
				],
				'unbelievable'=>[
					'unbeleivable',
					'unbelievible',
					'unbelivable',
				],
				'unbelievably'=>[
					'unbelievabally',
					'unbelievabaly',
					'unbelievabely',
					'unbelievablly',
				],
				'unbeliever'=>[
					'unbeleiver',
					'unbeliver',
				],
				'unbelieving'=>[
					'unbeleiving',
					'unbeliving',
				],
				'unbent'=>[
					'unbant',
				],
				'unbilled'=>[
					'unbiled',
				],
				'unbleached'=>[
					'unbleched',
				],
				'unbonnet'=>[
					'unbonet',
				],
				'unbouncy'=>[
					'unbounsy',
				],
				'unbreachable'=>[
					'unbreachible',
					'unbrechable',
				],
				'unbreakable'=>[
					'unbreakible',
					'unbrekable',
				],
				'unbreathable'=>[
					'unbreathible',
					'unbrethable',
				],
				'unbridgeable'=>[
					'unbridgeble',
					'unbridgeible',
				],
				'unbudgeable'=>[
					'unbudgeible',
				],
				'unbuildable'=>[
					'unbuildible',
				],
				'unburden'=>[
					'unburthen',
				],
				'unburdened'=>[
					'unburdend',
				],
				'unburied'=>[
					'unbureid',
					'unburid',
				],
				'unbusinesslike'=>[
					'unbuisnesslike',
					'unbusineslike',
					'unbusinisslike',
				],
				'unbusy'=>[
					'unbucy',
				],
				'uncanninesses'=>[
					'uncaninesses',
				],
				'uncanny'=>[
					'uncany',
				],
				'uncapturable'=>[
					'uncapturible',
				],
				'uncatchable'=>[
					'uncatchible',
				],
				'uncategorizable'=>[
					'uncategorizible',
				],
				'unceasing'=>[
					'uncesing',
				],
				'uncensorious'=>[
					'uncensorous',
				],
				'unceremonious'=>[
					'unceremonous',
				],
				'unceremoniously'=>[
					'unceremonously',
				],
				'uncertain'=>[
					'uncertian',
				],
				'uncertainness'=>[
					'uncertainess',
				],
				'uncertainnesses'=>[
					'uncertainesses',
				],
				'uncertainty'=>[
					'uncertainity',
				],
				'uncertified'=>[
					'uncertifeid',
					'uncertifid',
				],
				'unchallengeable'=>[
					'unchalengeable',
					'unchallengeble',
					'unchallengeible',
				],
				'unchallenged'=>[
					'unchalenged',
				],
				'unchallenging'=>[
					'unchalenging',
				],
				'unchancy'=>[
					'unchansy',
				],
				'unchangeable'=>[
					'unchangeble',
					'unchangeible',
				],
				'unchangeably'=>[
					'unchangeabally',
					'unchangeabaly',
					'unchangeabely',
					'unchangeablly',
				],
				'uncharitable'=>[
					'uncharitible',
				],
				'uncharitably'=>[
					'uncharitabally',
					'uncharitabaly',
					'uncharitabely',
					'uncharitablly',
				],
				'unchary'=>[
					'unchery',
				],
				'unchastely'=>[
					'unchastly',
				],
				'unchauvinistic'=>[
					'unchauvinastic',
				],
				'unchivalrously'=>[
					'unchivalrousally',
					'unchivalrousaly',
					'unchivalrousely',
					'unchivalrouslly',
				],
				'unchlorinated'=>[
					'unchlorinited',
				],
				'unchristened'=>[
					'unchristend',
				],
				'unchristian'=>[
					'unchristan',
				],
				'uncinal'=>[
					'uncinil',
				],
				'uncinariases'=>[
					'unciniriases',
				],
				'uncinariasis'=>[
					'unciniriasis',
				],
				'uncinate'=>[
					'uncinite',
				],
				'uncini'=>[
					'uncina',
				],
				'unclassifiable'=>[
					'unclasifiable',
					'unclassifiible',
				],
				'unclassified'=>[
					'unclassifeid',
					'unclasified',
					'unclassifid',
				],
				'unclassy'=>[
					'unclascy',
				],
				'uncleanlinesses'=>[
					'uncleanlinisses',
				],
				'uncleanly'=>[
					'uncleanally',
					'uncleanaly',
					'uncleanely',
					'uncleanlly',
				],
				'uncleannesses'=>[
					'uncleanesses',
				],
				'unclear'=>[
					'uncleer',
					'uncler',
				],
				'unclogging'=>[
					'uncloging',
				],
				'unclubbable'=>[
					'unclubable',
				],
				'uncoercively'=>[
					'uncoercivly',
				],
				'uncollected'=>[
					'uncolected',
				],
				'uncollectible'=>[
					'uncollectable',
				],
				'uncomely'=>[
					'uncomeally',
					'uncomealy',
					'uncomeely',
					'uncomelly',
					'uncomly',
				],
				'uncomfortable'=>[
					'uncomfrotable',
					'uncomfortible',
				],
				'uncommercial'=>[
					'uncomnercial',
				],
				'uncommitted'=>[
					'uncomnitted',
				],
				'uncommon'=>[
					'uncomnon',
				],
				'uncommonnesses'=>[
					'uncommonesses',
					'uncomnonnesses',
				],
				'uncommunicable'=>[
					'uncommunicible',
					'uncomnunicable',
				],
				'uncommunicative'=>[
					'uncomnunicative',
				],
				'uncomplaining'=>[
					'uncomplainang',
				],
				'uncomplainingly'=>[
					'uncomplainangly',
					'uncomplainingally',
					'uncomplainingaly',
					'uncomplainingely',
					'uncomplaininglly',
				],
				'uncomplimentary'=>[
					'uncomplimantary',
					'uncomplimentery',
				],
				'uncompromisable'=>[
					'uncompromisible',
				],
				'unconcealed'=>[
					'unconceled',
				],
				'unconceivable'=>[
					'unconceivible',
					'unconcievable',
				],
				'unconfined'=>[
					'unconfinid',
				],
				'unconformable'=>[
					'unconformible',
				],
				'unconfusing'=>[
					'unconfuisng',
				],
				'unconnected'=>[
					'unconected',
				],
				'unconquerable'=>[
					'unconquerible',
				],
				'unconscionable'=>[
					'unconcionable',
					'unconcsionable',
					'unconscionible',
					'unconsionable',
				],
				'unconscious'=>[
					'unconcious',
					'unconscience',
					'unconsious',
					'unconcsious',
					'unconscous',
				],
				'unconsciously'=>[
					'unconsciencly',
					'unconsiously',
					'unconsciousally',
					'unconsciousaly',
					'unconsciousely',
					'unconsciouslly',
					'unconscously',
				],
				'unconsciousness'=>[
					'unconciousness',
					'unconcsiousness',
					'unconsiousness',
				],
				'unconstrained'=>[
					'unconstrainid',
				],
				'unconsummated'=>[
					'unconsumnated',
				],
				'uncontainable'=>[
					'uncontainible',
				],
				'uncontaminated'=>[
					'uncontaminited',
				],
				'uncontemporary'=>[
					'uncontemporery',
				],
				'uncontentious'=>[
					'uncontantious',
					'uncontentous',
				],
				'uncontrollable'=>[
					'uncontrolable',
					'uncontrollible',
				],
				'uncontrolled'=>[
					'uncontroled',
				],
				'unconventional'=>[
					'unconvential',
					'unconvantional',
				],
				'unconventionally'=>[
					'unconventionaly',
				],
				'uncoordinated'=>[
					'uncoordinited',
				],
				'uncopyrightable'=>[
					'uncopyrightible',
				],
				'uncorrectable'=>[
					'uncorrectible',
				],
				'uncorrected'=>[
					'uncorected',
				],
				'uncorroborated'=>[
					'uncoroborated',
				],
				'uncountable'=>[
					'uncountible',
				],
				'uncovenanted'=>[
					'uncovenented',
				],
				'uncredentialed'=>[
					'uncredantialed',
				],
				'uncropped'=>[
					'uncroped',
				],
				'uncrushable'=>[
					'uncrushible',
				],
				'unctuous'=>[
					'unctous',
				],
				'unctuously'=>[
					'unctously',
				],
				'unctuousness'=>[
					'unctousness',
				],
				'unctuousnesses'=>[
					'unctousnesses',
				],
				'uncultivable'=>[
					'uncultivible',
				],
				'uncurious'=>[
					'uncurous',
				],
				'uncurtained'=>[
					'uncurtainid',
				],
				'uncustomary'=>[
					'uncustomery',
				],
				'undebatable'=>[
					'undebatible',
				],
				'undecadent'=>[
					'undecadant',
				],
				'undeceive'=>[
					'undecieve',
				],
				'undecidable'=>[
					'undecideable',
					'undecidible',
				],
				'undecipherable'=>[
					'undecipherible',
				],
				'undefeated'=>[
					'undefeted',
				],
				'undefined'=>[
					'undefinid',
				],
				'undeliverable'=>[
					'undeliverible',
				],
				'undeniable'=>[
					'undeniible',
				],
				'undeniably'=>[
					'undeniabally',
					'undeniabaly',
					'undeniabely',
					'undeniablly',
				],
				'undented'=>[
					'undanted',
				],
				'undependable'=>[
					'undependible',
				],
				'under'=>[
					'inder',
					'nder',
					'under under',
					'under under under',
				],
				'under its'=>[
					'under it\'s',
					'under its\'',
				],
				'underachieve'=>[
					'underacheive',
					'underachive',
				],
				'underbelly'=>[
					'underbelally',
					'underbelaly',
					'underbelely',
					'underbellly',
					'underbely',
				],
				'undercarriage'=>[
					'undercariage',
				],
				'undercarriages'=>[
					'undercariages',
				],
				'underclass'=>[
					'underclas',
				],
				'underclassman'=>[
					'underclasman',
				],
				'undercurrent'=>[
					'undercurent',
					'undercurrant',
				],
				'underdevelopment'=>[
					'undevelopment',
				],
				'underfinanced'=>[
					'underfininced',
				],
				'undergarment'=>[
					'undergarmant',
				],
				'undergraduate'=>[
					'undergradaute',
				],
				'undergraduates'=>[
					'undergradautes',
				],
				'underground'=>[
					'undergound',
				],
				'underlaid'=>[
					'underlayed',
				],
				'underlay'=>[
					'underlied',
				],
				'underlayment'=>[
					'underlaymant',
				],
				'underlie'=>[
					'underlei',
					'underly',
					'underli',
				],
				'underline'=>[
					'underlini',
				],
				'underlining'=>[
					'underlinang',
				],
				'underlying'=>[
					'underlaying',
				],
				'undermine'=>[
					'undermind',
					'undermini',
				],
				'undermining'=>[
					'underming',
				],
				'underneath'=>[
					'underneth',
				],
				'underpants'=>[
					'underpents',
				],
				'underpart'=>[
					'underpert',
				],
				'underpinning'=>[
					'underpining',
				],
				'underpinnings'=>[
					'underpinings',
				],
				'underprepared'=>[
					'underprepered',
				],
				'underpropping'=>[
					'underproping',
				],
				'underran'=>[
					'underan',
				],
				'underrate'=>[
					'underate',
				],
				'underrated'=>[
					'underated',
				],
				'underreact'=>[
					'undereact',
				],
				'underreport'=>[
					'undereport',
				],
				'underrun'=>[
					'underun',
				],
				'underscore'=>[
					'undercore',
					'undercsore',
					'undersore',
				],
				'undersea'=>[
					'underse',
				],
				'undersecretary'=>[
					'undersecretery',
				],
				'understandable'=>[
					'understandible',
				],
				'understandingly'=>[
					'understandingally',
					'understandingaly',
					'understandingely',
					'understandinglly',
				],
				'understatement'=>[
					'understatemant',
				],
				'understrapper'=>[
					'understraper',
				],
				'understrappers'=>[
					'understrapers',
				],
				'undersupplies'=>[
					'undersuplies',
				],
				'undersupply'=>[
					'undersuply',
					'undersuppally',
					'undersuppaly',
					'undersuppely',
					'undersupplly',
				],
				'undertenant'=>[
					'undertenent',
				],
				'undertook'=>[
					'undertok',
				],
				'underusing'=>[
					'underuisng',
				],
				'undervaluation'=>[
					'undervalaution',
				],
				'undervaluations'=>[
					'undervalautions',
				],
				'underwear'=>[
					'underware',
					'underweer',
					'underwer',
				],
				'underweight'=>[
					'underwieght',
				],
				'underweights'=>[
					'underwieghts',
				],
				'underwent'=>[
					'underwant',
				],
				'undescended'=>[
					'undecended',
					'undecsended',
					'undesended',
				],
				'undescribable'=>[
					'undescribible',
				],
				'undesirable'=>[
					'undesirible',
				],
				'undetectable'=>[
					'undetectible',
				],
				'undetected'=>[
					'un-detected',
				],
				'undeterminable'=>[
					'undeterminible',
				],
				'undetermined'=>[
					'undeterminid',
				],
				'undeterred'=>[
					'undetered',
				],
				'undiagnosable'=>[
					'undiagnosible',
				],
				'undies'=>[
					'undeis',
					'undis',
				],
				'undigestible'=>[
					'undigestable',
				],
				'undignified'=>[
					'undignifeid',
					'undignifid',
				],
				'undiminished'=>[
					'undiminashed',
				],
				'undimmed'=>[
					'undimned',
				],
				'undine'=>[
					'undini',
				],
				'undischarged'=>[
					'undicharged',
					'undicsharged',
					'undisharged',
				],
				'undisciplined'=>[
					'undiciplined',
					'undicsiplined',
					'undisciplinid',
					'undisiplined',
				],
				'undisclosed'=>[
					'undiclosed',
					'undicslosed',
					'undislosed',
				],
				'undiscoverable'=>[
					'undicoverable',
					'undicsoverable',
					'undiscoverible',
					'undisoverable',
				],
				'undiscovered'=>[
					'undicovered',
					'undicsovered',
					'undisovered',
				],
				'undiscussed'=>[
					'undicsussed',
					'undicussed',
					'undiscused',
					'undisussed',
				],
				'undissociated'=>[
					'undisociated',
				],
				'undissolved'=>[
					'undisolved',
				],
				'undoable'=>[
					'undoible',
				],
				'undoctrinaire'=>[
					'undoctriniire',
				],
				'undocumented'=>[
					'undocumanted',
				],
				'undoubtable'=>[
					'undoubtible',
				],
				'undoubtedly'=>[
					'undoubtably',
				],
				'undrained'=>[
					'undrainid',
				],
				'undress'=>[
					'undres',
				],
				'undressed'=>[
					'undresed',
				],
				'undrinkable'=>[
					'undrinkible',
				],
				'undular'=>[
					'unduler',
				],
				'unduly'=>[
					'undually',
					'undualy',
					'unduely',
					'undully',
				],
				'unearned'=>[
					'unerned',
				],
				'unearthlinesses'=>[
					'unearthlinisses',
				],
				'unearthly'=>[
					'unearthally',
					'unearthaly',
					'unearthely',
					'unearthlly',
					'unerthly',
				],
				'uneasy'=>[
					'uneacy',
					'unesy',
				],
				'uneatable'=>[
					'uneatible',
				],
				'unedible'=>[
					'unedable',
				],
				'unelectable'=>[
					'unelectible',
				],
				'unembarrassed'=>[
					'unembarassed',
					'unembarrased',
				],
				'unembellished'=>[
					'unembelished',
				],
				'unemployable'=>[
					'unemployible',
				],
				'unemployment'=>[
					'unnemployment',
					'unemploymant',
				],
				'unendurable'=>[
					'unendurible',
				],
				'unenforceable'=>[
					'unenforceble',
					'unenforceible',
				],
				'unenlightened'=>[
					'unenlightend',
				],
				'unenterprising'=>[
					'unanterprising',
				],
				'unenthusiastic'=>[
					'unanthusiastic',
					'unenthuisastic',
				],
				'unenviable'=>[
					'unenviible',
				],
				'unenvious'=>[
					'unenvous',
				],
				'unequal'=>[
					'uneqaul',
				],
				'unequaled'=>[
					'uneqauled',
				],
				'unequally'=>[
					'unequaly',
				],
				'unequals'=>[
					'uneqauls',
				],
				'unerring'=>[
					'unering',
				],
				'unescapable'=>[
					'unescapible',
				],
				'unessential'=>[
					'unesential',
				],
				'unevaluated'=>[
					'unevalauted',
				],
				'unexamined'=>[
					'unexaminid',
				],
				'unexceptionable'=>[
					'unexceptionible',
				],
				'unexceptionably'=>[
					'unexceptionabally',
					'unexceptionabaly',
					'unexceptionabely',
					'unexceptionablly',
				],
				'unexcitable'=>[
					'unexcitible',
				],
				'unexpectedly'=>[
					'unexpectadly',
					'unexpectantly',
					'unexpectedally',
					'unexpectedaly',
					'unexpectedely',
					'unexpectedlly',
				],
				'unexplainable'=>[
					'unexplainible',
				],
				'unexplained'=>[
					'unexplainid',
				],
				'unexpressed'=>[
					'unexpresed',
				],
				'unexpressive'=>[
					'unexpresive',
				],
				'unextraordinary'=>[
					'unextraordinery',
					'unextraordiniry',
				],
				'unfamiliar'=>[
					'unfamilar',
					'unfamilier',
				],
				'unfancy'=>[
					'unfansy',
				],
				'unfashionable'=>[
					'unfashionible',
				],
				'unfastened'=>[
					'unfastend',
				],
				'unfastidious'=>[
					'unfastidous',
				],
				'unfathomable'=>[
					'unfathomible',
				],
				'unfavorable'=>[
					'unfavorible',
				],
				'unfazed'=>[
					'unphased',
				],
				'unfeasible'=>[
					'unfeasable',
					'unfesible',
				],
				'unfeigned'=>[
					'unfiegned',
				],
				'unfeminine'=>[
					'unfeminane',
					'unfeminini',
				],
				'unfence'=>[
					'unfance',
				],
				'unfilled'=>[
					'unfiled',
				],
				'unfinished'=>[
					'unfinnished',
					'unfinashed',
				],
				'unflagging'=>[
					'unflaging',
				],
				'unflaggingly'=>[
					'unflagingly',
				],
				'unflappability'=>[
					'unflapability',
				],
				'unflappable'=>[
					'unflapable',
					'unflappible',
				],
				'unflapped'=>[
					'unflaped',
				],
				'unfledged'=>[
					'unfleged',
				],
				'unforeseeable'=>[
					'unforeseeble',
					'unforeseeible',
				],
				'unforeseen'=>[
					'unforseen',
				],
				'unforgettable'=>[
					'unforgettible',
				],
				'unforgivable'=>[
					'unforgivible',
				],
				'unfortified'=>[
					'unfortifeid',
					'unfortifid',
				],
				'unfortunately'=>[
					'unforetunately',
					'unfortunatley',
					'unfortunatly',
					'unfortuntely',
				],
				'unfrequented'=>[
					'unfrequanted',
				],
				'unfriendly'=>[
					'unfreindly',
					'unfriendally',
					'unfriendaly',
					'unfriendely',
					'unfriendlly',
					'unfrindly',
				],
				'unfulfillable'=>[
					'unfulfillible',
				],
				'unfulfilled'=>[
					'unfulfiled',
				],
				'unfunny'=>[
					'unfuny',
				],
				'unfussy'=>[
					'unfuscy',
				],
				'ungainly'=>[
					'ungainally',
					'ungainaly',
					'ungainely',
					'ungainlly',
				],
				'ungentlemanly'=>[
					'ungantlemanly',
					'ungentlemanally',
					'ungentlemanaly',
					'ungentlemanely',
					'ungentlemanlly',
				],
				'ungently'=>[
					'ungentally',
					'ungentaly',
					'ungentely',
					'ungentlly',
				],
				'ungerminated'=>[
					'ungerminited',
				],
				'unglamorized'=>[
					'unglamourized',
				],
				'unglamorous'=>[
					'unglamourous',
				],
				'ungodly'=>[
					'ungodally',
					'ungodaly',
					'ungodely',
					'ungodlly',
				],
				'ungovernable'=>[
					'ungovernible',
				],
				'ungracious'=>[
					'ungracous',
				],
				'ungraciously'=>[
					'ungracously',
				],
				'ungrammatical'=>[
					'ungramnatical',
				],
				'ungraspable'=>[
					'ungraspible',
				],
				'ungual'=>[
					'ungaul',
				],
				'unguard'=>[
					'ungaurd',
				],
				'unguarded'=>[
					'ungaurded',
				],
				'unguardedly'=>[
					'ungaurdedly',
				],
				'unguardednesses'=>[
					'ungaurdednesses',
				],
				'unguessable'=>[
					'unguessible',
				],
				'ungular'=>[
					'unguler',
				],
				'unhandsomely'=>[
					'unhandsomly',
				],
				'unhappinesses'=>[
					'unhapinesses',
				],
				'unhappy'=>[
					'unhapy',
				],
				'unhealthful'=>[
					'unhelthful',
				],
				'unhealthinesses'=>[
					'unhealthinisses',
				],
				'unhealthy'=>[
					'unhelthy',
				],
				'unheard'=>[
					'unherd',
				],
				'unhedged'=>[
					'unheged',
				],
				'unholy'=>[
					'unhoally',
					'unhoaly',
					'unhoely',
					'unholly',
				],
				'unhonored'=>[
					'unhonoured',
				],
				'unhousing'=>[
					'unhouisng',
				],
				'unhumanly'=>[
					'unhumanally',
					'unhumanaly',
					'unhumanely',
					'unhumanlly',
				],
				'unhumorous'=>[
					'unhumourous',
				],
				'unhurried'=>[
					'unhurreid',
					'unhuried',
					'unhurrid',
				],
				'unhygienic'=>[
					'unhygeinic',
					'unhyginic',
				],
				'unicellular'=>[
					'unicelluler',
					'unicelular',
				],
				'unidentifiable'=>[
					'unidantifiable',
					'unidentifiible',
				],
				'unidentified'=>[
					'unidentifeid',
					'unindentified',
					'unidantified',
					'unidentifid',
				],
				'unified'=>[
					'unifed',
				],
				'unifilar'=>[
					'unifiler',
				],
				'uniform'=>[
					'unifrom',
				],
				'uniformitarian'=>[
					'uniformitaran',
				],
				'uniformly'=>[
					'uniformally',
					'uniformaly',
					'uniformely',
					'uniformlly',
				],
				'unignorable'=>[
					'unignourable',
				],
				'unilateral'=>[
					'unilatreal',
				],
				'unilaterally'=>[
					'unilatreally',
				],
				'unilinear'=>[
					'unilineer',
					'uniliniar',
				],
				'unilingual'=>[
					'unilingaul',
				],
				'unilluminating'=>[
					'unilluminiting',
				],
				'unillusioned'=>[
					'unilluisoned',
				],
				'unilocular'=>[
					'uniloculer',
				],
				'unimaginable'=>[
					'unimaginible',
				],
				'unimaginably'=>[
					'unimaginabally',
					'unimaginabaly',
					'unimaginabely',
					'unimaginablly',
					'unimaginibly',
				],
				'unimaginative'=>[
					'unimaginitive',
				],
				'unimaginatively'=>[
					'unimaginativeally',
					'unimaginativealy',
					'unimaginativeely',
					'unimaginativelly',
					'unimaginativly',
					'unimaginitively',
				],
				'unimpassioned'=>[
					'unimpasioned',
				],
				'unimpeachable'=>[
					'unimpeachible',
					'unimpechable',
				],
				'unimportant'=>[
					'unimportent',
				],
				'unimpressed'=>[
					'unimpresed',
				],
				'unimpressive'=>[
					'unimpresive',
				],
				'uninformatively'=>[
					'uninformativeally',
					'uninformativealy',
					'uninformativeely',
					'uninformativelly',
					'uninformativly',
				],
				'uninhabitable'=>[
					'uninhabitible',
				],
				'uninitiate'=>[
					'uninatiate',
				],
				'uninitiated'=>[
					'uninatiated',
				],
				'uninsurable'=>[
					'uninsurible',
				],
				'unintellectual'=>[
					'unintellectaul',
				],
				'unintelligent'=>[
					'uninteligent',
					'unintelligant',
				],
				'unintelligently'=>[
					'unintelligentally',
					'unintelligentaly',
					'unintelligentely',
					'unintelligentlly',
				],
				'unintelligible'=>[
					'uninteligible',
					'unintelligable',
				],
				'unintentional'=>[
					'unintantional',
				],
				'uninterrupted'=>[
					'uninterupted',
				],
				'uninterruptedly'=>[
					'uninterruptedally',
					'uninterruptedaly',
					'uninterruptedely',
					'uninterruptedlly',
					'uninteruptedly',
				],
				'union'=>[
					'un1on',
				],
				'unions'=>[
					'un1ons',
				],
				'uniparentally'=>[
					'uniperentally',
				],
				'uniparous'=>[
					'uniperous',
				],
				'uniplanar'=>[
					'uniplaner',
				],
				'unipolar'=>[
					'unipoler',
				],
				'uniquely'=>[
					'uniquly',
				],
				'unisexual'=>[
					'unisexaul',
				],
				'unisexualities'=>[
					'unisexaulities',
				],
				'unit'=>[
					'unit unit',
					'unit unit unit',
					'unti',
				],
				'unitarian'=>[
					'unitaran',
				],
				'unitary'=>[
					'unitery',
				],
				'united'=>[
					'unitd',
					'unitesd',
					'untied',
				],
				'united kingdom'=>[
					'united kingdon',
					'untied kingdom',
				],
				'united states'=>[
					'unitd states',
					'united staes',
					'united stats',
					'unites states',
					'untied states',
				],
				'universally'=>[
					'universaly',
				],
				'universities'=>[
					'univerisities',
					'univeristies',
					'univerities',
					'universitaries',
					'universites',
					'universties',
					'univesities',
					'unviersities',
				],
				'university'=>[
					'unieversity',
					'univeristy',
					'univerity',
					'universitar',
					'universitaries',
					'universitary',
					'universty',
					'univesity',
					'unversity',
					'unviersity',
				],
				'unjustifiable'=>[
					'unjustifiible',
				],
				'unjustified'=>[
					'unjustifeid',
					'unjustifid',
				],
				'unjustly'=>[
					'unjustally',
					'unjustaly',
					'unjustely',
					'unjustlly',
				],
				'unkennel'=>[
					'unkenel',
				],
				'unkindly'=>[
					'unkindally',
					'unkindaly',
					'unkindely',
					'unkindlly',
				],
				'unknot'=>[
					'unkot',
				],
				'unknots'=>[
					'unkots',
				],
				'unknotted'=>[
					'unkotted',
				],
				'unknotting'=>[
					'unkotting',
				],
				'unknowabilities'=>[
					'unkowabilities',
				],
				'unknowability'=>[
					'unkowability',
				],
				'unknowable'=>[
					'unknowible',
					'unkowable',
				],
				'unknowing'=>[
					'unkowing',
				],
				'unknowingly'=>[
					'unkowingly',
				],
				'unknowings'=>[
					'unkowings',
				],
				'unknowledgeable'=>[
					'unknowledgeible',
					'unknowlegeable',
					'unkowledgeable',
				],
				'unknown'=>[
					'unknow',
					'unkown',
				],
				'unknowns'=>[
					'unkowns',
				],
				'unleaded'=>[
					'unleded',
				],
				'unleash'=>[
					'unlesh',
				],
				'unleavened'=>[
					'unleavend',
				],
				'unless'=>[
					'unles',
				],
				'unlethal'=>[
					'unletal',
				],
				'unlike'=>[
					'ulike',
				],
				'unlikely'=>[
					'unlikley',
					'unlikly',
					'unlikeally',
					'unlikealy',
					'unlikeely',
					'unlikelly',
				],
				'unlined'=>[
					'unlinid',
				],
				'unlistenable'=>[
					'unlistenible',
				],
				'unliterary'=>[
					'unliterery',
				],
				'unlivable'=>[
					'unlivible',
				],
				'unlively'=>[
					'unlivly',
				],
				'unloosened'=>[
					'unloosend',
				],
				'unlovable'=>[
					'unlovible',
				],
				'unlovely'=>[
					'unloveally',
					'unlovealy',
					'unloveely',
					'unlovelly',
					'unlovly',
				],
				'unmacho'=>[
					'umacho',
					'unacho',
				],
				'unmade'=>[
					'umade',
					'unade',
				],
				'unmagnified'=>[
					'umagnified',
					'unagnified',
				],
				'unmailed'=>[
					'umailed',
					'unailed',
				],
				'unmake'=>[
					'umake',
					'unake',
				],
				'unmaker'=>[
					'umaker',
					'unaker',
				],
				'unmakers'=>[
					'umakers',
					'unakers',
				],
				'unmakes'=>[
					'umakes',
					'unakes',
				],
				'unmaking'=>[
					'umaking',
					'unaking',
				],
				'unmalicious'=>[
					'umalicious',
					'unalicious',
					'unmalicous',
				],
				'unmaliciously'=>[
					'umaliciously',
					'unaliciously',
					'unmaliciousally',
					'unmaliciousaly',
					'unmaliciousely',
					'unmaliciouslly',
					'unmalicously',
				],
				'unman'=>[
					'uman',
					'unan',
				],
				'unmanageable'=>[
					'umnanageable',
					'umanageable',
					'unanageable',
					'unmanageble',
					'unmanageible',
				],
				'unmanageably'=>[
					'umanageably',
					'unanageably',
					'unmanageabally',
					'unmanageabaly',
					'unmanageabely',
					'unmanageablly',
				],
				'unmanaged'=>[
					'umanaged',
					'unanaged',
				],
				'unmaneuverable'=>[
					'unmanouverable',
				],
				'unmanful'=>[
					'umanful',
					'unanful',
				],
				'unmanipulated'=>[
					'umanipulated',
					'unanipulated',
				],
				'unmanlier'=>[
					'umanlier',
					'unanlier',
				],
				'unmanliest'=>[
					'umanliest',
					'unanliest',
				],
				'unmanliness'=>[
					'umanliness',
					'unanliness',
				],
				'unmanlinesses'=>[
					'umanlinesses',
					'unanlinesses',
				],
				'unmanly'=>[
					'umanly',
					'unanly',
					'unmanally',
					'unmanaly',
					'unmanely',
					'unmanlly',
				],
				'unmanned'=>[
					'umanned',
					'unanned',
					'unmaned',
				],
				'unmannered'=>[
					'umannered',
					'unannered',
					'unmanered',
				],
				'unmanneredly'=>[
					'umanneredly',
					'unanneredly',
					'unmanneredally',
					'unmanneredaly',
					'unmanneredely',
					'unmanneredlly',
				],
				'unmannerliness'=>[
					'umannerliness',
					'unannerliness',
					'unmanerliness',
				],
				'unmannerly'=>[
					'umannerly',
					'unannerly',
					'unmanerly',
					'unmannerally',
					'unmanneraly',
					'unmannerely',
					'unmannerlly',
				],
				'unmanning'=>[
					'umanning',
					'unanning',
				],
				'unmannish'=>[
					'umannish',
					'unannish',
				],
				'unmans'=>[
					'umans',
					'unans',
				],
				'unmapped'=>[
					'umapped',
					'unapped',
					'unmaped',
				],
				'unmarked'=>[
					'umarked',
					'unarked',
				],
				'unmarketable'=>[
					'umarketable',
					'unarketable',
					'unmarketible',
				],
				'unmarred'=>[
					'umarred',
					'unarred',
					'unmared',
				],
				'unmarried'=>[
					'unmarreid',
					'umarried',
					'unarried',
					'unmaried',
					'unmarrid',
				],
				'unmarrieds'=>[
					'umarrieds',
					'unarrieds',
				],
				'unmasculine'=>[
					'umasculine',
					'unasculine',
				],
				'unmask'=>[
					'umask',
					'unask',
				],
				'unmasked'=>[
					'umasked',
					'unasked',
				],
				'unmasker'=>[
					'umasker',
					'unasker',
				],
				'unmaskers'=>[
					'umaskers',
					'unaskers',
				],
				'unmasking'=>[
					'umasking',
					'unasking',
				],
				'unmasks'=>[
					'umasks',
					'unasks',
				],
				'unmatchable'=>[
					'umatchable',
					'unatchable',
					'unmatchible',
				],
				'unmatched'=>[
					'umatched',
					'unatched',
				],
				'unmated'=>[
					'umated',
					'unated',
				],
				'unmatted'=>[
					'umatted',
					'unatted',
				],
				'unmatured'=>[
					'umatured',
					'unatured',
				],
				'unmeaning'=>[
					'umeaning',
					'uneaning',
				],
				'unmeant'=>[
					'umeant',
					'uneant',
				],
				'unmeasurable'=>[
					'umeasurable',
					'uneasurable',
					'unmeasurible',
					'unmesurable',
				],
				'unmeasured'=>[
					'umeasured',
					'uneasured',
					'unmesured',
				],
				'unmechanized'=>[
					'umechanized',
					'unechanized',
				],
				'unmediated'=>[
					'umediated',
					'unediated',
				],
				'unmedicated'=>[
					'umedicated',
					'unedicated',
				],
				'unmeet'=>[
					'umeet',
					'uneet',
				],
				'unmeetly'=>[
					'umeetly',
					'uneetly',
				],
				'unmellow'=>[
					'umellow',
					'unellow',
				],
				'unmelodious'=>[
					'umelodious',
					'unelodious',
					'unmelodous',
				],
				'unmelodiousness'=>[
					'umelodiousness',
					'unelodiousness',
				],
				'unmelted'=>[
					'umelted',
					'unelted',
				],
				'unmemorable'=>[
					'umemorable',
					'unemorable',
					'unmemorible',
					'unmemourable',
					'unmorable',
				],
				'unmemorably'=>[
					'umemorably',
					'unemorably',
					'unmemourably',
					'unmorably',
				],
				'unmended'=>[
					'umended',
					'unended',
				],
				'unmentionable'=>[
					'umentionable',
					'unentionable',
					'unmantionable',
					'unmentionible',
				],
				'unmentionables'=>[
					'umentionables',
					'unentionables',
				],
				'unmerciful'=>[
					'umerciful',
					'unerciful',
				],
				'unmercifully'=>[
					'umercifully',
					'unercifully',
				],
				'unmerited'=>[
					'umerited',
					'unerited',
				],
				'unmerry'=>[
					'umerry',
					'unerry',
				],
				'unmesh'=>[
					'umesh',
					'unesh',
				],
				'unmeshed'=>[
					'umeshed',
					'uneshed',
				],
				'unmeshes'=>[
					'umeshes',
					'uneshes',
				],
				'unmeshing'=>[
					'umeshing',
					'uneshing',
				],
				'unmet'=>[
					'umet',
					'unet',
				],
				'unmetabolized'=>[
					'umetabolized',
					'unetabolized',
				],
				'unmew'=>[
					'umew',
					'unew',
				],
				'unmewed'=>[
					'umewed',
					'unewed',
				],
				'unmewing'=>[
					'umewing',
					'unewing',
				],
				'unmews'=>[
					'umews',
					'unews',
				],
				'unmilitary'=>[
					'umilitary',
					'unilitary',
					'unmilitery',
				],
				'unmilled'=>[
					'umilled',
					'unilled',
				],
				'unmindful'=>[
					'umindful',
					'unindful',
				],
				'unmined'=>[
					'umined',
					'unined',
				],
				'unmingle'=>[
					'umingle',
					'uningle',
				],
				'unmingled'=>[
					'umingled',
					'uningled',
				],
				'unmingles'=>[
					'umingles',
					'uningles',
				],
				'unmingling'=>[
					'umingling',
					'uningling',
				],
				'unmistakable'=>[
					'unmistakeable',
					'umistakable',
					'unistakable',
					'unmistakible',
				],
				'unmistakably'=>[
					'unmistakeably',
					'umistakably',
					'unistakably',
					'unmistakabally',
					'unmistakabaly',
					'unmistakabely',
					'unmistakablly',
				],
				'unmiter'=>[
					'umiter',
					'uniter',
				],
				'unmitered'=>[
					'umitered',
					'unitered',
				],
				'unmitering'=>[
					'umitering',
					'unitering',
				],
				'unmiters'=>[
					'umiters',
					'uniters',
				],
				'unmitigated'=>[
					'umitigated',
					'unitigated',
				],
				'unmitigatedly'=>[
					'umitigatedly',
					'unitigatedly',
				],
				'unmitigatedness'=>[
					'umitigatedness',
					'unitigatedness',
				],
				'unmitre'=>[
					'umitre',
					'unitre',
				],
				'unmitred'=>[
					'umitred',
					'unitred',
				],
				'unmitres'=>[
					'umitres',
					'unitres',
				],
				'unmitring'=>[
					'umitring',
					'unitring',
				],
				'unmix'=>[
					'umix',
					'unix',
				],
				'unmixable'=>[
					'umixable',
					'unixable',
				],
				'unmixed'=>[
					'umixed',
					'unixed',
				],
				'unmixedly'=>[
					'umixedly',
					'unixedly',
				],
				'unmixes'=>[
					'umixes',
					'unixes',
				],
				'unmixing'=>[
					'umixing',
					'unixing',
				],
				'unmixt'=>[
					'umixt',
					'unixt',
				],
				'unmodernized'=>[
					'umodernized',
					'unodernized',
				],
				'unmodified'=>[
					'unmodifeid',
					'umodified',
					'unmodifid',
					'unodified',
				],
				'unmodish'=>[
					'umodish',
					'unodish',
				],
				'unmold'=>[
					'umold',
					'unold',
				],
				'unmolded'=>[
					'umolded',
					'unolded',
				],
				'unmolding'=>[
					'umolding',
					'unolding',
				],
				'unmolds'=>[
					'umolds',
					'unolds',
				],
				'unmolested'=>[
					'umolested',
					'unolested',
				],
				'unmolten'=>[
					'umolten',
					'unolten',
				],
				'unmonitored'=>[
					'umonitored',
					'unonitored',
				],
				'unmoor'=>[
					'umoor',
					'unoor',
				],
				'unmoored'=>[
					'umoored',
					'unoored',
				],
				'unmooring'=>[
					'umooring',
					'unooring',
				],
				'unmoors'=>[
					'umoors',
					'unoors',
				],
				'unmoral'=>[
					'umoral',
					'unmoural',
					'unoral',
				],
				'unmoralities'=>[
					'umoralities',
					'unmouralities',
					'unoralities',
				],
				'unmorality'=>[
					'umorality',
					'unmourality',
					'unorality',
				],
				'unmorally'=>[
					'umorally',
					'unmourally',
					'unorally',
				],
				'unmortise'=>[
					'umortise',
					'unmourtise',
					'unortise',
				],
				'unmortised'=>[
					'umortised',
					'unmourtised',
					'unortised',
				],
				'unmortises'=>[
					'umortises',
					'unmourtises',
					'unortises',
				],
				'unmortising'=>[
					'umortising',
					'unmourtising',
					'unortising',
				],
				'unmotivated'=>[
					'umotivated',
					'unotivated',
				],
				'unmounted'=>[
					'umounted',
					'unounted',
				],
				'unmourned'=>[
					'umourned',
					'unourned',
				],
				'unmovable'=>[
					'umovable',
					'unovable',
				],
				'unmoved'=>[
					'umoved',
					'unoved',
				],
				'unmoving'=>[
					'umoving',
					'unoving',
				],
				'unmown'=>[
					'umown',
					'unown',
				],
				'unmuffle'=>[
					'umuffle',
					'unuffle',
				],
				'unmuffled'=>[
					'umuffled',
					'unuffled',
				],
				'unmuffles'=>[
					'umuffles',
					'unuffles',
				],
				'unmuffling'=>[
					'umuffling',
					'unuffling',
				],
				'unmusical'=>[
					'umusical',
					'unmuiscal',
					'unusical',
				],
				'unmuzzle'=>[
					'umuzzle',
					'unuzzle',
				],
				'unmuzzled'=>[
					'umuzzled',
					'unuzzled',
				],
				'unmuzzles'=>[
					'umuzzles',
					'unuzzles',
				],
				'unmuzzling'=>[
					'umuzzling',
					'unuzzling',
				],
				'unmyelinated'=>[
					'umyelinated',
					'unmyelinited',
					'unyelinated',
				],
				'unnail'=>[
					'unail',
				],
				'unnameable'=>[
					'unameable',
					'unnameible',
				],
				'unnamed'=>[
					'unnammed',
					'unamed',
				],
				'unnatural'=>[
					'un-natural',
					'unatural',
				],
				'unnaturalness'=>[
					'unaturalness',
				],
				'unnaturalnesses'=>[
					'unaturalnesses',
				],
				'unnecessarily'=>[
					'unneccesarily',
					'unneccessarily',
					'unnecesarily',
					'unecessarily',
				],
				'unnecessary'=>[
					'un-necessary',
					'unecessary',
					'unneccesary',
					'unneccessary',
					'unnecesary',
					'unnessary',
					'unnecessery',
				],
				'unneeded'=>[
					'uneeded',
				],
				'unnerve'=>[
					'unerve',
				],
				'unnerving'=>[
					'un-nerving',
				],
				'unnilhexium'=>[
					'unilhexium',
				],
				'unnilpentium'=>[
					'unilpentium',
				],
				'unnilpentiums'=>[
					'unilpentiums',
				],
				'unnilquadium'=>[
					'unilquadium',
					'unnilqaudium',
				],
				'unnilquadiums'=>[
					'unilquadiums',
				],
				'unnoisy'=>[
					'unnoicy',
				],
				'unnoticeable'=>[
					'unoticeable',
					'unnoticeble',
					'unnoticeible',
				],
				'unnoticed'=>[
					'unoticed',
				],
				'unnumbered'=>[
					'unumbered',
				],
				'unobjectionable'=>[
					'unobjectionible',
				],
				'unobservable'=>[
					'unobservible',
				],
				'unobtainable'=>[
					'unobtainible',
				],
				'unobtrusive'=>[
					'unobtruisve',
				],
				'unobtrusively'=>[
					'unobtruisvely',
					'unobtrusivly',
				],
				'unobtrusiveness'=>[
					'unobtruisveness',
				],
				'unoccupied'=>[
					'unoccupeid',
					'unoccupid',
					'unocupied',
				],
				'unofficial'=>[
					'un-official',
					'unoffical',
				],
				'unofficially'=>[
					'unofficialy',
				],
				'unopened'=>[
					'unopend',
				],
				'unopposed'=>[
					'unoposed',
				],
				'unordered'=>[
					'unourdered',
				],
				'unorderly'=>[
					'unourderly',
				],
				'unorganized'=>[
					'unourganized',
				],
				'unoriginal'=>[
					'unoriginil',
					'unouriginal',
				],
				'unornamented'=>[
					'unornamanted',
					'unournamented',
				],
				'unornate'=>[
					'unournate',
				],
				'unorthodox'=>[
					'unorthadox',
					'unourthodox',
				],
				'unorthodoxies'=>[
					'unourthodoxies',
				],
				'unorthodoxly'=>[
					'unourthodoxly',
				],
				'unorthodoxy'=>[
					'unourthodoxy',
				],
				'unostentatious'=>[
					'unostantatious',
					'unostentatous',
				],
				'unpalatable'=>[
					'unpalatible',
				],
				'unparalleled'=>[
					'unparaleled',
					'unperalleled',
				],
				'unparasitized'=>[
					'unperasitized',
				],
				'unpardonable'=>[
					'unpardonible',
					'unperdonable',
				],
				'unparliamentary'=>[
					'unparliamantary',
					'unparliamentery',
					'unperliamentary',
				],
				'unpeaceful'=>[
					'unpeacefui',
				],
				'unpedantic'=>[
					'unpedentic',
				],
				'unpegged'=>[
					'unpeged',
				],
				'unperceived'=>[
					'unpercieved',
				],
				'unperformable'=>[
					'unperformible',
				],
				'unpersuaded'=>[
					'unpersauded',
				],
				'unpersuasive'=>[
					'unpersausive',
				],
				'unplanned'=>[
					'unplaned',
				],
				'unplausible'=>[
					'unplauisble',
					'unplausable',
				],
				'unplayable'=>[
					'unplayible',
				],
				'unpleasant'=>[
					'unplesant',
					'unpleasent',
				],
				'unpleasantness'=>[
					'unpleasantnes',
					'unpleasentness',
					'unplesantness',
				],
				'unpledged'=>[
					'unpleged',
				],
				'unplugged'=>[
					'unpluged',
				],
				'unplugging'=>[
					'unpluging',
				],
				'unpolluted'=>[
					'unpoluted',
				],
				'unpopular'=>[
					'unpopuler',
				],
				'unprecedented'=>[
					'unpresidented',
					'unprecedanted',
				],
				'unprecedentedly'=>[
					'unprecedantedly',
					'unprecedentedally',
					'unprecedentedaly',
					'unprecedentedely',
					'unprecedentedlly',
				],
				'unpredictable'=>[
					'unpredictible',
				],
				'unprepared'=>[
					'unprepered',
				],
				'unpreparedness'=>[
					'unpreperedness',
				],
				'unprepossessing'=>[
					'unprepossesing',
				],
				'unpressurized'=>[
					'unpresurized',
				],
				'unpretentious'=>[
					'unpretantious',
					'unpretentous',
				],
				'unpretentiously'=>[
					'unpretentously',
				],
				'unprintable'=>[
					'unprintible',
				],
				'unprocessed'=>[
					'unprocesed',
				],
				'unprofessional'=>[
					'unprofesional',
				],
				'unprofitable'=>[
					'unprofitible',
				],
				'unprofitably'=>[
					'unprofitabally',
					'unprofitabaly',
					'unprofitabely',
					'unprofitablly',
				],
				'unprogrammable'=>[
					'unprogrammible',
					'unprogramnable',
				],
				'unprogressive'=>[
					'unprogresive',
				],
				'unpronounceable'=>[
					'unpronounceble',
					'unpronounceible',
				],
				'unpropitious'=>[
					'unpropitous',
				],
				'unprovable'=>[
					'unprovible',
				],
				'unpublishable'=>[
					'unpublishible',
				],
				'unpunctual'=>[
					'unpunctaul',
				],
				'unpunctualities'=>[
					'unpunctaulities',
				],
				'unpunctuated'=>[
					'unpunctauted',
				],
				'unpurely'=>[
					'unpurly',
				],
				'unqualified'=>[
					'unqualifeid',
					'unqaulified',
					'unqualifid',
				],
				'unquantifiable'=>[
					'unqauntifiable',
					'unquantifiible',
					'unquentifiable',
				],
				'unquenchable'=>[
					'unquenchible',
				],
				'unquestionable'=>[
					'unquestionible',
				],
				'unquestioningly'=>[
					'unquestioningally',
					'unquestioningaly',
					'unquestioningely',
					'unquestioninglly',
				],
				'unquiet'=>[
					'unqueit',
					'unquit',
				],
				'unquote'=>[
					'unqote',
				],
				'unquoted'=>[
					'unqoted',
				],
				'unquotes'=>[
					'unqotes',
				],
				'unquoting'=>[
					'unqoting',
				],
				'unreachable'=>[
					'unreachible',
					'unrechable',
				],
				'unreadable'=>[
					'unreadible',
					'unredable',
				],
				'unreal'=>[
					'unrel',
				],
				'unrealistic'=>[
					'unrelistic',
				],
				'unreality'=>[
					'unrelity',
				],
				'unrealizable'=>[
					'unrealizible',
					'unrelizable',
				],
				'unrealized'=>[
					'unrelized',
				],
				'unreasonable'=>[
					'unreasonible',
					'unresonable',
				],
				'unreasonably'=>[
					'unreasonabally',
					'unreasonabaly',
					'unreasonabely',
					'unreasonablly',
				],
				'unreasoning'=>[
					'unresoning',
				],
				'unreclaimable'=>[
					'unreclaimible',
				],
				'unrecognizable'=>[
					'unrecognizible',
				],
				'unreconcilable'=>[
					'unreconcilible',
				],
				'unrecoverable'=>[
					'unrecoverible',
				],
				'unredeemable'=>[
					'unredeemible',
				],
				'unredressed'=>[
					'unredresed',
				],
				'unreferenced'=>[
					'unrefereced',
				],
				'unrefined'=>[
					'unrefinid',
				],
				'unregenerately'=>[
					'unregeneratly',
				],
				'unrehearsed'=>[
					'unrehersed',
				],
				'unreinforced'=>[
					'unrienforced',
				],
				'unrelenting'=>[
					'unrelanting',
				],
				'unreliable'=>[
					'unreliible',
				],
				'unrelieved'=>[
					'unreleived',
					'unrelived',
				],
				'unremarkable'=>[
					'unremarkible',
				],
				'unremarkably'=>[
					'unremarkabally',
					'unremarkabaly',
					'unremarkabely',
					'unremarkablly',
				],
				'unremembered'=>[
					'unrembered',
				],
				'unreminiscent'=>[
					'unreminascent',
				],
				'unremovable'=>[
					'unremovible',
				],
				'unrepeatable'=>[
					'unrepeatible',
					'unrepetable',
				],
				'unrepentant'=>[
					'unrepentent',
					'unrepantant',
				],
				'unrepentantly'=>[
					'unrepentantally',
					'unrepentantaly',
					'unrepentantely',
					'unrepentantlly',
				],
				'unrepresented'=>[
					'unrepresanted',
				],
				'unresolvable'=>[
					'unresolvible',
				],
				'unrespectable'=>[
					'unrespectible',
				],
				'unresponsively'=>[
					'unresponsivly',
				],
				'unrestrained'=>[
					'unrestrainid',
				],
				'unrevolutionary'=>[
					'unrevolutionery',
				],
				'unrigged'=>[
					'unriged',
				],
				'unrighteously'=>[
					'unrighteousally',
					'unrighteousaly',
					'unrighteousely',
					'unrighteouslly',
				],
				'unripely'=>[
					'unriply',
				],
				'unripened'=>[
					'unripend',
				],
				'unroll'=>[
					'unrol',
				],
				'unromantic'=>[
					'unromentic',
				],
				'unruly'=>[
					'unrually',
					'unrualy',
					'unruely',
					'unrully',
				],
				'unsafely'=>[
					'unsafly',
				],
				'unsaintly'=>[
					'unsaintally',
					'unsaintaly',
					'unsaintely',
					'unsaintlly',
				],
				'unsalaried'=>[
					'unsalareid',
					'unsalarid',
				],
				'unsalvageable'=>[
					'unsalvageible',
				],
				'unsanitary'=>[
					'unsanitery',
				],
				'unsatisfied'=>[
					'unsatisfeid',
					'unsatisfid',
				],
				'unsayable'=>[
					'unsayible',
				],
				'unscalable'=>[
					'unscalible',
				],
				'unscarred'=>[
					'unscared',
				],
				'unscathed'=>[
					'uncathed',
					'uncsathed',
					'unsathed',
				],
				'unscented'=>[
					'uncented',
					'uncsented',
					'unsented',
				],
				'unscheduled'=>[
					'uncheduled',
					'uncsheduled',
					'unsheduled',
				],
				'unscholarly'=>[
					'uncholarly',
					'uncsholarly',
					'unscholarally',
					'unscholaraly',
					'unscholarely',
					'unscholarlly',
					'unsholarly',
				],
				'unschooled'=>[
					'unchooled',
					'uncshooled',
					'unshooled',
				],
				'unscientific'=>[
					'unsceintific',
					'uncientific',
					'uncsientific',
					'unsciantific',
					'unscintific',
					'unsientific',
				],
				'unscramble'=>[
					'uncramble',
					'uncsramble',
					'unsramble',
				],
				'unscreened'=>[
					'uncreened',
					'uncsreened',
					'unscreend',
					'unsreened',
				],
				'unscrew'=>[
					'uncrew',
					'uncsrew',
					'unsrew',
				],
				'unscripted'=>[
					'uncripted',
					'uncsripted',
					'unsripted',
				],
				'unscriptural'=>[
					'uncriptural',
					'uncsriptural',
					'unsriptural',
				],
				'unscrupulous'=>[
					'uncrupulous',
					'uncsrupulous',
					'unsrupulous',
				],
				'unscrupulously'=>[
					'unscrupulousally',
					'unscrupulousaly',
					'unscrupulousely',
					'unscrupulouslly',
				],
				'unsearchable'=>[
					'unsearchible',
					'unserchable',
				],
				'unsearchably'=>[
					'unsearchabally',
					'unsearchabaly',
					'unsearchabely',
					'unsearchablly',
				],
				'unseasonable'=>[
					'unseasonible',
					'unsesonable',
				],
				'unseasonably'=>[
					'unseasonabally',
					'unseasonabaly',
					'unseasonabely',
					'unseasonablly',
				],
				'unseasoned'=>[
					'unsesoned',
				],
				'unseat'=>[
					'unset',
				],
				'unseeable'=>[
					'unseeible',
				],
				'unseeing'=>[
					'unseieng',
				],
				'unseemly'=>[
					'unseemally',
					'unseemaly',
					'unseemely',
					'unseemlly',
				],
				'unselectively'=>[
					'unselectivly',
				],
				'unsentimental'=>[
					'unsentimantal',
				],
				'unseparated'=>[
					'unseperated',
				],
				'unserious'=>[
					'unserous',
				],
				'unserviceable'=>[
					'unserviceble',
					'unserviceible',
				],
				'unshakable'=>[
					'unshakible',
				],
				'unshakably'=>[
					'unshakabally',
					'unshakabaly',
					'unshakabely',
					'unshakablly',
				],
				'unshapely'=>[
					'unshapeally',
					'unshapealy',
					'unshapeely',
					'unshapelly',
					'unshaply',
				],
				'unsightlinesses'=>[
					'unsightlinisses',
				],
				'unsightly'=>[
					'unsightally',
					'unsightaly',
					'unsightely',
					'unsightlly',
				],
				'unsimilar'=>[
					'unsimiler',
				],
				'unsinkable'=>[
					'unsinkible',
				],
				'unskilled'=>[
					'unskiled',
				],
				'unsnagging'=>[
					'unsnaging',
				],
				'unsociable'=>[
					'unsociible',
				],
				'unsociably'=>[
					'unsociabally',
					'unsociabaly',
					'unsociabely',
					'unsociablly',
				],
				'unsoldierly'=>[
					'unsoldeirly',
					'unsoldierally',
					'unsoldieraly',
					'unsoldierely',
					'unsoldierlly',
					'unsoldirly',
				],
				'unsolvable'=>[
					'unsolvible',
				],
				'unsoncy'=>[
					'unsonsy',
				],
				'unsonsy'=>[
					'unsoncy',
				],
				'unsparing'=>[
					'unspering',
				],
				'unspeakable'=>[
					'unspeakible',
					'unspekable',
				],
				'unspecifiable'=>[
					'unspecifiible',
				],
				'unspecified'=>[
					'unspecifeid',
					'unspecifid',
				],
				'unspectacular'=>[
					'unspectaculer',
				],
				'unspent'=>[
					'unspant',
				],
				'unspiritual'=>[
					'unspiritaul',
				],
				'unspoiled'=>[
					'unspoilt',
				],
				'unstable'=>[
					'unstible',
				],
				'unstained'=>[
					'unstainid',
				],
				'unsteady'=>[
					'unstedy',
				],
				'unstoppable'=>[
					'unstopable',
					'unstoppible',
				],
				'unstopped'=>[
					'unstoped',
				],
				'unstopper'=>[
					'unstoper',
				],
				'unstrained'=>[
					'unstrainid',
				],
				'unstratified'=>[
					'unstratifeid',
					'unstratifid',
				],
				'unstudied'=>[
					'unstudeid',
					'unstudid',
				],
				'unsubstantial'=>[
					'unsubstential',
				],
				'unsubstantiated'=>[
					'unsubstanciated',
					'unsubstentiated',
				],
				'unsuccess'=>[
					'unsucess',
				],
				'unsuccessful'=>[
					'unsuccesful',
					'unsuccessfull',
					'unsucesful',
					'unsucessfull',
					'unsucessful',
				],
				'unsuccessfully'=>[
					'unsuccesfully',
					'unsucesfuly',
					'unsucessfully',
					'unsuccessfulally',
					'unsuccessfulaly',
					'unsuccessfulely',
					'unsuccessfullly',
				],
				'unsuitable'=>[
					'unsuitible',
				],
				'unsullied'=>[
					'unsulleid',
					'unsullid',
				],
				'unsupportable'=>[
					'unsuportable',
					'unsupportible',
				],
				'unsupported'=>[
					'unsuported',
				],
				'unsurely'=>[
					'unsurly',
				],
				'unsurpassable'=>[
					'unsurpasable',
					'unsurpassible',
				],
				'unsurpassed'=>[
					'unsurpased',
				],
				'unsurprised'=>[
					'unsuprised',
					'unsuprized',
					'unsurprized',
				],
				'unsurprising'=>[
					'unsuprising',
					'unsuprizing',
					'unsurprizing',
				],
				'unsurprisingly'=>[
					'unsuprisingly',
					'unsuprizingly',
					'unsurprizingly',
				],
				'unsusceptible'=>[
					'unsuceptible',
					'unsucseptible',
					'unsusceptable',
					'unsuseptible',
				],
				'unsuspicious'=>[
					'unsuspicous',
				],
				'unsustainable'=>[
					'unsustainible',
				],
				'unswear'=>[
					'unsweer',
				],
				'unsweetened'=>[
					'unsweetend',
				],
				'unsymmetrical'=>[
					'unsymnetrical',
				],
				'unsymmetrically'=>[
					'unsymmetricalally',
					'unsymmetricalaly',
					'unsymmetricalely',
					'unsymmetricallly',
					'unsymnetrically',
				],
				'untagged'=>[
					'untaged',
				],
				'untanned'=>[
					'untaned',
				],
				'untapped'=>[
					'untaped',
				],
				'unteachable'=>[
					'unteachible',
					'untechable',
				],
				'untenable'=>[
					'untenible',
				],
				'unthinkable'=>[
					'unthinkible',
				],
				'unthreatening'=>[
					'unthretening',
				],
				'untie'=>[
					'untei',
					'unti',
				],
				'until'=>[
					'until of',
					'until until',
					'until until until',
					'untill',
					'uptill',
				],
				'untimely'=>[
					'untimeally',
					'untimealy',
					'untimeely',
					'untimelly',
					'untimly',
				],
				'untouchable'=>[
					'untouchible',
				],
				'untraceable'=>[
					'untracable',
					'untraceble',
					'untraceible',
				],
				'untrained'=>[
					'untrainid',
				],
				'untrammeled'=>[
					'untramneled',
				],
				'untranslatable'=>[
					'untranslateable',
					'untranslatible',
				],
				'untreated'=>[
					'untreted',
				],
				'untried'=>[
					'untreid',
					'untrid',
				],
				'untrimmed'=>[
					'untrimned',
				],
				'untunable'=>[
					'untunible',
				],
				'unusable'=>[
					'unuseable',
					'unusible',
				],
				'unusual'=>[
					'unsual',
					'unusaul',
				],
				'unusually'=>[
					'unusally',
					'unusualy',
				],
				'unutterable'=>[
					'unutterible',
				],
				'unvaccinated'=>[
					'unvaccinited',
					'unvacinated',
				],
				'unveil'=>[
					'unviel',
				],
				'unventilated'=>[
					'unvantilated',
				],
				'unverifiable'=>[
					'unverifiible',
				],
				'unviable'=>[
					'inviable',
					'unviible',
				],
				'unwakened'=>[
					'unwakend',
				],
				'unwanted'=>[
					'unwented',
				],
				'unwarrantable'=>[
					'unwarantable',
					'unwarrantible',
					'unwarrentable',
				],
				'unwarranted'=>[
					'unwaranted',
					'unwarrented',
				],
				'unwary'=>[
					'unwery',
				],
				'unwatchable'=>[
					'unwatchible',
				],
				'unweary'=>[
					'unweery',
				],
				'unweighed'=>[
					'unwieghed',
				],
				'unweight'=>[
					'unwieght',
				],
				'unwell'=>[
					'unwel',
				],
				'unwhipped'=>[
					'unwhiped',
				],
				'unwholesomely'=>[
					'unwholesomly',
				],
				'unwieldy'=>[
					'unweildly',
					'unweildy',
					'unwieldly',
					'unwildy',
				],
				'unwifely'=>[
					'unwifly',
				],
				'unwilling'=>[
					'unwiling',
				],
				'unwinnable'=>[
					'unwinable',
					'unwinnible',
				],
				'unwisely'=>[
					'unwisly',
				],
				'unwomanly'=>[
					'unwomanally',
					'unwomanaly',
					'unwomanely',
					'unwomanlly',
				],
				'unwontedly'=>[
					'unwontedally',
					'unwontedaly',
					'unwontedely',
					'unwontedlly',
				],
				'unworkable'=>[
					'unworkible',
				],
				'unworldlinesses'=>[
					'unworldlinisses',
				],
				'unworldly'=>[
					'unworldally',
					'unworldaly',
					'unworldely',
					'unworldlly',
				],
				'unworried'=>[
					'unworreid',
					'unworied',
					'unworrid',
				],
				'unyielding'=>[
					'unyeilding',
					'unyilding',
				],
				'up'=>[
					'up up',
					'up up up',
				],
				'up the'=>[
					'upthe',
				],
				'up to'=>[
					'upto',
				],
				'upbear'=>[
					'upbeer',
				],
				'upbeat'=>[
					'upbet',
				],
				'upcoming'=>[
					'upcomming',
				],
				'upfield'=>[
					'upfeild',
					'upfild',
				],
				'upgradable'=>[
					'upgradeable',
				],
				'upgrade'=>[
					'upgarde',
				],
				'upheaval'=>[
					'upheval',
				],
				'upheld'=>[
					'upholded',
				],
				'uphill'=>[
					'uphil',
				],
				'upholstery'=>[
					'upholstary',
				],
				'upon'=>[
					'apon',
					'opon',
				],
				'upon, apron'=>[
					'apon',
				],
				'upped'=>[
					'uped',
				],
				'upper'=>[
					'uppper',
					'uper',
				],
				'uppercase'=>[
					'upercase',
				],
				'upperclassman'=>[
					'uperclassman',
					'upperclasman',
				],
				'upperclassmen'=>[
					'uperclassmen',
				],
				'uppercut'=>[
					'upercut',
				],
				'uppermost'=>[
					'upmost',
					'upermost',
				],
				'uppish'=>[
					'upish',
				],
				'uppity'=>[
					'upity',
				],
				'uprear'=>[
					'upreer',
				],
				'uprising'=>[
					'upnsing',
				],
				'uproar'=>[
					'uproer',
				],
				'uproarious'=>[
					'uproarous',
				],
				'uproariously'=>[
					'uproarously',
				],
				'uprousing'=>[
					'uprouisng',
				],
				'upsadaisy'=>[
					'upsadaicy',
				],
				'upscale'=>[
					'upcale',
					'upcsale',
					'upsale',
				],
				'upset'=>[
					'upsetted',
				],
				'upsoar'=>[
					'upsoer',
				],
				'upstream'=>[
					'upstrem',
				],
				'uptear'=>[
					'upteer',
				],
				'uraei'=>[
					'uraie',
				],
				'uraninite'=>[
					'uraninate',
				],
				'urbanely'=>[
					'urbanly',
				],
				'urbanistically'=>[
					'urbanisticalally',
					'urbanisticalaly',
					'urbanisticalely',
					'urbanisticallly',
				],
				'urea'=>[
					'ure',
				],
				'urediniospore'=>[
					'uredinaospore',
				],
				'urediniospores'=>[
					'uredinaospores',
				],
				'uredinium'=>[
					'uredinaum',
				],
				'ureic'=>[
					'uriec',
				],
				'ureide'=>[
					'uriede',
				],
				'urethroscope'=>[
					'urethrocope',
					'urethrocsope',
					'urethrosope',
				],
				'urgency'=>[
					'urgensy',
				],
				'urgent'=>[
					'urgant',
				],
				'urgently'=>[
					'urgentally',
					'urgentaly',
					'urgentely',
					'urgentlly',
				],
				'uridine'=>[
					'uridini',
				],
				'urinal'=>[
					'urinil',
				],
				'urinals'=>[
					'urinils',
				],
				'urinalyses'=>[
					'urinilyses',
				],
				'urinalysis'=>[
					'urinilysis',
				],
				'urinaries'=>[
					'uriniries',
				],
				'urinary'=>[
					'urinery',
					'uriniry',
				],
				'urinate'=>[
					'urinite',
				],
				'urinated'=>[
					'urinited',
				],
				'urinates'=>[
					'urinites',
				],
				'urinating'=>[
					'uriniting',
				],
				'urination'=>[
					'urinition',
				],
				'urinations'=>[
					'urinitions',
				],
				'urinative'=>[
					'urinitive',
				],
				'urinator'=>[
					'urinitor',
				],
				'urinators'=>[
					'urinitors',
				],
				'urine'=>[
					'urini',
				],
				'urokinase'=>[
					'urokinise',
				],
				'urokinases'=>[
					'urokinises',
				],
				'ursine'=>[
					'ursini',
				],
				'uruguayan-occupied'=>[
					'uruguayan occupied',
				],
				'us'=>[
					'us us',
					'us us us',
				],
				'usable'=>[
					'useable',
					'usible',
				],
				'usage'=>[
					'useage',
				],
				'usance'=>[
					'usence',
				],
				'use'=>[
					'uise',
					'use use',
					'use use use',
				],
				'useable'=>[
					'useible',
				],
				'used'=>[
					'unsed',
				],
				'useful'=>[
					'usefull',
				],
				'usefully'=>[
					'usefuly',
				],
				'usefulness'=>[
					'usefullness',
				],
				'useless'=>[
					'useles',
				],
				'userboxen'=>[
					'userboxev',
				],
				'using'=>[
					'useing',
				],
				'usual'=>[
					'usual usual',
					'usual usual usual',
					'usuall',
					'ususal',
					'usaul',
				],
				'usually'=>[
					'usally',
					'useally',
					'usualy',
					'usully',
					'ususally',
				],
				'usuals'=>[
					'usauls',
				],
				'usufructuary'=>[
					'usufructaury',
					'usufructuery',
				],
				'usurious'=>[
					'usurous',
				],
				'usuriously'=>[
					'usurously',
				],
				'usurp'=>[
					'usurpate',
				],
				'uterine'=>[
					'uterini',
				],
				'utilitarian'=>[
					'utilitaran',
				],
				'utilities'=>[
					'utilites',
				],
				'utilize'=>[
					'utalize',
				],
				'utilized'=>[
					'utilisied',
					'utilizied',
				],
				'utopian'=>[
					'utopan',
				],
				'utricular'=>[
					'utriculer',
				],
				'utterance'=>[
					'utterence',
				],
				'utterly'=>[
					'utterally',
					'utteraly',
					'utterely',
					'utterlly',
				],
				'uvea'=>[
					'uve',
				],
				'uveitis'=>[
					'uvietis',
				],
				'uvular'=>[
					'uvuler',
				],
				'uxorious'=>[
					'uxorous',
				],
				'uxoriously'=>[
					'uxorously',
				],
				'uzbekistani-occupied'=>[
					'uzbekistani occupied',
				],
			];
		}
	}

?>