<?php
		
		/* UTF-8 TEST
		
			中文汉字漢字
		
		*/
				
				/* EnglishMisspellingsWords_E
					
					Class for English-Misspellings for all words beginning with : E.
					
				*/

	class EnglishMisspellingsWords_E {
			/* __construct($args)
			
				Constructor.
				
				Nothing to do here.
			
			*/
			
		public function __construct($args) {
			return TRUE;
		}
		
			/* EnglishMisspellingsWords()
			
				List of English misspellings for words starting with : E.
			
			*/

		public function EnglishMisspellingsWords() {
			return [
				'each'=>[
					'cach',
					'each each',
					'each each each',
					'ech',
				],
				'each other'=>[
					'eachother',
				],
				'eager'=>[
					'eger',
				],
				'eagle'=>[
					'egle',
				],
				'ear'=>[
					'ear ear',
					'ear ear ear',
					'er',
				],
				'eared'=>[
					'ered',
				],
				'earl'=>[
					'erl',
				],
				'earlier'=>[
					'ealier',
					'eariler',
					'earler',
				],
				'earliest'=>[
					'ealiest',
				],
				'early'=>[
					'earely',
					'early early',
					'early early early',
					'eary',
					'earally',
					'earaly',
					'earlly',
					'erly',
				],
				'earn'=>[
					'ern',
				],
				'earned'=>[
					'earnt',
				],
				'earnest'=>[
					'ernest',
				],
				'earnestly'=>[
					'earnestally',
					'earnestaly',
					'earnestely',
					'earnestlly',
				],
				'earnestnesses'=>[
					'ernestnesses',
				],
				'earnings'=>[
					'ernings',
				],
				'earpiece'=>[
					'earpeice',
					'earpice',
				],
				'earring'=>[
					'earing',
				],
				'ears'=>[
					'ers',
				],
				'earsplitting'=>[
					'ersplitting',
				],
				'earth'=>[
					'ealth',
					'earth earth',
					'earth earth earth',
					'erth',
				],
				'earthbound'=>[
					'erthbound',
				],
				'earthenware'=>[
					'erthenware',
				],
				'earthenwares'=>[
					'erthenwares',
				],
				'earthinesses'=>[
					'erthinesses',
				],
				'earthlinesses'=>[
					'earthlinisses',
					'erthlinesses',
				],
				'earthly'=>[
					'earthally',
					'earthaly',
					'earthely',
					'earthlly',
					'erthly',
				],
				'earthmovings'=>[
					'erthmovings',
				],
				'earthquake'=>[
					'earthqauke',
					'erthquake',
				],
				'earthshaking'=>[
					'erthshaking',
				],
				'earthshakingly'=>[
					'erthshakingly',
				],
				'earthstar'=>[
					'earthster',
				],
				'earthy'=>[
					'erthy',
				],
				'earwigged'=>[
					'earwiged',
				],
				'ease'=>[
					'ease ease',
					'ease ease ease',
					'ese',
				],
				'easel'=>[
					'esel',
				],
				'easement'=>[
					'easemant',
				],
				'easily'=>[
					'easiliy',
					'easly',
					'easially',
					'easialy',
					'easiely',
					'easilly',
					'esily',
				],
				'east'=>[
					'east east',
					'east east east',
					'est',
				],
				'eastbound'=>[
					'estbound',
				],
				'easterly'=>[
					'easterally',
					'easteraly',
					'easterely',
					'easterlly',
				],
				'eastern'=>[
					'eastearn',
					'easten',
					'estern',
				],
				'easternmost'=>[
					'eastermost',
					'easternost',
					'esternmost',
				],
				'eastward'=>[
					'estward',
				],
				'easy'=>[
					'eacy',
					'esy',
				],
				'easygoing'=>[
					'esygoing',
				],
				'easygoingnesses'=>[
					'esygoingnesses',
				],
				'eat'=>[
					'eat eat',
					'eat eat eat',
					'et',
				],
				'eatable'=>[
					'eatible',
				],
				'eaten'=>[
					'eated',
					'eten',
				],
				'eatery'=>[
					'eatary',
					'etery',
				],
				'eath'=>[
					'eth',
				],
				'eating'=>[
					'eting',
				],
				'eats'=>[
					'ets',
				],
				'eau'=>[
					'eu',
				],
				'eaux'=>[
					'eux',
				],
				'eave'=>[
					'eve',
				],
				'eaves'=>[
					'eves',
				],
				'eavesdrop'=>[
					'evesdrop',
				],
				'eavesdroppers'=>[
					'eavesdropers',
				],
				'eavesdropping'=>[
					'eavesdroping',
				],
				'ebb'=>[
					'eb',
				],
				'ebbed'=>[
					'ebed',
				],
				'ebbet'=>[
					'ebet',
				],
				'ebbets'=>[
					'ebets',
				],
				'ebbing'=>[
					'ebing',
				],
				'ebbs'=>[
					'ebs',
				],
				'ebullience'=>[
					'ebulleince',
					'ebulience',
					'ebulliance',
					'ebullince',
				],
				'ebulliences'=>[
					'ebulleinces',
					'ebullinces',
				],
				'ebulliency'=>[
					'ebulliensy',
				],
				'ebullient'=>[
					'ebulleint',
					'ebulient',
					'ebullint',
				],
				'ebulliently'=>[
					'ebulleintly',
					'ebullintly',
				],
				'eccentric'=>[
					'eccantric',
					'ecentric',
				],
				'eccentrically'=>[
					'ecentrically',
				],
				'eccentricities'=>[
					'eccentriciteis',
					'eccentricitis',
					'ecentricities',
				],
				'eccentricity'=>[
					'eccantricity',
					'ecentricity',
				],
				'eccentrics'=>[
					'ecentrics',
				],
				'ecchymoses'=>[
					'echymoses',
				],
				'ecchymosis'=>[
					'echymosis',
				],
				'ecchymotic'=>[
					'echymotic',
				],
				'ecclesia'=>[
					'eclesia',
				],
				'ecclesiae'=>[
					'eclesiae',
				],
				'ecclesial'=>[
					'eclesial',
				],
				'ecclesiastic'=>[
					'ecclesiatic',
					'eclesiastic',
				],
				'ecclesiastical'=>[
					'ecclesiatical',
					'ecclestiastical',
					'eclesiastical',
				],
				'ecclesiasticism'=>[
					'eclesiasticism',
				],
				'ecclesiastics'=>[
					'eclesiastics',
				],
				'ecclesiological'=>[
					'eclesiological',
				],
				'ecclesiologies'=>[
					'ecclesiologeis',
					'ecclesiologis',
					'eclesiologies',
				],
				'ecclesiologist'=>[
					'eclesiologist',
				],
				'ecclesiologists'=>[
					'eclesiologists',
				],
				'ecclesiology'=>[
					'eclesiology',
				],
				'eccrine'=>[
					'ecrine',
				],
				'echinacea'=>[
					'echinicea',
				],
				'echinate'=>[
					'echinite',
				],
				'echini'=>[
					'echina',
				],
				'echinococci'=>[
					'echinococi',
				],
				'echinococcoses'=>[
					'echinococoses',
				],
				'echinococcosis'=>[
					'echinococosis',
				],
				'echinococcus'=>[
					'echinococus',
				],
				'eclaircissement'=>[
					'eclaircisement',
					'eclaircissemant',
				],
				'eclectic'=>[
					'ecclectic',
					'eclectric',
				],
				'eclipse'=>[
					'eclispe',
				],
				'eclogues'=>[
					'edogues',
				],
				'ecofeminism'=>[
					'ecofeminasm',
				],
				'ecological'=>[
					'ecolical',
				],
				'econometrician'=>[
					'econometrican',
				],
				'economic'=>[
					'ecomonic',
					'economis',
				],
				'economical'=>[
					'ecomonical',
					'economial',
				],
				'economist'=>[
					'eeonomist',
				],
				'economists'=>[
					'eeonomists',
				],
				'economy'=>[
					'ecomony',
				],
				'ecophysiologies'=>[
					'ecophysiologeis',
					'ecophysiologis',
				],
				'ecoterrorism'=>[
					'ecoterorism',
				],
				'ecraseur'=>[
					'ecraser',
				],
				'ecstasy'=>[
					'ecstacy',
					'esctasy',
					'exstacy',
					'extacy',
					'extasy',
				],
				'ectomorph'=>[
					'ectomourph',
				],
				'ectomorphic'=>[
					'ectomourphic',
				],
				'ectomorphs'=>[
					'ectomourphs',
				],
				'ectoparasite'=>[
					'ectoperasite',
				],
				'ectoparasites'=>[
					'ectoperasites',
				],
				'ectoparasitic'=>[
					'ectoperasitic',
				],
				'ecuadorean-occupied'=>[
					'ecuadorean occupied',
				],
				'edacious'=>[
					'edacous',
				],
				'edelweiss'=>[
					'edelwiess',
				],
				'edelweisses'=>[
					'edelwiesses',
				],
				'edentate'=>[
					'edantate',
				],
				'edentates'=>[
					'edantates',
				],
				'edentulous'=>[
					'edantulous',
				],
				'edge'=>[
					'edge edge',
					'edge edge edge',
				],
				'edged'=>[
					'eged',
				],
				'edgeless'=>[
					'egeless',
				],
				'edger'=>[
					'eger',
				],
				'edgers'=>[
					'egers',
				],
				'edges'=>[
					'eges',
				],
				'edgeways'=>[
					'egeways',
				],
				'edgewise'=>[
					'egewise',
				],
				'edibilities'=>[
					'edibiliteis',
					'edibilitis',
				],
				'edible'=>[
					'edable',
				],
				'editable'=>[
					'editible',
				],
				'edited'=>[
					'editied',
				],
				'edition'=>[
					'edtion',
				],
				'editor'=>[
					'editior',
				],
				'educable'=>[
					'educible',
				],
				'education'=>[
					'educadon',
					'eduction',
				],
				'educational'=>[
					'eductional',
				],
				'educible'=>[
					'educable',
				],
				'edutainment'=>[
					'edutaiment',
					'edutainent',
					'edutainmant',
				],
				'edutainments'=>[
					'edutaiments',
					'edutainents',
				],
				'eels'=>[
					'eles',
				],
				'eerie'=>[
					'eerei',
					'eery',
					'eeri',
				],
				'eerily'=>[
					'eeriely',
				],
				'eeriness'=>[
					'eerieness',
				],
				'effable'=>[
					'effible',
				],
				'effect'=>[
					'cffect',
					'effect effect',
					'effect effect effect',
				],
				'effective'=>[
					'efective',
					'effetive',
				],
				'effectively'=>[
					'effectiveally',
					'effectivealy',
					'effectiveely',
					'effectivelly',
					'effectivly',
				],
				'effectual'=>[
					'effectaul',
				],
				'effectualities'=>[
					'effectualiteis',
					'effectaulities',
					'effectualitis',
				],
				'effectualness'=>[
					'effectaulness',
				],
				'effectualnesses'=>[
					'effectaulnesses',
				],
				'effectuate'=>[
					'effectaute',
				],
				'effectuations'=>[
					'effectautions',
				],
				'effeminacy'=>[
					'effeminasy',
					'effeminicy',
				],
				'effeminate'=>[
					'effeminite',
				],
				'effervescence'=>[
					'effervecence',
					'effervecsence',
					'effervescance',
					'effervesence',
				],
				'effervescences'=>[
					'effervecences',
					'effervecsences',
					'effervesences',
				],
				'effervescently'=>[
					'effervecently',
					'effervecsently',
					'effervescentally',
					'effervescentaly',
					'effervescentely',
					'effervescentlly',
					'effervesently',
				],
				'effetely'=>[
					'effetly',
				],
				'efficacious'=>[
					'efficacous',
				],
				'efficaciously'=>[
					'efficaciousally',
					'efficaciousaly',
					'efficaciousely',
					'efficaciouslly',
					'efficacously',
				],
				'efficacy'=>[
					'efficasy',
				],
				'efficent'=>[
					'eficient',
				],
				'efficiency'=>[
					'effeciency',
					'efficeincy',
					'efficency',
					'efficiensy',
					'efficincy',
				],
				'efficient'=>[
					'effecient',
					'efficeint',
					'efficent',
					'eficient',
					'efficiant',
					'efficint',
				],
				'efficiently'=>[
					'efficeintly',
					'efficently',
					'efficintly',
				],
				'efflorescence'=>[
					'efflorecence',
					'efflorecsence',
					'efflorescance',
					'effloresence',
				],
				'efflorescences'=>[
					'efflorecences',
					'efflorecsences',
					'effloresences',
				],
				'effluence'=>[
					'effulence',
					'effluance',
				],
				'effluent'=>[
					'effluant',
				],
				'effort'=>[
					'affort',
					'ef- fort',
					'ef-fort',
					'efford',
					'efort',
				],
				'effortless'=>[
					'effortles',
				],
				'efforts'=>[
					'effords',
				],
				'effrontery'=>[
					'effrontary',
				],
				'effulgence'=>[
					'effulgance',
				],
				'effusing'=>[
					'effuisng',
				],
				'effusion'=>[
					'effuison',
				],
				'effusions'=>[
					'effuisons',
				],
				'effusive'=>[
					'effuisve',
				],
				'effusively'=>[
					'effuisvely',
					'effusivly',
				],
				'effusiveness'=>[
					'effuisveness',
				],
				'effusivenesses'=>[
					'effuisvenesses',
				],
				'efraín'=>[
					'efrain',
				],
				'egalitarian'=>[
					'egalitaran',
				],
				'egg'=>[
					'egg egg',
					'egg egg egg',
					'eg',
				],
				'eggar'=>[
					'egar',
					'egger',
				],
				'eggbeater'=>[
					'egbeater',
				],
				'eggcup'=>[
					'egcup',
				],
				'egged'=>[
					'eged',
				],
				'egger'=>[
					'eger',
				],
				'eggfruit'=>[
					'egfruit',
				],
				'eggfruits'=>[
					'egfruits',
				],
				'egghead'=>[
					'eghead',
				],
				'eggheaded'=>[
					'egheaded',
				],
				'eggheadedness'=>[
					'egheadedness',
				],
				'eggheadednesses'=>[
					'egghedednesses',
					'egheadednesses',
				],
				'eggnog'=>[
					'egnog',
				],
				'eggplant'=>[
					'eggplent',
					'egplant',
				],
				'eggplants'=>[
					'egplants',
				],
				'eggs'=>[
					'egs',
				],
				'eggshell'=>[
					'egshell',
				],
				'eggshells'=>[
					'egshells',
				],
				'eggy'=>[
					'egy',
				],
				'egocentricities'=>[
					'egocentriciteis',
					'egocantricities',
					'egocentricitis',
				],
				'egregious'=>[
					'aggregious',
					'agregious',
					'egregous',
				],
				'egregiously'=>[
					'egregiousally',
					'egregiousaly',
					'egregiousely',
					'egregiouslly',
					'egregously',
				],
				'egress'=>[
					'egres',
				],
				'egypt'=>[
					'eqypt',
				],
				'egyptian'=>[
					'eqyptian',
					'egyptan',
				],
				'egyptian-occupied'=>[
					'egyptian occupied',
				],
				'eicosanoid'=>[
					'iecosanoid',
				],
				'eicosanoids'=>[
					'iecosanoids',
				],
				'eide'=>[
					'iede',
				],
				'eider'=>[
					'ieder',
				],
				'eiderdown'=>[
					'iederdown',
				],
				'eiderdowns'=>[
					'iederdowns',
				],
				'eidetic'=>[
					'iedetic',
				],
				'eidetically'=>[
					'iedetically',
				],
				'eidola'=>[
					'iedola',
				],
				'eidolic'=>[
					'iedolic',
				],
				'eidolon'=>[
					'iedolon',
				],
				'eidos'=>[
					'iedos',
				],
				'eigenmode'=>[
					'eigemode',
					'eigenode',
				],
				'eigenmodes'=>[
					'eigemodes',
					'eigenodes',
					'iegenmodes',
				],
				'eigenvalue'=>[
					'iegenvalue',
				],
				'eigenvalues'=>[
					'iegenvalues',
				],
				'eigenvector'=>[
					'iegenvector',
				],
				'eigenvectors'=>[
					'iegenvectors',
				],
				'eight'=>[
					'eght',
					'eight eight',
					'eight eight eight',
					'eigth',
					'ieght',
				],
				'eight-hour'=>[
					'eighthour',
				],
				'eightballs'=>[
					'ieghtballs',
				],
				'eighteen'=>[
					'ieghteen',
				],
				'eighteenth'=>[
					'eighteanth',
					'ieghteenth',
				],
				'eighteenths'=>[
					'ieghteenths',
				],
				'eightfold'=>[
					'ieghtfold',
				],
				'eighth'=>[
					'eigth',
					'ieghth',
				],
				'eighths'=>[
					'ieghths',
				],
				'eighties'=>[
					'eightys',
				],
				'eightieth'=>[
					'eighieth',
					'eighteith',
					'eightith',
					'ieghtieth',
				],
				'eightieths'=>[
					'ieghtieths',
				],
				'eights'=>[
					'ieghts',
				],
				'eightvo'=>[
					'ieghtvo',
				],
				'eighty'=>[
					'ieghty',
				],
				'eikon'=>[
					'iekon',
				],
				'eikones'=>[
					'iekones',
				],
				'eikons'=>[
					'iekons',
				],
				'einkorn'=>[
					'ienkorn',
				],
				'einsteinium'=>[
					'einsteinaum',
					'einstienium',
				],
				'einsteiniums'=>[
					'einsteinaums',
					'einstieniums',
				],
				'eirenic'=>[
					'ierenic',
				],
				'eisteddfod'=>[
					'iesteddfod',
				],
				'eisteddfodau'=>[
					'iesteddfodau',
				],
				'eisteddfodic'=>[
					'iesteddfodic',
				],
				'eisteddfods'=>[
					'iesteddfods',
				],
				'either'=>[
					'either either',
					'either either either',
					'iether',
				],
				'eked'=>[
					'eeked',
				],
				'ekes'=>[
					'eeks',
				],
				'eking'=>[
					'eeking',
				],
				'el dorado'=>[
					'elderado',
				],
				'elaborate'=>[
					'elaborite',
				],
				'elaborately'=>[
					'elaboratly',
				],
				'elderberry'=>[
					'elderbery',
				],
				'elderlinesses'=>[
					'elderlinisses',
				],
				'elderly'=>[
					'elderally',
					'elderaly',
					'elderely',
					'elderlly',
				],
				'electabilities'=>[
					'electabiliteis',
					'electabilitis',
				],
				'electable'=>[
					'electible',
				],
				'electively'=>[
					'electivly',
				],
				'electoral'=>[
					'electorial',
				],
				'electric'=>[
					'elecric',
					'electic',
					'electric electric',
					'electric electric electric',
				],
				'electrical'=>[
					'electrial',
				],
				'electrically'=>[
					'electricly',
				],
				'electrician'=>[
					'electrican',
				],
				'electricity'=>[
					'electricty',
				],
				'electrified'=>[
					'electrifeid',
					'electrifid',
				],
				'electrifies'=>[
					'electrifeis',
					'electrifis',
				],
				'electrokinetic'=>[
					'electrokinitic',
				],
				'electrokinetics'=>[
					'electrokinitics',
				],
				'electroless'=>[
					'electroles',
				],
				'electron'=>[
					'electon',
				],
				'electronic'=>[
					'eletronic',
				],
				'electroscope'=>[
					'electrocope',
					'electrocsope',
					'electrosope',
				],
				'electroscopes'=>[
					'electrocopes',
					'electrocsopes',
					'electrosopes',
				],
				'electroweak'=>[
					'electrowek',
				],
				'electrowinning'=>[
					'electrowining',
				],
				'electrowinnings'=>[
					'electrowinings',
				],
				'electuaries'=>[
					'electuareis',
					'electuaris',
				],
				'electuary'=>[
					'electaury',
					'electuery',
				],
				'eleemosynary'=>[
					'eleemosynery',
				],
				'elegance'=>[
					'elegence',
				],
				'elegancy'=>[
					'elegansy',
				],
				'elegant'=>[
					'elegent',
				],
				'element'=>[
					'element element',
					'element element element',
					'elemant',
				],
				'elemental'=>[
					'elemantal',
				],
				'elementariness'=>[
					'elementariniss',
				],
				'elementary'=>[
					'elemantary',
					'elimentary',
					'elementery',
				],
				'elements'=>[
					'elemenst',
					'elemnts',
					'elemts',
				],
				'elephant'=>[
					'elphant',
					'elephent',
				],
				'elephantiases'=>[
					'elephentiases',
				],
				'elephantiasis'=>[
					'elephentiasis',
				],
				'elephantine'=>[
					'elephantini',
					'elephentine',
				],
				'eleventh'=>[
					'elevanth',
				],
				'elicited'=>[
					'elicided',
				],
				'elidible'=>[
					'elidable',
				],
				'eligibility'=>[
					'eligability',
				],
				'eligible'=>[
					'eligable',
				],
				'eliminate'=>[
					'elminate',
					'eliminite',
				],
				'eliminated'=>[
					'eleminated',
				],
				'eliminating'=>[
					'eleminating',
				],
				'ellipse'=>[
					'elipse',
				],
				'ells'=>[
					'els',
				],
				'elocutionary'=>[
					'elocutionery',
				],
				'eloinment'=>[
					'eloiment',
					'eloinent',
				],
				'eloinments'=>[
					'eloiments',
					'eloinents',
				],
				'eloquence'=>[
					'eloquance',
				],
				'eloquent'=>[
					'eloquant',
				],
				'else'=>[
					'else else',
					'else else else',
					'esle',
				],
				'eluant'=>[
					'elaunt',
					'eluent',
				],
				'eluate'=>[
					'elaute',
				],
				'eluent'=>[
					'eluant',
				],
				'elusions'=>[
					'eluisons',
				],
				'elusive'=>[
					'ellusive',
				],
				'elusively'=>[
					'eluisvely',
					'elusivly',
				],
				'elusiveness'=>[
					'eluisveness',
				],
				'elusivenesses'=>[
					'eluisvenesses',
				],
				'eluveitie'=>[
					'eluviete',
				],
				'elysian'=>[
					'elysan',
				],
				'emanant'=>[
					'iminent',
				],
				'emanate'=>[
					'eminate',
				],
				'emancipate'=>[
					'emacipate',
				],
				'emarginate'=>[
					'emarginite',
				],
				'emasculate'=>[
					'emacsulate',
					'emaculate',
					'emasulate',
				],
				'emasculations'=>[
					'emacsulations',
					'emaculations',
					'emasulations',
				],
				'embalmment'=>[
					'embalmnent',
				],
				'embankment'=>[
					'enbankment',
					'embankmant',
				],
				'embankments'=>[
					'enbankments',
				],
				'embar'=>[
					'ember',
				],
				'embarrass'=>[
					'embarass',
					'embaress',
					'embarras',
					'embarress',
				],
				'embarrassable'=>[
					'embarrassible',
				],
				'embarrassed'=>[
					'embarassed',
					'embarrased',
				],
				'embarrassing'=>[
					'embarassing',
					'embarrasing',
				],
				'embarrassingly'=>[
					'embarassingly',
				],
				'embarrassment'=>[
					'embarassment',
					'embaressment',
					'embarrasment',
					'embarressment',
					'embarrassmant',
				],
				'embarrassments'=>[
					'embarassments',
				],
				'embassy'=>[
					'embascy',
					'embasy',
				],
				'embattlement'=>[
					'embattlemant',
				],
				'embedded'=>[
					'embeded',
				],
				'embellish'=>[
					'embelish',
				],
				'embellishment'=>[
					'embelishment',
					'embellishmant',
				],
				'embezzled'=>[
					'embezelled',
				],
				'emblazonment'=>[
					'emblazoment',
					'emblazonent',
				],
				'emblazonments'=>[
					'emblazoments',
					'emblazonents',
				],
				'embodiment'=>[
					'embodimant',
				],
				'emboldened'=>[
					'emboldend',
				],
				'emboly'=>[
					'emboally',
					'emboaly',
					'emboely',
					'embolly',
				],
				'emboss'=>[
					'embos',
				],
				'embraceries'=>[
					'embracereis',
					'embraceris',
				],
				'embryologically'=>[
					'embryologicalally',
					'embryologicalaly',
					'embryologicalely',
					'embryologicallly',
				],
				'emergence'=>[
					'emergance',
				],
				'emergencies'=>[
					'emergenceis',
					'emergencis',
				],
				'emergency'=>[
					'emergensy',
				],
				'emergent'=>[
					'emergant',
				],
				'emigrant'=>[
					'emmigrant',
					'emigrent',
				],
				'emigrants'=>[
					'emmigrants',
				],
				'emigrate'=>[
					'emmigrate',
				],
				'emigrated'=>[
					'emmigrated',
				],
				'emigration'=>[
					'emmigration',
				],
				'emilia elsner'=>[
					'emily elsner',
				],
				'eminence'=>[
					'eminance',
					'eminince',
				],
				'eminency'=>[
					'eminensy',
				],
				'eminent'=>[
					'emminent',
					'eminant',
					'eminint',
				],
				'eminently'=>[
					'emminently',
					'eminentally',
					'eminentaly',
					'eminentely',
					'eminentlly',
				],
				'emissaries'=>[
					'emmisaries',
					'emmisarries',
				],
				'emissary'=>[
					'emisary',
					'emmisarry',
					'emmisary',
					'emmissary',
					'emissery',
				],
				'emission'=>[
					'emision',
					'emmision',
					'emmission',
				],
				'emit'=>[
					'emitt',
				],
				'emittance'=>[
					'emittence',
				],
				'emitted'=>[
					'emited',
					'emmited',
					'emmitted',
				],
				'emitter'=>[
					'emiter',
				],
				'emitting'=>[
					'emiting',
					'emmiting',
					'emmitting',
				],
				'emmenagogue'=>[
					'emnenagogue',
				],
				'emmer'=>[
					'emner',
				],
				'emmers'=>[
					'emners',
				],
				'emmet'=>[
					'emnet',
				],
				'emmetropes'=>[
					'emnetropes',
				],
				'emmets'=>[
					'emnets',
				],
				'emmy'=>[
					'emny',
				],
				'emmys'=>[
					'emnys',
				],
				'emollient'=>[
					'emolleint',
					'emollint',
				],
				'emotion'=>[
					'emition',
				],
				'emotionalities'=>[
					'emotionaliteis',
					'emotionalitis',
				],
				'emotionless'=>[
					'emotionles',
				],
				'emotionlessly'=>[
					'emotionlessally',
					'emotionlessaly',
					'emotionlessely',
					'emotionlesslly',
				],
				'emotivities'=>[
					'emotiviteis',
					'emotivitis',
				],
				'empennage'=>[
					'empenage',
				],
				'emperor'=>[
					'emporer',
				],
				'emphasis'=>[
					'empahsis',
				],
				'emphasize'=>[
					'empahsize',
				],
				'emphysema'=>[
					'emphysyma',
				],
				'empire'=>[
					'emprie',
				],
				'empiric'=>[
					'imperic',
				],
				'empirical'=>[
					'emperical',
					'imperical',
				],
				'empiricalism'=>[
					'emperical',
					'impericalism',
				],
				'empirically'=>[
					'imperically',
				],
				'emplacement'=>[
					'emplacemant',
				],
				'employ'=>[
					'emply',
				],
				'employabilities'=>[
					'employabiliteis',
					'employabilitis',
				],
				'employed'=>[
					'emloyed',
					'emploved',
					'emplowed',
					'employeed',
				],
				'employee'=>[
					'emloyee',
					'employe',
				],
				'employees'=>[
					'emloyees',
					'employes',
				],
				'employing'=>[
					'emloying',
				],
				'employment'=>[
					'employmant',
				],
				'empoisonment'=>[
					'empoisoment',
					'empoisonent',
				],
				'empoisonments'=>[
					'empoisoments',
					'empoisonents',
				],
				'empress'=>[
					'empres',
				],
				'empressement'=>[
					'empresement',
				],
				'emulatively'=>[
					'emulativly',
				],
				'emulsible'=>[
					'emulsable',
				],
				'emulsifiers'=>[
					'emulsifeirs',
					'emulsifirs',
				],
				'emunctories'=>[
					'emunctoreis',
					'emunctoris',
				],
				'en route'=>[
					'enroute',
				],
				'enable'=>[
					'enible',
				],
				'enact'=>[
					'inact',
				],
				'enactment'=>[
					'enactmant',
				],
				'enamor'=>[
					'enamour',
				],
				'enamored'=>[
					'enamoured',
				],
				'enamoring'=>[
					'enamouring',
				],
				'enamors'=>[
					'enamours',
				],
				'enantiomer'=>[
					'enentiomer',
				],
				'enantiomorph'=>[
					'enantiomourph',
					'enentiomorph',
				],
				'enantiomorphic'=>[
					'enantiomourphic',
					'enentiomorphic',
				],
				'enantiomorphism'=>[
					'enantiomourphism',
					'enentiomorphism',
				],
				'enantiomorphous'=>[
					'enantiomourphous',
					'enentiomorphous',
				],
				'enantiomorphs'=>[
					'enantiomourphs',
					'enentiomorphs',
				],
				'enceinte'=>[
					'enciente',
				],
				'enchainment'=>[
					'enchaiment',
					'enchainent',
				],
				'enchainments'=>[
					'enchaiments',
					'enchainents',
				],
				'enchant'=>[
					'enchent',
				],
				'enchanter'=>[
					'enchenter',
				],
				'enchanting'=>[
					'enchenting',
				],
				'enchantment'=>[
					'enchantmant',
					'enchentment',
				],
				'enchantress'=>[
					'enchantres',
					'enchentress',
				],
				'enchantresses'=>[
					'enchentresses',
				],
				'encina'=>[
					'encini',
				],
				'enclose'=>[
					'inclose',
				],
				'enclosed'=>[
					'inclosed',
				],
				'enclosure'=>[
					'encolsure',
				],
				'encompass'=>[
					'encompas',
				],
				'encounter'=>[
					'encouter',
				],
				'encouragement'=>[
					'encouragemant',
				],
				'encouraging'=>[
					'engourageing', 'engouraging', 'enouraging',
				],
				'encroachment'=>[
					'encroachmant',
				],
				'encryption'=>[
					'encryptiion',
				],
				'encumber'=>[
					'incumber',
				],
				'encumbrance'=>[
					'incumbrance',
					'encumbrence',
				],
				'encyclopedia'=>[
					'encyclopeadia',
					'encyclopeda',
					'encyclpedia',
					'encylopedia',
					'eyncyclopedia',
				],
				'end'=>[
					'end end',
					'end end end',
				],
				'endear'=>[
					'endeer',
				],
				'endearing'=>[
					'endering',
				],
				'endearment'=>[
					'enderment',
				],
				'endeavor'=>[
					'endavour',
					'endeaovour',
					'endeavnor',
					'endevor',
				],
				'endeavour'=>[
					'edeavour',
					'endevour',
				],
				'endless'=>[
					'endles',
				],
				'endocrine'=>[
					'endocrini',
				],
				'endocrinologies'=>[
					'endocrinologeis',
					'endocrinologis',
				],
				'endoliths'=>[
					'endolithes',
				],
				'endomorph'=>[
					'endomourph',
				],
				'endomorphic'=>[
					'endomourphic',
				],
				'endomorphies'=>[
					'endomourphies',
				],
				'endomorphism'=>[
					'endomourphism',
				],
				'endomorphisms'=>[
					'endomourphisms',
				],
				'endomorphs'=>[
					'endomourphs',
				],
				'endomorphy'=>[
					'endomourphy',
				],
				'endonuclease'=>[
					'endonuclese',
				],
				'endoparasite'=>[
					'endoperasite',
				],
				'endoparasites'=>[
					'endoperasites',
				],
				'endoparasitic'=>[
					'endoperasitic',
				],
				'endoparasitism'=>[
					'endoperasitism',
				],
				'endoparasitisms'=>[
					'endoperasitisms',
				],
				'endorsement'=>[
					'endorsemant',
				],
				'endoscope'=>[
					'endocope',
					'endocsope',
					'endosope',
				],
				'endoscopically'=>[
					'endocopically',
					'endocsopically',
					'endosopically',
				],
				'endoscopies'=>[
					'endoscopeis',
					'endoscopis',
				],
				'endotracheal'=>[
					'endotrachel',
				],
				'endowment'=>[
					'endowmant',
				],
				'endurable'=>[
					'endurible',
				],
				'endurance'=>[
					'endurace',
					'indurance',
					'endurence',
				],
				'endure'=>[
					'indure',
				],
				'enemy'=>[
					'enemey',
					'enemy enemy',
					'enemy enemy enemy',
				],
				'energy'=>[
					'energy energy',
					'energy energy energy',
				],
				'enforceability'=>[
					'enforcebility',
				],
				'enframement'=>[
					'enframent',
				],
				'enframements'=>[
					'enframents',
				],
				'enfranchisement'=>[
					'enfranchisemant',
				],
				'engage'=>[
					'enage',
				],
				'engagement'=>[
					'engagment',
					'engagemant',
				],
				'engine'=>[
					'engine engine',
					'engine engine engine',
					'engini',
				],
				'engineer'=>[
					'engeneer',
					'engieneer',
					'engineeer',
					'enginer',
					'enginner',
					'enginier',
				],
				'engineering'=>[
					'engeneering',
					'engineeering',
					'engineeering ',
					'enginnering',
					'enginiering',
				],
				'engineers'=>[
					'engieneers',
					'engineeers',
					'enginners',
				],
				'england'=>[
					'engand',
				],
				'english'=>[
					'enlish',
				],
				'english-occupied'=>[
					'english occupied',
				],
				'engrossing'=>[
					'engrosing',
				],
				'enhance'=>[
					'enhence',
				],
				'enhancement'=>[
					'enchancement',
				],
				'enjoyment'=>[
					'enjoymant',
				],
				'enlargement'=>[
					'enlargment',
					'enlargemant',
				],
				'enlightened'=>[
					'enlightend',
				],
				'enlightenment'=>[
					'enlightement',
					'enlightenent',
					'enlightenmant',
				],
				'enlightenments'=>[
					'enlightements',
					'enlightenents',
					'enlightenmants',
				],
				'enlist'=>[
					'enlift',
					'enlish',
				],
				'enlisted'=>[
					'enlifted',
				],
				'enlivened'=>[
					'enlivend',
				],
				'enmesh'=>[
					'emesh',
					'enesh',
				],
				'enmeshed'=>[
					'emeshed',
					'eneshed',
				],
				'enmeshes'=>[
					'emeshes',
					'eneshes',
				],
				'enmeshing'=>[
					'emeshing',
					'eneshing',
				],
				'enmeshment'=>[
					'emeshment',
					'eneshment',
				],
				'enmeshments'=>[
					'emeshments',
					'eneshments',
				],
				'enmities'=>[
					'emities',
					'enities',
				],
				'enmity'=>[
					'emnity',
					'emity',
					'enity',
				],
				'ennead'=>[
					'enead',
				],
				'ennoble'=>[
					'enoble',
				],
				'ennoblement'=>[
					'enoblement',
				],
				'ennoblements'=>[
					'enoblements',
				],
				'ennui'=>[
					'enui',
				],
				'enormities'=>[
					'enourmities',
				],
				'enormity'=>[
					'enourmity',
				],
				'enormous'=>[
					'enourmous',
				],
				'enormously'=>[
					'enourmously',
				],
				'enormousness'=>[
					'enourmousness',
				],
				'enormousnesses'=>[
					'enourmousnesses',
				],
				'enough'=>[
					'enough enough',
					'enough enough enough',
					'enought',
				],
				'enrichment'=>[
					'enrichmant',
				],
				'enroll'=>[
					'enrole',
					'enrol',
				],
				'enrollment'=>[
					'enrolement',
					'enrollmant',
					'enrolment',
				],
				'ensanguining'=>[
					'ensanguinang',
				],
				'ensconce'=>[
					'enconce',
					'encsonce',
					'ensonce',
				],
				'enshrine'=>[
					'enshrini',
				],
				'enshrinements'=>[
					'enshriniments',
				],
				'ensigncy'=>[
					'ensignsy',
				],
				'ensorcellments'=>[
					'ensorcellmants',
				],
				'ensue'=>[
					'insue',
					'insue etc.',
				],
				'ensued'=>[
					'unsued',
				],
				'ensuing'=>[
					'ensueing',
				],
				'ensuring'=>[
					'ensureing',
				],
				'entail'=>[
					'antail',
				],
				'entangle'=>[
					'antangle',
				],
				'entelechies'=>[
					'entelecheis',
					'entelechis',
				],
				'entente'=>[
					'entante',
				],
				'enter'=>[
					'enter enter',
					'enter enter enter',
					'anter',
				],
				'entera'=>[
					'antera',
				],
				'entered'=>[
					'entred',
				],
				'enteric'=>[
					'anteric',
				],
				'enterobacteria'=>[
					'anterobacteria',
				],
				'enterobacterial'=>[
					'anterobacterial',
				],
				'enterobacterium'=>[
					'anterobacterium',
				],
				'enterococcal'=>[
					'enterococal',
				],
				'enterococci'=>[
					'enterococi',
				],
				'enterococcus'=>[
					'anterococcus',
					'enterococus',
				],
				'enterocolitis'=>[
					'anterocolitis',
				],
				'enterocolitises'=>[
					'anterocolitises',
				],
				'enterogastrone'=>[
					'anterogastrone',
				],
				'enterogastrones'=>[
					'anterogastrones',
				],
				'enterokinase'=>[
					'enterokinise',
				],
				'enterprise'=>[
					'enteprise',
					'anterprise',
				],
				'enterprising'=>[
					'anterprising',
				],
				'enters'=>[
					'anters',
				],
				'entertain'=>[
					'antertain',
				],
				'entertaining'=>[
					'intertaining',
					'antertaining',
					'entertainang',
				],
				'entertainingly'=>[
					'antertainingly',
					'entertainangly',
				],
				'entertainment'=>[
					'entertaiment',
					'entertainement',
					'entertainent',
					'entertainmant',
				],
				'entertainments'=>[
					'entertaiments',
					'entertainents',
					'entertainmants',
				],
				'enthalpy'=>[
					'anthalpy',
				],
				'enthralled'=>[
					'enthralledd',
				],
				'enthuse'=>[
					'anthuse',
				],
				'enthusiasm'=>[
					'enthusiam',
					'anthusiasm',
					'enthuisasm',
				],
				'enthusiasms'=>[
					'enthuisasms',
				],
				'enthusiast'=>[
					'enthusiat',
					'anthusiast',
					'enthuisast',
				],
				'enthusiastic'=>[
					'enthusiatic',
					'entlinsiastic',
					'anthusiastic',
					'enthuisastic',
				],
				'enthusiasts'=>[
					'enthuisasts',
				],
				'enthusing'=>[
					'enthuisng',
				],
				'enthymeme'=>[
					'enthyme',
				],
				'enthymemes'=>[
					'enthymes',
				],
				'entia'=>[
					'antia',
				],
				'entice'=>[
					'intice',
					'antice',
				],
				'entire'=>[
					'entrie',
					'antire',
				],
				'entirely'=>[
					'antirely',
					'entireally',
					'entirealy',
					'entireely',
					'entirelly',
					'entirly',
				],
				'entirety'=>[
					'antirety',
				],
				'entities'=>[
					'entites',
				],
				'entitle'=>[
					'antitle',
				],
				'entitled'=>[
					'entilted',
					'entited',
					'entitied',
				],
				'entitlement'=>[
					'entitlemant',
				],
				'entity'=>[
					'enitity',
					'enity',
					'antity',
				],
				'entoil'=>[
					'antoil',
				],
				'entomb'=>[
					'antomb',
				],
				'entomologically'=>[
					'antomologically',
					'entomologicalally',
					'entomologicalaly',
					'entomologicalely',
					'entomologicallly',
				],
				'entomophagous'=>[
					'antomophagous',
				],
				'entomophilous'=>[
					'antomophilous',
				],
				'entourage'=>[
					'antourage',
				],
				'entrails'=>[
					'antrails',
				],
				'entrain'=>[
					'antrain',
				],
				'entrainment'=>[
					'entraiment',
					'entrainent',
				],
				'entrainments'=>[
					'entraiments',
					'entrainents',
				],
				'entrance'=>[
					'enterance',
					'entrace',
					'entrence',
					'antrance',
				],
				'entrances'=>[
					'entrences',
				],
				'entrant'=>[
					'antrant',
					'entrent',
				],
				'entrap'=>[
					'antrap',
				],
				'entre'=>[
					'emtre',
				],
				'entreat'=>[
					'antreat',
				],
				'entree'=>[
					'antree',
				],
				'entrench'=>[
					'antrench',
				],
				'entrepreneur'=>[
					'enterpreneur',
					'entrepeneur',
					'entreprenuer',
					'antrepreneur',
					'entreprener',
				],
				'entrepreneurial'=>[
					'entrepeneurial',
					'antrepreneurial',
				],
				'entrepreneurs'=>[
					'entrepeneurs',
				],
				'entropy'=>[
					'antropy',
				],
				'entrust'=>[
					'intrust',
					'antrust',
				],
				'entrusted'=>[
					'intrusted',
				],
				'entry'=>[
					'antry',
				],
				'entryway'=>[
					'antryway',
				],
				'entwine'=>[
					'antwine',
					'entwini',
				],
				'enumerabilities'=>[
					'enumerabiliteis',
					'enumerabilitis',
				],
				'enviable'=>[
					'enviible',
				],
				'envious'=>[
					'envous',
				],
				'enviously'=>[
					'envously',
				],
				'environment'=>[
					'enivoriment',
					'enviorment',
					'enviornment',
					'enviroment',
					'environent',
					'environmant',
				],
				'environmental'=>[
					'enviormental',
					'enviornmental',
					'enviromental',
					'environental',
					'environmantal',
				],
				'environmentalist'=>[
					'enviornmentalist',
					'enviromentalist',
				],
				'environmentally'=>[
					'enviormentally',
					'enviornmentally',
					'enviromentally',
					'environentally',
					'environmantally',
				],
				'environments'=>[
					'enviorments',
					'enviornments',
					'enviroments',
					'environents',
				],
				'eohippus'=>[
					'eohipus',
				],
				'eolian'=>[
					'eolan',
				],
				'eonian'=>[
					'eonan',
				],
				'eosine'=>[
					'eosini',
				],
				'eosinic'=>[
					'eosinac',
				],
				'eparchial'=>[
					'eperchial',
				],
				'eparchies'=>[
					'eperchies',
				],
				'eparchs'=>[
					'eperchs',
				],
				'eparchy'=>[
					'eperchy',
				],
				'epeeist'=>[
					'epeiest',
				],
				'epeiric'=>[
					'epieric',
				],
				'epeirogenic'=>[
					'epierogenic',
				],
				'epeirogenically'=>[
					'epeirogenicalally',
					'epeirogenicalaly',
					'epeirogenicalely',
					'epeirogenicallly',
					'epierogenically',
				],
				'epeirogenies'=>[
					'epierogenies',
				],
				'epeirogeny'=>[
					'epierogeny',
				],
				'ephah'=>[
					'epha',
				],
				'ephahs'=>[
					'ephas',
				],
				'ephedrine'=>[
					'ephedrini',
				],
				'ephemeralities'=>[
					'ephemeraliteis',
					'ephemeralitis',
				],
				'epiboly'=>[
					'epiboally',
					'epiboaly',
					'epiboely',
					'epibolly',
				],
				'epicenter'=>[
					'epicanter',
				],
				'epicontinental'=>[
					'epicontinantal',
					'epicontinintal',
				],
				'epicuticular'=>[
					'epicuticuler',
				],
				'epidemiologies'=>[
					'epidemiologeis',
					'epidemiologis',
				],
				'epigrammatic'=>[
					'epigramnatic',
				],
				'epigrammatism'=>[
					'epigramnatism',
				],
				'epigrammatisms'=>[
					'epigramnatisms',
				],
				'epigrammatist'=>[
					'epigramnatist',
				],
				'epigrammatists'=>[
					'epigramnatists',
				],
				'epigrammatize'=>[
					'epigramnatize',
				],
				'epigrammatized'=>[
					'epigramnatized',
				],
				'epigrammatizer'=>[
					'epigramnatizer',
				],
				'epigrammatizers'=>[
					'epigramnatizers',
				],
				'epigrammatizes'=>[
					'epigramnatizes',
				],
				'epigrammatizing'=>[
					'epigramnatizing',
				],
				'epigraphies'=>[
					'epigrapheis',
					'epigraphis',
				],
				'epilepsy'=>[
					'epilepcy',
				],
				'epinasty'=>[
					'epinisty',
				],
				'epinephrine'=>[
					'epinephrini',
				],
				'epineurium'=>[
					'epiniurium',
				],
				'epiphytologies'=>[
					'epiphytologeis',
					'epiphytologis',
				],
				'epirogenies'=>[
					'epirogeneis',
					'epirogenis',
				],
				'episcopacy'=>[
					'epicopacy',
					'epicsopacy',
					'episcopasy',
					'episopacy',
				],
				'episcopal'=>[
					'epicopal',
					'epicsopal',
					'episopal',
				],
				'episcopate'=>[
					'epicopate',
					'epicsopate',
					'episopate',
				],
				'episode'=>[
					'epiode',
					'eposide',
					'epsiode',
				],
				'episodes'=>[
					'kpisodes',
				],
				'epistasy'=>[
					'epistacy',
				],
				'epistemologies'=>[
					'epistemologeis',
					'epistemologis',
				],
				'epistolary'=>[
					'epistolery',
				],
				'epitome'=>[
					'epitomy',
				],
				'epizootiologies'=>[
					'epizootiologeis',
					'epizootiologis',
				],
				'equability'=>[
					'eqaubility',
				],
				'equable'=>[
					'eqauble',
					'equible',
				],
				'equablenesses'=>[
					'eqaublenesses',
				],
				'equal'=>[
					'equal equal',
					'equal equal equal',
					'eqaul',
				],
				'equalisers'=>[
					'eqaulisers',
				],
				'equalising'=>[
					'eqaulising',
				],
				'equalitarian'=>[
					'eqaulitarian',
					'equalitaran',
				],
				'equalitarianism'=>[
					'eqaulitarianism',
				],
				'equalitarians'=>[
					'eqaulitarians',
				],
				'equalities'=>[
					'eqaulities',
				],
				'equality'=>[
					'eqaulity',
				],
				'equalizations'=>[
					'eqaulizations',
				],
				'equalize'=>[
					'eqaulize',
				],
				'equalizer'=>[
					'eqaulizer',
				],
				'equalizers'=>[
					'eqaulizers',
				],
				'equalizing'=>[
					'eqaulizing',
				],
				'equally'=>[
					'eqaully',
					'equaly',
				],
				'equals'=>[
					'eqauls',
				],
				'equaly'=>[
					'eqaul',
				],
				'equanimity'=>[
					'eqaunimity',
				],
				'equate'=>[
					'equate equate',
					'equate equate equate',
					'eqaute',
				],
				'equation'=>[
					'eqaution',
				],
				'equational'=>[
					'eqautional',
				],
				'equator'=>[
					'eqautor',
				],
				'equatorial'=>[
					'equitorial',
					'eqautorial',
				],
				'equerry'=>[
					'equery',
				],
				'equestrian'=>[
					'equestran',
				],
				'equestrienne'=>[
					'equestreinne',
					'equestriene',
					'equestrinne',
				],
				'equestriennes'=>[
					'equestrienes',
				],
				'equiangular'=>[
					'equianguler',
				],
				'equidistant'=>[
					'equidistent',
				],
				'equidistantly'=>[
					'equidistantally',
					'equidistantaly',
					'equidistantely',
					'equidistantlly',
					'equidistently',
				],
				'equilibrium'=>[
					'equilibium',
					'equilibrum',
				],
				'equimolar'=>[
					'equimoler',
				],
				'equine'=>[
					'equini',
				],
				'equinely'=>[
					'equinly',
				],
				'equipment'=>[
					'equippment',
					'equiptment',
					'equipmant',
				],
				'equipollence'=>[
					'equipollance',
				],
				'equiponderant'=>[
					'equiponderent',
				],
				'equipotential'=>[
					'equipotantial',
				],
				'equipped'=>[
					'equiped',
				],
				'equipper'=>[
					'equiper',
				],
				'equiprobable'=>[
					'equiprobible',
				],
				'equitabilities'=>[
					'equitabiliteis',
					'equitabilitis',
				],
				'equitable'=>[
					'equitible',
				],
				'equitant'=>[
					'equitent',
				],
				'equivalence'=>[
					'equivalance',
				],
				'equivalency'=>[
					'equivalensy',
				],
				'equivalent'=>[
					'equilavent',
					'equivalant',
					'equivelant',
					'equivelent',
					'equivilant',
					'equivilent',
					'equivolent',
				],
				'equivocal'=>[
					'equivoval',
				],
				'equivocalities'=>[
					'equivocaliteis',
					'equivocalitis',
				],
				'eradicate'=>[
					'erradicate',
				],
				'erasable'=>[
					'erasible',
				],
				'erect'=>[
					'errect',
				],
				'erected'=>[
					'erested',
					'errected',
				],
				'ergometries'=>[
					'ergometreis',
					'ergometris',
				],
				'ergotamine'=>[
					'ergotamini',
				],
				'eritrean-occupied'=>[
					'eritrean occupied',
				],
				'ermine'=>[
					'ermini',
				],
				'erode'=>[
					'errode',
				],
				'eroded'=>[
					'erroded',
				],
				'erodent'=>[
					'erodant',
				],
				'erodible'=>[
					'erodable',
				],
				'eroding'=>[
					'errode',
				],
				'erosely'=>[
					'erosly',
				],
				'erosible'=>[
					'erosable',
				],
				'erosion'=>[
					'errosion',
				],
				'erosivities'=>[
					'erosiviteis',
					'erosivitis',
				],
				'errable'=>[
					'errible',
				],
				'errancy'=>[
					'erancy',
					'erransy',
				],
				'errand'=>[
					'erand',
				],
				'errant'=>[
					'erant',
					'errent',
				],
				'errantry'=>[
					'erantry',
				],
				'errata'=>[
					'erata',
				],
				'erratic'=>[
					'eratic',
				],
				'erratically'=>[
					'eraticly',
				],
				'erratum'=>[
					'eratum',
				],
				'erred'=>[
					'ered',
				],
				'errhine'=>[
					'erhine',
				],
				'erring'=>[
					'ering',
				],
				'erroneous'=>[
					'eroneous',
				],
				'erroneousness'=>[
					'eroneousness',
				],
				'erroneousnesses'=>[
					'eroneousnesses',
				],
				'error'=>[
					'eror',
				],
				'errors'=>[
					'erors',
				],
				'errs'=>[
					'ers',
				],
				'erudite'=>[
					'erudit',
				],
				'eruditely'=>[
					'erudately',
					'eruditly',
				],
				'erupted'=>[
					'errupted',
				],
				'eruptible'=>[
					'eruptable',
				],
				'eruptively'=>[
					'eruptivly',
				],
				'erythropoieses'=>[
					'erythropoeises',
					'erythropoises',
				],
				'erythropoiesis'=>[
					'erythropoeisis',
					'erythropoisis',
				],
				'erythropoietic'=>[
					'erythropoeitic',
					'erythropoitic',
				],
				'erythropoietin'=>[
					'erythropoeitin',
					'erythropoitin',
				],
				'erythropoietins'=>[
					'erythropoeitins',
					'erythropoitins',
				],
				'escalade'=>[
					'ecalade',
					'ecsalade',
					'esalade',
				],
				'escalate'=>[
					'ecalate',
					'ecsalate',
					'esalate',
				],
				'escalator'=>[
					'ecalator',
					'ecsalator',
					'esalator',
				],
				'escapade'=>[
					'ecapade',
					'ecsapade',
					'esapade',
				],
				'escape'=>[
					'excape',
					'exscape',
					'ecape',
					'ecsape',
					'esape',
				],
				'escapee'=>[
					'ecapee',
					'ecsapee',
					'esapee',
				],
				'escapement'=>[
					'ecapement',
					'ecsapement',
					'esapement',
				],
				'escapism'=>[
					'ecapism',
					'ecsapism',
					'esapism',
				],
				'escapist'=>[
					'ecapist',
					'ecsapist',
					'esapist',
				],
				'escar'=>[
					'ecar',
					'ecsar',
					'esar',
					'escer',
				],
				'escargot'=>[
					'ecargot',
					'ecsargot',
					'esargot',
				],
				'escarole'=>[
					'ecarole',
					'ecsarole',
					'esarole',
				],
				'escarp'=>[
					'ecarp',
					'ecsarp',
					'esarp',
				],
				'escarpment'=>[
					'ecarpment',
					'ecsarpment',
					'esarpment',
				],
				'escars'=>[
					'ecars',
					'ecsars',
					'esars',
				],
				'eschar'=>[
					'echar',
					'ecshar',
					'escher',
					'eshar',
				],
				'eschatological'=>[
					'echatological',
					'ecshatological',
					'eshatological',
				],
				'eschatology'=>[
					'echatology',
					'ecshatology',
					'eshatology',
				],
				'escheat'=>[
					'echeat',
					'ecsheat',
					'esheat',
				],
				'eschew'=>[
					'echew',
					'ecshew',
					'eshew',
				],
				'escolar'=>[
					'ecolar',
					'ecsolar',
					'escoler',
					'esolar',
				],
				'escort'=>[
					'ecort',
					'ecsort',
					'esort',
				],
				'escot'=>[
					'ecot',
					'ecsot',
					'esot',
				],
				'escots'=>[
					'ecots',
					'ecsots',
					'esots',
				],
				'escrow'=>[
					'ecrow',
					'ecsrow',
					'esrow',
				],
				'escudo'=>[
					'ecsudo',
					'ecudo',
					'esudo',
				],
				'eskar'=>[
					'esker',
				],
				'espalier'=>[
					'espaleir',
					'espalir',
				],
				'esparto'=>[
					'esperto',
				],
				'espartos'=>[
					'espertos',
				],
				'especially'=>[
					'espacially',
					'especally',
					'especially especially',
					'especially especially especially',
					'expecially',
					'especialally',
					'especialaly',
					'especialely',
					'especiallly',
					'especialy',
				],
				'esperance'=>[
					'esperence',
				],
				'espionage'=>[
					'espoinage',
					'esponage',
					'esponiage',
				],
				'espousing'=>[
					'espouisng',
				],
				'espresso'=>[
					'espreso',
				],
				'essai sur sénèque'=>[
					'esai sur seneque',
				],
				'essay'=>[
					'esay',
				],
				'essence'=>[
					'esence',
					'essense',
					'essance',
				],
				'essential'=>[
					'esential',
					'essencial',
					'essental',
					'essentual',
					'essesital',
					'essantial',
				],
				'essentialism'=>[
					'esentialism',
					'essantialism',
				],
				'essentialities'=>[
					'essentialiteis',
					'essentialitis',
				],
				'essentialize'=>[
					'esentialize',
					'essantialize',
				],
				'essentially'=>[
					'esentially',
					'essentialy',
				],
				'essentialnesses'=>[
					'essantialnesses',
				],
				'esses'=>[
					'eses',
				],
				'establish'=>[
					'estabilish',
					'estalbish',
				],
				'establishable'=>[
					'establishible',
				],
				'established'=>[
					'establised',
					'establislied',
				],
				'establishment'=>[
					'establishement',
					'establishme',
					'establishmant',
				],
				'esthetician'=>[
					'esthetican',
				],
				'estimable'=>[
					'estimible',
				],
				'estimate'=>[
					'estamite',
					'estimite',
				],
				'estonian-occupied'=>[
					'estonian occupied',
				],
				'estopped'=>[
					'estoped',
				],
				'estoppel'=>[
					'estopel',
				],
				'estrellas de areito'=>[
					'estreas de areito',
				],
				'estuarine'=>[
					'estaurine',
					'estuarini',
				],
				'estuary'=>[
					'estaury',
					'estuery',
				],
				'esurience'=>[
					'esuriance',
				],
				'esuriency'=>[
					'esuriensy',
				],
				'et cetera'=>[
					'ec cetera',
					'etcetera',
				],
				'etc'=>[
					'ect',
				],
				'etc.'=>[
					'ect.',
				],
				'etchant'=>[
					'etchent',
				],
				'etesian'=>[
					'etesan',
				],
				'ethanolamine'=>[
					'ethanolamini',
				],
				'ethanolamines'=>[
					'ethanolaminis',
				],
				'ethereal'=>[
					'etherial',
					'etherel',
				],
				'etherealization'=>[
					'etherelization',
				],
				'etherealnesses'=>[
					'etherelnesses',
				],
				'ethician'=>[
					'ethican',
				],
				'ethiopia'=>[
					'ethiopa',
				],
				'ethiopian-occupied'=>[
					'ethiopian occupied',
				],
				'ethnocentricity'=>[
					'ethnocantricity',
				],
				'ethnocentrism'=>[
					'ethnocantrism',
				],
				'ethnography'=>[
					'etnography',
				],
				'ethnohistorian'=>[
					'ethnohistoran',
				],
				'ethnohistories'=>[
					'ethnohistoreis',
					'ethnohistoris',
				],
				'ethnomusicology'=>[
					'ethnomuiscology',
				],
				'ethnoscience'=>[
					'ethnosceince',
					'ethnocience',
					'ethnocsience',
					'ethnosciance',
					'ethnoscince',
					'ethnosience',
				],
				'etymology'=>[
					'ethymology',
				],
				'euclidean'=>[
					'euclidian',
				],
				'euclidian'=>[
					'euclidan',
				],
				'eugeosyncline'=>[
					'eugeosynclini',
				],
				'eugeosynclines'=>[
					'eugeosynclinis',
				],
				'eulogistically'=>[
					'eulogisticalally',
					'eulogisticalaly',
					'eulogisticalely',
					'eulogisticallly',
				],
				'eulogy'=>[
					'euology',
				],
				'euonymus'=>[
					'eonymus',
				],
				'euonymuses'=>[
					'eonymuses',
				],
				'eupepsy'=>[
					'eupepcy',
				],
				'euphausid'=>[
					'euphauisd',
				],
				'euphausids'=>[
					'euphauisds',
				],
				'euphausiid'=>[
					'euphauisid',
				],
				'euphausiids'=>[
					'euphauisids',
				],
				'euphemism'=>[
					'euphamism',
				],
				'euphonious'=>[
					'euphonous',
				],
				'euphoniously'=>[
					'euphonously',
				],
				'euphrasy'=>[
					'euphracy',
				],
				'europe'=>[
					'euorpe',
				],
				'european'=>[
					'euorpean',
					'europian',
					'eurpean',
					'eurpoean',
				],
				'europeans'=>[
					'europians',
				],
				'eustacy'=>[
					'eustasy',
				],
				'eustasy'=>[
					'eustacy',
				],
				'eutherian'=>[
					'eutheran',
				],
				'evacuant'=>[
					'evacaunt',
				],
				'evacuate'=>[
					'evacaute',
				],
				'evacuating'=>[
					'evacauting',
				],
				'evacuation'=>[
					'evacaution',
				],
				'evacuative'=>[
					'evacautive',
				],
				'evacuators'=>[
					'evacautors',
				],
				'evadible'=>[
					'evadable',
				],
				'evaginate'=>[
					'evaginite',
				],
				'evaluate'=>[
					'evalaute',
				],
				'evaluating'=>[
					'evalauting',
				],
				'evaluation'=>[
					'evalaution',
				],
				'evaluative'=>[
					'evalautive',
				],
				'evaluators'=>[
					'evalautors',
				],
				'evanescence'=>[
					'evanescance',
				],
				'evanescences'=>[
					'evanecences',
					'evanecsences',
					'evanesences',
				],
				'evanescent'=>[
					'evanecent',
					'evanecsent',
					'evanesent',
				],
				'evasively'=>[
					'evasivly',
				],
				'even'=>[
					'even even',
					'even even even',
				],
				'evened'=>[
					'evend',
				],
				'evenhandedly'=>[
					'evenhandedally',
					'evenhandedaly',
					'evenhandedely',
					'evenhandedlly',
				],
				'evening'=>[
					'evening evening',
					'evening evening evening',
					'evining',
				],
				'event'=>[
					'event event',
					'event event event',
					'evant',
				],
				'eventful'=>[
					'evantful',
				],
				'events'=>[
					'evens',
					'evants',
				],
				'eventual'=>[
					'evantual',
					'eventaul',
				],
				'eventualities'=>[
					'eventaulities',
				],
				'eventuality'=>[
					'evantuality',
					'eventaulity',
				],
				'eventually'=>[
					'eventualy',
					'evantually',
					'eventaully',
					'eventualally',
					'eventualaly',
					'eventualely',
					'eventuallly',
				],
				'eventuate'=>[
					'eventaute',
				],
				'eventuated'=>[
					'eventauted',
				],
				'eventuates'=>[
					'eventautes',
				],
				'ever'=>[
					'ever ever',
					'ever ever ever',
				],
				'ever since'=>[
					'eversince',
				],
				'ever-working'=>[
					'everworking',
				],
				'evermore'=>[
					'evermoure',
				],
				'eversible'=>[
					'eversable',
				],
				'every'=>[
					'every every',
					'every every every',
					'eveyr',
				],
				'every time'=>[
					'everytime',
				],
				'everybody'=>[
					'everbody',
					'every body',
					'every-body',
					'everyboyd',
				],
				'everyone'=>[
					'every one',
					'every-one',
				],
				'everything'=>[
					'evervthing',
				],
				'evidence'=>[
					'evidance',
				],
				'evident'=>[
					'evedent',
					'evidant',
				],
				'evidential'=>[
					'evidantial',
				],
				'evidentially'=>[
					'evidantially',
				],
				'evidentiary'=>[
					'evidantiary',
					'evidentiery',
				],
				'evidently'=>[
					'evidentally',
					'evidantly',
					'evidentaly',
					'evidentely',
					'evidentlly',
				],
				'evil'=>[
					'evol',
				],
				'evincible'=>[
					'evincable',
				],
				'eviscerate'=>[
					'evicerate',
					'evicserate',
					'eviserate',
				],
				'eviscerating'=>[
					'evicerating',
					'evicserating',
					'eviserating',
				],
				'evisceration'=>[
					'eviceration',
					'evicseration',
					'eviseration',
				],
				'evitable'=>[
					'evitible',
				],
				'evocatively'=>[
					'evocativly',
				],
				'evolution'=>[
					'evalution',
					'evlution',
					'evoltion',
					'evoluton',
				],
				'evolutionary'=>[
					'evolutionery',
				],
				'exacerbate'=>[
					'exerbate',
				],
				'exacerbated'=>[
					'exerbated',
				],
				'exact'=>[
					'exact exact',
					'exact exact exact',
				],
				'exactly'=>[
					'exactally',
					'exactaly',
					'exactely',
					'exactlly',
				],
				'exaggerate'=>[
					'exagerate',
					'exagerrate',
				],
				'exaggerated'=>[
					'exagerated',
				],
				'exaggeratedly'=>[
					'exageratedly',
				],
				'exaggeratedness'=>[
					'exageratedness',
				],
				'exaggerates'=>[
					'exagerates',
					'exagerrates',
				],
				'exaggerating'=>[
					'exagerating',
					'exagerrating',
				],
				'exaggeration'=>[
					'exageration',
				],
				'exaggerations'=>[
					'exagerations',
				],
				'exaggerative'=>[
					'exagerative',
				],
				'exaggerator'=>[
					'exagerator',
				],
				'exaggerators'=>[
					'exagerators',
				],
				'exaggeratory'=>[
					'exageratory',
				],
				'exahertz'=>[
					'exaertz',
				],
				'exahertzes'=>[
					'exaertzes',
				],
				'exalt'=>[
					'exhalt',
				],
				'exaltation'=>[
					'exhaltation',
				],
				'examinant'=>[
					'examinint',
				],
				'examination'=>[
					'examinition',
				],
				'examine'=>[
					'examinate',
					'examini',
				],
				'examinee'=>[
					'examinie',
				],
				'example'=>[
					'example example',
					'example example example',
					'exemple',
					'exmaple',
				],
				'exanthematic'=>[
					'exenthematic',
				],
				'exasperated'=>[
					'exasparated',
				],
				'exceed'=>[
					'excede',
				],
				'exceeded'=>[
					'excedded',
				],
				'exceedingly'=>[
					'exceedingally',
					'exceedingaly',
					'exceedingely',
					'exceedinglly',
				],
				'excel'=>[
					'excell',
				],
				'excellence'=>[
					'excellance',
					'excelence',
				],
				'excellency'=>[
					'excellensy',
				],
				'excellent'=>[
					'excelent',
					'excellant',
					'execellent',
					'exelent',
					'exellent',
				],
				'excels'=>[
					'excells',
				],
				'except'=>[
					'except except',
					'except except except',
					'excet',
					'execpt',
					'exept',
				],
				'exceptionable'=>[
					'exceptionible',
				],
				'excerpt'=>[
					'exerpt',
				],
				'excerpting'=>[
					'exerpting',
				],
				'excerpts'=>[
					'exerpts',
				],
				'excess'=>[
					'exces',
				],
				'excessive'=>[
					'eccessive',
					'excesssive',
					'excesive',
				],
				'excessively'=>[
					'excessivly',
				],
				'exchange'=>[
					'exchnage',
					'exhange',
				],
				'exchangeability'=>[
					'exchangebility',
				],
				'excipient'=>[
					'excipeint',
					'excipint',
				],
				'excisable'=>[
					'excisible',
				],
				'excitabilities'=>[
					'excitabiliteis',
					'excitabilitis',
				],
				'excitable'=>[
					'exciteable',
					'excitible',
				],
				'excite'=>[
					'excite excite',
					'excite excite excite',
				],
				'excitement'=>[
					'excitemant',
				],
				'excludabilities'=>[
					'excludabiliteis',
					'excludabilitis',
				],
				'excludible'=>[
					'excludable',
				],
				'exclusion'=>[
					'excluison',
				],
				'exclusionary'=>[
					'excluisonary',
					'exclusionery',
				],
				'exclusionist'=>[
					'excluisonist',
				],
				'exclusionists'=>[
					'excluisonists',
				],
				'exclusions'=>[
					'excluisons',
				],
				'exclusive'=>[
					'excluisve',
				],
				'exclusively'=>[
					'excluisvely',
					'exclusivly',
				],
				'exclusiveness'=>[
					'excluisveness',
				],
				'exclusivenesses'=>[
					'excluisvenesses',
				],
				'exclusives'=>[
					'excluisves',
				],
				'exclusivism'=>[
					'excluisvism',
				],
				'exclusivisms'=>[
					'excluisvisms',
				],
				'exclusivist'=>[
					'excluisvist',
				],
				'exclusivists'=>[
					'excluisvists',
				],
				'exclusivities'=>[
					'excluisvities',
				],
				'exclusivity'=>[
					'excluisvity',
				],
				'excommunicate'=>[
					'excomnunicate',
				],
				'excommunicated'=>[
					'excomnunicated',
				],
				'excommunicates'=>[
					'excomnunicates',
				],
				'excommunicating'=>[
					'excomnunicating',
				],
				'excommunication'=>[
					'excomnunication',
				],
				'excommunicative'=>[
					'excomnunicative',
				],
				'excommunicator'=>[
					'excomnunicator',
				],
				'excommunicators'=>[
					'excomnunicators',
				],
				'excrementitious'=>[
					'excremantitious',
					'excrementitous',
				],
				'excrescence'=>[
					'excrecence',
					'excrecsence',
					'excrescance',
					'excresence',
				],
				'excrescences'=>[
					'excrecences',
					'excrecsences',
					'excresences',
				],
				'excrescency'=>[
					'excrescensy',
				],
				'excrescently'=>[
					'excrecently',
					'excrecsently',
					'excresently',
				],
				'excruciating'=>[
					'excrutiating',
				],
				'excurrent'=>[
					'excurent',
				],
				'excursively'=>[
					'excursivly',
				],
				'excusing'=>[
					'excuisng',
				],
				'execrable'=>[
					'execrible',
				],
				'execute'=>[
					'excecute',
				],
				'execution'=>[
					'excecution',
				],
				'executive'=>[
					'exective',
				],
				'exemplar'=>[
					'exempler',
				],
				'exemplariness'=>[
					'exemplariniss',
				],
				'exemplarinesses'=>[
					'exemplarinisses',
				],
				'exemplary'=>[
					'exemplery',
				],
				'exempt'=>[
					'exampt',
					'excempt',
				],
				'exequatur'=>[
					'exeqautur',
				],
				'exequaturs'=>[
					'exeqauturs',
				],
				'exercise'=>[
					'excercise',
					'excersise',
					'exercice',
					'exercise exercise',
					'exercise exercise exercise',
					'exercize',
				],
				'exerted'=>[
					'extered',
				],
				'exfoliate'=>[
					'exfolliate',
				],
				'exhaust'=>[
					'exaust',
					'exhuast',
				],
				'exhaustible'=>[
					'exhaustable',
				],
				'exhaustively'=>[
					'exhaustivly',
				],
				'exhaustivities'=>[
					'exhaustiviteis',
					'exhaustivitis',
				],
				'exhaustlessly'=>[
					'exhaustlessally',
					'exhaustlessaly',
					'exhaustlessely',
					'exhaustlesslly',
				],
				'exhibit'=>[
					'exbit',
					'exhbit',
					'exhibt',
					'exibit',
				],
				'exhibiting'=>[
					'exbiting',
					'exhbiting',
					'exhibting',
					'exibiting',
				],
				'exhibition'=>[
					'exhibiton',
					'exhibtion',
					'exibition',
				],
				'exhibitions'=>[
					'exjibitions',
				],
				'exhibits'=>[
					'exbits',
					'exhbits',
					'exhibts',
					'exibits',
				],
				'exhilarate'=>[
					'exhilirate',
				],
				'exigence'=>[
					'exigance',
				],
				'exigency'=>[
					'exigensy',
				],
				'exigent'=>[
					'exigant',
				],
				'exigently'=>[
					'exigentally',
					'exigentaly',
					'exigentely',
					'exigentlly',
				],
				'exigible'=>[
					'exigable',
				],
				'exiguous'=>[
					'exigous',
				],
				'exiguously'=>[
					'exigously',
				],
				'exiguousness'=>[
					'exigousness',
				],
				'exiguousnesses'=>[
					'exigousnesses',
				],
				'exilian'=>[
					'exilan',
				],
				'eximious'=>[
					'eximous',
				],
				'exine'=>[
					'exini',
				],
				'exines'=>[
					'exinis',
				],
				'exist'=>[
					'exsist',
					'exsit',
				],
				'existence'=>[
					'existance',
					'exsistance',
					'exsistence',
					'exsitance',
					'exsitence',
				],
				'existent'=>[
					'existant',
				],
				'existential'=>[
					'existantial',
				],
				'existentialism'=>[
					'existantialism',
				],
				'existentialisms'=>[
					'existantialisms',
				],
				'existentially'=>[
					'existantially',
				],
				'existing'=>[
					'exisiting',
					'exsiting',
				],
				'exocrine'=>[
					'exocrini',
				],
				'exonuclease'=>[
					'exonuclese',
				],
				'exorbitance'=>[
					'exorbitence',
				],
				'exorbitant'=>[
					'exhorbitant',
					'exorbitent',
				],
				'exorbitantly'=>[
					'exorbitently',
				],
				'exoskeleton'=>[
					'exoskelaton',
				],
				'exothermicities'=>[
					'exothermiciteis',
					'exothermicitis',
				],
				'expandabilities'=>[
					'expandabiliteis',
					'expandabilitis',
				],
				'expanded'=>[
					'exapnded',
				],
				'expanse'=>[
					'expance',
				],
				'expansibilities'=>[
					'expansibiliteis',
					'expansibilitis',
				],
				'expansible'=>[
					'expansable',
				],
				'expansion'=>[
					'expantion',
				],
				'expansionary'=>[
					'expansionery',
				],
				'expansively'=>[
					'expansivly',
				],
				'expect'=>[
					'expect expect',
					'expect expect expect',
				],
				'expectance'=>[
					'expectence',
				],
				'expectancy'=>[
					'expectansy',
				],
				'expectant'=>[
					'expectent',
				],
				'expectation'=>[
					'expection',
				],
				'expectedly'=>[
					'expectedally',
					'expectedaly',
					'expectedely',
					'expectedlly',
				],
				'expectorant'=>[
					'expectorent',
				],
				'expectorants'=>[
					'expectorents',
				],
				'expedience'=>[
					'expedeince',
					'expediance',
					'expedince',
				],
				'expediency'=>[
					'expedeincy',
					'expediensy',
					'expedincy',
				],
				'expedient'=>[
					'expedeint',
					'expediant',
					'expedint',
				],
				'expediential'=>[
					'expedeintial',
					'expediantial',
					'expedintial',
				],
				'expedite'=>[
					'expidite',
				],
				'expeditionary'=>[
					'expeditionery',
				],
				'expeditious'=>[
					'expeditous',
				],
				'expeditiously'=>[
					'expeditiousally',
					'expeditiousaly',
					'expeditiousely',
					'expeditiouslly',
					'expeditously',
				],
				'expel'=>[
					'expell',
				],
				'expelled'=>[
					'expeled',
				],
				'expelling'=>[
					'expeling',
				],
				'expels'=>[
					'expells',
				],
				'expendabilities'=>[
					'expendabiliteis',
					'expendabilitis',
				],
				'expendable'=>[
					'expendible',
				],
				'expense'=>[
					'expence',
				],
				'expenses'=>[
					'expences',
				],
				'expensively'=>[
					'expensivly',
				],
				'experience'=>[
					'expereince',
					'experiance',
					'experience experience',
					'experience experience experience',
					'exprience',
					'experince',
				],
				'experienced'=>[
					'expereinced',
					'experinced',
				],
				'experiential'=>[
					'expereintial',
					'experiantial',
					'experintial',
				],
				'experientially'=>[
					'expereintially',
					'experintially',
				],
				'experiment'=>[
					'experement',
					'experiment experiment',
					'experiment experiment experiment',
					'experment',
					'expirement',
					'experimant',
				],
				'experimental'=>[
					'experimantal',
				],
				'experimentalism'=>[
					'experimantalism',
				],
				'experimentally'=>[
					'experimentalally',
					'experimentalaly',
					'experimentalely',
					'experimentallly',
				],
				'experimentation'=>[
					'experimantation',
				],
				'experimenters'=>[
					'experimanters',
				],
				'experimenting'=>[
					'experimanting',
				],
				'expertly'=>[
					'expertally',
					'expertaly',
					'expertely',
					'expertlly',
				],
				'expiable'=>[
					'expiible',
				],
				'explain'=>[
					'expalin',
					'explane',
				],
				'explanation'=>[
					'explaination',
					'explination',
				],
				'explanatively'=>[
					'explanativly',
				],
				'explant'=>[
					'explent',
				],
				'explantation'=>[
					'explentation',
				],
				'explicable'=>[
					'explicible',
				],
				'explicably'=>[
					'explicabally',
					'explicabaly',
					'explicabely',
					'explicablly',
				],
				'explicatively'=>[
					'explicativly',
				],
				'explicit'=>[
					'explict',
				],
				'explicitly'=>[
					'explicitely',
					'explictly',
				],
				'exploit'=>[
					'exploitate',
					'exuloit',
				],
				'exploitation'=>[
					'exaloitation',
					'exuloitation',
				],
				'exploitative'=>[
					'exploititive',
				],
				'exploitatively'=>[
					'exploitativly',
				],
				'exploiter'=>[
					'exuloiter',
				],
				'exploiting'=>[
					'exuloiting',
				],
				'exploration'=>[
					'exporation',
				],
				'exploratively'=>[
					'explorativly',
				],
				'explosively'=>[
					'explosivly',
				],
				'exponent'=>[
					'exponant',
				],
				'exponential'=>[
					'exponantial',
				],
				'exponentially'=>[
					'exponantially',
				],
				'exponentiation'=>[
					'exponantiation',
				],
				'exportabilities'=>[
					'exportabiliteis',
					'exportabilitis',
				],
				'express'=>[
					'expres',
				],
				'expressely'=>[
					'expressedly',
				],
				'expressible'=>[
					'expressable',
				],
				'expression'=>[
					'expresion',
				],
				'expressionism'=>[
					'expresionism',
				],
				'expressionless'=>[
					'expressionles',
				],
				'expressive'=>[
					'expresive',
				],
				'expressively'=>[
					'expressivly',
				],
				'expressivities'=>[
					'expressiviteis',
					'expressivitis',
				],
				'expressivity'=>[
					'expresivity',
				],
				'expressly'=>[
					'expressedly',
					'expressely',
					'expresly',
					'expressally',
					'expressaly',
					'expresslly',
				],
				'expressway'=>[
					'expresway',
				],
				'exquisitely'=>[
					'exquisately',
					'exquisitly',
				],
				'exsanguinate'=>[
					'exsanguinite',
				],
				'exsanguinations'=>[
					'exsanguinitions',
				],
				'exsiccate'=>[
					'exsicate',
				],
				'exsiccated'=>[
					'exsicated',
				],
				'exsiccates'=>[
					'exsicates',
				],
				'exsiccating'=>[
					'exsicating',
				],
				'exsiccation'=>[
					'exsication',
				],
				'exsiccations'=>[
					'exsications',
				],
				'extant'=>[
					'extint',
					'extent',
				],
				'extemporaneity'=>[
					'extemporaniety',
				],
				'extemporary'=>[
					'extemporery',
				],
				'extended'=>[
					'extented',
				],
				'extendedly'=>[
					'extendedally',
					'extendedaly',
					'extendedely',
					'extendedlly',
				],
				'extendible'=>[
					'extendable',
				],
				'extensible'=>[
					'extensable',
				],
				'extension'=>[
					'extention',
				],
				'extension '=>[
					'extention',
				],
				'extensions'=>[
					'extentions',
				],
				'extensive'=>[
					'exstensive',
				],
				'extensively'=>[
					'exten-sively',
					'extensivly',
				],
				'extent'=>[
					'extant',
				],
				'extenuate'=>[
					'extenaute',
				],
				'extenuated'=>[
					'extenauted',
				],
				'extenuates'=>[
					'extenautes',
				],
				'extenuation'=>[
					'extenaution',
				],
				'extenuator'=>[
					'extenautor',
				],
				'exterminate'=>[
					'exterminite',
				],
				'exterminator'=>[
					'exterminitor',
				],
				'extermining'=>[
					'exterminang',
				],
				'external'=>[
					'exerternal',
					'extemal',
				],
				'exterritorial'=>[
					'exteritorial',
				],
				'extinct'=>[
					'extincted',
				],
				'extinction'=>[
					'extionction',
				],
				'extinguishable'=>[
					'extinguishible',
				],
				'extinguisher'=>[
					'extinguiser',
				],
				'extol'=>[
					'extoll',
				],
				'extortionary'=>[
					'extortionery',
				],
				'extortionately'=>[
					'extortionatly',
				],
				'extra-terrestrial'=>[
					'extra-terrestial',
				],
				'extracellular'=>[
					'extracelluler',
					'extracelular',
				],
				'extracorporeal'=>[
					'extracorporel',
				],
				'extracted'=>[
					'exctracted',
				],
				'extractively'=>[
					'extractivly',
				],
				'extracurricular'=>[
					'extracuricular',
					'extracurriculer',
				],
				'extraditable'=>[
					'extraditible',
				],
				'extrahepatic'=>[
					'extraepatic',
				],
				'extraliterary'=>[
					'extraliterery',
				],
				'extramusical'=>[
					'extramuiscal',
				],
				'extranuclear'=>[
					'extranucleer',
					'extranucler',
				],
				'extraordinaire'=>[
					'extraordiniire',
				],
				'extraordinarily'=>[
					'extrordinarily',
					'extraordinirily',
				],
				'extraordinary'=>[
					'extrordinary',
					'extraordinery',
					'extraordiniry',
				],
				'extraterrestrial'=>[
					'extraterestrial',
					'extraterrestial',
				],
				'extraterrestrials'=>[
					'extraterrestials',
				],
				'extrauterine'=>[
					'extrauterini',
				],
				'extravagance'=>[
					'extravagence',
				],
				'extravagancies'=>[
					'extravaganceis',
					'extravagancis',
				],
				'extravagancy'=>[
					'extravagansy',
				],
				'extravagant'=>[
					'extravagent',
				],
				'extravagantly'=>[
					'extravagantally',
					'extravagantaly',
					'extravagantely',
					'extravagantlly',
				],
				'extravascular'=>[
					'extravacsular',
					'extravacular',
					'extravasculer',
					'extravasular',
				],
				'extravehicular'=>[
					'extravehiculer',
				],
				'extreme'=>[
					'extreem',
				],
				'extremely'=>[
					'extemely',
					'extermely',
					'extreamly',
					'extremley',
					'extremly',
				],
				'extremophile'=>[
					'extremeophile',
				],
				'extrusion'=>[
					'extruison',
				],
				'extrusions'=>[
					'extruisons',
				],
				'extrusive'=>[
					'extruisve',
				],
				'exuberance'=>[
					'exhuberance',
					'exuberence',
				],
				'exuberant'=>[
					'exhuberant',
					'exuberent',
				],
				'exultance'=>[
					'exultence',
				],
				'exultancy'=>[
					'exultansy',
				],
				'exultant'=>[
					'exultent',
				],
				'eyass'=>[
					'eyas',
				],
				'eye'=>[
					'eye eye',
					'eye eye eye',
				],
				'eyeable'=>[
					'eyeible',
				],
				'eyeball'=>[
					'eyebal',
				],
				'eyebar'=>[
					'eyeber',
				],
				'eyedropper'=>[
					'eyedroper',
				],
				'eyedroppers'=>[
					'eyedropers',
				],
				'eyeliner'=>[
					'eyelinir',
				],
				'eyepiece'=>[
					'eyepeice',
					'eyepice',
				],
				'eyewear'=>[
					'eyeweer',
					'eyewer',
				],
				'eyewitness'=>[
					'eyewitnes',
				],
				'eyrie'=>[
					'eyrei',
					'eyri',
				],
				'ezekiel'=>[
					'ezekeil',
				],
				'èze'=>[
					'eze',
				],
				'éamonn o\'doherty'=>[
					'eamonn o\'doherty',
				],
				'échantillon'=>[
					'chantillon',
				],
				'école alsacienne'=>[
					'ecole alsacienne',
				],
				'écrits'=>[
					'ecrits',
				],
				'émigrés'=>[
					'emigres',
				],
				'être'=>[
					'etre',
				],
			];
		}
	}

?>