<?php
				
				/* EnglishMisspellingsWords_L
					
					Class for English-Misspellings for all words beginning with : L.
					
				*/

	class EnglishMisspellingsWords_L {
			/* __construct($args)
			
				Constructor.
				
				Nothing to do here.
			
			*/
			
		public function __construct($args) {
			return TRUE;
		}
		
			/* EnglishMisspellingsWords()
			
				List of English misspellings for words starting with : L.
			
			*/

		public function EnglishMisspellingsWords() {
			return [
				'Leagers'=>[
					'Leaqers',
				],
				'l\'écume'=>[
					'l\'ecume',
				],
				'l\'épervier'=>[
					'l\'epervier',
				],
				'l\'été indien'=>[
					'l\'ete indien',
					'l\'eté indien',
					'l\'éte indien',
				],
				'la cérémonie'=>[
					'la ceremonie',
				],
				'la dernière valse'=>[
					'la derniere valse',
				],
				'la follete'=>[
					'lafollete',
				],
				'la fontaine'=>[
					'lafontaine',
				],
				'label'=>[
					'lable',
				],
				'labeled'=>[
					'labelled',
					'labled',
				],
				'labiodental'=>[
					'labiodantal',
				],
				'labiodentals'=>[
					'labiodantals',
				],
				'labiovelar'=>[
					'labioveler',
				],
				'labor'=>[
					'1abor',
					'1abour',
				],
				'laboratory'=>[
					'labatory',
					'labratory',
				],
				'laborer'=>[
					'1aborer',
					'1abourer',
				],
				'laborious'=>[
					'laborous',
					'labourious',
				],
				'laboriously'=>[
					'laborously',
					'labouriously',
				],
				'labyrinthian'=>[
					'labyrinthan',
				],
				'labyrinthine'=>[
					'labyrinthini',
				],
				'laccolith'=>[
					'lacolith',
				],
				'laciniate'=>[
					'lacinaate',
				],
				'laciniation'=>[
					'lacinaation',
				],
				'laciniations'=>[
					'lacinaations',
				],
				'lack'=>[
					'laclr',
				],
				'lacrosse'=>[
					'lacrose',
				],
				'lactary'=>[
					'lactery',
				],
				'lactobacillus'=>[
					'lactobacilus',
				],
				'lacunar'=>[
					'lacuner',
				],
				'lacunary'=>[
					'lacunery',
				],
				'lacustrine'=>[
					'lacustrini',
				],
				'laddie'=>[
					'laddei',
					'laddi',
				],
				'laden'=>[
					'ladden',
				],
				'ladened'=>[
					'ladend',
				],
				'lady'=>[
					'lady lady',
					'lady lady lady',
				],
				'laggard'=>[
					'lagard',
				],
				'laggardly'=>[
					'lagardly',
				],
				'laggardness'=>[
					'lagardness',
				],
				'laggardnesses'=>[
					'lagardnesses',
				],
				'lagging'=>[
					'laging',
				],
				'lagniappe'=>[
					'lagniape',
				],
				'lagomorph'=>[
					'lagomourph',
				],
				'lagomorphs'=>[
					'lagomourphs',
				],
				'lahar'=>[
					'laar',
					'laher',
				],
				'lahars'=>[
					'laars',
				],
				'laid'=>[
					'layed',
				],
				'laitance'=>[
					'laitence',
				],
				'lake'=>[
					'laek',
					'lake lake',
					'lake lake lake',
				],
				'lake-based'=>[
					'lake based',
					'lakebased',
				],
				'lall'=>[
					'lal',
				],
				'lallygagged'=>[
					'lallygaged',
				],
				'lallygagging'=>[
					'lallygaging',
				],
				'lambda'=>[
					'lamda',
				],
				'lambency'=>[
					'lambensy',
				],
				'lambent'=>[
					'lambant',
				],
				'lamellar'=>[
					'lameller',
				],
				'lamellately'=>[
					'lamellatly',
				],
				'lamellibranch'=>[
					'lamelibranch',
				],
				'lamely'=>[
					'lamly',
				],
				'lamennais'=>[
					'lamenais',
				],
				'lament'=>[
					'lamant',
				],
				'lamentable'=>[
					'lamentible',
				],
				'lamented'=>[
					'lamanted',
				],
				'lamentedly'=>[
					'lamentedally',
					'lamentedaly',
					'lamentedely',
					'lamentedlly',
				],
				'lamina'=>[
					'lamini',
				],
				'laminae'=>[
					'laminie',
				],
				'laminal'=>[
					'laminil',
				],
				'laminar'=>[
					'laminir',
				],
				'laminarian'=>[
					'laminaran',
				],
				'laminarians'=>[
					'laminirians',
				],
				'laminarin'=>[
					'laminirin',
				],
				'laminary'=>[
					'laminery',
				],
				'laminas'=>[
					'laminis',
				],
				'laminate'=>[
					'laminite',
				],
				'laminated'=>[
					'laminited',
				],
				'lamination'=>[
					'laminition',
				],
				'laminations'=>[
					'laminitions',
				],
				'laminin'=>[
					'laminan',
				],
				'laminitis'=>[
					'laminatis',
				],
				'laminitises'=>[
					'laminatises',
				],
				'lammed'=>[
					'lamned',
				],
				'lammergeier'=>[
					'lammergeeir',
					'lammergeir',
					'lammergieer',
					'lamnergeier',
				],
				'lammergeiers'=>[
					'lammergieers',
					'lamnergeiers',
				],
				'lammergeyer'=>[
					'lamnergeyer',
				],
				'lammergeyers'=>[
					'lamnergeyers',
				],
				'lamp post'=>[
					'lampost',
				],
				'lamp posts'=>[
					'lamposts',
				],
				'lamppost'=>[
					'lampost',
				],
				'lance'=>[
					'lence',
				],
				'lancinating'=>[
					'lanciniting',
				],
				'land'=>[
					'lancl',
					'land land',
					'land land land',
				],
				'land-based'=>[
					'land based',
					'landbased',
				],
				'landfall'=>[
					'landfal',
				],
				'landfill'=>[
					'landfil',
				],
				'landless'=>[
					'landles',
				],
				'landline'=>[
					'landlini',
				],
				'landlubber'=>[
					'landluber',
				],
				'landlubberly'=>[
					'landluberly',
				],
				'landlubbers'=>[
					'landlubers',
				],
				'landlubbing'=>[
					'landlubing',
				],
				'landscape'=>[
					'landcape',
					'landcsape',
					'landsape',
					'lanscape',
				],
				'landscaping'=>[
					'landscapping',
				],
				'landsleit'=>[
					'landsliet',
				],
				'landworker'=>[
					'land-worker',
				],
				'landworkers'=>[
					'land-workers',
				],
				'lanely'=>[
					'lanly',
				],
				'langbeinite'=>[
					'langbeinate',
					'langbienite',
				],
				'langbeinites'=>[
					'langbeinates',
					'langbienites',
				],
				'langoustine'=>[
					'langoustini',
				],
				'language'=>[
					'laguage',
					'langauge',
					'languae',
					'language language',
					'language language language',
					'lanugage',
				],
				'languages'=>[
					'langauges',
					'lanugages',
				],
				'languish'=>[
					'languise',
				],
				'languor'=>[
					'langor',
				],
				'languorous'=>[
					'langorous',
				],
				'languorously'=>[
					'langorously',
				],
				'languors'=>[
					'langors',
				],
				'laniary'=>[
					'laniery',
				],
				'lanner'=>[
					'laner',
				],
				'lanneret'=>[
					'laneret',
				],
				'lannerets'=>[
					'lanerets',
				],
				'lantana'=>[
					'lentana',
				],
				'lantern'=>[
					'latern',
					'lentern',
				],
				'lanthanide'=>[
					'lenthanide',
				],
				'lanthanum'=>[
					'lenthanum',
				],
				'laparoscope'=>[
					'laparocope',
					'laparocsope',
					'laparosope',
					'laperoscope',
				],
				'laparoscopes'=>[
					'laperoscopes',
				],
				'laparoscopic'=>[
					'laperoscopic',
				],
				'laparoscopies'=>[
					'laperoscopies',
				],
				'laparoscopist'=>[
					'laperoscopist',
				],
				'laparoscopists'=>[
					'laperoscopists',
				],
				'laparoscopy'=>[
					'laparocopy',
					'laparocsopy',
					'laparosopy',
					'laperoscopy',
				],
				'laparotomies'=>[
					'laperotomies',
				],
				'laparotomy'=>[
					'laperotomy',
				],
				'lapidarian'=>[
					'lapidaran',
				],
				'lapidary'=>[
					'lapidery',
				],
				'lappet'=>[
					'lapet',
				],
				'lapsible'=>[
					'lapsable',
				],
				'large'=>[
					'iarge',
					'large large',
					'large large large',
				],
				'large-scale'=>[
					'largescale',
				],
				'largely'=>[
					'largeally',
					'largealy',
					'largeely',
					'largelly',
					'largley',
					'largly',
				],
				'largess'=>[
					'larges',
				],
				'largest'=>[
					'largets',
				],
				'larrigan'=>[
					'larigan',
				],
				'larrikin'=>[
					'larikin',
				],
				'larrup'=>[
					'larup',
				],
				'larvae'=>[
					'lavae',
				],
				'laryngeal'=>[
					'laryngel',
				],
				'laryngoscope'=>[
					'laryngocope',
					'laryngocsope',
					'laryngosope',
				],
				'larynx'=>[
					'larnyx',
				],
				'lascar'=>[
					'lacar',
					'lacsar',
					'lasar',
					'lascer',
				],
				'lascivious'=>[
					'lacivious',
					'lacsivious',
					'lascivous',
					'lasivious',
				],
				'lasciviously'=>[
					'lascivously',
				],
				'laserdisc'=>[
					'laserdic',
					'laserdics',
					'laserdis',
				],
				'lass'=>[
					'las',
				],
				'lassi'=>[
					'lasi',
				],
				'lassie'=>[
					'lasie',
					'lassei',
					'lassi',
				],
				'lasso'=>[
					'laso',
				],
				'last'=>[
					'last last',
					'last last last',
					'lsat',
				],
				'lastly'=>[
					'lastally',
					'lastaly',
					'lastely',
					'lastlly',
				],
				'latches'=>[
					'latchs',
				],
				'late'=>[
					'late late',
					'late late late',
				],
				'lately'=>[
					'lateally',
					'latealy',
					'lateely',
					'lateley',
					'latelly',
					'latley',
					'latly',
				],
				'latency'=>[
					'latancy',
					'latensy',
				],
				'latened'=>[
					'latend',
				],
				'latent'=>[
					'latant',
				],
				'latently'=>[
					'latentally',
					'latentaly',
					'latentely',
					'latentlly',
				],
				'later'=>[
					'lated',
				],
				'later on'=>[
					'alter on',
				],
				'laterally'=>[
					'lateraly',
				],
				'latest'=>[
					'lastest',
				],
				'latina'=>[
					'latini',
				],
				'latinas'=>[
					'latinis',
				],
				'latinization'=>[
					'latinazation',
				],
				'latinizations'=>[
					'latinazations',
				],
				'latitude'=>[
					'lattitude',
				],
				'latitudinal'=>[
					'latitudinil',
				],
				'latitudinarian'=>[
					'latitudinaran',
					'latitudinirian',
				],
				'latitudinarians'=>[
					'latitudinirians',
				],
				'latrine'=>[
					'latrini',
				],
				'latvian-occupied'=>[
					'latvian occupied',
				],
				'lauan'=>[
					'laaun',
				],
				'lauans'=>[
					'laauns',
				],
				'laudable'=>[
					'laudible',
				],
				'laugh'=>[
					'laugh laugh',
					'laugh laugh laugh',
				],
				'laughable'=>[
					'laughible',
				],
				'launch'=>[
					'lauch',
				],
				'launches'=>[
					'launchs',
				],
				'laundromat'=>[
					'laundrymat',
				],
				'laureate'=>[
					'laurete',
				],
				'laurence'=>[
					'laurenec',
				],
				'law'=>[
					'law law',
					'law law law',
				],
				'lawless'=>[
					'lawles',
				],
				'lawnmower'=>[
					'lawmower',
					'lawnower',
				],
				'lawnmowers'=>[
					'lawmowers',
					'lawnowers',
				],
				'lawyer'=>[
					'lawyre',
				],
				'lay'=>[
					'lay lay',
					'lay lay lay',
				],
				'lay low'=>[
					'layed low',
				],
				'lazar'=>[
					'lazer',
				],
				'laúd'=>[
					'laoud',
				],
				'le pèse-nerfs'=>[
					'le pese-nerfs',
				],
				'lea'=>[
					'le',
				],
				'leach'=>[
					'lech',
				],
				'leachabilities'=>[
					'lechabilities',
				],
				'lead'=>[
					'lead lead',
					'lead lead lead',
					'led',
				],
				'lead belly'=>[
					'leadbelly',
				],
				'leaden'=>[
					'leden',
				],
				'leadened'=>[
					'leadend',
				],
				'leadennesses'=>[
					'leadenesses',
				],
				'leader'=>[
					'leder',
				],
				'leaderboard'=>[
					'lederboard',
				],
				'leadership'=>[
					'ledership',
				],
				'leading'=>[
					'leding',
				],
				'leadoff'=>[
					'ledoff',
				],
				'leaf'=>[
					'lef',
				],
				'leafhopper'=>[
					'leafhoper',
				],
				'leaflet'=>[
					'leflet',
				],
				'leafy'=>[
					'lefy',
				],
				'league'=>[
					'leauge',
					'legue',
				],
				'leaguer'=>[
					'leguer',
				],
				'leak'=>[
					'lek',
				],
				'leakage'=>[
					'lekage',
				],
				'leaky'=>[
					'leky',
				],
				'leal'=>[
					'lel',
				],
				'lean'=>[
					'len',
				],
				'leaned'=>[
					'leant',
				],
				'leaning'=>[
					'lening',
				],
				'leant'=>[
					'leent',
					'lent',
				],
				'leap'=>[
					'lep',
				],
				'leaped'=>[
					'leapt',
					'lept',
				],
				'leapfrog'=>[
					'lepfrog',
				],
				'leapfrogged'=>[
					'leapfroged',
				],
				'leapfrogging'=>[
					'leapfroging',
				],
				'leapt'=>[
					'lept',
				],
				'lear'=>[
					'leer',
					'ler',
				],
				'learn'=>[
					'leanr',
					'learn learn',
					'learn learn learn',
					'leran',
					'lern',
				],
				'learned'=>[
					'learnt',
					'lerned',
					'lernt',
				],
				'learning'=>[
					'lerning',
				],
				'learns'=>[
					'lerans',
				],
				'learnt'=>[
					'lernt',
				],
				'leary'=>[
					'leery',
				],
				'leas'=>[
					'les',
				],
				'lease'=>[
					'lese',
				],
				'leaseback'=>[
					'leseback',
				],
				'leasehold'=>[
					'lesehold',
				],
				'leash'=>[
					'lesh',
				],
				'leasing'=>[
					'lesing',
				],
				'least'=>[
					'least least',
					'least least least',
					'lest',
				],
				'leather'=>[
					'lether',
				],
				'leatherback'=>[
					'letherback',
				],
				'leatherette'=>[
					'letherette',
				],
				'leatherwood'=>[
					'letherwood',
				],
				'leave'=>[
					'leave leave',
					'leave leave leave',
					'leve',
				],
				'leavened'=>[
					'leavend',
				],
				'leaves'=>[
					'leafs',
					'leves',
				],
				'lebanese-occupied'=>[
					'lebanese occupied',
				],
				'lecithinase'=>[
					'lecithinise',
				],
				'lectionary'=>[
					'lectionery',
				],
				'led'=>[
					'led led',
					'led led led',
				],
				'led by'=>[
					'lead by',
				],
				'ledge'=>[
					'lege',
				],
				'ledger'=>[
					'leger',
				],
				'ledgers'=>[
					'legers',
				],
				'ledges'=>[
					'leges',
				],
				'leewardly'=>[
					'leewardally',
					'leewardaly',
					'leewardely',
					'leewardlly',
				],
				'left'=>[
					'leaved',
					'left left',
					'left left left',
				],
				'leg'=>[
					'leg leg',
					'leg leg leg',
				],
				'legacy'=>[
					'legasy',
				],
				'legalistically'=>[
					'legalisticalally',
					'legalisticalaly',
					'legalisticalely',
					'legalisticallly',
				],
				'legally'=>[
					'legaly',
				],
				'legend'=>[
					'ledgend',
				],
				'legendary'=>[
					'ledgendary',
					'legendery',
					'legendry',
				],
				'legged'=>[
					'leged',
				],
				'legginess'=>[
					'leginess',
				],
				'legginesses'=>[
					'leginesses',
				],
				'legging'=>[
					'leging',
				],
				'leggy'=>[
					'legy',
				],
				'legible'=>[
					'legable',
				],
				'legionary'=>[
					'legionery',
				],
				'legionnaire'=>[
					'legionaire',
				],
				'legionnaires'=>[
					'legionaires',
				],
				'legislate'=>[
					'ledgislate',
					'legistlate',
				],
				'legislation'=>[
					'ledgislation',
					'legistlation',
				],
				'legislative'=>[
					'ledgislative',
					'legilative',
					'legistlative',
				],
				'legislatively'=>[
					'legislativly',
				],
				'legislator'=>[
					'ledgislator',
					'legistlator',
				],
				'legitimacy'=>[
					'legitimasy',
				],
				'legitimate'=>[
					'legimate',
					'legitamate',
				],
				'legitimately'=>[
					'legitimatly',
				],
				'legitimist'=>[
					'legimist',
				],
				'lehua'=>[
					'lehau',
				],
				'lehuas'=>[
					'lehaus',
				],
				'lei'=>[
					'lie',
				],
				'leiomyoma'=>[
					'lieomyoma',
				],
				'leiomyomas'=>[
					'lieomyomas',
				],
				'leiomyomata'=>[
					'lieomyomata',
				],
				'leis'=>[
					'lies',
				],
				'leishmania'=>[
					'lieshmania',
				],
				'leishmanial'=>[
					'lieshmanial',
				],
				'leishmanias'=>[
					'lieshmanias',
				],
				'leishmaniases'=>[
					'lieshmaniases',
				],
				'leishmaniasis'=>[
					'lieshmaniasis',
				],
				'leister'=>[
					'liester',
				],
				'leistered'=>[
					'liestered',
				],
				'leistering'=>[
					'liestering',
				],
				'leisters'=>[
					'liesters',
				],
				'leisure'=>[
					'leasure',
					'liesure',
				],
				'leisured'=>[
					'liesured',
				],
				'leisureliness'=>[
					'liesureliness',
				],
				'leisurelinesses'=>[
					'leisurelinisses',
					'liesurelinesses',
				],
				'leisurely'=>[
					'leisureally',
					'leisurealy',
					'leisureely',
					'leisurelly',
					'leisurly',
					'liesurely',
				],
				'leisures'=>[
					'liesures',
				],
				'leitmotif'=>[
					'lietmotif',
				],
				'leitmotifs'=>[
					'lietmotifs',
				],
				'leitmotiv'=>[
					'lietmotiv',
				],
				'leitmotivs'=>[
					'lietmotivs',
				],
				'lekvar'=>[
					'lekver',
				],
				'lemma'=>[
					'lemna',
				],
				'lemmas'=>[
					'lemnas',
				],
				'lemmatize'=>[
					'lemnatize',
				],
				'lemmatizing'=>[
					'lemnatizing',
				],
				'lemming'=>[
					'lemning',
				],
				'lemminglike'=>[
					'lemninglike',
				],
				'lemmings'=>[
					'lemnings',
				],
				'lendable'=>[
					'lendible',
				],
				'length'=>[
					'legnth',
					'lenght',
					'length length',
					'length length length',
					'lenth',
				],
				'lengthen'=>[
					'lenghten',
				],
				'lengthened'=>[
					'lengthend',
				],
				'lengthy'=>[
					'lenghty',
				],
				'lenience'=>[
					'leniance',
				],
				'leniency'=>[
					'leneincy',
					'leniensy',
					'lenincy',
				],
				'lenient'=>[
					'leneint',
					'leniant',
					'lenint',
				],
				'leniently'=>[
					'lenientally',
					'lenientaly',
					'lenientely',
					'lenientlly',
				],
				'lenitively'=>[
					'lenitivly',
				],
				'lens'=>[
					'lense',
				],
				'lense'=>[
					'lence',
				],
				'lent'=>[
					'lant',
				],
				'lenten'=>[
					'lanten',
				],
				'lentic'=>[
					'lantic',
				],
				'lenticular'=>[
					'lenticuler',
				],
				'lentil'=>[
					'lantil',
				],
				'lento'=>[
					'lanto',
				],
				'leonine'=>[
					'leonini',
				],
				'leopard'=>[
					'leoperd',
				],
				'leopardess'=>[
					'leoperdess',
				],
				'leopardesses'=>[
					'leoperdesses',
				],
				'leopards'=>[
					'leoperds',
				],
				'leprosy'=>[
					'leprocy',
				],
				'lesbian'=>[
					'lesban',
				],
				'leslie woodhead'=>[
					'leslie woodward',
				],
				'less'=>[
					'les',
					'less less',
					'less less less',
				],
				'less than'=>[
					'less then',
				],
				'lessee'=>[
					'lesee',
				],
				'lessen'=>[
					'lesen',
				],
				'lessened'=>[
					'lessend',
				],
				'lesser'=>[
					'iesser',
					'leser',
					'lessor',
				],
				'lesson'=>[
					'leson',
				],
				'lessor'=>[
					'lesor',
				],
				'let'=>[
					'let let',
					'let let let',
				],
				'lethal'=>[
					'letal',
				],
				'letter'=>[
					'letter letter',
					'letter letter letter',
				],
				'letterhead'=>[
					'letterhed',
				],
				'letterpress'=>[
					'letterpres',
				],
				'leucine'=>[
					'leucini',
				],
				'leukemia'=>[
					'luekemia',
					'lukemia',
				],
				'leukopoiesis'=>[
					'leukopoeisis',
					'leukopoisis',
				],
				'leukorrhea'=>[
					'leukorhea',
				],
				'leukotriene'=>[
					'leukotreine',
					'leukotrine',
				],
				'levant'=>[
					'levent',
				],
				'leveeing'=>[
					'leveieng',
				],
				'level'=>[
					'level level',
					'level level level',
					'levle',
				],
				'leveled'=>[
					'levelled',
				],
				'levelheaded'=>[
					'levelheded',
				],
				'levelheadedness'=>[
					'levelhededness',
				],
				'leveling'=>[
					'levelling',
				],
				'leviable'=>[
					'leviible',
				],
				'levitate'=>[
					'levetate',
				],
				'levorotary'=>[
					'levorotery',
				],
				'lexicon'=>[
					'lexion',
				],
				'liable'=>[
					'liible',
				],
				'liaise'=>[
					'liase',
				],
				'liaison'=>[
					'liason',
				],
				'liaisons'=>[
					'liasons',
				],
				'liam ó maonlaí'=>[
					'liam o\'maonlai',
				],
				'liar'=>[
					'lier',
				],
				'libationary'=>[
					'libationery',
				],
				'libber'=>[
					'liber',
				],
				'libeccio'=>[
					'libecio',
				],
				'libel'=>[
					'libell',
					'lible',
				],
				'libelous'=>[
					'libellous',
				],
				'liberian-occupied'=>[
					'liberian occupied',
				],
				'libertarian'=>[
					'libertaran',
				],
				'libertinage'=>[
					'libertinige',
				],
				'libertine'=>[
					'libertini',
				],
				'libertinism'=>[
					'libertinasm',
				],
				'libertinisms'=>[
					'libertinasms',
				],
				'libidinally'=>[
					'libidinilly',
				],
				'librarian'=>[
					'libraran',
				],
				'library'=>[
					'libarary',
					'libarry',
					'libary',
					'librery',
				],
				'libya'=>[
					'lybia',
				],
				'libyan-occupied'=>[
					'libyan occupied',
				],
				'licence'=>[
					'licance',
					'liscence',
				],
				'license'=>[
					'licence',
					'liscence',
					'liscense',
				],
				'licentious'=>[
					'licentous',
				],
				'licentiously'=>[
					'licentously',
				],
				'lichened'=>[
					'lichend',
				],
				'lictorian'=>[
					'lictoran',
				],
				'lidar'=>[
					'lider',
				],
				'lidocaine'=>[
					'lidocaini',
				],
				'lie'=>[
					'lei',
					'lie lie',
					'lie lie lie',
				],
				'lied'=>[
					'leid',
				],
				'lief'=>[
					'leif',
				],
				'liege'=>[
					'leige',
					'lige',
				],
				'lien'=>[
					'lein',
				],
				'lientery'=>[
					'lientary',
				],
				'lier'=>[
					'leir',
				],
				'lies'=>[
					'iies',
					'leis',
				],
				'lieu'=>[
					'leiu',
				],
				'lieutenancy'=>[
					'lieutenansy',
				],
				'lieutenant'=>[
					'leiutenant',
					'leuitenant',
					'leutenant',
					'lieutenent',
					'lieutentant',
					'liuetenant',
					'liutenant',
				],
				'life'=>[
					'life life',
					'life life life',
				],
				'life-changing experience'=>[
					'life changing experience',
				],
				'lifeguard'=>[
					'lifegaurd',
				],
				'lifeguarding'=>[
					'lifegaurding',
				],
				'lifeless'=>[
					'lifeles',
				],
				'lifeline'=>[
					'lifelini',
				],
				'lifelong'=>[
					'life-long',
				],
				'lift'=>[
					'lift lift',
					'lift lift lift',
				],
				'ligament'=>[
					'ligamant',
				],
				'light'=>[
					'Iight',
					'light light',
					'light light light',
					'lite',
				],
				'light-year'=>[
					'lightyear',
				],
				'light-years'=>[
					'lightyears',
				],
				'lightened'=>[
					'lightend',
				],
				'lighthearted'=>[
					'lightherted',
				],
				'lightheartedly'=>[
					'lighthertedly',
				],
				'lightly'=>[
					'lightally',
					'lightaly',
					'lightely',
					'lightlly',
				],
				'lightness'=>[
					'lightnes',
				],
				'lightning'=>[
					'lightening',
				],
				'lightsomely'=>[
					'lightsomly',
				],
				'lightweight'=>[
					'lightwieght',
				],
				'lightweights'=>[
					'lightwieghts',
				],
				'lignocellulose'=>[
					'lignocelulose',
				],
				'ligular'=>[
					'liguler',
				],
				'likable'=>[
					'likeable',
					'likible',
				],
				'like'=>[
					'liek',
					'like like',
					'like like like',
					'liuke',
				],
				'like-minded'=>[
					'like minded',
				],
				'likeable'=>[
					'likeible',
				],
				'liked'=>[
					'liekd',
				],
				'likelihood'=>[
					'likelyhood',
				],
				'likely'=>[
					'likeally',
					'likealy',
					'likeely',
					'likelly',
					'likley',
					'likly',
				],
				'likened'=>[
					'likend',
				],
				'likeness'=>[
					'likenes',
				],
				'lilies'=>[
					'lillies',
				],
				'lilliputian'=>[
					'lilliputan',
				],
				'limekilns'=>[
					'lime kilns',
				],
				'limina'=>[
					'limini',
				],
				'liminal'=>[
					'liminil',
				],
				'limit'=>[
					'limitate',
				],
				'limitary'=>[
					'limitery',
				],
				'limited'=>[
					'limitated',
				],
				'limitless'=>[
					'limitles',
				],
				'limitlessly'=>[
					'limitlessally',
					'limitlessaly',
					'limitlessely',
					'limitlesslly',
				],
				'limmer'=>[
					'limner',
				],
				'limousine'=>[
					'limouisne',
					'limousini',
				],
				'limousines'=>[
					'limouisnes',
				],
				'limpsy'=>[
					'limpcy',
				],
				'linable'=>[
					'linible',
				],
				'linac'=>[
					'linic',
				],
				'linacs'=>[
					'linics',
				],
				'linage'=>[
					'linige',
				],
				'linages'=>[
					'liniges',
				],
				'linalol'=>[
					'linilol',
				],
				'linalool'=>[
					'linilool',
				],
				'lincoln'=>[
					'linclon',
				],
				'lincolnshire'=>[
					'linconshire',
				],
				'line'=>[
					'line line',
					'line line line',
				],
				'lineage'=>[
					'linege',
					'liniage',
				],
				'lineal'=>[
					'linial',
				],
				'lineament'=>[
					'liniament',
				],
				'linear'=>[
					'lineer',
					'liner',
					'liniar',
				],
				'linearizations'=>[
					'linerizations',
					'liniarizations',
				],
				'linebacker'=>[
					'linibacker',
				],
				'lined'=>[
					'linid',
				],
				'lineman'=>[
					'liniman',
				],
				'linen'=>[
					'linin',
				],
				'liner'=>[
					'linir',
				],
				'linerboard'=>[
					'linirboard',
				],
				'lines'=>[
					'linis',
				],
				'linesman'=>[
					'linisman',
				],
				'lineup'=>[
					'liniup',
				],
				'liney'=>[
					'liniy',
				],
				'lingerie'=>[
					'lingerei',
					'lingeri',
				],
				'lingonberry'=>[
					'lingonbery',
				],
				'lingua'=>[
					'lingau',
				],
				'lingual'=>[
					'lingaul',
				],
				'lingually'=>[
					'lingaully',
				],
				'linguine'=>[
					'linguini',
				],
				'linguistic'=>[
					'languistic',
					'libguistic',
					'lingustic',
				],
				'linguistician'=>[
					'linguistican',
				],
				'linguistics'=>[
					'libguistics',
				],
				'linguistique'=>[
					'liguistique',
				],
				'linier'=>[
					'linaer',
				],
				'liniest'=>[
					'linaest',
				],
				'liniment'=>[
					'linament',
				],
				'linin'=>[
					'linan',
				],
				'lining'=>[
					'linang',
				],
				'linings'=>[
					'linangs',
				],
				'linins'=>[
					'linans',
				],
				'linn'=>[
					'lin',
				],
				'linnet'=>[
					'linet',
				],
				'linns'=>[
					'lins',
				],
				'lioness'=>[
					'liones',
				],
				'lipoprotein'=>[
					'lipoprotien',
				],
				'lipoproteins'=>[
					'lipoprotiens',
				],
				'lippened'=>[
					'lippend',
				],
				'lippy'=>[
					'lipy',
				],
				'liquate'=>[
					'liqaute',
				],
				'liquating'=>[
					'liqauting',
				],
				'liquation'=>[
					'liqaution',
				],
				'liqueur'=>[
					'liquer',
				],
				'liquid'=>[
					'liquid liquid',
					'liquid liquid liquid',
				],
				'liquidambar'=>[
					'liquidamber',
				],
				'liquor'=>[
					'liqor',
					'liquour',
				],
				'liquored'=>[
					'liqored',
				],
				'liquorice'=>[
					'liqorice',
				],
				'liquorices'=>[
					'liqorices',
				],
				'liquoring'=>[
					'liqoring',
				],
				'liquorish'=>[
					'liqorish',
				],
				'liquors'=>[
					'liqors',
				],
				'lisa lân'=>[
					'lisa lan',
				],
				'lissomely'=>[
					'lissomly',
				],
				'list'=>[
					'list list',
					'list list list',
				],
				'listen'=>[
					'listen listen',
					'listen listen listen',
				],
				'listenable'=>[
					'listenible',
				],
				'listened'=>[
					'listend',
				],
				'listless'=>[
					'listles',
				],
				'litany'=>[
					'littany',
				],
				'literacy'=>[
					'literasy',
				],
				'literal'=>[
					'litteral',
				],
				'literally'=>[
					'literalally',
					'literalaly',
					'literalely',
					'literallly',
					'literaly',
					'litterally',
				],
				'literarinesses'=>[
					'literarinisses',
				],
				'literary'=>[
					'literery',
				],
				'literately'=>[
					'literatly',
				],
				'literature'=>[
					'litature',
					'literture',
					'litterature',
					'liturature',
				],
				'lithely'=>[
					'lithly',
				],
				'lithotripsy'=>[
					'lithotripcy',
				],
				'lithuanian-occupied'=>[
					'lithuanian occupied',
				],
				'litigant'=>[
					'litigent',
				],
				'litigious'=>[
					'litigous',
				],
				'litigiously'=>[
					'litigiousally',
					'litigiousaly',
					'litigiousely',
					'litigiouslly',
					'litigously',
				],
				'litterateur'=>[
					'litterater',
				],
				'littery'=>[
					'littary',
				],
				'little'=>[
					'litle',
					'littel',
					'little little',
					'little little little',
				],
				'livable'=>[
					'liveable',
					'livible',
				],
				'live'=>[
					'live live',
					'live live live',
				],
				'live in'=>[
					'livein',
				],
				'liveable'=>[
					'liveible',
				],
				'lived'=>[
					'liued',
				],
				'lively'=>[
					'liveally',
					'livealy',
					'liveely',
					'livelly',
					'livley',
					'livly',
				],
				'livened'=>[
					'livend',
				],
				'liveried'=>[
					'livereid',
					'liverid',
				],
				'livetrapping'=>[
					'livetraping',
				],
				'lividly'=>[
					'lividally',
					'lividaly',
					'lividely',
					'lividlly',
				],
				'living'=>[
					'livmg',
				],
				'llama'=>[
					'lama',
				],
				'llano'=>[
					'lano',
				],
				'loadstar'=>[
					'loadster',
				],
				'loathly'=>[
					'loathally',
					'loathaly',
					'loathely',
					'loathlly',
				],
				'loathsomely'=>[
					'loathsomly',
				],
				'lobar'=>[
					'lober',
				],
				'lobately'=>[
					'lobatly',
				],
				'lobbed'=>[
					'lobed',
				],
				'lobber'=>[
					'lober',
				],
				'lobby'=>[
					'loby',
				],
				'lobbygows'=>[
					'lobygows',
				],
				'lobbyisms'=>[
					'lobyisms',
				],
				'lobbyists'=>[
					'lobyists',
				],
				'loblolly'=>[
					'loblolally',
					'loblolaly',
					'loblolely',
					'loblollly',
				],
				'locally'=>[
					'localy',
				],
				'locate'=>[
					'locate locate',
					'locate locate locate',
				],
				'located'=>[
					'loacted',
				],
				'location'=>[
					'loction',
				],
				'locker room'=>[
					'lockeroom',
				],
				'locksley'=>[
					'loxely',
				],
				'locomotive'=>[
					'locamotive',
				],
				'locular'=>[
					'loculer',
				],
				'lodestar'=>[
					'lodester',
				],
				'loess'=>[
					'loes',
				],
				'log'=>[
					'log log',
					'log log log',
				],
				'loganberries'=>[
					'loganberies',
				],
				'loganberry'=>[
					'loganbery',
				],
				'logarithmically'=>[
					'logarithmicalally',
					'logarithmicalaly',
					'logarithmicalely',
					'logarithmicallly',
				],
				'logged'=>[
					'llogged',
				],
				'logger'=>[
					'loger',
				],
				'loggerhead'=>[
					'logerhead',
				],
				'loggerheads'=>[
					'logerheads',
				],
				'loggia'=>[
					'logia',
				],
				'logging'=>[
					'loging',
				],
				'loggy'=>[
					'logy',
				],
				'logically'=>[
					'logicaly',
				],
				'logician'=>[
					'logican',
				],
				'logistician'=>[
					'logistican',
				],
				'lognormal'=>[
					'lognourmal',
				],
				'lognormalities'=>[
					'lognourmalities',
				],
				'lognormality'=>[
					'lognourmality',
				],
				'lognormally'=>[
					'lognourmally',
				],
				'logogrammatic'=>[
					'logogramnatic',
				],
				'logorrhea'=>[
					'logorhea',
				],
				'logorrheic'=>[
					'logorrhiec',
				],
				'loll'=>[
					'lol',
				],
				'lollipop'=>[
					'lolipop',
				],
				'lolly'=>[
					'lolally',
					'lolaly',
					'lollly',
					'loly',
				],
				'lollygagged'=>[
					'lollygaged',
				],
				'lollygagging'=>[
					'lollygaging',
				],
				'loment'=>[
					'lomant',
				],
				'london'=>[
					'lond',
				],
				'lone'=>[
					'lone lone',
					'lone lone lone',
				],
				'loneliness'=>[
					'lonelyness',
					'lonleyness',
					'lonliness',
				],
				'lonely'=>[
					'loneally',
					'lonealy',
					'loneely',
					'loneley',
					'lonelly',
					'lonley',
					'lonly',
				],
				'lonesomely'=>[
					'lonesomly',
				],
				'long'=>[
					'iong',
					'long long',
					'long long long',
				],
				'longeing'=>[
					'longieng',
				],
				'longheadedness'=>[
					'longhededness',
				],
				'longing'=>[
					'ionging',
				],
				'longings'=>[
					'iongings',
				],
				'longitudinal'=>[
					'longitudinil',
				],
				'longitudinally'=>[
					'longitudinalally',
					'longitudinalaly',
					'longitudinalely',
					'longitudinallly',
					'longitudinilly',
				],
				'longline'=>[
					'longlini',
				],
				'longs'=>[
					'iongs',
				],
				'longsomely'=>[
					'longsomly',
				],
				'longueur'=>[
					'longuer',
				],
				'loofah'=>[
					'loofa',
				],
				'loofahs'=>[
					'loofas',
				],
				'look'=>[
					'look look',
					'look look look',
				],
				'looking'=>[
					'loking',
				],
				'loosely'=>[
					'loosley',
					'loosly',
				],
				'loosened'=>[
					'loosend',
				],
				'loppers'=>[
					'lopers',
				],
				'loppy'=>[
					'lopy',
				],
				'lopsidedly'=>[
					'lopsidedally',
					'lopsidedaly',
					'lopsidedely',
					'lopsidedlly',
				],
				'loquacious'=>[
					'loqaucious',
					'loquacous',
				],
				'loquaciously'=>[
					'loqauciously',
					'loquacously',
				],
				'loquaciousness'=>[
					'loqauciousness',
				],
				'loquacity'=>[
					'loqaucity',
				],
				'loquat'=>[
					'loqaut',
				],
				'lordly'=>[
					'lordally',
					'lordaly',
					'lordely',
					'lordlly',
				],
				'lorry'=>[
					'lory',
				],
				'los angeles'=>[
					'los angles',
				],
				'losable'=>[
					'losible',
				],
				'loses'=>[
					'looses',
				],
				'losing'=>[
					'loosing',
					'loseing',
				],
				'loss'=>[
					'los',
				],
				'lossy'=>[
					'loscy',
					'losy',
				],
				'lost'=>[
					'losed',
					'lost lost',
					'lost lost lost',
					'lsot',
				],
				'lot'=>[
					'lot lot',
					'lot lot lot',
				],
				'lotah'=>[
					'lota',
				],
				'lotahs'=>[
					'lotas',
				],
				'lottery'=>[
					'lottary',
				],
				'loud'=>[
					'loud loud',
					'loud loud loud',
				],
				'loudened'=>[
					'loudend',
				],
				'loudspeaker'=>[
					'loudspeker',
				],
				'lough neagh'=>[
					'lough neah',
				],
				'louis lecoin'=>[
					'henri lecoin',
				],
				'louisiana'=>[
					'louisana',
					'louisianna',
					'lousiana',
				],
				'loungewear'=>[
					'loungeweer',
					'loungewer',
				],
				'lousiest'=>[
					'louisest',
				],
				'lousiness'=>[
					'louisness',
				],
				'lousinesses'=>[
					'louisnesses',
				],
				'lousy'=>[
					'loucy',
				],
				'lovable'=>[
					'loveable',
					'lovible',
				],
				'love'=>[
					'loev',
					'love love',
					'love love love',
					'lveo',
					'lvoe',
				],
				'loveable'=>[
					'loveible',
				],
				'loveless'=>[
					'loveles',
				],
				'lovelornness'=>[
					'lovelorness',
				],
				'lovelornnesses'=>[
					'lovelornesses',
				],
				'lovely'=>[
					'loveally',
					'lovealy',
					'loveely',
					'lovelly',
					'lovley',
					'lovly',
				],
				'low'=>[
					'low low',
					'low low low',
				],
				'low-down'=>[
					'lowdown',
				],
				'lower than'=>[
					'lower then',
				],
				'lowly'=>[
					'lowally',
					'lowaly',
					'lowlly',
				],
				'luau'=>[
					'lauu',
				],
				'luaus'=>[
					'lauus',
				],
				'lubber'=>[
					'luber',
				],
				'lubberliness'=>[
					'luberliness',
				],
				'lubberlinesses'=>[
					'lubberlinisses',
					'luberlinesses',
				],
				'lubricant'=>[
					'lubricent',
				],
				'lubrication'=>[
					'lubrification',
				],
				'lubricious'=>[
					'lubricous',
				],
				'lubriciously'=>[
					'lubricously',
				],
				'lucence'=>[
					'lucance',
				],
				'lucency'=>[
					'lucensy',
				],
				'lucent'=>[
					'lucant',
				],
				'lucidly'=>[
					'lucidally',
					'lucidaly',
					'lucidely',
					'lucidlly',
				],
				'luckily'=>[
					'luckially',
					'luckialy',
					'luckiely',
					'luckilly',
					'luckly',
				],
				'lucky'=>[
					'lukcy',
				],
				'luggage'=>[
					'lugage',
				],
				'lugger'=>[
					'luger',
				],
				'lugubrious'=>[
					'lugubrous',
				],
				'lugubriously'=>[
					'lugubrously',
				],
				'lull'=>[
					'lul',
				],
				'lullaby'=>[
					'lulaby',
				],
				'lumbar'=>[
					'lumber',
				],
				'lumina'=>[
					'lumini',
				],
				'luminaire'=>[
					'luminiire',
				],
				'luminal'=>[
					'luminil',
				],
				'luminance'=>[
					'luminence',
					'luminince',
				],
				'luminaria'=>[
					'luminiria',
				],
				'luminary'=>[
					'luminery',
					'luminiry',
				],
				'luminescence'=>[
					'luminecence',
					'luminecsence',
					'luminescance',
					'luminesence',
					'luminiscence',
				],
				'luminescent'=>[
					'luminecent',
					'luminecsent',
					'luminescant',
					'luminesent',
					'luminiscent',
				],
				'luminiferous'=>[
					'luminaferous',
				],
				'luminism'=>[
					'luminasm',
				],
				'lummox'=>[
					'lumnox',
				],
				'lummoxes'=>[
					'lumnoxes',
				],
				'lunacy'=>[
					'lunasy',
				],
				'lunar'=>[
					'luner',
				],
				'lunarian'=>[
					'lunaran',
				],
				'lunately'=>[
					'lunatly',
				],
				'lunches'=>[
					'lunchs',
				],
				'lunisolar'=>[
					'lunisoler',
				],
				'lunular'=>[
					'lunuler',
				],
				'lupine'=>[
					'lupini',
				],
				'luridly'=>[
					'luridally',
					'luridaly',
					'luridely',
					'luridlly',
				],
				'luscious'=>[
					'lucious',
					'lucsious',
					'luscous',
					'lusious',
				],
				'lusciously'=>[
					'luscously',
				],
				'lutein'=>[
					'lutien',
				],
				'luteinization'=>[
					'luteinazation',
					'lutienization',
				],
				'luteinizations'=>[
					'luteinazations',
					'lutienizations',
				],
				'luteinize'=>[
					'luteinaze',
					'lutienize',
				],
				'luteinized'=>[
					'lutienized',
				],
				'luteinizes'=>[
					'lutienizes',
				],
				'luteinizing'=>[
					'luteinazing',
					'lutienizing',
				],
				'luxuriance'=>[
					'luxurience',
				],
				'luxuriant'=>[
					'luxurient',
				],
				'luxurious'=>[
					'luxurous',
				],
				'luxuriously'=>[
					'luxurously',
				],
				'luxury'=>[
					'luxary',
				],
				'lwei'=>[
					'lwie',
				],
				'lweis'=>[
					'lwies',
				],
				'lycanthropy'=>[
					'lycenthropy',
				],
				'lying'=>[
					'lieing',
				],
				'lymphokine'=>[
					'lymphokini',
				],
				'lyonnaise'=>[
					'lyonaise',
				],
				'lyrately'=>[
					'lyratly',
				],
				'lysine'=>[
					'lysini',
				],
				'lyssa'=>[
					'lysa',
				],
				'lópez'=>[
					'lopez',
				],
			];
		}
	}

?>