<?php
		
		/* UTF-8 TEST
		
			中文汉字漢字
		
		*/
		
				/* EnglishMisspellingsWords_Q
					
					Class for English-Misspellings for all words beginning with : Q.
					
				*/

	class EnglishMisspellingsWords_Q {
			/* __construct($args)
			
				Constructor.
				
				Nothing to do here.
			
			*/
			
		public function __construct($args) {
			return TRUE;
		}
		
			/* EnglishMisspellingsWords()
			
				List of English misspellings for words starting with : Q.
			
			*/

		public function EnglishMisspellingsWords() {
			return [
				'qabalah'=>[
					'qabala',
				],
				'qabalahs'=>[
					'qabalas',
				],
				'qindar'=>[
					'qinder',
				],
				'qintar'=>[
					'qinter',
				],
				'quack'=>[
					'qauck',
				],
				'quacks'=>[
					'qaucks',
				],
				'quacksalver'=>[
					'qaucksalver',
				],
				'quacksalvers'=>[
					'qaucksalvers',
				],
				'quacky'=>[
					'qaucky',
				],
				'quad'=>[
					'qaud',
				],
				'quadplex'=>[
					'qaudplex',
				],
				'quadrangle'=>[
					'qaudrangle',
				],
				'quadrangular'=>[
					'qaudrangular',
					'quadranguler',
				],
				'quadrant'=>[
					'qaudrant',
					'quadrent',
				],
				'quadraphonic'=>[
					'qaudraphonic',
				],
				'quadraphonics'=>[
					'qaudraphonics',
				],
				'quadrat'=>[
					'qaudrat',
				],
				'quadrate'=>[
					'qaudrate',
				],
				'quadratic'=>[
					'qaudratic',
				],
				'quadratically'=>[
					'qaudratically',
				],
				'quadratics'=>[
					'qaudratics',
				],
				'quadrature'=>[
					'qaudrature',
				],
				'quadrennial'=>[
					'qaudrennial',
					'quadrenial',
				],
				'quadrennially'=>[
					'qaudrennially',
					'quadrenially',
				],
				'quadrennials'=>[
					'qaudrennials',
				],
				'quadrennium'=>[
					'qaudrennium',
					'quadrenium',
				],
				'quadrenniums'=>[
					'qaudrenniums',
				],
				'quadric'=>[
					'qaudric',
				],
				'quadriceps'=>[
					'qaudriceps',
				],
				'quadricepses'=>[
					'qaudricepses',
				],
				'quadriga'=>[
					'qaudriga',
				],
				'quadrilateral'=>[
					'qaudrilateral',
				],
				'quadrilaterals'=>[
					'qaudrilaterals',
				],
				'quadrille'=>[
					'qaudrille',
				],
				'quadrillion'=>[
					'qaudrillion',
					'quadrilion',
				],
				'quadrillions'=>[
					'qaudrillions',
				],
				'quadrillionth'=>[
					'qaudrillionth',
					'quadrilionth',
				],
				'quadrillionths'=>[
					'qaudrillionths',
				],
				'quadripartite'=>[
					'qaudripartite',
					'quadripertite',
				],
				'quadriphonic'=>[
					'qaudriphonic',
				],
				'quadriphonics'=>[
					'qaudriphonics',
				],
				'quadriplegia'=>[
					'qaudriplegia',
				],
				'quadriplegias'=>[
					'qaudriplegias',
				],
				'quadriplegic'=>[
					'qaudriplegic',
				],
				'quadriplegics'=>[
					'qaudriplegics',
				],
				'quadrivalent'=>[
					'qaudrivalent',
					'quadrivalant',
				],
				'quadrivalents'=>[
					'qaudrivalents',
				],
				'quadrivium'=>[
					'qaudrivium',
				],
				'quadroon'=>[
					'qaudroon',
				],
				'quadrumanous'=>[
					'qaudrumanous',
				],
				'quadrumvirate'=>[
					'qaudrumvirate',
				],
				'quadrumvirates'=>[
					'qaudrumvirates',
				],
				'quadruped'=>[
					'qaudruped',
					'quadraped',
					'quadriped',
				],
				'quadrupedal'=>[
					'quadrapedal',
					'quadripedal',
					'quadropedal',
				],
				'quadrupedalism'=>[
					'quadrapedalism',
					'quadripedalism',
				],
				'quadruple'=>[
					'qaudruple',
				],
				'quadruplet'=>[
					'qaudruplet',
				],
				'quadruplicate'=>[
					'qaudruplicate',
				],
				'quadruplicated'=>[
					'qaudruplicated',
				],
				'quadruplicates'=>[
					'qaudruplicates',
				],
				'quadruplicating'=>[
					'qaudruplicating',
				],
				'quadruplication'=>[
					'qaudruplication',
				],
				'quadruplicities'=>[
					'qaudruplicities',
				],
				'quadruplicity'=>[
					'qaudruplicity',
				],
				'quadrupole'=>[
					'qaudrupole',
					'quadrapole',
				],
				'quads'=>[
					'qauds',
				],
				'quaere'=>[
					'qauere',
				],
				'quaestor'=>[
					'qauestor',
				],
				'quaff'=>[
					'qauff',
				],
				'quaffs'=>[
					'qauffs',
				],
				'quag'=>[
					'qaug',
				],
				'quagga'=>[
					'qaugga',
					'quaga',
				],
				'quaggas'=>[
					'quagas',
				],
				'quaggier'=>[
					'quagier',
				],
				'quaggy'=>[
					'qauggy',
					'quagy',
				],
				'quagmire'=>[
					'qaugmire',
				],
				'quags'=>[
					'qaugs',
				],
				'quahaug'=>[
					'quaaug',
				],
				'quahaugs'=>[
					'quaaugs',
				],
				'quahog'=>[
					'qauhog',
					'quaog',
				],
				'quahogs'=>[
					'quaogs',
				],
				'quai'=>[
					'qaui',
				],
				'quaich'=>[
					'qauich',
				],
				'quaigh'=>[
					'qauigh',
				],
				'quail'=>[
					'qauil',
				],
				'quails'=>[
					'qauils',
				],
				'quaint'=>[
					'qauint',
				],
				'quaintly'=>[
					'quaintally',
					'quaintaly',
					'quaintely',
					'quaintlly',
				],
				'quaintnesses'=>[
					'qauintnesses',
				],
				'quais'=>[
					'qauis',
				],
				'quake'=>[
					'qauke',
				],
				'quaked'=>[
					'qauked',
				],
				'quaker'=>[
					'qauker',
				],
				'quakes'=>[
					'qaukes',
				],
				'quaky'=>[
					'qauky',
				],
				'quale'=>[
					'qaule',
				],
				'qualia'=>[
					'qaulia',
				],
				'qualification'=>[
					'qaulification',
					'qualifaction',
				],
				'qualifications'=>[
					'qaulifications',
				],
				'qualified'=>[
					'qaulified',
					'qualifeid',
					'qualifid',
					'qualifiyed',
				],
				'qualifier'=>[
					'qaulifier',
					'qualifeir',
					'qualifer',
					'qualifir',
				],
				'qualifiers'=>[
					'qualifers',
				],
				'qualify'=>[
					'qaulify',
				],
				'qualifying'=>[
					'qualifiing',
					'qualifiying',
					'qualifyng',
				],
				'qualitative'=>[
					'qaulitative',
				],
				'qualitatively'=>[
					'qaulitatively',
					'qualitativly',
				],
				'qualities'=>[
					'qualites',
				],
				'quality'=>[
					'qaulity',
				],
				'qualm'=>[
					'qaulm',
				],
				'qualmishness'=>[
					'qaulmishness',
				],
				'qualmishnesses'=>[
					'qaulmishnesses',
				],
				'qualms'=>[
					'qaulms',
				],
				'qualmy'=>[
					'qaulmy',
				],
				'quamash'=>[
					'qaumash',
				],
				'quandary'=>[
					'qaundary',
					'quandery',
					'quandry',
				],
				'quandong'=>[
					'qaundong',
				],
				'quango'=>[
					'qaungo',
				],
				'quant'=>[
					'qaunt',
					'quent',
				],
				'quanta'=>[
					'qaunta',
					'quenta',
				],
				'quantal'=>[
					'qauntal',
					'quental',
				],
				'quantic'=>[
					'qauntic',
					'quentic',
				],
				'quantifiable'=>[
					'qauntifiable',
				],
				'quantification'=>[
					'qauntification',
				],
				'quantifications'=>[
					'qauntifications',
				],
				'quantifier'=>[
					'qauntifier',
					'quantifeir',
					'quantifir',
					'quentifier',
				],
				'quantify'=>[
					'qauntify',
					'quentify',
				],
				'quantile'=>[
					'qauntile',
					'quentile',
				],
				'quantitate'=>[
					'qauntitate',
					'quentitate',
				],
				'quantitating'=>[
					'qauntitating',
				],
				'quantitation'=>[
					'qauntitation',
				],
				'quantitations'=>[
					'qauntitations',
				],
				'quantitative'=>[
					'qauntitative',
					'quantative',
					'quentitative',
				],
				'quantitatively'=>[
					'qauntitatively',
					'quantitativly',
				],
				'quantities'=>[
					'quanities',
					'quanitities',
					'quantites',
				],
				'quantity'=>[
					'qauntity',
					'quanitity',
					'quanity',
					'quantaty',
					'quentity',
				],
				'quantization'=>[
					'qauntization',
				],
				'quantizations'=>[
					'qauntizations',
				],
				'quantize'=>[
					'qauntize',
				],
				'quants'=>[
					'qaunts',
					'quents',
				],
				'quantum'=>[
					'qauntum',
					'quentum',
				],
				'quarantine'=>[
					'qaurantine',
					'quarantaine',
					'quarantini',
					'quarentine',
				],
				'quarantining'=>[
					'qaurantining',
					'quarantinang',
				],
				'quare'=>[
					'qaure',
				],
				'quark'=>[
					'qaurk',
				],
				'quarks'=>[
					'qaurks',
				],
				'quarrel'=>[
					'qaurrel',
					'quarel',
					'quarell',
				],
				'quarrellers'=>[
					'qaurrellers',
				],
				'quarrelling'=>[
					'qaurrelling',
				],
				'quarrelsome'=>[
					'qaurrelsome',
					'quarelsome',
				],
				'quarrelsomely'=>[
					'quarrelsomly',
				],
				'quarrelsomeness'=>[
					'qaurrelsomeness',
					'quarelsomeness',
				],
				'quarry'=>[
					'qaurry',
					'quary',
				],
				'quarryman'=>[
					'qaurryman',
				],
				'quart'=>[
					'qaurt',
					'quart quart',
					'quart quart quart',
				],
				'quartan'=>[
					'qaurtan',
				],
				'quarte'=>[
					'qaurte',
				],
				'quarter'=>[
					'qaurter',
					'quater',
				],
				'quarter '=>[
					'quater',
				],
				'quarterage'=>[
					'qaurterage',
				],
				'quarterages'=>[
					'qaurterages',
				],
				'quarterback'=>[
					'qaurterback',
					'quaterback',
				],
				'quarterbacking'=>[
					'qaurterbacking',
				],
				'quarterdeck'=>[
					'qaurterdeck',
				],
				'quarterfinal'=>[
					'qaurterfinal',
					'quarterfinil',
				],
				'quarterfinalist'=>[
					'qaurterfinalist',
					'quarterfinilist',
				],
				'quarterfinals'=>[
					'quarterfinils',
					'quaterfinals',
				],
				'quarterings'=>[
					'qaurterings',
				],
				'quarterlies'=>[
					'qaurterlies',
				],
				'quarterly'=>[
					'qaurterly',
					'quarterally',
					'quarteraly',
					'quarterely',
					'quarterlly',
					'quaterly',
				],
				'quartermaster'=>[
					'qaurtermaster',
					'quatermaster',
				],
				'quartermasters'=>[
					'qaurtermasters',
				],
				'quartern'=>[
					'qaurtern',
				],
				'quartersawn'=>[
					'qaurtersawn',
				],
				'quarterstaff'=>[
					'qaurterstaff',
				],
				'quartes'=>[
					'qaurtes',
				],
				'quartet'=>[
					'qaurtet',
				],
				'quartic'=>[
					'qaurtic',
				],
				'quartier'=>[
					'qaurtier',
					'quarteir',
					'quartir',
				],
				'quartile'=>[
					'qaurtile',
				],
				'quarto'=>[
					'qaurto',
				],
				'quartos'=>[
					'qaurtos',
				],
				'quarts'=>[
					'qaurts',
				],
				'quartz'=>[
					'qaurtz',
				],
				'quartzite'=>[
					'qaurtzite',
				],
				'quasar'=>[
					'qausar',
					'quaser',
				],
				'quasars'=>[
					'qausars',
				],
				'quash'=>[
					'qaush',
				],
				'quashed'=>[
					'qaushed',
				],
				'quasher'=>[
					'qausher',
				],
				'quashes'=>[
					'qaushes',
				],
				'quasi'=>[
					'qausi',
				],
				'quasicrystal'=>[
					'qausicrystal',
				],
				'quasiparticle'=>[
					'qausiparticle',
					'quasiperticle',
				],
				'quasiparticles'=>[
					'qausiparticles',
					'quasiperticles',
				],
				'quass'=>[
					'qauss',
					'quas',
				],
				'quasses'=>[
					'qausses',
				],
				'quassia'=>[
					'qaussia',
				],
				'quassin'=>[
					'qaussin',
				],
				'quatari-occupied'=>[
					'quatari occupied',
				],
				'quate'=>[
					'qaute',
				],
				'quatercentenary'=>[
					'qautercentenary',
					'quatercantenary',
					'quatercentenery',
				],
				'quaternary'=>[
					'qauternary',
					'quarternary',
					'quaternery',
				],
				'quaternion'=>[
					'qauternion',
				],
				'quaternions'=>[
					'qauternions',
				],
				'quatorze'=>[
					'qautorze',
				],
				'quatrain'=>[
					'qautrain',
				],
				'quatre'=>[
					'qautre',
				],
				'quatrefoil'=>[
					'qautrefoil',
				],
				'quatrefoils'=>[
					'qautrefoils',
				],
				'quatres'=>[
					'qautres',
				],
				'quattrocento'=>[
					'qauttrocento',
					'quattrocanto',
				],
				'quaver'=>[
					'qauver',
				],
				'quaveringly'=>[
					'qauveringly',
				],
				'quavers'=>[
					'qauvers',
				],
				'quavery'=>[
					'qauvery',
				],
				'quay'=>[
					'qauy',
				],
				'quayage'=>[
					'qauyage',
				],
				'quays'=>[
					'qauys',
				],
				'quayside'=>[
					'qauyside',
				],
				'queasy'=>[
					'queacy',
					'queazy',
					'quesy',
				],
				'queened'=>[
					'queend',
				],
				'queenly'=>[
					'queenally',
					'queenaly',
					'queenely',
					'queenlly',
				],
				'quell'=>[
					'quel',
				],
				'quesadilla'=>[
					'quesadila',
				],
				'question'=>[
					'question question',
					'question question question',
				],
				'questionable'=>[
					'questionible',
				],
				'questionably'=>[
					'questionabally',
					'questionabaly',
					'questionabely',
					'questionablly',
				],
				'questionary'=>[
					'questionery',
				],
				'questioned'=>[
					'questionned',
				],
				'questionnaire'=>[
					'questionaire',
				],
				'questionnaires'=>[
					'questionaires',
				],
				'quibble'=>[
					'quible',
				],
				'quibblers'=>[
					'quiblers',
				],
				'quibbling'=>[
					'quibling',
				],
				'quick'=>[
					'quick quick',
					'quick quick quick',
				],
				'quickened'=>[
					'quickend',
				],
				'quickie'=>[
					'quickei',
					'quicki',
				],
				'quickly'=>[
					'quicklyu',
					'quicky',
					'quikly',
				],
				'quiescence'=>[
					'quiescance',
				],
				'quiescent'=>[
					'queiscent',
					'quiecent',
					'quiecsent',
					'quiesent',
					'quiscent',
				],
				'quiet'=>[
					'queit',
					'quiet quiet',
					'quiet quiet quiet',
					'quit',
				],
				'quietened'=>[
					'quietend',
				],
				'quietism'=>[
					'queitism',
					'quitism',
				],
				'quietly'=>[
					'quitely',
				],
				'quietude'=>[
					'queitude',
					'quitude',
				],
				'quill'=>[
					'quil',
				],
				'quinacrine'=>[
					'quinacrini',
					'quinicrine',
				],
				'quinary'=>[
					'quinery',
					'quiniry',
				],
				'quinate'=>[
					'quinite',
				],
				'quincentenary'=>[
					'quincantenary',
					'quincentenery',
				],
				'quincentennial'=>[
					'quincantennial',
					'quincentenial',
				],
				'quincentennials'=>[
					'quincentenials',
				],
				'quindecillion'=>[
					'quindecilion',
				],
				'quindecimvir'=>[
					'quindecemvir',
				],
				'quindecimviri'=>[
					'quindecemviri',
				],
				'quinic'=>[
					'quinac',
				],
				'quinidine'=>[
					'quinadine',
				],
				'quinidines'=>[
					'quinadines',
				],
				'quiniela'=>[
					'quinaela',
				],
				'quinin'=>[
					'quinan',
				],
				'quinina'=>[
					'quinana',
					'quinini',
				],
				'quininas'=>[
					'quininis',
				],
				'quinine'=>[
					'quinane',
					'quinini',
				],
				'quinins'=>[
					'quinans',
				],
				'quinnat'=>[
					'quinat',
				],
				'quinquennial'=>[
					'quinquenial',
				],
				'quinquennially'=>[
					'quinquenially',
				],
				'quinquennials'=>[
					'quinquenials',
				],
				'quinquennium'=>[
					'quinquenium',
				],
				'quinquenniums'=>[
					'quinqueniums',
				],
				'quinquereme'=>[
					'quinquireme',
				],
				'quinsy'=>[
					'quincy',
				],
				'quintessence'=>[
					'quintesence',
					'quintessance',
				],
				'quintessential'=>[
					'quintesential',
					'quintessantial',
					'quintissential',
				],
				'quintillion'=>[
					'quintilion',
				],
				'quintillionth'=>[
					'quintilionth',
				],
				'quintino'=>[
					'qmntino',
				],
				'quipped'=>[
					'quiped',
				],
				'quipper'=>[
					'quiper',
				],
				'quippiest'=>[
					'quipiest',
				],
				'quippu'=>[
					'quipu',
				],
				'quippus'=>[
					'quipus',
				],
				'quippy'=>[
					'quipy',
				],
				'quit'=>[
					'quited',
				],
				'quite'=>[
					'qtiite',
					'qtuie',
					'quite quite',
					'quite quite quite',
					'qutie',
				],
				'quittance'=>[
					'quittence',
				],
				'quizzes'=>[
					'quizes',
				],
				'quodlibet'=>[
					'qodlibet',
				],
				'quodlibets'=>[
					'qodlibets',
				],
				'quods'=>[
					'qods',
				],
				'quohog'=>[
					'qohog',
				],
				'quohogs'=>[
					'qohogs',
				],
				'quoin'=>[
					'qoin',
				],
				'quoined'=>[
					'qoined',
				],
				'quoining'=>[
					'qoining',
				],
				'quoins'=>[
					'qoins',
				],
				'quoit'=>[
					'qoit',
				],
				'quoited'=>[
					'qoited',
				],
				'quoiting'=>[
					'qoiting',
				],
				'quoits'=>[
					'qoits',
				],
				'quokka'=>[
					'qokka',
				],
				'quokkas'=>[
					'qokkas',
				],
				'quoll'=>[
					'qoll',
					'quol',
				],
				'quolls'=>[
					'qolls',
				],
				'quomodos'=>[
					'qomodos',
				],
				'quondam'=>[
					'qondam',
				],
				'quorum'=>[
					'qorum',
				],
				'quorums'=>[
					'qorums',
				],
				'quota'=>[
					'qota',
				],
				'quotabilities'=>[
					'qotabilities',
				],
				'quotability'=>[
					'qotability',
				],
				'quotable'=>[
					'qotable',
					'quotible',
				],
				'quotably'=>[
					'qotably',
				],
				'quotas'=>[
					'qotas',
				],
				'quotation'=>[
					'qotation',
					'qoutation',
				],
				'quotations'=>[
					'qotations',
				],
				'quote'=>[
					'qote',
					'qoute',
				],
				'quoted'=>[
					'qoted',
					'qouted',
				],
				'quoter'=>[
					'qoter',
				],
				'quoters'=>[
					'qoters',
				],
				'quotes'=>[
					'qotes',
					'qoutes',
				],
				'quoth'=>[
					'qoth',
				],
				'quotha'=>[
					'qotha',
				],
				'quotidian'=>[
					'qotidian',
					'quotidan',
				],
				'quotidians'=>[
					'qotidians',
				],
				'quotient'=>[
					'qotient',
					'quoteint',
					'quotiant',
					'quotient quotient',
					'quotient quotient quotient',
					'quotint',
				],
				'quotients'=>[
					'qotients',
				],
				'quoting'=>[
					'qoting',
					'qouting',
				],
			];
		}
	}

?>