<?php
		
		/* UTF-8 TEST
		
			中文汉字漢字
		
		*/
				
				/* EnglishMisspellingsWords_R
					
					Class for English-Misspellings for all words beginning with : R.
					
				*/

	class EnglishMisspellingsWords_R {
			/* __construct($args)
			
				Constructor.
				
				Nothing to do here.
			
			*/
			
		public function __construct($args) {
			return TRUE;
		}
		
			/* EnglishMisspellingsWords()
			
				List of English misspellings for words starting with : R.
			
			*/

		public function EnglishMisspellingsWords() {
			return [
				'rabbet'=>[
					'rabet',
				],
				'rabbeting'=>[
					'rabeting',
				],
				'rabbi'=>[
					'rabi',
				],
				'rabbinate'=>[
					'rabbinite',
					'rabinate',
				],
				'rabbinates'=>[
					'rabbinites',
					'rabinates',
				],
				'rabbinical'=>[
					'rabbinacal',
					'rabinical',
				],
				'rabbinically'=>[
					'rabbinacally',
					'rabinically',
				],
				'rabbinism'=>[
					'rabbinasm',
					'rabinism',
				],
				'rabbinisms'=>[
					'rabbinasms',
					'rabinisms',
				],
				'rabbit'=>[
					'rabit',
				],
				'rabbitbrush'=>[
					'rabitbrush',
				],
				'rabbitbrushes'=>[
					'rabitbrushes',
				],
				'rabbiters'=>[
					'rabiters',
				],
				'rabbiting'=>[
					'rabiting',
				],
				'rabbitries'=>[
					'rabitries',
				],
				'rabble'=>[
					'rable',
				],
				'rabblement'=>[
					'rablement',
				],
				'rabblements'=>[
					'rablements',
				],
				'rabidly'=>[
					'rabidally',
					'rabidaly',
					'rabidely',
					'rabidlly',
				],
				'rabies'=>[
					'rabeis',
					'rabis',
				],
				'raccoon'=>[
					'racoon',
				],
				'raccoons'=>[
					'racoons',
				],
				'race'=>[
					'race race',
					'race race race',
				],
				'raconteur'=>[
					'raconter',
				],
				'racquet'=>[
					'raquet',
				],
				'racquetball'=>[
					'racquetbal',
				],
				'radar'=>[
					'rader',
				],
				'radian'=>[
					'radan',
				],
				'radiance'=>[
					'radience',
				],
				'radiancy'=>[
					'radiansy',
				],
				'radiant'=>[
					'radient',
				],
				'radiately'=>[
					'radiatly',
				],
				'radicchio'=>[
					'radichio',
				],
				'radicular'=>[
					'radiculer',
				],
				'radio'=>[
					'radio radio',
					'radio radio radio',
				],
				'radioactively'=>[
					'radioactivly',
				],
				'radiochemically'=>[
					'radiochemicalally',
					'radiochemicalaly',
					'radiochemicalely',
					'radiochemicallly',
				],
				'radiolarian'=>[
					'radiolaran',
				],
				'radiolucency'=>[
					'radiolucensy',
				],
				'radular'=>[
					'raduler',
				],
				'raffinate'=>[
					'raffinite',
				],
				'raffinates'=>[
					'raffinites',
				],
				'ragg'=>[
					'rag',
				],
				'ragged'=>[
					'raged',
				],
				'raggeder'=>[
					'rageder',
				],
				'raggediest'=>[
					'ragediest',
				],
				'raggedly'=>[
					'ragedly',
				],
				'raggedness'=>[
					'ragedness',
				],
				'raggednesses'=>[
					'ragednesses',
				],
				'raggedy'=>[
					'ragedy',
				],
				'raggee'=>[
					'ragee',
				],
				'raggees'=>[
					'ragees',
				],
				'raggies'=>[
					'ragies',
				],
				'ragging'=>[
					'raging',
				],
				'raggle'=>[
					'ragle',
				],
				'raggles'=>[
					'ragles',
				],
				'raggs'=>[
					'rags',
				],
				'raggy'=>[
					'ragy',
				],
				'raidió éireann'=>[
					'radio éireann',
				],
				'rail'=>[
					'rail rail',
					'rail rail rail',
				],
				'railcar'=>[
					'railcer',
				],
				'railroad'=>[
					'rail road',
				],
				'railway'=>[
					'railwaye',
				],
				'raiment'=>[
					'raimant',
				],
				'rain'=>[
					'rain rain',
					'rain rain rain',
				],
				'rainfall'=>[
					'rainfal',
				],
				'rainier'=>[
					'rainaer',
				],
				'rainily'=>[
					'rainaly',
				],
				'raining'=>[
					'rainang',
				],
				'rainmaker'=>[
					'raimaker',
					'rainaker',
				],
				'rainmakers'=>[
					'raimakers',
					'rainakers',
				],
				'rainmaking'=>[
					'raimaking',
					'rainaking',
				],
				'rainmakings'=>[
					'raimakings',
					'rainakings',
				],
				'rainsquall'=>[
					'rainsqaull',
				],
				'rainsqualls'=>[
					'rainsqaulls',
				],
				'rainwear'=>[
					'rainweer',
				],
				'raisable'=>[
					'raisible',
				],
				'raise'=>[
					'raise raise',
					'raise raise raise',
				],
				'raised'=>[
					'rasied',
					'rised',
				],
				'rajah'=>[
					'raja',
				],
				'rajahs'=>[
					'rajas',
				],
				'rally'=>[
					'ralally',
					'ralaly',
					'rallly',
					'raly',
				],
				'rambunctious'=>[
					'rambunctous',
				],
				'rambunctiously'=>[
					'rambunctiousally',
					'rambunctiousaly',
					'rambunctiousely',
					'rambunctiouslly',
					'rambunctously',
				],
				'ramie'=>[
					'ramei',
					'rami',
				],
				'rammed'=>[
					'ramned',
				],
				'rammer'=>[
					'ramner',
				],
				'rammers'=>[
					'ramners',
				],
				'rammier'=>[
					'ramnier',
				],
				'ramming'=>[
					'ramning',
				],
				'rammish'=>[
					'ramnish',
				],
				'rammy'=>[
					'ramny',
				],
				'ramosely'=>[
					'ramosly',
				],
				'rampancy'=>[
					'rampansy',
				],
				'rampant'=>[
					'rampent',
				],
				'rampart'=>[
					'rampert',
				],
				'ran'=>[
					'ran ran',
					'ran ran ran',
				],
				'ranafast'=>[
					'rannafast',
				],
				'rance'=>[
					'rence',
				],
				'range'=>[
					'range range',
					'range range range',
				],
				'ranted'=>[
					'rented',
				],
				'ranter'=>[
					'renter',
				],
				'rants'=>[
					'rents',
				],
				'ranular'=>[
					'ranuler',
				],
				'rapacious'=>[
					'rapacous',
				],
				'rapaciously'=>[
					'rapaciousally',
					'rapaciousaly',
					'rapaciousely',
					'rapaciouslly',
					'rapacously',
				],
				'rapidly'=>[
					'rapidally',
					'rapidaly',
					'rapidely',
					'rapidily',
					'rapidlly',
					'rapidy',
				],
				'rapier'=>[
					'rapeir',
					'rapir',
				],
				'rapine'=>[
					'rapini',
				],
				'rapini'=>[
					'rapina',
				],
				'rapparee'=>[
					'raparee',
					'rapperee',
				],
				'rapparees'=>[
					'raparees',
				],
				'rapped'=>[
					'raped',
				],
				'rappee'=>[
					'rapee',
				],
				'rappees'=>[
					'rapees',
				],
				'rappel'=>[
					'rapel',
				],
				'rappeling'=>[
					'rapeling',
				],
				'rappelled'=>[
					'rapelled',
				],
				'rappelling'=>[
					'rapelling',
				],
				'rappels'=>[
					'rapels',
				],
				'rappen'=>[
					'rapen',
				],
				'rapper'=>[
					'raper',
				],
				'rappers'=>[
					'rapers',
				],
				'rapping'=>[
					'raping',
				],
				'rappini'=>[
					'rapini',
					'rappina',
				],
				'rapport'=>[
					'raport',
				],
				'rapporteur'=>[
					'raporteur',
					'rapporter',
				],
				'rapprochement'=>[
					'rapprochemant',
					'raprochement',
				],
				'rapprochements'=>[
					'raprochements',
				],
				'rapscallion'=>[
					'rapcallion',
					'rapcsallion',
					'rapsallion',
					'rapscalion',
				],
				'rarefied'=>[
					'rarefeid',
					'rarefid',
				],
				'rarely'=>[
					'rareally',
					'rarealy',
					'rareely',
					'rarelly',
					'rarley',
					'rarly',
				],
				'rarified'=>[
					'rarifeid',
					'rarifid',
				],
				'rascal'=>[
					'racal',
					'racsal',
					'rasal',
				],
				'raspberry'=>[
					'rasberry',
					'raspbery',
				],
				'rassle'=>[
					'rasle',
				],
				'ratable'=>[
					'ratible',
				],
				'ratatouille'=>[
					'ratatouile',
				],
				'rateable'=>[
					'rateible',
				],
				'rather'=>[
					'rather rather',
					'rather rather rather',
				],
				'rather than'=>[
					'rather then',
				],
				'ratine'=>[
					'ratini',
				],
				'ratiocinate'=>[
					'ratiocinite',
				],
				'ratiocinated'=>[
					'ratiocinited',
				],
				'ratiocinates'=>[
					'ratiocinites',
				],
				'ratiocinating'=>[
					'ratiociniting',
				],
				'ratiocination'=>[
					'ratiocinition',
				],
				'ratiocinations'=>[
					'ratiocinitions',
				],
				'ratiocinative'=>[
					'ratiocinitive',
				],
				'ratiocinator'=>[
					'ratiocinitor',
				],
				'ratiocinators'=>[
					'ratiocinitors',
				],
				'rationalize'=>[
					'raticnalize',
				],
				'rattened'=>[
					'rattend',
				],
				'rattlebrained'=>[
					'rattlebrainid',
				],
				'rattlin\''=>[
					'ratlin\'',
				],
				'rattling'=>[
					'ratling',
				],
				'rattly'=>[
					'rattally',
					'rattaly',
					'rattely',
					'rattlly',
				],
				'ravened'=>[
					'ravend',
				],
				'ravine'=>[
					'ravini',
				],
				'rayah'=>[
					'raya',
				],
				'raúl'=>[
					'raul',
				],
				'reaccede'=>[
					'reacede',
				],
				'reaccelerate'=>[
					'reacelerate',
				],
				'reaccelerated'=>[
					'reacelerated',
				],
				'reaccelerates'=>[
					'reacelerates',
				],
				'reaccelerating'=>[
					'reacelerating',
				],
				'reaccent'=>[
					'reacent',
				],
				'reaccenting'=>[
					'reacenting',
				],
				'reaccept'=>[
					'reacept',
				],
				'reaccession'=>[
					'reacession',
				],
				'reaccessions'=>[
					'reacessions',
				],
				'reacclaimed'=>[
					'reaclaimed',
				],
				'reacclaiming'=>[
					'reaclaiming',
				],
				'reacclimatize'=>[
					'reaclimatize',
				],
				'reacclimatized'=>[
					'reaclimatized',
				],
				'reacclimatizes'=>[
					'reaclimatizes',
				],
				'reacclimatizing'=>[
					'reaclimatizing',
					'recclimatizing',
				],
				'reaccreditation'=>[
					'reacreditation',
					'reccreditation',
				],
				'reaccredited'=>[
					'reacredited',
				],
				'reaccrediting'=>[
					'reacrediting',
				],
				'reaccredits'=>[
					'reacredits',
				],
				'reaccuse'=>[
					'reacuse',
				],
				'reaccusing'=>[
					'reaccuisng',
				],
				'reach'=>[
					'reach reach',
					'reach reach reach',
					'rech',
				],
				'reached'=>[
					'eached',
				],
				'reaches'=>[
					'reachs',
				],
				'reacquaint'=>[
					'reacqauint',
				],
				'reacquaints'=>[
					'reacqauints',
				],
				'reacquire'=>[
					'recquire',
				],
				'react'=>[
					'rect',
				],
				'reactance'=>[
					'reactence',
				],
				'reactant'=>[
					'reactent',
				],
				'reaction'=>[
					'rection',
				],
				'reactionary'=>[
					'reactionery',
					'recationary',
					'rectionary',
				],
				'reactionaryisms'=>[
					'rectionaryisms',
				],
				'reactivate'=>[
					'rectivate',
				],
				'reactivated'=>[
					'reactived',
				],
				'reactive'=>[
					'rective',
				],
				'reactively'=>[
					'reactivly',
				],
				'reactor'=>[
					'rector',
				],
				'read'=>[
					'read read',
					'read read read',
					'red',
				],
				'readable'=>[
					'readible',
					'redable',
				],
				'reader'=>[
					'reder',
				],
				'readerly'=>[
					'readerally',
					'readeraly',
					'readerely',
					'readerlly',
				],
				'readership'=>[
					'redership',
				],
				'readily'=>[
					'readially',
					'readialy',
					'readiely',
					'readilly',
					'readly',
					'redily',
				],
				'reading'=>[
					'reding',
				],
				'ready'=>[
					'ready ready',
					'ready ready ready',
					'redy',
				],
				'reaffirm'=>[
					'reffirm',
				],
				'reafforestation'=>[
					'refforestation',
				],
				'reagan'=>[
					'regan',
				],
				'reagent'=>[
					'reagant',
					'regent',
				],
				'reaggregate'=>[
					'reagregate',
				],
				'reaggregated'=>[
					'reagregated',
				],
				'reaggregates'=>[
					'reagregates',
				],
				'reaggregating'=>[
					'reagregating',
				],
				'reaggregation'=>[
					'reagregation',
				],
				'reaggregations'=>[
					'reagregations',
				],
				'real'=>[
					'reai',
					'real real',
					'real real real',
					'rel',
					'rela',
				],
				'real-time'=>[
					'real time',
					'realtime',
				],
				'realgar'=>[
					'realger',
				],
				'realignment'=>[
					'realigment',
					'realignent',
				],
				'realignments'=>[
					'realigments',
					'realignents',
				],
				'realism'=>[
					'relism',
				],
				'realist'=>[
					'relist',
				],
				'realistic'=>[
					'relistic',
				],
				'reality'=>[
					'reallity',
					'relity',
				],
				'realization'=>[
					'relization',
				],
				'realize'=>[
					'relize',
				],
				'realized'=>[
					'relized',
				],
				'reallocate'=>[
					'realocate',
					'rellocate',
				],
				'really'=>[
					'erally',
					'realally',
					'realaly',
					'realely',
					'reallly',
					'realy',
					'relly',
				],
				'realm'=>[
					'relm',
				],
				'realpolitik'=>[
					'relpolitik',
				],
				'realty'=>[
					'relty',
				],
				'ream'=>[
					'rem',
				],
				'reannex'=>[
					'reanex',
				],
				'reannexations'=>[
					'reanexations',
				],
				'reap'=>[
					'rep',
				],
				'reapable'=>[
					'reapible',
				],
				'reappear'=>[
					'reapear',
					'reappeer',
					'reapper',
				],
				'reappearance'=>[
					'reappearence',
				],
				'reappearances'=>[
					'reapearances',
				],
				'reappeared'=>[
					'reapeared',
				],
				'reappears'=>[
					'reapears',
				],
				'reapplication'=>[
					'reaplication',
				],
				'reapplications'=>[
					'reaplications',
				],
				'reapplied'=>[
					'reaplied',
				],
				'reapplies'=>[
					'reaplies',
				],
				'reapply'=>[
					'reaply',
					'reappally',
					'reappaly',
					'reappely',
					'reapplly',
				],
				'reapplying'=>[
					'reaplying',
				],
				'reappoint'=>[
					'reapoint',
				],
				'reappointment'=>[
					'reapointment',
				],
				'reappointments'=>[
					'reapointments',
				],
				'reappoints'=>[
					'reapoints',
				],
				'reapportion'=>[
					'reaportion',
				],
				'reapportioned'=>[
					'reaportioned',
				],
				'reapportioning'=>[
					'reaportioning',
				],
				'reapportionment'=>[
					'reaportionment',
					'reapportioment',
					'reapportionent',
					'reapportionmant',
					'repportionment',
				],
				'reappraisal'=>[
					'reapraisal',
					'reppraisal',
				],
				'reappraise'=>[
					'reapraise',
				],
				'reapprove'=>[
					'reaprove',
				],
				'reapproved'=>[
					'reaproved',
				],
				'reapproves'=>[
					'reaproves',
				],
				'rear'=>[
					'reer',
					'rer',
				],
				'rearguard'=>[
					'reargaurd',
					'rerguard',
				],
				'rearm'=>[
					'rerm',
				],
				'rearousing'=>[
					'rearouisng',
				],
				'rearrange'=>[
					'rearange',
					'rerrange',
				],
				'rearrangements'=>[
					'rearangements',
				],
				'rearrest'=>[
					'rearest',
				],
				'reason'=>[
					'reaon',
					'reason reason',
					'reason reason reason',
					'reson',
				],
				'reasonabilities'=>[
					'resonabilities',
				],
				'reasonable'=>[
					'reasonible',
					'resonable',
				],
				'reasoning'=>[
					'resoning',
				],
				'reasons'=>[
					'reaons',
					'reasosn',
				],
				'reassemble'=>[
					'reasemble',
					'ressemble',
				],
				'reassert'=>[
					'reasert',
					'ressert',
				],
				'reassess'=>[
					'reasses',
					'ressess',
				],
				'reassign'=>[
					'reasign',
				],
				'reassignment'=>[
					'reassigment',
					'reassignent',
				],
				'reassignments'=>[
					'reassigments',
					'reassignents',
				],
				'reassurance'=>[
					'reassurence',
				],
				'reassure'=>[
					'reasure',
					'ressure',
				],
				'reauthorization'=>[
					'reuthorization',
				],
				'reawakened'=>[
					'reawakend',
				],
				'rebalance'=>[
					'rebalence',
				],
				'rebar'=>[
					'reber',
				],
				'rebarbatively'=>[
					'rebarbativly',
				],
				'rebbe'=>[
					'rebe',
				],
				'rebbetzin'=>[
					'rebetzin',
				],
				'rebbetzins'=>[
					'rebetzins',
				],
				'rebellion'=>[
					'rebelion',
					'rebellian',
				],
				'rebellious'=>[
					'rebelious',
					'rebellous',
				],
				'rebelliously'=>[
					'rebellously',
				],
				'rebroadcast'=>[
					'rebroadcasted',
				],
				'rebuilding'=>[
					'rebulding',
				],
				'rebuilt'=>[
					'rebuilded',
				],
				'rebuttal'=>[
					'rebuttle',
				],
				'recalcitrance'=>[
					'recalcitrence',
				],
				'recalcitrancy'=>[
					'recalcitransy',
				],
				'recalcitrant'=>[
					'recalcitrent',
				],
				'recall'=>[
					'recal',
				],
				'recalled'=>[
					'realled',
				],
				'recant'=>[
					'recent',
				],
				'recappable'=>[
					'recapable',
				],
				'recapping'=>[
					'recaping',
				],
				'recast'=>[
					'recasted',
				],
				'recce'=>[
					'rece',
				],
				'recces'=>[
					'reces',
				],
				'receded'=>[
					'receeded',
				],
				'receding'=>[
					'receeding',
				],
				'receipt'=>[
					'reciept',
				],
				'receivable'=>[
					'receivible',
					'recievable',
				],
				'receive'=>[
					'receive receive',
					'receive receive receive',
					'receve',
					'recieve',
					'recive',
				],
				'received'=>[
					'recepted',
					'receved',
					'recevied',
					'recieved',
					'recived',
				],
				'receiver'=>[
					'reciever',
				],
				'receivership'=>[
					'recievership',
				],
				'receiverships'=>[
					'recieverships',
				],
				'receives'=>[
					'recieves',
				],
				'receiving'=>[
					'receving',
					'recieving',
				],
				'recency'=>[
					'recensy',
				],
				'recent'=>[
					'recant',
					'reccent',
				],
				'recently'=>[
					'reccently',
					'recenly',
					'recentley',
					'recentyl',
				],
				'receptively'=>[
					'receptivly',
				],
				'recess'=>[
					'reces',
				],
				'recession'=>[
					'recesion',
				],
				'recessional'=>[
					'recesional',
				],
				'recessionary'=>[
					'recessionery',
				],
				'recessively'=>[
					'recessivly',
				],
				'rechannelling'=>[
					'rechanelling',
				],
				'rechristened'=>[
					'rechristend',
				],
				'recipe'=>[
					'recepe',
					'recepie',
					'recipie',
				],
				'recipes'=>[
					'recipies',
				],
				'recipient'=>[
					'recepient',
					'recipeint',
					'recipent',
					'recipiant',
					'recipint',
				],
				'reckless'=>[
					'reckles',
					'wreckless',
				],
				'recklessness'=>[
					'wrecklessness',
				],
				'reclassify'=>[
					'reclasify',
				],
				'reclinate'=>[
					'reclinite',
				],
				'recline'=>[
					'reclini',
				],
				'recliner'=>[
					'reclinir',
				],
				'reclusion'=>[
					'recluison',
				],
				'reclusions'=>[
					'recluisons',
				],
				'reclusive'=>[
					'recluisve',
				],
				'reclusively'=>[
					'recluisvely',
					'reclusivly',
				],
				'reclusiveness'=>[
					'recluisveness',
				],
				'reclusivenesses'=>[
					'recluisvenesses',
				],
				'recognise'=>[
					'recogise',
				],
				'recognizably'=>[
					'recognizabally',
					'recognizabaly',
					'recognizabely',
					'recognizablly',
				],
				'recognizance'=>[
					'recognizence',
				],
				'recognize'=>[
					'recoginise',
					'recogize',
					'recongize',
					'reconize',
				],
				'recoilless'=>[
					'recoiless',
				],
				'recoinage'=>[
					'recoinige',
				],
				'recoinages'=>[
					'recoiniges',
				],
				'recollect'=>[
					'recolect',
				],
				'recollection'=>[
					'recolection',
				],
				'recombinant'=>[
					'recombinent',
					'recombinint',
				],
				'recombinants'=>[
					'recombinints',
				],
				'recombination'=>[
					'recombinition',
				],
				'recombinational'=>[
					'recombinitional',
				],
				'recombinations'=>[
					'recombinitions',
				],
				'recombine'=>[
					'recombini',
				],
				'recommence'=>[
					'recommance',
					'recomnence',
				],
				'recommencement'=>[
					'recomnencement',
				],
				'recommencements'=>[
					'recomnencements',
				],
				'recommend'=>[
					'reccomend',
					'reccommend',
					'recomend',
					'recomnend',
				],
				'recommendable'=>[
					'recomnendable',
				],
				'recommendation'=>[
					'recomendation',
					'recomnendation',
				],
				'recommendations'=>[
					'recomnendations',
				],
				'recommendatory'=>[
					'recomnendatory',
				],
				'recommended'=>[
					'reccomended',
					'reccomended ',
					'reccommended',
					'recomended',
				],
				'recommending'=>[
					'recomending',
				],
				'recommends'=>[
					'recomends',
				],
				'recommission'=>[
					'recommision',
					'recomnission',
				],
				'recommissioned'=>[
					'recomnissioned',
				],
				'recommissioning'=>[
					'recomnissioning',
				],
				'recommissions'=>[
					'recomnissions',
				],
				'recommit'=>[
					'recomnit',
				],
				'recommitments'=>[
					'recomnitments',
				],
				'recommits'=>[
					'recomnits',
				],
				'recompense'=>[
					'recompence',
				],
				'reconceptualize'=>[
					'reconceptaulize',
				],
				'reconcilable'=>[
					'reconcilible',
				],
				'reconcile'=>[
					'reconciliate',
				],
				'reconciliation'=>[
					'reconcilation',
				],
				'recondense'=>[
					'recondence',
				],
				'reconditely'=>[
					'recondately',
					'reconditly',
				],
				'reconnaissance'=>[
					'reconaisance',
					'reconaissance',
					'reconnaisance',
					'reconnaissence',
				],
				'reconnaissances'=>[
					'reconaissances',
				],
				'reconnect'=>[
					'reconect',
				],
				'reconnections'=>[
					'reconections',
				],
				'reconnoiter'=>[
					'reconoiter',
				],
				'reconnoitered'=>[
					'reconoitered',
				],
				'reconnoitering'=>[
					'reconoitering',
				],
				'reconnoitre'=>[
					'reconoitre',
				],
				'reconnoitring'=>[
					'reconoitring',
				],
				'reconstructible'=>[
					'reconstructable',
				],
				'recontaminate'=>[
					'recontaminite',
				],
				'recontaminated'=>[
					'recontaminited',
				],
				'recontaminates'=>[
					'recontaminites',
				],
				'recontaminating'=>[
					'recontaminiting',
				],
				'recontamination'=>[
					'recontaminition',
				],
				'recontextualize'=>[
					'recontextaulize',
				],
				'recontré'=>[
					'recontre',
				],
				'reconvened'=>[
					'reconvend',
				],
				'reconveyance'=>[
					'reconveyence',
				],
				'record'=>[
					'record record',
					'record record record',
					'recored',
					'recrod',
				],
				'recorded'=>[
					'recoreded',
				],
				'recreance'=>[
					'recreence',
				],
				'recreancy'=>[
					'recreansy',
				],
				'recreate'=>[
					'recrete',
				],
				'recreation'=>[
					'recretion',
				],
				'recreational'=>[
					'recretional',
				],
				'recriminate'=>[
					'recriminite',
				],
				'recriminated'=>[
					'recriminited',
				],
				'recriminates'=>[
					'recriminites',
				],
				'recriminating'=>[
					'recriminiting',
				],
				'recrimination'=>[
					'recriminition',
				],
				'recriminations'=>[
					'recriminitions',
				],
				'recriminative'=>[
					'recriminitive',
				],
				'recriminatory'=>[
					'recriminitory',
				],
				'recrudescence'=>[
					'recrudescance',
				],
				'recrudescences'=>[
					'recrudecences',
					'recrudecsences',
					'recrudesences',
				],
				'recruited'=>[
					'recruted',
				],
				'recruiting'=>[
					'recruting',
				],
				'recrystallize'=>[
					'recrystalize',
				],
				'rectangular'=>[
					'rectanguler',
				],
				'rectangularly'=>[
					'rectangularally',
					'rectangularaly',
					'rectangularely',
					'rectangularlly',
				],
				'rectifier'=>[
					'rectifeir',
					'rectifir',
				],
				'rectilinear'=>[
					'rectilineer',
					'rectiliner',
					'rectiliniar',
				],
				'rectilinearly'=>[
					'rectilinearally',
					'rectilinearaly',
					'rectilinearely',
					'rectilinearlly',
				],
				'recumbency'=>[
					'recumbensy',
				],
				'recuperate'=>[
					'recouperate',
				],
				'recurrence'=>[
					'recurrance',
				],
				'recurrent'=>[
					'recurent',
					'recurrant',
				],
				'recurring'=>[
					'reccuring',
					'recuring',
				],
				'recursively'=>[
					'recursivly',
				],
				'recusancy'=>[
					'recusansy',
				],
				'recusant'=>[
					'recusent',
				],
				'recusing'=>[
					'recuisng',
				],
				'red'=>[
					'red red',
					'red red red',
				],
				'reddened'=>[
					'reddend',
				],
				'redefine'=>[
					'redefini',
				],
				'redefining'=>[
					'redefinang',
				],
				'redefinition'=>[
					'redefination',
				],
				'redefinitions'=>[
					'redefinations',
				],
				'redescriptions'=>[
					'redecriptions',
					'redecsriptions',
					'redesriptions',
				],
				'redetermination'=>[
					'redeterminition',
				],
				'redetermine'=>[
					'redetermini',
				],
				'redetermining'=>[
					'redeterminang',
				],
				'redevelopment'=>[
					'redevelopement',
				],
				'redipping'=>[
					'rediping',
				],
				'rediscountable'=>[
					'redicountable',
					'redicsountable',
					'rediscountible',
					'redisountable',
				],
				'rediscover'=>[
					'redicover',
					'redicsover',
					'redisover',
				],
				'redline'=>[
					'redlini',
				],
				'redlinings'=>[
					'redlinangs',
				],
				'redly'=>[
					'redally',
					'redaly',
					'redlly',
				],
				'redolence'=>[
					'redolance',
				],
				'redolency'=>[
					'redolensy',
				],
				'redolent'=>[
					'redolant',
				],
				'redoubtable'=>[
					'redoubtible',
				],
				'redress'=>[
					'redres',
				],
				'redubbing'=>[
					'redubing',
				],
				'reducible'=>[
					'reducable',
				],
				'redundancy'=>[
					'redundansy',
					'redundency',
				],
				'redundant'=>[
					'redundent',
				],
				'redundantly'=>[
					'redundently',
				],
				'reduplicatively'=>[
					'reduplicativeally',
					'reduplicativealy',
					'reduplicativeely',
					'reduplicativelly',
					'reduplicativly',
				],
				'reeligible'=>[
					'reeligable',
				],
				'reemergence'=>[
					'reemergance',
				],
				'reenact'=>[
					'reinact',
				],
				'reenter'=>[
					'reanter',
				],
				'reentrance'=>[
					'reentrence',
				],
				'reentry'=>[
					'reantry',
				],
				'reequipped'=>[
					'reequiped',
				],
				'reevaluated'=>[
					'reevalauted',
					'revaluated',
				],
				'reevaluates'=>[
					'reevalautes',
				],
				'reexamination'=>[
					'reexaminition',
				],
				'reexaminations'=>[
					'reexaminitions',
				],
				'reexamine'=>[
					'reexamini',
				],
				'reexperience'=>[
					'reexperiance',
				],
				'reexplaining'=>[
					'reexplainang',
				],
				'refastened'=>[
					'refastend',
				],
				'refence'=>[
					'refance',
				],
				'refer'=>[
					'referr',
					'refferr',
				],
				'referee'=>[
					'referree',
				],
				'reference'=>[
					'referance',
					'refernece',
					'referrence',
					'refference',
					'refrence',
				],
				'referenced'=>[
					'refrenced',
				],
				'references'=>[
					'refereces',
					'referencs',
					'refernces',
					'refrences',
				],
				'referendum'=>[
					'rejerendumi.e.',
				],
				'referent'=>[
					'referant',
				],
				'referral'=>[
					'referal',
				],
				'referred'=>[
					'refered',
					'reffered',
				],
				'referring'=>[
					'refering',
				],
				'refers'=>[
					'referes',
					'referrs',
				],
				'refill'=>[
					'refil',
				],
				'refinable'=>[
					'refinible',
				],
				'refinance'=>[
					'refinence',
					'refinince',
				],
				'refinanced'=>[
					'refininced',
				],
				'refinances'=>[
					'refininces',
				],
				'refine'=>[
					'refini',
				],
				'refined'=>[
					'refinid',
				],
				'refinement'=>[
					'refinemant',
					'refiniment',
				],
				'refinery'=>[
					'refiniry',
				],
				'refinish'=>[
					'refinash',
				],
				'refinished'=>[
					'refinashed',
				],
				'refinisher'=>[
					'refinasher',
				],
				'refinishes'=>[
					'refinashes',
				],
				'reflagging'=>[
					'reflaging',
				],
				'reflationary'=>[
					'reflationery',
				],
				'reflectance'=>[
					'reflectence',
				],
				'reflectively'=>[
					'reflectivly',
				],
				'refluence'=>[
					'refluance',
				],
				'refly'=>[
					'refally',
					'refaly',
					'reflly',
				],
				'refocusing'=>[
					'refocuisng',
				],
				'reform'=>[
					're-form',
					'refrom',
				],
				'reform-minded'=>[
					'reform minded',
				],
				'reformed'=>[
					're-formed',
				],
				'reformer'=>[
					're-former',
				],
				'reforms'=>[
					're-forms',
				],
				'refractively'=>[
					'refractivly',
				],
				'refraining'=>[
					'refrainang',
				],
				'refrainment'=>[
					'refraiment',
					'refrainent',
				],
				'refrainments'=>[
					'refraiments',
					'refrainents',
				],
				'refrangible'=>[
					'refrangable',
				],
				'refreshened'=>[
					'refreshend',
				],
				'refreshment'=>[
					'refreshmant',
				],
				'refrigerant'=>[
					'refrigerent',
				],
				'refrigeration'=>[
					'refridgeration',
				],
				'refrigerator'=>[
					'refridgerator',
				],
				'refulgence'=>[
					'refulgance',
				],
				'refuse to tolerate'=>[
					'refuse to be tolerate',
				],
				'refusing'=>[
					'refuisng',
				],
				'regard'=>[
					'reguard',
				],
				'regardant'=>[
					'regardent',
				],
				'regardless'=>[
					'irregardless',
					'regar:lless', 'reger:lless',
					'regardles',
				],
				'regency'=>[
					'regensy',
				],
				'regeneracy'=>[
					'regenerasy',
				],
				'regenerately'=>[
					'regeneratly',
				],
				'regent'=>[
					'regant',
				],
				'reggae'=>[
					'regae',
				],
				'reggaes'=>[
					'regaes',
				],
				'regiment'=>[
					'regimant',
				],
				'regina'=>[
					'regini',
				],
				'reginae'=>[
					'reginie',
				],
				'reginal'=>[
					'reginil',
				],
				'reginas'=>[
					'reginis',
				],
				'region'=>[
					'region region',
					'region region region',
					'regoin',
					'reigon',
				],
				'regional'=>[
					'regionial',
					'regoinal',
				],
				'regisseur'=>[
					'regisser',
				],
				'register'=>[
					'registrate',
				],
				'registrant'=>[
					'registrent',
				],
				'registrar'=>[
					'registrer',
				],
				'registration'=>[
					'registeration',
				],
				'registry'=>[
					'registery',
				],
				'regnancy'=>[
					'regnansy',
				],
				'regnant'=>[
					'regnent',
				],
				'regreened'=>[
					'regreend',
				],
				'regress'=>[
					'regres',
				],
				'regression'=>[
					'regresion',
				],
				'regressive'=>[
					'regresive',
				],
				'regressively'=>[
					'regressivly',
				],
				'regrettable'=>[
					'regrettible',
				],
				'regrettably'=>[
					'regrettabally',
					'regrettabaly',
					'regrettabely',
					'regrettablly',
				],
				'regulable'=>[
					'regulible',
				],
				'regular'=>[
					'reguler',
				],
				'regularly'=>[
					'reguarly',
					'regularily',
					'regulary',
				],
				'rehabbers'=>[
					'rehabers',
				],
				'rehabbing'=>[
					'rehabing',
				],
				'rehabilitant'=>[
					'rehabilitent',
				],
				'rehammers'=>[
					'rehamners',
				],
				'rehardened'=>[
					'rehardend',
				],
				'rehear'=>[
					'reheer',
				],
				'rehearsal'=>[
					'rehersal',
				],
				'rehearse'=>[
					'reherse',
				],
				'rehemming'=>[
					'rehemning',
				],
				'rehousing'=>[
					'rehouisng',
				],
				'rei'=>[
					'rie',
				],
				'reichsmark'=>[
					'riechsmark',
				],
				'reidentified'=>[
					'reidantified',
				],
				'reidentifies'=>[
					'reidantifies',
				],
				'reidentify'=>[
					'reidantify',
				],
				'reidentifying'=>[
					'reidantifying',
					'riedentifying',
				],
				'reif'=>[
					'rief',
				],
				'reifs'=>[
					'riefs',
				],
				'reify'=>[
					'riefy',
				],
				'reign'=>[
					'riegn',
				],
				'reignite'=>[
					'riegnite',
				],
				'reimbursable'=>[
					'riembursable',
				],
				'reimburse'=>[
					'riemburse',
				],
				'reimbursement'=>[
					'riembursement',
				],
				'reimbursements'=>[
					'riembursements',
				],
				'reimmerse'=>[
					'reimnerse',
				],
				'reimplantation'=>[
					'riemplantation',
				],
				'reimplantations'=>[
					'riemplantations',
				],
				'reimplanting'=>[
					'riemplanting',
				],
				'reimport'=>[
					'riemport',
				],
				'reimportation'=>[
					'riemportation',
				],
				'reimportations'=>[
					'riemportations',
				],
				'reimpose'=>[
					'riempose',
				],
				'reimposition'=>[
					'riemposition',
				],
				'reimpositions'=>[
					'riempositions',
				],
				'reimpression'=>[
					'reimpresion',
					'riempression',
				],
				'reimpressions'=>[
					'riempressions',
				],
				'rein'=>[
					'rien',
				],
				'reincarnate'=>[
					'riencarnate',
				],
				'reincarnated'=>[
					'riencarnated',
				],
				'reincarnates'=>[
					'riencarnates',
				],
				'reincarnating'=>[
					'riencarnating',
				],
				'reincarnation'=>[
					'riencarnation',
				],
				'reincarnations'=>[
					'riencarnations',
				],
				'reincorporate'=>[
					'riencorporate',
				],
				'reincorporated'=>[
					'riencorporated',
				],
				'reincorporates'=>[
					'riencorporates',
				],
				'reincorporating'=>[
					'riencorporating',
				],
				'reincorporation'=>[
					'riencorporation',
				],
				'reindeer'=>[
					'riendeer',
				],
				'reindictment'=>[
					'riendictment',
				],
				'reindictments'=>[
					'riendictments',
				],
				'reindustrialize'=>[
					'riendustrialize',
				],
				'reinfect'=>[
					'rienfect',
				],
				'reinfection'=>[
					'rienfection',
				],
				'reinfections'=>[
					'rienfections',
				],
				'reinfestation'=>[
					'rienfestation',
				],
				'reinfestations'=>[
					'rienfestations',
				],
				'reinflate'=>[
					'rienflate',
				],
				'reinflations'=>[
					'rienflations',
				],
				'reinforce'=>[
					'reforce',
					'rienforce',
				],
				'reinforceable'=>[
					'reinforceible',
					'rienforceable',
				],
				'reinforced'=>[
					'rcinforccd',
				],
				'reinforcement'=>[
					'reenforcement',
					'reinforcemant',
					'rienforcement',
				],
				'reinforcements'=>[
					'rienforcements',
				],
				'reinforcer'=>[
					'rienforcer',
				],
				'reinfusing'=>[
					'reinfuisng',
				],
				'reinhabit'=>[
					'rienhabit',
				],
				'reinhabiting'=>[
					'rienhabiting',
				],
				'reining'=>[
					'reinang',
				],
				'reinitiate'=>[
					'reinatiate',
				],
				'reinitiating'=>[
					'reinatiating',
					'rienitiating',
				],
				'reinjections'=>[
					'rienjections',
				],
				'reink'=>[
					'rienk',
				],
				'reinnervated'=>[
					'riennervated',
				],
				'reinnervates'=>[
					'riennervates',
				],
				'reinnervating'=>[
					'reinervating',
					'riennervating',
				],
				'reinnervation'=>[
					'reinervation',
					'riennervation',
				],
				'reinnervations'=>[
					'reinervations',
					'riennervations',
				],
				'reinoculated'=>[
					'rienoculated',
				],
				'reinoculates'=>[
					'rienoculates',
				],
				'reinoculating'=>[
					'rienoculating',
				],
				'reinoculation'=>[
					'rienoculation',
				],
				'reinoculations'=>[
					'rienoculations',
				],
				'reins'=>[
					'riens',
				],
				'reinsert'=>[
					'riensert',
				],
				'reinsertions'=>[
					'riensertions',
				],
				'reinspecting'=>[
					'rienspecting',
				],
				'reinspection'=>[
					'rienspection',
				],
				'reinspections'=>[
					'rienspections',
				],
				'reinstall'=>[
					'reinstal',
					'rienstall',
				],
				'reinstallation'=>[
					'rienstallation',
				],
				'reinstallations'=>[
					'rienstallations',
				],
				'reinstate'=>[
					'rienstate',
				],
				'reinstatements'=>[
					'rienstatements',
				],
				'reinsurance'=>[
					'reinsurence',
				],
				'reinsure'=>[
					'riensure',
				],
				'reintegrate'=>[
					'rientegrate',
				],
				'reintegrations'=>[
					'rientegrations',
				],
				'reintegrative'=>[
					'rientegrative',
				],
				'reinter'=>[
					'rienter',
				],
				'reinterpret'=>[
					'rienterpret',
				],
				'reinterpreted'=>[
					'rienterpreted',
				],
				'reinterpreting'=>[
					'rienterpreting',
				],
				'reinterprets'=>[
					'rienterprets',
				],
				'reinterviewing'=>[
					'rienterviewing',
				],
				'reinterviews'=>[
					'rienterviews',
				],
				'reintroduce'=>[
					'rientroduce',
				],
				'reintroduced'=>[
					'rientroduced',
				],
				'reintroduces'=>[
					'rientroduces',
				],
				'reintroduction'=>[
					'rientroduction',
				],
				'reintroductions'=>[
					'rientroductions',
				],
				'reinvade'=>[
					'rienvade',
				],
				'reinvent'=>[
					'reinvant',
					'rienvent',
				],
				'reinventions'=>[
					'rienventions',
				],
				'reinvest'=>[
					'rienvest',
				],
				'reinvestigated'=>[
					'rienvestigated',
				],
				'reinvestigates'=>[
					'rienvestigates',
				],
				'reinvestigating'=>[
					'rienvestigating',
				],
				'reinvestigation'=>[
					'rienvestigation',
				],
				'reinvestment'=>[
					'rienvestment',
				],
				'reinvigorate'=>[
					'rienvigorate',
				],
				'reinvigorating'=>[
					'rienvigorating',
				],
				'reinvigoration'=>[
					'rienvigoration',
				],
				'reinvigorations'=>[
					'rienvigorations',
				],
				'reinvigorators'=>[
					'rienvigorators',
				],
				'reis'=>[
					'ries',
				],
				'reissue'=>[
					'reisue',
					'riessue',
				],
				'reiterate'=>[
					'rieterate',
				],
				'reiteratively'=>[
					'reiterativly',
				],
				'reive'=>[
					'rieve',
				],
				'rejigged'=>[
					'rejiged',
				],
				'rejigger'=>[
					'rejiger',
				],
				'rejiggered'=>[
					'rejigered',
				],
				'rejiggering'=>[
					'rejigering',
				],
				'rejuggling'=>[
					'rejugling',
				],
				'rejuvenate'=>[
					'rejuvinate',
				],
				'rejuvenescence'=>[
					'rejuvenecence',
					'rejuvenecsence',
					'rejuvenescance',
					'rejuvenesence',
				],
				'rejuvenescences'=>[
					'rejuvenecences',
					'rejuvenecsences',
					'rejuvenesences',
				],
				'rekindled'=>[
					're-kindled',
				],
				'reknot'=>[
					'rekot',
				],
				'reknots'=>[
					'rekots',
				],
				'reknotted'=>[
					'rekotted',
				],
				'reknotting'=>[
					'rekotting',
				],
				'related'=>[
					'realted',
				],
				'relating'=>[
					'realting',
				],
				'relation'=>[
					'realtion',
				],
				'relative'=>[
					'realtive',
					'reletive',
				],
				'relatively'=>[
					'realtively',
					'relativeally',
					'relativealy',
					'relativeely',
					'relativelly',
					'relativley',
					'relativly',
					'relitavely',
					'relitively',
				],
				'relaxant'=>[
					'relaxent',
				],
				'releasable'=>[
					'releasible',
				],
				'release'=>[
					'realease',
					'relase',
					'relesae',
					'relese',
				],
				'released'=>[
					'realeased',
					'realesed',
					'relaesed',
					'relesaed',
				],
				'releases'=>[
					'realeases',
				],
				'relegate'=>[
					'relagate',
				],
				'relegated'=>[
					'relagated',
				],
				'relegation'=>[
					'relagation',
				],
				'relent'=>[
					'relant',
				],
				'relentless'=>[
					'relantless',
					'relentles',
				],
				'relevance'=>[
					'relevence',
					'revelance',
				],
				'relevancy'=>[
					'relevansy',
					'revelancy',
				],
				'relevant'=>[
					'relavent',
					'relevent',
					'revelant',
				],
				'reliability'=>[
					'reliablity',
				],
				'reliable'=>[
					'reliible',
				],
				'reliance'=>[
					'relience',
				],
				'reliant'=>[
					'relient',
				],
				'relicense'=>[
					'relicence',
				],
				'relief'=>[
					'releif',
					'relif',
				],
				'relieve'=>[
					'releave',
					'releive',
					'relive',
				],
				'relieved'=>[
					'releived',
				],
				'reliever'=>[
					'releiver',
					'reliver',
				],
				'religion'=>[
					'religon',
				],
				'religions'=>[
					'religons',
				],
				'religious'=>[
					'rehgious',
					'religeous',
					'religous',
				],
				'religiously'=>[
					'religiousally',
					'religiousaly',
					'religiousely',
					'religiouslly',
					'religously',
				],
				'reline'=>[
					'relini',
				],
				'relinquished'=>[
					'relinuished',
					'reliquished',
				],
				'reliquaries'=>[
					'reliqauries',
				],
				'reliquary'=>[
					'reliqaury',
					'reliquery',
				],
				'reluctance'=>[
					'reluctence',
				],
				'reluctancy'=>[
					'reluctansy',
				],
				'reluctant'=>[
					'reluctent',
				],
				'relumining'=>[
					'reluminang',
				],
				'remain'=>[
					'reamain',
					'reamin',
					'remian',
				],
				'remained'=>[
					'remaned',
				],
				'remaining'=>[
					'remaing',
					'remainging',
					'remainin',
					'remaning',
				],
				'remanence'=>[
					'remanance',
				],
				'remanned'=>[
					'remaned',
				],
				'remapping'=>[
					'remaping',
				],
				'remarkable'=>[
					'remarkible',
				],
				'remarkably'=>[
					'remarkabally',
					'remarkabaly',
					'remarkabely',
					'remarkablly',
				],
				'remarry'=>[
					'remary',
				],
				'remastered'=>[
					'remaster',
				],
				'rembrance'=>[
					'rememberance',
				],
				'remediable'=>[
					'remediible',
				],
				'remedy'=>[
					'rememdy',
				],
				'remember'=>[
					're member',
					'rember',
					'remeber',
					'remember remember',
					'remember remember remember',
				],
				'rememberability'=>[
					'remberability',
				],
				'rememberable'=>[
					'remberable',
				],
				'remembered'=>[
					'rembered',
					'rememberd',
					'remembred',
				],
				'rememberer'=>[
					'remberer',
				],
				'rememberers'=>[
					'remberers',
				],
				'remembering'=>[
					'rembering',
				],
				'remembers'=>[
					'rembers',
				],
				'remembrance'=>[
					'rembrance',
					'rememberance',
					'remembrence',
				],
				'remembrancer'=>[
					'rembrancer',
				],
				'remembrancers'=>[
					'rembrancers',
				],
				'remembrances'=>[
					'rembrances',
					'rememberances',
				],
				'reminisce'=>[
					'reminasce',
					'reminice',
					'reminicse',
					'reminise',
				],
				'reminisced'=>[
					'reminasced',
				],
				'reminiscence'=>[
					'reminascence',
					'reminicence',
					'reminicsence',
					'reminiscance',
					'reminisence',
				],
				'reminiscences'=>[
					'reminascences',
				],
				'reminiscent'=>[
					'reminascent',
					'reminescent',
					'reminicent',
					'reminicsent',
					'reminiscant',
					'reminisent',
				],
				'reminiscential'=>[
					'reminascential',
					'reminicential',
					'reminicsential',
					'reminisential',
				],
				'reminiscently'=>[
					'reminascently',
					'reminiscentally',
					'reminiscentaly',
					'reminiscentely',
					'reminiscentlly',
				],
				'reminiscer'=>[
					'reminascer',
				],
				'reminisces'=>[
					'reminasces',
				],
				'remiss'=>[
					'remis',
				],
				'remissible'=>[
					'remissable',
				],
				'remission'=>[
					'remision',
				],
				'remittance'=>[
					'remittence',
				],
				'remnant'=>[
					'remnent',
				],
				'remnants'=>[
					'remanants',
				],
				'remodeled'=>[
					'remodelled',
				],
				'remodeling'=>[
					'remodelling',
				],
				'remoistened'=>[
					'remoistend',
				],
				'remonstrance'=>[
					'remonstrence',
				],
				'remonstrant'=>[
					'remonstrent',
				],
				'remonstrantly'=>[
					'remonstrantally',
					'remonstrantaly',
					'remonstrantely',
					'remonstrantlly',
				],
				'remonstratively'=>[
					'remonstrativeally',
					'remonstrativealy',
					'remonstrativeely',
					'remonstrativelly',
					'remonstrativly',
				],
				'remora'=>[
					'remoura',
				],
				'remoras'=>[
					'remouras',
				],
				'remorid'=>[
					'remourid',
				],
				'remorse'=>[
					'remourse',
				],
				'remorseful'=>[
					'remourseful',
				],
				'remorsefully'=>[
					'remoursefully',
				],
				'remorsefulness'=>[
					'remoursefulness',
				],
				'remorseless'=>[
					'reemorseless',
					'remorseles',
					'remourseless',
				],
				'remorselessly'=>[
					'remorselessally',
					'remorselessaly',
					'remorselessely',
					'remorselesslly',
					'remourselessly',
				],
				'remorselessness'=>[
					'remourselessness',
				],
				'remorses'=>[
					'remourses',
				],
				'remotely'=>[
					'remotly',
				],
				'removable'=>[
					'removible',
				],
				'remove'=>[
					'reomove',
				],
				'remuneratively'=>[
					'remunerativly',
				],
				'renaissance'=>[
					'renaisance',
					'renaissence',
					'rennaisance',
				],
				'renascence'=>[
					'renacence',
					'renacsence',
					'renascance',
					'renasence',
				],
				'render'=>[
					'renc/tr',
				],
				'rendezvous'=>[
					'rendevous',
				],
				'rendezvousing'=>[
					'rendezvouisng',
				],
				'rendible'=>[
					'rendable',
				],
				'rendzina'=>[
					'rendzini',
				],
				'rendzinas'=>[
					'rendzinis',
				],
				'renewable'=>[
					'renewible',
				],
				'renewedly'=>[
					'renewedally',
					'renewedaly',
					'renewedely',
					'renewedlly',
				],
				'renitence'=>[
					'renitance',
				],
				'renitency'=>[
					'renitensy',
				],
				'renminbi'=>[
					'reminbi',
					'reninbi',
				],
				'rennase'=>[
					'renase',
				],
				'rennet'=>[
					'renet',
				],
				'rennets'=>[
					'renets',
				],
				'rennin'=>[
					'renin',
				],
				'rennins'=>[
					'renins',
				],
				'renominate'=>[
					'renominite',
				],
				'renominating'=>[
					'renominiting',
				],
				'renomination'=>[
					'renominition',
				],
				'renominations'=>[
					'renominitions',
				],
				'renovascular'=>[
					'renovasculer',
				],
				'renovate'=>[
					'rennovate',
				],
				'renovation'=>[
					'rennovation',
				],
				'renown'=>[
					'reknown',
				],
				'renowned'=>[
					'reknowned',
					'renound',
					'renouned',
					'renowed',
				],
				'rent'=>[
					'rant',
				],
				'rental'=>[
					'rantal',
				],
				'rente'=>[
					'rante',
				],
				'renter'=>[
					'ranter',
				],
				'rentier'=>[
					'rantier',
				],
				'rents'=>[
					'rants',
				],
				'rené'=>[
					'rene',
				],
				'rené duvillier'=>[
					'rene duvillier',
					'rene duvilliers',
					'rené duvilliers',
				],
				'reoccupation'=>[
					'reocupation',
				],
				'reoccupations'=>[
					'reocupations',
				],
				'reoccupy'=>[
					'reocupy',
				],
				'reoccupying'=>[
					'reocupying',
				],
				'reoccur'=>[
					'reocur',
				],
				'reoccurrence'=>[
					'reoccurrance',
					'reocurrence',
				],
				'reoccurrences'=>[
					'reocurrences',
				],
				'reoccurring'=>[
					'reocurring',
				],
				'reoccurs'=>[
					'reocurs',
				],
				'reopened'=>[
					'reopend',
				],
				'reopposed'=>[
					'reoposed',
				],
				'reopposes'=>[
					'reoposes',
				],
				'reopposing'=>[
					'reoposing',
				],
				'reorient'=>[
					'reoreint',
					'reoriant',
					'reorint',
				],
				'repaid'=>[
					'repayed',
				],
				'reparable'=>[
					'reparible',
					'reperable',
				],
				'reparation'=>[
					'reperation',
				],
				'reparations'=>[
					'reperations',
				],
				'reparative'=>[
					'reperative',
				],
				'reparks'=>[
					'reperks',
				],
				'repartee'=>[
					'repertee',
				],
				'repartition'=>[
					'repertition',
				],
				'repartitions'=>[
					'repertitions',
				],
				'repass'=>[
					'repas',
				],
				'repeal'=>[
					'repel',
				],
				'repeat'=>[
					'repeat repeat',
					'repeat repeat repeat',
					'repet',
				],
				'repeatabilities'=>[
					'repetabilities',
				],
				'repeated'=>[
					'repeted',
				],
				'repeatedly'=>[
					'repeatedally',
					'repeatedaly',
					'repeatedely',
					'repeatedlly',
					'repeatly',
					'repetedly',
				],
				'repel'=>[
					'repell',
				],
				'repelled'=>[
					'repeled',
				],
				'repellency'=>[
					'repellensy',
				],
				'repellent'=>[
					'repelent',
				],
				'repent'=>[
					'repant',
				],
				'repentance'=>[
					'repantance',
					'repentence',
				],
				'repentant'=>[
					'repentent',
				],
				'repercussion'=>[
					'repercusion',
				],
				'repertoire'=>[
					'repertoir',
					'repetoire',
					'reåertoire',
				],
				'repetition'=>[
					'repetion',
					'repitition',
				],
				'repetitious'=>[
					'repetitous',
				],
				'repetitiously'=>[
					'repetitiousally',
					'repetitiousaly',
					'repetitiousely',
					'repetitiouslly',
					'repetitously',
				],
				'repetitive'=>[
					'repetetive',
					'repetive',
				],
				'repetitively'=>[
					'repetitivly',
				],
				'repine'=>[
					'repini',
				],
				'replacement'=>[
					'replacemant',
				],
				'replacing'=>[
					'replaceing',
				],
				'replant'=>[
					'replent',
				],
				'repledge'=>[
					'replege',
				],
				'repledged'=>[
					'repleged',
				],
				'repledges'=>[
					'repleges',
				],
				'replenishable'=>[
					'replenishible',
				],
				'repletely'=>[
					'repletly',
				],
				'reply'=>[
					'repally',
					'repaly',
					'replly',
					'reply reply',
					'reply reply reply',
				],
				'reportedly'=>[
					'reportably',
					'reportedally',
					'reportedaly',
					'reportedely',
					'reportedlly',
				],
				'reporter'=>[
					'reportor',
				],
				'repossession'=>[
					'repossetion',
				],
				'repped'=>[
					'reped',
				],
				'repping'=>[
					'reping',
				],
				'repps'=>[
					'reps',
				],
				'reprehensible'=>[
					'reprehensable',
				],
				'represent'=>[
					'represant',
					'represent represent',
					'represent represent represent',
					'representate',
				],
				'representable'=>[
					'representible',
				],
				'representation'=>[
					'represantation',
				],
				'representative'=>[
					'represantative',
					'represenative',
					'representitive',
					'representive',
				],
				'representatives'=>[
					'representives',
				],
				'represented'=>[
					'repersented',
				],
				'representing'=>[
					'repersenting',
				],
				'represents'=>[
					'repersents',
					'represesnt',
				],
				'repress'=>[
					'repres',
				],
				'repressible'=>[
					'repressable',
				],
				'repression'=>[
					'represion',
				],
				'repressive'=>[
					'represive',
				],
				'reprieve'=>[
					'repreive',
					'reprive',
				],
				'reprise'=>[
					'reprize',
				],
				'repristinate'=>[
					'repristinite',
				],
				'repristinated'=>[
					'repristinited',
				],
				'repristinates'=>[
					'repristinites',
				],
				'repristinating'=>[
					'repristiniting',
				],
				'repristination'=>[
					'repristinition',
				],
				'repristinations'=>[
					'repristinitions',
				],
				'reprobance'=>[
					'reprobence',
				],
				'reproducible'=>[
					'reproducable',
				],
				'reproducibly'=>[
					'reproducibally',
					'reproducibaly',
					'reproducibely',
					'reproduciblly',
				],
				'reproductively'=>[
					'reproductivly',
				],
				'reprogrammable'=>[
					'reprogrammible',
					'reprogramnable',
				],
				'reprogramming'=>[
					'reprogramning',
				],
				'reptilian'=>[
					'reptilan',
				],
				'republic'=>[
					'repubic',
					'repulic',
				],
				'republican'=>[
					'repubican',
				],
				'repudiate'=>[
					'repudate',
				],
				'repudiating'=>[
					'repudating',
				],
				'repugnance'=>[
					'repugnence',
				],
				'repugnancy'=>[
					'repugnansy',
				],
				'repugnant'=>[
					'repugnent',
				],
				'repulsively'=>[
					'repulsivly',
				],
				'repunctuations'=>[
					'repunctautions',
				],
				'reputable'=>[
					'reputible',
				],
				'requalifies'=>[
					'reqaulifies',
				],
				'requiem'=>[
					'requeim',
					'requim',
				],
				'requiescat'=>[
					'requeiscat',
					'requiscat',
				],
				'require'=>[
					'recquire',
					'reqire',
					'require require',
					'require require require',
				],
				'requirement'=>[
					'requiremant',
				],
				'requires'=>[
					'reqiures',
				],
				'requisition'=>[
					'requisiton',
				],
				'requisitioned'=>[
					'requisitoned',
				],
				'rescale'=>[
					'recale',
					'recsale',
					'resale',
				],
				'reschedule'=>[
					'rechedule',
					'recshedule',
					'reshedule',
				],
				'rescind'=>[
					'recind',
					'recsind',
					'resind',
				],
				'rescission'=>[
					'recission',
					'recsission',
					'rescision',
					'resission',
				],
				'rescore'=>[
					'recore',
					'recsore',
					'resore',
				],
				'rescreened'=>[
					'rescreend',
				],
				'rescript'=>[
					'recript',
					'recsript',
					'resript',
				],
				'rescuable'=>[
					'rescuible',
				],
				'rescue'=>[
					'recsue',
					'recue',
					'rescure',
					'rescuse',
					'resue',
				],
				'research'=>[
					'reasearch',
					'reseach',
					'reserach',
					'reserch',
				],
				'resell'=>[
					'resel',
				],
				'resemblance'=>[
					'resemblence',
					'ressemblance',
				],
				'resemble'=>[
					'ressemble',
				],
				'resembled'=>[
					'ressembled',
				],
				'resembling'=>[
					'ressembling',
				],
				'resent'=>[
					'resant',
				],
				'resentence'=>[
					'resentance',
				],
				'resentment'=>[
					'resenment',
					'resentmant',
				],
				'reservoir'=>[
					'resevoir',
				],
				'reservoirs'=>[
					'resservoirs',
				],
				'resharpened'=>[
					'resharpend',
				],
				'reshipped'=>[
					'reshiped',
				],
				'reshipper'=>[
					'reshiper',
				],
				'reshippers'=>[
					'reshipers',
				],
				'reshipping'=>[
					'reshiping',
				],
				'reside'=>[
					'recide',
				],
				'residence'=>[
					'residance',
				],
				'residency'=>[
					'residensy',
				],
				'resident'=>[
					'residant',
				],
				'residential'=>[
					'residantial',
				],
				'residentially'=>[
					'residantially',
				],
				'residents'=>[
					'residants',
				],
				'residua'=>[
					'residau',
				],
				'residual'=>[
					'residaul',
				],
				'residuary'=>[
					'residaury',
					'residuery',
				],
				'resignedly'=>[
					'resignedally',
					'resignedaly',
					'resignedely',
					'resignedlly',
				],
				'resilience'=>[
					'resileince',
					'resiliance',
					'resilince',
				],
				'resiliency'=>[
					'resileincy',
					'resiliensy',
					'resilincy',
				],
				'resilient'=>[
					'resileint',
					'resiliant',
					'resilint',
				],
				'resinate'=>[
					'resinite',
				],
				'resinated'=>[
					'resinited',
				],
				'resinating'=>[
					'resiniting',
				],
				'resistance'=>[
					'resislance',
					'resistence',
				],
				'resistant'=>[
					'resistent',
				],
				'resistible'=>[
					'resistable',
				],
				'resisting'=>[
					'resisiting',
				],
				'resistively'=>[
					'resistivly',
				],
				'resituating'=>[
					'resitauting',
				],
				'resoftened'=>[
					'resoftend',
				],
				'resolutely'=>[
					'resolutly',
				],
				'resonance'=>[
					'resonence',
				],
				'resonant'=>[
					'resonent',
				],
				'resource'=>[
					'resourse',
				],
				'resources'=>[
					'resrouces',
				],
				'respect'=>[
					'repect',
				],
				'respectable'=>[
					'respectible',
				],
				'respected'=>[
					'repected',
				],
				'respecting'=>[
					'repecting',
				],
				'respectively'=>[
					'respectiveally',
					'respectivealy',
					'respectiveely',
					'respectivelly',
					'respectivley',
					'respectivly',
				],
				'respirable'=>[
					'respirible',
				],
				'respiritualize'=>[
					'respiritaulize',
				],
				'respiritualized'=>[
					'respiritaulized',
				],
				'respiritualizes'=>[
					'respiritaulizes',
				],
				'resplendence'=>[
					'resplendance',
				],
				'resplendency'=>[
					'resplendensy',
				],
				'resplendent'=>[
					'resplendant',
				],
				'resplendently'=>[
					'resplendantly',
					'resplendentally',
					'resplendentaly',
					'resplendentely',
					'resplendentlly',
				],
				'responded'=>[
					'responsed',
				],
				'respondent'=>[
					'respondant',
				],
				'respondents'=>[
					'respondants',
				],
				'response'=>[
					'reponse',
					'repsonse',
					'responce',
				],
				'responses'=>[
					'reponses',
				],
				'responsibilities'=>[
					'responsibilites',
				],
				'responsibility'=>[
					'reponsibility',
					'responibility',
					'responsability',
					'responsibilty',
					'resposibility',
				],
				'responsible'=>[
					'reponsible',
					'responsable',
					'resposible',
				],
				'responsive'=>[
					'reponsive',
				],
				'responsively'=>[
					'responsivly',
				],
				'ressentiment'=>[
					'resentiment',
					'ressentimant',
				],
				'rest'=>[
					'rest rest',
					'rest rest rest',
				],
				'restaurant'=>[
					'restarant',
					'restaraunt',
					'restauraunt',
					'restaurent',
					'resteraunt',
					'restorant',
					'restraunt',
					'restuarant',
					'resturant',
				],
				'restauranteur'=>[
					'restauranter',
				],
				'restaurants'=>[
					'restarants',
					'restaraunts',
					'resteraunts',
					'resturants',
				],
				'restaurateur'=>[
					'restaurater',
				],
				'restless'=>[
					'restles',
				],
				'restoration'=>[
					'resoration',
					'restauration',
				],
				'restore'=>[
					'resore',
				],
				'restrainable'=>[
					'restrainible',
				],
				'restrainedly'=>[
					'restrainedally',
					'restrainedaly',
					'restrainedely',
					'restrainedlly',
				],
				'restrengthened'=>[
					'restrengthend',
				],
				'restrict'=>[
					'resrtict',
				],
				'restrictedly'=>[
					'restrictedally',
					'restrictedaly',
					'restrictedely',
					'restrictedlly',
				],
				'restriction'=>[
					'i;estriction',
					'resrtiction',
				],
				'restrictions'=>[
					'resrtictions',
				],
				'restrictively'=>[
					'restrictivly',
				],
				'restricts'=>[
					'resrticts',
				],
				'result'=>[
					'result result',
					'result result result',
				],
				'resultant'=>[
					'resultent',
				],
				'resulting'=>[
					'resuIting',
					'reulting',
				],
				'results'=>[
					'resuIts',
					'reults',
				],
				'resume'=>[
					'reassume',
				],
				'resumes'=>[
					'reassumes',
				],
				'resummons'=>[
					'resumnons',
				],
				'resupinate'=>[
					'resupinite',
				],
				'resupplied'=>[
					'resuplied',
				],
				'resupplies'=>[
					'resuplies',
				],
				'resupply'=>[
					'resuply',
					'resuppally',
					'resuppaly',
					'resuppely',
					'resupplly',
				],
				'resurgence'=>[
					'resurgance',
				],
				'resurrect'=>[
					'resurect',
				],
				'resurrecting'=>[
					'resurecting',
				],
				'resurrection'=>[
					'ressurection',
					'resurection',
				],
				'resurrectional'=>[
					'resurectional',
				],
				'resurrectionist'=>[
					'resurectionist',
				],
				'resuscitate'=>[
					'resucitate',
					'resucsitate',
					'resusitate',
				],
				'resuscitations'=>[
					'resucitations',
					'resucsitations',
					'resusitations',
				],
				'resuscitator'=>[
					'resucitator',
					'resucsitator',
					'resusitator',
				],
				'retable'=>[
					'retible',
				],
				'retainer'=>[
					'retainir',
				],
				'retaken'=>[
					'ertaken',
				],
				'retaliation'=>[
					'retailation',
				],
				'retardant'=>[
					'retardent',
				],
				'retardants'=>[
					'retardents',
				],
				'retear'=>[
					'reteer',
				],
				'retell'=>[
					'retel',
				],
				'retelling'=>[
					'reteling',
				],
				'retention'=>[
					'retantion',
				],
				'retiary'=>[
					'retiery',
				],
				'reticence'=>[
					'reticance',
				],
				'reticency'=>[
					'reticensy',
				],
				'reticent'=>[
					'reticant',
				],
				'reticular'=>[
					'reticuler',
				],
				'retie'=>[
					'retei',
					'reti',
				],
				'retightened'=>[
					'retightend',
				],
				'retina'=>[
					'retini',
				],
				'retinacula'=>[
					'retinicula',
				],
				'retinaculum'=>[
					'retiniculum',
				],
				'retinae'=>[
					'retinie',
				],
				'retinal'=>[
					'retinil',
				],
				'retinals'=>[
					'retinils',
				],
				'retinas'=>[
					'retinis',
				],
				'retinitis'=>[
					'retinatis',
				],
				'retinular'=>[
					'retinuler',
				],
				'retired'=>[
					'reired',
				],
				'retirement'=>[
					'retiremant',
				],
				'retransferring'=>[
					'retransfering',
				],
				'retreat'=>[
					'ertreat',
					'retret',
				],
				'retreated'=>[
					'retreatde',
				],
				'retrenchment'=>[
					'retrenchmant',
				],
				'retributively'=>[
					'retributivly',
				],
				'retried'=>[
					'retreid',
					'retrid',
				],
				'retries'=>[
					'retreis',
					'retris',
				],
				'retrieval'=>[
					'retreival',
					'retrival',
				],
				'retrieve'=>[
					'retreive',
					'retrive',
				],
				'retrieved'=>[
					'retireved',
					'retreived',
				],
				'retriever'=>[
					'retreiver',
					'retriver',
				],
				'retrimmed'=>[
					'retrimned',
				],
				'retroactively'=>[
					'retroactivly',
				],
				'retrogradely'=>[
					'retrogradly',
				],
				'retrogression'=>[
					'retrogresion',
				],
				'retrogressively'=>[
					'retrogressiveally',
					'retrogressivealy',
					'retrogressiveely',
					'retrogressivelly',
					'retrogressivly',
				],
				'retroperitoneal'=>[
					'retroperitonel',
				],
				'retrospectively'=>[
					'retrospectiveally',
					'retrospectivealy',
					'retrospectiveely',
					'retrospectivelly',
					'retrospectivly',
				],
				'retsina'=>[
					'retsini',
				],
				'retsinas'=>[
					'retsinis',
				],
				'return'=>[
					'erturn',
					'retrun',
				],
				'returnable'=>[
					'returnible',
				],
				'returned'=>[
					'erturned',
					'retruned',
					'retured',
					'rrturned',
				],
				'returning'=>[
					'retruning',
					'returing',
				],
				'reunite'=>[
					'reunit',
				],
				'revaccinate'=>[
					'revaccinite',
					'revacinate',
				],
				'revaccinated'=>[
					'revaccinited',
					'revacinated',
				],
				'revaccinates'=>[
					'revaccinites',
					'revacinates',
				],
				'revaccinating'=>[
					'revacciniting',
					'revacinating',
				],
				'revaccination'=>[
					'revaccinition',
					'revacination',
				],
				'revaccinations'=>[
					'revaccinitions',
					'revacinations',
				],
				'revaluate'=>[
					'revalaute',
				],
				'revaluating'=>[
					'revalauting',
				],
				'revaluation'=>[
					'revalaution',
				],
				'reveal'=>[
					'revel',
				],
				'revealing'=>[
					'reveling',
				],
				'reveille'=>[
					'revielle',
				],
				'reveling'=>[
					'revelling',
				],
				'revenue'=>[
					'revnue',
				],
				'revenues'=>[
					'revnues',
				],
				'reverberant'=>[
					'reverberent',
				],
				'reverberantly'=>[
					'reverberantally',
					'reverberantaly',
					'reverberantely',
					'reverberantlly',
				],
				'reverberation'=>[
					'reveberation',
					'reverbration',
				],
				'reverence'=>[
					'reverance',
				],
				'reverend'=>[
					'reverand',
				],
				'reverent'=>[
					'reverant',
				],
				'reverential'=>[
					'reverantial',
				],
				'reverie'=>[
					'reverei',
					'reveri',
				],
				'reverse'=>[
					'reverese',
				],
				'reversely'=>[
					'reversly',
				],
				'reversible'=>[
					'reversable',
				],
				'reversionary'=>[
					'reversionery',
				],
				'revertible'=>[
					'revertable',
				],
				'revictualed'=>[
					'revictauled',
				],
				'review'=>[
					'reveiw',
					'reviw',
				],
				'reviewed'=>[
					'reveiwed',
				],
				'reviewer'=>[
					'reveiwer',
					'reviwer',
				],
				'reviewers'=>[
					'reveiwers',
				],
				'revisionary'=>[
					'revisionery',
				],
				'revisualization'=>[
					'revisaulization',
				],
				'reviviscence'=>[
					'reviviscance',
				],
				'revocable'=>[
					'revocible',
				],
				'revolution'=>[
					'recolution',
					'revlution',
					'revolu- tion',
					'revolu-tion',
					'revoluiton',
					'revolutoin',
					'revoluton',
					'revoulution',
				],
				'revolutionary'=>[
					'revoltitionary',
					'revolu- tionary',
					'revolu-tionary',
					'revoluitonary',
					'revolutionarv',
					'revolutionery',
					'revolutioniary',
					'revolutiotary',
					'revolutiotiary',
					'revolutoinary',
					'revoulution- ary',
					'revoulution-ary',
					'revoulutionary',
				],
				'revolutionize'=>[
					'revolustionise',
				],
				'rewakened'=>[
					'rewakend',
				],
				'rewear'=>[
					'reweer',
				],
				'reweigh'=>[
					'rewiegh',
				],
				'rewidened'=>[
					'rewidend',
				],
				'rewrapped'=>[
					'rewraped',
				],
				'rewrapping'=>[
					'rewraping',
				],
				'rhabdomancy'=>[
					'rhabdomansy',
				],
				'rhea'=>[
					'rhe',
				],
				'rhetoric'=>[
					'rethoric',
				],
				'rhetorician'=>[
					'rhetorican',
				],
				'rhinal'=>[
					'rhinil',
				],
				'rhinencephalon'=>[
					'rhinincephalon',
				],
				'rhinestone'=>[
					'rhinistone',
				],
				'rhinitis'=>[
					'rhinatis',
				],
				'rhinoscopy'=>[
					'rhinocopy',
					'rhinocsopy',
					'rhinosopy',
				],
				'rhode island'=>[
					'rode island',
				],
				'rhodope mountains'=>[
					'rodopi mountain',
				],
				'rhythm'=>[
					'rhythem',
					'rhythym',
					'rhytm',
					'rythem',
					'rythm',
					'rythum',
					'rythym',
				],
				'riant'=>[
					'rient',
				],
				'ribband'=>[
					'riband',
				],
				'ribber'=>[
					'riber',
				],
				'ribbing'=>[
					'ribing',
				],
				'ribbon'=>[
					'ribon',
				],
				'ribbonfish'=>[
					'ribonfish',
				],
				'ribbonfishes'=>[
					'ribonfishes',
				],
				'ribboning'=>[
					'riboning',
				],
				'ribbonlike'=>[
					'ribonlike',
				],
				'ribby'=>[
					'riby',
				],
				'ribonuclease'=>[
					'ribonuclese',
				],
				'ricercar'=>[
					'ricercer',
				],
				'rich'=>[
					'nch',
					'rich rich',
					'rich rich rich',
				],
				'richened'=>[
					'richend',
				],
				'riches'=>[
					'richs',
				],
				'ricochet'=>[
					'richochet',
				],
				'ridable'=>[
					'ridible',
				],
				'riddance'=>[
					'riddence',
				],
				'ridden'=>[
					'riden',
				],
				'ride'=>[
					'ride ride',
					'ride ride ride',
				],
				'rident'=>[
					'ridant',
				],
				'ridgeline'=>[
					'ridgelini',
				],
				'ridiculous'=>[
					'rediculous',
				],
				'riel'=>[
					'reil',
				],
				'rifely'=>[
					'rifly',
				],
				'rigged'=>[
					'riged',
				],
				'rigger'=>[
					'riger',
				],
				'riggers'=>[
					'rigers',
				],
				'rigging'=>[
					'riging',
				],
				'right'=>[
					'right right',
					'right right right',
					'rigth',
				],
				'right and'=>[
					'righ tand',
				],
				'righteous'=>[
					'rightous',
				],
				'rightly'=>[
					'rightally',
					'rightaly',
					'rightely',
					'rightlly',
				],
				'rightness'=>[
					'rightnes',
				],
				'rights'=>[
					'irghts',
				],
				'rigidly'=>[
					'rigidally',
					'rigidaly',
					'rigidely',
					'rigidlly',
				],
				'rigor'=>[
					'rigeur',
				],
				'rigorous'=>[
					'rigourous',
				],
				'rill'=>[
					'ril',
				],
				'rimmed'=>[
					'rimned',
				],
				'rimmer'=>[
					'rimner',
				],
				'rimmers'=>[
					'rimners',
				],
				'rimming'=>[
					'rimning',
				],
				'rimosely'=>[
					'rimosly',
				],
				'ring'=>[
					'ring ring',
					'ring ring ring',
				],
				'ringgit'=>[
					'ringit',
				],
				'ringleader'=>[
					'ringleder',
				],
				'rinse'=>[
					'rince',
				],
				'rinsible'=>[
					'rinsable',
				],
				'rio de janeiro'=>[
					'rio de janerio',
					'rio de janero',
					'rio de janiero',
				],
				'riparian'=>[
					'riparan',
					'riperian',
				],
				'ripely'=>[
					'riply',
				],
				'ripened'=>[
					'ripend',
				],
				'ripped'=>[
					'riped',
				],
				'ripper'=>[
					'riper',
				],
				'rippers'=>[
					'ripers',
				],
				'ripping'=>[
					'riping',
				],
				'rippingly'=>[
					'ripingly',
				],
				'ripple'=>[
					'riple',
				],
				'rippled'=>[
					'ripled',
				],
				'rippler'=>[
					'ripler',
				],
				'ripples'=>[
					'riples',
				],
				'ripplet'=>[
					'riplet',
				],
				'rippliest'=>[
					'ripliest',
				],
				'ripply'=>[
					'riply',
					'rippally',
					'rippaly',
					'rippely',
					'ripplly',
				],
				'riprapped'=>[
					'ripraped',
				],
				'riprapping'=>[
					'ripraping',
				],
				'ripsnorter'=>[
					'ripsnourter',
				],
				'ripsnorters'=>[
					'ripsnourters',
				],
				'ripsnorting'=>[
					'ripsnourting',
				],
				'rise'=>[
					'rise rise',
					'rise rise rise',
				],
				'risible'=>[
					'risable',
				],
				'risperdal'=>[
					'risperidal',
				],
				'risqué'=>[
					'risque',
				],
				'ritual'=>[
					'ritaul',
				],
				'ritualism'=>[
					'ritaulism',
				],
				'ritualist'=>[
					'ritaulist',
				],
				'ritualistic'=>[
					'ritaulistic',
				],
				'ritualistically'=>[
					'ritaulistically',
				],
				'ritualizations'=>[
					'ritaulizations',
				],
				'ritualize'=>[
					'ritaulize',
				],
				'ritualizing'=>[
					'ritaulizing',
				],
				'rituals'=>[
					'ritauls',
				],
				'rivalry'=>[
					'rivarly',
				],
				'river'=>[
					'river river',
					'river river river',
				],
				'riverhead'=>[
					'riverhed',
				],
				'riverine'=>[
					'riverini',
				],
				'riverside'=>[
					'rivrside',
				],
				'riviere'=>[
					'riveire',
					'rivire',
				],
				'road'=>[
					'road road',
					'road road road',
				],
				'roadie'=>[
					'roadei',
					'roadi',
				],
				'roadrunner'=>[
					'roadruner',
				],
				'roadworthiness'=>[
					'roadworthiniss',
				],
				'roan inish'=>[
					'roan irish',
				],
				'roar'=>[
					'roer',
				],
				'robbed'=>[
					'rob bed',
				],
				'robberies'=>[
					'roberies',
				],
				'robbery'=>[
					'robery',
				],
				'robert cinnamond'=>[
					'robert cinnamon',
				],
				'robustious'=>[
					'robustous',
				],
				'robustiously'=>[
					'robustously',
				],
				'robustly'=>[
					'robustally',
					'robustaly',
					'robustely',
					'robustlly',
				],
				'rock'=>[
					'rock rock',
					'rock rock rock',
				],
				'rockabilly'=>[
					'rockabilally',
					'rockabilaly',
					'rockabilely',
					'rockabillly',
					'rockabily',
				],
				'rockefeller'=>[
					'rockerfeller',
				],
				'rockhopper'=>[
					'rockhoper',
				],
				'rodent'=>[
					'rodant',
				],
				'rodenticide'=>[
					'rodanticide',
				],
				'rodenticides'=>[
					'rodanticides',
				],
				'rodents'=>[
					'rodants',
				],
				'rodríguez'=>[
					'rodriguez',
				],
				'roentgenogram'=>[
					'roantgenogram',
				],
				'roentgenography'=>[
					'roantgenography',
				],
				'roentgenology'=>[
					'roantgenology',
				],
				'roily'=>[
					'roially',
					'roialy',
					'roilly',
				],
				'roll'=>[
					'rol',
					'roll roll',
					'roll roll roll',
				],
				'rollback'=>[
					'rolback',
				],
				'roller'=>[
					'roler',
				],
				'rollicking'=>[
					'rolicking',
				],
				'rollout'=>[
					'rolout',
				],
				'rollover'=>[
					'rolover',
				],
				'romaine'=>[
					'romaini',
				],
				'romance'=>[
					'romence',
				],
				'romanian horă'=>[
					'romanian hora',
				],
				'romanian-occupied'=>[
					'romanian occupied',
				],
				'romantic'=>[
					'romatic',
					'romentic',
				],
				'romantically'=>[
					'romatically',
				],
				'romanticism'=>[
					'romenticism',
				],
				'romanticize'=>[
					'romenticize',
				],
				'ronnel'=>[
					'ronel',
				],
				'ronnels'=>[
					'ronels',
				],
				'roofline'=>[
					'rooflini',
				],
				'rookie'=>[
					'rookei',
					'rooki',
				],
				'room'=>[
					'room room',
					'room room room',
					'rooom',
				],
				'roommate'=>[
					'roomate',
					'roomnate',
				],
				'roommates'=>[
					'roomnates',
				],
				'root'=>[
					'root root',
					'root root root',
				],
				'ropable'=>[
					'ropible',
				],
				'rope'=>[
					'rope rope',
					'rope rope rope',
				],
				'rorqual'=>[
					'rorqaul',
				],
				'rosarian'=>[
					'rosaran',
				],
				'rosary'=>[
					'rosery',
				],
				'roscoe'=>[
					'rocoe',
					'rocsoe',
					'rosoe',
				],
				'rose'=>[
					'rose rose',
					'rose rose rose',
				],
				'roseately'=>[
					'roseatly',
				],
				'roselle'=>[
					'rosele',
				],
				'rosemary'=>[
					'rosemery',
				],
				'roseolar'=>[
					'roseoler',
				],
				'rostellar'=>[
					'rosteller',
				],
				'rosy'=>[
					'rocy',
				],
				'rotary'=>[
					'rotery',
				],
				'rotatively'=>[
					'rotativly',
				],
				'rotisserie'=>[
					'rotiserie',
					'rotisserei',
					'rotisseri',
				],
				'rottweiler'=>[
					'rottwieler',
				],
				'rough'=>[
					'roug',
				],
				'roughened'=>[
					'roughend',
				],
				'roughhousing'=>[
					'roughhouisng',
				],
				'roughly'=>[
					'rougly',
				],
				'round'=>[
					'round round',
					'round round round',
				],
				'roundheadedness'=>[
					'roundhededness',
				],
				'roundly'=>[
					'roundally',
					'roundaly',
					'roundely',
					'roundlly',
				],
				'roundtable'=>[
					'roundtible',
				],
				'rousingly'=>[
					'rouisngly',
				],
				'routine'=>[
					'routini',
				],
				'routinely'=>[
					'routinly',
				],
				'routinization'=>[
					'routinazation',
				],
				'routinizations'=>[
					'routinazations',
				],
				'routinize'=>[
					'routinaze',
				],
				'row'=>[
					'row row',
					'row row row',
				],
				'rowable'=>[
					'rowible',
				],
				'royal & sun alliance'=>[
					'royal & sunalliance',
				],
				'royalties'=>[
					'royalites',
					'royalities',
				],
				'royalty'=>[
					'royality',
				],
				'rté'=>[
					'rte',
				],
				'ruana'=>[
					'rauna',
				],
				'ruanas'=>[
					'raunas',
				],
				'rub'=>[
					'rub rub',
					'rub rub rub',
				],
				'rubalcaba'=>[
					'rubalcava',
				],
				'rubber'=>[
					'ruber',
				],
				'rubberiest'=>[
					'ruberiest',
				],
				'rubberize'=>[
					'ruberize',
				],
				'rubberized'=>[
					'ruberized',
				],
				'rubberizes'=>[
					'ruberizes',
				],
				'rubberizing'=>[
					'ruberizing',
				],
				'rubberlike'=>[
					'ruberlike',
				],
				'rubberneck'=>[
					'ruberneck',
				],
				'rubbernecked'=>[
					'rubernecked',
				],
				'rubbernecker'=>[
					'rubernecker',
				],
				'rubberneckers'=>[
					'ruberneckers',
				],
				'rubbernecking'=>[
					'rubernecking',
				],
				'rubbernecks'=>[
					'rubernecks',
				],
				'rubbery'=>[
					'rubery',
				],
				'rubbing'=>[
					'rubing',
				],
				'rubbish'=>[
					'rubish',
				],
				'rubbishy'=>[
					'rubishy',
				],
				'rubble'=>[
					'ruble',
				],
				'rubbled'=>[
					'rubled',
				],
				'rubby'=>[
					'ruby',
				],
				'rubefacient'=>[
					'rubefaceint',
					'rubefacint',
				],
				'rubella'=>[
					'rubela',
				],
				'rubeolar'=>[
					'rubeoler',
				],
				'rubious'=>[
					'rubous',
				],
				'rubrician'=>[
					'rubrican',
				],
				'rubén gonzález'=>[
					'ruben gonzalez',
					'ruben gonzález',
				],
				'ructious'=>[
					'ructous',
				],
				'rudely'=>[
					'rudly',
				],
				'rudimentary'=>[
					'rudimantary',
					'rudimentery',
				],
				'ruffian'=>[
					'ruffan',
				],
				'ruffianly'=>[
					'ruffianally',
					'ruffianaly',
					'ruffianely',
					'ruffianlly',
				],
				'rugged'=>[
					'ruged',
				],
				'ruggedization'=>[
					'rugedization',
				],
				'ruggedizations'=>[
					'rugedizations',
				],
				'ruggedized'=>[
					'rugedized',
				],
				'ruggedizes'=>[
					'rugedizes',
				],
				'ruggedizing'=>[
					'rugedizing',
				],
				'ruggedness'=>[
					'rugedness',
				],
				'ruggednesses'=>[
					'rugednesses',
				],
				'rugger'=>[
					'ruger',
				],
				'ruggers'=>[
					'rugers',
				],
				'rugging'=>[
					'ruging',
				],
				'rugosely'=>[
					'rugosly',
				],
				'ruinable'=>[
					'ruinible',
				],
				'ruinate'=>[
					'ruinite',
				],
				'ruinated'=>[
					'ruinited',
				],
				'ruinates'=>[
					'ruinites',
				],
				'ruination'=>[
					'ruinition',
				],
				'ruinations'=>[
					'ruinitions',
				],
				'ruining'=>[
					'ruinang',
				],
				'ruinous'=>[
					'runious',
				],
				'rulable'=>[
					'rulible',
				],
				'rule'=>[
					'rule rule',
					'rule rule rule',
					'rulle',
				],
				'ruler'=>[
					'ruller',
				],
				'rumbustious'=>[
					'rumbustous',
				],
				'rumbustiously'=>[
					'rumbustiousally',
					'rumbustiousaly',
					'rumbustiousely',
					'rumbustiouslly',
					'rumbustously',
				],
				'rumina'=>[
					'rumini',
				],
				'ruminal'=>[
					'ruminil',
				],
				'ruminant'=>[
					'ruminent',
					'ruminint',
				],
				'ruminantly'=>[
					'ruminintly',
				],
				'ruminate'=>[
					'ruminite',
				],
				'ruminating'=>[
					'ruminiting',
				],
				'rumination'=>[
					'ruminition',
				],
				'ruminative'=>[
					'ruminitive',
				],
				'ruminatively'=>[
					'ruminativly',
					'ruminitively',
				],
				'ruminators'=>[
					'ruminitors',
				],
				'rummage'=>[
					'rumnage',
				],
				'rummagers'=>[
					'rumnagers',
				],
				'rummaging'=>[
					'rumnaging',
				],
				'rummer'=>[
					'rumner',
				],
				'rummers'=>[
					'rumners',
				],
				'rummest'=>[
					'rumnest',
				],
				'rummier'=>[
					'rumnier',
				],
				'rummies'=>[
					'rumnies',
				],
				'rummy'=>[
					'rumny',
				],
				'rumor'=>[
					'rummor',
				],
				'rumored'=>[
					'rumoured',
				],
				'rumoring'=>[
					'rumouring',
				],
				'rumormonger'=>[
					'rumourmonger',
				],
				'rumormongering'=>[
					'rumourmongering',
				],
				'rumormongerings'=>[
					'rumourmongerings',
				],
				'rumormongers'=>[
					'rumourmongers',
				],
				'rumors'=>[
					'rumours',
				],
				'rumrunner'=>[
					'rumruner',
				],
				'run'=>[
					'run run',
					'run run run',
					'runned',
				],
				'runcinate'=>[
					'runcinite',
				],
				'runnel'=>[
					'runel',
				],
				'runnels'=>[
					'runels',
				],
				'runner'=>[
					'runer',
				],
				'runners'=>[
					'runers',
				],
				'runnier'=>[
					'runier',
				],
				'runniest'=>[
					'runiest',
				],
				'running'=>[
					'runing',
				],
				'runnings'=>[
					'runings',
				],
				'runny'=>[
					'runy',
				],
				'rupiah'=>[
					'rupia',
				],
				'rupiahs'=>[
					'rupias',
				],
				'rushes'=>[
					'rushs',
				],
				'russet'=>[
					'ruset',
				],
				'russia'=>[
					'eussia',
					'russ*',
				],
				'russian'=>[
					'rusian',
					'russain',
					'russina',
					'russion',
					'russsian',
				],
				'russian-occupied'=>[
					'russian occupied',
				],
				'ruthless'=>[
					'ruthles',
				],
				'rwanda'=>[
					'ewanda',
				],
				'rwandan-occupied'=>[
					'rwandan occupied',
				],
				'règnes'=>[
					'regnes',
				],
				'régine'=>[
					'regine',
				],
				'régine chassagne'=>[
					'regine chassagne',
				],
				'rêve'=>[
					'reve',
				],
			];
		}
	}

?>