<?php
		
		/* UTF-8 TEST
		
			中文汉字漢字
		
		*/
				
				/* EnglishMisspellingsWords_T
					
					Class for English-Misspellings for all words beginning with : T.
					
				*/

	class EnglishMisspellingsWords_T {
			/* __construct($args)
			
				Constructor.
				
				Nothing to do here.
			
			*/
			
		public function __construct($args) {
			return TRUE;
		}
		
			/* EnglishMisspellingsWords()
			
				List of English misspellings for words starting with : T.
			
			*/

		public function EnglishMisspellingsWords() {
			return [
				'tabbouleh'=>[
					'tabouleh',
				],
				'tabboulehs'=>[
					'taboulehs',
				],
				'tabby'=>[
					'taby',
				],
				'tabernacular'=>[
					'tabernaculer',
				],
				'table'=>[
					'table table',
					'table table table',
				],
				'tableau'=>[
					'tableu',
				],
				'tables'=>[
					'tanles',
				],
				'tableware'=>[
					'tablewear',
				],
				'tabular'=>[
					'tabuler',
				],
				'tacamahac'=>[
					'tacamaac',
				],
				'tacamahacs'=>[
					'tacamaacs',
				],
				'tachinid'=>[
					'tachinad',
				],
				'tachistoscope'=>[
					'tachistocope',
					'tachistocsope',
					'tachistosope',
				],
				'tachyarrhythmia'=>[
					'tachyarhythmia',
				],
				'tacrine'=>[
					'tacrini',
				],
				'tactic'=>[
					'tactict',
				],
				'tactically'=>[
					'tacticaly',
				],
				'tactician'=>[
					'tactitian',
					'tactican',
				],
				'tactics'=>[
					'tatics',
				],
				'tactilely'=>[
					'tactilly',
				],
				'tactual'=>[
					'tactaul',
				],
				'taggant'=>[
					'tagant',
					'taggent',
				],
				'taggants'=>[
					'tagants',
				],
				'tagged'=>[
					'taged',
				],
				'tagger'=>[
					'tager',
				],
				'tagliatelle'=>[
					'tagliatele',
				],
				'tagmeme'=>[
					'tagme',
				],
				'tagmemes'=>[
					'tagmes',
				],
				'tagmemic'=>[
					'tagmic',
				],
				'tagmemics'=>[
					'tagmics',
				],
				'tahini'=>[
					'tahina',
					'taini',
				],
				'tahinis'=>[
					'tahinas',
					'tainis',
				],
				'tahr'=>[
					'tar',
				],
				'tahrs'=>[
					'tars',
				],
				'tahsil'=>[
					'tasil',
				],
				'tahsildar'=>[
					'tahsilder',
					'tasildar',
				],
				'tahsildars'=>[
					'tasildars',
				],
				'tahsils'=>[
					'tasils',
				],
				'tail'=>[
					'tail tail',
					'tail tail tail',
				],
				'tailleur'=>[
					'tailler',
				],
				'taillight'=>[
					'tailight',
				],
				'tailpiece'=>[
					'tailpeice',
					'tailpice',
				],
				'tailspinning'=>[
					'tailspining',
				],
				'taiwan'=>[
					'taiwon',
				],
				'taiwanese'=>[
					'taiwenese',
				],
				'takable'=>[
					'takible',
				],
				'takahe'=>[
					'takae',
				],
				'takahes'=>[
					'takaes',
				],
				'take'=>[
					'take take',
					'take take take',
					'tkae',
				],
				'taken'=>[
					'takn','takne',
					'tooked',
				],
				'takeover'=>[
					'takover',
				],
				'takes'=>[
					'tkaes',
				],
				'taking'=>[
					'tkaing',
				],
				'taking the reins'=>[
					'taking the reigns',
				],
				'talar'=>[
					'taler',
				],
				'taleggio'=>[
					'talegio',
				],
				'talent'=>[
					'talant',
				],
				'talisman'=>[
					'tallisman',
				],
				'talk'=>[
					'talk talk',
					'talk talk talk',
				],
				'talkatively'=>[
					'talkativly',
				],
				'talked'=>[
					'taked',
					'talekd',
				],
				'talkie'=>[
					'talkei',
					'talki',
				],
				'talking'=>[
					'tlaking',
				],
				'tall'=>[
					'tall tall',
					'tall tall tall',
					'tal',
				],
				'taller than'=>[
					'taller then',
				],
				'tallow'=>[
					'talow',
				],
				'tally'=>[
					'talally',
					'talaly',
					'tallly',
					'taly',
				],
				'tamable'=>[
					'tamible',
				],
				'tamandua'=>[
					'tamandau',
				],
				'tambourine'=>[
					'tamborine',
					'tambourini',
				],
				'tamely'=>[
					'tamly',
				],
				'tamil nadu'=>[
					'tamilnadu',
				],
				'tammy'=>[
					'tamny',
				],
				'tandem'=>[
					'tandum',
				],
				'tangence'=>[
					'tangance',
				],
				'tangency'=>[
					'tangensy',
				],
				'tangent'=>[
					'tangant',
				],
				'tangerine'=>[
					'tangerini',
				],
				'tangible'=>[
					'tangable',
				],
				'tango notturno'=>[
					'tango noturno',
				],
				'tankini'=>[
					'tankina',
				],
				'tannable'=>[
					'tanable',
					'tannible',
				],
				'tannages'=>[
					'tanages',
				],
				'tannate'=>[
					'tanate',
				],
				'tannates'=>[
					'tanates',
				],
				'tanned'=>[
					'taned',
				],
				'tanner'=>[
					'taner',
				],
				'tannery'=>[
					'tanery',
				],
				'tannic'=>[
					'tanic',
				],
				'tannin'=>[
					'tanin',
				],
				'tanning'=>[
					'taning',
				],
				'tannings'=>[
					'tanings',
				],
				'tannoy'=>[
					'tanoy',
				],
				'tansy'=>[
					'tancy',
				],
				'tantalize'=>[
					'tentalize',
				],
				'tantalum'=>[
					'tentalum',
				],
				'tantamount'=>[
					'tentamount',
				],
				'tantara'=>[
					'tentara',
				],
				'tantivy'=>[
					'tentivy',
				],
				'tanto'=>[
					'tento',
				],
				'tantra'=>[
					'tentra',
				],
				'tantrum'=>[
					'tentrum',
				],
				'tappable'=>[
					'tappible',
				],
				'tapper'=>[
					'taper',
				],
				'tappet'=>[
					'tapet',
				],
				'tapping'=>[
					'taping',
				],
				'tarantella'=>[
					'tarantela',
					'tarentella',
				],
				'tarantula'=>[
					'tarentula',
				],
				'targetable'=>[
					'targetible',
				],
				'targeted'=>[
					'targetted',
				],
				'targeting'=>[
					'targetting',
				],
				'tariff'=>[
					'tarif',
					'tarrif',
					'tarriff',
				],
				'tarradiddle'=>[
					'taradiddle',
				],
				'tarragon'=>[
					'taragon',
				],
				'tarre'=>[
					'tare',
				],
				'tarred'=>[
					'tared',
				],
				'tarriance'=>[
					'tarrience',
				],
				'tarry'=>[
					'tary',
				],
				'tartar'=>[
					'tarter',
				],
				'tartly'=>[
					'tartally',
					'tartaly',
					'tartely',
					'tartlly',
				],
				'taskbar'=>[
					'taskber',
				],
				'taskmistress'=>[
					'taskmistres',
				],
				'tass'=>[
					'tas',
				],
				'tasse'=>[
					'tase',
				],
				'tassel'=>[
					'tasel',
				],
				'tassie'=>[
					'tasie',
				],
				'taste'=>[
					'tast',
				],
				'tasteless'=>[
					'tasteles',
				],
				'tastelessly'=>[
					'tastelessally',
					'tastelessaly',
					'tastelessely',
					'tastelesslly',
				],
				'tatar'=>[
					'tater',
				],
				'tatouays'=>[
					'tatoauys',
				],
				'tattersall'=>[
					'tattersal',
				],
				'tattoo'=>[
					'tatoo',
				],
				'tattoos'=>[
					'tattooes',
				],
				'taught'=>[
					'teached',
					'tought',
				],
				'tauon'=>[
					'taon',
				],
				'tauons'=>[
					'taons',
				],
				'taurine'=>[
					'taurini',
				],
				'tautened'=>[
					'tautend',
				],
				'tautly'=>[
					'tautally',
					'tautaly',
					'tautely',
					'tautlly',
				],
				'tautologously'=>[
					'tautologousally',
					'tautologousaly',
					'tautologousely',
					'tautologouslly',
				],
				'taxable'=>[
					'taxible',
				],
				'taxonomic'=>[
					'taxanomic',
				],
				'taxonomy'=>[
					'taxanomy',
				],
				'tea'=>[
					'te',
				],
				'teaberry'=>[
					'teabery',
				],
				'teach'=>[
					'teach teach',
					'teach teach teach',
					'tech',
				],
				'teachable'=>[
					'teachible',
				],
				'teacher'=>[
					'techer',
				],
				'teacherly'=>[
					'teacherally',
					'teacheraly',
					'teacherely',
					'teacherlly',
				],
				'teaches'=>[
					'teachs',
				],
				'teaching'=>[
					'teching',
				],
				'teahouse'=>[
					'teaouse',
				],
				'teahouses'=>[
					'teaouses',
				],
				'teak'=>[
					'tek',
				],
				'teal'=>[
					'tel',
				],
				'team'=>[
					'team team',
					'team team team',
					'tem',
				],
				'team composed of'=>[
					'team comprised of',
				],
				'teammate'=>[
					'teamate',
					'teamnate',
					'temmate',
				],
				'teamwork'=>[
					'temwork',
				],
				'teapot'=>[
					'tepot',
				],
				'tear'=>[
					'teer',
					'ter',
				],
				'tearable'=>[
					'tearible',
				],
				'tearful'=>[
					'terful',
				],
				'tearing'=>[
					'tering',
				],
				'teary'=>[
					'teery',
					'tery',
				],
				'teas'=>[
					'tes',
				],
				'tease'=>[
					'tese',
				],
				'teaspoon'=>[
					'tespoon',
				],
				'teaspoonful'=>[
					'tespoonful',
				],
				'teat'=>[
					'tet',
				],
				'techie'=>[
					'techei',
					'techi',
				],
				'technical'=>[
					'techical',
					'techilical',
					'techincal',
				],
				'technically'=>[
					'technicaly',
				],
				'technician'=>[
					'techician',
					'technican',
				],
				'technique'=>[
					'techique',
					'techique', 'techniqu',
					'techniqu',
					'technque',
				],
				'technobabble'=>[
					'technobable',
				],
				'technobabbles'=>[
					'technobables',
				],
				'technocracy'=>[
					'technocrasy',
				],
				'technological'=>[
					'tecnological',
				],
				'technologically'=>[
					'technologicalally',
					'technologicalaly',
					'technologicalely',
					'technologicallly',
				],
				'technology'=>[
					'technolgy',
					'tecnology',
				],
				'tedious'=>[
					'tedous',
				],
				'tediously'=>[
					'tedously',
				],
				'teenage'=>[
					'teengage',
				],
				'teensy'=>[
					'teency',
				],
				'teentsy'=>[
					'teentcy',
				],
				'teenybopper'=>[
					'teenyboper',
				],
				'teeth'=>[
					'teetb',
					'teeth teeth',
					'teeth teeth teeth',
				],
				'tegg'=>[
					'teg',
				],
				'teggs'=>[
					'tegs',
				],
				'tegmina'=>[
					'tegmini',
				],
				'tegminal'=>[
					'tegminil',
				],
				'tegua'=>[
					'tegau',
				],
				'teguas'=>[
					'tegaus',
				],
				'tegular'=>[
					'teguler',
				],
				'tegumina'=>[
					'tegumini',
				],
				'teiglach'=>[
					'tieglach',
				],
				'teiid'=>[
					'tieid',
				],
				'teind'=>[
					'tiend',
				],
				'telangana'=>[
					'telengana',
				],
				'telangiectasia'=>[
					'telangeictasia',
					'telangictasia',
				],
				'telecommute'=>[
					'telecomnute',
				],
				'teleconference'=>[
					'teleconferance',
				],
				'telekinesis'=>[
					'telekinisis',
				],
				'telekinetically'=>[
					'telekinitically',
				],
				'teleprocessing'=>[
					'teleprocesing',
				],
				'telescope'=>[
					'telecope',
					'telecsope',
					'telesope',
				],
				'telescopic'=>[
					'telecopic',
					'telecsopic',
					'telesopic',
				],
				'televiewer'=>[
					'televeiwer',
					'televiwer',
				],
				'televise'=>[
					'televize',
				],
				'television'=>[
					'televison',
					'televison', 'telivision',
					'telivision',
				],
				'televisual'=>[
					'televisaul',
				],
				'tell'=>[
					'tell tell',
					'tell tell tell',
					'tel',
				],
				'teller'=>[
					'teler',
				],
				'telling'=>[
					'teling',
				],
				'telltale'=>[
					'teltale',
				],
				'tellurian'=>[
					'telluran',
				],
				'telluride'=>[
					'teluride',
				],
				'tellurometer'=>[
					'telurometer',
				],
				'telly'=>[
					'telally',
					'telaly',
					'tellly',
					'tely',
				],
				'temerarious'=>[
					'temerarous',
				],
				'temerariously'=>[
					'temerariousally',
					'temerariousaly',
					'temerariousely',
					'temerariouslly',
					'temerarously',
				],
				'temperament'=>[
					'temperment',
					'temperamant',
				],
				'temperamental'=>[
					'tempermental',
					'temperamantal',
				],
				'temperance'=>[
					'temperence',
				],
				'temperate'=>[
					'temparate',
				],
				'temperately'=>[
					'temperatly',
				],
				'temperature'=>[
					'temerature',
					'temperature temperature',
					'temperature temperature temperature',
					'temperture',
					'temprature',
				],
				'tempestuous'=>[
					'tempestous',
				],
				'tempestuously'=>[
					'tempestously',
					'tempestuousally',
					'tempestuousaly',
					'tempestuousely',
					'tempestuouslly',
				],
				'tempestuousness'=>[
					'tempestousness',
				],
				'temporarily'=>[
					'temporarely',
				],
				'temporarinesses'=>[
					'temporarinisses',
				],
				'temporary'=>[
					'temporery',
				],
				'ten'=>[
					'ten ten',
					'ten ten ten',
				],
				'tenable'=>[
					'tenible',
				],
				'tenacious'=>[
					'tenacous',
				],
				'tenaciously'=>[
					'tenaciousally',
					'tenaciousaly',
					'tenaciousely',
					'tenaciouslly',
					'tenacously',
				],
				'tenancy'=>[
					'tenansy',
				],
				'tenant'=>[
					'tennant',
					'tenent',
				],
				'tendance'=>[
					'tendence',
				],
				'tendence'=>[
					'tendance',
				],
				'tendencies'=>[
					'tendancies',
				],
				'tendencious'=>[
					'tendencous',
				],
				'tendency'=>[
					'tendancy',
					'tendensy',
				],
				'tendentious'=>[
					'tendantious',
					'tendentous',
				],
				'tendentiously'=>[
					'tendantiously',
					'tendentiousally',
					'tendentiousaly',
					'tendentiousely',
					'tendentiouslly',
					'tendentously',
				],
				'tendentiousness'=>[
					'tendantiousness',
				],
				'tenderhearted'=>[
					'tenderherted',
				],
				'tenderheartedly'=>[
					'tenderheartedally',
					'tenderheartedaly',
					'tenderheartedely',
					'tenderheartedlly',
				],
				'tendinitis'=>[
					'tendonitis',
					'tendinatis',
				],
				'tenebrious'=>[
					'tenebrous',
				],
				'tenement'=>[
					'tenament',
					'tennament',
					'tennement',
					'tenemant',
				],
				'tenner'=>[
					'tener',
				],
				'tennies'=>[
					'tenies',
				],
				'tennis'=>[
					'tenis',
				],
				'tennis player'=>[
					'tennisplayer',
				],
				'tennises'=>[
					'tenises',
				],
				'tennists'=>[
					'tenists',
				],
				'tenor'=>[
					'tenour',
					'tenoure',
				],
				'tenorist'=>[
					'tenourist',
				],
				'tenorists'=>[
					'tenourists',
				],
				'tenorite'=>[
					'tenourite',
				],
				'tenorites'=>[
					'tenourites',
				],
				'tenpence'=>[
					'tenpance',
				],
				'tense'=>[
					'tence',
				],
				'tensely'=>[
					'tensly',
				],
				'tensible'=>[
					'tensable',
				],
				'tensilely'=>[
					'tensilly',
				],
				'tent'=>[
					'tant',
				],
				'tentacle'=>[
					'tenacle',
					'tenticle',
					'tantacle',
				],
				'tentacular'=>[
					'tentaculer',
				],
				'tentage'=>[
					'tantage',
				],
				'tentative'=>[
					'tantative',
				],
				'tented'=>[
					'tanted',
				],
				'tenter'=>[
					'tanter',
				],
				'tenth'=>[
					'tanth',
				],
				'tents'=>[
					'tants',
				],
				'tenty'=>[
					'tanty',
				],
				'tenuous'=>[
					'tenous',
				],
				'tenuously'=>[
					'tenously',
				],
				'tenuousness'=>[
					'tenousness',
				],
				'tenuousnesses'=>[
					'tenousnesses',
				],
				'tenure'=>[
					'teneur',
					'teneure',
					'tenowr',
					'tenture',
					'tenur',
				],
				'tepidly'=>[
					'tepidally',
					'tepidaly',
					'tepidely',
					'tepidlly',
				],
				'terahertz'=>[
					'teraertz',
				],
				'terahertzes'=>[
					'teraertzes',
				],
				'tercentenary'=>[
					'tercantenary',
					'tercentenery',
				],
				'tercentennial'=>[
					'tercantennial',
					'tercentenial',
				],
				'tercentennials'=>[
					'tercentenials',
				],
				'terefah'=>[
					'terefa',
				],
				'term'=>[
					'term term',
					'term term term',
				],
				'terminable'=>[
					'terminible',
				],
				'terminableness'=>[
					'terminibleness',
				],
				'terminably'=>[
					'terminabally',
					'terminabaly',
					'terminabely',
					'terminablly',
				],
				'terminal'=>[
					'terminil',
				],
				'terminally'=>[
					'terminaly',
				],
				'terminate'=>[
					'terminite',
				],
				'termination'=>[
					'terminition',
				],
				'terminational'=>[
					'terminitional',
				],
				'terminations'=>[
					'terminitions',
				],
				'terminative'=>[
					'terminitive',
				],
				'terminatively'=>[
					'terminativly',
					'terminitively',
				],
				'terminator'=>[
					'terminitor',
				],
				'termini'=>[
					'termina',
				],
				'termitary'=>[
					'termitery',
				],
				'termly'=>[
					'termally',
					'termaly',
					'termely',
					'termlly',
				],
				'termor'=>[
					'termour',
				],
				'termors'=>[
					'termours',
				],
				'ternary'=>[
					'ternery',
				],
				'ternately'=>[
					'ternatly',
				],
				'terpsichorean'=>[
					'terpsichoren',
				],
				'terra'=>[
					'tera',
				],
				'terrace'=>[
					'terace',
				],
				'terrae'=>[
					'terae',
				],
				'terraform'=>[
					'teraform',
				],
				'terrain'=>[
					'terain',
				],
				'terrane'=>[
					'terane',
				],
				'terrapin'=>[
					'terapin',
				],
				'terraqueous'=>[
					'teraqueous',
				],
				'terrarium'=>[
					'terarium',
				],
				'terrazzo'=>[
					'terazzo',
				],
				'terrene'=>[
					'terene',
				],
				'terrenely'=>[
					'terrenly',
				],
				'terreplein'=>[
					'tereplein',
					'terreplien',
				],
				'terrestrial'=>[
					'terestrial',
					'terresterial',
					'terrestial',
				],
				'terret'=>[
					'teret',
				],
				'terrible'=>[
					'terible',
					'terrable',
				],
				'terriblenesses'=>[
					'teriblenesses',
				],
				'terribly'=>[
					'teribly',
					'terribally',
					'terribaly',
					'terribely',
					'terriblly',
				],
				'terricolous'=>[
					'tericolous',
				],
				'terrier'=>[
					'terreir',
					'terier',
					'terrir',
				],
				'terrific'=>[
					'terific',
				],
				'terrify'=>[
					'terify',
				],
				'terrigenous'=>[
					'terigenous',
				],
				'terrine'=>[
					'terine',
					'terrini',
				],
				'territorial'=>[
					'teritorial',
				],
				'territorialism'=>[
					'teritorialism',
				],
				'territorialisms'=>[
					'teritorialisms',
				],
				'territorialist'=>[
					'teritorialist',
				],
				'territorialists'=>[
					'teritorialists',
				],
				'territoriality'=>[
					'teritoriality',
				],
				'territorialize'=>[
					'teritorialize',
				],
				'territorialized'=>[
					'teritorialized',
				],
				'territorializes'=>[
					'teritorializes',
				],
				'territories'=>[
					'terriories',
					'territones',
					'territores',
					'territorles',
				],
				'territory'=>[
					'teritory',
					'terriory',
					'territority',
				],
				'terror'=>[
					'teror',
				],
				'terrorism'=>[
					'terorism',
				],
				'terrorist'=>[
					'terorist',
					'territorist',
				],
				'terrorizations'=>[
					'terorizations',
				],
				'terrorize'=>[
					'terorize',
				],
				'terry'=>[
					'tery',
				],
				'tersely'=>[
					'tersly',
				],
				'tertian'=>[
					'tertan',
				],
				'tertiary'=>[
					'tertiery',
				],
				'tessera'=>[
					'tesera',
				],
				'test'=>[
					'test test',
					'test test test',
				],
				'testacy'=>[
					'testasy',
				],
				'testament'=>[
					'testiment',
					'testimont',
					'testamant',
				],
				'testamentary'=>[
					'testamentery',
				],
				'testicle'=>[
					'testical',
				],
				'testicular'=>[
					'testiculer',
				],
				'testimonial'=>[
					'testamonial',
				],
				'testimony'=>[
					'test1mony',
					'testamony',
					'testlmony',
					'testomony',
				],
				'tetracaine'=>[
					'tetracaini',
				],
				'tetracycline'=>[
					'tetracyclini',
				],
				'tetrafluoride'=>[
					'tetrafloride',
				],
				'tetrafluorides'=>[
					'tetraflorides',
				],
				'tetragrammatons'=>[
					'tetragramnatons',
				],
				'tetrahedra'=>[
					'tetraedra',
				],
				'tetrahedral'=>[
					'tetraedral',
				],
				'tetrahedrally'=>[
					'tetraedrally',
				],
				'tetrahedrite'=>[
					'tetraedrite',
				],
				'tetrahedrites'=>[
					'tetraedrites',
				],
				'tetrahedron'=>[
					'tetraedron',
				],
				'tetrahedrons'=>[
					'tetraedrons',
				],
				'tetrahydrofuran'=>[
					'tetraydrofuran',
				],
				'tetrahymena'=>[
					'tetraymena',
				],
				'tetrahymenas'=>[
					'tetraymenas',
				],
				'tetrazzini'=>[
					'tetrazzina',
				],
				'texts'=>[
					'textes',
				],
				'textual'=>[
					'textaul',
				],
				'textuary'=>[
					'textaury',
					'textuery',
				],
				'thai-occupied'=>[
					'thai occupied',
				],
				'thalassaemia'=>[
					'thalasaemia',
				],
				'thalassemia'=>[
					'thalasemia',
				],
				'thalassocracy'=>[
					'thalasocracy',
					'thalassocrasy',
				],
				'thallious'=>[
					'thallous',
				],
				'thallium'=>[
					'thalium',
				],
				'than'=>[
					'tahn',
					'than than',
					'than than than',
					'thna',
				],
				'thank'=>[
					'thanbk',
					'thank thank',
					'thank thank thank',
				],
				'thanklessly'=>[
					'thanklessally',
					'thanklessaly',
					'thanklessely',
					'thanklesslly',
				],
				'that'=>[
					'htat',
					'taht',
					'tath',
					'tbat',
					'that that',
					'that that that',
					'thgat',
					'thot',
					'thst',
					'tht',
					'thta',
					'thyat',
					'tyhat',
				],
				'that are'=>[
					'thet are',
				],
				'that\'s'=>[
					'thast',
					'thats',
				],
				'the'=>[
					'a the',
					'hte',
					'hthe',
					'ihe',
					'rhe',
					'tbe',
					'tbe','tlie',
					'teh',
					'tge',
					'tghe',
					'thc',
					'the the',
					'the the the',
					'thge',
					'thte',
					'ththe',
					'tiie',
					'tje',
					'tjhe',
					'tlie',
					'tthe',
					'ttle',
					'tye',
					'yhe',
				],
				'the album closes'=>[
					'the albums closes',
				],
				'the large'=>[
					'thelarge',
				],
				'the legal'=>[
					'thelegal',
				],
				'the new'=>[
					'thenew',
				],
				'the other'=>[
					'tho other',
				],
				'the position'=>[
					'theposition',
				],
				'the small'=>[
					'thesmall',
				],
				'theater'=>[
					'theather',
					'theter',
				],
				'theatergoer'=>[
					'thetergoer',
				],
				'theatre'=>[
					'thetre',
				],
				'theatrical'=>[
					'thetrical',
				],
				'theatricalism'=>[
					'thetricalism',
				],
				'theatricalize'=>[
					'thetricalize',
				],
				'theatrics'=>[
					'thetrics',
				],
				'theessink'=>[
					'theesink',
				],
				'thein'=>[
					'thien',
				],
				'theine'=>[
					'theini',
					'thiene',
				],
				'their'=>[
					'tehir',
					'theier',
					'their their',
					'their their their',
					'theit',
					'theri',
					'thier',
					'tlieir',
				],
				'their done'=>[
					'thier',
				],
				'theirs'=>[
					'their\'s',
					'thiers',
				],
				'theirselves'=>[
					'thierselves',
				],
				'theism'=>[
					'thiesm',
				],
				'theistically'=>[
					'thiestically',
				],
				'them'=>[
					'tbem',
					'them them',
					'them them them',
					'tliem',
				],
				'themselves'=>[
					'fhemselves', 'theinselves',
					'thcmsclves',
					'themseleves',
					'themself',
					'themselfs',
					'themsleves',
				],
				'then'=>[
					'hten',
					'then then',
					'then then then',
					'thne',
				],
				'thenar'=>[
					'thener',
				],
				'thence'=>[
					'thance',
				],
				'theobromine'=>[
					'theobromini',
				],
				'theocracy'=>[
					'theocrasy',
				],
				'theodicy'=>[
					'theodisy',
				],
				'theologian'=>[
					'theologan',
				],
				'theophylline'=>[
					'theophyline',
					'theophyllini',
				],
				'theoretical'=>[
					'theroretical',
				],
				'theoretically'=>[
					'tbeoretically',
				],
				'theoretician'=>[
					'theoretican',
				],
				'theory'=>[
					'thoery',
				],
				'therapeusis'=>[
					'therapeuiss',
				],
				'therapeutic'=>[
					'therapuetic',
					'therepeutic',
				],
				'therapeutics'=>[
					'therapuetics',
				],
				'therapy'=>[
					'theraphy',
				],
				'there'=>[
					'htere',
					'thcrc',
					'thcre',
					'ther',
					'therc',
					'there there',
					'there there there',
					'thrcc',
					'thrce',
					'threc',
				],
				'there were'=>[
					'there where',
				],
				'thereabouts'=>[
					'therebouts',
				],
				'thereafter'=>[
					'thenafter',
					'therafter',
					'therefter',
				],
				'therefore'=>[
					'herefore',
					'thcreforc',
					'therfore',
				],
				'therein'=>[
					'therien',
				],
				'thereinafter'=>[
					'thereinifter',
					'therienafter',
				],
				'thereinto'=>[
					'theriento',
				],
				'therewithal'=>[
					'therewital',
				],
				'therian'=>[
					'theran',
				],
				'theriomorphic'=>[
					'theriomourphic',
				],
				'thermocline'=>[
					'thermoclini',
				],
				'thermoformable'=>[
					'thermoformible',
				],
				'thermonuclear'=>[
					'thermonucleer',
					'thermonucler',
				],
				'thermoreceptor'=>[
					'thermoureceptor',
				],
				'thermoreceptors'=>[
					'thermoureceptors',
				],
				'thermoregulate'=>[
					'thermouregulate',
				],
				'thermoregulated'=>[
					'thermouregulated',
				],
				'thermoregulates'=>[
					'thermouregulates',
				],
				'thermoregulator'=>[
					'thermouregulator',
				],
				'thermoremanence'=>[
					'thermoremanance',
					'thermouremanence',
				],
				'thermoremanent'=>[
					'thermouremanent',
				],
				'thermostable'=>[
					'thermostible',
				],
				'these'=>[
					'theese',
					'these these',
					'these these these',
				],
				'thespian'=>[
					'thespan',
				],
				'they'=>[
					'fhey',
					'htey',
					'tehy',
					'thay',
					'thet', 'thev',
					'they they',
					'they they they',
					'tliey',
					'tyhe',
				],
				'they had'=>[
					'theyhad',
				],
				'they make'=>[
					'they makes',
				],
				'thick'=>[
					'thick thick',
					'thick thick thick',
				],
				'thickened'=>[
					'thickend',
				],
				'thickness'=>[
					'thicknes',
				],
				'thief'=>[
					'theif',
					'thif',
				],
				'thiefs'=>[
					'theifs',
				],
				'thievery'=>[
					'theivery',
					'thivery',
				],
				'thieves'=>[
					'theives',
					'thiefs',
				],
				'thievish'=>[
					'theivish',
				],
				'thill'=>[
					'thil',
				],
				'thimbleberries'=>[
					'thimbleberies',
				],
				'thimbleberry'=>[
					'thimblebery',
				],
				'thimblerigged'=>[
					'thimbleriged',
				],
				'thimblerigger'=>[
					'thimbleriger',
				],
				'thimbleriggers'=>[
					'thimblerigers',
				],
				'thimblerigging'=>[
					'thimbleriging',
				],
				'thin'=>[
					'thin thin',
					'thin thin thin',
				],
				'thine'=>[
					'thini',
				],
				'thing'=>[
					'hting',
					'thig',
					'thign',
					'thing thing',
					'thing thing thing',
					'thnig',
				],
				'things'=>[
					'thigns',
					'thigsn',
					'thnigs',
				],
				'thingummy'=>[
					'thingumny',
				],
				'think'=>[
					'htikn',
					'htink',
					'thikn',
					'think think',
					'think think think',
					'thiunk',
					'tihkn',
				],
				'thinkable'=>[
					'thinkible',
				],
				'thinking'=>[
					'thikning',
					'thingking',
				],
				'thinks'=>[
					'thikns',
				],
				'thinner'=>[
					'thiner',
				],
				'thioridazine'=>[
					'thioridazini',
				],
				'third'=>[
					'third third',
					'third third third',
					'thrid',
				],
				'thirdly'=>[
					'thridly',
					'thirdally',
					'thirdaly',
					'thirdely',
					'thirdlly',
				],
				'thirteen'=>[
					'thirteeen',
					'thriteen',
				],
				'thirteenth'=>[
					'thirteanth',
				],
				'thirties'=>[
					'thirtys',
				],
				'thirtieth'=>[
					'thirteith',
					'thirtith',
				],
				'thirty'=>[
					'thrity',
					'tliirty',
				],
				'this'=>[
					'bbis',
					'htis',
					'this this',
					'this this this',
					'ths',
					'thsi',
					'tihs',
				],
				'tholeiite'=>[
					'tholieite',
				],
				'thorough'=>[
					'thorogh',
					'thorugh',
					'thourough',
					'thruogh',
				],
				'thoroughbass'=>[
					'thoroughbas',
				],
				'thoroughbred'=>[
					'thoroghbred',
					'thoroughbread',
				],
				'thoroughfare'=>[
					'throughfare',
				],
				'thoroughly'=>[
					'thorougly',
					'thouroughly',
					'throughly',
				],
				'those'=>[
					'ethose',
					'thiose',
					'those those',
					'those those those',
					'thosse',
					'thsoe',
				],
				'though'=>[
					'though though',
					'though though though',
				],
				'thought'=>[
					'thought thought',
					'thought thought thought',
					'throught',
					'tought',
				],
				'thoughtless'=>[
					'thoughtles',
				],
				'thoughtlessly'=>[
					'thoughtlessally',
					'thoughtlessaly',
					'thoughtlessely',
					'thoughtlesslly',
				],
				'thoughts'=>[
					'thoughs',
					'toughts',
				],
				'thousand'=>[
					'thousand thousand',
					'thousand thousand thousand',
					'thousnad',
				],
				'thraldom'=>[
					'thraldoin',
				],
				'thrall'=>[
					'thral',
				],
				'thread'=>[
					'thred',
				],
				'threadbare'=>[
					'thredbare',
				],
				'threat'=>[
					'threath',
					'thret',
				],
				'threaten'=>[
					'threten',
				],
				'threatened'=>[
					'threated',
					'threatend',
					'thretened',
				],
				'threatening'=>[
					'threatning',
				],
				'three'=>[
					'three three',
					'three three three',
					'threee',
				],
				'three-year-old who'=>[
					'three year old who',
				],
				'threepence'=>[
					'threepance',
				],
				'threepenny'=>[
					'threepeny',
				],
				'threonine'=>[
					'threonini',
				],
				'threshold'=>[
					'threshhold',
					'thresold',
					'treshold',
				],
				'thrill'=>[
					'thril',
				],
				'thriller'=>[
					'thriler',
				],
				'thrombokinase'=>[
					'thrombokinise',
				],
				'thrombokinases'=>[
					'thrombokinises',
				],
				'through'=>[
					'throgh',
					'throguh',
					'through through',
					'through through through',
					'thru',
				],
				'through its'=>[
					'through it\'',
					'through its\'',
				],
				'throughly'=>[
					'throughally',
					'throughaly',
					'throughely',
					'throughlly',
				],
				'throughout'=>[
					'thoughout',
					'through out',
					'throughtout',
					'througout',
					'troughout',
				],
				'throw'=>[
					'throw throw',
					'throw throw throw',
				],
				'thrust'=>[
					'thrusted',
				],
				'thruston ballard morton'=>[
					'thurston ballard morton',
				],
				'thuggees'=>[
					'thugees',
				],
				'thuggeries'=>[
					'thugeries',
				],
				'thuggery'=>[
					'thugery',
				],
				'thuggish'=>[
					'thugish',
				],
				'thunderhead'=>[
					'thunderhed',
				],
				'thurible'=>[
					'thurable',
				],
				'thus'=>[
					'thus thus',
					'thus thus thus',
				],
				'thusly'=>[
					'thusally',
					'thusaly',
					'thusely',
					'thuslly',
				],
				'thwartly'=>[
					'thwartally',
					'thwartaly',
					'thwartely',
					'thwartlly',
				],
				'thymidine'=>[
					'thymidini',
				],
				'thymine'=>[
					'thymini',
				],
				'thyroxine'=>[
					'thyroxini',
				],
				'tiananmen'=>[
					'tianenmen','tienanmen',
				],
				'tibetan'=>[
					'thibetan',
				],
				'ticced'=>[
					'ticed',
				],
				'ticcing'=>[
					'ticing',
				],
				'tiddly'=>[
					'tiddally',
					'tiddaly',
					'tiddely',
					'tiddlly',
				],
				'tie'=>[
					'tie tie',
					'tie tie tie',
					'tei',
				],
				'tieback'=>[
					'teiback',
					'tiback',
				],
				'tiebreak'=>[
					'teibreak',
					'tibreak',
				],
				'tiebreaker'=>[
					'teibreaker',
					'tibreaker',
					'tiebreker',
				],
				'tied'=>[
					'teid',
				],
				'tier'=>[
					'teir',
				],
				'ties'=>[
					'teis',
				],
				'tightened'=>[
					'tightend',
				],
				'tijuana'=>[
					'tiajuana',
				],
				'till'=>[
					'til',
				],
				'tillage'=>[
					'tilage',
				],
				'tiller'=>[
					'tiler',
				],
				'timberline'=>[
					'timberlini',
				],
				'time'=>[
					'tiem',
					'time time',
					'time time time',
					'timne',
					'tiome',
				],
				'timeless'=>[
					'timeles',
				],
				'timeline'=>[
					'timelini',
				],
				'timely'=>[
					'timeally',
					'timealy',
					'timeely',
					'timelly',
					'timly',
				],
				'timepiece'=>[
					'timepeice',
					'timepice',
				],
				'times'=>[
					'timees',
				],
				'timescale'=>[
					'timecale',
					'timecsale',
					'timesale',
				],
				'timetable'=>[
					'timetible',
				],
				'timidly'=>[
					'timidally',
					'timidaly',
					'timidely',
					'timidlly',
				],
				'timocracy'=>[
					'timocrasy',
				],
				'timorous'=>[
					'timourous',
				],
				'timorously'=>[
					'timourously',
				],
				'timorousness'=>[
					'timourousness',
				],
				'timorousnesses'=>[
					'timourousnesses',
				],
				'tinamou'=>[
					'tinimou',
				],
				'tinamous'=>[
					'tinimous',
				],
				'tinea'=>[
					'tinia',
				],
				'tined'=>[
					'tinid',
				],
				'tines'=>[
					'tinis',
				],
				'tinier'=>[
					'tinaer',
				],
				'tiniest'=>[
					'tinaest',
				],
				'tinily'=>[
					'tinaly',
				],
				'tining'=>[
					'tinang',
				],
				'tinman'=>[
					'timan',
					'tinan',
				],
				'tinmen'=>[
					'timen',
					'tinen',
				],
				'tinner'=>[
					'tiner',
				],
				'tinnitus'=>[
					'tinitus',
				],
				'tinny'=>[
					'tiny',
				],
				'tintinnabulary'=>[
					'tintinabulary',
					'tintinnabulery',
				],
				'tiny'=>[
					'tiny tiny',
					'tiny tiny tiny',
				],
				'tippable'=>[
					'tippible',
				],
				'tippet'=>[
					'tipet',
				],
				'tipple'=>[
					'tiple',
				],
				'tippy'=>[
					'tipy',
				],
				'tipsy'=>[
					'tipcy',
				],
				'tirade'=>[
					'tirad',
				],
				'tire'=>[
					'tire tire',
					'tire tire tire',
				],
				'tireless'=>[
					'tireles',
				],
				'tiresomely'=>[
					'tiresomly',
				],
				'tissue'=>[
					'tisue',
				],
				'titian'=>[
					'titan',
				],
				'title'=>[
					'tittle',
				],
				'titrant'=>[
					'titrent',
				],
				'titular'=>[
					'tituler',
				],
				'titularly'=>[
					'titularally',
					'titularaly',
					'titularely',
					'titularlly',
				],
				'titulary'=>[
					'titulery',
				],
				'to'=>[
					'to to',
					'to to to',
				],
				'to a'=>[
					'ot a',
				],
				'to and fro'=>[
					'two and fro',
				],
				'to be treated'=>[
					'to treated',
				],
				'to its'=>[
					'to it\'',
					'to it\'s',
					'to its\'',
				],
				'to remove'=>[
					'to removed',
				],
				'to the'=>[
					'ot the',
					'othe',
					't othe',
					'to the to the',
					'to tho',
					'tot he',
					'tothe',
				],
				'toastmistress'=>[
					'toastmistres',
				],
				'tobacco'=>[
					'tabacco',
					'tableclothes',
					'tobbaco',
					'tobaco',
				],
				'tobacconist'=>[
					'tobaconist',
				],
				'toboggan'=>[
					'tobogan',
				],
				'tobogganed'=>[
					'toboganed',
				],
				'tobogganer'=>[
					'toboganer',
				],
				'tobogganers'=>[
					'toboganers',
				],
				'tobogganing'=>[
					'toboganing',
				],
				'tobogganings'=>[
					'toboganings',
				],
				'tobogganist'=>[
					'toboganist',
				],
				'tobogganists'=>[
					'toboganists',
				],
				'toccata'=>[
					'tocata',
				],
				'toccate'=>[
					'tocate',
				],
				'today'=>[
					'todya',
				],
				'today\'s'=>[
					'todays',
				],
				'toea'=>[
					'toe',
				],
				'together'=>[
					'tegether',
					'togather',
					'togeather',
					'togehter',
					'together together',
					'together together together',
					'togther',
				],
				'togged'=>[
					'toged',
				],
				'toggery'=>[
					'togery',
				],
				'toggle'=>[
					'togle',
				],
				'togglers'=>[
					'toglers',
				],
				'toggling'=>[
					'togling',
				],
				'toilet'=>[
					'toliet',
				],
				'toilsomely'=>[
					'toilsomly',
				],
				'tokened'=>[
					'tokend',
				],
				'tolar'=>[
					'toler',
				],
				'told'=>[
					'telled',
					'told told',
					'told told told',
				],
				'tolerable'=>[
					'tolerible',
				],
				'tolerance'=>[
					'tolerence',
				],
				'tolerant'=>[
					'tolerent',
				],
				'tolerate'=>[
					'tolelate',
				],
				'tolkien'=>[
					'tolkein',
				],
				'toll'=>[
					'tol',
				],
				'tollway'=>[
					'tolway',
				],
				'toluate'=>[
					'tolaute',
				],
				'toluates'=>[
					'tolautes',
				],
				'toluidine'=>[
					'toluidini',
				],
				'toluol'=>[
					'tolol',
				],
				'toluole'=>[
					'tolole',
				],
				'toluoles'=>[
					'tololes',
				],
				'toluols'=>[
					'tolols',
				],
				'tomahawk'=>[
					'tomaawk',
				],
				'tomahawked'=>[
					'tomaawked',
				],
				'tomahawking'=>[
					'tomaawking',
				],
				'tomahawks'=>[
					'tomaawks',
				],
				'tomatoes'=>[
					'tomatos',
				],
				'tommy'=>[
					'tomny',
				],
				'tommy makem'=>[
					'tommy make',
				],
				'tommyrot'=>[
					'tomnyrot',
				],
				'tomorrow'=>[
					'tommorow',
					'tommorrow',
					'tomorow',
					'tomourrow',
				],
				'tomorrows'=>[
					'tomourrows',
				],
				'tone'=>[
					'tone tone',
					'tone tone tone',
				],
				'tongue'=>[
					'tounge',
					'toungue',
				],
				'tongue-in-cheek'=>[
					'tongue and cheek',
					'tongue-and-cheek',
				],
				'tonight'=>[
					'tongiht',
				],
				'tonnage'=>[
					'tonage',
				],
				'tonne'=>[
					'tone',
				],
				'tonneau'=>[
					'toneau',
				],
				'tonsilar'=>[
					'tonsiler',
				],
				'tonsillar'=>[
					'tonsiller',
				],
				'tonsillectomy'=>[
					'tonsilectomy',
				],
				'tonsillitis'=>[
					'tonsilitis',
				],
				'tontine'=>[
					'tontini',
				],
				'too'=>[
					'too too',
					'too too too',
					'tooo',
				],
				'took'=>[
					'took took',
					'took took took',
					'toook',
				],
				'took over'=>[
					'tookover',
				],
				'tool'=>[
					'tool tool',
					'tool tool tool',
				],
				'toolbar'=>[
					'toolber',
				],
				'toolless'=>[
					'tooless',
				],
				'toothless'=>[
					'toothles',
				],
				'toothsomely'=>[
					'toothsomly',
				],
				'tootsie'=>[
					'tootsei',
					'tootsi',
				],
				'tootsy'=>[
					'tootcy',
				],
				'top'=>[
					'top top',
					'top top top',
					'tope',
				],
				'top-earning runner'=>[
					'top earning runner',
				],
				'topiary'=>[
					'topiery',
				],
				'topknot'=>[
					'topkot',
				],
				'topknots'=>[
					'topkots',
				],
				'topless'=>[
					'toples',
				],
				'topminnow'=>[
					'topminow',
				],
				'topper'=>[
					'toper',
				],
				'topping'=>[
					'toping',
				],
				'topple'=>[
					'tople',
				],
				'torah'=>[
					'tora',
				],
				'torahs'=>[
					'toras',
				],
				'torch'=>[
					'tourch',
				],
				'torchbearer'=>[
					'torchberer',
				],
				'torment'=>[
					'tormant',
				],
				'tornadoes'=>[
					'tornados',
					'tornaodes',
				],
				'toroid'=>[
					'toriod',
				],
				'toroidal'=>[
					'toriodal',
				],
				'torpedoed'=>[
					'torpedod',
				],
				'torpedoes'=>[
					'torpedos',
				],
				'torquate'=>[
					'torqaute',
				],
				'torr'=>[
					'tor',
				],
				'torrent'=>[
					'torent',
					'torrant',
				],
				'torrential'=>[
					'torential',
				],
				'torrid'=>[
					'torid',
				],
				'torrs'=>[
					'tors',
				],
				'tortellini'=>[
					'tortelini',
					'tortellina',
				],
				'torticollis'=>[
					'torticolis',
				],
				'tortilla'=>[
					'tortila',
				],
				'tortious'=>[
					'tortous',
				],
				'tortiously'=>[
					'tortously',
				],
				'tortoise'=>[
					'tortise',
					'totoise',
				],
				'tortoiseshell'=>[
					'tortoiseshel',
				],
				'tortuosities'=>[
					'tortosities',
				],
				'tortuosity'=>[
					'tortosity',
				],
				'tortuous'=>[
					'tortous',
				],
				'tortuously'=>[
					'tortously',
				],
				'tortuousness'=>[
					'tortousness',
				],
				'tortuousnesses'=>[
					'tortousnesses',
				],
				'torturous'=>[
					'tortous',
				],
				'toss'=>[
					'tos',
				],
				'tossup'=>[
					'tosup',
				],
				'totable'=>[
					'totible',
				],
				'total'=>[
					'total total',
					'total total total',
				],
				'totaled'=>[
					'totalled',
				],
				'totaling'=>[
					'totalling',
				],
				'totalitarian'=>[
					'totalitaran',
				],
				'totally'=>[
					'totaly',
					'totalally',
					'totalaly',
					'totalely',
					'totallly',
				],
				'totipotency'=>[
					'totipotensy',
				],
				'tottery'=>[
					'tottary',
				],
				'touch'=>[
					'touch touch',
					'touch touch touch',
				],
				'touchline'=>[
					'touchlini',
				],
				'toughened'=>[
					'toughend',
				],
				'tourmaline'=>[
					'tourmalini',
				],
				'tournament'=>[
					'tornament',
					'tounament',
					'tourament',
					'tourmanent',
					'tournement',
					'tournamant',
				],
				'touré'=>[
					'toure',
				],
				'towable'=>[
					'towible',
				],
				'toward'=>[
					'toward toward',
					'toward toward toward',
					'towrad',
				],
				'towardly'=>[
					'towardally',
					'towardaly',
					'towardely',
					'towardlly',
				],
				'towards'=>[
					'tor-ards',
				],
				'town'=>[
					'town town',
					'town town town',
					'twon',
				],
				'townscape'=>[
					'towncape',
					'towncsape',
					'townsape',
				],
				'toxicant'=>[
					'toxicent',
				],
				'toxicologically'=>[
					'toxicologicalally',
					'toxicologicalaly',
					'toxicologicalely',
					'toxicologicallly',
				],
				'trabecular'=>[
					'trabeculer',
				],
				'tracheary'=>[
					'tracheery',
				],
				'tracheid'=>[
					'trachied',
				],
				'tracheitis'=>[
					'trachietis',
				],
				'tracheitises'=>[
					'trachietises',
				],
				'tracheolar'=>[
					'tracheoler',
				],
				'track'=>[
					'track track',
					'track track track',
				],
				'track listing'=>[
					'tracklisting',
				],
				'trackball'=>[
					'trackbal',
				],
				'tractable'=>[
					'tractible',
				],
				'trade'=>[
					'trade trade',
					'trade trade trade',
				],
				'trader'=>[
					'traider',
				],
				'tradescantia'=>[
					'tradecantia',
					'tradecsantia',
					'tradesantia',
					'tradescentia',
				],
				'tradition'=>[
					'traditionn',
					'traditon',
				],
				'traditional'=>[
					'tradicional',
					'tradional',
					'traditonal',
				],
				'traditionalism'=>[
					'tradionalism',
				],
				'traditionally'=>[
					'tradionally',
					'traditionaly',
					'traditonally', 'tradionally',
				],
				'traditionary'=>[
					'traditionery',
				],
				'traffic'=>[
					'trafic',
				],
				'trafficked'=>[
					'trafficed',
				],
				'tragedian'=>[
					'tragedan',
				],
				'tragedienne'=>[
					'tragedeinne',
					'tragediene',
					'tragedinne',
				],
				'tragedy'=>[
					'tradgedy',
				],
				'tragic'=>[
					'tragical',
				],
				'trailbreaker'=>[
					'trailbreker',
				],
				'trailhead'=>[
					'trailhed',
				],
				'train'=>[
					'train train',
					'train train train',
				],
				'trainabilities'=>[
					'trainibilities',
				],
				'trainability'=>[
					'trainibility',
				],
				'trainable'=>[
					'trainible',
				],
				'trainee'=>[
					'trainie',
				],
				'trainer'=>[
					'trainir',
				],
				'training'=>[
					'traing',
					'traning',
					'trainang',
				],
				'trainman'=>[
					'traiman',
					'trainan',
				],
				'trainmen'=>[
					'traimen',
					'trainen',
				],
				'trait'=>[
					'trate',
				],
				'tramcar'=>[
					'tramcer',
				],
				'trammel'=>[
					'tramnel',
				],
				'trampoline'=>[
					'trampolini',
				],
				'trampolinings'=>[
					'trampolinangs',
				],
				'trampolinists'=>[
					'trampolinasts',
				],
				'trance'=>[
					'trence',
				],
				'tranny'=>[
					'trany',
				],
				'tranquillity'=>[
					'tranquility',
				],
				'transactinide'=>[
					'transactinade',
				],
				'transalpine'=>[
					'transalpini',
				],
				'transaminase'=>[
					'transaminise',
				],
				'transaminases'=>[
					'transaminises',
				],
				'transamination'=>[
					'transaminition',
				],
				'transaminations'=>[
					'transaminitions',
				],
				'transatlantic'=>[
					'transatlentic',
				],
				'transceiver'=>[
					'tranceiver',
					'trancseiver',
					'transciever',
					'transeiver',
				],
				'transceivers'=>[
					'transcievers',
				],
				'transcend'=>[
					'trancend',
					'transend',
					'trancsend',
				],
				'transcended'=>[
					'trancended',
				],
				'transcendence'=>[
					'transcendance',
				],
				'transcendencies'=>[
					'trancendencies',
					'trancsendencies',
					'transendencies',
				],
				'transcendency'=>[
					'transcendensy',
				],
				'transcendent'=>[
					'trancendent',
					'transcendant',
					'trancsendent',
					'transendent',
				],
				'transcendental'=>[
					'trancendental',
					'transcendentational',
					'trancsendental',
					'transcendantal',
					'transendental',
				],
				'transcendently'=>[
					'transcendantly',
					'transcendentally',
					'transcendentaly',
					'transcendentely',
					'transcendentlly',
				],
				'transcending'=>[
					'trancending',
					'transending',
				],
				'transcribe'=>[
					'trancribe',
					'trancsribe',
					'transribe',
				],
				'transcribing'=>[
					'transcripting',
				],
				'transcript'=>[
					'trancript',
					'trancsript',
					'transript',
				],
				'transcriptase'=>[
					'trancriptase',
					'trancsriptase',
					'transriptase',
				],
				'transcription'=>[
					'trancription',
					'trancsription',
					'transription',
				],
				'transcriptional'=>[
					'trancriptional',
					'trancsriptional',
					'transriptional',
				],
				'transcutaneous'=>[
					'trancsutaneous',
					'trancutaneous',
					'transutaneous',
				],
				'transductant'=>[
					'transductent',
				],
				'transept'=>[
					'transcept',
				],
				'transfer'=>[
					'transferr',
				],
				'transference'=>[
					'transferance',
				],
				'transferrable'=>[
					'transferrible',
				],
				'transferred'=>[
					'transfered',
				],
				'transferrin'=>[
					'transferin',
				],
				'transferring'=>[
					'transfering',
				],
				'transfinite'=>[
					'transfinate',
				],
				'transform'=>[
					'tranform',
				],
				'transformable'=>[
					'transformible',
				],
				'transformation'=>[
					'transformaton',
					'trasformation',
				],
				'transformed'=>[
					'tranformed',
					'trasformed',
				],
				'transfusible'=>[
					'transfuisble',
					'transfusable',
				],
				'transfusing'=>[
					'transfuisng',
				],
				'transfusion'=>[
					'transfuison',
				],
				'transfusional'=>[
					'transfuisonal',
				],
				'transfusions'=>[
					'transfuisons',
				],
				'transgender'=>[
					'transgneder',
				],
				'transgress'=>[
					'transgres',
				],
				'transgression'=>[
					'transgresion',
				],
				'transgressive'=>[
					'transgresive',
				],
				'transhumance'=>[
					'transhumence',
				],
				'transience'=>[
					'transeince',
					'transiance',
					'transince',
				],
				'transiency'=>[
					'transiensy',
				],
				'transient'=>[
					'transeint',
					'transiant',
					'transint',
				],
				'transilluminate'=>[
					'transilluminite',
				],
				'transistor'=>[
					'transister',
				],
				'transition'=>[
					'transistion',
				],
				'transitional'=>[
					'transitionary',
				],
				'transitionally'=>[
					'transitionalally',
					'transitionalaly',
					'transitionalely',
					'transitionallly',
				],
				'transitively'=>[
					'transitivly',
				],
				'translation'=>[
					'trnaslation',
				],
				'translator'=>[
					'translater',
				],
				'translucence'=>[
					'translucance',
				],
				'translucency'=>[
					'translucensy',
				],
				'translucent'=>[
					'transluscent',
					'translucant',
				],
				'translucently'=>[
					'translucentally',
					'translucentaly',
					'translucentely',
					'translucentlly',
				],
				'transmarine'=>[
					'transmarini',
				],
				'transmembrane'=>[
					'transmbrane',
				],
				'transmissible'=>[
					'transmissable',
					'transmisible',
				],
				'transmission'=>[
					'transmision',
				],
				'transmissivity'=>[
					'transmisivity',
				],
				'transmissometer'=>[
					'transmisometer',
				],
				'transmit'=>[
					'transmitt',
				],
				'transmittance'=>[
					'transmittence',
				],
				'transmitted'=>[
					'transmited',
				],
				'transmitter'=>[
					'transmiter',
				],
				'transmitting'=>[
					'transmiting',
				],
				'transoceanic'=>[
					'transocenic',
				],
				'transparence'=>[
					'transparance',
				],
				'transparences'=>[
					'transperences',
				],
				'transparencies'=>[
					'transperencies',
				],
				'transparency'=>[
					'transparensy',
					'transperency',
				],
				'transparent'=>[
					'transparant',
					'transperent',
				],
				'transparentize'=>[
					'transperentize',
				],
				'transparentized'=>[
					'transperentized',
				],
				'transparentizes'=>[
					'transperentizes',
				],
				'transparently'=>[
					'transperently',
				],
				'transparentness'=>[
					'transperentness',
				],
				'transpicuous'=>[
					'transpicous',
				],
				'transpierce'=>[
					'transpeirce',
					'transpirce',
				],
				'transplacental'=>[
					'transplacantal',
				],
				'transplant'=>[
					'transplent',
				],
				'transplantable'=>[
					'transplantible',
				],
				'transpolar'=>[
					'transpoler',
				],
				'transpontine'=>[
					'transpontini',
				],
				'transportable'=>[
					'transportible',
				],
				'transportation'=>[
					'transporation',
					'transpotation',
				],
				'transported'=>[
					'tranpsorted',
				],
				'transports'=>[
					'tranpsorts',
				],
				'transsexual'=>[
					'transexual',
					'transsexaul',
				],
				'transsexualism'=>[
					'transsexaulism',
				],
				'transsexualisms'=>[
					'transsexaulisms',
				],
				'transsexuality'=>[
					'transsexaulity',
				],
				'transshipping'=>[
					'transshiping',
				],
				'transvaluating'=>[
					'transvalauting',
				],
				'transvaluation'=>[
					'transvalaution',
				],
				'transvaluations'=>[
					'transvalautions',
				],
				'trapper'=>[
					'traper',
				],
				'trapping'=>[
					'traping',
				],
				'trass'=>[
					'tras',
				],
				'travel'=>[
					'travei',
					'travel travel',
					'travel travel travel',
				],
				'traveled'=>[
					'travelled',
				],
				'traveler'=>[
					'traveller',
				],
				'traveling'=>[
					'travelling',
				],
				'travels'=>[
					'traveis',
				],
				'travertine'=>[
					'travertini',
				],
				'treacherous'=>[
					'trecherous',
				],
				'treachery'=>[
					'trechery',
				],
				'treacly'=>[
					'treacally',
					'treacaly',
					'treacely',
					'treaclly',
				],
				'tread'=>[
					'tred',
				],
				'treadmill'=>[
					'treadmil',
					'tredmill',
				],
				'treason'=>[
					'treson',
				],
				'treasonable'=>[
					'treasonible',
					'tresonable',
				],
				'treasonous'=>[
					'tresonous',
				],
				'treasure'=>[
					'tresure',
				],
				'treasurer'=>[
					'tresurer',
				],
				'treasury'=>[
					'tresury',
				],
				'treat'=>[
					'tret',
				],
				'treatable'=>[
					'treatible',
					'tretable',
				],
				'treatise'=>[
					'tretise',
				],
				'treatment'=>[
					'treatement',
					'treatmant',
					'tretment',
				],
				'treaty'=>[
					'trety',
				],
				'trebbianos'=>[
					'trebianos',
				],
				'tredecillion'=>[
					'tredecilion',
				],
				'tree'=>[
					'tree tree',
					'tree tree tree',
					'treee',
				],
				'treehopper'=>[
					'treehoper',
				],
				'trefah'=>[
					'trefa',
				],
				'treillage'=>[
					'triellage',
				],
				'trellis'=>[
					'trelis',
				],
				'tremolo'=>[
					'tremelo',
				],
				'tremor'=>[
					'tremour',
				],
				'tremorous'=>[
					'tremourous',
				],
				'tremors'=>[
					'tremours',
				],
				'trenchancy'=>[
					'trenchansy',
				],
				'trenchant'=>[
					'trenchent',
				],
				'trephination'=>[
					'trephinition',
				],
				'trephinations'=>[
					'trephinitions',
				],
				'trepidant'=>[
					'trepident',
				],
				'trespass'=>[
					'tresspass',
					'trespas',
				],
				'tress'=>[
					'tres',
				],
				'tressy'=>[
					'trescy',
				],
				'trestle'=>[
					'tresle',
				],
				'trevally'=>[
					'trevalally',
					'trevalaly',
					'trevalely',
					'trevallly',
				],
				'triable'=>[
					'triible',
				],
				'triangle'=>[
					'traingle',
					'triangle triangle',
					'triangle triangle triangle',
				],
				'triangular'=>[
					'trianguler',
				],
				'triathlon'=>[
					'triathalon',
				],
				'triazine'=>[
					'triazini',
				],
				'tribunary'=>[
					'tribunery',
				],
				'tribune'=>[
					'tribime',
				],
				'tributary'=>[
					'tributery',
				],
				'trichina'=>[
					'trichini',
				],
				'trichinae'=>[
					'trichinie',
				],
				'trichinal'=>[
					'trichinil',
				],
				'trichinas'=>[
					'trichinis',
				],
				'trichinize'=>[
					'trichinaze',
				],
				'trichotomously'=>[
					'trichotomousally',
					'trichotomousaly',
					'trichotomousely',
					'trichotomouslly',
				],
				'tricksy'=>[
					'trickcy',
				],
				'triclinic'=>[
					'triclinac',
				],
				'triclinium'=>[
					'triclinaum',
				],
				'trident'=>[
					'tridant',
				],
				'tridental'=>[
					'tridantal',
				],
				'tridentine'=>[
					'tndentme',
				],
				'tridents'=>[
					'tridants',
				],
				'tried'=>[
					'treid',
					'tryed',
					'trid',
				],
				'triennial'=>[
					'treinnial',
					'trienial',
					'trinnial',
				],
				'triennium'=>[
					'trienium',
				],
				'trier'=>[
					'treir',
					'trir',
				],
				'tries'=>[
					'treis',
					'trys',
					'tris',
				],
				'trifluoperazine'=>[
					'trifloperazine',
					'trifluoperazini',
				],
				'trigeminal'=>[
					'trigeminil',
				],
				'trigger'=>[
					'triger',
				],
				'triggerfish'=>[
					'trigerfish',
				],
				'triggerfishes'=>[
					'trigerfishes',
				],
				'triggering'=>[
					'trigering',
				],
				'triggerman'=>[
					'trigerman',
				],
				'triggermen'=>[
					'trigermen',
				],
				'triggers'=>[
					'trigers',
				],
				'trigging'=>[
					'triging',
				],
				'trilinear'=>[
					'trilineer',
					'triliniar',
				],
				'trilingual'=>[
					'trilingaul',
				],
				'trill'=>[
					'tril',
				],
				'trillion'=>[
					'trilion',
				],
				'trillium'=>[
					'trilium',
				],
				'trilogy'=>[
					'triology',
				],
				'trimmer'=>[
					'trimner',
				],
				'trimming'=>[
					'trimning',
				],
				'trimonthly'=>[
					'trimonthally',
					'trimonthaly',
					'trimonthely',
					'trimonthlly',
				],
				'trimorph'=>[
					'trimourph',
				],
				'trimorphic'=>[
					'trimourphic',
				],
				'trimorphs'=>[
					'trimourphs',
				],
				'trinal'=>[
					'trinil',
				],
				'trinary'=>[
					'trinery',
					'triniry',
				],
				'trine'=>[
					'trini',
				],
				'trining'=>[
					'trinang',
				],
				'trinitarian'=>[
					'trinitaran',
				],
				'trinitrotoluene'=>[
					'trinatrotoluene',
				],
				'trinity'=>[
					'trinaty',
				],
				'trinocular'=>[
					'trinoculer',
				],
				'trip'=>[
					'trip trip',
					'trip trip trip',
				],
				'tripartite'=>[
					'tripertite',
				],
				'tripinnate'=>[
					'tripinate',
				],
				'tripinnately'=>[
					'tripinnatly',
				],
				'triple'=>[
					'tripple',
				],
				'triply'=>[
					'tripally',
					'tripaly',
					'tripely',
					'triplly',
				],
				'tripper'=>[
					'triper',
				],
				'trippet'=>[
					'tripet',
				],
				'tripping'=>[
					'triping',
				],
				'trippy'=>[
					'tripy',
				],
				'trisaccharide'=>[
					'trisacharide',
				],
				'trisaccharides'=>[
					'trisacharides',
				],
				'trisoctahedra'=>[
					'trisoctaedra',
				],
				'trisoctahedron'=>[
					'trisoctaedron',
				],
				'trisoctahedrons'=>[
					'trisoctaedrons',
				],
				'tritely'=>[
					'trately',
					'tritly',
				],
				'tritheism'=>[
					'trithiesm',
				],
				'tritheistical'=>[
					'trithiestical',
				],
				'triumphant'=>[
					'triumphent',
				],
				'trivia'=>[
					'triva',
				],
				'triweekly'=>[
					'triweekally',
					'triweekaly',
					'triweekely',
					'triweeklly',
				],
				'trocar'=>[
					'trocer',
				],
				'trochanter'=>[
					'trochenter',
				],
				'trochlear'=>[
					'trochleer',
				],
				'trod'=>[
					'treaded',
				],
				'trois nouvelles études'=>[
					'trois nouvelles etudes',
				],
				'trois-rivières'=>[
					'trois-rivieres',
				],
				'troll'=>[
					'trol',
				],
				'trolley'=>[
					'troley',
				],
				'trolly'=>[
					'trolally',
					'trolaly',
					'trolely',
					'trollly',
				],
				'trommel'=>[
					'tromnel',
				],
				'trophallaxis'=>[
					'trophalaxis',
				],
				'tropocollagen'=>[
					'tropocolagen',
				],
				'trotsky'=>[
					'trotksy',
					'trotzky',
				],
				'trotskyism'=>[
					'trotzkyism',
				],
				'trotskyist'=>[
					'trotzkyist',
				],
				'troubadour'=>[
					'troubador',
				],
				'trouble'=>[
					'trobule',
					'trouble trouble',
					'trouble trouble trouble',
				],
				'troublesomely'=>[
					'troublesomly',
				],
				'troupes'=>[
					'troups',
				],
				'trouveur'=>[
					'trouver',
				],
				'truancy'=>[
					'trauncy',
					'truansy',
				],
				'truant'=>[
					'traunt',
					'truent',
				],
				'truanted'=>[
					'traunted',
				],
				'truantly'=>[
					'trauntly',
				],
				'truantry'=>[
					'trauntry',
				],
				'truck'=>[
					'truck truck',
					'truck truck truck',
				],
				'truculence'=>[
					'truculance',
				],
				'truculency'=>[
					'truculensy',
				],
				'true'=>[
					'true true',
					'true true true',
				],
				'truepenny'=>[
					'truepeny',
				],
				'trull'=>[
					'trul',
				],
				'truly'=>[
					'truely',
					'truley',
					'trually',
					'trualy',
					'trully',
				],
				'trunk'=>[
					'turnk',
				],
				'trunnel'=>[
					'trunel',
				],
				'trunnion'=>[
					'trunion',
				],
				'truss'=>[
					'trus',
				],
				'trustworthiness'=>[
					'trustworthyness',
					'trustworthiniss',
				],
				'trustworthy'=>[
					'trustwortby',
				],
				'try'=>[
					'try try',
					'try try try',
				],
				'tsar'=>[
					'tser',
				],
				'tsarina'=>[
					'tsarini',
				],
				'tsarinas'=>[
					'tsarinis',
				],
				'tsimmes'=>[
					'tsimnes',
				],
				'tsunami'=>[
					'tsuname',
				],
				'tuatara'=>[
					'tautara',
				],
				'tuataras'=>[
					'tautaras',
				],
				'tuateras'=>[
					'tauteras',
				],
				'tubbinesses'=>[
					'tubinesses',
				],
				'tubby'=>[
					'tuby',
				],
				'tube'=>[
					'tube tube',
					'tube tube tube',
				],
				'tubercular'=>[
					'tuberculer',
				],
				'tubocurarine'=>[
					'tubocurarini',
				],
				'tubular'=>[
					'tubuler',
				],
				'tuckahoe'=>[
					'tuckaoe',
				],
				'tuckahoes'=>[
					'tuckaoes',
				],
				'tucson'=>[
					'tuscon',
				],
				'tuesday'=>[
					'teusday',
				],
				'tugged'=>[
					'tuged',
				],
				'tugger'=>[
					'tuger',
				],
				'tulle'=>[
					'tule',
				],
				'tumescence'=>[
					'tumecence',
					'tumecsence',
					'tumescance',
					'tumesence',
				],
				'tumidly'=>[
					'tumidally',
					'tumidaly',
					'tumidely',
					'tumidlly',
				],
				'tummler'=>[
					'tumnler',
				],
				'tummy'=>[
					'tumny',
				],
				'tumoral'=>[
					'tumoural',
				],
				'tumorigeneses'=>[
					'tumourigeneses',
				],
				'tumorigenesis'=>[
					'tumourigenesis',
				],
				'tumorigenic'=>[
					'tumourigenic',
				],
				'tumorigenicity'=>[
					'tumourigenicity',
				],
				'tumorlike'=>[
					'tumourlike',
				],
				'tumorous'=>[
					'tumourous',
				],
				'tumors'=>[
					'tumours',
				],
				'tumular'=>[
					'tumuler',
				],
				'tumultuary'=>[
					'tumultaury',
					'tumultuery',
				],
				'tumultuous'=>[
					'tumultous',
				],
				'tumultuously'=>[
					'tumultously',
				],
				'tumultuousness'=>[
					'tumultousness',
				],
				'tunable'=>[
					'tunible',
				],
				'tuneable'=>[
					'tuneible',
				],
				'tunefully'=>[
					'tunefulally',
					'tunefulaly',
					'tunefulely',
					'tunefullly',
				],
				'tunisian-occupied'=>[
					'tunisian occupied',
				],
				'tunnel'=>[
					'tunel',
				],
				'tunnel-disease'=>[
					'tunneldisease',
				],
				'tunneled'=>[
					'tunnelled',
				],
				'tunneling'=>[
					'tunnelling',
					'tuneling',
				],
				'tunny'=>[
					'tuny',
				],
				'tuppence'=>[
					'tupence',
					'tuppance',
				],
				'tuppenny'=>[
					'tupenny',
					'tuppeny',
				],
				'turbary'=>[
					'turbery',
				],
				'turbellarian'=>[
					'turbelarian',
					'turbellaran',
				],
				'turbinal'=>[
					'turbinil',
				],
				'turbinals'=>[
					'turbinils',
				],
				'turbinate'=>[
					'turbinite',
				],
				'turbinated'=>[
					'turbinited',
				],
				'turbinates'=>[
					'turbinites',
				],
				'turbine'=>[
					'turbini',
				],
				'turbulence'=>[
					'turbulance',
				],
				'turbulency'=>[
					'turbulensy',
				],
				'turbulent'=>[
					'turbulant',
				],
				'turgency'=>[
					'turgensy',
				],
				'turgescence'=>[
					'turgescance',
				],
				'turkey'=>[
					'turky',
				],
				'turkeys'=>[
					'turkies',
				],
				'turkish-occupied'=>[
					'turkish occupied',
				],
				'turn'=>[
					'turn turn',
					'turn turn turn',
				],
				'turnable'=>[
					'turnible',
				],
				'turns'=>[
					'turnes',
				],
				'turnstile'=>[
					'turnstyle',
				],
				'turntable'=>[
					'turntible',
				],
				'turnverein'=>[
					'turnverien',
				],
				'turpentine'=>[
					'turpentini',
				],
				'turquois'=>[
					'turqois',
				],
				'turquoise'=>[
					'turqoise',
				],
				'turquoises'=>[
					'turqoises',
				],
				'turret'=>[
					'turet',
				],
				'turreted'=>[
					'tureted',
				],
				'turtle'=>[
					'turle',
				],
				'turtles'=>[
					'turles',
				],
				'tusche'=>[
					'tuche',
					'tucshe',
					'tushe',
				],
				'tussah'=>[
					'tusah',
					'tussa',
				],
				'tussahs'=>[
					'tussas',
				],
				'tussar'=>[
					'tusser',
				],
				'tussis'=>[
					'tusis',
				],
				'tussle'=>[
					'tusle',
				],
				'tutelar'=>[
					'tuteler',
				],
				'tutelary'=>[
					'tutelery',
				],
				'tweak'=>[
					'twek',
				],
				'twelfth'=>[
					'twefth',
					'twelth',
					'twelveth',
				],
				'twelve years'=>[
					'twelve year',
				],
				'twenties'=>[
					'twentys',
				],
				'twentieth'=>[
					'twenteith',
					'twntieth',
					'twantieth',
					'twentith',
				],
				'twenty'=>[
					'twenty twenty',
					'twenty twenty twenty',
					'twanty',
				],
				'twenty-two'=>[
					'twentytwo',
				],
				'twiggier'=>[
					'twigier',
				],
				'twigging'=>[
					'twiging',
				],
				'twiggy'=>[
					'twigy',
				],
				'twill'=>[
					'twil',
				],
				'twinberry'=>[
					'twinbery',
				],
				'twine'=>[
					'twini',
				],
				'twinier'=>[
					'twinaer',
				],
				'twinight'=>[
					'twinaght',
				],
				'twining'=>[
					'twinang',
				],
				'twinkie'=>[
					'twinkei',
					'twinki',
				],
				'twinned'=>[
					'twined',
				],
				'twinning'=>[
					'twining',
				],
				'twittery'=>[
					'twittary',
				],
				'two'=>[
					'two two',
					'two two two',
				],
				'two-disc album'=>[
					'two disc album',
				],
				'twopence'=>[
					'twopance',
				],
				'twopenny'=>[
					'twopeny',
				],
				'typable'=>[
					'typible',
				],
				'type'=>[
					'type type',
					'type type type',
				],
				'type-cast'=>[
					'type-casted',
				],
				'typescript'=>[
					'typecript',
					'typecsript',
					'typesript',
				],
				'typical'=>[
					'tipical',
					'typcial',
				],
				'typically'=>[
					'typicaly',
				],
				'typps'=>[
					'typs',
				],
				'tyrannical'=>[
					'tyranical',
				],
				'tyrannicalness'=>[
					'tyranicalness',
				],
				'tyrannicide'=>[
					'tyranicide',
				],
				'tyrannies'=>[
					'tyranies',
				],
				'tyrannize'=>[
					'tyranize',
				],
				'tyrannosaur'=>[
					'tyranosaur',
				],
				'tyrannosaurus'=>[
					'tyranosaurus',
				],
				'tyrannosauruses'=>[
					'tyranosauruses',
				],
				'tyrannous'=>[
					'tyranous',
				],
				'tyranny'=>[
					'tyrany',
					'tyrrany',
				],
				'tyrant'=>[
					'tyrannt',
					'tyrent',
				],
				'tyrosinase'=>[
					'tyrosinise',
				],
				'tyrosine'=>[
					'tyrosini',
				],
				'tzar'=>[
					'tzer',
				],
				'tzarina'=>[
					'tzarini',
				],
				'tzarinas'=>[
					'tzarinis',
				],
				'tzimmes'=>[
					'tzimnes',
				],
				'táimse im'=>[
					'taimse im',
				],
			];
		}
	}

?>