<?php
		
		/* UTF-8 TEST
		
			中文汉字漢字
		
		*/
				
				/* EnglishMisspellingsWords_B
					
					Class for English-Misspellings for all words beginning with : B.
					
				*/

	class EnglishMisspellingsWords_B {
			/* __construct($args)
			
				Constructor.
				
				Nothing to do here.
			
			*/
			
		public function __construct($args) {
			return TRUE;
		}
		
			/* EnglishMisspellingsWords()
			
				List of English misspellings for words starting with : B.
			
			*/

		public function EnglishMisspellingsWords() {
			return [
				'babbitries'=>[
					'babitries',
				],
				'babbitry'=>[
					'babitry',
				],
				'babbitt'=>[
					'babitt',
				],
				'babbitted'=>[
					'babitted',
				],
				'babbitting'=>[
					'babitting',
				],
				'babbittries'=>[
					'babittries',
				],
				'babbittry'=>[
					'babittry',
				],
				'babbitts'=>[
					'babitts',
				],
				'babble'=>[
					'bable',
				],
				'babbled'=>[
					'babled',
				],
				'babblement'=>[
					'bablement',
				],
				'babblements'=>[
					'bablements',
				],
				'babbler'=>[
					'babler',
				],
				'babblers'=>[
					'bablers',
				],
				'babbles'=>[
					'bables',
				],
				'babbling'=>[
					'babling',
				],
				'babblings'=>[
					'bablings',
				],
				'babies'=>[
					'babys',
				],
				'baby'=>[
					'baby baby',
					'baby baby baby',
				],
				'bacca'=>[
					'baca',
				],
				'baccae'=>[
					'bacae',
				],
				'baccalaureate'=>[
					'bacalaureate',
					'baccalaurete',
				],
				'baccalaureates'=>[
					'bacalaureates',
					'baccalauretes',
				],
				'baccara'=>[
					'bacara',
				],
				'baccaras'=>[
					'bacaras',
				],
				'baccarat'=>[
					'bacarat',
				],
				'baccarats'=>[
					'bacarats',
				],
				'baccate'=>[
					'bacate',
				],
				'baccated'=>[
					'bacated',
				],
				'bacchanal'=>[
					'bachanal',
				],
				'bacchanalia'=>[
					'bachanalia',
				],
				'bacchanalian'=>[
					'bacchanalan',
					'bachanalian',
				],
				'bacchanalians'=>[
					'bachanalians',
				],
				'bacchanals'=>[
					'bachanals',
				],
				'bacchant'=>[
					'bachant',
				],
				'bacchante'=>[
					'bachante',
				],
				'bacchantes'=>[
					'bachantes',
				],
				'bacchants'=>[
					'bachants',
				],
				'bacchic'=>[
					'bachic',
				],
				'bacchii'=>[
					'bachii',
				],
				'bacchius'=>[
					'bachius',
				],
				'bacciform'=>[
					'baciform',
				],
				'bacillar'=>[
					'baciller',
				],
				'bacillary'=>[
					'bacillery',
				],
				'bacillus'=>[
					'bacilus',
				],
				'back'=>[
					'back back',
					'back back back',
					'bakc',
					'bcak',
				],
				'backbreaking'=>[
					'backbreking',
				],
				'backdropped'=>[
					'backdroped',
				],
				'backdropping'=>[
					'backdroping',
				],
				'backetfuls'=>[
					'bucketsful',
				],
				'backfield'=>[
					'backfeild',
					'backfild',
				],
				'backflipped'=>[
					'backfliped',
				],
				'backflipping'=>[
					'backfliping',
				],
				'backgammon'=>[
					'backgamnon',
				],
				'background'=>[
					'backround',
				],
				'backhandedly'=>[
					'backhandedally',
					'backhandedaly',
					'backhandedely',
					'backhandedlly',
				],
				'backlogged'=>[
					'backloged',
				],
				'backlogging'=>[
					'backloging',
				],
				'backpedal'=>[
					'backpeddle',
				],
				'backpedalling'=>[
					'backpedaling',
				],
				'backscatter'=>[
					'backcatter',
					'backcsatter',
					'backsatter',
				],
				'backscattered'=>[
					'backcattered',
					'backcsattered',
					'backsattered',
				],
				'backscattering'=>[
					'backcattering',
					'backcsattering',
					'backsattering',
				],
				'backscatterings'=>[
					'backcatterings',
					'backcsatterings',
					'backsatterings',
				],
				'backslapped'=>[
					'backslaped',
				],
				'backslapper'=>[
					'backslaper',
				],
				'backslappers'=>[
					'backslapers',
				],
				'backslapping'=>[
					'backslaping',
				],
				'backstabbed'=>[
					'backstabed',
				],
				'backstabber'=>[
					'backstaber',
				],
				'backstabbers'=>[
					'backstabers',
				],
				'backstabbing'=>[
					'backstabing',
				],
				'backstabbings'=>[
					'backstabings',
				],
				'backstopped'=>[
					'backstoped',
				],
				'backstopping'=>[
					'backstoping',
				],
				'backwoodsy'=>[
					'backwoodcy',
				],
				'bactericidally'=>[
					'bactericidaly',
				],
				'bacteriologies'=>[
					'bacteriologeis',
					'bacteriologis',
				],
				'bacteriophagies'=>[
					'bacteriophageis',
					'bacteriophagis',
				],
				'bad'=>[
					'bad bad',
					'bad bad bad',
				],
				'bad begun'=>[
					'had began',
				],
				'badass'=>[
					'badas',
				],
				'baddie'=>[
					'baddei',
					'baddi',
				],
				'badinage'=>[
					'badinige',
				],
				'badly'=>[
					'badally',
					'badaly',
					'badlly',
				],
				'badminton'=>[
					'badmiton',
					'badmitton',
				],
				'baffled'=>[
					'baffeld',
					'baffeled',
				],
				'baggage'=>[
					'bagage',
				],
				'bagginess'=>[
					'baginess',
				],
				'bagginesses'=>[
					'baginesses',
				],
				'bagging'=>[
					'baging',
				],
				'baggy'=>[
					'bagy',
				],
				'baghdad'=>[
					'bagdad',
					'baghad',
				],
				'bahadur'=>[
					'baadur',
				],
				'bahadurs'=>[
					'baadurs',
				],
				'bahraini-occupied'=>[
					'bahraini occupied',
				],
				'bahts'=>[
					'bats',
				],
				'bahuvrihi'=>[
					'bauvrihi',
				],
				'bahuvrihis'=>[
					'bauvrihis',
				],
				'bailable'=>[
					'bailible',
				],
				'bailie'=>[
					'bailei',
					'baili',
				],
				'bailout'=>[
					'baleout',
				],
				'bakeapple'=>[
					'bakeaple',
				],
				'balance'=>[
					'balence',
				],
				'balances'=>[
					'balanzes',
				],
				'balbriggan'=>[
					'balbrigan',
				],
				'balbriggans'=>[
					'balbrigans',
				],
				'balefully'=>[
					'balefulally',
					'balefulaly',
					'balefulely',
					'balefullly',
				],
				'balk'=>[
					'bauk',
				],
				'ball'=>[
					'bal',
					'ball ball',
					'ball ball ball',
				],
				'ballad'=>[
					'balad',
				],
				'ballast'=>[
					'balast',
					'ballest',
				],
				'ballcarrier'=>[
					'ballcarier',
				],
				'ballerina'=>[
					'balerina',
					'ballerini',
				],
				'ballet'=>[
					'balet',
				],
				'balletomane'=>[
					'baletomane',
				],
				'ballistic'=>[
					'balistic',
				],
				'ballistics'=>[
					'balistics',
				],
				'balloon'=>[
					'baloon',
				],
				'ballot'=>[
					'balot',
				],
				'ballpark'=>[
					'ballperk',
					'balpark',
				],
				'ballparks'=>[
					'ballperks',
				],
				'ballplayer'=>[
					'balplayer',
				],
				'ballpoint'=>[
					'balpoint',
				],
				'ballroom'=>[
					'balroom',
				],
				'ballsy'=>[
					'ballcy',
				],
				'bally'=>[
					'balally',
					'balaly',
					'ballly',
					'baly',
				],
				'ballyloughlin'=>[
					'baliloughlin',
				],
				'ballyragged'=>[
					'ballyraged',
				],
				'ballyragging'=>[
					'ballyraging',
				],
				'balmoral'=>[
					'balmoural',
				],
				'balmorals'=>[
					'balmourals',
				],
				'baloy'=>[
					'valoy',
				],
				'baltimore'=>[
					'baltimor',
				],
				'bambini'=>[
					'bambina',
				],
				'bamboozlements'=>[
					'bamboozlemants',
				],
				'bammed'=>[
					'bamned',
				],
				'banana'=>[
					'bannana',
				],
				'banausic'=>[
					'banauisc',
				],
				'band'=>[
					'band band',
					'band band band',
				],
				'band\'s style'=>[
					'bands style',
				],
				'bandanna'=>[
					'bandana',
				],
				'banderillero'=>[
					'banderilero',
				],
				'bandleader'=>[
					'bandleder',
				],
				'bandwidth'=>[
					'bandwith',
				],
				'baneberries'=>[
					'baneberies',
				],
				'baneberry'=>[
					'banebery',
				],
				'banefully'=>[
					'banefulally',
					'banefulaly',
					'banefulely',
					'banefullly',
				],
				'bangladeshi-occupied'=>[
					'bangladeshi occupied',
				],
				'banian'=>[
					'banan',
				],
				'bank'=>[
					'bank bank',
					'bank bank bank',
				],
				'bankable'=>[
					'bankible',
				],
				'banknote'=>[
					'bankote',
				],
				'banknotes'=>[
					'bankotes',
				],
				'bankruptcy'=>[
					'backruptcy',
					'bankrupcy',
					'bankruptsy',
				],
				'bannable'=>[
					'bannible',
				],
				'banner'=>[
					'baner',
				],
				'banneret'=>[
					'baneret',
				],
				'bannerette'=>[
					'banerette',
				],
				'bannerol'=>[
					'banerol',
				],
				'bannister'=>[
					'banister',
				],
				'bannock'=>[
					'banock',
				],
				'banns'=>[
					'bans',
				],
				'bantam'=>[
					'bentam',
				],
				'bantamweight'=>[
					'bantamwieght',
					'bentamweight',
				],
				'bantamweights'=>[
					'bantamwieghts',
					'bentamweights',
				],
				'banter'=>[
					'benter',
				],
				'banty'=>[
					'benty',
				],
				'baptistery'=>[
					'baptistary',
				],
				'bar'=>[
					'bar bar',
					'bar bar bar',
				],
				'barbadian-occupied'=>[
					'barbadian occupied',
				],
				'barbarian'=>[
					'barbaran',
				],
				'barbarousnesses'=>[
					'barbarousneses',
				],
				'barberry'=>[
					'barbery',
				],
				'barbie'=>[
					'barbei',
					'barbi',
				],
				'barbiturate'=>[
					'barbituate',
				],
				'barbiturates'=>[
					'barbituates',
				],
				'bared'=>[
					'beared',
				],
				'barefacednesses'=>[
					'barefacedneses',
				],
				'barely'=>[
					'bareally',
					'barealy',
					'bareely',
					'barelly',
					'barly',
					'bearly',
				],
				'barfly'=>[
					'barfally',
					'barfaly',
					'barfely',
					'barflly',
				],
				'barn-like'=>[
					'barnlike',
				],
				'barometrically'=>[
					'barometricaly',
				],
				'baroness'=>[
					'barones',
				],
				'baronetcy'=>[
					'baronetsy',
				],
				'baroquely'=>[
					'baroquly',
				],
				'barquentine'=>[
					'barquentini',
				],
				'barrack'=>[
					'barack',
				],
				'barracoon'=>[
					'baracoon',
				],
				'barracouta'=>[
					'baracouta',
				],
				'barracoutas'=>[
					'baracoutas',
				],
				'barracuda'=>[
					'baracuda',
				],
				'barrage'=>[
					'barage',
				],
				'barramunda'=>[
					'baramunda',
				],
				'barramundas'=>[
					'baramundas',
				],
				'barramundis'=>[
					'baramundis',
				],
				'barranca'=>[
					'baranca',
				],
				'barrator'=>[
					'barator',
				],
				'barratry'=>[
					'baratry',
				],
				'barred'=>[
					'bared',
				],
				'barrel'=>[
					'barel',
				],
				'barrelful'=>[
					'barelful',
				],
				'barrelhead'=>[
					'barelhead',
				],
				'barrelheads'=>[
					'barelheads',
				],
				'barrelhouse'=>[
					'barelhouse',
				],
				'barren'=>[
					'baren',
				],
				'barrennesses'=>[
					'barrenesses',
				],
				'barres'=>[
					'bares',
				],
				'barrette'=>[
					'barette',
				],
				'barricade'=>[
					'baricade',
				],
				'barricades'=>[
					'baricades',
				],
				'barricading'=>[
					'baricading',
				],
				'barricadoed'=>[
					'baricadoed',
				],
				'barricadoes'=>[
					'baricadoes',
				],
				'barrier'=>[
					'barier',
					'barreir',
					'barrir',
				],
				'barring'=>[
					'baring',
				],
				'barrio'=>[
					'bario',
				],
				'barrister'=>[
					'barister',
				],
				'barroom'=>[
					'baroom',
				],
				'barrow'=>[
					'barow',
				],
				'barère'=>[
					'barere',
				],
				'bascule'=>[
					'bacsule',
					'bacule',
					'basule',
				],
				'base'=>[
					'base base',
					'base base base',
				],
				'baseball'=>[
					'basebal',
				],
				'baseless'=>[
					'baseles',
				],
				'basely'=>[
					'basly',
				],
				'basement'=>[
					'basemant',
				],
				'baserunnings'=>[
					'baserunings',
				],
				'basic'=>[
					'basic basic',
					'basic basic basic',
				],
				'basically'=>[
					'basicalally',
					'basicalaly',
					'basicalely',
					'basicallly',
					'basicaly',
					'basicly',
				],
				'basilar'=>[
					'basiler',
				],
				'basilary'=>[
					'basilery',
				],
				'basinal'=>[
					'basinil',
				],
				'basketball'=>[
					'basketbal',
				],
				'bass'=>[
					'bas',
				],
				'basset'=>[
					'baset',
				],
				'bassi'=>[
					'basi',
				],
				'bassinet'=>[
					'bassinit',
				],
				'bassist'=>[
					'basist',
				],
				'basso'=>[
					'baso',
				],
				'bassoon'=>[
					'basoon',
				],
				'bassy'=>[
					'bascy',
					'basy',
				],
				'bastille'=>[
					'bastile',
				],
				'bastinado'=>[
					'bastinido',
				],
				'bat'=>[
					'bat bat',
					'bat bat bat',
				],
				'batallion'=>[
					'batalian',
					'batalion',
					'batallian',
				],
				'batallions'=>[
					'batalians',
					'batalions',
					'batallians',
				],
				'batches'=>[
					'batchs',
				],
				'bathroom'=>[
					'bathrooom',
				],
				'bathymetrically'=>[
					'bathymetricaly',
				],
				'bathyscaphe'=>[
					'bathycaphe',
					'bathycsaphe',
					'bathysaphe',
				],
				'batrachian'=>[
					'batrachan',
				],
				'battened'=>[
					'battend',
				],
				'batterie'=>[
					'batterei',
					'batteri',
				],
				'battery'=>[
					'battary',
				],
				'battlefield'=>[
					'battlefeild',
					'battlefild',
				],
				'bauhinia'=>[
					'bauhinaa',
				],
				'bauhinias'=>[
					'bauhinaas',
				],
				'bauzá'=>[
					'bauza',
				],
				'bayberry'=>[
					'baybery',
				],
				'bayonets'=>[
					'bayonnettes',
				],
				'bazaar'=>[
					'baazar',
					'bazaer',
				],
				'bazar'=>[
					'bazer',
				],
				'be'=>[
					'be be',
					'be be be',
				],
				'beach'=>[
					'bech',
				],
				'beachcomber'=>[
					'bechcomber',
				],
				'beaches'=>[
					'beachs',
				],
				'beachfront'=>[
					'bechfront',
				],
				'beachhead'=>[
					'beachhed',
				],
				'beachwear'=>[
					'beachweer',
				],
				'beacon'=>[
					'becon',
				],
				'bead'=>[
					'bed',
				],
				'beady'=>[
					'bedy',
				],
				'beagle'=>[
					'begle',
				],
				'beak'=>[
					'bek',
				],
				'beaked'=>[
					'breaked',
				],
				'beam'=>[
					'bem',
				],
				'bean'=>[
					'ben',
				],
				'beanie'=>[
					'beanei',
					'beani',
					'benie',
				],
				'beano'=>[
					'beno',
				],
				'bear'=>[
					'bear bear',
					'bear bear bear',
					'ber',
				],
				'bearabilities'=>[
					'berabilities',
				],
				'bearable'=>[
					'bearible',
				],
				'bearberry'=>[
					'bearbery',
				],
				'beard'=>[
					'berd',
				],
				'beardednesses'=>[
					'berdednesses',
				],
				'bearer'=>[
					'berer',
				],
				'bearing'=>[
					'bering',
				],
				'bearishnesses'=>[
					'berishnesses',
				],
				'beast'=>[
					'beest',
				],
				'beastie'=>[
					'beastei',
					'beasti',
				],
				'beastlinesses'=>[
					'beastlinisses',
					'bestlinesses',
				],
				'beastly'=>[
					'beastally',
					'beastaly',
					'beastely',
					'beastlly',
				],
				'beat'=>[
					'beat beat',
					'beat beat beat',
					'beated',
					'bet',
				],
				'beaten'=>[
					'beten',
				],
				'beatification'=>[
					'betification',
				],
				'beatifications'=>[
					'betifications',
				],
				'beating'=>[
					'beting',
				],
				'beau'=>[
					'beu',
				],
				'beauteousness'=>[
					'beuteousness',
				],
				'beauteousnesses'=>[
					'beauteousneses',
					'beuteousnesses',
				],
				'beautician'=>[
					'beautican',
					'beutician',
				],
				'beautification'=>[
					'beutification',
				],
				'beautifications'=>[
					'beutifications',
				],
				'beautiful'=>[
					'beatiful',
					'beautifull',
					'beautyfull',
					'beutiful',
					'bueatiful',
				],
				'beautifullest'=>[
					'beutifullest',
				],
				'beautifully'=>[
					'beautifuly',
				],
				'beautifulness'=>[
					'beutifulness',
				],
				'beautifulnesses'=>[
					'beautifulneses',
					'beutifulnesses',
				],
				'beauty'=>[
					'beautiy',
					'beauty beauty',
					'beauty beauty beauty',
					'beuty',
				],
				'beaux'=>[
					'beux',
				],
				'beaver'=>[
					'bever',
				],
				'became'=>[
					'bacame',
					'beacame',
					'becamae',
					'becamed',
					'becomed',
				],
				'because'=>[
					'beacause',
					'beacuse',
					'beause',
					'becase',
					'becasue',
					'becouse',
					'becuase',
					'becuse',
				],
				'beccafico'=>[
					'becafico',
				],
				'beccaficos'=>[
					'becaficos',
				],
				'bechance'=>[
					'bechence',
				],
				'beclamor'=>[
					'beclamour',
				],
				'beclamoring'=>[
					'beclamouring',
				],
				'beclamors'=>[
					'beclamours',
				],
				'becloggedbeflagged'=>[
					'becloggedbeflaged',
				],
				'beclogging'=>[
					'becloging',
				],
				'become'=>[
					'bacome',
					'beceme',
				],
				'becoming'=>[
					'becomeing',
					'becomming',
				],
				'bed'=>[
					'bed bed',
					'bed bed bed',
				],
				'bedabble'=>[
					'bedable',
				],
				'bedabbled'=>[
					'bedabled',
				],
				'bedabbles'=>[
					'bedables',
				],
				'bedabbling'=>[
					'bedabling',
				],
				'bedarkened'=>[
					'bedarkend',
				],
				'beddable'=>[
					'beddible',
				],
				'bedeafened'=>[
					'bedeafend',
				],
				'bedimmed'=>[
					'bedimned',
				],
				'bedizened'=>[
					'bedizend',
				],
				'bedizenment'=>[
					'bedizement',
					'bedizenent',
				],
				'bedizenments'=>[
					'bedizements',
					'bedizenents',
				],
				'bedraggle'=>[
					'bedragle',
				],
				'bedraggled'=>[
					'bedragled',
				],
				'bedraggles'=>[
					'bedragles',
				],
				'bedraggling'=>[
					'bedragling',
				],
				'bedrugged'=>[
					'bedruged',
				],
				'bedrugging'=>[
					'bedruging',
				],
				'beeline'=>[
					'beelini',
				],
				'beelining'=>[
					'beelinang',
				],
				'been'=>[
					'beeen',
					'been been',
					'been been been',
				],
				'befall'=>[
					'befal',
				],
				'beflagging'=>[
					'beflaging',
				],
				'befogging'=>[
					'befoging',
				],
				'before'=>[
					'befoer',
					'befor',
					'before before',
					'before before before',
					'beofer',
					'beofre',
				],
				'befriend'=>[
					'befreind',
					'befrind',
				],
				'began'=>[
					'began began',
					'began began began',
				],
				'beggar'=>[
					'begar',
					'begger',
				],
				'beggardom'=>[
					'begardom',
				],
				'beggardoms'=>[
					'begardoms',
				],
				'beggaries'=>[
					'begaries',
				],
				'beggaring'=>[
					'begaring',
				],
				'beggarliness'=>[
					'begarliness',
				],
				'beggarlinesses'=>[
					'begarlinesses',
					'beggarlinisses',
				],
				'beggarly'=>[
					'begarly',
					'beggarally',
					'beggaraly',
					'beggarely',
					'beggarlly',
				],
				'beggarweed'=>[
					'begarweed',
				],
				'beggarweeds'=>[
					'begarweeds',
				],
				'beggary'=>[
					'begary',
					'beggery',
				],
				'begging'=>[
					'beggin',
				],
				'begin'=>[
					'begin begin',
					'begin begin begin',
					'beign',
				],
				'beginner'=>[
					'begginer',
					'beginer',
				],
				'beginning'=>[
					'beggining',
					'begginning',
					'begining',
					'beginnig',
				],
				'begins'=>[
					'beigns',
				],
				'beglamor'=>[
					'beglamour',
				],
				'beglamoring'=>[
					'beglamouring',
				],
				'beglamors'=>[
					'beglamours',
				],
				'begoggledbewiggingbraggiest'=>[
					'begoggledbewiggingbragiest',
				],
				'begorah'=>[
					'begora',
				],
				'begorra'=>[
					'begora',
				],
				'begorrah'=>[
					'begorra',
				],
				'begrimming'=>[
					'begrimning',
				],
				'beguine'=>[
					'beguini',
				],
				'behavior'=>[
					'behaivor',
					'behavour',
				],
				'behaviour'=>[
					'behaviur',
				],
				'behaviours'=>[
					'behaviurs',
				],
				'behind'=>[
					'behind behind',
					'behind behind behind',
					'behing',
				],
				'behoove'=>[
					'behove',
				],
				'beige'=>[
					'biege',
				],
				'beiges'=>[
					'bieges',
				],
				'beigne'=>[
					'biegne',
				],
				'beignet'=>[
					'biegnet',
				],
				'beigy'=>[
					'biegy',
				],
				'beijing'=>[
					'beijng',
					'bejing',
				],
				'being'=>[
					'beeing',
					'bieng',
				],
				'beings'=>[
					'biengs',
				],
				'beirut'=>[
					'beruit',
				],
				'bejabbers'=>[
					'bejabers',
				],
				'beknot'=>[
					'bekot',
				],
				'beknots'=>[
					'bekots',
				],
				'beknotted'=>[
					'bekotted',
				],
				'beknotting'=>[
					'bekotting',
				],
				'belarussian-occupied'=>[
					'belarussian occupied',
				],
				'beleaguered'=>[
					'beleagered',
					'beleagured',
				],
				'beleaguerment'=>[
					'beleguerment',
				],
				'beleaguerments'=>[
					'beleaguermants',
					'beleguerments',
				],
				'belgian-occupied'=>[
					'belgian occupied',
				],
				'belgium'=>[
					'belguim',
				],
				'belgrade'=>[
					'belgade',
				],
				'belie'=>[
					'belei',
					'beli',
				],
				'belief'=>[
					'beleif',
					'beleive',
					'belif',
				],
				'beliefs'=>[
					'beleives',
					'belives',
				],
				'believabilities'=>[
					'believabiliteis',
					'believabilitis',
				],
				'believable'=>[
					'beleivable',
					'believeable',
					'believible',
					'belivable',
				],
				'believe'=>[
					'beleave',
					'beleieve',
					'beleive',
					'believe believe',
					'believe believe believe',
					'belive',
				],
				'believed'=>[
					'beleieved',
					'beleived',
					'beleivedbeleives',
				],
				'believer'=>[
					'beliver',
				],
				'believers'=>[
					'beleivers',
				],
				'believes'=>[
					'beleives',
				],
				'believing'=>[
					'beleiving',
					'beliving',
				],
				'beliquor'=>[
					'beliqor',
				],
				'beliquored'=>[
					'beliqored',
				],
				'beliquoring'=>[
					'beliqoring',
				],
				'beliquors'=>[
					'beliqors',
				],
				'bell'=>[
					'bel',
					'bell bell',
					'bell bell bell',
				],
				'belladonna'=>[
					'beladonna',
					'belladona',
				],
				'belle'=>[
					'bele',
				],
				'belleville'=>[
					'bellevile',
				],
				'bellflower'=>[
					'belflower',
				],
				'bellicose'=>[
					'belicose',
				],
				'belligerence'=>[
					'beligerence',
					'belligerance',
				],
				'belligerencies'=>[
					'beligerencies',
					'belligerenceis',
					'belligerencis',
				],
				'belligerency'=>[
					'beligerency',
					'belligerensy',
				],
				'belligerent'=>[
					'beligerent',
					'belligerant',
				],
				'bellow'=>[
					'belllow',
				],
				'bellows'=>[
					'belows',
				],
				'bellwether'=>[
					'bell-wether',
					'bellweather',
					'belwether',
				],
				'belly'=>[
					'belally',
					'belaly',
					'bellly',
					'bely',
				],
				'belongingnesses'=>[
					'belongingneses',
				],
				'bemaddened'=>[
					'bemaddend',
				],
				'bemusing'=>[
					'bemuisng',
				],
				'ben'=>[
					'bne',
				],
				'bench'=>[
					'bencd',
				],
				'benches'=>[
					'benchs',
				],
				'beneath'=>[
					'beneth',
				],
				'benefactress'=>[
					'benefactres',
				],
				'beneficence'=>[
					'beneficance',
				],
				'beneficial'=>[
					'benefical',
					'benificial',
				],
				'beneficiary'=>[
					'beneficary',
					'beneficiery',
				],
				'benefit'=>[
					'benfit',
					'benifit',
					'bennefit',
				],
				'benefited'=>[
					'benefitted',
				],
				'benefits'=>[
					'benfits',
					'benifits',
				],
				'benevolence'=>[
					'benevolance',
				],
				'benevolent'=>[
					'benevolant',
				],
				'benevolentness'=>[
					'benevolantness',
				],
				'benghazi'=>[
					'bengahzi',
				],
				'benightednesses'=>[
					'benightedneses',
				],
				'benignancy'=>[
					'benignansy',
				],
				'benjamin'=>[
					'benj',
				],
				'benjamin péret'=>[
					'benjamin peret',
				],
				'benne'=>[
					'bene',
				],
				'bennet'=>[
					'benet',
				],
				'benni'=>[
					'beni',
				],
				'benny'=>[
					'beny',
				],
				'benny moré'=>[
					'benny more',
					'beny more',
					'beny moré',
				],
				'bent'=>[
					'bant',
				],
				'benthal'=>[
					'bental',
				],
				'benthos'=>[
					'banthos',
				],
				'bento'=>[
					'banto',
				],
				'bentos'=>[
					'bantos',
				],
				'bents'=>[
					'bants',
				],
				'benzanthracenes'=>[
					'benzenthracenes',
				],
				'benzocaine'=>[
					'benzocaini',
				],
				'benzodiazepine'=>[
					'benzodiazapine',
					'benzodiazepini',
				],
				'benzodiazepines'=>[
					'benzodiazapines',
					'benzodiazepinis',
				],
				'bequeathal'=>[
					'bequeatal',
				],
				'bereaved'=>[
					'bereved',
				],
				'bergamot'=>[
					'bergamont',
				],
				'beribboned'=>[
					'beriboned',
				],
				'berkhamsted'=>[
					'berkhamstead',
				],
				'berline'=>[
					'berlini',
				],
				'bernoulli'=>[
					'bernouilli',
				],
				'berried'=>[
					'beried',
				],
				'berry'=>[
					'bery',
				],
				'berserk'=>[
					'beserk',
				],
				'beryllium'=>[
					'berylium',
				],
				'bescreened'=>[
					'bescreend',
				],
				'beset'=>[
					'besetted',
				],
				'beside the'=>[
					'besidet he',
				],
				'besides'=>[
					'beised',
				],
				'besiege'=>[
					'beseige',
					'besige',
				],
				'besieged'=>[
					'beseiged',
				],
				'besmear'=>[
					'besmeer',
				],
				'bespousing'=>[
					'bespouisng',
				],
				'bessarabia'=>[
					'bassarabia',
					'basserabia',
				],
				'best'=>[
					'best best',
					'best best best',
				],
				'bestial'=>[
					'beastial',
				],
				'bestialities'=>[
					'beastialities',
				],
				'bestiality'=>[
					'beastiality',
				],
				'bestiary'=>[
					'bestiery',
				],
				'bestsellerdoms'=>[
					'bestselerdoms',
				],
				'betaine'=>[
					'betaini',
				],
				'betokened'=>[
					'betokend',
				],
				'betrayal'=>[
					'betrayel',
				],
				'betrayed'=>[
					'betrayeed',
				],
				'betrothal'=>[
					'betrotal',
				],
				'better'=>[
					'beter',
					'better better',
					'better better better',
				],
				'betterment'=>[
					'bettermant',
				],
				'between'=>[
					'beetween',
					'beetwen',
					'beteen',
					'bettween',
					'betweeen',
					'between between',
					'between between between',
					'betwen',
					'beween',
					'btw',
					'inbetween',
					'vetween',
				],
				'between its'=>[
					'between it\'s',
				],
				'betweennesses'=>[
					'betweenesses',
				],
				'beweary'=>[
					'beweery',
				],
				'bewigged'=>[
					'bewiged',
				],
				'bewilderedly'=>[
					'bewilderedally',
					'bewilderedaly',
					'bewilderedely',
					'bewilderedlly',
				],
				'bewilderment'=>[
					'bewildermant',
				],
				'bezant'=>[
					'bezent',
				],
				'bezoar'=>[
					'bezoer',
				],
				'bhutanese-occupied'=>[
					'bhutanese occupied',
				],
				'bialy'=>[
					'biaally',
					'biaaly',
					'bially',
				],
				'biannual'=>[
					'biannaul',
					'bianual',
				],
				'biased'=>[
					'baised',
					'biassed',
				],
				'bibb'=>[
					'bib',
				],
				'bibbed'=>[
					'bibed',
				],
				'bibber'=>[
					'biber',
				],
				'bibberies'=>[
					'biberies',
				],
				'bibbers'=>[
					'bibers',
				],
				'bibbery'=>[
					'bibery',
				],
				'bibbing'=>[
					'bibing',
				],
				'bibbs'=>[
					'bibs',
				],
				'bibliographies'=>[
					'bibliographeis',
					'bibliographis',
				],
				'bibliography'=>[
					'bibiliography',
					'bibilography',
					'biblography',
					'bilbliography',
				],
				'bibliotherapies'=>[
					'bibliotherapeis',
					'bibliotherapis',
				],
				'bicentenary'=>[
					'bicentenery',
				],
				'bicentennial'=>[
					'bicantennial',
					'bicentenial',
				],
				'bicentennials'=>[
					'bicentenials',
				],
				'biceps'=>[
					'bicep',
				],
				'biddable'=>[
					'biddible',
				],
				'bidental'=>[
					'bidantal',
				],
				'bidentate'=>[
					'bidantate',
				],
				'bidirectionally'=>[
					'bidirectionaly',
				],
				'bield'=>[
					'beild',
					'bild',
				],
				'biennale'=>[
					'beinnale',
					'bienale',
					'binnale',
				],
				'biennia'=>[
					'bienia',
				],
				'biennial'=>[
					'beinnial',
					'bienial',
					'binnial',
				],
				'biennium'=>[
					'beinnium',
					'bienium',
					'binnium',
				],
				'bier'=>[
					'beir',
				],
				'biers'=>[
					'beirs',
					'birs',
				],
				'bifarious'=>[
					'bifarous',
				],
				'bifidly'=>[
					'bifidally',
					'bifidaly',
					'bifidely',
					'bifidlly',
				],
				'bifilar'=>[
					'bifiler',
				],
				'biflagellate'=>[
					'biflagelate',
				],
				'big'=>[
					'big big',
					'big big big',
				],
				'bigeminal'=>[
					'bigeminil',
				],
				'biggety'=>[
					'bigety',
				],
				'biggie'=>[
					'biggei',
					'biggi',
					'bigie',
				],
				'biggity'=>[
					'bigity',
				],
				'biggy'=>[
					'bigy',
				],
				'bigheartedly'=>[
					'bigheartedally',
					'bigheartedaly',
					'bigheartedely',
					'bigheartedlly',
				],
				'bigheartedness'=>[
					'bighertedness',
				],
				'bigly'=>[
					'bigally',
					'bigaly',
					'biglly',
				],
				'bijouterie'=>[
					'bijouterei',
					'bijouteri',
				],
				'bikie'=>[
					'bikei',
					'biki',
				],
				'bikini'=>[
					'bikina',
				],
				'bikinied'=>[
					'bikinaed',
				],
				'bikinis'=>[
					'bikinas',
				],
				'bilaterally'=>[
					'bilateraly',
				],
				'bilberry'=>[
					'bilbery',
				],
				'biliary'=>[
					'biliery',
				],
				'bilinear'=>[
					'bilineer',
					'biliniar',
				],
				'bilingual'=>[
					'bilingaul',
				],
				'bilingualism'=>[
					'bilingaulism',
				],
				'bilingualisms'=>[
					'bilingaulisms',
				],
				'bilious'=>[
					'bilous',
				],
				'biliously'=>[
					'bilously',
				],
				'bill'=>[
					'bil',
				],
				'billboard'=>[
					'bilboard',
				],
				'biller'=>[
					'biler',
				],
				'billet'=>[
					'bilet',
				],
				'billiard'=>[
					'biliard',
				],
				'billiards'=>[
					'biliards',
				],
				'billing'=>[
					'biling',
				],
				'billingsgate'=>[
					'bilingsgate',
				],
				'billion'=>[
					'bilion',
				],
				'billionaire'=>[
					'bilionaire',
				],
				'billions'=>[
					'billlions',
				],
				'billionth'=>[
					'bilionth',
				],
				'billon'=>[
					'bilon',
				],
				'billow'=>[
					'bilow',
				],
				'bills'=>[
					'bils',
				],
				'billy'=>[
					'bilally',
					'bilaly',
					'billly',
					'bily',
				],
				'bilobular'=>[
					'bilobuler',
				],
				'bilocular'=>[
					'biloculer',
				],
				'bimah'=>[
					'bima',
				],
				'bimahs'=>[
					'bimas',
				],
				'bimanual'=>[
					'bimanaul',
				],
				'bimetallic'=>[
					'bimetalic',
				],
				'bimillenary'=>[
					'bimillenery',
				],
				'bimillennial'=>[
					'bimillenial',
				],
				'bimillennials'=>[
					'bimillenials',
				],
				'bimolecular'=>[
					'bimoleculer',
				],
				'bimolecularly'=>[
					'bimolecularally',
					'bimolecularaly',
					'bimolecularely',
					'bimolecularlly',
				],
				'bimonthly'=>[
					'bimonthally',
					'bimonthaly',
					'bimonthely',
					'bimonthlly',
				],
				'bimorph'=>[
					'bimourph',
				],
				'bimorphemic'=>[
					'bimourphemic',
				],
				'bimorphs'=>[
					'bimourphs',
				],
				'binal'=>[
					'binil',
				],
				'binary'=>[
					'binery',
					'biniry',
				],
				'binate'=>[
					'binite',
				],
				'binately'=>[
					'binatly',
				],
				'binational'=>[
					'binitional',
				],
				'binaural'=>[
					'biniural',
				],
				'biner'=>[
					'binir',
				],
				'biners'=>[
					'binirs',
				],
				'bines'=>[
					'binis',
				],
				'binit'=>[
					'binat',
				],
				'binits'=>[
					'binats',
				],
				'binnacle'=>[
					'binacle',
				],
				'binocular'=>[
					'binoculer',
				],
				'binocularities'=>[
					'binoculariteis',
					'binocularitis',
				],
				'binocularly'=>[
					'binocularally',
					'binocularaly',
					'binocularely',
					'binocularlly',
				],
				'binomial'=>[
					'binominal',
				],
				'binuclear'=>[
					'binucleer',
				],
				'biochemistries'=>[
					'biochemistreis',
					'biochemistris',
				],
				'biocompatible'=>[
					'biocompatable',
				],
				'biodegradable'=>[
					'biodegradible',
				],
				'biodiversities'=>[
					'biodiversiteis',
					'biodiversitis',
				],
				'bioengineered'=>[
					'bioenginiered',
				],
				'bioengineering'=>[
					'bioenginiering',
				],
				'bioengineerings'=>[
					'bioenginierings',
				],
				'biogenetically'=>[
					'biogeneticaly',
				],
				'biogeographies'=>[
					'biogeographeis',
					'biogeographis',
				],
				'biographically'=>[
					'biographicaly',
				],
				'biography'=>[
					'biographie',
				],
				'bioluminescence'=>[
					'bioluminecence',
					'bioluminecsence',
					'bioluminescance',
					'bioluminesence',
					'bioluminiscence',
				],
				'bioluminescent'=>[
					'bioluminecent',
					'bioluminecsent',
					'bioluminescant',
					'bioluminesent',
					'bioluminiscent',
				],
				'biomass'=>[
					'biomas',
				],
				'biomechanically'=>[
					'biomechanicalally',
					'biomechanicalaly',
					'biomechanicalely',
					'biomechanicallly',
					'biomechanicaly',
				],
				'biomedicine'=>[
					'biomedicini',
				],
				'biometrician'=>[
					'biometrican',
				],
				'biomolecular'=>[
					'biomoleculer',
				],
				'biomorph'=>[
					'biomourph',
				],
				'biomorphs'=>[
					'biomourphs',
				],
				'biopiracy'=>[
					'biopirasy',
				],
				'biopsy'=>[
					'biopcy',
				],
				'bioreactor'=>[
					'biorector',
				],
				'bioscience'=>[
					'biocience',
					'biocsience',
					'biosceince',
					'biosciance',
					'bioscince',
					'biosience',
				],
				'bioscientific'=>[
					'biocientific',
					'biocsientific',
					'biosientific',
				],
				'bioscientists'=>[
					'biocientists',
					'biocsientists',
					'biosientists',
				],
				'bioscope'=>[
					'biocope',
					'biocsope',
					'biosope',
				],
				'biostatistician'=>[
					'biostatistican',
				],
				'biotechnologies'=>[
					'biotechnologeis',
					'biotechnologis',
				],
				'biotelemetries'=>[
					'biotelemetreis',
					'biotelemetris',
				],
				'biparental'=>[
					'biperental',
				],
				'biparentally'=>[
					'biperentally',
				],
				'biparous'=>[
					'biperous',
				],
				'biparted'=>[
					'biperted',
				],
				'bipartisan'=>[
					'bipertisan',
				],
				'bipartisanism'=>[
					'bipertisanism',
				],
				'bipartisanisms'=>[
					'bipertisanisms',
				],
				'bipartisanship'=>[
					'bipertisanship',
				],
				'bipartisanships'=>[
					'bipertisanships',
				],
				'bipartite'=>[
					'bipertite',
				],
				'bipartitely'=>[
					'bipartately',
					'bipartitly',
					'bipertitely',
				],
				'bipartition'=>[
					'bipertition',
				],
				'bipartitions'=>[
					'bipertitions',
				],
				'biparty'=>[
					'biperty',
				],
				'bipinnate'=>[
					'bipinate',
				],
				'bipinnately'=>[
					'bipinnatly',
				],
				'bipolar'=>[
					'bipoler',
				],
				'bipropellant'=>[
					'bipropelant',
					'bipropellent',
				],
				'bipropellants'=>[
					'bipropellents',
				],
				'biquadratic'=>[
					'biqaudratic',
				],
				'biquadratics'=>[
					'biqaudratics',
				],
				'bird'=>[
					'bird bird',
					'bird bird bird',
				],
				'birddogged'=>[
					'birddoged',
				],
				'birddogging'=>[
					'birddoging',
				],
				'birdie'=>[
					'birdei',
					'birdi',
				],
				'birds'=>[
					'brids',
				],
				'birefringence'=>[
					'birefringance',
				],
				'birr'=>[
					'bir',
				],
				'birrs'=>[
					'birs',
				],
				'biscuit'=>[
					'bicsuit',
					'bicuit',
					'bisuit',
				],
				'bisect'=>[
					'disect',
				],
				'bisection'=>[
					'disection',
				],
				'bisexual'=>[
					'bisexaul',
				],
				'bisexualities'=>[
					'bisexaulities',
				],
				'bismuthal'=>[
					'bismutal',
				],
				'bit'=>[
					'bit bit',
					'bit bit bit',
					'bited',
				],
				'bitable'=>[
					'bitible',
				],
				'bitsy'=>[
					'bitcy',
				],
				'bitten'=>[
					'biten',
				],
				'bitterroot'=>[
					'bitteroot',
				],
				'bitterroots'=>[
					'bitteroots',
				],
				'bittersweetly'=>[
					'bittersweetally',
					'bittersweetaly',
					'bittersweetely',
					'bittersweetlly',
				],
				'bituminization'=>[
					'bituminazation',
				],
				'bituminizations'=>[
					'bituminazations',
				],
				'bituminize'=>[
					'bituminaze',
				],
				'bituminized'=>[
					'bituminazed',
				],
				'bituminizes'=>[
					'bituminazes',
				],
				'bituminizing'=>[
					'bituminazing',
				],
				'biuniquenesses'=>[
					'biuniqueneses',
				],
				'bivalence'=>[
					'bivalance',
				],
				'bivalency'=>[
					'bivalensy',
				],
				'bivouac'=>[
					'bivoauc',
				],
				'biweekly'=>[
					'biweekally',
					'biweekaly',
					'biweekely',
					'biweeklly',
				],
				'biyearly'=>[
					'biyearally',
					'biyearaly',
					'biyearely',
					'biyearlly',
				],
				'bizarre'=>[
					'bizaare',
					'bizare',
				],
				'bizarrely'=>[
					'bizarrly',
				],
				'bizarreness'=>[
					'bizareness',
				],
				'bizarrenesses'=>[
					'bizarenesses',
				],
				'bizarrerie'=>[
					'bizarerie',
				],
				'bizarreries'=>[
					'bizareries',
				],
				'bizarro'=>[
					'bizaro',
				],
				'blabbed'=>[
					'blabed',
				],
				'blabber'=>[
					'blaber',
				],
				'blabbered'=>[
					'blabered',
				],
				'blabbering'=>[
					'blabering',
				],
				'blabbermouth'=>[
					'blabermouth',
				],
				'blabbermouths'=>[
					'blabermouths',
				],
				'blabbers'=>[
					'blabers',
				],
				'blabbing'=>[
					'blabing',
				],
				'blabby'=>[
					'blaby',
				],
				'black'=>[
					'black black',
					'black black black',
				],
				'black-box testing'=>[
					'black box testing',
				],
				'blackberry'=>[
					'blackbery',
				],
				'blackened'=>[
					'blackend',
				],
				'blackfly'=>[
					'blackfally',
					'blackfaly',
					'blackfely',
					'blackflly',
				],
				'blackguard'=>[
					'blackgaurd',
				],
				'blackguarded'=>[
					'blackgaurded',
				],
				'blackguarding'=>[
					'blackgaurding',
				],
				'blackguardism'=>[
					'blackgaurdism',
				],
				'blackguardisms'=>[
					'blackgaurdisms',
				],
				'blackguardly'=>[
					'blackgaurdly',
				],
				'blacktopped'=>[
					'blacktoped',
				],
				'blacktopping'=>[
					'blacktoping',
				],
				'blaeberries'=>[
					'blaeberies',
				],
				'blagging'=>[
					'blaging',
				],
				'blaggings'=>[
					'blagings',
				],
				'blah'=>[
					'bla',
				],
				'blahs'=>[
					'blas',
				],
				'blamable'=>[
					'blamible',
				],
				'blame'=>[
					'blaim',
				],
				'blameable'=>[
					'blameible',
				],
				'blamed'=>[
					'blaimed',
				],
				'blameless'=>[
					'blameles',
				],
				'blamelessly'=>[
					'blamelessally',
					'blamelessaly',
					'blamelessely',
					'blamelesslly',
				],
				'blameworthiness'=>[
					'blameworthiniss',
				],
				'blandly'=>[
					'blandally',
					'blandaly',
					'blandely',
					'blandlly',
				],
				'blasphemously'=>[
					'blasphemousally',
					'blasphemousaly',
					'blasphemousely',
					'blasphemouslly',
				],
				'blastular'=>[
					'blastuler',
				],
				'blatancy'=>[
					'blatansy',
				],
				'blatant'=>[
					'blatent',
				],
				'bleach'=>[
					'blech',
				],
				'bleak'=>[
					'blek',
				],
				'blear'=>[
					'bleer',
				],
				'bleary'=>[
					'bleery',
				],
				'bleat'=>[
					'blet',
				],
				'blebby'=>[
					'bleby',
				],
				'bled'=>[
					'bleeded',
				],
				'bleeding'=>[
					'bleeeding',
				],
				'blenny'=>[
					'bleny',
				],
				'blent'=>[
					'blant',
				],
				'bless'=>[
					'bles',
				],
				'blessed'=>[
					'blesed',
					'blest',
				],
				'blessing'=>[
					'blesing',
				],
				'blimpishnesses'=>[
					'blimpishneses',
				],
				'blini'=>[
					'blina',
				],
				'blinis'=>[
					'blinas',
				],
				'bliss'=>[
					'blis',
				],
				'blissfulnesses'=>[
					'blissfulneses',
				],
				'blistery'=>[
					'blistary',
				],
				'blithely'=>[
					'blithly',
				],
				'blithesomely'=>[
					'blithesomly',
				],
				'blitzkrieg'=>[
					'blitzkreig',
					'blitzkrig',
				],
				'blobbed'=>[
					'blobed',
				],
				'blobbing'=>[
					'blobing',
				],
				'block'=>[
					'block block',
					'block block block',
				],
				'bloggings'=>[
					'blogings',
				],
				'blond'=>[
					'blonde',
				],
				'blood'=>[
					'blood blood',
					'blood blood blood',
				],
				'bloodguiltiness'=>[
					'bloodguiltiniss',
				],
				'bloodless'=>[
					'bloodles',
				],
				'bloodlessly'=>[
					'bloodlessally',
					'bloodlessaly',
					'bloodlessely',
					'bloodlesslly',
				],
				'bloodline'=>[
					'bloodlini',
				],
				'bloodstained'=>[
					'bloodstainid',
				],
				'bloodstream'=>[
					'bloodstrem',
				],
				'blossom'=>[
					'bloosom',
					'blosom',
					'blossem',
				],
				'blousier'=>[
					'blouiser',
				],
				'blousiest'=>[
					'blouisest',
				],
				'blousily'=>[
					'blouisly',
				],
				'blousing'=>[
					'blouisng',
				],
				'blousy'=>[
					'bloucy',
				],
				'blow'=>[
					'blow blow',
					'blow blow blow',
				],
				'blowfly'=>[
					'blowfally',
					'blowfaly',
					'blowfely',
					'blowflly',
				],
				'blown'=>[
					'blowed',
				],
				'blowsy'=>[
					'blowcy',
				],
				'blubbed'=>[
					'blubed',
				],
				'blubber'=>[
					'bluber',
				],
				'blubbered'=>[
					'blubered',
				],
				'blubberer'=>[
					'bluberer',
				],
				'blubberers'=>[
					'bluberers',
				],
				'blubbering'=>[
					'blubering',
				],
				'blubbers'=>[
					'blubers',
				],
				'blubbery'=>[
					'blubery',
				],
				'blubbing'=>[
					'blubing',
				],
				'blue'=>[
					'blue blue',
					'blue blue blue',
				],
				'blueberries'=>[
					'blueberies',
				],
				'blueberry'=>[
					'bluebery',
				],
				'bluebonnet'=>[
					'bluebonet',
				],
				'blueing'=>[
					'bluieng',
				],
				'blueish'=>[
					'bluiesh',
				],
				'blueline'=>[
					'bluelini',
				],
				'bluely'=>[
					'bluly',
				],
				'blueprint'=>[
					'tblueprint',
				],
				'bluesy'=>[
					'bluecy',
				],
				'blunderbuss'=>[
					'blunderbus',
				],
				'blustery'=>[
					'blustary',
				],
				'boar'=>[
					'boer',
				],
				'board'=>[
					'baord',
					'board board',
					'board board board',
				],
				'boarded'=>[
					'borded',
				],
				'boastfulnesses'=>[
					'boastfulneses',
				],
				'boat'=>[
					'boat boat',
					'boat boat boat',
				],
				'bobbed'=>[
					'bobed',
				],
				'bobber'=>[
					'bober',
				],
				'bobberies'=>[
					'boberies',
				],
				'bobbers'=>[
					'bobers',
				],
				'bobbery'=>[
					'bobery',
				],
				'bobbies'=>[
					'bobies',
				],
				'bobbin'=>[
					'bobin',
				],
				'bobbinet'=>[
					'bobinet',
				],
				'bobbinets'=>[
					'bobinets',
				],
				'bobbing'=>[
					'bobing',
				],
				'bobbins'=>[
					'bobins',
				],
				'bobble'=>[
					'boble',
				],
				'bobbled'=>[
					'bobled',
				],
				'bobbles'=>[
					'bobles',
				],
				'bobbling'=>[
					'bobling',
				],
				'bobby'=>[
					'boby',
				],
				'bobbysox'=>[
					'bobysox',
				],
				'bobsleigh'=>[
					'bobsliegh',
				],
				'bocaccio'=>[
					'bocacio',
				],
				'bocaccios'=>[
					'bocacios',
				],
				'bocce'=>[
					'boce',
				],
				'bocces'=>[
					'boces',
				],
				'bocci'=>[
					'boci',
				],
				'boccia'=>[
					'bocia',
				],
				'boccias'=>[
					'bocias',
				],
				'boccie'=>[
					'bocie',
				],
				'boccies'=>[
					'bocies',
				],
				'boccis'=>[
					'bocis',
				],
				'bodacious'=>[
					'bodacous',
				],
				'bodhrán'=>[
					'bodhran',
				],
				'bodied'=>[
					'bodeid',
					'bodid',
				],
				'bodies'=>[
					'bodys',
				],
				'bodily'=>[
					'bodially',
					'bodialy',
					'bodiely',
					'bodilly',
					'bodly',
				],
				'body'=>[
					'body body',
					'body body body',
				],
				'bodyguard'=>[
					'bodygaurd',
				],
				'bodyguarding'=>[
					'bodygaurding',
				],
				'bogginess'=>[
					'boginess',
				],
				'bogginesses'=>[
					'boginesses',
				],
				'boggle'=>[
					'bogle',
				],
				'boggy'=>[
					'bogy',
				],
				'bogie'=>[
					'bogei',
					'bogi',
				],
				'bohemian'=>[
					'boheman',
				],
				'boisterousness'=>[
					'boisterousnes',
				],
				'bolar'=>[
					'boler',
				],
				'bolivar'=>[
					'boliver',
				],
				'bolivarian'=>[
					'boliviarian',
				],
				'bolivian-occupied'=>[
					'bolivian occupied',
				],
				'boll'=>[
					'bol',
				],
				'bolls'=>[
					'bols',
				],
				'bolometrically'=>[
					'bolometricaly',
				],
				'bomb in'=>[
					'bombin',
				],
				'bombardier'=>[
					'bombardeir',
					'bombardir',
				],
				'bombinate'=>[
					'bombinite',
				],
				'bombshell'=>[
					'bombshel',
				],
				'bona fide'=>[
					'bonafied',
					'bonified',
				],
				'bonanno'=>[
					'bonnano',
				],
				'bone'=>[
					'bone bone',
					'bone bone bone',
				],
				'boneheadedness'=>[
					'boneheadednes',
					'bonehededness',
				],
				'boneless'=>[
					'boneles',
				],
				'bonhomie'=>[
					'bonhomei',
					'bonhomi',
				],
				'bonne'=>[
					'bonnne',
				],
				'bonnet'=>[
					'bonet',
				],
				'bonny'=>[
					'bony',
				],
				'bonnyclabber'=>[
					'bonnyclaber',
					'bonyclabber',
				],
				'bonnyclabbers'=>[
					'bonnyclabers',
					'bonyclabbers',
				],
				'boogie'=>[
					'boogei',
					'boogi',
				],
				'book'=>[
					'book book',
					'book book book',
					'boook',
				],
				'bookable'=>[
					'bookible',
				],
				'bookie'=>[
					'bookei',
					'booki',
				],
				'bookseller'=>[
					'bookseler',
				],
				'boondoggle'=>[
					'boondogle',
				],
				'boondoggled'=>[
					'boondogled',
				],
				'boondoggler'=>[
					'boondogler',
				],
				'boondogglers'=>[
					'boondoglers',
				],
				'boondoggles'=>[
					'boondogles',
				],
				'boondoggling'=>[
					'boondogling',
				],
				'boos'=>[
					'boo\'s',
				],
				'bootable'=>[
					'bootible',
				],
				'bootery'=>[
					'bootary',
				],
				'bootie'=>[
					'bootei',
					'booti',
				],
				'bootlegged'=>[
					'bootleged',
				],
				'bootlegger'=>[
					'bootleger',
				],
				'bootleggers'=>[
					'bootlegers',
				],
				'bootlegging'=>[
					'bootleging',
				],
				'bootlessnesses'=>[
					'bootlessneses',
				],
				'bootstrapped'=>[
					'bootstraped',
				],
				'bootstrapping'=>[
					'bootstraping',
				],
				'bopped'=>[
					'boped',
				],
				'borderline'=>[
					'borderlini',
				],
				'born'=>[
					'born born',
					'born born born',
				],
				'borrelia'=>[
					'borelia',
				],
				'borrow'=>[
					'borow',
				],
				'borrowing'=>[
					'borowing',
				],
				'borscht'=>[
					'borcht',
					'borcsht',
					'borsht',
				],
				'bosnian-occupied'=>[
					'bosnian occupied',
				],
				'boss'=>[
					'bos',
					'bosss',
				],
				'bossy'=>[
					'boscy',
					'bosy',
				],
				'boston'=>[
					'bost',
				],
				'botfly'=>[
					'botfally',
					'botfaly',
					'botfely',
					'botflly',
				],
				'both'=>[
					'boht ',
					'both both',
					'both both both',
					'boths',
				],
				'both the'=>[
					'the both the',
				],
				'bottom'=>[
					'bottom bottom',
					'bottom bottom bottom',
				],
				'bottomless'=>[
					'bottomles',
				],
				'bottomlessness'=>[
					'bottomlessnes',
				],
				'bottommost'=>[
					'bottomnost',
				],
				'botzwanian-occupied'=>[
					'botzwanian occupied',
				],
				'bouffant'=>[
					'bouffent',
				],
				'bougainvillaea'=>[
					'bougainvilaea',
					'bougainvillae',
				],
				'bougainvillaeas'=>[
					'bougainvilaeas',
					'bougainvillaes',
				],
				'bougainvillea'=>[
					'bougainvilea',
					'bougainville',
				],
				'bougainvilleas'=>[
					'bougainvileas',
					'bougainvilles',
				],
				'bought'=>[
					'bought bought',
					'bought bought bought',
					'buyed',
				],
				'bouillabaisse'=>[
					'bouilabaisse',
					'bouillabaise',
				],
				'bouillabaisses'=>[
					'bouilabaisses',
					'bouillabaises',
				],
				'boulevardier'=>[
					'boulevardeir',
					'boulevardir',
				],
				'boulevards'=>[
					'boulevarsd', 'boulvarsd',
				],
				'bouleversement'=>[
					'bouleversemant',
				],
				'bouleversements'=>[
					'bouleversemants',
				],
				'bouncy'=>[
					'bounsy',
				],
				'bound'=>[
					'binded',
				],
				'boundaries'=>[
					'boundries',
				],
				'boundary'=>[
					'bondary',
					'boundery',
					'boundry',
				],
				'boundless'=>[
					'boundles',
				],
				'boundlessly'=>[
					'boundlessally',
					'boundlessaly',
					'boundlessely',
					'boundlesslly',
				],
				'bourgeois'=>[
					'bourgois',
				],
				'bourgeoisie'=>[
					'borgeoisie',
					'bourgeoisei',
					'bourgeoisi',
				],
				'bourgeoisified'=>[
					'bourgeoisifeid',
					'bourgeoisifid',
				],
				'bourgeoisifies'=>[
					'bourgeoisifeis',
					'bourgeoisifis',
				],
				'bourguignonne'=>[
					'bourguignone',
				],
				'bourree'=>[
					'bouree',
				],
				'bousy'=>[
					'boucy',
				],
				'bout'=>[
					'baout',
				],
				'boutonniere'=>[
					'boutoniere',
					'boutonneire',
					'boutonnire',
				],
				'boutonnieres'=>[
					'boutonieres',
				],
				'bouvier'=>[
					'bouveir',
					'bouvir',
				],
				'bouzouki'=>[
					'bouyzouki',
					'buzouki',
				],
				'bovine'=>[
					'bovini',
				],
				'bovinely'=>[
					'bovinly',
				],
				'bovinity'=>[
					'bovinaty',
				],
				'bowknot'=>[
					'bowkot',
				],
				'bowknots'=>[
					'bowkots',
				],
				'bowlegged'=>[
					'bowleged',
				],
				'bowline'=>[
					'bowlini',
				],
				'box'=>[
					'box box',
					'box box box',
				],
				'boxcar'=>[
					'boxcer',
				],
				'boy'=>[
					'boy boy',
					'boy boy boy',
				],
				'boyar'=>[
					'boyer',
				],
				'boycott'=>[
					'boycot',
				],
				'boyfriend'=>[
					'boyfreind',
					'boyfrind',
				],
				'boysenberries'=>[
					'boysenberies',
				],
				'boysenberry'=>[
					'boysenbery',
				],
				'brabble'=>[
					'brable',
				],
				'brabbled'=>[
					'brabled',
				],
				'brabbler'=>[
					'brabler',
				],
				'brabblers'=>[
					'brablers',
				],
				'brabbles'=>[
					'brables',
				],
				'brabbling'=>[
					'brabling',
				],
				'brachycephalies'=>[
					'brachycephaleis',
					'brachycephalis',
				],
				'brackish'=>[
					'brakish',
				],
				'brackishnesses'=>[
					'brackishneses',
				],
				'bradykinin'=>[
					'bradykinan',
				],
				'bradykinins'=>[
					'bradykinans',
				],
				'braggadocio'=>[
					'bragadocio',
				],
				'braggadocios'=>[
					'bragadocios',
				],
				'braggart'=>[
					'bragart',
				],
				'braggarts'=>[
					'bragarts',
				],
				'brahma'=>[
					'brama',
				],
				'brahmas'=>[
					'bramas',
				],
				'braillewriters'=>[
					'brailewriters',
				],
				'brained'=>[
					'brainid',
				],
				'brainiac'=>[
					'brainaac',
				],
				'brainiacs'=>[
					'brainaacs',
				],
				'brainier'=>[
					'brainaer',
				],
				'brainiest'=>[
					'brainaest',
				],
				'brainily'=>[
					'brainaly',
				],
				'braininesses'=>[
					'brainanesses',
				],
				'braining'=>[
					'brainang',
				],
				'brainish'=>[
					'brainash',
				],
				'brainlessly'=>[
					'brainlessally',
					'brainlessaly',
					'brainlessely',
					'brainlesslly',
				],
				'brainteaser'=>[
					'brainteser',
				],
				'branch'=>[
					'branch branch',
					'branch branch branch',
				],
				'branches'=>[
					'branchs',
				],
				'brannigan'=>[
					'branigan',
				],
				'brant'=>[
					'brent',
				],
				'brants'=>[
					'brents',
				],
				'brass'=>[
					'bras',
				],
				'brasserie'=>[
					'braserie',
					'brasserei',
					'brasseri',
				],
				'brassiere'=>[
					'brasseire',
					'brassire',
				],
				'brassy'=>[
					'brascy',
					'brasy',
				],
				'braunschweiger'=>[
					'braunchweiger',
					'brauncshweiger',
					'braunschwieger',
					'braunshweiger',
				],
				'braunschweigers'=>[
					'braunchweigers',
					'brauncshweigers',
					'braunschwiegers',
					'braunshweigers',
				],
				'brave'=>[
					'bave',
				],
				'bravely'=>[
					'bravly',
				],
				'brawly'=>[
					'brawally',
					'brawaly',
					'brawely',
					'brawlly',
				],
				'brazened'=>[
					'brazend',
				],
				'brazennesses'=>[
					'brazenesses',
				],
				'brazier'=>[
					'brazeir',
					'brazir',
				],
				'brazilian'=>[
					'brasillian',
					'brazilan',
					'brazillan',
					'brazillian',
					'brazillion',
				],
				'brazilian-occupied'=>[
					'brazilian occupied',
				],
				'breach'=>[
					'brech',
				],
				'bread'=>[
					'bread bread',
					'bread bread bread',
					'bred',
				],
				'breadbasket'=>[
					'bredbasket',
				],
				'breadboarding'=>[
					'bredboarding',
				],
				'breadline'=>[
					'breadlini',
				],
				'breadth'=>[
					'bredth',
				],
				'breadwinner'=>[
					'breadwiner',
					'bredwinner',
				],
				'breadwinners'=>[
					'breadwiners',
				],
				'breadwinning'=>[
					'breadwining',
				],
				'breadwinnings'=>[
					'breadwinings',
					'bredwinnings',
				],
				'break'=>[
					'break break',
					'break break break',
					'brek',
				],
				'breakable'=>[
					'breakible',
				],
				'breakage'=>[
					'brekage',
				],
				'breakaway'=>[
					'brekaway',
				],
				'breakdown'=>[
					'brakedown',
					'brekdown',
				],
				'breaker'=>[
					'breker',
				],
				'breakeven'=>[
					'brekeven',
				],
				'breakfast'=>[
					'brekfast',
				],
				'breaking'=>[
					'breking',
				],
				'breakneck'=>[
					'brekneck',
				],
				'breakout'=>[
					'brekout',
				],
				'breakthrough'=>[
					'break-through',
					'breakthough',
					'brekthrough',
				],
				'breakthroughs'=>[
					'brekthroughs',
				],
				'breakup'=>[
					'brakeup',
					'brekup',
				],
				'breakwater'=>[
					'brekwater',
				],
				'bream'=>[
					'brem',
				],
				'breast'=>[
					'brest',
				],
				'breastfeed'=>[
					'brestfeed',
				],
				'breastfeeding'=>[
					'brestfeeding',
				],
				'breastplate'=>[
					'brestplate',
				],
				'breaststroke'=>[
					'breststroke',
				],
				'breaststroker'=>[
					'breststroker',
				],
				'breaststrokers'=>[
					'breststrokers',
				],
				'breaststrokes'=>[
					'breststrokes',
				],
				'breath'=>[
					'breth',
				],
				'breathabilities'=>[
					'breathabiliteis',
					'breathabilitis',
					'brethabilities',
				],
				'breathability'=>[
					'brethability',
				],
				'breathable'=>[
					'breathible',
					'brethable',
				],
				'breathe'=>[
					'brethe',
				],
				'breathed'=>[
					'brethed',
				],
				'breather'=>[
					'brether',
				],
				'breathinesses'=>[
					'breathinisses',
					'brethinesses',
				],
				'breathing'=>[
					'brething',
				],
				'breathless'=>[
					'breathles',
					'brethless',
				],
				'breathlessness'=>[
					'breathlessnes',
					'brethlessness',
				],
				'breathtaking'=>[
					'brethtaking',
				],
				'breathtakingly'=>[
					'brethtakingly',
				],
				'breccia'=>[
					'brecia',
				],
				'breccial'=>[
					'brecial',
				],
				'breccias'=>[
					'brecias',
				],
				'brecciate'=>[
					'breciate',
				],
				'brecciated'=>[
					'breciated',
				],
				'brecciates'=>[
					'breciates',
				],
				'brecciating'=>[
					'breciating',
				],
				'brecciation'=>[
					'breciation',
				],
				'brecciations'=>[
					'breciations',
				],
				'bred'=>[
					'breeded',
				],
				'bremsstrahlung'=>[
					'bremsstralung',
					'bremstrahlung',
				],
				'bremsstrahlungs'=>[
					'bremsstralungs',
				],
				'brent'=>[
					'brant',
				],
				'brents'=>[
					'brants',
				],
				'brethren'=>[
					'brethrens',
				],
				'breton'=>[
					'brenton',
				],
				'brevetcy'=>[
					'brevetsy',
				],
				'breviary'=>[
					'breviery',
				],
				'briar'=>[
					'brar',
					'brier',
				],
				'briary'=>[
					'briery',
				],
				'bribery'=>[
					'bribary',
				],
				'brickfield'=>[
					'brickfeild',
					'brickfild',
				],
				'bridgehead'=>[
					'bridgehed',
				],
				'brie'=>[
					'brei',
				],
				'brief'=>[
					'breif',
					'brif',
				],
				'briefcase'=>[
					'breifcase',
					'brifcase',
				],
				'briefing'=>[
					'breifing',
					'brifing',
				],
				'briefly'=>[
					'breifly',
				],
				'brier'=>[
					'breir',
					'brir',
				],
				'bries'=>[
					'breis',
					'bris',
				],
				'brigade'=>[
					'brigaded',
				],
				'brigadier'=>[
					'brigadeir',
					'brigadir',
					'brigandier',
				],
				'brigantine'=>[
					'brigantini',
					'brigentine',
				],
				'bright'=>[
					'bright bright',
					'bright bright bright',
				],
				'brightened'=>[
					'brightend',
				],
				'brightness'=>[
					'brightnes',
				],
				'brill'=>[
					'bril',
				],
				'brilliance'=>[
					'briliance',
					'brillance',
					'brillience',
				],
				'brilliancy'=>[
					'brilliansy',
				],
				'brilliant'=>[
					'briliant',
					'brillant',
					'brillient',
				],
				'brilliantine'=>[
					'briliantine',
					'brilliantini',
					'brillientine',
				],
				'brilliantines'=>[
					'brilliantinis',
					'brillientines',
				],
				'brimmers'=>[
					'brimners',
				],
				'brimming'=>[
					'brimnning',
					'brimning',
				],
				'brine'=>[
					'brini',
				],
				'brined'=>[
					'brinid',
				],
				'briner'=>[
					'brinir',
				],
				'brines'=>[
					'brinis',
				],
				'bring'=>[
					'bring bring',
					'bring bring bring',
				],
				'briniest'=>[
					'brinaest',
				],
				'brininess'=>[
					'brinaness',
				],
				'brininesses'=>[
					'brinanesses',
				],
				'brink'=>[
					'bnnk',
				],
				'brisance'=>[
					'brisence',
				],
				'briss'=>[
					'bris',
				],
				'bristling'=>[
					'bristlng',
				],
				'bristly'=>[
					'bristally',
					'bristaly',
					'bristely',
					'bristlly',
				],
				'britain'=>[
					'britan',
					'britian',
					'brittain',
				],
				'britannica'=>[
					'britanica',
					'brittanica',
					'brittanicca',
				],
				'british'=>[
					'bntish',
					'britis',
					'brittish',
					'brtish',
				],
				'british-occupied'=>[
					'british occupied',
				],
				'brittlely'=>[
					'brittlly',
				],
				'broad'=>[
					'boroad',
					'broad broad',
					'broad broad broad',
				],
				'broadcast'=>[
					'brodcast',
				],
				'broadcast should be used per wp:commonality'=>[
					'broadcasted',
				],
				'broadened'=>[
					'broadend',
				],
				'broadly'=>[
					'broady',
				],
				'broccoli'=>[
					'brocoli',
				],
				'broccolis'=>[
					'brocolis',
				],
				'broke'=>[
					'broke broke',
					'broke broke broke',
					'broked',
				],
				'brokenhearted'=>[
					'brokenherted',
				],
				'brokennesses'=>[
					'brokenesses',
				],
				'brolly'=>[
					'brolally',
					'brolaly',
					'brolely',
					'brollly',
				],
				'brominate'=>[
					'brominite',
				],
				'bromine'=>[
					'bromini',
				],
				'brominism'=>[
					'brominasm',
				],
				'bromocriptine'=>[
					'bromocriptini',
				],
				'bromocriptines'=>[
					'bromocriptinis',
				],
				'bronchiectases'=>[
					'broncheictases',
					'bronchictases',
				],
				'bronchiectasis'=>[
					'broncheictasis',
					'bronchictasis',
				],
				'bronchiolar'=>[
					'bronchioler',
				],
				'bronchoscope'=>[
					'bronchocope',
					'bronchocsope',
					'bronchosope',
				],
				'bronchoscopes'=>[
					'bronchocopes',
					'bronchocsopes',
					'bronchosopes',
				],
				'bronchoscopic'=>[
					'bronchocopic',
					'bronchocsopic',
					'bronchosopic',
				],
				'bronchoscopies'=>[
					'bronchocopies',
					'bronchocsopies',
					'bronchoscopeis',
					'bronchoscopis',
					'bronchosopies',
				],
				'bronchoscopist'=>[
					'bronchocopist',
					'bronchocsopist',
					'bronchosopist',
				],
				'bronchoscopists'=>[
					'bronchocopists',
					'bronchocsopists',
					'bronchosopists',
				],
				'brosy'=>[
					'brocy',
				],
				'brother'=>[
					'borther',
					'brotber',
					'brother brother',
					'brother brother brother',
				],
				'brotherliness'=>[
					'brotherliniss',
				],
				'brotherlinesses'=>[
					'brotherlinisses',
				],
				'brotherly'=>[
					'brotherally',
					'brotheraly',
					'brotherely',
					'brotherlly',
				],
				'brought'=>[
					'brang',
					'bringed',
					'broght',
					'brough',
					'brought brought',
					'brought brought brought',
					'brung',
				],
				'brouhaha'=>[
					'brouhaa',
				],
				'brouhahas'=>[
					'brouhaas',
				],
				'brown'=>[
					'brown brown',
					'brown brown brown',
				],
				'brownfield'=>[
					'brownfeild',
					'brownfild',
				],
				'brownie'=>[
					'brownei',
					'browni',
				],
				'brownnose'=>[
					'brownose',
				],
				'brrr'=>[
					'brr',
				],
				'brucellosis'=>[
					'brucelosis',
				],
				'brummagem'=>[
					'brumnagem',
				],
				'bruneian-occupied'=>[
					'bruneian occupied',
				],
				'brushabilities'=>[
					'brushabiliteis',
					'brushabilitis',
				],
				'brusquely'=>[
					'brusquly',
				],
				'brussels'=>[
					'brussells',
				],
				'brutely'=>[
					'brutly',
				],
				'bruxelles'=>[
					'bruxels',
				],
				'bubba'=>[
					'buba',
				],
				'bubbas'=>[
					'bubas',
				],
				'bubbies'=>[
					'bubies',
				],
				'bubble'=>[
					'buble',
				],
				'bubbled'=>[
					'bubled',
				],
				'bubblegum'=>[
					'bublegum',
				],
				'bubblegums'=>[
					'bublegums',
				],
				'bubblehead'=>[
					'bublehead',
				],
				'bubbleheaded'=>[
					'bubleheaded',
				],
				'bubbleheads'=>[
					'bubleheads',
				],
				'bubbler'=>[
					'bubler',
				],
				'bubblers'=>[
					'bublers',
				],
				'bubbles'=>[
					'bubles',
				],
				'bubblier'=>[
					'bublier',
				],
				'bubblies'=>[
					'bublies',
				],
				'bubbliest'=>[
					'bubliest',
				],
				'bubbling'=>[
					'bubling',
				],
				'bubbly'=>[
					'bubbally',
					'bubbaly',
					'bubbely',
					'bubblly',
					'bubly',
				],
				'bubby'=>[
					'buby',
				],
				'buccal'=>[
					'bucal',
				],
				'buccally'=>[
					'bucally',
				],
				'buccaneer'=>[
					'bucaneer',
				],
				'buccaneering'=>[
					'bucaneering',
				],
				'buccaneerish'=>[
					'bucaneerish',
				],
				'buccaneers'=>[
					'bucaneers',
				],
				'buccinator'=>[
					'buccinitor',
					'bucinator',
				],
				'buccinators'=>[
					'bucinators',
				],
				'buckyballs'=>[
					'buckybals',
				],
				'buddha'=>[
					'buddah',
					'budha',
				],
				'buddhism'=>[
					'buddh\'ism',
				],
				'buddhist'=>[
					'buddist',
					'budhist',
				],
				'buddleia'=>[
					'buddliea',
				],
				'budgerigar'=>[
					'budgeriger',
				],
				'budget'=>[
					'buget',
				],
				'budgetary'=>[
					'budgetery',
				],
				'budgie'=>[
					'budgei',
					'budgi',
				],
				'buena vista social club'=>[
					'buenavista social club',
				],
				'buffaloberries'=>[
					'buffaloberies',
					'buffaloberreis',
					'buffaloberris',
				],
				'buffaloberry'=>[
					'buffalobery',
				],
				'buffaloes'=>[
					'buffalos',
				],
				'buffooneries'=>[
					'buffoonereis',
					'buffooneris',
				],
				'bugbear'=>[
					'bugbeer',
				],
				'bugger'=>[
					'buger',
				],
				'buggeries'=>[
					'bugeries',
				],
				'buggering'=>[
					'bugering',
				],
				'buggery'=>[
					'bugery',
				],
				'bugginess'=>[
					'buginess',
				],
				'bugginesses'=>[
					'buginesses',
				],
				'buggy'=>[
					'bugy',
				],
				'build'=>[
					'build build',
					'build build build',
					'buld',
				],
				'buildable'=>[
					'buildible',
				],
				'builder'=>[
					'buiider',
					'bulder',
					'bulider',
				],
				'builders'=>[
					'buiiders',
					'bulders',
					'buliders',
				],
				'building'=>[
					'biulding',
					'buiding',
					'buidling',
					'buiiding',
					'buildng',
					'builiding',
					'bulding',
					'buliding',
				],
				'buildings'=>[
					'buiidings',
					'builings',
					'buldings',
					'bulidings',
				],
				'built'=>[
					'builded',
					'huilt',
				],
				'built-in'=>[
					'build-in',
				],
				'bulbar'=>[
					'bulber',
				],
				'bulgarian-occupied'=>[
					'bulgarian occupied',
				],
				'bull'=>[
					'bul',
				],
				'bulla'=>[
					'bula',
				],
				'bulldog'=>[
					'buldog',
				],
				'bulldogged'=>[
					'bulldoged',
				],
				'bulldogger'=>[
					'bulldoger',
				],
				'bulldoggers'=>[
					'bulldogers',
				],
				'bulldogging'=>[
					'bulldoging',
				],
				'bulldoggings'=>[
					'bulldogings',
				],
				'bulldozer'=>[
					'buldozer',
				],
				'bullet'=>[
					'bulet',
				],
				'bulletin'=>[
					'buletin',
					'bulliten',
				],
				'bulletining'=>[
					'bulletinang',
				],
				'bulletins'=>[
					'bullitens',
				],
				'bulletproof'=>[
					'buletproof',
				],
				'bullheadedness'=>[
					'bulheadedness',
					'bullheadednes',
					'bullhededness',
				],
				'bullion'=>[
					'bulion',
				],
				'bullish'=>[
					'bulish',
				],
				'bullock'=>[
					'bulock',
				],
				'bullpen'=>[
					'bulpen',
				],
				'bulls'=>[
					'buls',
				],
				'bullshit'=>[
					'bulshit',
				],
				'bullterriers'=>[
					'bullteriers',
					'bullterreirs',
					'bullterrirs',
				],
				'bullwhipped'=>[
					'bullwhiped',
				],
				'bullwhipping'=>[
					'bullwhiping',
				],
				'bully'=>[
					'bulally',
					'bulaly',
					'bullly',
					'buly',
				],
				'bullyragged'=>[
					'bullyraged',
				],
				'bullyragging'=>[
					'bullyraging',
				],
				'bummalo'=>[
					'bumnalo',
				],
				'bummalos'=>[
					'bumnalos',
				],
				'bummed'=>[
					'bumned',
				],
				'bummer'=>[
					'bumner',
				],
				'bumpkinly'=>[
					'bumpkinally',
					'bumpkinaly',
					'bumpkinely',
					'bumpkinlly',
				],
				'bumptious'=>[
					'bumptous',
				],
				'bumptiously'=>[
					'bumptously',
				],
				'bunchberries'=>[
					'bunchberies',
					'bunchberreis',
					'bunchberris',
				],
				'bunchberry'=>[
					'bunchbery',
				],
				'bunn'=>[
					'bun',
				],
				'bunns'=>[
					'buns',
				],
				'bunny'=>[
					'buny',
				],
				'buoy'=>[
					'bouy',
				],
				'buoyage'=>[
					'boyage',
				],
				'buoyages'=>[
					'boyages',
				],
				'buoyance'=>[
					'boyance',
					'buoyence',
				],
				'buoyances'=>[
					'boyances',
				],
				'buoyancies'=>[
					'boyancies',
				],
				'buoyancy'=>[
					'bouyancy',
					'boyancy',
					'buoyansy',
				],
				'buoyant'=>[
					'bouyant',
					'boyant',
					'buoyent',
				],
				'buoyantly'=>[
					'boyantly',
				],
				'buoyed'=>[
					'boyed',
				],
				'buoying'=>[
					'boying',
				],
				'buoys'=>[
					'boys',
				],
				'buppie'=>[
					'bupie',
				],
				'buppy'=>[
					'bupy',
				],
				'burden'=>[
					'buden',
					'burthen',
				],
				'burdened'=>[
					'burdend',
				],
				'burdening'=>[
					'burthening',
				],
				'burdens'=>[
					'burthens',
				],
				'burdensome'=>[
					'burthensome',
				],
				'bureau'=>[
					'bereau',
					'bureu',
				],
				'bureaucracies'=>[
					'bureaucraceis',
					'bureaucracis',
					'bureucracies',
				],
				'bureaucracy'=>[
					'beaurocracy',
					'buraucracy',
					'bureaucrasy',
					'bureucracy',
				],
				'bureaucrat'=>[
					'beaurocrat',
					'bureucrat',
				],
				'bureaucratese'=>[
					'bureucratese',
				],
				'bureaucrateses'=>[
					'bureucrateses',
				],
				'bureaucratic'=>[
					'bureacratic',
				],
				'bureaucratise'=>[
					'bureucratise',
				],
				'bureaucratised'=>[
					'bureucratised',
				],
				'bureaucratises'=>[
					'bureucratises',
				],
				'bureaucratising'=>[
					'bureucratising',
				],
				'bureaucratism'=>[
					'bureucratism',
				],
				'bureaucratisms'=>[
					'bureucratisms',
				],
				'bureaucratize'=>[
					'bureucratize',
				],
				'bureaucratized'=>[
					'bureucratized',
				],
				'bureaucratizes'=>[
					'bureucratizes',
				],
				'bureaucratizing'=>[
					'bureucratizing',
				],
				'bureaux'=>[
					'bureux',
				],
				'burgess'=>[
					'burges',
				],
				'burglar'=>[
					'burgler',
				],
				'burglarious'=>[
					'burglarous',
				],
				'burglariously'=>[
					'burglariousally',
					'burglariousaly',
					'burglariousely',
					'burglariouslly',
					'burglarously',
				],
				'burglary'=>[
					'burglery',
				],
				'burgundy'=>[
					'bourgondy',
				],
				'burial'=>[
					'buriel',
					'burrial',
				],
				'buried'=>[
					'burried',
				],
				'burlesquely'=>[
					'burlesquly',
				],
				'burly'=>[
					'burally',
					'buraly',
					'burlly',
				],
				'burmese-occupied'=>[
					'burmese occupied',
				],
				'burn'=>[
					'burn burn',
					'burn burn burn',
				],
				'burnable'=>[
					'burnible',
				],
				'burning'=>[
					'burining',
				],
				'burr'=>[
					'bur',
				],
				'burrito'=>[
					'burito',
				],
				'burro'=>[
					'buro',
				],
				'burrow'=>[
					'burow',
				],
				'burrs'=>[
					'burs',
				],
				'burrstone'=>[
					'burstone',
				],
				'burry'=>[
					'bury',
				],
				'bursar'=>[
					'burser',
				],
				'bursary'=>[
					'bursery',
				],
				'burthened'=>[
					'burthend',
				],
				'burundian-occupied'=>[
					'burundian occupied',
				],
				'bury'=>[
					'burry',
				],
				'burying'=>[
					'buring',
					'burrying',
				],
				'busbar'=>[
					'busber',
				],
				'buses'=>[
					'busses',
				],
				'bushwah'=>[
					'bushwa',
				],
				'bushwahs'=>[
					'bushwas',
				],
				'business'=>[
					'buisness',
					'busines',
					'businesss',
					'businiss',
					'busness',
					'bussines',
					'bussiness',
				],
				'businesses'=>[
					'buisnesses',
					'busineses',
				],
				'businesslike'=>[
					'buisnesslike',
					'busineslike',
					'businisslike',
				],
				'businessman'=>[
					'buisnessman',
					'businesman',
					'businissman',
				],
				'businessmen'=>[
					'buisnessmen',
				],
				'businesspeople'=>[
					'buisnesspeople',
					'businespeople',
					'businisspeople',
				],
				'businessperson'=>[
					'buisnessperson',
					'businesperson',
					'businissperson',
				],
				'businesspersons'=>[
					'buisnesspersons',
					'businisspersons',
				],
				'businesswoman'=>[
					'buisnesswoman',
					'busineswoman',
					'businisswoman',
				],
				'businesswomen'=>[
					'buisnesswomen',
					'businisswomen',
				],
				'busing'=>[
					'bussing',
				],
				'buss'=>[
					'bus',
				],
				'busses'=>[
					'buses',
				],
				'bustier'=>[
					'busteir',
					'bustir',
				],
				'busy'=>[
					'bucy',
					'busy busy',
					'busy busy busy',
				],
				'but'=>[
					'bitt',
					'but but',
					'but but but',
				],
				'butadiene'=>[
					'butadeine',
					'butadine',
				],
				'butterball'=>[
					'butterbal',
				],
				'butterfly'=>[
					'butterfally',
					'butterfaly',
					'butterfely',
					'butterflly',
				],
				'butterscotch'=>[
					'buttercotch',
					'buttercsotch',
					'buttersotch',
				],
				'butterscotches'=>[
					'buttercotches',
					'buttercsotches',
					'buttersotches',
				],
				'buttery'=>[
					'buttary',
				],
				'buttress'=>[
					'buttres',
				],
				'buy'=>[
					'buy buy',
					'buy buy buy',
				],
				'buyable'=>[
					'buyible',
				],
				'buying'=>[
					'buy-ing',
				],
				'buzzing'=>[
					'buzzling',
				],
				'by'=>[
					'bv',
					'by by',
					'by by by',
					'by by by by',
				],
				'by its'=>[
					'by it\'s',
				],
				'by the'=>[
					'by the by the',
				],
				'by-election'=>[
					'bye-election',
				],
				'byline'=>[
					'bylini',
				],
				'bylining'=>[
					'bylinang',
				],
				'bypass'=>[
					'by-pass',
					'byepass',
					'bypas',
				],
				'byssi'=>[
					'bysi',
				],
				'byssus'=>[
					'bysus',
				],
				'byzant'=>[
					'byzent',
				],
				'béla bartók'=>[
					'bela bartok',
				],
				'băneasă'=>[
					'baneasa',
				],
			];
		}
	}

?>