<?php
		
		/* UTF-8 TEST
		
			中文汉字漢字
		
		*/
				
				/* EnglishMisspellingsWords_W
					
					Class for English-Misspellings for all words beginning with : W.
					
				*/

	class EnglishMisspellingsWords_W {
			/* __construct($args)
			
				Constructor.
				
				Nothing to do here.
			
			*/
			
		public function __construct($args) {
			return TRUE;
		}
		
			/* EnglishMisspellingsWords()
			
				List of English misspellings for words starting with : W.
			
			*/

		public function EnglishMisspellingsWords() {
			return [
				'wabble'=>[
					'wable',
				],
				'wadable'=>[
					'wadible',
				],
				'wage worker'=>[
					'wageworker',
				],
				'wage-work'=>[
					'wagework',
				],
				'wage-workers'=>[
					'wageworkers',
				],
				'wagged'=>[
					'waged',
				],
				'wagger'=>[
					'wager',
				],
				'waggers'=>[
					'wagers',
				],
				'waggery'=>[
					'wagery',
				],
				'wagging'=>[
					'waging',
				],
				'waggish'=>[
					'wagish',
				],
				'waggishness'=>[
					'wagishness',
				],
				'waggishnesses'=>[
					'wagishnesses',
				],
				'waggle'=>[
					'wagle',
				],
				'waggled'=>[
					'wagled',
				],
				'waggles'=>[
					'wagles',
				],
				'waggly'=>[
					'wagly',
				],
				'waggon'=>[
					'wagon',
				],
				'waggons'=>[
					'wagons',
				],
				'wagon'=>[
					'waggon',
				],
				'wagons'=>[
					'waggons',
				],
				'wahconda'=>[
					'waconda',
				],
				'wahcondas'=>[
					'wacondas',
				],
				'wahine'=>[
					'wahini',
					'waine',
				],
				'wahoo'=>[
					'waoo',
				],
				'wahoos'=>[
					'waoos',
				],
				'wainscot'=>[
					'waincot',
					'waincsot',
					'wainsot',
				],
				'wainscoting'=>[
					'waincoting',
					'waincsoting',
					'wainsoting',
				],
				'waistline'=>[
					'waistlini',
				],
				'wait'=>[
					'wait wait',
					'wait wait wait',
				],
				'waitress'=>[
					'waitres',
				],
				'waitressing'=>[
					'waitresing',
				],
				'wakefully'=>[
					'wakefulally',
					'wakefulaly',
					'wakefulely',
					'wakefullly',
				],
				'wakened'=>[
					'wakend',
				],
				'walk'=>[
					'walk walk',
					'walk walk walk',
				],
				'wall'=>[
					'wal',
					'wall wall',
					'wall wall wall',
				],
				'walla'=>[
					'wala',
				],
				'wallah'=>[
					'walla',
				],
				'wallboard'=>[
					'walboard',
				],
				'wallet'=>[
					'walet',
				],
				'wallflower'=>[
					'walflower',
				],
				'wallop'=>[
					'walop',
				],
				'wallow'=>[
					'walow',
				],
				'wallpaper'=>[
					'walpaper',
				],
				'wally'=>[
					'walally',
					'walaly',
					'wallly',
					'waly',
				],
				'wanly'=>[
					'wanally',
					'wanaly',
					'wanlly',
				],
				'wannabe'=>[
					'wanabe',
				],
				'want'=>[
					'want want',
					'want want want',
					'watn',
					'whant',
					'wnat',
				],
				'want to'=>[
					'wanna',
				],
				'wanted'=>[
					'wented',
					'wnated',
				],
				'wanter'=>[
					'wenter',
				],
				'wanting'=>[
					'wenting',
				],
				'wanton'=>[
					'wenton',
				],
				'wants'=>[
					'want\'s',
					'wents',
					'whants',
					'wnats',
				],
				'wappenschawings'=>[
					'wapenschawings',
					'wappenchawings',
					'wappencshawings',
					'wappenshawings',
				],
				'war'=>[
					'war war',
					'war war war',
				],
				'warbonnet'=>[
					'warbonet',
				],
				'warehousing'=>[
					'warehouisng',
				],
				'warm'=>[
					'warm warm',
					'warm warm warm',
				],
				'warrant'=>[
					'warant',
					'warrent',
				],
				'warrantableness'=>[
					'warantableness',
				],
				'warrantee'=>[
					'warantee',
					'warrentee',
				],
				'warrantor'=>[
					'warantor',
				],
				'warranty'=>[
					'waranty',
					'warrenty',
				],
				'warren'=>[
					'waren',
				],
				'warrener'=>[
					'warener',
				],
				'warrigal'=>[
					'warigal',
				],
				'warrior'=>[
					'warior',
				],
				'wary'=>[
					'wery',
				],
				'was'=>[
					'was was',
					'was was was',
					'wass',
					'ws',
				],
				'was a'=>[
					'wasa',
				],
				'was being'=>[
					'was been',
				],
				'was encouraged'=>[
					'was encourage',
				],
				'was the'=>[
					'wasthe',
				],
				'wash'=>[
					'wash wash',
					'wash wash wash',
				],
				'washable'=>[
					'washible',
				],
				'washburne'=>[
					'wushburne',
				],
				'washington'=>[
					'washignton',
					'wshington',
				],
				'wasn\'t'=>[
					'was\'nt',
					'wasnt',
				],
				'wastery'=>[
					'wastary',
				],
				'watch'=>[
					'watch watch',
					'watch watch watch',
				],
				'watchable'=>[
					'watchible',
				],
				'watchdogged'=>[
					'watchdoged',
				],
				'watchdogging'=>[
					'watchdoging',
				],
				'watches'=>[
					'watchs',
				],
				'water'=>[
					'water water',
					'water water water',
				],
				'watercress'=>[
					'watercres',
				],
				'waterfall'=>[
					'waterfal',
				],
				'waterlogged'=>[
					'waterloged',
				],
				'waterlogging'=>[
					'waterloging',
				],
				'waterscape'=>[
					'watercape',
					'watercsape',
					'watersape',
				],
				'watery'=>[
					'watary',
				],
				'wave'=>[
					'wave wave',
					'wave wave wave',
				],
				'waxable'=>[
					'waxible',
				],
				'waxberry'=>[
					'waxbery',
				],
				'way'=>[
					'way way',
					'way way way',
					'waye',
				],
				'ways'=>[
					'wayes',
				],
				'we'=>[
					'wc',
					'we we',
					'we we we',
				],
				'we were'=>[
					'we we\'re',
				],
				'we\'re'=>[
					'weere',
				],
				'weak'=>[
					'wek',
				],
				'weaken'=>[
					'weken',
				],
				'weakened'=>[
					'weakend',
				],
				'weaker than'=>[
					'weaker then',
				],
				'weakly'=>[
					'weakally',
					'weakaly',
					'weakely',
					'weaklly',
					'wekly',
				],
				'weakness'=>[
					'weaknes',
					'weaknss',
					'wekness',
				],
				'weal'=>[
					'wel',
				],
				'weald'=>[
					'weld',
				],
				'wealth'=>[
					'weaIth',
					'welth',
				],
				'wealthy'=>[
					'weaIthy',
					'welthy',
				],
				'wean'=>[
					'wen',
				],
				'weapon'=>[
					'wepon',
				],
				'weaponry'=>[
					'weaponary',
					'weponry',
				],
				'wear'=>[
					'wear wear',
					'wear wear wear',
					'weer',
					'wer',
				],
				'wearability'=>[
					'werability',
				],
				'wearable'=>[
					'wearible',
					'werable',
				],
				'wearilessly'=>[
					'wearilessally',
					'wearilessaly',
					'wearilessely',
					'wearilesslly',
				],
				'wearing'=>[
					'wearilig',
					'wering',
				],
				'wearisomely'=>[
					'wearisomly',
				],
				'weary'=>[
					'weery',
					'wery',
				],
				'weasel'=>[
					'wesel',
				],
				'weasely'=>[
					'weasly',
				],
				'weather'=>[
					'weater',
					'weather weather',
					'weather weather weather',
					'wether',
					'wheather',
				],
				'weatherboard'=>[
					'wetherboard',
				],
				'weatherboarding'=>[
					'wetherboarding',
				],
				'weathered'=>[
					'wethered',
				],
				'weatherglass'=>[
					'weatherglas',
					'wetherglass',
				],
				'weathering'=>[
					'wethering',
				],
				'weatherly'=>[
					'weatherally',
					'weatheraly',
					'weatherely',
					'weatherlly',
				],
				'weatherman'=>[
					'wetherman',
				],
				'weatherproof'=>[
					'wetherproof',
				],
				'weave'=>[
					'weve',
				],
				'weaver'=>[
					'wever',
				],
				'web-based'=>[
					'web based',
					'webbased',
				],
				'webbed'=>[
					'webed',
				],
				'webbing'=>[
					'webing',
				],
				'webby'=>[
					'weby',
				],
				'webcast'=>[
					'webcasted',
				],
				'website'=>[
					'wbesite',
					'webiste',
					'websit',
					'webstie',
					'wesbite',
				],
				'wedge'=>[
					'wege',
				],
				'wedged'=>[
					'weged',
				],
				'wedgelike'=>[
					'wegelike',
				],
				'wedges'=>[
					'weges',
				],
				'wednesday'=>[
					'wendesday',
					'wendsay',
					'wendsday',
					'wensday',
				],
				'week'=>[
					'week week',
					'week week week',
				],
				'weekend'=>[
					'weekened',
				],
				'weekly'=>[
					'weekally',
					'weekaly',
					'weekely',
					'weeklly',
				],
				'weened'=>[
					'weend',
				],
				'weenie'=>[
					'weenei',
					'weeni',
				],
				'weensy'=>[
					'weency',
				],
				'weigela'=>[
					'wiegela',
				],
				'weigh'=>[
					'wiegh',
				],
				'weight'=>[
					'weight weight',
					'weight weight weight',
					'weigth',
					'wieght',
				],
				'weighted'=>[
					'wieghted',
				],
				'weightinesses'=>[
					'wieghtinesses',
				],
				'weightless'=>[
					'weightles',
					'wieghtless',
				],
				'weightlessly'=>[
					'wieghtlessly',
				],
				'weightlessness'=>[
					'wieghtlessness',
				],
				'weighty'=>[
					'wieghty',
				],
				'weir'=>[
					'wier',
				],
				'weird'=>[
					'wierd',
				],
				'weirdie'=>[
					'wierdie',
				],
				'weirdo'=>[
					'wierdo',
				],
				'weirs'=>[
					'wiers',
				],
				'weisenheimer'=>[
					'weisenhiemer',
				],
				'weisenheimers'=>[
					'weisenhiemers',
				],
				'welcomed'=>[
					'welcame',
				],
				'welcomely'=>[
					'welcomly',
				],
				'welfare'=>[
					'wellfare',
				],
				'well'=>[
					'we11',
					'we1l',
					'weii',
					'weil',
					'wel',
					'wel1',
					'weli',
					'well well',
					'well well well',
				],
				'well conceived'=>[
					'wellconceived',
				],
				'well known'=>[
					'wellknown',
				],
				'well-being'=>[
					'wellbeing',
				],
				'well-demarcated area'=>[
					'well demarcated area',
				],
				'well-known'=>[
					'well known',
				],
				'well-ordered'=>[
					'wellordered',
				],
				'wellbutrin'=>[
					'welbutrin',
				],
				'wellhead'=>[
					'welhead',
				],
				'wellness'=>[
					'wellnes',
					'welness',
				],
				'wellspring'=>[
					'welspring',
				],
				'welly'=>[
					'welally',
					'welaly',
					'wellly',
				],
				'weltanschauungs'=>[
					'weltanchauungs',
					'weltancshauungs',
					'weltanshauungs',
				],
				'welterweight'=>[
					'welterwieght',
				],
				'welterweights'=>[
					'welterwieghts',
				],
				'wenny'=>[
					'weny',
				],
				'went'=>[
					'want',
					'went went',
					'went went went',
					'whent',
				],
				'were'=>[
					'weere',
					'were were',
					'were were were',
					'wewre',
					'wre',
				],
				'were being'=>[
					'were been',
				],
				'weren\'t'=>[
					'were\'nt',
					'werent',
				],
				'west'=>[
					'west west',
					'west west west',
				],
				'westerly'=>[
					'westerally',
					'westeraly',
					'westerely',
					'westerlly',
				],
				'westernmost'=>[
					'westermost',
					'westernost',
				],
				'wetly'=>[
					'wetally',
					'wetaly',
					'wetlly',
				],
				'wetness'=>[
					'wetnes',
				],
				'whack'=>[
					'wack',
				],
				'whacked'=>[
					'wacked',
				],
				'whacker'=>[
					'wacker',
				],
				'whackers'=>[
					'wackers',
				],
				'whackier'=>[
					'wackier',
				],
				'whackiest'=>[
					'wackiest',
				],
				'whacking'=>[
					'wacking',
				],
				'whacko'=>[
					'wacko',
				],
				'whackos'=>[
					'wackos',
				],
				'whacks'=>[
					'wacks',
				],
				'whacky'=>[
					'wacky',
				],
				'whale'=>[
					'wale',
				],
				'whaleback'=>[
					'waleback',
				],
				'whalebacks'=>[
					'walebacks',
				],
				'whaleboat'=>[
					'waleboat',
				],
				'whaleboats'=>[
					'waleboats',
				],
				'whalebone'=>[
					'walebone',
				],
				'whalebones'=>[
					'walebones',
				],
				'whaled'=>[
					'waled',
				],
				'whalelike'=>[
					'walelike',
				],
				'whaleman'=>[
					'waleman',
				],
				'whalemen'=>[
					'walemen',
				],
				'whaler'=>[
					'waler',
				],
				'whalers'=>[
					'walers',
				],
				'whales'=>[
					'wales',
				],
				'whaling'=>[
					'waling',
				],
				'whalings'=>[
					'walings',
				],
				'wham'=>[
					'wam',
				],
				'whammed'=>[
					'wammed',
				],
				'whammies'=>[
					'wammies',
				],
				'whamming'=>[
					'wamming',
				],
				'whammo'=>[
					'wammo',
					'whamno',
				],
				'whammy'=>[
					'wammy',
					'whamny',
				],
				'whamo'=>[
					'wamo',
				],
				'whams'=>[
					'wams',
				],
				'whang'=>[
					'wang',
				],
				'whanged'=>[
					'wanged',
				],
				'whangee'=>[
					'wangee',
				],
				'whangees'=>[
					'wangees',
				],
				'whanging'=>[
					'wanging',
				],
				'whangs'=>[
					'wangs',
				],
				'whap'=>[
					'wap',
				],
				'whapped'=>[
					'wapped',
				],
				'whapper'=>[
					'wapper',
				],
				'whappers'=>[
					'wappers',
				],
				'whapping'=>[
					'wapping',
				],
				'whaps'=>[
					'waps',
				],
				'wharf'=>[
					'warf',
				],
				'wharfage'=>[
					'warfage',
				],
				'wharfages'=>[
					'warfages',
				],
				'wharfed'=>[
					'warfed',
				],
				'wharfing'=>[
					'warfing',
				],
				'wharfinger'=>[
					'warfinger',
				],
				'wharfingers'=>[
					'warfingers',
				],
				'wharfmaster'=>[
					'warfmaster',
				],
				'wharfmasters'=>[
					'warfmasters',
				],
				'wharfs'=>[
					'warfs',
				],
				'wharve'=>[
					'warve',
				],
				'wharves'=>[
					'warves',
				],
				'what'=>[
					'waht',
					'wat',
					'what what',
					'what what what',
					'whta',
				],
				'whatchamacallit'=>[
					'watchamacallit',
					'whatchamacalit',
				],
				'whatever'=>[
					'watever',
					'wiiatevcr',
				],
				'whatness'=>[
					'watness',
				],
				'whatnesses'=>[
					'watnesses',
				],
				'whatnot'=>[
					'watnot',
				],
				'whatnots'=>[
					'watnots',
				],
				'whats'=>[
					'wats',
				],
				'whatsis'=>[
					'watsis',
				],
				'whatsises'=>[
					'watsises',
				],
				'whatsit'=>[
					'watsit',
				],
				'whatsits'=>[
					'watsits',
				],
				'whatsoever'=>[
					'watsoever',
				],
				'whaup'=>[
					'waup',
				],
				'whaups'=>[
					'waups',
				],
				'wheal'=>[
					'weal',
					'whel',
				],
				'wheals'=>[
					'weals',
				],
				'wheat'=>[
					'weat',
					'wheet',
					'whet',
				],
				'wheatear'=>[
					'weatear',
					'wheateer',
				],
				'wheatears'=>[
					'weatears',
				],
				'wheaten'=>[
					'weaten',
				],
				'wheatens'=>[
					'weatens',
				],
				'wheatland'=>[
					'weatland',
				],
				'wheatless'=>[
					'weatless',
				],
				'wheats'=>[
					'weats',
				],
				'wheatworm'=>[
					'weatworm',
				],
				'wheatworms'=>[
					'weatworms',
				],
				'whee'=>[
					'wee',
				],
				'wheedle'=>[
					'weedle',
				],
				'wheedled'=>[
					'weedled',
				],
				'wheedler'=>[
					'weedler',
				],
				'wheedlers'=>[
					'weedlers',
				],
				'wheedles'=>[
					'weedles',
				],
				'wheedling'=>[
					'weedling',
				],
				'wheel'=>[
					'weel',
					'wheel wheel',
					'wheel wheel wheel',
				],
				'wheelbarrow'=>[
					'weelbarrow',
					'wheelbarow',
					'wheelbarrel',
				],
				'wheelbarrowed'=>[
					'weelbarrowed',
				],
				'wheelbarrowing'=>[
					'weelbarrowing',
				],
				'wheelbarrows'=>[
					'weelbarrows',
				],
				'wheelbase'=>[
					'weelbase',
				],
				'wheelbases'=>[
					'weelbases',
				],
				'wheelchair'=>[
					'weelchair',
				],
				'wheelchairs'=>[
					'weelchairs',
				],
				'wheeled'=>[
					'weeled',
				],
				'wheeler'=>[
					'weeler',
				],
				'wheelers'=>[
					'weelers',
				],
				'wheelhorse'=>[
					'weelhorse',
				],
				'wheelhorses'=>[
					'weelhorses',
				],
				'wheelhouse'=>[
					'weelhouse',
				],
				'wheelhouses'=>[
					'weelhouses',
				],
				'wheelie'=>[
					'weelie',
					'wheelei',
					'wheeli',
				],
				'wheelies'=>[
					'weelies',
				],
				'wheeling'=>[
					'weeling',
				],
				'wheelings'=>[
					'weelings',
				],
				'wheelless'=>[
					'weelless',
				],
				'wheelman'=>[
					'weelman',
				],
				'wheelmen'=>[
					'weelmen',
				],
				'wheels'=>[
					'weels',
				],
				'wheelsman'=>[
					'weelsman',
				],
				'wheelsmen'=>[
					'weelsmen',
				],
				'wheelwork'=>[
					'weelwork',
				],
				'wheelworks'=>[
					'weelworks',
				],
				'wheelwright'=>[
					'weelwright',
				],
				'wheelwrights'=>[
					'weelwrights',
				],
				'wheen'=>[
					'ween',
				],
				'wheens'=>[
					'weens',
				],
				'wheep'=>[
					'weep',
				],
				'wheeped'=>[
					'weeped',
				],
				'wheeping'=>[
					'weeping',
				],
				'wheeple'=>[
					'weeple',
				],
				'wheepled'=>[
					'weepled',
				],
				'wheeples'=>[
					'weeples',
				],
				'wheepling'=>[
					'weepling',
				],
				'wheeps'=>[
					'weeps',
				],
				'wheeze'=>[
					'weeze',
				],
				'wheezed'=>[
					'weezed',
				],
				'wheezer'=>[
					'weezer',
				],
				'wheezers'=>[
					'weezers',
				],
				'wheezes'=>[
					'weezes',
				],
				'wheezier'=>[
					'weezier',
				],
				'wheeziest'=>[
					'weeziest',
				],
				'wheezily'=>[
					'weezily',
				],
				'wheeziness'=>[
					'weeziness',
				],
				'wheezinesses'=>[
					'weezinesses',
				],
				'wheezing'=>[
					'weezing',
				],
				'wheezy'=>[
					'weezy',
				],
				'whelk'=>[
					'welk',
				],
				'whelkier'=>[
					'welkier',
				],
				'whelkiest'=>[
					'welkiest',
				],
				'whelks'=>[
					'welks',
				],
				'whelky'=>[
					'welky',
				],
				'whelm'=>[
					'welm',
				],
				'whelmed'=>[
					'welmed',
				],
				'whelming'=>[
					'welming',
				],
				'whelms'=>[
					'welms',
				],
				'whelp'=>[
					'welp',
				],
				'whelped'=>[
					'welped',
				],
				'whelping'=>[
					'welping',
				],
				'whelpless'=>[
					'welpless',
				],
				'whelps'=>[
					'welps',
				],
				'when'=>[
					'wehn',
					'wen',
					'whcn',
					'when when',
					'when when when',
				],
				'whenas'=>[
					'wenas',
				],
				'whence'=>[
					'wence',
					'whance',
				],
				'whencesoever'=>[
					'wencesoever',
				],
				'whenever'=>[
					'wenever',
				],
				'whens'=>[
					'wens',
				],
				'whensoever'=>[
					'wensoever',
				],
				'where'=>[
					'were',
					'where where',
					'where where where',
					'wheree',
				],
				'whereabout'=>[
					'wereabout',
				],
				'whereabouts'=>[
					'wereabouts',
					'wherabouts',
					'wherebouts',
				],
				'whereas'=>[
					'wereas',
					'wheras',
					'where as',
					'wheres',
				],
				'whereases'=>[
					'wereases',
				],
				'whereat'=>[
					'wereat',
				],
				'whereby'=>[
					'wereby',
					'wherby',
				],
				'wherefore'=>[
					'werefore',
				],
				'wherefores'=>[
					'werefores',
				],
				'wherefrom'=>[
					'werefrom',
				],
				'wherein'=>[
					'werein',
					'wherien',
					'wherin',
				],
				'whereinto'=>[
					'wereinto',
					'wheriento',
				],
				'whereof'=>[
					'wereof',
				],
				'whereon'=>[
					'wereon',
				],
				'wheres'=>[
					'weres',
				],
				'wheresoever'=>[
					'weresoever',
				],
				'wherethrough'=>[
					'werethrough',
				],
				'whereto'=>[
					'wereto',
				],
				'whereunto'=>[
					'wereunto',
				],
				'whereupon'=>[
					'wereupon',
					'where upon',
				],
				'wherever'=>[
					'werever',
					'where ever',
					'whereever',
				],
				'wherewith'=>[
					'werewith',
				],
				'wherewithal'=>[
					'werewithal',
					'wherewital',
				],
				'wherewithals'=>[
					'werewithals',
				],
				'wherewiths'=>[
					'werewiths',
				],
				'wherried'=>[
					'werried',
				],
				'wherries'=>[
					'werries',
				],
				'wherry'=>[
					'werry',
					'whery',
				],
				'wherrying'=>[
					'werrying',
				],
				'wherve'=>[
					'werve',
				],
				'wherves'=>[
					'werves',
				],
				'whet'=>[
					'wet',
				],
				'whether'=>[
					'wether',
					'whether whether',
					'whether whether whether',
					'whetlier',
				],
				'whets'=>[
					'wets',
				],
				'whetstone'=>[
					'wetstone',
				],
				'whetstones'=>[
					'wetstones',
				],
				'whetted'=>[
					'wetted',
				],
				'whetter'=>[
					'wetter',
				],
				'whetters'=>[
					'wetters',
				],
				'whetting'=>[
					'wetting',
				],
				'whew'=>[
					'wew',
				],
				'whews'=>[
					'wews',
				],
				'whey'=>[
					'wey',
				],
				'wheyey'=>[
					'weyey',
				],
				'wheyface'=>[
					'weyface',
				],
				'wheyfaced'=>[
					'weyfaced',
				],
				'wheyfaces'=>[
					'weyfaces',
				],
				'wheyish'=>[
					'weyish',
				],
				'wheylike'=>[
					'weylike',
				],
				'wheys'=>[
					'weys',
				],
				'which'=>[
					'hwihc',
					'whach',
					'whcih',
					'whic',
					'which which',
					'which which which',
					'whicli',
					'whihc',
					'whoch',
					'wich',
				],
				'whichever'=>[
					'wichever',
				],
				'whichsoever'=>[
					'wichsoever',
				],
				'whicker'=>[
					'wicker',
				],
				'whickered'=>[
					'wickered',
				],
				'whickering'=>[
					'wickering',
				],
				'whickers'=>[
					'wickers',
				],
				'whid'=>[
					'wid',
				],
				'whidah'=>[
					'whida',
					'widah',
				],
				'whidahs'=>[
					'widahs',
				],
				'whidded'=>[
					'widded',
				],
				'whidding'=>[
					'widding',
				],
				'whids'=>[
					'wids',
				],
				'whiff'=>[
					'wiff',
				],
				'whiffed'=>[
					'wiffed',
				],
				'whiffer'=>[
					'wiffer',
				],
				'whiffers'=>[
					'wiffers',
				],
				'whiffet'=>[
					'wiffet',
				],
				'whiffets'=>[
					'wiffets',
				],
				'whiffle'=>[
					'wiffle',
				],
				'whiffled'=>[
					'wiffled',
				],
				'whifflers'=>[
					'wifflers',
				],
				'whiffles'=>[
					'wiffles',
				],
				'whiffletree'=>[
					'wiffletree',
				],
				'whiffletrees'=>[
					'wiffletrees',
				],
				'whiffling'=>[
					'wiffling',
				],
				'whiffs'=>[
					'wiffs',
				],
				'whig'=>[
					'wig',
				],
				'whigmaleerie'=>[
					'wigmaleerie',
				],
				'whigmaleeries'=>[
					'wigmaleeries',
				],
				'whigs'=>[
					'wigs',
				],
				'while'=>[
					'hwile',
					'while while',
					'while while while',
					'whilest',
					'whilst',
					'wile',
				],
				'whiled'=>[
					'wiled',
				],
				'whiles'=>[
					'wiles',
				],
				'whiling'=>[
					'wiling',
				],
				'whilom'=>[
					'wilom',
				],
				'whilst'=>[
					'wilst',
				],
				'whim'=>[
					'wim',
				],
				'whimbrel'=>[
					'wimbrel',
				],
				'whimbrels'=>[
					'wimbrels',
				],
				'whimper'=>[
					'wimper',
				],
				'whimpered'=>[
					'wimpered',
				],
				'whimperer'=>[
					'wimperer',
				],
				'whimperers'=>[
					'wimperers',
				],
				'whimpering'=>[
					'wimpering',
				],
				'whimpers'=>[
					'wimpers',
				],
				'whims'=>[
					'wims',
				],
				'whimsey'=>[
					'wimsey',
				],
				'whimseys'=>[
					'wimseys',
				],
				'whimsical'=>[
					'wimsical',
				],
				'whimsicalities'=>[
					'wimsicalities',
				],
				'whimsicality'=>[
					'wimsicality',
				],
				'whimsically'=>[
					'wimsically',
				],
				'whimsicalness'=>[
					'wimsicalness',
				],
				'whimsicalnesses'=>[
					'wimsicalnesses',
				],
				'whimsied'=>[
					'wimsied',
				],
				'whimsies'=>[
					'wimsies',
				],
				'whimsy'=>[
					'whimcy',
					'wimsy',
				],
				'whin'=>[
					'win',
				],
				'whinchat'=>[
					'winchat',
				],
				'whinchats'=>[
					'winchats',
				],
				'whine'=>[
					'whini',
					'wine',
				],
				'whined'=>[
					'wined',
				],
				'whiner'=>[
					'winer',
				],
				'whiners'=>[
					'winers',
				],
				'whines'=>[
					'wines',
				],
				'whiney'=>[
					'winey',
				],
				'whingding'=>[
					'wingding',
				],
				'whingdings'=>[
					'wingdings',
				],
				'whinge'=>[
					'winge',
				],
				'whinged'=>[
					'winged',
				],
				'whingeing'=>[
					'wingeing',
				],
				'whinger'=>[
					'winger',
				],
				'whingers'=>[
					'wingers',
				],
				'whinges'=>[
					'winges',
				],
				'whinging'=>[
					'winging',
				],
				'whinier'=>[
					'whinaer',
					'winier',
				],
				'whiniest'=>[
					'winiest',
				],
				'whininess'=>[
					'wininess',
				],
				'whininesses'=>[
					'wininesses',
				],
				'whining'=>[
					'whinang',
					'whinning',
					'wining',
				],
				'whiningly'=>[
					'winingly',
				],
				'whinnied'=>[
					'winnied',
				],
				'whinnier'=>[
					'winnier',
				],
				'whinnies'=>[
					'winnies',
				],
				'whinniest'=>[
					'winniest',
				],
				'whinny'=>[
					'whiny',
					'winny',
				],
				'whinnying'=>[
					'winnying',
				],
				'whins'=>[
					'wins',
				],
				'whinstone'=>[
					'winstone',
				],
				'whinstones'=>[
					'winstones',
				],
				'whiny'=>[
					'winy',
				],
				'whip'=>[
					'wip',
				],
				'whipcord'=>[
					'wipcord',
				],
				'whipcords'=>[
					'wipcords',
				],
				'whiplash'=>[
					'wiplash',
				],
				'whiplashes'=>[
					'wiplashes',
				],
				'whiplike'=>[
					'wiplike',
				],
				'whipped'=>[
					'wipped',
				],
				'whipper'=>[
					'wipper',
				],
				'whippers'=>[
					'wippers',
				],
				'whippersnapper'=>[
					'whippersnaper',
					'wippersnapper',
				],
				'whippersnappers'=>[
					'whippersnapers',
					'wippersnappers',
				],
				'whippet'=>[
					'whipet',
					'wippet',
				],
				'whippets'=>[
					'wippets',
				],
				'whippier'=>[
					'wippier',
				],
				'whippiest'=>[
					'wippiest',
				],
				'whipping'=>[
					'whiping',
					'wipping',
				],
				'whippings'=>[
					'wippings',
				],
				'whippletree'=>[
					'whipletree',
					'wippletree',
				],
				'whippletrees'=>[
					'wippletrees',
				],
				'whippoorwill'=>[
					'whipoorwill',
					'whippoorwil',
					'wippoorwill',
				],
				'whippoorwills'=>[
					'whipoorwills',
					'wippoorwills',
				],
				'whippy'=>[
					'whipy',
					'wippy',
				],
				'whipray'=>[
					'wipray',
				],
				'whiprays'=>[
					'wiprays',
				],
				'whips'=>[
					'wips',
				],
				'whipsaw'=>[
					'wipsaw',
				],
				'whipsawed'=>[
					'wipsawed',
				],
				'whipsawing'=>[
					'wipsawing',
				],
				'whipsawn'=>[
					'wipsawn',
				],
				'whipsaws'=>[
					'wipsaws',
				],
				'whipsnake'=>[
					'wipsnake',
				],
				'whipsnakes'=>[
					'wipsnakes',
				],
				'whipstall'=>[
					'wipstall',
				],
				'whipstalls'=>[
					'wipstalls',
				],
				'whipstitch'=>[
					'wipstitch',
				],
				'whipstitched'=>[
					'wipstitched',
				],
				'whipstitches'=>[
					'wipstitches',
				],
				'whipstitching'=>[
					'wipstitching',
				],
				'whipstock'=>[
					'wipstock',
				],
				'whipstocks'=>[
					'wipstocks',
				],
				'whipt'=>[
					'wipt',
				],
				'whiptail'=>[
					'wiptail',
				],
				'whiptails'=>[
					'wiptails',
				],
				'whipworm'=>[
					'wipworm',
				],
				'whipworms'=>[
					'wipworms',
				],
				'whir'=>[
					'wir',
				],
				'whirl'=>[
					'wirl',
				],
				'whirled'=>[
					'wirled',
				],
				'whirler'=>[
					'wirler',
				],
				'whirlers'=>[
					'wirlers',
				],
				'whirlier'=>[
					'wirlier',
				],
				'whirlies'=>[
					'wirlies',
				],
				'whirliest'=>[
					'wirliest',
				],
				'whirligig'=>[
					'wirligig',
				],
				'whirligigs'=>[
					'wirligigs',
				],
				'whirling'=>[
					'wirling',
				],
				'whirlpool'=>[
					'wirlpool',
				],
				'whirlpools'=>[
					'wirlpools',
				],
				'whirls'=>[
					'wirls',
				],
				'whirlwind'=>[
					'wirlwind',
				],
				'whirlwinds'=>[
					'wirlwinds',
				],
				'whirly'=>[
					'wirly',
				],
				'whirlybird'=>[
					'wirlybird',
				],
				'whirlybirds'=>[
					'wirlybirds',
				],
				'whirr'=>[
					'whir',
					'wirr',
				],
				'whirred'=>[
					'wirred',
				],
				'whirried'=>[
					'wirried',
				],
				'whirries'=>[
					'wirries',
				],
				'whirring'=>[
					'wirring',
				],
				'whirrs'=>[
					'wirrs',
				],
				'whirry'=>[
					'wirry',
				],
				'whirrying'=>[
					'wirrying',
				],
				'whirs'=>[
					'wirs',
				],
				'whish'=>[
					'wish',
				],
				'whished'=>[
					'wished',
				],
				'whishes'=>[
					'wishes',
				],
				'whishing'=>[
					'wishing',
				],
				'whisht'=>[
					'wisht',
				],
				'whishted'=>[
					'wishted',
				],
				'whishting'=>[
					'wishting',
				],
				'whishts'=>[
					'wishts',
				],
				'whisk'=>[
					'wisk',
				],
				'whisked'=>[
					'wisked',
				],
				'whisker'=>[
					'wisker',
				],
				'whiskered'=>[
					'wiskered',
				],
				'whiskers'=>[
					'wiskers',
				],
				'whiskery'=>[
					'wiskery',
				],
				'whiskey'=>[
					'whisky',
					'wiskey',
				],
				'whiskeys'=>[
					'wiskeys',
				],
				'whiskies'=>[
					'wiskies',
				],
				'whisking'=>[
					'wisking',
				],
				'whisks'=>[
					'wisks',
				],
				'whisky'=>[
					'wisky',
				],
				'whisper'=>[
					'wisper',
				],
				'whispered'=>[
					'wispered',
				],
				'whisperer'=>[
					'wisperer',
				],
				'whisperers'=>[
					'wisperers',
				],
				'whispering'=>[
					'wispering',
				],
				'whisperingly'=>[
					'wisperingly',
				],
				'whisperings'=>[
					'wisperings',
				],
				'whist'=>[
					'wist',
				],
				'whisted'=>[
					'wisted',
				],
				'whistle'=>[
					'wistle',
				],
				'whistleable'=>[
					'wistleable',
				],
				'whistler'=>[
					'wistler',
				],
				'whistlers'=>[
					'wistlers',
				],
				'whistling'=>[
					'wistling',
				],
				'whistlings'=>[
					'wistlings',
				],
				'whists'=>[
					'wists',
				],
				'whit'=>[
					'wit',
				],
				'white'=>[
					'white white',
					'white white white',
					'wite',
				],
				'whitebait'=>[
					'witebait',
				],
				'whitebaits'=>[
					'witebaits',
				],
				'whitebeard'=>[
					'witebeard',
				],
				'whitebeards'=>[
					'witebeards',
				],
				'whitecap'=>[
					'witecap',
				],
				'whitecaps'=>[
					'witecaps',
				],
				'whitecomb'=>[
					'witecomb',
				],
				'whitecombs'=>[
					'witecombs',
				],
				'whited'=>[
					'wited',
				],
				'whiteface'=>[
					'witeface',
				],
				'whitefaces'=>[
					'witefaces',
				],
				'whitefish'=>[
					'witefish',
				],
				'whitefishes'=>[
					'witefishes',
				],
				'whiteflies'=>[
					'witeflies',
				],
				'whitefly'=>[
					'whitefally',
					'whitefaly',
					'whitefely',
					'whiteflly',
					'witefly',
				],
				'whitehead'=>[
					'whitehed',
					'witehead',
				],
				'whiteheads'=>[
					'witeheads',
				],
				'whitely'=>[
					'whately',
					'whitly',
					'witely',
				],
				'whiten'=>[
					'witen',
				],
				'whitened'=>[
					'whitend',
				],
				'whiteners'=>[
					'witeners',
				],
				'whiteness'=>[
					'witeness',
				],
				'whitenesses'=>[
					'witenesses',
				],
				'whitening'=>[
					'witening',
				],
				'whitenings'=>[
					'witenings',
				],
				'whitens'=>[
					'witens',
				],
				'whiteout'=>[
					'witeout',
				],
				'whiteouts'=>[
					'witeouts',
				],
				'whiter'=>[
					'witer',
				],
				'whites'=>[
					'wites',
				],
				'whitesmith'=>[
					'witesmith',
				],
				'whitesmiths'=>[
					'witesmiths',
				],
				'whitest'=>[
					'witest',
				],
				'whitetail'=>[
					'witetail',
				],
				'whitetails'=>[
					'witetails',
				],
				'whitethroat'=>[
					'witethroat',
				],
				'whitethroats'=>[
					'witethroats',
				],
				'whitewall'=>[
					'witewall',
				],
				'whitewalls'=>[
					'witewalls',
				],
				'whitewash'=>[
					'witewash',
				],
				'whitewashed'=>[
					'witewashed',
				],
				'whitewasher'=>[
					'witewasher',
				],
				'whitewashers'=>[
					'witewashers',
				],
				'whitewashes'=>[
					'witewashes',
				],
				'whitewashing'=>[
					'witewashing',
				],
				'whitewashings'=>[
					'witewashings',
				],
				'whitewing'=>[
					'witewing',
				],
				'whitewings'=>[
					'witewings',
				],
				'whitewood'=>[
					'witewood',
				],
				'whitewoods'=>[
					'witewoods',
				],
				'whitey'=>[
					'witey',
				],
				'whiteys'=>[
					'witeys',
				],
				'whither'=>[
					'wither',
				],
				'whithersoever'=>[
					'withersoever',
				],
				'whitherward'=>[
					'witherward',
				],
				'whitier'=>[
					'witier',
				],
				'whities'=>[
					'wities',
				],
				'whiting'=>[
					'witing',
				],
				'whitish'=>[
					'witish',
				],
				'whitlow'=>[
					'witlow',
				],
				'whitracks'=>[
					'witracks',
				],
				'whits'=>[
					'wits',
				],
				'whitter'=>[
					'witter',
				],
				'whittle'=>[
					'wittle',
				],
				'whittlers'=>[
					'wittlers',
				],
				'whittling'=>[
					'wittling',
				],
				'whittlings'=>[
					'wittlings',
				],
				'whittrets'=>[
					'wittrets',
				],
				'whity'=>[
					'wity',
				],
				'whiz'=>[
					'wiz',
				],
				'whizz'=>[
					'wizz',
				],
				'whizzbangs'=>[
					'wizzbangs',
				],
				'whizzed'=>[
					'wizzed',
				],
				'whizzy'=>[
					'wizzy',
				],
				'who'=>[
					'swho',
					'who who',
					'who who who',
				],
				'who\'s'=>[
					'whos',
				],
				'whoa'=>[
					'woa',
				],
				'whodunit'=>[
					'wodunit',
				],
				'whodunnits'=>[
					'wodunnits',
				],
				'whoever'=>[
					'woever',
				],
				'whole'=>[
					'hwole',
					'whole whole',
					'whole whole whole',
					'wohle',
					'wole',
				],
				'wholehearted'=>[
					'wholeherted',
					'wolehearted',
				],
				'wholeheartedly'=>[
					'woleheartedly',
				],
				'wholemeal'=>[
					'wolemeal',
				],
				'wholeness'=>[
					'woleness',
				],
				'wholenesses'=>[
					'wolenesses',
				],
				'wholes'=>[
					'woles',
				],
				'wholesale'=>[
					'wolesale',
				],
				'wholesaled'=>[
					'wolesaled',
				],
				'wholesaler'=>[
					'wolesaler',
				],
				'wholesalers'=>[
					'wolesalers',
				],
				'wholesales'=>[
					'wolesales',
				],
				'wholesaling'=>[
					'wolesaling',
				],
				'wholesome'=>[
					'wholsome',
					'wolesome',
				],
				'wholesomely'=>[
					'wholesomly',
					'wolesomely',
				],
				'wholesomeness'=>[
					'wholsomeness',
					'wolesomeness',
				],
				'wholesomenesses'=>[
					'wolesomenesses',
				],
				'wholesomer'=>[
					'wolesomer',
				],
				'wholesomest'=>[
					'wolesomest',
				],
				'wholism'=>[
					'wolism',
				],
				'wholistic'=>[
					'wolistic',
				],
				'wholly'=>[
					'wholally',
					'wholaly',
					'wholely',
					'wholey',
					'wholley',
					'whollly',
					'wholy',
					'wolly',
				],
				'whom'=>[
					'whon',
					'wom',
				],
				'whom he recorded'=>[
					'who he recorded',
				],
				'whomever'=>[
					'womever',
				],
				'whomp'=>[
					'womp',
				],
				'whomped'=>[
					'womped',
				],
				'whomps'=>[
					'womps',
				],
				'whomso'=>[
					'womso',
				],
				'whomsoever'=>[
					'womsoever',
				],
				'whoof'=>[
					'woof',
				],
				'whoofed'=>[
					'woofed',
				],
				'whoofs'=>[
					'woofs',
				],
				'whoop'=>[
					'woop',
				],
				'whooped'=>[
					'wooped',
				],
				'whoopee'=>[
					'woopee',
				],
				'whooper'=>[
					'wooper',
				],
				'whoopla'=>[
					'woopla',
				],
				'whoops'=>[
					'woops',
				],
				'whoosh'=>[
					'woosh',
				],
				'whooshing'=>[
					'wooshing',
				],
				'whoosis'=>[
					'woosis',
				],
				'whoosises'=>[
					'woosises',
				],
				'whop'=>[
					'wop',
				],
				'whopped'=>[
					'wopped',
				],
				'whopper'=>[
					'whoper',
					'wopper',
				],
				'whopping'=>[
					'whoping',
					'wopping',
				],
				'whops'=>[
					'wops',
				],
				'whore'=>[
					'wore',
				],
				'whored'=>[
					'wored',
				],
				'whoredom'=>[
					'woredom',
				],
				'whoredoms'=>[
					'woredoms',
				],
				'whorehouse'=>[
					'worehouse',
				],
				'whorehouses'=>[
					'worehouses',
				],
				'whoremaster'=>[
					'woremaster',
				],
				'whoremasters'=>[
					'woremasters',
				],
				'whoremonger'=>[
					'woremonger',
				],
				'whoremongers'=>[
					'woremongers',
				],
				'whores'=>[
					'wores',
				],
				'whoreson'=>[
					'woreson',
				],
				'whoresons'=>[
					'woresons',
				],
				'whoring'=>[
					'woring',
				],
				'whorish'=>[
					'worish',
				],
				'whorishly'=>[
					'worishly',
				],
				'whorl'=>[
					'worl',
				],
				'whorled'=>[
					'worled',
				],
				'whorls'=>[
					'worls',
				],
				'whort'=>[
					'wort',
				],
				'whortle'=>[
					'wortle',
				],
				'whortleberries'=>[
					'wortleberries',
				],
				'whortleberry'=>[
					'whortlebery',
					'wortleberry',
				],
				'whorts'=>[
					'worts',
				],
				'whose'=>[
					'whose whose',
					'whose whose whose',
					'wose',
				],
				'whosesoever'=>[
					'wosesoever',
				],
				'whosever'=>[
					'wosever',
				],
				'whosis'=>[
					'wosis',
				],
				'whoso'=>[
					'woso',
				],
				'whosoever'=>[
					'wosoever',
				],
				'whump'=>[
					'wump',
				],
				'whumps'=>[
					'wumps',
				],
				'whup'=>[
					'wup',
				],
				'whups'=>[
					'wups',
				],
				'why'=>[
					'why why',
					'why why why',
				],
				'whydah'=>[
					'whyda',
					'wydah',
				],
				'whys'=>[
					'wys',
				],
				'wicca'=>[
					'wica',
				],
				'wiccan'=>[
					'wican',
				],
				'wiccans'=>[
					'wicans',
				],
				'wiccas'=>[
					'wicas',
				],
				'wide'=>[
					'wide wide',
					'wide wide wide',
				],
				'widely'=>[
					'widelly',
					'widly',
				],
				'widened'=>[
					'widend',
				],
				'widespread'=>[
					'widesperead',
					'widespred',
				],
				'wield'=>[
					'weild',
				],
				'wielded'=>[
					'weilded',
				],
				'wiener'=>[
					'weiner',
					'winer',
				],
				'wienerwurst'=>[
					'weinerwurst',
					'winerwurst',
				],
				'wife'=>[
					'wief',
					'wife wife',
					'wife wife wife',
				],
				'wife\'s'=>[
					'wifes',
					'wifes\'',
				],
				'wifely'=>[
					'wifeally',
					'wifealy',
					'wifeely',
					'wifelly',
					'wifly',
				],
				'wigged'=>[
					'wiged',
				],
				'wiggery'=>[
					'wigery',
				],
				'wiggier'=>[
					'wigier',
				],
				'wigging'=>[
					'wiging',
				],
				'wiggle'=>[
					'wigle',
				],
				'wiggled'=>[
					'wigled',
				],
				'wiggler'=>[
					'wigler',
				],
				'wiggles'=>[
					'wigles',
				],
				'wiggly'=>[
					'wigly',
				],
				'wiggy'=>[
					'wigy',
				],
				'wigwaggers'=>[
					'wigwagers',
				],
				'wigwagging'=>[
					'wigwaging',
				],
				'wikipedia'=>[
					'wikipadia',
					'wikipeidaintramural',
					'wikipeuia',
				],
				'wild'=>[
					'wild wild',
					'wild wild wild',
				],
				'wilderness'=>[
					'wildernes',
				],
				'will'=>[
					'iwll',
					'v. ill',
					'v.ill',
					'wil',
					'will will',
					'will will will',
					'wiull',
					'wlil',
				],
				'willed'=>[
					'wiled',
				],
				'willet'=>[
					'wilet',
				],
				'willful'=>[
					'wilful',
				],
				'william'=>[
					'willliam',
				],
				'willies'=>[
					'willeis',
					'willis',
				],
				'willing'=>[
					'wiling',
				],
				'willingness'=>[
					'willingess',
				],
				'willow'=>[
					'wilow',
				],
				'willpower'=>[
					'wilpower',
				],
				'willy'=>[
					'wilally',
					'wilaly',
					'willly',
					'wily',
				],
				'wimmin'=>[
					'wimnin',
				],
				'win'=>[
					'win win',
					'win win win',
				],
				'wind'=>[
					'wind wind',
					'wind wind wind',
				],
				'wind-based'=>[
					'wind based',
					'windbased',
				],
				'windfall'=>[
					'windfal',
				],
				'windjammer'=>[
					'windjamner',
				],
				'windmill'=>[
					'windmil',
				],
				'window'=>[
					'window window',
					'window window window',
				],
				'windowsill'=>[
					'window-sill',
					'windowsil',
				],
				'windscreen'=>[
					'windcreen',
					'windcsreen',
					'windsreen',
				],
				'windshield'=>[
					'windsheild',
					'windshild',
				],
				'wined'=>[
					'winid',
				],
				'winegrower'=>[
					'winigrower',
				],
				'winery'=>[
					'winiry',
				],
				'wines'=>[
					'winis',
				],
				'winey'=>[
					'winiy',
				],
				'wing'=>[
					'wing wing',
					'wing wing wing',
				],
				'winier'=>[
					'winaer',
				],
				'winiest'=>[
					'winaest',
				],
				'wining'=>[
					'winang',
				],
				'winish'=>[
					'winash',
				],
				'winnable'=>[
					'winable',
					'winnible',
				],
				'winner'=>[
					'winer',
				],
				'winning'=>[
					'wining',
				],
				'winnow'=>[
					'winow',
				],
				'winsomely'=>[
					'winsomly',
				],
				'winter'=>[
					'winter winter',
					'winter winter winter',
				],
				'winterberry'=>[
					'winterbery',
				],
				'wintery'=>[
					'wintary',
				],
				'wirable'=>[
					'wirible',
				],
				'wire'=>[
					'wire wire',
					'wire wire wire',
				],
				'wireless'=>[
					'wireles',
				],
				'wirra'=>[
					'wira',
				],
				'wisconsin'=>[
					'wisconin',
					'wisconson',
				],
				'wisdom'=>[
					'wisom',
				],
				'wisely'=>[
					'wisly',
				],
				'wisenheimer'=>[
					'wisenhiemer',
				],
				'wisenheimers'=>[
					'wisenhiemers',
				],
				'wisent'=>[
					'wisant',
				],
				'wish'=>[
					'wish wish',
					'wish wish wish',
				],
				'wishes'=>[
					'wisghes',
				],
				'wiss'=>[
					'wis',
				],
				'witch'=>[
					'whitch',
				],
				'witches'=>[
					'witchs',
				],
				'with'=>[
					'iwth',
					'uith',
					'whith',
					'wiht',
					'with with',
					'with with with',
					'witht',
					'wth',
					'wtih',
				],
				'with its'=>[
					'with it\'s',
					'with its\'',
				],
				'with the'=>[
					'witht he',
					'withthe',
				],
				'withal'=>[
					'wital',
				],
				'withdrawal'=>[
					'withdrawl',
				],
				'withdrawals'=>[
					'withdrawls',
				],
				'withdrawnness'=>[
					'withdrawness',
				],
				'withdrawnnesses'=>[
					'withdrawnesses',
				],
				'withhold'=>[
					'withold',
				],
				'withholding'=>[
					'witholding',
				],
				'within'=>[
					'wihtin',
					'withing',
				],
				'without'=>[
					'wihtout',
					'withotu',
					'withought',
					'witout',
				],
				'without its'=>[
					'without it\'s',
				],
				'witless'=>[
					'witles',
				],
				'witness'=>[
					'witnes',
					'wittness',
				],
				'wizardly'=>[
					'wizardally',
					'wizardaly',
					'wizardely',
					'wizardlly',
				],
				'wizened'=>[
					'wizend',
				],
				'wobble'=>[
					'woble',
				],
				'wobbliness'=>[
					'wobliness',
				],
				'wobblinesses'=>[
					'woblinesses',
				],
				'wobbly'=>[
					'wobbally',
					'wobbaly',
					'wobbely',
					'wobblly',
					'wobly',
				],
				'woeful'=>[
					'woful',
				],
				'woggish'=>[
					'wogish',
				],
				'woke'=>[
					'wok',
				],
				'wolfberry'=>[
					'wolfbery',
				],
				'wollastonite'=>[
					'wolastonite',
				],
				'wolverine'=>[
					'wolverini',
				],
				'woman'=>[
					'vvoman',
					'woman woman',
					'woman woman woman',
				],
				'womanly'=>[
					'womanally',
					'womanaly',
					'womanely',
					'womanlly',
				],
				'women'=>[
					'women women',
					'women women women',
					'womens',
				],
				'women\'s'=>[
					'womens\'',
				],
				'won'=>[
					'won won',
					'won won won',
				],
				'wonder'=>[
					'wonder wonder',
					'wonder wonder wonder',
				],
				'wondrous'=>[
					'wonderous',
				],
				'wood'=>[
					'wood wood',
					'wood wood wood',
					'woood',
				],
				'woodbine'=>[
					'woodbini',
				],
				'woodchopper'=>[
					'woodchoper',
				],
				'woodie'=>[
					'woodei',
					'woodi',
				],
				'woodsy'=>[
					'woodcy',
				],
				'woollen'=>[
					'woolen',
				],
				'woolly'=>[
					'woolally',
					'woolaly',
					'woolely',
					'woollly',
					'wooly',
				],
				'wooly'=>[
					'wooally',
					'wooaly',
					'woolly',
				],
				'word'=>[
					'word word',
					'word word word',
				],
				'wordless'=>[
					'wordles',
				],
				'wore'=>[
					'weared',
				],
				'work'=>[
					'owrk',
					'wokr',
					'work work',
					'work work work',
					'wrk',
					'wrok',
				],
				'work-people'=>[
					'workpeople',
				],
				'workable'=>[
					'workible',
				],
				'workaholic'=>[
					'workaolic',
				],
				'workaholics'=>[
					'workaolics',
				],
				'workaholism'=>[
					'workaolism',
				],
				'workaholisms'=>[
					'workaolisms',
				],
				'worked'=>[
					'workred',
				],
				'worker'=>[
					'worer',
					'worlier',
				],
				'workers'=>[
					'worers',
					'worhers',
					'worliers',
				],
				'working'=>[
					'wokring',
					'wroking',
				],
				'working classes'=>[
					'workingclasses',
				],
				'workmanly'=>[
					'workmanally',
					'workmanaly',
					'workmanely',
					'workmanlly',
				],
				'workpiece'=>[
					'workpeice',
					'workpice',
				],
				'works'=>[
					'woks',
				],
				'worktable'=>[
					'worktible',
				],
				'world'=>[
					'world world',
					'world world world',
				],
				'worldly'=>[
					'wordly',
					'worldally',
					'worldaly',
					'worldely',
					'worldlly',
				],
				'worldview'=>[
					'worldveiw',
					'worldviw',
				],
				'worldwide'=>[
					'worlwide',
				],
				'worm-eaten'=>[
					'wormeaten',
				],
				'worn'=>[
					'weared',
				],
				'worrisome'=>[
					'worisome',
				],
				'worrisomely'=>[
					'worrisomly',
				],
				'worrisomenesses'=>[
					'worisomenesses',
				],
				'worrit'=>[
					'worit',
				],
				'worry'=>[
					'wory',
				],
				'worrywart'=>[
					'worywart',
				],
				'worse than'=>[
					'worse then',
				],
				'worsen'=>[
					'worsten',
				],
				'worsened'=>[
					'worsend',
					'worstened',
				],
				'worsening'=>[
					'worstening',
				],
				'worship'=>[
					'worsbip',
				],
				'worshiper'=>[
					'worshipper',
				],
				'worthless'=>[
					'a-orthless',
					'worthles',
				],
				'worthlessly'=>[
					'worthlessally',
					'worthlessaly',
					'worthlessely',
					'worthlesslly',
				],
				'worthwhile'=>[
					'worth while',
				],
				'worthy of exploiting'=>[
					'worthily of exploding',
				],
				'would'=>[
					'owudl',
					'owuld',
					'whould',
					'wonld',
					'woudl',
					'wouid',
					'would would',
					'would would would',
				],
				'would have'=>[
					'would of',
				],
				'wouldn\'t'=>[
					'would\'nt',
					'wouldnt',
				],
				'wraparound'=>[
					'wraperound',
				],
				'wrapper'=>[
					'wraper',
				],
				'wrapping'=>[
					'wraping',
				],
				'wrasse'=>[
					'wrase',
				],
				'wreak'=>[
					'reak',
					'wrek',
				],
				'wreath'=>[
					'wreth',
				],
				'wrecked'=>[
					'wecked',
				],
				'wrestling'=>[
					'wresling',
				],
				'wretchedly'=>[
					'wretchedally',
					'wretchedaly',
					'wretchedely',
					'wretchedlly',
				],
				'wrier'=>[
					'wreir',
					'wrir',
				],
				'wriggle'=>[
					'wrigle',
				],
				'wriggler'=>[
					'wrigler',
				],
				'wriggliest'=>[
					'wrigliest',
				],
				'wriggly'=>[
					'wrigly',
				],
				'writable'=>[
					'writible',
				],
				'write'=>[
					'wriet',
					'write write',
					'write write write',
				],
				'writer'=>[
					'writter',
				],
				'writer\'s block'=>[
					'writers block',
					'writers\' block',
				],
				'writerly'=>[
					'writerally',
					'writeraly',
					'writerely',
					'writerlly',
				],
				'writhed'=>[
					'writed',
				],
				'writing'=>[
					'wirting',
					'writting',
				],
				'written'=>[
					'writen',
					'written written',
					'written written written',
					'writtin',
					'writtten',
					'wroten',
				],
				'wrong'=>[
					'wrong wrong',
					'wrong wrong wrong',
				],
				'wrote'=>[
					'wroet',
					'wrote wrote',
					'wrote wrote wrote',
				],
				'wryly'=>[
					'wryally',
					'wryaly',
					'wrylly',
				],
				'wuss'=>[
					'wus',
				],
				'wussy'=>[
					'wuscy',
					'wusy',
				],
				'www'=>[
					'www.www',
				],
				'wynn'=>[
					'wyn',
				],
				'wynns'=>[
					'wyns',
				],
				'wyoming'=>[
					'wyomng',
				],
			];
		}
	}

?>