<?php
		
		/* UTF-8 TEST
		
			中文汉字漢字
		
		*/
				
				/* EnglishMisspellingsWords_N
					
					Class for English-Misspellings for all words beginning with : N.
					
				*/

	class EnglishMisspellingsWords_N {
			/* __construct($args)
			
				Constructor.
				
				Nothing to do here.
			
			*/
			
		public function __construct($args) {
			return TRUE;
		}
		
			/* EnglishMisspellingsWords()
			
				List of English misspellings for words starting with : N.
			
			*/

		public function EnglishMisspellingsWords() {
			return [
				'nagged'=>[
					'naged',
				],
				'nagger'=>[
					'nager',
				],
				'naggers'=>[
					'nagers',
				],
				'naggier'=>[
					'nagier',
				],
				'nagging'=>[
					'naging',
				],
				'naggy'=>[
					'nagy',
				],
				'naissance'=>[
					'naissence',
				],
				'naively'=>[
					'naivly',
				],
				'naivety'=>[
					'naivity',
				],
				'namable'=>[
					'namible',
				],
				'name'=>[
					'name name',
					'name name name',
				],
				'nameless'=>[
					'nameles',
				],
				'namely'=>[
					'nameally',
					'namealy',
					'nameely',
					'namelly',
					'namly',
				],
				'namibia'=>[
					'nambia',
				],
				'namibian-occupied'=>[
					'namibian occupied',
				],
				'nance'=>[
					'nence',
				],
				'nancy'=>[
					'nansy',
				],
				'nandina'=>[
					'nandini',
				],
				'nannoplankton'=>[
					'nanoplankton',
				],
				'nannoplanktons'=>[
					'nanoplanktons',
				],
				'nanny'=>[
					'nany',
				],
				'nanoscale'=>[
					'nanocale',
					'nanocsale',
					'nanosale',
				],
				'naphthylamines'=>[
					'naphthylaminis',
				],
				'napoleonic'=>[
					'napoleonian',
				],
				'nappa'=>[
					'napa',
				],
				'nappe'=>[
					'nape',
				],
				'nappy'=>[
					'napy',
				],
				'narceine'=>[
					'narciene',
				],
				'narcissism'=>[
					'narcisism',
				],
				'narcolepsy'=>[
					'narcolepcy',
				],
				'narrate'=>[
					'narate',
				],
				'narration'=>[
					'naration',
				],
				'narrative'=>[
					'narative',
				],
				'narratological'=>[
					'naratological',
				],
				'narratologists'=>[
					'naratologists',
				],
				'narratology'=>[
					'naratology',
				],
				'narrow'=>[
					'narow',
				],
				'narrow-minded'=>[
					'narrowminded',
				],
				'narrowband'=>[
					'narowband',
				],
				'narrowcastings'=>[
					'narowcastings',
				],
				'narrowly'=>[
					'narrowally',
					'narrowaly',
					'narrowely',
					'narrowlly',
				],
				'narrownesses'=>[
					'narownesses',
				],
				'nary'=>[
					'nery',
				],
				'nasalization'=>[
					'ansalization',
				],
				'nascence'=>[
					'nacence',
					'nacsence',
					'nascance',
					'nasence',
				],
				'nascency'=>[
					'nascensy',
				],
				'nascent'=>[
					'nacent',
					'nacsent',
					'nascant',
					'nascient',
					'nasent',
				],
				'natant'=>[
					'natent',
				],
				'nation'=>[
					'nation nation',
					'nation nation nation',
				],
				'nation\'s'=>[
					'nation\'',
				],
				'national'=>[
					'naitonal',
					'nalional',
					'nationa',
					'nationl',
					'nationnal',
					'natioual',
				],
				'nationalities'=>[
					'nationalites',
				],
				'nationality'=>[
					'nationalty',
				],
				'nationalizatino'=>[
					'na- tionalization',
					'na-tionalization',
				],
				'nationalization'=>[
					'nationlization',
				],
				'nationally'=>[
					'nationaly',
				],
				'nationwide'=>[
					'naitonwide',
					'nationnwide',
				],
				'natively'=>[
					'nativly',
				],
				'natural'=>[
					'natrual',
					'natual',
					'natural natural',
					'natural natural natural',
					'naturual',
				],
				'naturally'=>[
					'natuarlly',
					'naturalally',
					'naturalaly',
					'naturalely',
					'naturallly',
					'naturaly',
					'naturely',
					'naturually',
				],
				'nature'=>[
					'nature nature',
					'nature nature nature',
				],
				'naugahyde'=>[
					'naugayde',
				],
				'naugahydes'=>[
					'naugaydes',
				],
				'nauruan-occupied'=>[
					'nauruan occupied',
				],
				'nausea'=>[
					'nause',
				],
				'nauseating'=>[
					'nauseting',
				],
				'navar'=>[
					'naver',
				],
				'navicular'=>[
					'naviculer',
				],
				'navigable'=>[
					'navigible',
				],
				'navigation'=>[
					'navagation',
					'naviagation',
				],
				'navigationally'=>[
					'navigationalally',
					'navigationalaly',
					'navigationalely',
					'navigationallly',
				],
				'nazareth'=>[
					'nazereth',
				],
				'neap'=>[
					'nep',
				],
				'near'=>[
					'near near',
					'near near near',
					'neer',
					'ner',
				],
				'nearby'=>[
					'near by',
					'nearbye',
					'nerby',
				],
				'nearly'=>[
					'mearly',
					'nealry',
					'nearally',
					'nearaly',
					'nearely',
					'nearlly',
					'nenrly',
					'nerly',
				],
				'nearsighted'=>[
					'nersighted',
				],
				'nearsightedness'=>[
					'nersightedness',
				],
				'neat'=>[
					'net',
				],
				'neatened'=>[
					'neatend',
				],
				'neath'=>[
					'neth',
				],
				'nebbish'=>[
					'nebish',
				],
				'nebraska'=>[
					'nebaska',
				],
				'nebuly'=>[
					'nebually',
					'nebualy',
					'nebuely',
					'nebully',
				],
				'necessarily'=>[
					'neccesarily',
					'neccessarily',
					'necesarily',
					'necessarially',
					'necessarialy',
					'necessariely',
					'necessarilly',
					'nessasarily',
				],
				'necessary'=>[
					'neccesary',
					'neccessary',
					'necesary',
					'necessary necessary',
					'necessary necessary necessary',
					'necessery',
					'necesssary',
					'nesessary',
					'nesessary', 'nessecary',
					'nessacary',
					'nessecary',
				],
				'necessitarian'=>[
					'necessitaran',
				],
				'necessitate'=>[
					'necesitate',
				],
				'necessities'=>[
					'neccesities',
					'necessaties',
				],
				'necessitously'=>[
					'necessitousally',
					'necessitousaly',
					'necessitousely',
					'necessitouslly',
				],
				'necessity'=>[
					'neccesity',
					'necesity',
					'necessaty',
					'nesessity',
				],
				'neck'=>[
					'neck neck',
					'neck neck neck',
				],
				'neckerchief'=>[
					'neckercheif',
					'neckerchif',
				],
				'neckline'=>[
					'necklini',
				],
				'necktie'=>[
					'necktei',
					'neckti',
				],
				'neckwear'=>[
					'neckweer',
				],
				'necromancy'=>[
					'necromansy',
				],
				'necropsy'=>[
					'necropcy',
				],
				'nectar'=>[
					'necter',
				],
				'nectarine'=>[
					'nectarini',
				],
				'nectary'=>[
					'nectery',
				],
				'need'=>[
					'ened',
					'need need',
					'need need need',
					'neeed',
				],
				'need friends'=>[
					'kneed friends',
				],
				'needless'=>[
					'needles',
				],
				'needs'=>[
					'need\'s',
				],
				'nefarious'=>[
					'nefarous',
				],
				'nefariously'=>[
					'nefariousally',
					'nefariousaly',
					'nefariousely',
					'nefariouslly',
					'nefarously',
				],
				'negative'=>[
					'negitive',
				],
				'negatively'=>[
					'negativley',
					'negativly',
				],
				'negativity'=>[
					'negitivity',
				],
				'negligence'=>[
					'negligance',
				],
				'negligent'=>[
					'negligant',
				],
				'negligible'=>[
					'neglible',
					'negligable',
				],
				'negotiable'=>[
					'negotiible',
				],
				'negotiate'=>[
					'negociate',
				],
				'negotiation'=>[
					'negotation',
				],
				'negotiations'=>[
					'negociations',
				],
				'negotiator'=>[
					'negotiater',
				],
				'neif'=>[
					'nief',
				],
				'neifs'=>[
					'niefs',
				],
				'neigh'=>[
					'niegh',
				],
				'neighbor'=>[
					'neigbor',
					'neigbour',
					'neighboor',
					'neighbor neighbor',
					'neighbor neighbor neighbor',
					'nieghbor',
				],
				'neighborhood'=>[
					'neighbohood',
					'neighbourbood',
					'neightbourhood',
					'nieghborhood',
				],
				'neighborhoods'=>[
					'nieghborhoods',
				],
				'neighboring'=>[
					'neigbouring',
				],
				'neighborliness'=>[
					'neighborliniss',
					'nieghborliness',
				],
				'neighborly'=>[
					'neighborally',
					'neighboraly',
					'neighborely',
					'neighborlly',
					'nieghborly',
				],
				'neighbors'=>[
					'neigbors',
					'neigbours',
				],
				'neighbour'=>[
					'nieghbour',
				],
				'neist'=>[
					'niest',
				],
				'neither'=>[
					'niether',
				],
				'nelly'=>[
					'nelally',
					'nelaly',
					'nellly',
					'nely',
				],
				'neoclassicism'=>[
					'neoclasicism',
				],
				'neomorph'=>[
					'neomourph',
				],
				'neostigmine'=>[
					'neostigmini',
				],
				'nepalese-occupied'=>[
					'nepalese occupied',
				],
				'nephelinic'=>[
					'nephelinac',
				],
				'nephelinite'=>[
					'nephelinate',
				],
				'nephelinites'=>[
					'nephelinates',
				],
				'nephelinitic'=>[
					'nephelinatic',
				],
				'nephew'=>[
					'newphew',
				],
				'nereis'=>[
					'neries',
				],
				'nervelessly'=>[
					'nervelessally',
					'nervelessaly',
					'nervelessely',
					'nervelesslly',
				],
				'nescience'=>[
					'nesciance',
				],
				'ness'=>[
					'nes',
				],
				'netherlands'=>[
					'netherland\'s',
				],
				'nettly'=>[
					'nettally',
					'nettaly',
					'nettely',
					'nettlly',
				],
				'network'=>[
					'newtork',
				],
				'neuraminidase'=>[
					'neuraminadase',
				],
				'neuraminidases'=>[
					'neuraminadases',
				],
				'neurilemma'=>[
					'neurilemna',
				],
				'neuroendocrine'=>[
					'neuroendocrini',
				],
				'neurofibrillary'=>[
					'neurofibrillery',
				],
				'neurohumor'=>[
					'neurohumour',
				],
				'neurohumoral'=>[
					'neurohumoural',
				],
				'neurohumors'=>[
					'neurohumours',
				],
				'neurological'=>[
					'nuerological',
				],
				'neuromuscular'=>[
					'neuromucsular',
					'neuromucular',
					'neuromusculer',
					'neuromusular',
				],
				'neuroscience'=>[
					'neurocience',
					'neurocsience',
					'neurosceince',
					'neurosciance',
					'neuroscince',
					'neurosience',
				],
				'neuroscientific'=>[
					'neurocientific',
					'neurocsientific',
					'neurosientific',
				],
				'neuroscientists'=>[
					'neurocientists',
					'neurocsientists',
					'neurosientists',
				],
				'neurotic'=>[
					'nuerotic',
				],
				'neurotransmitter'=>[
					'nuerotransmitter',
				],
				'neutral'=>[
					'nuetral',
				],
				'neutrality'=>[
					'nuetrality',
				],
				'neutralize'=>[
					'nuetralize',
				],
				'never'=>[
					'never never',
					'never never never',
				],
				'nevermore'=>[
					'nevermoure',
				],
				'nevertheless'=>[
					'nethertheless',
					'neveretheless',
					'nevertheles',
				],
				'new'=>[
					'new new',
					'new new new',
					'neww',
					'nwe',
				],
				'new york'=>[
					'new yrok',
				],
				'new yorker'=>[
					'newyorker',
				],
				'new zealander-occupied'=>[
					'new zealander occupied',
				],
				'newbie'=>[
					'newbei',
					'newbi',
				],
				'newfoundland'=>[
					'foundland',
				],
				'newie'=>[
					'newei',
					'newi',
				],
				'newly'=>[
					'newally',
					'newaly',
					'newely',
					'newlly',
				],
				'newly-elected'=>[
					'newly elected',
					'newlyelected',
				],
				'newly-established'=>[
					'newly established',
				],
				'news'=>[
					'newws',
				],
				'newscast'=>[
					'newcast',
					'newcsast',
					'newsast',
				],
				'newsletter'=>[
					'newletter',
				],
				'newsmagazine'=>[
					'newsmagazini',
				],
				'newspaper'=>[
					'nejvspaper',
				],
				'newspapers'=>[
					'newspaners',
				],
				'newsreader'=>[
					'newsreder',
				],
				'newsstand'=>[
					'newstand',
				],
				'newsweekly'=>[
					'newsweekally',
					'newsweekaly',
					'newsweekely',
					'newsweeklly',
				],
				'newsworthiness'=>[
					'newsworthiniss',
				],
				'newsy'=>[
					'newcy',
				],
				'next'=>[
					'enxt',
					'next next',
					'next next next',
				],
				'niagara'=>[
					'niagra',
				],
				'niagara falls'=>[
					'niagra falls',
				],
				'nibble'=>[
					'nible',
				],
				'nicaraguan-occupied'=>[
					'nicaraguan occupied',
				],
				'niccolite'=>[
					'nicolite',
				],
				'nicely'=>[
					'nicly',
				],
				'niche'=>[
					'nitch',
				],
				'nickelodeon'=>[
					'nikelodeon',
				],
				'nickname'=>[
					'nick name',
					'nicname',
				],
				'nicknamed'=>[
					'nick named',
				],
				'nicotinamide'=>[
					'nicotinimide',
				],
				'nicotinamides'=>[
					'nicotinimides',
				],
				'nicotine'=>[
					'nicotini',
				],
				'nicotinic'=>[
					'nicotinac',
				],
				'niece'=>[
					'neice',
					'nice',
				],
				'nieces'=>[
					'neices',
				],
				'niello'=>[
					'neillo',
					'nillo',
				],
				'nietzsche'=>[
					'nietzche',
					'nietzche', 'nietzshe',
				],
				'nifedipine'=>[
					'nifedipini',
				],
				'nigerian-occupied'=>[
					'nigerian occupied',
				],
				'nigerien-occupied'=>[
					'nigerien occupied',
				],
				'niggard'=>[
					'nigard',
				],
				'niggarding'=>[
					'nigarding',
				],
				'niggardliness'=>[
					'nigardliness',
				],
				'niggardlinesses'=>[
					'nigardlinesses',
					'niggardlinisses',
				],
				'niggardly'=>[
					'nigardly',
					'niggardally',
					'niggardaly',
					'niggardely',
					'niggardlly',
				],
				'niggle'=>[
					'nigle',
				],
				'niggled'=>[
					'nigled',
				],
				'niggler'=>[
					'nigler',
				],
				'niggles'=>[
					'nigles',
				],
				'niggling'=>[
					'nigling',
				],
				'nigglingly'=>[
					'niglingly',
				],
				'niggly'=>[
					'nigly',
				],
				'night'=>[
					'mght',
					'night night',
					'night night night',
					'nigth',
				],
				'nightclubbed'=>[
					'nightclubed',
				],
				'nightclubber'=>[
					'nightcluber',
				],
				'nightclubbers'=>[
					'nightclubers',
				],
				'nightclubbing'=>[
					'nightclubing',
				],
				'nightfall'=>[
					'nightfal',
				],
				'nightie'=>[
					'nightei',
					'nighti',
				],
				'nightjar'=>[
					'nightjer',
				],
				'nightly'=>[
					'nightally',
					'nightaly',
					'nightely',
					'nightlly',
				],
				'nightwear'=>[
					'nightweer',
				],
				'nill'=>[
					'nil',
				],
				'nimious'=>[
					'nimous',
				],
				'nine'=>[
					'nine nine',
					'nine nine nine',
				],
				'ninefold'=>[
					'ninifold',
				],
				'nines'=>[
					'ninis',
				],
				'nineteen'=>[
					'niniteen',
					'ninteen',
				],
				'nineteenth'=>[
					'nineteanth',
					'niniteenth',
					'ninteenth',
				],
				'nineties'=>[
					'ninetys',
					'ninties',
				],
				'ninetieth'=>[
					'nineteith',
					'ninetith',
					'ninitieth',
				],
				'ninety'=>[
					'ninity',
					'nintey',
					'ninty',
				],
				'ninny'=>[
					'niny',
				],
				'ninnyhammer'=>[
					'ninyhammer',
				],
				'ninnyhammers'=>[
					'ninyhammers',
				],
				'ninth'=>[
					'nineth',
				],
				'ninthly'=>[
					'ninethly',
				],
				'nipper'=>[
					'niper',
				],
				'nipping'=>[
					'niping',
				],
				'nipple'=>[
					'niple',
				],
				'nippy'=>[
					'nipy',
				],
				'nisei'=>[
					'nisie',
				],
				'nitery'=>[
					'nitary',
				],
				'nitpick'=>[
					'knit-pick',
					'knitpick',
				],
				'nitrocellulose'=>[
					'nitrocelulose',
				],
				'nitroglycerines'=>[
					'nitroglycerinis',
				],
				'nitroparaffin'=>[
					'nitroperaffin',
				],
				'nitroparaffins'=>[
					'nitroperaffins',
				],
				'nitrosamine'=>[
					'nitrosamini',
				],
				'nixie'=>[
					'nixei',
					'nixi',
				],
				'no'=>[
					'no no',
					'no no no',
				],
				'no one'=>[
					'noone',
				],
				'no running water'=>[
					'no running wood',
				],
				'nobble'=>[
					'noble',
				],
				'nobby'=>[
					'noby',
				],
				'nobiliary'=>[
					'nobiliery',
				],
				'nobly'=>[
					'nobally',
					'nobaly',
					'noblly',
				],
				'nobody'=>[
					'no body',
					'no-body',
				],
				'nocent'=>[
					'nocant',
				],
				'noctuoid'=>[
					'noctoid',
				],
				'nocuous'=>[
					'nocous',
				],
				'nocuously'=>[
					'nocously',
				],
				'nodular'=>[
					'noduler',
				],
				'nogg'=>[
					'nog',
				],
				'nogged'=>[
					'noged',
				],
				'noggin'=>[
					'nogin',
				],
				'nogging'=>[
					'noging',
				],
				'noggins'=>[
					'nogins',
				],
				'noggs'=>[
					'nogs',
				],
				'noily'=>[
					'noially',
					'noialy',
					'noilly',
				],
				'noise'=>[
					'noise noise',
					'noise noise noise',
				],
				'noiselessly'=>[
					'noiselessally',
					'noiselessaly',
					'noiselessely',
					'noiselesslly',
				],
				'noisomely'=>[
					'noisomly',
				],
				'noisy'=>[
					'noicy',
				],
				'nomenclature'=>[
					'nomencalture',
				],
				'nomina'=>[
					'nomini',
				],
				'nominal'=>[
					'nominil',
				],
				'nominalism'=>[
					'nominilism',
				],
				'nominate'=>[
					'nominite',
				],
				'nomination'=>[
					'nominition',
				],
				'nominative'=>[
					'nominitive',
				],
				'nominee'=>[
					'nominie',
				],
				'non-capitalist'=>[
					'noncapitalist',
				],
				'non-commissioned'=>[
					'noncommissioned',
				],
				'non-communist'=>[
					'noncommunist',
				],
				'non-hierarchical'=>[
					'nonheirarchical',
					'nonhierarchical',
				],
				'non-participation'=>[
					'nonparticipation',
				],
				'non-political'=>[
					'nonpolitical',
				],
				'non-western'=>[
					'nonwestern',
				],
				'non-worker'=>[
					'nonworker',
				],
				'non-workers'=>[
					'nonworkers',
				],
				'nonabsorbable'=>[
					'nonabsorbible',
				],
				'nonacceptance'=>[
					'nonacceptence',
					'nonaceptance',
				],
				'nonacceptances'=>[
					'nonaceptances',
				],
				'nonaccountable'=>[
					'nonaccountible',
					'nonacountable',
				],
				'nonaccredited'=>[
					'nonacredited',
				],
				'nonagenarian'=>[
					'nonagenaran',
				],
				'nonaggression'=>[
					'nonaggresion',
					'nonagression',
				],
				'nonaggressions'=>[
					'nonagressions',
				],
				'nonaggressive'=>[
					'nonagressive',
				],
				'nonalignment'=>[
					'nonaligment',
					'nonalignent',
				],
				'nonalignments'=>[
					'nonaligments',
					'nonalignents',
				],
				'nonambiguous'=>[
					'nonambigous',
				],
				'nonappearance'=>[
					'nonapearance',
					'nonappearence',
					'nonapperance',
				],
				'nonappearances'=>[
					'nonapearances',
				],
				'nonarbitrary'=>[
					'nonarbitrery',
				],
				'nonattendance'=>[
					'nonattendence',
				],
				'nonbeliever'=>[
					'nonbeleiver',
					'nonbeliver',
				],
				'nonbelligerency'=>[
					'nonbelligerensy',
				],
				'nonbinary'=>[
					'nonbinery',
				],
				'nonbiologically'=>[
					'nonbiologicalally',
					'nonbiologicalaly',
					'nonbiologicalely',
					'nonbiologicallly',
				],
				'nonbusiness'=>[
					'nonbuisness',
					'nonbusines',
					'nonbusiniss',
				],
				'noncallable'=>[
					'noncalable',
					'noncallible',
				],
				'noncancelable'=>[
					'noncancelible',
				],
				'noncandidacy'=>[
					'noncandidasy',
				],
				'noncellular'=>[
					'noncelluler',
				],
				'nonchalance'=>[
					'nonchalence',
				],
				'nonchalant'=>[
					'nonchalent',
				],
				'nonchauvinist'=>[
					'nonchauvinast',
				],
				'noncircular'=>[
					'noncirculer',
				],
				'nonclogging'=>[
					'noncloging',
				],
				'noncoincidence'=>[
					'noncoincidance',
				],
				'noncollinear'=>[
					'noncollineer',
				],
				'noncombatant'=>[
					'noncombatent',
				],
				'noncombustible'=>[
					'noncombustable',
				],
				'noncommitments'=>[
					'noncomnitments',
				],
				'noncommittal'=>[
					'noncomnittal',
				],
				'noncommittally'=>[
					'noncommittalally',
					'noncommittalaly',
					'noncommittalely',
					'noncommittallly',
					'noncomnittally',
				],
				'noncommutative'=>[
					'noncomnutative',
				],
				'noncomparable'=>[
					'noncomparible',
					'noncomperable',
				],
				'noncompatible'=>[
					'noncompatable',
				],
				'noncompliance'=>[
					'noncomplience',
				],
				'noncompressible'=>[
					'noncompressable',
				],
				'nonconceptual'=>[
					'nonconceptaul',
				],
				'nonconclusion'=>[
					'nonconcluison',
				],
				'nonconclusions'=>[
					'nonconcluisons',
				],
				'nonconcurred'=>[
					'nonconcured',
				],
				'nonconcurrence'=>[
					'nonconcurence',
					'nonconcurrance',
				],
				'nonconcurrences'=>[
					'nonconcurences',
				],
				'noncondensable'=>[
					'noncondensible',
				],
				'nonconference'=>[
					'nonconferance',
				],
				'nonconfidence'=>[
					'nonconfidance',
				],
				'nonconfidential'=>[
					'nonconfidantial',
				],
				'nonconformance'=>[
					'nonconformence',
				],
				'nonconnection'=>[
					'nonconection',
				],
				'nonconnections'=>[
					'nonconections',
				],
				'nonconscious'=>[
					'nonconscous',
				],
				'nonconsensual'=>[
					'nonconsensaul',
				],
				'noncontagious'=>[
					'noncontagous',
				],
				'noncontemporary'=>[
					'noncontemporery',
				],
				'noncontiguous'=>[
					'noncontigous',
				],
				'noncontinuous'=>[
					'noncontinous',
				],
				'noncontractual'=>[
					'noncontractaul',
				],
				'noncontrollable'=>[
					'noncontrollible',
				],
				'nonconvertible'=>[
					'nonconvertable',
				],
				'noncoplanar'=>[
					'noncoplaner',
				],
				'noncorrelation'=>[
					'noncorelation',
				],
				'noncorrelations'=>[
					'noncorelations',
				],
				'noncorrodible'=>[
					'noncorrodable',
				],
				'noncorroding'=>[
					'noncoroding',
				],
				'noncorrosive'=>[
					'noncorosive',
				],
				'noncreativities'=>[
					'noncretivities',
				],
				'noncredentialed'=>[
					'noncredantialed',
				],
				'nonculinary'=>[
					'nonculinery',
				],
				'nondance'=>[
					'nondence',
				],
				'nondeductible'=>[
					'nondeductable',
				],
				'nondefense'=>[
					'nondefence',
				],
				'nondeferrable'=>[
					'nondeferrible',
				],
				'nondegradable'=>[
					'nondegradible',
				],
				'nondepartmental'=>[
					'nondepertmental',
				],
				'nondependent'=>[
					'nondependant',
				],
				'nondependents'=>[
					'nondependants',
				],
				'nondepletable'=>[
					'nondepletible',
				],
				'nondescript'=>[
					'nondecript',
					'nondecsript',
					'nondesript',
				],
				'nondetachable'=>[
					'nondetachible',
				],
				'nondiapausing'=>[
					'nondiapauisng',
				],
				'nondiffusible'=>[
					'nondiffuisble',
					'nondiffusable',
				],
				'nondoctrinaire'=>[
					'nondoctriniire',
				],
				'nondocumentary'=>[
					'nondocumentery',
				],
				'nondollar'=>[
					'nondoller',
				],
				'nondurable'=>[
					'nondurible',
				],
				'none'=>[
					'noen',
				],
				'nonedible'=>[
					'nonedable',
				],
				'nonelementary'=>[
					'nonelementery',
				],
				'nonemergency'=>[
					'nonemergensy',
				],
				'nonequivalence'=>[
					'nonequivalance',
				],
				'nonessential'=>[
					'nonesential',
					'nonessantial',
				],
				'nonetheless'=>[
					'nonetheles',
				],
				'nonevaluative'=>[
					'nonevalautive',
				],
				'nonevidence'=>[
					'nonevidance',
				],
				'nonexclusive'=>[
					'nonexcluisve',
				],
				'nonexistence'=>[
					'nonexistance',
				],
				'nonexistent'=>[
					'non-existant',
				],
				'nonfeasance'=>[
					'nonfeasence',
				],
				'nonfeminists'=>[
					'nonfeminasts',
				],
				'nonferrous'=>[
					'nonferous',
				],
				'nonfilterable'=>[
					'nonfilterible',
				],
				'nonfissionable'=>[
					'nonfissionible',
				],
				'nonflammability'=>[
					'nonflamnability',
				],
				'nonflammable'=>[
					'nonflammible',
					'nonflamnable',
				],
				'nonfluency'=>[
					'nonfluensy',
				],
				'nonfluorescent'=>[
					'nonflorescent',
				],
				'nonforfeitable'=>[
					'nonforfeitible',
					'nonforfietable',
				],
				'nonforfeiture'=>[
					'nonforfieture',
				],
				'nonforfeitures'=>[
					'nonforfietures',
				],
				'nonglamorous'=>[
					'nonglamourous',
				],
				'nonglossy'=>[
					'nongloscy',
				],
				'nongonococcal'=>[
					'nongonococal',
				],
				'nongovernment'=>[
					'nongoverment',
					'nongovernent',
				],
				'nongovernmental'=>[
					'nongovermental',
					'nongovernental',
				],
				'nongraduates'=>[
					'nongradautes',
				],
				'nongrammatical'=>[
					'nongramnatical',
				],
				'nongranular'=>[
					'nongranuler',
				],
				'nongreasy'=>[
					'nongreacy',
				],
				'nongregarious'=>[
					'nongregarous',
				],
				'nonhandicapped'=>[
					'nonhandicaped',
				],
				'nonhappening'=>[
					'nonhapening',
				],
				'nonhappenings'=>[
					'nonhapenings',
				],
				'nonhereditary'=>[
					'nonhereditery',
				],
				'nonhomosexual'=>[
					'nonhomosexaul',
				],
				'nonhomosexuals'=>[
					'nonhomosexauls',
				],
				'nonhousing'=>[
					'nonhouisng',
				],
				'nonidentical'=>[
					'nonidantical',
				],
				'nonidentities'=>[
					'nonidantities',
				],
				'nonidentity'=>[
					'nonidantity',
				],
				'nonimmigrant'=>[
					'nonimmigrent',
					'nonimnigrant',
				],
				'nonimmune'=>[
					'nonimnune',
				],
				'noninclusion'=>[
					'nonincluison',
				],
				'noninclusions'=>[
					'nonincluisons',
				],
				'nonindependence'=>[
					'nonindependance',
				],
				'nonindividual'=>[
					'nonindividaul',
				],
				'noninfectious'=>[
					'noninfectous',
				],
				'noninflammable'=>[
					'noninflammible',
					'noninflamnable',
				],
				'noninflammatory'=>[
					'noninflamnatory',
				],
				'noninflationary'=>[
					'noninflationery',
				],
				'noninfluence'=>[
					'noninfluance',
				],
				'noninitial'=>[
					'noninatial',
				],
				'noninitiates'=>[
					'noninatiates',
				],
				'noninsurance'=>[
					'noninsurence',
				],
				'nonintellectual'=>[
					'nonintellectaul',
				],
				'noninterference'=>[
					'noninterferance',
				],
				'nonintervention'=>[
					'nonintervantion',
				],
				'nonintrusive'=>[
					'nonintruisve',
				],
				'noninvolvement'=>[
					'noninvolvemant',
				],
				'nonirrigated'=>[
					'nonirigated',
				],
				'nonirritants'=>[
					'noniritants',
				],
				'nonjudgmental'=>[
					'nonjudgmantal',
				],
				'nonjusticiable'=>[
					'nonjusticiible',
				],
				'nonlanguages'=>[
					'nonlangauges',
				],
				'nonlethal'=>[
					'nonletal',
				],
				'nonlibrarian'=>[
					'nonlibraran',
				],
				'nonlibrary'=>[
					'nonlibrery',
				],
				'nonlinear'=>[
					'nonlineer',
					'nonliner',
					'nonliniar',
				],
				'nonliterary'=>[
					'nonliterery',
				],
				'nonmagnetic'=>[
					'nomagnetic',
					'nonagnetic',
				],
				'nonmainstream'=>[
					'nomainstream',
					'nonainstream',
				],
				'nonmajor'=>[
					'nomajor',
					'nonajor',
				],
				'nonmajors'=>[
					'nomajors',
					'nonajors',
				],
				'nonmalignant'=>[
					'nomalignant',
					'nonalignant',
				],
				'nonmalleable'=>[
					'nomalleable',
					'nonalleable',
				],
				'nonman'=>[
					'noman',
					'nonan',
				],
				'nonmanagement'=>[
					'nomanagement',
					'nonanagement',
				],
				'nonmanagerial'=>[
					'nomanagerial',
					'nonanagerial',
				],
				'nonmanual'=>[
					'nomanual',
					'nonanual',
				],
				'nonmarital'=>[
					'nomarital',
					'nonarital',
				],
				'nonmarket'=>[
					'nomarket',
					'nonarket',
				],
				'nonmarkets'=>[
					'nomarkets',
					'nonarkets',
				],
				'nonmaterial'=>[
					'nomaterial',
					'nonaterial',
				],
				'nonmathematical'=>[
					'nomathematical',
					'nonathematical',
				],
				'nonmatriculated'=>[
					'nomatriculated',
					'nonatriculated',
				],
				'nonmature'=>[
					'nomature',
					'nonature',
				],
				'nonmeaningful'=>[
					'nomeaningful',
					'noneaningful',
				],
				'nonmeat'=>[
					'nomeat',
					'noneat',
				],
				'nonmechanical'=>[
					'nomechanical',
					'nonechanical',
				],
				'nonmechanistic'=>[
					'nomechanistic',
					'nonechanistic',
				],
				'nonmedical'=>[
					'nomedical',
					'nonedical',
				],
				'nonmeeting'=>[
					'nomeeting',
					'noneeting',
				],
				'nonmeetings'=>[
					'nomeetings',
					'noneetings',
				],
				'nonmember'=>[
					'nomember',
					'nonember',
					'nonmber',
				],
				'nonmembers'=>[
					'nomembers',
					'nonembers',
					'nonmbers',
				],
				'nonmembership'=>[
					'nomembership',
					'nonembership',
					'nonmbership',
				],
				'nonmemberships'=>[
					'nomemberships',
					'nonemberships',
					'nonmberships',
				],
				'nonmen'=>[
					'nomen',
					'nonen',
				],
				'nonmental'=>[
					'nomental',
					'nonental',
				],
				'nonmercurial'=>[
					'nomercurial',
					'nonercurial',
				],
				'nonmetal'=>[
					'nometal',
					'nonetal',
				],
				'nonmetallic'=>[
					'nometallic',
					'nonetallic',
					'nonmetalic',
				],
				'nonmetals'=>[
					'nometals',
					'nonetals',
				],
				'nonmetameric'=>[
					'nometameric',
					'nonetameric',
				],
				'nonmetaphorical'=>[
					'nometaphorical',
					'nonetaphorical',
				],
				'nonmetric'=>[
					'nometric',
					'nonetric',
				],
				'nonmetrical'=>[
					'nometrical',
					'nonetrical',
				],
				'nonmetro'=>[
					'nometro',
					'nonetro',
				],
				'nonmetropolitan'=>[
					'nometropolitan',
					'nonetropolitan',
				],
				'nonmicrobial'=>[
					'nomicrobial',
					'nonicrobial',
				],
				'nonmigrant'=>[
					'nomigrant',
					'nonigrant',
				],
				'nonmigratory'=>[
					'nomigratory',
					'nonigratory',
				],
				'nonmilitant'=>[
					'nomilitant',
					'nonilitant',
				],
				'nonmilitants'=>[
					'nomilitants',
					'nonilitants',
				],
				'nonmilitary'=>[
					'nomilitary',
					'nonilitary',
					'nonmilitery',
				],
				'nonmimetic'=>[
					'nomimetic',
					'nonimetic',
				],
				'nonminorities'=>[
					'nominorities',
					'noninorities',
					'nonminourities',
				],
				'nonminority'=>[
					'nominority',
					'noninority',
					'nonminourity',
				],
				'nonmobile'=>[
					'nomobile',
					'nonobile',
				],
				'nonmodal'=>[
					'nomodal',
					'nonodal',
				],
				'nonmodern'=>[
					'nomodern',
					'nonodern',
				],
				'nonmoderns'=>[
					'nomoderns',
					'nonoderns',
				],
				'nonmolecular'=>[
					'nomolecular',
					'nonmoleculer',
					'nonolecular',
				],
				'nonmonetarist'=>[
					'nomonetarist',
					'nononetarist',
				],
				'nonmonetarists'=>[
					'nomonetarists',
					'nononetarists',
				],
				'nonmonetary'=>[
					'nomonetary',
					'nonmonetery',
					'nononetary',
				],
				'nonmoney'=>[
					'nomoney',
					'nononey',
				],
				'nonmonogamous'=>[
					'nomonogamous',
					'nononogamous',
				],
				'nonmoral'=>[
					'nomoral',
					'nonmoural',
					'nonoral',
				],
				'nonmortal'=>[
					'nomortal',
					'nonortal',
				],
				'nonmortals'=>[
					'nomortals',
					'nonmourtals',
					'nonortals',
				],
				'nonmotile'=>[
					'nomotile',
					'nonotile',
				],
				'nonmotilities'=>[
					'nomotilities',
					'nonotilities',
				],
				'nonmotility'=>[
					'nomotility',
					'nonotility',
				],
				'nonmotorized'=>[
					'nomotorized',
					'nonotorized',
				],
				'nonmoving'=>[
					'nomoving',
					'nonoving',
				],
				'nonmunicipal'=>[
					'nomunicipal',
					'nonunicipal',
				],
				'nonmusic'=>[
					'nomusic',
					'nonmuisc',
					'nonusic',
				],
				'nonmusical'=>[
					'nomusical',
					'nonmuiscal',
					'nonusical',
				],
				'nonmusicals'=>[
					'nomusicals',
					'nonmuiscals',
					'nonusicals',
				],
				'nonmusician'=>[
					'nomusician',
					'nonmuiscian',
					'nonmusican',
					'nonusician',
				],
				'nonmusicians'=>[
					'nomusicians',
					'nonmuiscians',
					'nonusicians',
				],
				'nonmusics'=>[
					'nomusics',
					'nonmuiscs',
					'nonusics',
				],
				'nonmutant'=>[
					'nomutant',
					'nonutant',
				],
				'nonmutants'=>[
					'nomutants',
					'nonutants',
				],
				'nonmutual'=>[
					'nomutual',
					'nonutual',
				],
				'nonmyelinated'=>[
					'nomyelinated',
					'nonmyelinited',
					'nonyelinated',
				],
				'nonmystical'=>[
					'nomystical',
					'nonystical',
				],
				'nonnarrative'=>[
					'nonnarative',
				],
				'nonnecessities'=>[
					'nonecessities',
				],
				'nonnegative'=>[
					'nonegative',
				],
				'nonnegotiable'=>[
					'nonegotiable',
					'nonnegotiible',
				],
				'nonnegotiables'=>[
					'nonegotiables',
				],
				'nonnitrogenous'=>[
					'nonitrogenous',
				],
				'nonnormal'=>[
					'nonnourmal',
				],
				'nonnormative'=>[
					'nonnourmative',
				],
				'nonnuclear'=>[
					'nonnucleer',
					'nonuclear',
				],
				'nonnutritious'=>[
					'nonnutritous',
					'nonutritious',
				],
				'nonobservance'=>[
					'nonobservence',
				],
				'nonoccupational'=>[
					'nonocupational',
				],
				'nonoccurrence'=>[
					'nonoccurrance',
					'nonocurrence',
				],
				'nonoccurrences'=>[
					'nonoccurences',
					'nonocurrences',
				],
				'nonoral'=>[
					'nonoural',
				],
				'nonorally'=>[
					'nonourally',
				],
				'nonorganic'=>[
					'nonourganic',
				],
				'nonorgasmic'=>[
					'nonourgasmic',
				],
				'nonorthodox'=>[
					'nonourthodox',
				],
				'nonoverlapping'=>[
					'nonoverlaping',
				],
				'nonpar'=>[
					'nonper',
				],
				'nonparametric'=>[
					'nonperametric',
				],
				'nonpareil'=>[
					'nonpariel',
					'nonpereil',
				],
				'nonparent'=>[
					'nonperent',
				],
				'nonparticipant'=>[
					'nonperticipant',
				],
				'nonparticipants'=>[
					'nonperticipants',
				],
				'nonpartisan'=>[
					'nonpertisan',
				],
				'nonpartisanship'=>[
					'nonpertisanship',
				],
				'nonparty'=>[
					'nonperty',
				],
				'nonperformance'=>[
					'nonperformence',
				],
				'nonperishable'=>[
					'nonperishible',
				],
				'nonpersistent'=>[
					'nonpersistant',
				],
				'nonphysician'=>[
					'nonphysican',
				],
				'nonplanar'=>[
					'nonplaner',
				],
				'nonplusing'=>[
					'nonpluisng',
				],
				'nonplussed'=>[
					'non-plussed',
				],
				'nonpolar'=>[
					'nonpoler',
				],
				'nonpolarizable'=>[
					'nonpolarizible',
				],
				'nonpolitician'=>[
					'nonpolitican',
				],
				'nonprescription'=>[
					'nonprecription',
					'nonprecsription',
					'nonpresription',
				],
				'nonprofessional'=>[
					'nonprofesional',
					'nonproressional',
				],
				'nonprogrammers'=>[
					'nonprogramners',
				],
				'nonproprietary'=>[
					'nonproprietery',
				],
				'nonquantifiable'=>[
					'nonqauntifiable',
					'nonquantifiible',
				],
				'nonquantitative'=>[
					'nonqauntitative',
				],
				'nonrecombinant'=>[
					'nonrecombinent',
					'nonrecombinint',
				],
				'nonrecombinants'=>[
					'nonrecombinints',
				],
				'nonrecurrent'=>[
					'nonrecurent',
				],
				'nonrecurring'=>[
					'nonrecuring',
				],
				'nonrecyclable'=>[
					'nonrecyclible',
				],
				'nonredundant'=>[
					'nonredundent',
				],
				'nonrefillable'=>[
					'nonrefillible',
				],
				'nonreligious'=>[
					'nonreligous',
				],
				'nonrenewable'=>[
					'nonrenewible',
				],
				'nonresidence'=>[
					'nonresidance',
				],
				'nonresidency'=>[
					'nonresidensy',
				],
				'nonresident'=>[
					'nonresidant',
				],
				'nonresidential'=>[
					'nonresidantial',
				],
				'nonresidents'=>[
					'nonresidants',
				],
				'nonresistance'=>[
					'nonresistence',
				],
				'nonresistant'=>[
					'nonresistent',
				],
				'nonrespondent'=>[
					'nonrespondant',
				],
				'nonrespondents'=>[
					'nonrespondants',
				],
				'nonresponse'=>[
					'nonresponce',
				],
				'nonreturnable'=>[
					'nonreturnible',
				],
				'nonreversible'=>[
					'nonreversable',
				],
				'nonsaponifiable'=>[
					'nonsaponifiible',
				],
				'nonscheduled'=>[
					'noncheduled',
					'noncsheduled',
					'nonsheduled',
				],
				'nonscience'=>[
					'nonsciance',
				],
				'nonsectarian'=>[
					'nonsectaran',
				],
				'nonsedimentable'=>[
					'nonsedimentible',
				],
				'nonsense'=>[
					'nonsence',
				],
				'nonsensuous'=>[
					'nonsensous',
				],
				'nonsentence'=>[
					'nonsentance',
				],
				'nonserious'=>[
					'nonserous',
				],
				'nonshrinkable'=>[
					'nonshrinkible',
				],
				'nonsignificant'=>[
					'nonsignificent',
				],
				'nonsolar'=>[
					'nonsoler',
				],
				'nonspecifically'=>[
					'nonspecificalally',
					'nonspecificalaly',
					'nonspecificalely',
					'nonspecificallly',
				],
				'nonspectacular'=>[
					'nonspectaculer',
				],
				'nonstationary'=>[
					'nonstationery',
				],
				'nonstudent'=>[
					'nonstudant',
				],
				'nonstudents'=>[
					'nonstudants',
				],
				'nonsupport'=>[
					'nonsuport',
				],
				'nonsymmetrical'=>[
					'nonsymnetrical',
				],
				'nonterminating'=>[
					'nonterminiting',
				],
				'nontotalitarian'=>[
					'nontotalitaran',
				],
				'nontransferable'=>[
					'nontransferible',
				],
				'nonusing'=>[
					'nonuisng',
				],
				'nonutilitarian'=>[
					'nonutilitaran',
				],
				'nonutopian'=>[
					'nonutopan',
				],
				'nonvascular'=>[
					'nonvasculer',
				],
				'nonvegetarian'=>[
					'nonvegetaran',
				],
				'nonviable'=>[
					'nonviible',
				],
				'nonviolence'=>[
					'nonviolance',
				],
				'nonvoluntary'=>[
					'nonvoluntery',
				],
				'noon'=>[
					'noon noon',
					'noon noon noon',
				],
				'nor'=>[
					'nor nor',
					'nor nor nor',
				],
				'noradrenalin'=>[
					'nouradrenalin',
				],
				'noradrenaline'=>[
					'noradrenalini',
					'nouradrenaline',
				],
				'noradrenalines'=>[
					'nouradrenalines',
				],
				'noradrenalins'=>[
					'nouradrenalins',
				],
				'noradrenergic'=>[
					'nouradrenergic',
				],
				'norepinephrine'=>[
					'norepinephrini',
					'nourepinephrine',
				],
				'norepinephrines'=>[
					'norepinephrinis',
					'nourepinephrines',
				],
				'norethindrone'=>[
					'nourethindrone',
				],
				'norethindrones'=>[
					'nourethindrones',
				],
				'norites'=>[
					'nourites',
				],
				'noritic'=>[
					'nouritic',
				],
				'norland'=>[
					'nourland',
				],
				'norlands'=>[
					'nourlands',
				],
				'normalcies'=>[
					'nourmalcies',
				],
				'normalcy'=>[
					'normalsy',
					'nourmalcy',
				],
				'normalise'=>[
					'nourmalise',
				],
				'normalised'=>[
					'nourmalised',
				],
				'normalises'=>[
					'nourmalises',
				],
				'normalising'=>[
					'nourmalising',
				],
				'normalities'=>[
					'nourmalities',
				],
				'normality'=>[
					'nourmality',
				],
				'normalizable'=>[
					'nourmalizable',
				],
				'normalization'=>[
					'nourmalization',
				],
				'normalizations'=>[
					'nourmalizations',
				],
				'normalize'=>[
					'nourmalize',
				],
				'normalized'=>[
					'nourmalized',
				],
				'normalizer'=>[
					'nourmalizer',
				],
				'normalizers'=>[
					'nourmalizers',
				],
				'normalizes'=>[
					'nourmalizes',
				],
				'normalizing'=>[
					'nourmalizing',
				],
				'normally'=>[
					'normaly',
					'nourmally',
				],
				'normals'=>[
					'nourmals',
				],
				'normande'=>[
					'nourmande',
				],
				'normative'=>[
					'nourmative',
				],
				'normatively'=>[
					'normativly',
					'nourmatively',
				],
				'normativeness'=>[
					'nourmativeness',
				],
				'normativenesses'=>[
					'nourmativenesses',
				],
				'normless'=>[
					'nourmless',
				],
				'normotensive'=>[
					'nourmotensive',
				],
				'normotensives'=>[
					'nourmotensives',
				],
				'normothermia'=>[
					'nourmothermia',
				],
				'normothermias'=>[
					'nourmothermias',
				],
				'normothermic'=>[
					'nourmothermic',
				],
				'north'=>[
					'north north',
					'north north north',
					'noth',
				],
				'north-east'=>[
					'northeast\' & \'northwest',
				],
				'northbound'=>[
					'nourthbound',
				],
				'northeast'=>[
					'norteast',
					'northest',
					'nourtheast',
				],
				'northeaster'=>[
					'nourtheaster',
				],
				'northeasterly'=>[
					'northeasterally',
					'northeasteraly',
					'northeasterely',
					'northeasterlly',
					'northesterly',
					'nourtheasterly',
				],
				'northeastern'=>[
					'northereastern',
					'nourtheastern',
				],
				'northeasters'=>[
					'nourtheasters',
				],
				'northeasts'=>[
					'nourtheasts',
				],
				'northeastward'=>[
					'northestward',
					'nourtheastward',
				],
				'northeastwards'=>[
					'nourtheastwards',
				],
				'norther'=>[
					'nourther',
				],
				'northerlies'=>[
					'nourtherlies',
				],
				'northerly'=>[
					'northerally',
					'northeraly',
					'northerely',
					'northerlly',
					'nourtherly',
				],
				'northern'=>[
					'northen',
					'nothern',
					'nourthern',
				],
				'northernmost'=>[
					'northermost',
					'northernost',
					'nourthernmost',
				],
				'northerns'=>[
					'nourtherns',
				],
				'northers'=>[
					'nourthers',
				],
				'northing'=>[
					'nourthing',
				],
				'northings'=>[
					'nourthings',
				],
				'northland'=>[
					'nourthland',
				],
				'northlands'=>[
					'nourthlands',
				],
				'northmost'=>[
					'nourthmost',
				],
				'northward'=>[
					'nourthward',
				],
				'northwards'=>[
					'nothwards',
					'nourthwards',
				],
				'northwest'=>[
					'nortwest',
					'nourthwest',
				],
				'northwester'=>[
					'nourthwester',
				],
				'northwesterly'=>[
					'northwesterally',
					'northwesteraly',
					'northwesterely',
					'northwesterlly',
					'nourthwesterly',
				],
				'northwestern'=>[
					'nourthwestern',
				],
				'northwesters'=>[
					'nourthwesters',
				],
				'northwests'=>[
					'nourthwests',
				],
				'northwestward'=>[
					'nourthwestward',
				],
				'northwestwards'=>[
					'nourthwestwards',
				],
				'nortriptyline'=>[
					'nortriptylini',
					'nourtriptyline',
				],
				'nortriptylines'=>[
					'nourtriptylines',
				],
				'norway'=>[
					'norwway',
				],
				'norwegian'=>[
					'norweigan',
				],
				'norwegian-occupied'=>[
					'norwegian occupied',
				],
				'nose'=>[
					'nose nose',
					'nose nose nose',
				],
				'nosepiece'=>[
					'nosepeice',
					'nosepice',
				],
				'nosy'=>[
					'nocy',
				],
				'not'=>[
					'not not',
					'not not not',
					'nto',
				],
				'not to be'=>[
					'not te be',
				],
				'notable'=>[
					'noteable',
					'notible',
				],
				'notably'=>[
					'noteably',
				],
				'notary'=>[
					'notery',
				],
				'note'=>[
					'note note',
					'note note note',
				],
				'noteworthy'=>[
					'notewothy',
				],
				'nothing'=>[
					'nothing nothing',
					'nothing nothing nothing',
				],
				'nothingness'=>[
					'nothingnes',
				],
				'noticable'=>[
					'noticible',
				],
				'notice'=>[
					'notice notice',
					'notice notice notice',
				],
				'noticeable'=>[
					'noticable',
					'noticeble',
					'noticeible',
					'noticible',
				],
				'noticeably'=>[
					'noticably',
					'noticeabally',
					'noticeabaly',
					'noticeabely',
					'noticeablly',
					'noticebly',
					'noticibly',
				],
				'noticing'=>[
					'noticeing',
				],
				'notifiable'=>[
					'notifiible',
				],
				'notoriety'=>[
					'nortoriety',
					'notariety',
					'noteriety',
					'notoreity',
					'notority',
				],
				'notorious'=>[
					'nortorious',
					'notorios',
					'notorius',
					'notorous',
				],
				'notoriously'=>[
					'notorously',
				],
				'noun'=>[
					'noun noun',
					'noun noun noun',
				],
				'nourishment'=>[
					'nourishmant',
				],
				'nouveau'=>[
					'nouveu',
					'noveau',
				],
				'nouvelle'=>[
					'nouvele',
				],
				'novella'=>[
					'novela',
				],
				'november'=>[
					'nobember',
					'novembber',
					'novemeber',
					'novemebr',
					'novemver',
					'novermber',
				],
				'novemdecillion'=>[
					'novemdecilion',
				],
				'novgorod'=>[
					'novgord',
					'novgord', 'novgrod',
				],
				'now'=>[
					'now now',
					'now now now',
				],
				'now he'=>[
					'nowh e',
				],
				'nowadays'=>[
					'now a days',
					'now adays',
					'nowdays',
				],
				'noxious'=>[
					'noxous',
				],
				'noxiously'=>[
					'noxously',
				],
				'nuance'=>[
					'naunce',
					'nuence',
				],
				'nubbin'=>[
					'nubin',
				],
				'nubbinesses'=>[
					'nubinesses',
				],
				'nubble'=>[
					'nuble',
				],
				'nubbly'=>[
					'nubbally',
					'nubbaly',
					'nubbely',
					'nubblly',
					'nubly',
				],
				'nubby'=>[
					'nuby',
				],
				'nucellar'=>[
					'nuceller',
				],
				'nuclear'=>[
					'neuclear',
					'nucleer',
					'nucler',
					'nucular',
					'nuculear',
				],
				'nuclei'=>[
					'nuclie',
				],
				'nuclein'=>[
					'nuclien',
				],
				'nucleolar'=>[
					'nucleoler',
				],
				'nucleoprotein'=>[
					'nucleoprotien',
				],
				'nucleoproteins'=>[
					'nucleoprotiens',
				],
				'nucleus'=>[
					'nucleas',
					'nucleaus',
				],
				'nudely'=>[
					'nudly',
				],
				'nudie'=>[
					'nudei',
					'nudi',
				],
				'nugget'=>[
					'nuget',
				],
				'nuggets'=>[
					'nugets',
				],
				'nuggety'=>[
					'nugety',
				],
				'nuisance'=>[
					'nuisanse',
					'nuisence',
					'nusance',
				],
				'null'=>[
					'nul',
				],
				'nullah'=>[
					'nulla',
				],
				'nullahs'=>[
					'nullas',
				],
				'nullarbor'=>[
					'nullabour',
				],
				'nullification'=>[
					'nulification',
				],
				'nullify'=>[
					'nulify',
				],
				'nullipara'=>[
					'nullipera',
				],
				'number'=>[
					'number number',
					'number number number',
				],
				'numbskull'=>[
					'numbscul',
				],
				'numerable'=>[
					'numerible',
				],
				'numeracy'=>[
					'numerasy',
				],
				'numeral'=>[
					'numeral numeral',
					'numeral numeral numeral',
				],
				'numerary'=>[
					'numerery',
				],
				'numerous'=>[
					'numberous',
				],
				'numina'=>[
					'numini',
				],
				'nummary'=>[
					'nummery',
				],
				'nummular'=>[
					'nummuler',
					'numnular',
				],
				'nummulite'=>[
					'numnulite',
				],
				'nunnery'=>[
					'nunery',
				],
				'nuptial'=>[
					'nuptual',
				],
				'nuremberg'=>[
					'nuremburg',
				],
				'nurturance'=>[
					'nurturence',
				],
				'nusch éluard'=>[
					'nusch eluard',
				],
				'nutant'=>[
					'nutent',
				],
				'nutrient'=>[
					'nutreint',
					'nutriant',
					'nutrint',
					'nutritent',
				],
				'nutritious'=>[
					'nutritous',
				],
				'nutritiously'=>[
					'nutritously',
				],
				'nutritively'=>[
					'nutritivly',
				],
				'nutsedge'=>[
					'nutsege',
				],
				'nutsedges'=>[
					'nutseges',
				],
				'nutshell'=>[
					'nutshel',
				],
				'nutsy'=>[
					'nutcy',
				],
				'nympholepsy'=>[
					'nympholepcy',
				],
				'née'=>[
					'neé',
				],
				'néron'=>[
					'neron',
				],
				'ní'=>[
					'ni',
				],
			];
		}
	}

?>