<?php
				
				/* EnglishMisspellingsWords_K
					
					Class for English-Misspellings for all words beginning with : K.
					
				*/

	class EnglishMisspellingsWords_K {
			/* __construct($args)
			
				Constructor.
				
				Nothing to do here.
			
			*/
			
		public function __construct($args) {
			return TRUE;
		}
		
			/* EnglishMisspellingsWords()
			
				List of English misspellings for words starting with : K.
			
			*/

		public function EnglishMisspellingsWords() {
			return [
				'kabar'=>[
					'kaber',
				],
				'kabbala'=>[
					'kabala',
				],
				'kabbalah'=>[
					'kabalah',
					'kabbala',
				],
				'kabbalahs'=>[
					'kabalahs',
					'kabbalas',
				],
				'kabbalas'=>[
					'kabalas',
				],
				'kabbalism'=>[
					'kabalism',
				],
				'kabbalisms'=>[
					'kabalisms',
				],
				'kabbalist'=>[
					'kabalist',
				],
				'kabbalists'=>[
					'kabalists',
				],
				'kachina'=>[
					'kachini',
				],
				'kaffeeklatsch'=>[
					'kaffeeklatch',
					'kaffeeklatcsh',
					'kaffeeklatsh',
				],
				'kaffeeklatsches'=>[
					'kaffeeklatches',
					'kaffeeklatcshes',
					'kaffeeklatshes',
				],
				'kaffiyah'=>[
					'kaffiya',
				],
				'kaffiyahs'=>[
					'kaffiyas',
				],
				'kahuna'=>[
					'kauna',
				],
				'kahunas'=>[
					'kaunas',
				],
				'kainit'=>[
					'kainat',
				],
				'kainite'=>[
					'kainate',
				],
				'kainits'=>[
					'kainats',
				],
				'kaleidoscope'=>[
					'kaliedoscope',
					'kaleidocope',
					'kaleidocsope',
					'kaleidosope',
				],
				'kaleidoscopes'=>[
					'kaliedoscopes',
				],
				'kaleidoscopic'=>[
					'kaliedoscopic',
				],
				'kalian'=>[
					'kalan',
				],
				'kallikrein'=>[
					'kallikrien',
				],
				'kallikreins'=>[
					'kallikriens',
				],
				'kalsomining'=>[
					'kalsominang',
				],
				'kampuchean-occupied'=>[
					'kampuchean occupied',
				],
				'kantar'=>[
					'kentar',
				],
				'kaolinite'=>[
					'kaolinate',
				],
				'kapellmeister'=>[
					'kapellmiester',
				],
				'kapellmeisters'=>[
					'kapellmiesters',
				],
				'kappa'=>[
					'kapa',
				],
				'karateist'=>[
					'karatiest',
				],
				'karateists'=>[
					'karatiests',
				],
				'kaross'=>[
					'karos',
				],
				'karroo'=>[
					'karoo',
				],
				'karyokinesis'=>[
					'karyokinisis',
				],
				'kasbah'=>[
					'kasba',
				],
				'kasbahs'=>[
					'kasbas',
				],
				'katcina'=>[
					'katcini',
				],
				'katzenjammer'=>[
					'katzenjamner',
				],
				'katzenjammers'=>[
					'katzenjamners',
				],
				'kbar'=>[
					'kber',
				],
				'kea'=>[
					'ke',
				],
				'keas'=>[
					'kes',
				],
				'kebar'=>[
					'keber',
				],
				'kebbie'=>[
					'kebie',
				],
				'kebbies'=>[
					'kebies',
				],
				'kebbock'=>[
					'kebock',
				],
				'kebbocks'=>[
					'kebocks',
				],
				'kebbuck'=>[
					'kebuck',
				],
				'kebbucks'=>[
					'kebucks',
				],
				'keblah'=>[
					'kebla',
				],
				'keddah'=>[
					'kedda',
				],
				'keddahs'=>[
					'keddas',
				],
				'kedge'=>[
					'kege',
				],
				'kedged'=>[
					'keged',
				],
				'kedgeree'=>[
					'kegeree',
				],
				'kedgerees'=>[
					'kegerees',
				],
				'kedges'=>[
					'keges',
				],
				'keened'=>[
					'keend',
				],
				'keep'=>[
					'keep keep',
					'keep keep keep',
				],
				'keepable'=>[
					'keepible',
				],
				'keffiyah'=>[
					'keffiya',
				],
				'keffiyahs'=>[
					'keffiyas',
				],
				'kegger'=>[
					'keger',
				],
				'keir'=>[
					'kier',
				],
				'keiretsu'=>[
					'kieretsu',
				],
				'keiretsus'=>[
					'kieretsus',
				],
				'keirs'=>[
					'kiers',
				],
				'keister'=>[
					'kiester',
				],
				'keisters'=>[
					'kiesters',
				],
				'keitloas'=>[
					'kietloas',
				],
				'kelly'=>[
					'kelally',
					'kelaly',
					'kellly',
				],
				'kennel'=>[
					'kenel',
				],
				'kenneling'=>[
					'keneling',
				],
				'kennelled'=>[
					'kenelled',
				],
				'kenning'=>[
					'kening',
				],
				'kent'=>[
					'kant',
				],
				'kente'=>[
					'kante',
				],
				'kentes'=>[
					'kantes',
				],
				'kentledge'=>[
					'kentlege',
				],
				'kentledges'=>[
					'kentleges',
				],
				'kenyan-occupied'=>[
					'kenyan occupied',
				],
				'kept'=>[
					'keeped',
					'kept kept',
					'kept kept kept',
				],
				'keratinization'=>[
					'keratinazation',
				],
				'keratinizations'=>[
					'keratinazations',
				],
				'keratinize'=>[
					'keratinaze',
				],
				'keratinized'=>[
					'keratinazed',
				],
				'keratinizes'=>[
					'keratinazes',
				],
				'keratinizing'=>[
					'keratinazing',
				],
				'kerchief'=>[
					'kercheif',
					'kerchif',
				],
				'kerria'=>[
					'keria',
				],
				'kerry'=>[
					'kery',
				],
				'ketamine'=>[
					'ketamini',
				],
				'key'=>[
					'key key',
					'key key key',
				],
				'keyboard'=>[
					'keybord',
				],
				'keyboards'=>[
					'keybords',
				],
				'khaddar'=>[
					'khadder',
				],
				'khazakstani-occupied'=>[
					'khazakstani occupied',
				],
				'khedah'=>[
					'kheda',
				],
				'khedahs'=>[
					'khedas',
				],
				'khirkah'=>[
					'khirka',
				],
				'khirkahs'=>[
					'khirkas',
				],
				'kibbe'=>[
					'kibe',
				],
				'kibbeh'=>[
					'kibeh',
				],
				'kibbehs'=>[
					'kibehs',
				],
				'kibbes'=>[
					'kibes',
				],
				'kibbi'=>[
					'kibi',
				],
				'kibbis'=>[
					'kibis',
				],
				'kibbitz'=>[
					'kibitz',
				],
				'kibbitzed'=>[
					'kibitzed',
				],
				'kibbitzer'=>[
					'kibitzer',
				],
				'kibbitzers'=>[
					'kibitzers',
				],
				'kibbitzes'=>[
					'kibitzes',
				],
				'kibbitzing'=>[
					'kibitzing',
				],
				'kibble'=>[
					'kible',
				],
				'kibbutz'=>[
					'kibutz',
				],
				'kibbutzim'=>[
					'kibutzim',
				],
				'kibbutznik'=>[
					'kibutznik',
				],
				'kibbutzniks'=>[
					'kibutzniks',
				],
				'kibei'=>[
					'kibie',
				],
				'kiblah'=>[
					'kibla',
				],
				'kiblahs'=>[
					'kiblas',
				],
				'kiddie'=>[
					'kiddei',
					'kiddi',
				],
				'kief'=>[
					'keif',
				],
				'kielbasa'=>[
					'keilbasa',
					'kilbasa',
				],
				'kielbasy'=>[
					'kielbacy',
				],
				'kier'=>[
					'keir',
				],
				'kill'=>[
					'kill kill',
					'kill kill kill',
					'kil',
				],
				'killed'=>[
					'kiled',
				],
				'killer'=>[
					'kiler',
				],
				'killing'=>[
					'kiling',
				],
				'kilobar'=>[
					'kilober',
				],
				'kilocalorie'=>[
					'kilocalorei',
					'kilocalori',
				],
				'kilogram'=>[
					'killogram',
				],
				'kilometer'=>[
					'killometer',
				],
				'kilometre'=>[
					'killometre',
				],
				'kiloparsecs'=>[
					'kilopersecs',
				],
				'kinara'=>[
					'kinira',
				],
				'kinaras'=>[
					'kiniras',
				],
				'kinas'=>[
					'kinis',
				],
				'kinase'=>[
					'kinise',
				],
				'kinases'=>[
					'kinises',
				],
				'kind'=>[
					'kind kind',
					'kind kind kind',
				],
				'kindergarten'=>[
					'kindergarden',
					'kindergarden ',
					'kindnergarden',
					'kindnergarten',
				],
				'kindergartens'=>[
					'kindergardens',
					'kindnergardens',
					'kindnergartens',
				],
				'kindhearted'=>[
					'kindherted',
				],
				'kindheartedness'=>[
					'kindhertedness',
				],
				'kindliness'=>[
					'kindliniss',
				],
				'kindly'=>[
					'kindally',
					'kindaly',
					'kindely',
					'kindlly',
				],
				'kindness'=>[
					'kindenss',
					'kindnes',
				],
				'kinematics'=>[
					'kinimatics',
				],
				'kines'=>[
					'kinis',
				],
				'kinescope'=>[
					'kinoscope',
				],
				'kinesiology'=>[
					'kinisiology',
				],
				'kinesis'=>[
					'kinisis',
				],
				'kinesthesia'=>[
					'kinisthesia',
				],
				'kinesthetically'=>[
					'kinisthetically',
				],
				'kinetic'=>[
					'kinitic',
				],
				'kinetics'=>[
					'kinitics',
				],
				'kinetin'=>[
					'kinitin',
				],
				'kinetochore'=>[
					'kinitochore',
				],
				'kinetoplast'=>[
					'kinitoplast',
				],
				'kinetoscope'=>[
					'kinetocope',
					'kinetocsope',
					'kinetosope',
					'kinitoscope',
				],
				'king'=>[
					'king king',
					'king king king',
				],
				'kingdom'=>[
					'kingdon',
				],
				'kingly'=>[
					'kingally',
					'kingaly',
					'kingely',
					'kinglly',
				],
				'kinin'=>[
					'kinan',
				],
				'kinins'=>[
					'kinans',
				],
				'kinnikinnick'=>[
					'kinnikinick',
				],
				'kinnikinnicks'=>[
					'kinnikinicks',
				],
				'kipper'=>[
					'kiper',
				],
				'kirsch'=>[
					'kirch',
					'kircsh',
					'kirsh',
				],
				'kiss'=>[
					'kis',
				],
				'kisser'=>[
					'kiser',
				],
				'kissy'=>[
					'kiscy',
					'kisy',
				],
				'kitsch'=>[
					'kitch',
					'kitcsh',
					'kitsh',
				],
				'kittened'=>[
					'kittend',
				],
				'klebsiella'=>[
					'klebseilla',
					'klebsiela',
					'klebsilla',
				],
				'klezmorim'=>[
					'klezmourim',
				],
				'knar'=>[
					'kner',
				],
				'knead'=>[
					'kned',
				],
				'kneecappings'=>[
					'kneecapings',
				],
				'knell'=>[
					'knel',
				],
				'knew'=>[
					'knew knew',
					'knew knew knew',
					'knowed',
				],
				'knightlinesses'=>[
					'knightlinisses',
				],
				'knitwear'=>[
					'knitweer',
				],
				'knives'=>[
					'knifes',
				],
				'knob'=>[
					'kob',
				],
				'knobbed'=>[
					'kobbed',
				],
				'knobbier'=>[
					'kobbier',
				],
				'knobbiest'=>[
					'knobiest',
					'kobbiest',
				],
				'knobblier'=>[
					'knoblier',
					'kobblier',
				],
				'knobbliest'=>[
					'knobliest',
					'kobbliest',
				],
				'knobbly'=>[
					'knobbally',
					'knobbaly',
					'knobbely',
					'knobblly',
					'knobly',
					'kobbly',
				],
				'knobby'=>[
					'knoby',
					'kobby',
				],
				'knobkerrie'=>[
					'knobkerrei',
					'knobkerie',
					'knobkerri',
					'kobkerrie',
				],
				'knobkerries'=>[
					'kobkerries',
				],
				'knoblike'=>[
					'koblike',
				],
				'knobs'=>[
					'kobs',
				],
				'knock'=>[
					'kock',
				],
				'knockabout'=>[
					'kockabout',
				],
				'knockabouts'=>[
					'kockabouts',
				],
				'knockdown'=>[
					'kockdown',
				],
				'knockdowns'=>[
					'kockdowns',
				],
				'knocked'=>[
					'kocked',
				],
				'knocker'=>[
					'kocker',
				],
				'knockers'=>[
					'kockers',
				],
				'knocking'=>[
					'kocking',
				],
				'knockless'=>[
					'kockless',
				],
				'knockoff'=>[
					'kockoff',
				],
				'knockoffs'=>[
					'kockoffs',
				],
				'knockout'=>[
					'kockout',
				],
				'knockouts'=>[
					'kockouts',
				],
				'knocks'=>[
					'kocks',
				],
				'knockwurst'=>[
					'kockwurst',
				],
				'knockwursts'=>[
					'kockwursts',
				],
				'knoll'=>[
					'knol',
					'koll',
				],
				'knolled'=>[
					'kolled',
				],
				'knoller'=>[
					'koller',
				],
				'knollers'=>[
					'kollers',
				],
				'knolling'=>[
					'kolling',
				],
				'knolls'=>[
					'kolls',
				],
				'knolly'=>[
					'kolly',
				],
				'knop'=>[
					'kop',
				],
				'knopped'=>[
					'kopped',
				],
				'knops'=>[
					'kops',
				],
				'knosp'=>[
					'kosp',
				],
				'knosps'=>[
					'kosps',
				],
				'knot'=>[
					'kot',
				],
				'knotgrass'=>[
					'kotgrass',
				],
				'knotgrasses'=>[
					'kotgrasses',
				],
				'knothole'=>[
					'kothole',
				],
				'knotholes'=>[
					'kotholes',
				],
				'knotless'=>[
					'kotless',
				],
				'knotlike'=>[
					'kotlike',
				],
				'knots'=>[
					'kots',
				],
				'knotted'=>[
					'kotted',
				],
				'knotter'=>[
					'kotter',
				],
				'knotters'=>[
					'kotters',
				],
				'knottier'=>[
					'kottier',
				],
				'knottiest'=>[
					'kottiest',
				],
				'knottily'=>[
					'kottily',
				],
				'knottiness'=>[
					'kottiness',
				],
				'knottinesses'=>[
					'kottinesses',
				],
				'knotting'=>[
					'kotting',
				],
				'knottings'=>[
					'kottings',
				],
				'knotty'=>[
					'kotty',
				],
				'knotweed'=>[
					'kotweed',
				],
				'knotweeds'=>[
					'kotweeds',
				],
				'knout'=>[
					'kout',
				],
				'knouted'=>[
					'kouted',
				],
				'knouting'=>[
					'kouting',
				],
				'knouts'=>[
					'kouts',
				],
				'know'=>[
					'know know',
					'know know know',
					'knwo',
					'konw',
					'lnow',
					'nkow',
					'nkwo',
					'kow',
				],
				'knowable'=>[
					'kowable',
				],
				'knower'=>[
					'kower',
				],
				'knowers'=>[
					'kowers',
				],
				'knowing'=>[
					'kowing',
				],
				'knowinger'=>[
					'kowinger',
				],
				'knowingest'=>[
					'kowingest',
				],
				'knowingly'=>[
					'kowingly',
				],
				'knowingness'=>[
					'kowingness',
				],
				'knowingnesses'=>[
					'kowingnesses',
				],
				'knowings'=>[
					'kowings',
				],
				'knowledge'=>[
					'knoweldge',
					'knowldge',
					'knowlege',
					'knowlege ',
					'kowledge',
				],
				'knowledgeable'=>[
					'knowlegeable',
					'knowledgeble',
					'knowledgeible',
					'kowledgeable',
				],
				'knowledgeably'=>[
					'knowlegeably',
					'kowledgeably',
				],
				'knowledges'=>[
					'knowleges',
					'kowledges',
				],
				'known'=>[
					'knowed',
					'konwn',
					'kown',
				],
				'knowns'=>[
					'kowns',
				],
				'knows'=>[
					'know\'s',
					'knwos',
					'konws',
					'kows',
				],
				'knubbiest'=>[
					'knubiest',
				],
				'knubby'=>[
					'knuby',
				],
				'knucklehead'=>[
					'knucklehed',
				],
				'koine'=>[
					'koini',
				],
				'koines'=>[
					'koinis',
				],
				'kolkhosy'=>[
					'kolkhocy',
				],
				'kookaburra'=>[
					'kookabura',
				],
				'koppa'=>[
					'kopa',
				],
				'koppie'=>[
					'kopie',
				],
				'korean-occupied'=>[
					'korean occupied',
				],
				'koss'=>[
					'kos',
				],
				'kowtow'=>[
					'cowtow',
				],
				'krill'=>[
					'kril',
				],
				'krimmer'=>[
					'krimner',
				],
				'krimmers'=>[
					'krimners',
				],
				'kropotkin'=>[
					'kroptkin',
					'kroptokin',
				],
				'krummholz'=>[
					'krumnholz',
				],
				'krummhorn'=>[
					'krumnhorn',
				],
				'kruševo'=>[
					'krusevo',
				],
				'ku klux klan'=>[
					'klu klux klan',
				],
				'kummel'=>[
					'kumnel',
				],
				'kumquat'=>[
					'kumqaut',
				],
				'kundalini'=>[
					'kundalina',
				],
				'kurdish-occupied'=>[
					'kurdish occupied',
				],
				'kurrajong'=>[
					'kurajong',
				],
				'kusso'=>[
					'kuso',
				],
				'kuwaiti-occupied'=>[
					'kuwaiti occupied',
				],
				'kvass'=>[
					'kvas',
				],
				'kvell'=>[
					'kvel',
				],
				'kyar'=>[
					'kyer',
				],
			];
		}
	}

?>