<?php
		
		/* UTF-8 TEST
		
			中文汉字漢字
		
		*/
				
				/* EnglishMisspellingsWords_V
					
					Class for English-Misspellings for all words beginning with : V.
					
				*/

	class EnglishMisspellingsWords_V {
			/* __construct($args)
			
				Constructor.
				
				Nothing to do here.
			
			*/
			
		public function __construct($args) {
			return TRUE;
		}
		
			/* EnglishMisspellingsWords()
			
				List of English misspellings for words starting with : V.
			
			*/

		public function EnglishMisspellingsWords() {
			return [
				'vacancy'=>[
					'vacansy',
					'vacency',
				],
				'vacant'=>[
					'vacent',
				],
				'vaccina'=>[
					'vaccini',
					'vacina',
				],
				'vaccinal'=>[
					'vaccinil',
					'vacinal',
				],
				'vaccinas'=>[
					'vaccinis',
				],
				'vaccinate'=>[
					'vaccinite',
					'vacinate',
				],
				'vaccinated'=>[
					'vaccinited',
				],
				'vaccinates'=>[
					'vaccinites',
				],
				'vaccination'=>[
					'vaccinition',
					'vacination',
				],
				'vaccinations'=>[
					'vaccinitions',
				],
				'vaccinator'=>[
					'vaccinitor',
				],
				'vaccine'=>[
					'vaccini',
					'vacine',
				],
				'vaccinee'=>[
					'vacinee',
				],
				'vaccinia'=>[
					'vaccinaa',
					'vacinia',
				],
				'vacua'=>[
					'vacau',
				],
				'vacuolar'=>[
					'vacolar',
					'vacuoler',
				],
				'vacuolate'=>[
					'vacolate',
				],
				'vacuolated'=>[
					'vacolated',
				],
				'vacuolation'=>[
					'vacolation',
				],
				'vacuolations'=>[
					'vacolations',
				],
				'vacuole'=>[
					'vacole',
				],
				'vacuoles'=>[
					'vacoles',
				],
				'vacuous'=>[
					'vacous',
				],
				'vacuously'=>[
					'vacously',
				],
				'vacuousness'=>[
					'vacousness',
				],
				'vacuousnesses'=>[
					'vacousnesses',
				],
				'vacuum'=>[
					'vaccum',
					'vaccum/vaccume',
					'vaccume',
					'vaccuum',
					'vacum',
					'vacume',
				],
				'vagarious'=>[
					'vagarous',
				],
				'vagariously'=>[
					'vagarously',
				],
				'vagary'=>[
					'vagery',
				],
				'vagina'=>[
					'vagini',
				],
				'vaginae'=>[
					'vaginie',
				],
				'vaginal'=>[
					'vaginil',
				],
				'vaginally'=>[
					'vaginilly',
				],
				'vaginas'=>[
					'vaginis',
				],
				'vaginate'=>[
					'vaginite',
				],
				'vaginated'=>[
					'vaginited',
				],
				'vaginismus'=>[
					'vaginasmus',
				],
				'vaginitis'=>[
					'vaginatis',
				],
				'vagrancy'=>[
					'vagransy',
				],
				'vagrant'=>[
					'vagrent',
				],
				'vaguely'=>[
					'vaguly',
				],
				'vahine'=>[
					'vahini',
					'vaine',
				],
				'vainglorious'=>[
					'vainglorous',
				],
				'vaingloriously'=>[
					'vaingloriousally',
					'vaingloriousaly',
					'vaingloriousely',
					'vaingloriouslly',
					'vainglorously',
				],
				'valance'=>[
					'valence',
				],
				'valedictorian'=>[
					'valedictoran',
				],
				'valence'=>[
					'valance',
				],
				'valency'=>[
					'valensy',
				],
				'valentine'=>[
					'valantine',
					'valentini',
				],
				'valerian'=>[
					'valeran',
				],
				'valetudinarian'=>[
					'valetudinaran',
					'valetudinirian',
				],
				'valetudinarians'=>[
					'valetudinirians',
				],
				'valetudinaries'=>[
					'valetudiniries',
				],
				'valetudinary'=>[
					'valetudinery',
					'valetudiniry',
				],
				'valiance'=>[
					'valience',
				],
				'valiancy'=>[
					'valiansy',
				],
				'valiant'=>[
					'valient',
				],
				'validly'=>[
					'validally',
					'validaly',
					'validely',
					'validlly',
				],
				'valine'=>[
					'valini',
				],
				'valium'=>[
					'vallium',
				],
				'vallecular'=>[
					'valleculer',
				],
				'valley'=>[
					'valey',
					'valley valley',
					'valley valley valley',
				],
				'valparaiso'=>[
					'valpariso',
				],
				'valuable'=>[
					'valauble',
					'valuble',
					'valueable',
					'valuible',
				],
				'valuables'=>[
					'valubles',
					'valueables',
				],
				'valuate'=>[
					'valaute',
				],
				'valuation'=>[
					'valaution',
				],
				'valuator'=>[
					'valautor',
				],
				'value'=>[
					'value value',
					'value value value',
				],
				'valvar'=>[
					'valver',
				],
				'valvular'=>[
					'valvuler',
				],
				'valència'=>[
					'valencia',
				],
				'van trees'=>[
					'van tress',
				],
				'vanguard'=>[
					'vangaurd',
				],
				'vanilla'=>[
					'vanila',
				],
				'vanish'=>[
					'vannish',
				],
				'vanman'=>[
					'vaman',
					'vanan',
				],
				'vanmen'=>[
					'vamen',
					'vanen',
				],
				'vantage'=>[
					'ventage',
				],
				'vapidly'=>[
					'vapidally',
					'vapidaly',
					'vapidely',
					'vapidlly',
				],
				'variable'=>[
					'varable',
					'varible',
					'variible',
				],
				'variance'=>[
					'varience',
				],
				'variant'=>[
					'varient',
				],
				'variants'=>[
					'varients',
				],
				'variation'=>[
					'varietion',
				],
				'varied'=>[
					'vareid',
					'varid',
				],
				'variegated'=>[
					'vareigated',
					'varigated',
				],
				'variegation'=>[
					'vareigation',
					'varigation',
				],
				'varies'=>[
					'varys',
				],
				'varietal'=>[
					'vareital',
					'varital',
				],
				'varieties'=>[
					'varietes',
					'varities',
				],
				'variety'=>[
					'vairety',
					'vareity',
					'variaty',
					'varity',
				],
				'variolar'=>[
					'varioler',
				],
				'various'=>[
					'vairous',
					'varios',
					'varius',
					'varlous',
					'varoius',
					'varous',
				],
				'variously'=>[
					'variosly',
					'varously',
				],
				'varsity'=>[
					'varisty',
				],
				'vary'=>[
					'vary vary',
					'vary vary vary',
				],
				'vascular'=>[
					'vacsular',
					'vacular',
					'vasculer',
					'vasular',
				],
				'vascularization'=>[
					'vacsularization',
					'vacularization',
					'vasularization',
				],
				'vasculature'=>[
					'vacsulature',
					'vaculature',
					'vasulature',
				],
				'vasculitis'=>[
					'vacsulitis',
					'vaculitis',
					'vasulitis',
				],
				'vasodilation'=>[
					'vasodialation',
				],
				'vasodilator'=>[
					'vasodialator',
				],
				'vasopressin'=>[
					'vasopresin',
				],
				'vassal'=>[
					'vasal',
					'vasall',
				],
				'vassals'=>[
					'vasalls',
				],
				'vaticinal'=>[
					'vaticinil',
				],
				'vaticinate'=>[
					'vaticinite',
				],
				'vaticinating'=>[
					'vaticiniting',
				],
				'vaticination'=>[
					'vaticinition',
				],
				'vaticinations'=>[
					'vaticinitions',
				],
				'vaticinators'=>[
					'vaticinitors',
				],
				'vaudeville'=>[
					'vaudevile',
				],
				'vaudevillian'=>[
					'vaudevilian',
					'vaudevillan',
				],
				'veal'=>[
					'vel',
				],
				'vealy'=>[
					'veaally',
					'veaaly',
					'veally',
				],
				'vector-borne'=>[
					'vector-born',
				],
				'vegetable'=>[
					'vegatable',
					'vegetible',
					'vegitable',
					'vegtable',
				],
				'vegetables'=>[
					'vegeatables',
					'vegitables',
					'vegtables',
				],
				'vegetarian'=>[
					'vegatarian',
					'vegetaran',
					'vegeterian',
					'vegitarian',
					'vegtarian',
				],
				'vegetarianism'=>[
					'vegitarianism',
					'vegtarianism',
				],
				'vegetarians'=>[
					'vegitarians',
					'vegtarians',
				],
				'vegetatively'=>[
					'vegetativly',
				],
				'vegged'=>[
					'veged',
				],
				'veggie'=>[
					'veggei',
					'veggi',
					'vegie',
				],
				'vehemence'=>[
					'vehemance',
				],
				'vehemency'=>[
					'vehemensy',
				],
				'vehement'=>[
					'vehemant',
				],
				'vehicle'=>[
					'vechicle',
					'vehichle',
				],
				'vehicular'=>[
					'vehiculer',
				],
				'veil'=>[
					'viel',
				],
				'veiled'=>[
					'vieled',
				],
				'veiling'=>[
					'vieling',
				],
				'veils'=>[
					'viels',
				],
				'vein'=>[
					'veign',
					'vien',
				],
				'veinal'=>[
					'veinil',
				],
				'veined'=>[
					'veinid',
					'viened',
				],
				'veinier'=>[
					'veinaer',
				],
				'veining'=>[
					'veinang',
					'viening',
				],
				'veinlet'=>[
					'vienlet',
				],
				'veins'=>[
					'viens',
				],
				'veinstone'=>[
					'vienstone',
				],
				'veinule'=>[
					'vienule',
				],
				'veiny'=>[
					'vieny',
				],
				'velamina'=>[
					'velamini',
				],
				'velar'=>[
					'veler',
				],
				'velleity'=>[
					'velliety',
				],
				'vellum'=>[
					'velum',
				],
				'vendable'=>[
					'vendible',
				],
				'vendible'=>[
					'vendable',
				],
				'venerable'=>[
					'venerible',
				],
				'venetian'=>[
					'venetan',
				],
				'venezualan-occupied'=>[
					'venezualan occupied',
				],
				'venezuela'=>[
					'venezeula',
					'venezuala',
					'venezulea',
				],
				'vengeance'=>[
					'vengance',
					'vengeence',
					'vengence',
				],
				'venice'=>[
					'vemce',
				],
				'venomous'=>[
					'venemous',
				],
				'vent'=>[
					'vant',
				],
				'venter'=>[
					'vanter',
				],
				'ventilation'=>[
					'vantilation',
				],
				'ventilator'=>[
					'vantilator',
				],
				'ventral'=>[
					'vantral',
				],
				'ventricular'=>[
					'vantricular',
					'ventriculer',
				],
				'ventriloquism'=>[
					'vantriloquism',
				],
				'ventriloquist'=>[
					'vantriloquist',
				],
				'ventriloquize'=>[
					'vantriloquize',
				],
				'ventrolateral'=>[
					'vantrolateral',
				],
				'ventromedial'=>[
					'vantromedial',
				],
				'vents'=>[
					'vants',
				],
				'venture'=>[
					'vanture',
				],
				'venturesomely'=>[
					'venturesomly',
				],
				'venturi'=>[
					'vanturi',
				],
				'venular'=>[
					'venuler',
				],
				'veracious'=>[
					'veracous',
				],
				'veraciously'=>[
					'veraciousally',
					'veraciousaly',
					'veraciousely',
					'veraciouslly',
					'veracously',
				],
				'verandah'=>[
					'veranda',
				],
				'verandahed'=>[
					'verandaed',
				],
				'verandahs'=>[
					'verandas',
				],
				'veratridine'=>[
					'veratridini',
				],
				'verb'=>[
					'verb verb',
					'verb verb verb',
				],
				'verbally'=>[
					'verbaly',
				],
				'verbiage'=>[
					'verbage',
				],
				'verbosely'=>[
					'verbosly',
				],
				'verdancy'=>[
					'verdansy',
				],
				'verdant'=>[
					'verdent',
				],
				'verdantly'=>[
					'verdently',
				],
				'vergence'=>[
					'vergance',
				],
				'verifiable'=>[
					'varifiable',
					'verifiible',
				],
				'verification'=>[
					'verfication',
				],
				'verified'=>[
					'verifed',
				],
				'verify'=>[
					'varify',
				],
				'verifying'=>[
					'verifing',
				],
				'verily'=>[
					'verially',
					'verialy',
					'veriely',
					'verilly',
				],
				'verisimilar'=>[
					'verisimiler',
				],
				'verisimilarly'=>[
					'verisimilarally',
					'verisimilaraly',
					'verisimilarely',
					'verisimilarlly',
				],
				'verisimilitude'=>[
					'versimilitude',
				],
				'verision'=>[
					'verson',
				],
				'veritable'=>[
					'veritible',
				],
				'vermeil'=>[
					'vermiel',
				],
				'vermian'=>[
					'verman',
				],
				'vermicular'=>[
					'vermiculer',
				],
				'vermilion'=>[
					'vermillion',
				],
				'vernacular'=>[
					'venacular',
					'vernaculer',
				],
				'vernier'=>[
					'verneir',
					'vernir',
				],
				'vernon'=>[
					'vermon',
				],
				'verruca'=>[
					'veruca',
				],
				'versant'=>[
					'versent',
				],
				'versatile'=>[
					'versitile',
				],
				'versatilely'=>[
					'versatilly',
				],
				'versatility'=>[
					'versitility',
				],
				'versicular'=>[
					'versiculer',
				],
				'version'=>[
					'verion',
					'verison',
					'versione',
				],
				'vertebra'=>[
					'vertabra',
				],
				'vertebrate'=>[
					'vertabrate',
				],
				'vertical'=>[
					'verticle',
				],
				'verticillate'=>[
					'verticilate',
				],
				'very'=>[
					'very very',
					'very very very',
					'veyr',
					'vrey',
					'vyer',
					'vyre',
				],
				'vesicular'=>[
					'vesiculer',
				],
				'vespertilian'=>[
					'vespertilan',
				],
				'vespertine'=>[
					'vespertini',
				],
				'vespiary'=>[
					'vespiery',
				],
				'vessel'=>[
					'vesel',
				],
				'vestiary'=>[
					'vestiery',
				],
				'vestibular'=>[
					'vestibuler',
				],
				'vesuvian'=>[
					'vesuvan',
				],
				'veteran'=>[
					'veteren',
					'vetran',
				],
				'veterinarian'=>[
					'veterinaran',
					'veterinirian',
					'vetinarian',
				],
				'veterinarians'=>[
					'veterinirians',
				],
				'veterinaries'=>[
					'veteriniries',
				],
				'veterinary'=>[
					'veterinery',
					'veteriniry',
					'vetinary',
				],
				'vetted'=>[
					'veted',
				],
				'vexatious'=>[
					'vexatous',
				],
				'vexatiously'=>[
					'vexatously',
				],
				'vexillar'=>[
					'vexiller',
				],
				'vexillary'=>[
					'vexillery',
				],
				'viable'=>[
					'viible',
				],
				'vial'=>[
					'phial',
				],
				'vibraharp'=>[
					'vibraarp',
				],
				'vibraharpist'=>[
					'vibraarpist',
				],
				'vibraharpists'=>[
					'vibraarpists',
				],
				'vibraharps'=>[
					'vibraarps',
				],
				'vibrance'=>[
					'vibrence',
				],
				'vibrancy'=>[
					'vibransy',
				],
				'vibrant'=>[
					'vibrent',
				],
				'vicar'=>[
					'vicer',
				],
				'vicariance'=>[
					'vicarience',
				],
				'vicarious'=>[
					'vicarous',
				],
				'vicariously'=>[
					'vicariousally',
					'vicariousaly',
					'vicariousely',
					'vicariouslly',
					'vicarously',
				],
				'vice versa'=>[
					'vice-versa',
					'viceversa',
				],
				'vice-minister'=>[
					'viceminister',
				],
				'vicegerency'=>[
					'vicegerensy',
				],
				'vicenary'=>[
					'vicenery',
				],
				'vicennial'=>[
					'vicenial',
				],
				'vicente fox'=>[
					'vincente fox',
				],
				'vicereine'=>[
					'viceriene',
				],
				'vichyssoise'=>[
					'vichysoise',
				],
				'vicinage'=>[
					'vicinige',
				],
				'vicinages'=>[
					'viciniges',
				],
				'vicinal'=>[
					'vicinil',
				],
				'vicinity'=>[
					'vacinity',
					'vicinaty',
					'vicintity',
					'vicinty',
					'vincinity',
				],
				'vicious'=>[
					'vicous',
					'viscious',
					'viscous',
				],
				'viciously'=>[
					'vicously',
					'visciousely',
					'visciously',
					'viscousely',
					'viscously',
				],
				'vicissitude'=>[
					'vicisitude',
				],
				'vicodin'=>[
					'vicoden',
				],
				'vicous'=>[
					'viscous',
				],
				'victorious'=>[
					'victorous',
				],
				'victoriously'=>[
					'victorously',
				],
				'victual'=>[
					'victaul',
				],
				'victualer'=>[
					'victauler',
				],
				'video'=>[
					'vidéo',
				],
				'videocassette'=>[
					'videocasette',
				],
				'videoconference'=>[
					'videoconferance',
				],
				'videodisc'=>[
					'videodic',
					'videodics',
					'videodis',
				],
				'vie'=>[
					'vei',
				],
				'vied'=>[
					'veid',
				],
				'vier'=>[
					'veir',
				],
				'vies'=>[
					'veis',
				],
				'vietnam'=>[
					'vetnam',
				],
				'vietnamese'=>[
					'vietnames',
				],
				'vietnamese-occupied'=>[
					'vietnamese occupied',
				],
				'view'=>[
					'veiw',
					'view view',
					'view view view',
				],
				'viewable'=>[
					'view-able',
				],
				'viewdata'=>[
					'veiwdata',
					'viwdata',
				],
				'viewer'=>[
					'veiwer',
					'viwer',
				],
				'viewership'=>[
					'veiwership',
					'viwership',
				],
				'viewfinder'=>[
					'veiwfinder',
					'viwfinder',
				],
				'viewing'=>[
					'veiwing',
					'viwing',
				],
				'viewpoint'=>[
					'veiwpoint',
					'viwpoint',
				],
				'views'=>[
					'veiws',
				],
				'viewy'=>[
					'veiwy',
					'viwy',
				],
				'vigilance'=>[
					'vigilence',
				],
				'vigilant'=>[
					'vigilent',
				],
				'vigilante'=>[
					'vigilente',
				],
				'vigor'=>[
					'vigeur',
				],
				'vigorous'=>[
					'vigourous',
				],
				'vilely'=>[
					'villy',
				],
				'vilified'=>[
					'villified',
				],
				'vilify'=>[
					'villify',
				],
				'vill'=>[
					'vil',
				],
				'villa'=>[
					'vila',
				],
				'village'=>[
					'',
					'viallage',
					'vilage',
					'village village',
					'village village village',
				],
				'villager'=>[
					'vilager',
				],
				'villages'=>[
					'vilages',
				],
				'villain'=>[
					'vilain',
					'villian',
					'villin',
				],
				'villainess'=>[
					'villainiss',
				],
				'villainous'=>[
					'vilainous',
					'villianous',
				],
				'villains'=>[
					'villans',
					'villians',
				],
				'villainy'=>[
					'villany',
					'villiany',
				],
				'villein'=>[
					'villien',
				],
				'villi'=>[
					'vili',
				],
				'villus'=>[
					'vilus',
				],
				'vimina'=>[
					'vimini',
				],
				'viminal'=>[
					'viminil',
				],
				'vinaceous'=>[
					'viniceous',
				],
				'vinaigrette'=>[
					'vinegarette',
					'vinegrette',
					'viniigrette',
				],
				'vinaigrettes'=>[
					'viniigrettes',
				],
				'vinal'=>[
					'vinil',
				],
				'vinals'=>[
					'vinils',
				],
				'vinas'=>[
					'vinis',
				],
				'vinasse'=>[
					'vinisse',
				],
				'vinasses'=>[
					'vinisses',
				],
				'vinblastine'=>[
					'vinblastini',
				],
				'vincible'=>[
					'vincable',
				],
				'vincristine'=>[
					'vincristini',
				],
				'vindictively'=>[
					'vindictivly',
				],
				'vined'=>[
					'vinid',
				],
				'vinedresser'=>[
					'vinidresser',
				],
				'vinegar'=>[
					'vineger',
					'vinigar',
				],
				'vinegary'=>[
					'vinegery',
					'vinigary',
				],
				'vinery'=>[
					'viniry',
				],
				'vines'=>[
					'vinis',
				],
				'vineyard'=>[
					'viniyard',
				],
				'vineyardist'=>[
					'viniyardist',
				],
				'vinic'=>[
					'vinac',
				],
				'viniculture'=>[
					'vinaculture',
				],
				'vinier'=>[
					'vinaer',
				],
				'viniest'=>[
					'vinaest',
				],
				'vinifications'=>[
					'vinafications',
				],
				'vinify'=>[
					'vinafy',
				],
				'vining'=>[
					'vinang',
				],
				'violable'=>[
					'violible',
				],
				'violation'=>[
					'voilation',
					'volation',
				],
				'violence'=>[
					'violance',
					'voilence',
				],
				'violent'=>[
					'violant',
					'voilent',
				],
				'violently'=>[
					'violentally',
					'violentaly',
					'violentely',
					'violentlly',
				],
				'violoncello'=>[
					'violoncelo',
				],
				'virescence'=>[
					'virescance',
				],
				'virgin'=>[
					'virgina',
				],
				'virginal'=>[
					'virginil',
				],
				'virginalists'=>[
					'virginilists',
				],
				'virginally'=>[
					'virginilly',
				],
				'virginals'=>[
					'virginils',
				],
				'virginia'=>[
					'virgina',
				],
				'virginity'=>[
					'virginaty',
				],
				'viridian'=>[
					'viridan',
				],
				'virilely'=>[
					'virilly',
				],
				'virtual'=>[
					'virtaul',
					'virtural',
				],
				'virtually'=>[
					'virtaully',
					'virtualally',
					'virtualaly',
					'virtualely',
					'virtuallly',
					'virtualy',
				],
				'virtuosa'=>[
					'virtosa',
				],
				'virtuosas'=>[
					'virtosas',
				],
				'virtuose'=>[
					'virtose',
				],
				'virtuosi'=>[
					'virtosi',
				],
				'virtuosic'=>[
					'virtosic',
				],
				'virtuosities'=>[
					'virtosities',
				],
				'virtuosity'=>[
					'virtosity',
				],
				'virtuoso'=>[
					'virtoso',
				],
				'virtuosos'=>[
					'virtosos',
				],
				'virtuous'=>[
					'virtous',
				],
				'virtuously'=>[
					'virtously',
				],
				'virtuousness'=>[
					'virtousness',
				],
				'virtuousnesses'=>[
					'virtousnesses',
				],
				'virulence'=>[
					'virulance',
				],
				'virulency'=>[
					'virulensy',
				],
				'virulent'=>[
					'virulant',
				],
				'viruses'=>[
					'virii',
				],
				'viscera'=>[
					'vicera',
					'vicsera',
					'visera',
				],
				'visceral'=>[
					'viceral',
					'vicseral',
					'viseral',
				],
				'viscid'=>[
					'vicid',
					'vicsid',
					'visid',
				],
				'viscoelasticity'=>[
					'vicoelasticity',
					'vicsoelasticity',
					'visoelasticity',
				],
				'viscometer'=>[
					'vicometer',
					'vicsometer',
					'visometer',
				],
				'viscose'=>[
					'vicose',
					'vicsose',
					'visose',
				],
				'viscosimeter'=>[
					'vicosimeter',
					'vicsosimeter',
					'visosimeter',
				],
				'viscosity'=>[
					'vicosity',
					'vicsosity',
					'visosity',
				],
				'viscount'=>[
					'vicount',
					'vicsount',
					'visount',
				],
				'viscountcy'=>[
					'viscountsy',
				],
				'viscountess'=>[
					'vicountess',
					'vicsountess',
					'viscountes',
					'visountess',
				],
				'viscous'=>[
					'vicous',
					'vicsous',
					'visous',
				],
				'viscus'=>[
					'vicsus',
					'vicus',
					'visus',
				],
				'visibility'=>[
					'visability',
				],
				'visible'=>[
					'visable',
				],
				'visibly'=>[
					'visably',
				],
				'vision'=>[
					'vison',
				],
				'visionarinesses'=>[
					'visionarinisses',
				],
				'visionary'=>[
					'visionery',
					'visonary',
				],
				'visit'=>[
					'visist',
					'visit visit',
					'visit visit visit',
					'vist',
				],
				'visitable'=>[
					'visitible',
				],
				'visitant'=>[
					'visitent',
				],
				'visitation'=>[
					'vistation',
				],
				'visited'=>[
					'visted',
				],
				'visiting'=>[
					'visting',
				],
				'visitor'=>[
					'vistor',
				],
				'visits'=>[
					'vists',
				],
				'visual'=>[
					'visaul',
				],
				'visualization'=>[
					'vizualization',
				],
				'visualize'=>[
					'visaulize',
					'vizualize',
				],
				'visualizer'=>[
					'visaulizer',
				],
				'visually'=>[
					'visualy',
				],
				'vitellogenesis'=>[
					'vitelogenesis',
				],
				'viticulturally'=>[
					'viticulturalally',
					'viticulturalaly',
					'viticulturalely',
					'viticulturallly',
				],
				'vitrine'=>[
					'vitrini',
				],
				'vittle'=>[
					'vittel',
				],
				'vituperatively'=>[
					'vituperativly',
				],
				'vivacious'=>[
					'vivacous',
				],
				'vivaciously'=>[
					'vivaciousally',
					'vivaciousaly',
					'vivaciousely',
					'vivaciouslly',
					'vivacously',
				],
				'vivandiere'=>[
					'vivandeire',
					'vivandire',
				],
				'vivary'=>[
					'vivery',
				],
				'viverrid'=>[
					'viverid',
				],
				'vividly'=>[
					'vividally',
					'vividaly',
					'vividely',
					'vividlly',
				],
				'viviparous'=>[
					'viviperous',
				],
				'vizier'=>[
					'vizeir',
					'vizir',
				],
				'vladivostok'=>[
					'vladavostok',
					'vladivostock',
					'vladovostock',
					'vladovostok',
				],
				'vocable'=>[
					'vocible',
				],
				'vocabular'=>[
					'vocabuler',
				],
				'vocabulary'=>[
					'vocabulery',
				],
				'vocals'=>[
					'volcals',
				],
				'vocatively'=>[
					'vocativly',
				],
				'voice'=>[
					'vioce',
					'voice voice',
					'voice voice voice',
				],
				'voiceless'=>[
					'voiceles',
				],
				'voicelessly'=>[
					'voicelessally',
					'voicelessaly',
					'voicelessely',
					'voicelesslly',
				],
				'voidable'=>[
					'voidible',
				],
				'voidance'=>[
					'voidence',
				],
				'voilà'=>[
					'walla',
					'wallah',
				],
				'volant'=>[
					'volent',
				],
				'volar'=>[
					'voler',
				],
				'volcanic'=>[
					'vulcanic',
				],
				'volcano'=>[
					'volcanoe',
				],
				'volcanoes'=>[
					'volcanos',
				],
				'volkswagen'=>[
					'volkswagon',
				],
				'volley'=>[
					'voley',
				],
				'volleyball'=>[
					'volleybal',
				],
				'voluntarinesses'=>[
					'voluntarinisses',
				],
				'voluntary'=>[
					'volontary',
					'voluntery',
				],
				'volunteer'=>[
					'volonteer',
					'volounteer',
				],
				'volunteered'=>[
					'volonteered',
					'volounteered',
				],
				'volunteering'=>[
					'volonteering',
					'volounteering',
				],
				'volunteers'=>[
					'volimteers',
					'voltmteers',
				],
				'voluptuary'=>[
					'voluptaury',
					'voluptuery',
				],
				'voluptuous'=>[
					'voluptous',
				],
				'voluptuously'=>[
					'voluptously',
				],
				'voluptuousness'=>[
					'voluptousness',
				],
				'voracious'=>[
					'voracous',
				],
				'voraciously'=>[
					'voraciousally',
					'voraciousaly',
					'voraciousely',
					'voraciouslly',
					'voracously',
				],
				'votable'=>[
					'votible',
				],
				'votary'=>[
					'votery',
				],
				'votively'=>[
					'votivly',
				],
				'vowel'=>[
					'vowel vowel',
					'vowel vowel vowel',
				],
				'voyageur'=>[
					'voyager',
				],
				'voyageurs'=>[
					'voyaguers',
				],
				'voyeur'=>[
					'voyer',
				],
				'vugg'=>[
					'vug',
				],
				'vuggier'=>[
					'vugier',
				],
				'vuggs'=>[
					'vugs',
				],
				'vuggy'=>[
					'vugy',
				],
				'vulcanian'=>[
					'vulcanan',
				],
				'vulgar'=>[
					'vulger',
				],
				'vulgarian'=>[
					'vulgaran',
				],
				'vulnerable'=>[
					'vulnerible',
				],
				'vulnerably'=>[
					'vulnerabally',
					'vulnerabaly',
					'vulnerabely',
					'vulnerablly',
				],
				'vulnerary'=>[
					'vulnerery',
				],
				'vulvovaginitis'=>[
					'vulvovaginatis',
				],
				'véronique'=>[
					'veronique',
				],
			];
		}
	}

?>