<?php
		
		/* UTF-8 TEST
		
			中文汉字漢字
		
		*/
				
				/* EnglishMisspellingsWords_J
					
					Class for English-Misspellings for all words beginning with : J.
					
				*/

	class EnglishMisspellingsWords_J {
			/* __construct($args)
			
				Constructor.
				
				Nothing to do here.
			
			*/
			
		public function __construct($args) {
			return TRUE;
		}
		
			/* EnglishMisspellingsWords()
			
				List of English misspellings for words starting with : J.
			
			*/

		public function EnglishMisspellingsWords() {
			return [
				'Jacobinism'=>[
					'Jaoobinism',
				],
				'jabbed'=>[
					'jabed',
				],
				'jabber'=>[
					'jaber',
				],
				'jabbered'=>[
					'jabered',
				],
				'jabberers'=>[
					'jaberers',
				],
				'jabbering'=>[
					'jabering',
				],
				'jabbers'=>[
					'jabers',
				],
				'jabberwockies'=>[
					'jaberwockies',
				],
				'jabberwocky'=>[
					'jaberwocky',
				],
				'jabbing'=>[
					'jabing',
				],
				'jacamar'=>[
					'jacamer',
				],
				'jackass'=>[
					'jackas',
				],
				'jackhammer'=>[
					'jackhamner',
				],
				'jackhammered'=>[
					'jackhamnered',
				],
				'jackhammering'=>[
					'jackhamnering',
				],
				'jackhammers'=>[
					'jackhamners',
				],
				'jackrabbit'=>[
					'jackrabit',
				],
				'jackrabbits'=>[
					'jackrabits',
				],
				'jacquard'=>[
					'jacqaurd',
				],
				'jadeite'=>[
					'jadiete',
				],
				'jadeites'=>[
					'jadietes',
				],
				'jagg'=>[
					'jag',
				],
				'jaggaries'=>[
					'jagaries',
				],
				'jaggary'=>[
					'jaggery',
				],
				'jagged'=>[
					'jaged',
				],
				'jaggedest'=>[
					'jagedest',
				],
				'jaggednesses'=>[
					'jagednesses',
				],
				'jaggeries'=>[
					'jageries',
				],
				'jaggery'=>[
					'jagery',
				],
				'jaggs'=>[
					'jags',
				],
				'jaggy'=>[
					'jagy',
				],
				'jaguar'=>[
					'jagaur',
					'jaguer',
				],
				'jaguarundi'=>[
					'jagaurundi',
				],
				'jalousie'=>[
					'jalouise',
				],
				'jalousied'=>[
					'jalouised',
				],
				'jalousies'=>[
					'jalouises',
				],
				'jamaica'=>[
					'jamacia',
				],
				'jamaican-occupied'=>[
					'jamaican occupied',
				],
				'jammable'=>[
					'jamnable',
				],
				'jammed'=>[
					'jamned',
				],
				'jammer'=>[
					'jamner',
				],
				'jammies'=>[
					'jamnies',
				],
				'jammiest'=>[
					'jamniest',
				],
				'jammy'=>[
					'jamny',
				],
				'janisary'=>[
					'janisery',
				],
				'janissary'=>[
					'janissery',
				],
				'janizary'=>[
					'janizery',
				],
				'janty'=>[
					'jenty',
				],
				'january'=>[
					'jamuary',
					'janaury',
					'janurary',
					'janury',
					'janusry',
					'jauary',
					'jaunary',
				],
				'japanese'=>[
					'japaneese',
					'japanes',
				],
				'japanese-occupied'=>[
					'japanese occupied',
					'japaneseoccupied',
				],
				'japanners'=>[
					'japaners',
				],
				'japanning'=>[
					'japaning',
				],
				'jardiniere'=>[
					'jardineire',
					'jardinaere',
					'jardinire',
				],
				'jardinieres'=>[
					'jardinaeres',
				],
				'jarina'=>[
					'jarini',
				],
				'jarinas'=>[
					'jarinis',
				],
				'jarrah'=>[
					'jarah',
					'jarra',
				],
				'jarrahs'=>[
					'jarras',
				],
				'jasmine'=>[
					'jasmini',
				],
				'javelina'=>[
					'javelini',
				],
				'jawline'=>[
					'jawlini',
				],
				'jazz-influenced mambo'=>[
					'jazz influenced mambo',
				],
				'jealous'=>[
					'jelous',
				],
				'jealousies'=>[
					'jealouises',
				],
				'jealousy'=>[
					'jealoucy',
					'jelousy',
				],
				'jean'=>[
					'jen',
				],
				'jean de nostredame'=>[
					'jean de nostre dame',
				],
				'jean-claude'=>[
					'jean claude',
				],
				'jean-marie'=>[
					'jean marie',
				],
				'jean-michel'=>[
					'jean michel',
				],
				'jefferson'=>[
					'jeiferson',
				],
				'jejunely'=>[
					'jejunly',
				],
				'jell'=>[
					'jel',
				],
				'jellied'=>[
					'jelleid',
					'jellid',
				],
				'jello'=>[
					'jelo',
				],
				'jelly'=>[
					'jelally',
					'jelaly',
					'jellly',
					'jely',
				],
				'jellyfish'=>[
					'jelyfish',
				],
				'jemmy'=>[
					'jemny',
				],
				'jemmying'=>[
					'jemnying',
				],
				'jennet'=>[
					'jenet',
				],
				'jenny'=>[
					'jeny',
				],
				'jeopard'=>[
					'jeoperd',
				],
				'jeoparded'=>[
					'jeoperded',
				],
				'jeopardised'=>[
					'jeoperdised',
				],
				'jeopardises'=>[
					'jeoperdises',
				],
				'jeopardising'=>[
					'jeoperdising',
				],
				'jeopardize'=>[
					'jeoperdize',
				],
				'jeopardized'=>[
					'jeoperdized',
				],
				'jeopardizes'=>[
					'jeoperdizes',
				],
				'jeopardizing'=>[
					'jeoperdizing',
				],
				'jeopards'=>[
					'jeoperds',
				],
				'jeopardy'=>[
					'jeapardy',
					'jeoperdy',
				],
				'jerrican'=>[
					'jerican',
				],
				'jerry'=>[
					'jery',
				],
				'jerrycan'=>[
					'jerycan',
				],
				'jerusalem'=>[
					'jersualem',
				],
				'jess'=>[
					'jes',
				],
				'jesse'=>[
					'jese',
				],
				'jesús alemañy'=>[
					'jesus alemany',
				],
				'jetliner'=>[
					'jetlinir',
				],
				'jeweler'=>[
					'jewler',
				],
				'jewellery'=>[
					'jewlery',
					'jewlrey',
					'jewelery',
				],
				'jharkhand'=>[
					'jharkand',
				],
				'jibb'=>[
					'jib',
				],
				'jibbed'=>[
					'jibed',
				],
				'jibber'=>[
					'jiber',
				],
				'jibbers'=>[
					'jibers',
				],
				'jibbing'=>[
					'jibing',
				],
				'jibboom'=>[
					'jiboom',
				],
				'jibbs'=>[
					'jibs',
				],
				'jigger'=>[
					'jiger',
				],
				'jiggered'=>[
					'jigered',
				],
				'jiggering'=>[
					'jigering',
				],
				'jiggle'=>[
					'jigle',
				],
				'jiggliest'=>[
					'jigliest',
				],
				'jiggy'=>[
					'jigy',
				],
				'jill'=>[
					'jil',
				],
				'jim white-inspired film'=>[
					'jim white inspired film',
				],
				'jimi hendrix'=>[
					'jimmy hendrix',
				],
				'jimmie'=>[
					'jimnie',
				],
				'jimmies'=>[
					'jimnies',
				],
				'jimmy'=>[
					'jimny',
				],
				'jimmy buffett'=>[
					'jimmy buffet',
				],
				'jimmying'=>[
					'jimnying',
				],
				'jinn'=>[
					'jin',
				],
				'jinni'=>[
					'jini',
				],
				'jinns'=>[
					'jins',
				],
				'jitterbugged'=>[
					'jitterbuged',
				],
				'jitterbugging'=>[
					'jitterbuging',
				],
				'jittery'=>[
					'jittary',
				],
				'joan miró'=>[
					'joan miro',
				],
				'job'=>[
					'job job',
					'job job job',
				],
				'job hunting'=>[
					'jobhunting',
				],
				'jobbed'=>[
					'jobed',
				],
				'jobber'=>[
					'jober',
				],
				'jobberies'=>[
					'joberies',
				],
				'jobbers'=>[
					'jobers',
				],
				'jobbery'=>[
					'jobery',
				],
				'jobbing'=>[
					'jobing',
				],
				'jobless'=>[
					'jobles',
				],
				'jocosely'=>[
					'jocosly',
				],
				'jocular'=>[
					'joculer',
				],
				'joggle'=>[
					'jogle',
				],
				'johann heinrich füssli'=>[
					'johann henrich füssli',
				],
				'johannine'=>[
					'johanine',
				],
				'john j. barceló'=>[
					'john j. barcelo',
				],
				'johnny'=>[
					'johny',
				],
				'johnnycake'=>[
					'johnycake',
				],
				'johnnycakes'=>[
					'johnycakes',
				],
				'johnston press'=>[
					'johnson press',
				],
				'join'=>[
					'join join',
					'join join join',
				],
				'joinable'=>[
					'joinible',
				],
				'joined'=>[
					'joinde',
					'joinid',
				],
				'joiner'=>[
					'joinir',
				],
				'joinery'=>[
					'joiniry',
				],
				'joining'=>[
					'joinang',
				],
				'jointly'=>[
					'jointally',
					'jointaly',
					'jointely',
					'jointlly',
				],
				'jollification'=>[
					'jolification',
				],
				'jolly'=>[
					'jolally',
					'jolaly',
					'jollly',
					'joly',
				],
				'jongleur'=>[
					'jongler',
				],
				'jonnycake'=>[
					'jonycake',
				],
				'jordanian'=>[
					'jordianian',
					'jordnian',
				],
				'jordanian-occupied'=>[
					'jordanian occupied',
				],
				'jorge cáceres'=>[
					'jorge caceres',
				],
				'jorrín'=>[
					'jorin',
				],
				'joseph'=>[
					'jospeh',
				],
				'joss'=>[
					'jos',
				],
				'josé'=>[
					'jose',
				],
				'josé marco'=>[
					'jose marco',
				],
				'joual'=>[
					'joaul',
				],
				'jouals'=>[
					'joauls',
				],
				'jouncy'=>[
					'jounsy',
				],
				'journal'=>[
					'jorunal',
					'jounal',
					'journey=jorney',
					'journeys=jorneys',
				],
				'journalism'=>[
					'jornalism',
				],
				'journalist'=>[
					'jornalist',
				],
				'journey'=>[
					'journy',
				],
				'journeys'=>[
					'journies',
				],
				'jowar'=>[
					'jower',
				],
				'jowly'=>[
					'jowally',
					'jowaly',
					'jowlly',
				],
				'joy'=>[
					'joy joy',
					'joy joy joy',
				],
				'joyance'=>[
					'joyence',
				],
				'joyas inéditas'=>[
					'joyas ineditas',
				],
				'joyless'=>[
					'joyles',
				],
				'jubbah'=>[
					'jubah',
					'jubba',
				],
				'jubbahs'=>[
					'jubahs',
					'jubbas',
				],
				'jubhah'=>[
					'jubha',
				],
				'jubhahs'=>[
					'jubhas',
				],
				'jubilance'=>[
					'jubilence',
				],
				'jubilant'=>[
					'jubilent',
				],
				'jubilarian'=>[
					'jubilaran',
				],
				'judaism'=>[
					'juadaism',
					'juadism',
				],
				'judgement'=>[
					'judgemant',
				],
				'judgment'=>[
					'judgement',
					'judgmant',
				],
				'judicable'=>[
					'judicible',
				],
				'judicial'=>[
					'judical',
				],
				'judiciary'=>[
					'judisuary',
					'judiciery',
				],
				'judicious'=>[
					'judicous',
				],
				'judiciously'=>[
					'judiciousally',
					'judiciousaly',
					'judiciousely',
					'judiciouslly',
					'judicously',
				],
				'juggernaut'=>[
					'jugernaut',
				],
				'juggernauts'=>[
					'jugernauts',
				],
				'juggle'=>[
					'jugle',
				],
				'juggler'=>[
					'jugler',
				],
				'jugglery'=>[
					'juglery',
				],
				'jugglings'=>[
					'juglings',
				],
				'jugular'=>[
					'juguler',
				],
				'juicy'=>[
					'juisy',
				],
				'julienne'=>[
					'juleinne',
					'juliene',
					'julinne',
				],
				'julienned'=>[
					'juliened',
				],
				'juliennes'=>[
					'julienes',
				],
				'jump'=>[
					'jump jump',
					'jump jump jump',
				],
				'jumpable'=>[
					'jumpible',
				],
				'junction'=>[
					'juction',
					'juntion',
				],
				'june'=>[
					'jime',
					'qune',
				],
				'junior'=>[
					'juniour',
					'junoir',
				],
				'junkie'=>[
					'junkei',
					'junki',
				],
				'jurant'=>[
					'jurent',
				],
				'jurisconsult'=>[
					'juriconsult',
					'juricsonsult',
					'jurisonsult',
				],
				'jurisdiction'=>[
					'jurisdication',
					'jursidiction',
				],
				'jurisprudence'=>[
					'jurisprudance',
				],
				'jurisprudent'=>[
					'jurisprudant',
				],
				'jurisprudential'=>[
					'jurisprudantial',
				],
				'jurisprudents'=>[
					'jurisprudants',
				],
				'just'=>[
					'jstu',
					'jsut',
					'just just',
					'just just just',
				],
				'justiciable'=>[
					'justiciible',
				],
				'justiciar'=>[
					'justicar',
					'justicier',
				],
				'justifiable'=>[
					'justifiible',
				],
				'justly'=>[
					'justally',
					'justaly',
					'justely',
					'justlly',
				],
				'juvenescence'=>[
					'juvenescance',
				],
				'juvenile'=>[
					'juvinile',
				],
				'jérémie'=>[
					'jeremie',
				],
			];
		}
	}

?>