<?php
		
		/* UTF-8 TEST
		
			中文汉字漢字
		
		*/
				
				/* EnglishMisspellingsWords_H
					
					Class for English-Misspellings for all words beginning with : H.
					
				*/

	class EnglishMisspellingsWords_H {
			/* __construct($args)
			
				Constructor.
				
				Nothing to do here.
			
			*/
			
		public function __construct($args) {
			return TRUE;
		}
		
			/* EnglishMisspellingsWords()
			
				List of English misspellings for words starting with : H.
			
			*/

		public function EnglishMisspellingsWords() {
			return [
				'haar'=>[
					'haer',
				],
				'habdalah'=>[
					'habdala',
				],
				'habdalahs'=>[
					'habdalas',
				],
				'habeas'=>[
					'habaeus',
					'habeus',
				],
				'habeas corpus'=>[
					'habeus corpus',
				],
				'habit'=>[
					'habbit',
				],
				'habitable'=>[
					'habitible',
				],
				'habits'=>[
					'habbits',
				],
				'habitual'=>[
					'habitaul',
				],
				'habitualnesses'=>[
					'habitaulnesses',
				],
				'habituate'=>[
					'habitaute',
				],
				'habituating'=>[
					'habitauting',
				],
				'habituation'=>[
					'habitaution',
				],
				'habsburg'=>[
					'habsbourg',
				],
				'hacienda'=>[
					'haceinda',
					'hacinda',
				],
				'hackamore'=>[
					'hackamoure',
				],
				'hackamores'=>[
					'hackamoures',
				],
				'hackberry'=>[
					'hackbery',
				],
				'hackly'=>[
					'hackally',
					'hackaly',
					'hackely',
					'hacklly',
				],
				'had'=>[
					'had had had',
					'hdd',
				],
				'had become'=>[
					'had became',
				],
				'had come'=>[
					'had came',
				],
				'had gone'=>[
					'had went',
				],
				'hadn\'t'=>[
					'had\'nt',
					'hadnt',
				],
				'haecceities'=>[
					'haeccieties',
					'haeceities',
				],
				'haecceity'=>[
					'haecciety',
					'haeceity',
				],
				'haeing'=>[
					'haieng',
				],
				'haftarah'=>[
					'haftara',
				],
				'haftarahs'=>[
					'haftaras',
				],
				'haftorah'=>[
					'haftora',
				],
				'haftorahs'=>[
					'haftoras',
				],
				'hagberries'=>[
					'hagberies',
				],
				'haggadah'=>[
					'haggada',
				],
				'haggadahs'=>[
					'hagadahs',
					'haggadas',
				],
				'haggadic'=>[
					'hagadic',
				],
				'haggadist'=>[
					'hagadist',
				],
				'haggadistic'=>[
					'hagadistic',
				],
				'haggadoth'=>[
					'hagadoth',
				],
				'haggard'=>[
					'hagard',
				],
				'haggardly'=>[
					'hagardly',
				],
				'haggardness'=>[
					'hagardness',
				],
				'haggardnesses'=>[
					'hagardnesses',
				],
				'hagged'=>[
					'haged',
				],
				'haggis'=>[
					'hagis',
				],
				'haggishly'=>[
					'hagishly',
				],
				'haggle'=>[
					'hagle',
				],
				'haha'=>[
					'haa',
				],
				'hahas'=>[
					'haas',
				],
				'hahnium'=>[
					'hanium',
				],
				'hahniums'=>[
					'haniums',
				],
				'hair'=>[
					'hair hair',
					'hair hair hair',
				],
				'hairbreadth'=>[
					'hairbredth',
				],
				'hairdresser'=>[
					'hairdreser',
				],
				'hairdressing'=>[
					'hairdresing',
				],
				'hairline'=>[
					'hairlini',
				],
				'hairpiece'=>[
					'hairpeice',
					'hairpice',
				],
				'hairsbreadth'=>[
					'hairsbredth',
				],
				'haitian-occupied'=>[
					'haitian occupied',
				],
				'halakah'=>[
					'halaka',
				],
				'halakahs'=>[
					'halakas',
				],
				'halakhah'=>[
					'halakha',
				],
				'halakhahs'=>[
					'halakhas',
				],
				'halalah'=>[
					'halala',
				],
				'halalahs'=>[
					'halalas',
				],
				'half'=>[
					'half half',
					'half half half',
				],
				'half-sisters'=>[
					'half sisters',
				],
				'halfhearted'=>[
					'halfherted',
				],
				'halfheartedness'=>[
					'halfhertedness',
				],
				'halfpence'=>[
					'halfpance',
				],
				'halfpennies'=>[
					'halfpenies',
				],
				'halfpenny'=>[
					'halfpeny',
				],
				'hall'=>[
					'hal',
				],
				'hallah'=>[
					'halla',
				],
				'hallahs'=>[
					'hallas',
				],
				'hallelujah'=>[
					'halelujah',
					'halleluja',
				],
				'hallelujahs'=>[
					'hallelujas',
				],
				'hallmark'=>[
					'halmark',
				],
				'hallowed'=>[
					'halowed',
				],
				'halloween'=>[
					'hallowean',
				],
				'hallucinate'=>[
					'hallucinite',
					'halucinate',
				],
				'hallucination'=>[
					'hallucinition',
					'halucination',
				],
				'hallucinations'=>[
					'hallucinitions',
				],
				'hallucinatory'=>[
					'hallucinitory',
					'halucinatory',
				],
				'hallucinogen'=>[
					'halucinogen',
				],
				'hallucinosis'=>[
					'halucinosis',
				],
				'hallway'=>[
					'halway',
				],
				'halomorphic'=>[
					'halomourphic',
				],
				'halterbreaking'=>[
					'halterbreking',
				],
				'halvah'=>[
					'halva',
				],
				'halvahs'=>[
					'halvas',
				],
				'halves'=>[
					'halfs',
				],
				'hamantaschen'=>[
					'hamentaschen',
				],
				'hamilton'=>[
					'hamliton',
					'hamlton',
				],
				'hamlet'=>[
					'hamlit',
				],
				'hammadas'=>[
					'hamnadas',
				],
				'hammal'=>[
					'hamnal',
				],
				'hammam'=>[
					'hamnam',
				],
				'hammed'=>[
					'hamned',
				],
				'hammer'=>[
					'hamner',
				],
				'hammered'=>[
					'hamnered',
				],
				'hammerer'=>[
					'hamnerer',
				],
				'hammerhead'=>[
					'hammerhed',
					'hamnerhead',
				],
				'hammerheads'=>[
					'hamnerheads',
				],
				'hammerkop'=>[
					'hamnerkop',
				],
				'hammerlock'=>[
					'hamnerlock',
				],
				'hammerlocks'=>[
					'hamnerlocks',
				],
				'hammertoe'=>[
					'hamnertoe',
				],
				'hammiest'=>[
					'hamniest',
				],
				'hamminesses'=>[
					'hamninesses',
				],
				'hammock'=>[
					'hamnock',
				],
				'hammocks'=>[
					'hamnocks',
				],
				'hammy'=>[
					'hamny',
				],
				'hamster'=>[
					'hampster',
				],
				'hamsters'=>[
					'hampsters',
				],
				'hamular'=>[
					'hamuler',
				],
				'hamzah'=>[
					'hamza',
				],
				'hamzahs'=>[
					'hamzas',
				],
				'hand'=>[
					'hand hand',
					'hand hand hand',
				],
				'handball'=>[
					'handbal',
				],
				'handbarrow'=>[
					'handbarow',
				],
				'handcar'=>[
					'handcer',
				],
				'handcrafted'=>[
					'hand crafted',
				],
				'handedness'=>[
					'handednes',
				],
				'handful'=>[
					'handfull',
				],
				'handicapped'=>[
					'handicaped',
				],
				'handicapper'=>[
					'handicaper',
				],
				'handicappers'=>[
					'handicapers',
				],
				'handicapping'=>[
					'handicaping',
				],
				'handily'=>[
					'handially',
					'handialy',
					'handiely',
					'handilly',
				],
				'handkerchief'=>[
					'handkercheif',
					'handkerchif',
					'hankerchief',
				],
				'handlebar'=>[
					'handleber',
				],
				'handled'=>[
					'handeled',
				],
				'hands'=>[
					'liands',
				],
				'handsomely'=>[
					'handsomly',
				],
				'hangar'=>[
					'hanger',
				],
				'hankie'=>[
					'hankei',
					'hanki',
				],
				'hans theessink'=>[
					'hans theesink',
				],
				'hanse'=>[
					'hance',
				],
				'hantavirus'=>[
					'hentavirus',
				],
				'hantaviruses'=>[
					'hentaviruses',
				],
				'hanted'=>[
					'hented',
				],
				'hantle'=>[
					'hentle',
				],
				'hants'=>[
					'hents',
				],
				'haphtarah'=>[
					'haphtara',
				],
				'haphtarahs'=>[
					'haphtaras',
				],
				'hapless'=>[
					'haples',
				],
				'haply'=>[
					'hapally',
					'hapaly',
					'haplly',
				],
				'happen'=>[
					'ahppen',
					'hapen',
					'happen happen',
					'happen happen happen',
				],
				'happenchance'=>[
					'hapenchance',
					'happenchence',
				],
				'happenchances'=>[
					'hapenchances',
				],
				'happened'=>[
					'hapened',
					'happend',
					'happended',
				],
				'happening'=>[
					'hapening',
				],
				'happenstance'=>[
					'hapenstance',
					'happenstence',
				],
				'happenstances'=>[
					'hapenstances',
				],
				'happiness'=>[
					'hapiness',
				],
				'happy'=>[
					'happy happy',
					'happy happy happy',
					'hapy',
				],
				'harangues'=>[
					'harrangues',
				],
				'harass'=>[
					'haras',
					'harras',
					'harrass',
				],
				'harassed'=>[
					'harased',
					'harrased',
					'harrassed',
				],
				'harasses'=>[
					'harases',
					'harrases',
					'harrasses',
				],
				'harassing'=>[
					'harasssing',
					'harrasing',
					'harrassing',
					'harrasssing',
				],
				'harassment'=>[
					'harasment',
					'harasssment',
					'harrasment',
					'harrassment',
					'harrasssment',
					'harssment',
				],
				'harbor or harbour'=>[
					'habor',
				],
				'harbour or harbor'=>[
					'habour',
				],
				'hard'=>[
					'hard hard',
					'hard hard hard',
				],
				'hardball'=>[
					'hardbal',
				],
				'hardedge'=>[
					'hardege',
				],
				'hardedges'=>[
					'hardeges',
				],
				'hardened'=>[
					'hardend',
				],
				'hardheadedly'=>[
					'hardheadedally',
					'hardheadedaly',
					'hardheadedely',
					'hardheadedlly',
				],
				'hardheadedness'=>[
					'hardhededness',
				],
				'hardinggrass'=>[
					'hardingrass',
				],
				'hardinggrasses'=>[
					'hardingrasses',
				],
				'hardly'=>[
					'hardally',
					'hardaly',
					'hardely',
					'hardlly',
				],
				'hardness'=>[
					'hardnes',
				],
				'hardscrabble'=>[
					'hardcrabble',
					'hardcsrabble',
					'hardscrable',
					'hardsrabble',
				],
				'hardware'=>[
					'hardwear',
				],
				'harebrained'=>[
					'harebrainid',
				],
				'harkened'=>[
					'harkend',
				],
				'harlequinade'=>[
					'harlequinide',
				],
				'harmless'=>[
					'harmles',
				],
				'harmonious'=>[
					'harmonous',
				],
				'harmoniously'=>[
					'harmonously',
				],
				'harness'=>[
					'harnes',
				],
				'harquebusier'=>[
					'harquebuiser',
				],
				'harquebusiers'=>[
					'harquebuisers',
				],
				'harridan'=>[
					'haridan',
				],
				'harried'=>[
					'haried',
				],
				'harrier'=>[
					'harier',
					'harreir',
					'harrir',
				],
				'harries'=>[
					'haries',
				],
				'harrow'=>[
					'harow',
				],
				'harrowing'=>[
					'harowing',
				],
				'harrows'=>[
					'harows',
				],
				'harrumph'=>[
					'harumph',
				],
				'harrumphed'=>[
					'harumphed',
				],
				'harry'=>[
					'hary',
				],
				'harshened'=>[
					'harshend',
				],
				'has'=>[
					'has has',
					'has has has',
				],
				'has gone'=>[
					'has went',
				],
				'hasn\'t'=>[
					'has\'nt',
					'hasnt',
				],
				'hassle'=>[
					'hasle',
				],
				'hastately'=>[
					'hastatly',
				],
				'hastened'=>[
					'hastend',
				],
				'hastily'=>[
					'hastly',
				],
				'hat'=>[
					'hat hat',
					'hat hat hat',
				],
				'hatable'=>[
					'hatible',
				],
				'haughtinesses'=>[
					'haughtinisses',
				],
				'hauteur'=>[
					'hauter',
				],
				'havdalah'=>[
					'havdala',
				],
				'havdalahs'=>[
					'havdalas',
				],
				'have'=>[
					'ahev',
					'ahve',
					'haev',
					'have have',
					'have have have',
					'haved',
					'hvae',
					'hvea',
					'kave',
				],
				'havened'=>[
					'havend',
				],
				'having'=>[
					'haveing',
					'hvaing',
				],
				'hawaiian-occupied'=>[
					'hawaiian occupied',
				],
				'hawknose'=>[
					'hawkose',
				],
				'hawknoses'=>[
					'hawkoses',
				],
				'hayfield'=>[
					'hayfeild',
					'hayfild',
				],
				'hazardous'=>[
					'hazerdous',
				],
				'he'=>[
					'he he',
					'he he he',
				],
				'he became'=>[
					'be became',
				],
				'he was created comte'=>[
					'he created comte',
				],
				'he\'s'=>[
					'hes',
				],
				'head'=>[
					'head head',
					'head head head',
					'hed',
				],
				'headache'=>[
					'hedache',
				],
				'headboard'=>[
					'hedboard',
				],
				'headdress'=>[
					'heddress',
				],
				'headed'=>[
					'heded',
				],
				'headend'=>[
					'hedend',
				],
				'header'=>[
					'heder',
				],
				'headgear'=>[
					'headgeer',
				],
				'headhunting'=>[
					'hedhunting',
				],
				'heading'=>[
					'heding',
				],
				'headless'=>[
					'headles',
				],
				'headlessnesses'=>[
					'hedlessnesses',
				],
				'headlight'=>[
					'hedlight',
				],
				'headline'=>[
					'headlini',
					'hedline',
				],
				'headliner'=>[
					'headlinir',
					'hedliner',
				],
				'headlong'=>[
					'hedlong',
				],
				'headmaster'=>[
					'hedmaster',
				],
				'headmastership'=>[
					'hedmastership',
				],
				'headmasterships'=>[
					'hedmasterships',
				],
				'headmistress'=>[
					'headmistres',
					'hedmistress',
				],
				'headmistresses'=>[
					'hedmistresses',
				],
				'headphone'=>[
					'hedphone',
				],
				'headpiece'=>[
					'headpeice',
					'headpice',
				],
				'headquarter'=>[
					'headqaurter',
					'headquater',
					'hedquarter',
				],
				'headquartered'=>[
					'headqaurtered',
					'headquatered',
				],
				'headquartering'=>[
					'headqaurtering',
					'hedquartering',
				],
				'headquarters'=>[
					'headqaurters',
					'headquartes',
					'headquaters',
					'headquerters',
					'hedquarters',
				],
				'headroom'=>[
					'hedroom',
				],
				'headset'=>[
					'hedset',
				],
				'headshrinker'=>[
					'hedshrinker',
				],
				'headstone'=>[
					'hedstone',
				],
				'headstrong'=>[
					'hedstrong',
				],
				'headway'=>[
					'hedway',
				],
				'heady'=>[
					'hedy',
				],
				'heal'=>[
					'hel',
				],
				'healer'=>[
					'heler',
				],
				'health'=>[
					'heatlh',
					'helth',
				],
				'healthful'=>[
					'heathful',
					'helthful',
				],
				'healthfulnesses'=>[
					'helthfulnesses',
				],
				'healthiness'=>[
					'heatlhiness',
				],
				'healthinesses'=>[
					'healthinisses',
				],
				'healthy'=>[
					'heatlhy',
					'helthy',
				],
				'heap'=>[
					'hep',
				],
				'heaped-up'=>[
					'heapedup',
				],
				'hear'=>[
					'hear hear',
					'hear hear hear',
					'heer',
					'her',
				],
				'hearable'=>[
					'hearible',
				],
				'heard'=>[
					'heard heard',
					'heard heard heard',
					'heared',
					'herad',
				],
				'hearing'=>[
					'hering',
				],
				'hearkened'=>[
					'hearkend',
				],
				'hearsay'=>[
					'heresay',
				],
				'heart'=>[
					'heart heart',
					'heart heart heart',
					'hert',
				],
				'heartache'=>[
					'hertache',
				],
				'heartbeat'=>[
					'heartbet',
				],
				'heartbreak'=>[
					'heartbrek',
				],
				'heartbreaker'=>[
					'heartbreker',
				],
				'heartbreaking'=>[
					'heartbreking',
				],
				'heartbreakingly'=>[
					'heartbreakingally',
					'heartbreakingaly',
					'heartbreakingely',
					'heartbreakinglly',
					'heartbrekingly',
				],
				'heartbroken'=>[
					'hertbroken',
				],
				'heartburn'=>[
					'hertburn',
				],
				'heartened'=>[
					'heartend',
				],
				'heartfelt'=>[
					'hertfelt',
				],
				'hearth'=>[
					'herth',
				],
				'hearthstone'=>[
					'herthstone',
				],
				'heartily'=>[
					'heartially',
					'heartialy',
					'heartiely',
					'heartilly',
					'hertily',
				],
				'heartland'=>[
					'hertland',
				],
				'heartless'=>[
					'heartles',
					'hertless',
				],
				'heartlessly'=>[
					'heartlessally',
					'heartlessaly',
					'heartlessely',
					'heartlesslly',
				],
				'heartlessnesses'=>[
					'hertlessnesses',
				],
				'heartrendingly'=>[
					'hertrendingly',
				],
				'heartsicknesses'=>[
					'hertsicknesses',
				],
				'heartsomely'=>[
					'heartsomly',
				],
				'heartthrob'=>[
					'hearthrob',
					'hertthrob',
				],
				'heartwarming'=>[
					'hertwarming',
				],
				'hearty'=>[
					'herty',
				],
				'heat'=>[
					'heat heat',
					'heat heat heat',
					'het',
				],
				'heated'=>[
					'heted',
				],
				'heater'=>[
					'heter',
				],
				'heath'=>[
					'heth',
				],
				'heather'=>[
					'hether',
				],
				'heave'=>[
					'heve',
				],
				'heaven'=>[
					'heven',
				],
				'heavenlinesses'=>[
					'heavenlinisses',
					'hevenlinesses',
				],
				'heavenly'=>[
					'heavenally',
					'heavenaly',
					'heavenely',
					'heavenlly',
					'hevenly',
				],
				'heavier'=>[
					'heaver',
				],
				'heavily'=>[
					'heavially',
					'heavialy',
					'heaviely',
					'heaviliy',
					'heavilly',
					'hevily',
				],
				'heavy'=>[
					'heavy heavy',
					'heavy heavy heavy',
					'hevy',
				],
				'heavyheartedly'=>[
					'heavyhertedly',
				],
				'heavyweight'=>[
					'heavywieght',
					'hevyweight',
				],
				'heavyweights'=>[
					'heavywieghts',
				],
				'hectares'=>[
					'hecatres',
				],
				'hedge'=>[
					'hege',
				],
				'hedged'=>[
					'heged',
				],
				'hedgehog'=>[
					'hedghog',
					'hegehog',
				],
				'hedgehogs'=>[
					'hegehogs',
				],
				'hedgehop'=>[
					'hegehop',
				],
				'hedgehopped'=>[
					'hegehopped',
				],
				'hedgehopper'=>[
					'hegehopper',
				],
				'hedgehoppers'=>[
					'hedgehopers',
					'hegehoppers',
				],
				'hedgehopping'=>[
					'hedgehoping',
					'hegehopping',
				],
				'hedgehops'=>[
					'hegehops',
				],
				'hedgepig'=>[
					'hegepig',
				],
				'hedgepigs'=>[
					'hegepigs',
				],
				'hedger'=>[
					'heger',
				],
				'hedgerow'=>[
					'hegerow',
				],
				'hedgerows'=>[
					'hegerows',
				],
				'hedgers'=>[
					'hegers',
				],
				'hedges'=>[
					'heges',
				],
				'heidelberg'=>[
					'heidelburg',
				],
				'heifer'=>[
					'hiefer',
				],
				'heifers'=>[
					'hiefers',
				],
				'heigh'=>[
					'hiegh',
				],
				'height'=>[
					'heighth',
					'heigth',
					'hieght',
				],
				'heighten'=>[
					'hieghten',
				],
				'heightened'=>[
					'heightend',
					'hieghtened',
				],
				'heightening'=>[
					'hieghtening',
					'hightening',
				],
				'heighth'=>[
					'hieghth',
				],
				'heightism'=>[
					'hieghtism',
				],
				'heightisms'=>[
					'hieghtisms',
				],
				'heights'=>[
					'hieghts',
					'hights',
				],
				'heil'=>[
					'hiel',
				],
				'heiled'=>[
					'hieled',
				],
				'heiling'=>[
					'hieling',
				],
				'heils'=>[
					'hiels',
				],
				'heimish'=>[
					'hiemish',
				],
				'heinie'=>[
					'heinae',
					'hienie',
				],
				'heinies'=>[
					'heinaes',
					'hienies',
				],
				'heinous'=>[
					'henious',
					'hienous',
				],
				'heinousness'=>[
					'hienousness',
				],
				'heinousnesses'=>[
					'hienousnesses',
				],
				'heir'=>[
					'hier',
				],
				'heirdom'=>[
					'hierdom',
				],
				'heired'=>[
					'hiered',
				],
				'heiress'=>[
					'heires',
					'hieress',
				],
				'heiring'=>[
					'hiering',
				],
				'heirloom'=>[
					'hierloom',
				],
				'heirs'=>[
					'hiers',
				],
				'heirship'=>[
					'hiership',
				],
				'heishi'=>[
					'hieshi',
				],
				'heist'=>[
					'hiest',
				],
				'heisted'=>[
					'hiested',
				],
				'heister'=>[
					'hiester',
				],
				'heists'=>[
					'hiests',
				],
				'held'=>[
					'held held',
					'held held held',
					'helded',
					'holded',
				],
				'heldentenor'=>[
					'heldantenor',
					'heldentenour',
				],
				'heldentenors'=>[
					'heldantenors',
					'heldentenours',
				],
				'heliocentric'=>[
					'heliocantric',
				],
				'heliometrically'=>[
					'heliometricaly',
				],
				'hell'=>[
					'hel',
				],
				'hellacious'=>[
					'hellacous',
				],
				'hellaciously'=>[
					'hellacously',
				],
				'heller'=>[
					'heler',
				],
				'hellgrammite'=>[
					'helgrammite',
					'hellgramnite',
				],
				'hellgrammites'=>[
					'hellgramnites',
				],
				'hellish'=>[
					'helish',
				],
				'hello'=>[
					'heiio',
					'heilo',
					'helio',
					'helo',
				],
				'help'=>[
					'help help',
					'help help help',
				],
				'helpable'=>[
					'helpible',
				],
				'helped set up'=>[
					'helped setup',
				],
				'helpful'=>[
					'helpfull',
				],
				'helpless'=>[
					'helples',
				],
				'hemagglutinate'=>[
					'hemagglutinite',
					'hemaglutinate',
				],
				'hemagglutinated'=>[
					'hemagglutinited',
					'hemaglutinated',
				],
				'hemagglutinates'=>[
					'hemagglutinites',
					'hemaglutinates',
				],
				'hemagglutinin'=>[
					'hemagglutinan',
					'hemaglutinin',
				],
				'hemagglutinins'=>[
					'hemagglutinans',
					'hemaglutinins',
				],
				'hematein'=>[
					'hematien',
				],
				'hematinic'=>[
					'hematinac',
				],
				'hematopoiesis'=>[
					'hematopoeisis',
					'hematopoisis',
				],
				'hemerocallis'=>[
					'hemerocalis',
				],
				'hemerocallises'=>[
					'hemerocalises',
				],
				'hemicellulose'=>[
					'hemicelulose',
				],
				'hemicelluloses'=>[
					'hemiceluloses',
				],
				'hemimorphic'=>[
					'hemimourphic',
				],
				'hemimorphism'=>[
					'hemimourphism',
				],
				'hemimorphisms'=>[
					'hemimourphisms',
				],
				'hemline'=>[
					'hemlini',
				],
				'hemmed'=>[
					'hemned',
				],
				'hemmer'=>[
					'hemner',
				],
				'hemodynamically'=>[
					'hemodynamicalally',
					'hemodynamicalaly',
					'hemodynamicalely',
					'hemodynamicallly',
					'hemodynamicaly',
				],
				'hemoflagellate'=>[
					'hemoflagelate',
				],
				'hemoflagellates'=>[
					'hemoflagelates',
				],
				'hemopoiesis'=>[
					'hemopoeisis',
					'hemopoisis',
				],
				'hemoprotein'=>[
					'hemoprotien',
				],
				'hemoproteins'=>[
					'hemoprotiens',
				],
				'hemorrhage'=>[
					'hemmorhage',
					'hemorhage',
					'hemourrhage',
				],
				'hemorrhaged'=>[
					'hemourrhaged',
				],
				'hemorrhages'=>[
					'hemourrhages',
				],
				'hemorrhagic'=>[
					'hemourrhagic',
				],
				'hemorrhaging'=>[
					'hemourrhaging',
				],
				'hemorrhoid'=>[
					'hemorhoid',
					'hemourrhoid',
				],
				'hemorrhoidal'=>[
					'hemorhoidal',
					'hemourrhoidal',
				],
				'hemorrhoidals'=>[
					'hemorhoidals',
					'hemourrhoidals',
				],
				'hemorrhoids'=>[
					'hemourrhoids',
				],
				'hence'=>[
					'hcncc',
					'hcnce',
					'hcnec',
					'hencc',
					'henoe',
				],
				'hendecasyllabic'=>[
					'hendecasylabic',
				],
				'hendecasyllable'=>[
					'hendecasylable',
					'hendecasyllible',
				],
				'henna'=>[
					'hena',
				],
				'henneries'=>[
					'heneries',
				],
				'hennery'=>[
					'henery',
				],
				'hennishly'=>[
					'henishly',
				],
				'henotheism'=>[
					'henothiesm',
				],
				'henotheisms'=>[
					'henothiesms',
				],
				'henotheist'=>[
					'henothiest',
				],
				'henotheistic'=>[
					'henothiestic',
				],
				'henotheists'=>[
					'henothiests',
				],
				'henri espinouze'=>[
					'henri espinoza',
				],
				'hent'=>[
					'hant',
				],
				'hented'=>[
					'hanted',
				],
				'hents'=>[
					'hants',
				],
				'heparin'=>[
					'heperin',
				],
				'heparinized'=>[
					'heparinazed',
					'heperinized',
				],
				'heparins'=>[
					'heperins',
				],
				'hepatomegaly'=>[
					'hepatomegaally',
					'hepatomegaaly',
					'hepatomegaely',
					'hepatomegally',
				],
				'hepatopancreas'=>[
					'hepatopancres',
				],
				'heptathlon'=>[
					'heptathalon',
				],
				'her'=>[
					'her her',
					'her her her',
				],
				'here'=>[
					'here here',
					'here here here',
				],
				'hereafter'=>[
					'herefter',
				],
				'hereditarian'=>[
					'hereditaran',
				],
				'hereditary'=>[
					'hereditery',
				],
				'herein'=>[
					'herien',
				],
				'hereinabove'=>[
					'hereinibove',
					'herienabove',
				],
				'hereinafter'=>[
					'hereinifter',
					'herienafter',
				],
				'hereinbefore'=>[
					'herienbefore',
				],
				'hereinbelow'=>[
					'herienbelow',
				],
				'hereinto'=>[
					'heriento',
				],
				'heresy'=>[
					'herecy',
				],
				'heritable'=>[
					'heritible',
				],
				'heritage'=>[
					'hertiage',
				],
				'hermeneutically'=>[
					'hermeneuticaly',
				],
				'heroes'=>[
					'heros',
				],
				'heroine'=>[
					'heroini',
				],
				'heroinism'=>[
					'heroinasm',
				],
				'herrenvolk'=>[
					'herenvolk',
				],
				'herried'=>[
					'heried',
				],
				'herring'=>[
					'hering',
				],
				'herringbone'=>[
					'heringbone',
				],
				'herringboning'=>[
					'heringboning',
				],
				'herry'=>[
					'hery',
				],
				'hers'=>[
					'her\'s',
				],
				'herself'=>[
					'her self',
				],
				'hesitance'=>[
					'hesitence',
				],
				'hesitancy'=>[
					'hesitansy',
				],
				'hesitant'=>[
					'hesitent',
				],
				'hessian'=>[
					'hessan',
				],
				'heteroecious'=>[
					'heteroecous',
				],
				'heterogeneities'=>[
					'heterogenieties',
				],
				'heterogeneity'=>[
					'heterogeniety',
				],
				'heterogeneous'=>[
					'heterogenous',
				],
				'heterologously'=>[
					'heterologousally',
					'heterologousaly',
					'heterologousely',
					'heterologouslly',
				],
				'heteromorphic'=>[
					'heteromourphic',
				],
				'heteromorphism'=>[
					'heteromourphism',
				],
				'heteromorphisms'=>[
					'heteromourphisms',
				],
				'heterophyllies'=>[
					'heterophylies',
				],
				'heterophyllous'=>[
					'heterophylous',
				],
				'heterosexual'=>[
					'heterosexaul',
				],
				'heterosexuality'=>[
					'heterosexaulity',
				],
				'heterosexually'=>[
					'heterosexaully',
					'heterosexualally',
					'heterosexualaly',
					'heterosexualely',
					'heterosexuallly',
					'heterosexualy',
				],
				'heterosexuals'=>[
					'heterosexauls',
				],
				'heterothallic'=>[
					'heterothalic',
				],
				'heterothallism'=>[
					'heterothalism',
				],
				'heterothallisms'=>[
					'heterothalisms',
				],
				'hewable'=>[
					'hewible',
				],
				'hexahedra'=>[
					'hexaedra',
				],
				'hexahedron'=>[
					'hexaedron',
				],
				'hexahedrons'=>[
					'hexaedrons',
				],
				'hexahydrate'=>[
					'hexaydrate',
				],
				'hexahydrates'=>[
					'hexaydrates',
				],
				'hexaplar'=>[
					'hexapler',
				],
				'hexereis'=>[
					'hexeries',
				],
				'hexokinases'=>[
					'hexokinises',
				],
				'hexosaminidase'=>[
					'hexosaminadase',
				],
				'heyday'=>[
					'hayday',
				],
				'hibiscus'=>[
					'hibicsus',
					'hibicus',
					'hibisus',
				],
				'hiccough'=>[
					'hicough',
				],
				'hiccoughed'=>[
					'hicoughed',
				],
				'hiccoughing'=>[
					'hicoughing',
				],
				'hiccoughs'=>[
					'hicoughs',
				],
				'hiccup'=>[
					'hicup',
				],
				'hiccuped'=>[
					'hicuped',
				],
				'hiccuping'=>[
					'hicuping',
				],
				'hiccupped'=>[
					'hicupped',
				],
				'hiccupping'=>[
					'hicupping',
				],
				'hiccups'=>[
					'hicups',
				],
				'hidable'=>[
					'hidible',
				],
				'hidden'=>[
					'hideen',
				],
				'hiddennesses'=>[
					'hiddenesses',
				],
				'hiding'=>[
					'hidding',
				],
				'hie'=>[
					'hei',
				],
				'hied'=>[
					'heid',
				],
				'hierarch'=>[
					'heirarch',
				],
				'hierarchical'=>[
					'heirarchial',
					'heirarchical',
					'hierachical',
					'hierarchial',
					'hierarcical',
					'hirarchical',
				],
				'hierarchically'=>[
					'hierarchially',
					'hierarchicaly',
				],
				'hierarchies'=>[
					'hierachies',
				],
				'hierarchize'=>[
					'heirarchize',
					'hirarchize',
				],
				'hierarchy'=>[
					'heirarchy',
					'hierachy',
					'hierarcy',
					'hirarchy',
				],
				'hieratic'=>[
					'heiratic',
					'hiratic',
				],
				'hieroglyph'=>[
					'heiroglyph',
					'hieroglph',
					'hiroglyph',
				],
				'hieroglyphic'=>[
					'heiroglyphic',
					'hiroglyphic',
				],
				'hieroglyphics'=>[
					'heiroglyphics',
				],
				'hieroglyphs'=>[
					'hieroglphs',
				],
				'hierophant'=>[
					'heirophant',
					'hirophant',
				],
				'hierophantic'=>[
					'hierophentic',
				],
				'hies'=>[
					'heis',
				],
				'higgle'=>[
					'higle',
				],
				'high'=>[
					'high high',
					'high high high',
					'hlgh',
				],
				'high-level rank'=>[
					'high level rank',
				],
				'high-profile gigs'=>[
					'high profile gigs',
				],
				'higher'=>[
					'heigher',
					'higer',
					'highter',
				],
				'highest'=>[
					'higest',
				],
				'highhanded'=>[
					'highbanded',
				],
				'highlands'=>[
					'higlands',
				],
				'highness'=>[
					'highnes',
				],
				'highway'=>[
					'higllway',
				],
				'hijrah'=>[
					'hijra',
				],
				'hijrahs'=>[
					'hijras',
				],
				'hilar'=>[
					'hiler',
				],
				'hilarious'=>[
					'hilarous',
					'hillarious',
				],
				'hilariously'=>[
					'hilarously',
				],
				'hill'=>[
					'hil',
					'hill hill',
					'hill hill hill',
				],
				'hillary clinton'=>[
					'hilary clinton',
				],
				'hillbilly'=>[
					'hillbilally',
					'hillbilaly',
					'hillbilely',
					'hillbillly',
				],
				'hillcrest'=>[
					'hilcrest',
				],
				'hillside'=>[
					'hilside',
				],
				'hilltop'=>[
					'hiltop',
				],
				'hilly'=>[
					'hilally',
					'hilaly',
					'hillly',
					'hily',
				],
				'him'=>[
					'him him',
					'him him him',
				],
				'himself'=>[
					'hiinself',
					'him self',
					'himseld',
					'hismelf',
					'hisself',
					'hmself',
				],
				'hindquarter'=>[
					'hindqaurter',
				],
				'hindquarters'=>[
					'hindqaurters',
				],
				'hindrance'=>[
					'hinderance',
					'hinderence',
					'hindrence',
				],
				'hindrances'=>[
					'hinderances',
				],
				'hindu'=>[
					'hindoo',
				],
				'hindus'=>[
					'hindoos',
				],
				'hinny'=>[
					'hiny',
				],
				'hiphugger'=>[
					'hiphuger',
				],
				'hiply'=>[
					'hipally',
					'hipaly',
					'hiplly',
				],
				'hipparch'=>[
					'hipperch',
				],
				'hipparchs'=>[
					'hipperchs',
				],
				'hipped'=>[
					'hiped',
				],
				'hippie'=>[
					'hipie',
					'hippei',
					'hippi',
				],
				'hippieish'=>[
					'hippiiesh',
				],
				'hippienesses'=>[
					'hipienesses',
				],
				'hippo'=>[
					'hipo',
				],
				'hippocampus'=>[
					'hipocampus',
				],
				'hippocras'=>[
					'hipocras',
				],
				'hippodrome'=>[
					'hipodrome',
				],
				'hippogriff'=>[
					'hipogriff',
				],
				'hippopotamus'=>[
					'hipopotamus',
				],
				'hippopotamuses'=>[
					'hipopotamuses',
				],
				'hippy'=>[
					'hipy',
				],
				'hirable'=>[
					'hirible',
				],
				'hirsute'=>[
					'hersuit',
					'hersute',
					'hirsuit',
				],
				'his'=>[
					'his his',
					'his his his',
					'hs',
				],
				'hiss'=>[
					'his',
				],
				'hissy'=>[
					'hiscy',
					'hisy',
				],
				'histaminase'=>[
					'histaminise',
				],
				'histamine'=>[
					'histamini',
				],
				'histaminergic'=>[
					'histaminirgic',
				],
				'histidine'=>[
					'histidini',
				],
				'histochemically'=>[
					'histochemicalally',
					'histochemicalaly',
					'histochemicalely',
					'histochemicallly',
					'histochemicaly',
				],
				'histocompatibility'=>[
					'histocompatability',
				],
				'historian'=>[
					'historan',
				],
				'history'=>[
					'hisory',
					'hisotry',
					'history history',
					'history history history',
					'histroy',
					'hitory',
				],
				'histrionically'=>[
					'histrionicaly',
				],
				'hit'=>[
					'hit hit',
					'hit hit hit',
				],
				'hit-and-run'=>[
					'hit and run',
				],
				'hitches'=>[
					'hitchs',
				],
				'hitter'=>[
					'hitted',
				],
				'hitting'=>[
					'hiting',
				],
				'hmm'=>[
					'hmn',
				],
				'hoar'=>[
					'hoer',
				],
				'hoarsely'=>[
					'hoarsly',
				],
				'hoarsened'=>[
					'hoarsend',
				],
				'hoary'=>[
					'hoery',
				],
				'hobbed'=>[
					'hobed',
				],
				'hobber'=>[
					'hober',
				],
				'hobbers'=>[
					'hobers',
				],
				'hobbies'=>[
					'hobies',
				],
				'hobbing'=>[
					'hobing',
				],
				'hobbit'=>[
					'hobit',
				],
				'hobbits'=>[
					'hobits',
				],
				'hobble'=>[
					'hoble',
				],
				'hobblebush'=>[
					'hoblebush',
				],
				'hobblebushes'=>[
					'hoblebushes',
				],
				'hobbled'=>[
					'hobled',
				],
				'hobbledehoy'=>[
					'hobledehoy',
				],
				'hobbledehoys'=>[
					'hobledehoys',
				],
				'hobbler'=>[
					'hobler',
				],
				'hobbles'=>[
					'hobles',
				],
				'hobby'=>[
					'hoby',
				],
				'hobbyhorse'=>[
					'hobyhorse',
				],
				'hobbyhorses'=>[
					'hobyhorses',
				],
				'hobbyist'=>[
					'hobbiest',
					'hobbist',
				],
				'hobbyists'=>[
					'hobyists',
				],
				'hobnobbed'=>[
					'hobnobed',
				],
				'hobnobber'=>[
					'hobnober',
				],
				'hobnobbers'=>[
					'hobnobers',
				],
				'hobnobbing'=>[
					'hobnobing',
				],
				'hobos'=>[
					'hoboes',
				],
				'hocusing'=>[
					'hocuisng',
				],
				'hodgkin\'s disease'=>[
					'hodgkins disease',
				],
				'hogg'=>[
					'hog',
				],
				'hogget'=>[
					'hoget',
				],
				'hoggish'=>[
					'hogish',
				],
				'hoggishly'=>[
					'hogishly',
				],
				'hoggishness'=>[
					'hogishness',
				],
				'hoggishnesses'=>[
					'hogishnesses',
				],
				'hoggs'=>[
					'hogs',
				],
				'hogtieing'=>[
					'hogtiieng',
				],
				'hoidened'=>[
					'hoidend',
				],
				'hold'=>[
					'hold hold',
					'hold hold hold',
				],
				'holds'=>[
					'hold\'s',
				],
				'hole'=>[
					'hole hole',
					'hole hole hole',
				],
				'holiness'=>[
					'holines',
					'holiniss',
				],
				'holistic'=>[
					'hollistic',
					'wholistic',
				],
				'holla'=>[
					'hola',
				],
				'holland'=>[
					'holand',
				],
				'holler'=>[
					'holer',
				],
				'hollow'=>[
					'holow',
				],
				'hollowly'=>[
					'hollowally',
					'hollowaly',
					'hollowely',
					'hollowlly',
				],
				'holly'=>[
					'holally',
					'holaly',
					'hollly',
					'holy',
				],
				'holographically'=>[
					'holographicaly',
				],
				'holothurian'=>[
					'holothuran',
				],
				'holstein'=>[
					'holstien',
				],
				'holsteins'=>[
					'holstiens',
				],
				'home'=>[
					'home home',
					'home home home',
				],
				'homeless'=>[
					'homeles',
				],
				'homely'=>[
					'homeally',
					'homealy',
					'homeely',
					'homelly',
					'homly',
				],
				'homemade'=>[
					'homade',
					'homeade',
				],
				'homemaker'=>[
					'homaker',
				],
				'homemakers'=>[
					'homakers',
				],
				'homemaking'=>[
					'homaking',
				],
				'homemakings'=>[
					'homakings',
				],
				'homeomorphic'=>[
					'homeomourphic',
				],
				'homeomorphism'=>[
					'homeomourphism',
				],
				'homeomorphisms'=>[
					'homeomourphisms',
				],
				'homeopathically'=>[
					'homeopathicaly',
				],
				'homepage'=>[
					'hompage',
				],
				'homeschool'=>[
					'homechool',
					'homecshool',
					'homeshool',
				],
				'homestead'=>[
					'homested',
				],
				'hometown'=>[
					'home town',
				],
				'homicide'=>[
					'homocide',
				],
				'homie'=>[
					'homei',
					'homi',
				],
				'homily'=>[
					'homially',
					'homialy',
					'homiely',
					'homilly',
				],
				'hominian'=>[
					'hominaan',
					'hominan',
				],
				'hominid'=>[
					'hominad',
				],
				'hominids'=>[
					'hominads',
				],
				'hominies'=>[
					'hominaes',
				],
				'hominine'=>[
					'hominane',
				],
				'hominization'=>[
					'hominazation',
				],
				'hominizations'=>[
					'hominazations',
				],
				'hominize'=>[
					'hominaze',
				],
				'hommocks'=>[
					'homnocks',
				],
				'hommos'=>[
					'homnos',
				],
				'hommoses'=>[
					'homnoses',
				],
				'homocercy'=>[
					'homocersy',
				],
				'homogeneities'=>[
					'homogenieties',
				],
				'homogeneity'=>[
					'homogeniety',
				],
				'homogeneously'=>[
					'homogeneousally',
					'homogeneousaly',
					'homogeneousely',
					'homogeneouslly',
				],
				'homogenize'=>[
					'homogeneize',
				],
				'homogenized'=>[
					'homogeneized',
				],
				'homoiousian'=>[
					'homoiouisan',
					'homoiousan',
				],
				'homoiousians'=>[
					'homoiouisans',
				],
				'homomorphic'=>[
					'homomourphic',
				],
				'homomorphism'=>[
					'homomourphism',
				],
				'homomorphisms'=>[
					'homomourphisms',
				],
				'homonuclear'=>[
					'homonucleer',
				],
				'homoousian'=>[
					'homoouisan',
					'homoousan',
				],
				'homoousians'=>[
					'homoouisans',
				],
				'homophyly'=>[
					'homophyally',
					'homophyaly',
					'homophyely',
					'homophylly',
				],
				'homoplasy'=>[
					'homoplacy',
				],
				'homopolar'=>[
					'homopoler',
				],
				'homosexual'=>[
					'homosexaul',
				],
				'homosexualities'=>[
					'homosexaulities',
				],
				'homosexuality'=>[
					'homosexaulity',
				],
				'homosexually'=>[
					'homosexaully',
				],
				'homostyly'=>[
					'homostyally',
					'homostyaly',
					'homostyely',
					'homostylly',
				],
				'homotransplant'=>[
					'homotransplent',
				],
				'homotransplants'=>[
					'homotransplents',
				],
				'honduran-occupied'=>[
					'honduran occupied',
				],
				'honestly'=>[
					'honestally',
					'honestaly',
					'honestely',
					'honestlly',
				],
				'honeyed'=>[
					'honied',
				],
				'honor'=>[
					'bonor',
					'honord',
				],
				'honorabilities'=>[
					'honourabilities',
				],
				'honorability'=>[
					'honourability',
				],
				'honorable'=>[
					'honarable',
					'honorible',
					'honoruable',
					'honourable',
				],
				'honorableness'=>[
					'honourableness',
				],
				'honorablenesses'=>[
					'honourablenesses',
				],
				'honorably'=>[
					'honourably',
				],
				'honorand'=>[
					'honourand',
				],
				'honorands'=>[
					'honourands',
				],
				'honoraria'=>[
					'honouraria',
				],
				'honoraries'=>[
					'honouraries',
				],
				'honorarily'=>[
					'honourarily',
				],
				'honorarium'=>[
					'honourarium',
				],
				'honorariums'=>[
					'honourariums',
				],
				'honorary'=>[
					'honorery',
					'honory',
					'honourary',
				],
				'honored'=>[
					'honord',
					'honoured',
				],
				'honoree'=>[
					'honouree',
				],
				'honorees'=>[
					'honourees',
				],
				'honorer'=>[
					'honourer',
				],
				'honorers'=>[
					'honourers',
				],
				'honorific'=>[
					'honourific',
				],
				'honorifically'=>[
					'honourifically',
				],
				'honorifics'=>[
					'honourifics',
				],
				'honoring'=>[
					'bonoring',
					'honouring',
				],
				'honourable'=>[
					'honourible',
				],
				'hoodie'=>[
					'hoodei',
					'hoodi',
				],
				'hookah'=>[
					'hooka',
				],
				'hookahs'=>[
					'hookas',
				],
				'hooknose'=>[
					'hookose',
				],
				'hooknosed'=>[
					'hookosed',
				],
				'hooknoses'=>[
					'hookoses',
				],
				'hooly'=>[
					'hooally',
					'hooaly',
					'hoolly',
				],
				'hoorah'=>[
					'hoora',
				],
				'hoorahed'=>[
					'hooraed',
				],
				'hoorahing'=>[
					'hooraing',
				],
				'hoorahs'=>[
					'hooras',
				],
				'hootenannies'=>[
					'hootenanies',
				],
				'hootenanny'=>[
					'hootenany',
				],
				'hope'=>[
					'hope hope',
					'hope hope hope',
				],
				'hopeful'=>[
					'hopefull',
				],
				'hopefully'=>[
					'hopefulally',
					'hopefulaly',
					'hopefulely',
					'hopefullly',
					'hopefuly',
					'hopfully',
				],
				'hopeless'=>[
					'hopeles',
				],
				'hoping'=>[
					'hopeing',
				],
				'hopper'=>[
					'hoper',
				],
				'hopple'=>[
					'hople',
				],
				'hoppy'=>[
					'hopy',
				],
				'hopscotch'=>[
					'hopcotch',
					'hopcsotch',
					'hopsotch',
				],
				'horah'=>[
					'hora',
				],
				'horahs'=>[
					'horas',
				],
				'horary'=>[
					'horery',
				],
				'hordeins'=>[
					'hordiens',
				],
				'hornswoggle'=>[
					'hornswogle',
				],
				'hornswoggled'=>[
					'hornswogled',
				],
				'hornswoggles'=>[
					'hornswogles',
				],
				'hornswoggling'=>[
					'hornswogling',
				],
				'horoscope'=>[
					'horocope',
					'horocsope',
					'horosope',
				],
				'horrendous'=>[
					'horendous',
				],
				'horrent'=>[
					'horent',
				],
				'horrible'=>[
					'horible',
					'hornble',
					'horrable',
				],
				'horriblenesses'=>[
					'horiblenesses',
				],
				'horrid'=>[
					'horid',
				],
				'horridness'=>[
					'horidness',
				],
				'horrific'=>[
					'horific',
				],
				'horrify'=>[
					'horify',
				],
				'horrifying'=>[
					'horifying',
					'horrifing',
				],
				'horror'=>[
					'horor',
				],
				'horrors'=>[
					'horors',
				],
				'horse'=>[
					'horse horse',
					'horse horse horse',
				],
				'horsefeathers'=>[
					'horsefethers',
				],
				'horsefly'=>[
					'horsefally',
					'horsefaly',
					'horsefely',
					'horseflly',
				],
				'horseshoeing'=>[
					'horseshoieng',
				],
				'horsewhipped'=>[
					'horsewhiped',
				],
				'horsewhipper'=>[
					'horsewhiper',
				],
				'horsewhippers'=>[
					'horsewhipers',
				],
				'horsewhipping'=>[
					'horsewhiping',
				],
				'horsy'=>[
					'horcy',
				],
				'horticulturally'=>[
					'horticulturaly',
				],
				'horticulture'=>[
					'horticultnre',
				],
				'hosanna'=>[
					'hosana',
				],
				'hosannah'=>[
					'hosanna',
				],
				'hosannahs'=>[
					'hosannas',
				],
				'hosiery'=>[
					'hoseiry',
					'hosiry',
				],
				'hospitable'=>[
					'hospitible',
				],
				'hospital'=>[
					'hopsital',
					'hosptal',
					'hosptial',
					'hostpital',
				],
				'hospodar'=>[
					'hospoder',
				],
				'hosted'=>[
					'hoasted',
				],
				'hostess'=>[
					'hostes',
				],
				'hostilely'=>[
					'hostilly',
				],
				'hostly'=>[
					'hostally',
					'hostaly',
					'hostely',
					'hostlly',
				],
				'hot'=>[
					'hot hot',
					'hot hot hot',
				],
				'hotdogged'=>[
					'hotdoged',
				],
				'hotdogger'=>[
					'hotdoger',
				],
				'hotelier'=>[
					'hoteleir',
					'hotelir',
				],
				'hotheadednesses'=>[
					'hothedednesses',
				],
				'hothousing'=>[
					'hothouisng',
				],
				'hotly'=>[
					'hotally',
					'hotaly',
					'hotlly',
				],
				'hottie'=>[
					'hottei',
					'hotti',
				],
				'houdah'=>[
					'houda',
				],
				'houdahs'=>[
					'houdas',
				],
				'hour'=>[
					'hour hour',
					'hour hour hour',
				],
				'hour-long programme'=>[
					'hour long programme',
				],
				'hourly'=>[
					'hourally',
					'houraly',
					'hourely',
					'hourlly',
				],
				'hours'=>[
					'housr',
				],
				'house'=>[
					'house house',
					'house house house',
				],
				'housebreaking'=>[
					'housebreking',
				],
				'housebreakings'=>[
					'housebrekings',
				],
				'housecleaning'=>[
					'houseclening',
				],
				'housecleanings'=>[
					'houseclenings',
				],
				'housefly'=>[
					'housefally',
					'housefaly',
					'housefely',
					'houseflly',
				],
				'household'=>[
					'houshold',
				],
				'housekeeper'=>[
					'houskeeper',
				],
				'houseparent'=>[
					'houseperent',
				],
				'houseparents'=>[
					'houseperents',
				],
				'houseplant'=>[
					'houseplent',
				],
				'housewife'=>[
					'houswife',
				],
				'housewifeliness'=>[
					'housewifeliniss',
				],
				'housewifely'=>[
					'housewifeally',
					'housewifealy',
					'housewifeely',
					'housewifelly',
					'housewifly',
				],
				'housewives'=>[
					'housewifes',
				],
				'housings'=>[
					'houisngs',
				],
				'hoverfly'=>[
					'hoverfally',
					'hoverfaly',
					'hoverfely',
					'hoverflly',
				],
				'how'=>[
					'how how',
					'how how how',
				],
				'howbeit'=>[
					'howbiet',
				],
				'howdah'=>[
					'howda',
				],
				'howdahs'=>[
					'howdas',
				],
				'however'=>[
					'how ever',
					'howver',
				],
				'hoydened'=>[
					'hoydend',
				],
				'huarache'=>[
					'haurache',
				],
				'hubbies'=>[
					'hubies',
				],
				'hubbly'=>[
					'hubly',
				],
				'hubbub'=>[
					'hubub',
				],
				'hubbubs'=>[
					'hububs',
				],
				'hubby'=>[
					'huby',
				],
				'huckleberries'=>[
					'huckleberies',
				],
				'huckleberry'=>[
					'hucklebery',
				],
				'huge'=>[
					'huge huge',
					'huge huge huge',
				],
				'hugely'=>[
					'hugly',
				],
				'hugh hefner'=>[
					'hugh heffner',
				],
				'hull'=>[
					'hul',
				],
				'hullabaloo'=>[
					'hulabaloo',
				],
				'hullo'=>[
					'hulo',
				],
				'human'=>[
					'human human',
					'human human human',
				],
				'humanely'=>[
					'humanly',
				],
				'humanistically'=>[
					'humanisticalally',
					'humanisticalaly',
					'humanisticalely',
					'humanisticallly',
				],
				'humanitarian'=>[
					'humanitaran',
				],
				'humanly'=>[
					'humanally',
					'humanaly',
					'humanely',
					'humanlly',
				],
				'humannesses'=>[
					'humanesses',
				],
				'humbugged'=>[
					'humbuged',
				],
				'humbugger'=>[
					'humbuger',
				],
				'humbuggeries'=>[
					'humbugeries',
				],
				'humidifier'=>[
					'humidifeir',
					'humidifir',
				],
				'humidly'=>[
					'humidally',
					'humidaly',
					'humidely',
					'humidlly',
				],
				'hummable'=>[
					'humnable',
				],
				'hummed'=>[
					'humned',
				],
				'hummer'=>[
					'humner',
				],
				'hummingbird'=>[
					'humningbird',
				],
				'hummingbirds'=>[
					'humningbirds',
				],
				'hummock'=>[
					'humnock',
				],
				'hummocks'=>[
					'humnocks',
				],
				'hummocky'=>[
					'humnocky',
				],
				'hummus'=>[
					'humnus',
				],
				'hummuses'=>[
					'humnuses',
				],
				'humor'=>[
					'humer',
				],
				'humoral'=>[
					'humoural',
				],
				'humored'=>[
					'humoured',
				],
				'humoresque'=>[
					'humouresque',
				],
				'humoresques'=>[
					'humouresques',
				],
				'humorful'=>[
					'humourful',
				],
				'humoring'=>[
					'humouring',
				],
				'humorist'=>[
					'humourist',
				],
				'humoristic'=>[
					'humouristic',
				],
				'humorists'=>[
					'humourists',
				],
				'humorless'=>[
					'humourless',
				],
				'humorlessly'=>[
					'humorlessally',
					'humorlessaly',
					'humorlessely',
					'humorlesslly',
					'humourlessly',
				],
				'humorlessness'=>[
					'humourlessness',
				],
				'humorlessnesses'=>[
					'humourlessnesses',
				],
				'humorous'=>[
					'humerous',
					'humourous',
				],
				'humorously'=>[
					'humourously',
				],
				'humorousness'=>[
					'humourousness',
				],
				'humorousnesses'=>[
					'humourousnesses',
				],
				'humors'=>[
					'humours',
				],
				'hundred'=>[
					'hundered',
					'hundred hundred',
					'hundred hundred hundred',
					'hundrend',
					'liraidred',
				],
				'hundredweight'=>[
					'hundredwieght',
				],
				'hundredweights'=>[
					'hundredwieghts',
				],
				'hungarian'=>[
					'hungaran',
				],
				'hungarian-occupied'=>[
					'hungarian occupied',
				],
				'hunt'=>[
					'hunt hunt',
					'hunt hunt hunt',
				],
				'huppah'=>[
					'huppa',
				],
				'huppahs'=>[
					'huppas',
				],
				'hurdy-gurdies'=>[
					'hurdy gurdies',
					'hurdy gurdys',
					'hurdy-gurdys',
				],
				'hurdy-gurdy'=>[
					'hurdy gurdy',
				],
				'hurly'=>[
					'hurally',
					'huraly',
					'hurlly',
				],
				'hurrah'=>[
					'hurah',
					'hurra',
				],
				'hurrahed'=>[
					'hurraed',
				],
				'hurrahing'=>[
					'hurraing',
				],
				'hurrahs'=>[
					'hurahs',
					'hurras',
				],
				'hurray'=>[
					'huray',
				],
				'hurrays'=>[
					'hurays',
				],
				'hurricane'=>[
					'huricane',
					'hurricaine',
				],
				'hurricanes'=>[
					'huricanes',
				],
				'hurried'=>[
					'huried',
					'hurreid',
					'hurrid',
				],
				'hurriednesses'=>[
					'huriednesses',
				],
				'hurrier'=>[
					'hurier',
				],
				'hurry'=>[
					'hurry hurry',
					'hurry hurry hurry',
					'hury',
				],
				'husband'=>[
					'husban',
				],
				'hussar'=>[
					'husar',
					'husser',
				],
				'hussy'=>[
					'huscy',
					'husy',
				],
				'hutzpah'=>[
					'hutzpa',
				],
				'hutzpahs'=>[
					'hutzpas',
				],
				'huzzah'=>[
					'huzza',
				],
				'huzzahed'=>[
					'huzzaed',
				],
				'huzzahing'=>[
					'huzzaing',
				],
				'huzzahs'=>[
					'huzzas',
				],
				'hyaline'=>[
					'hyalini',
				],
				'hydralazine'=>[
					'hydralazini',
				],
				'hydrant'=>[
					'hydrent',
				],
				'hydraulic'=>[
					'hydralic',
				],
				'hydrazine'=>[
					'hydrazini',
				],
				'hydrocephaly'=>[
					'hydrocephaally',
					'hydrocephaaly',
					'hydrocephaely',
					'hydrocephally',
				],
				'hydrocolloid'=>[
					'hydrocoloid',
				],
				'hydrokinetic'=>[
					'hydrokinitic',
				],
				'hydromancy'=>[
					'hydromansy',
				],
				'hydrometallurgy'=>[
					'hydrometalurgy',
				],
				'hydromorphic'=>[
					'hydromourphic',
				],
				'hydrophile'=>[
					'hydropile',
				],
				'hydrophilic'=>[
					'hydropilic',
				],
				'hydrophobe'=>[
					'hydropobe',
				],
				'hydrophobic'=>[
					'hydropobic',
				],
				'hydropsy'=>[
					'hydropcy',
				],
				'hydrostatically'=>[
					'hydrostaticaly',
				],
				'hydrothermally'=>[
					'hydrothermalally',
					'hydrothermalaly',
					'hydrothermalely',
					'hydrothermallly',
				],
				'hydroxylamine'=>[
					'hydroxylamini',
				],
				'hydroxylamines'=>[
					'hydroxylaminis',
				],
				'hydroxyproline'=>[
					'hydroxyprolini',
				],
				'hydroxyprolines'=>[
					'hydroxyprolinis',
				],
				'hydroxyurea'=>[
					'hydroxyure',
				],
				'hydroxyzines'=>[
					'hydroxyzinis',
				],
				'hygeists'=>[
					'hygiests',
				],
				'hygieist'=>[
					'hygiiest',
				],
				'hygieists'=>[
					'hygiiests',
				],
				'hygiene'=>[
					'hygeine',
					'hygene',
					'hygine',
				],
				'hygienic'=>[
					'hygeinic',
					'hygenic',
					'hyginic',
				],
				'hygroscopic'=>[
					'hygrocopic',
					'hygrocsopic',
					'hygrosopic',
				],
				'hymnary'=>[
					'hymnery',
				],
				'hyoscyamine'=>[
					'hyocsyamine',
					'hyocyamine',
					'hyoscyamini',
					'hyosyamine',
				],
				'hyoscyamines'=>[
					'hyoscyaminis',
				],
				'hyperaggressive'=>[
					'hyperagressive',
				],
				'hypercautious'=>[
					'hypercautous',
				],
				'hypercoagulable'=>[
					'hypercoagulible',
				],
				'hyperconscious'=>[
					'hyperconcious',
					'hyperconcsious',
					'hyperconscous',
					'hyperconsious',
				],
				'hypercorrect'=>[
					'hypercorect',
				],
				'hypercorrection'=>[
					'hypercorection',
				],
				'hypercorrectly'=>[
					'hypercorectly',
					'hypercorrectally',
					'hypercorrectaly',
					'hypercorrectely',
					'hypercorrectlly',
				],
				'hypercritically'=>[
					'hypercriticaly',
				],
				'hyperexcitable'=>[
					'hyperexcitible',
				],
				'hyperfastidious'=>[
					'hyperfastidous',
				],
				'hyperimmune'=>[
					'hyperimnune',
				],
				'hyperimmunize'=>[
					'hyperimnunize',
				],
				'hyperimmunized'=>[
					'hyperimnunized',
				],
				'hyperimmunizes'=>[
					'hyperimnunizes',
				],
				'hyperimmunizing'=>[
					'hyperimnunizing',
				],
				'hyperinsulinism'=>[
					'hyperinsulinasm',
				],
				'hyperintense'=>[
					'hyperintence',
				],
				'hyperirritable'=>[
					'hyperiritable',
					'hyperirritible',
				],
				'hyperkineses'=>[
					'hyperkinises',
				],
				'hyperkinesia'=>[
					'hyperkinisia',
				],
				'hyperkinesias'=>[
					'hyperkinisias',
				],
				'hyperkinesis'=>[
					'hyperkinisis',
				],
				'hyperkinetic'=>[
					'hyperkinitic',
				],
				'hypermutable'=>[
					'hypermutible',
				],
				'hyperparasite'=>[
					'hyperperasite',
				],
				'hyperparasites'=>[
					'hyperperasites',
				],
				'hyperparasitic'=>[
					'hyperperasitic',
				],
				'hyperparasitism'=>[
					'hyperperasitism',
				],
				'hyperpituitary'=>[
					'hyperpituitery',
				],
				'hyperpneic'=>[
					'hyperpniec',
				],
				'hyperreactive'=>[
					'hypereactive',
				],
				'hyperreactivity'=>[
					'hypereactivity',
					'hyperrectivity',
				],
				'hyperreactors'=>[
					'hypereactors',
				],
				'hyperrealism'=>[
					'hyperealism',
					'hyperrelism',
				],
				'hyperrealisms'=>[
					'hyperealisms',
				],
				'hyperrealistic'=>[
					'hyperealistic',
					'hyperrelistic',
				],
				'hyperresponsive'=>[
					'hyperesponsive',
				],
				'hyperromantic'=>[
					'hyperomantic',
				],
				'hyperromantics'=>[
					'hyperomantics',
					'hyperromentics',
				],
				'hypersalinities'=>[
					'hypersalinaties',
				],
				'hypersalinity'=>[
					'hypersalinaty',
				],
				'hypersexual'=>[
					'hypersexaul',
				],
				'hypersexuality'=>[
					'hypersexaulity',
				],
				'hypersomnolence'=>[
					'hypersomnolance',
				],
				'hypertense'=>[
					'hypertence',
				],
				'hyperventilate'=>[
					'hypervantilate',
				],
				'hypervigilance'=>[
					'hypervigilence',
				],
				'hyphened'=>[
					'hyphend',
				],
				'hypnotize'=>[
					'hyptonize',
				],
				'hypoallergenic'=>[
					'hypoalergenic',
				],
				'hypocrisy'=>[
					'hypocracy',
					'hypocrasy',
					'hypocricy',
					'hyprocrisy',
				],
				'hypocrite'=>[
					'hypocricy ',
					'hypocrit',
				],
				'hypocrites'=>[
					'hypocrits',
				],
				'hypocritical'=>[
					'hyprocritical',
				],
				'hypoglossal'=>[
					'hypoglosal',
				],
				'hypopituitary'=>[
					'hypopituitery',
				],
				'hypopneic'=>[
					'hypopniec',
				],
				'hypoxanthine'=>[
					'hypoxanthini',
					'hypoxenthine',
				],
				'hypoxanthines'=>[
					'hypoxanthinis',
				],
				'hyssop'=>[
					'hysop',
				],
			];
		}
	}

?>