<?php
		
		/* UTF-8 TEST
		
			中文汉字漢字
		
		*/
				
				/* EnglishMisspellingsWords_O
					
					Class for English-Misspellings for all words beginning with : O.
					
				*/

	class EnglishMisspellingsWords_O {
			/* __construct($args)
			
				Constructor.
				
				Nothing to do here.
			
			*/
			
		public function __construct($args) {
			return TRUE;
		}
		
			/* EnglishMisspellingsWords()
			
				List of English misspellings for words starting with : O.
			
			*/

		public function EnglishMisspellingsWords() {
			return [
				'countries'=>[
					'ocuntries',
				],
				'country'=>[
					'ocuntry',
				],
				'going'=>[
					'oging',
				],
				'more'=>[
					'omre',
				],
				'note'=>[
					'onot',
				],
				'o\'boyle'=>[
					'o boyle',
				],
				'o\'neil'=>[
					'o neil',
				],
				'oaxaca'=>[
					'oaxac',
				],
				'obbligato'=>[
					'obligato',
				],
				'obbligatos'=>[
					'obligatos',
				],
				'obduracy'=>[
					'obdurasy',
				],
				'obdurate'=>[
					'abdurate',
				],
				'obdurately'=>[
					'obduratly',
				],
				'obeah'=>[
					'obea',
				],
				'obeahism'=>[
					'obeaism',
				],
				'obeahisms'=>[
					'obeaisms',
				],
				'obeahs'=>[
					'obeas',
				],
				'obedience'=>[
					'obedeince',
					'obediance',
					'obedince',
				],
				'obedient'=>[
					'obedeint',
					'obediant',
					'obedint',
				],
				'obeisance'=>[
					'obeisence',
					'obiesance',
				],
				'obento'=>[
					'obanto',
				],
				'obesely'=>[
					'obesly',
				],
				'obey'=>[
					'cbey',
				],
				'obfuscate'=>[
					'obfucate',
					'obfucsate',
					'obfusate',
				],
				'obituary'=>[
					'obitaury',
					'obituery',
				],
				'object'=>[
					'object object',
					'object object object',
				],
				'objectionable'=>[
					'objectionible',
				],
				'objective'=>[
					'objetive',
				],
				'oblately'=>[
					'oblatly',
				],
				'obligately'=>[
					'obligatly',
				],
				'obligatory'=>[
					'obligatoty',
				],
				'obliged'=>[
					'obligued',
				],
				'oblique'=>[
					'obligue',
				],
				'obliquely'=>[
					'obliquly',
				],
				'oblivious'=>[
					'oblivous',
				],
				'obliviously'=>[
					'oblivously',
				],
				'obnoxious'=>[
					'obnoxous',
				],
				'obnoxiously'=>[
					'obnoxously',
				],
				'obscene'=>[
					'obcene',
					'obcsene',
					'obsene',
				],
				'obscenely'=>[
					'obscenly',
				],
				'obscenity'=>[
					'obcenity',
					'obcsenity',
					'obsenity',
				],
				'obscurantism'=>[
					'obcsurantism',
					'obcurantism',
					'obscurentism',
					'obsurantism',
				],
				'obscure'=>[
					'obcsure',
					'obcure',
					'obsure',
				],
				'obscurely'=>[
					'obscurly',
				],
				'obscurity'=>[
					'obcsurity',
					'obcurity',
					'obsurity',
				],
				'obsequious'=>[
					'obsequous',
				],
				'obsequiously'=>[
					'obsequously',
				],
				'observable'=>[
					'observible',
				],
				'observance'=>[
					'observence',
				],
				'observant'=>[
					'observent',
				],
				'observation'=>[
					'obervation',
				],
				'observe'=>[
					'observe observe',
					'observe observe observe',
				],
				'observer'=>[
					'observor',
				],
				'obsess'=>[
					'obses',
				],
				'obsession'=>[
					'obsesion',
					'obssession',
				],
				'obsessive'=>[
					'obsesive',
					'obssessive',
				],
				'obsessively'=>[
					'obsessivly',
				],
				'obsidian'=>[
					'obsidan',
				],
				'obsolescence'=>[
					'obsolecence',
					'obsolecense',
					'obsolescance',
					'obsolesence',
					'obsolesense',
				],
				'obsolescent'=>[
					'obsolecent',
					'obsolecsent',
					'obsolesent',
				],
				'obsolescently'=>[
					'obsolescentally',
					'obsolescentaly',
					'obsolescentely',
					'obsolescentlly',
				],
				'obsoletely'=>[
					'obsoletly',
				],
				'obstacle'=>[
					'obstacal',
					'obsticle',
				],
				'obstacles'=>[
					'obstacels',
				],
				'obstetrician'=>[
					'obstetrican',
				],
				'obstinacy'=>[
					'obstinasy',
					'obstinicy',
				],
				'obstinate'=>[
					'obstinite',
				],
				'obstinately'=>[
					'obstinatly',
				],
				'obstinateness'=>[
					'obstiniteness',
				],
				'obstinatenesses'=>[
					'obstinitenesses',
				],
				'obstreperously'=>[
					'obstreperousally',
					'obstreperousaly',
					'obstreperousely',
					'obstreperouslly',
				],
				'obtainabilities'=>[
					'obtainibilities',
				],
				'obtainability'=>[
					'obtainibility',
				],
				'obtainment'=>[
					'obtaiment',
					'obtainent',
				],
				'obtainments'=>[
					'obtaiments',
					'obtainents',
				],
				'obtrusion'=>[
					'obtruison',
				],
				'obtrusions'=>[
					'obtruisons',
				],
				'obtrusive'=>[
					'obtruisve',
				],
				'obtrusively'=>[
					'obtruisvely',
					'obtrusivly',
				],
				'obtrusiveness'=>[
					'obtruisveness',
				],
				'obtrusivenesses'=>[
					'obtruisvenesses',
				],
				'obtundent'=>[
					'obtundant',
				],
				'obtundents'=>[
					'obtundants',
				],
				'obtusely'=>[
					'obtusly',
				],
				'obtusities'=>[
					'obtuisties',
				],
				'obtusity'=>[
					'obtuisty',
				],
				'obversely'=>[
					'obversly',
				],
				'obvious'=>[
					'obvous',
				],
				'obviously'=>[
					'obvously',
				],
				'ocarina'=>[
					'ocarini',
				],
				'ocarinas'=>[
					'ocarinis',
				],
				'occasion'=>[
					'ocasion',
					'ocassion',
					'occassion',
				],
				'occasional'=>[
					'ocasional',
					'ocassional',
					'occasonal',
					'occassional',
				],
				'occasionally'=>[
					'ocasionally',
					'ocasionaly',
					'ocassionally',
					'occaisonally',
					'occasionalally',
					'occasionalaly',
					'occasionalely',
					'occasionallly',
					'occasionaly',
					'occassionally',
					'occassionaly',
				],
				'occasioned'=>[
					'ocasioned',
					'ocassioned',
					'occassioned',
				],
				'occasions'=>[
					'ocasions',
					'ocassions',
					'occassions',
				],
				'occident'=>[
					'occidant',
					'ocident',
				],
				'occidental'=>[
					'occidantal',
					'ocidental',
				],
				'occidentalize'=>[
					'occidantalize',
					'ocidentalize',
				],
				'occidentalized'=>[
					'occidantalized',
					'ocidentalized',
				],
				'occidentalizes'=>[
					'occidantalizes',
					'ocidentalizes',
				],
				'occidentalizing'=>[
					'occidantalizing',
					'ocidentalizing',
				],
				'occidentally'=>[
					'occidantally',
				],
				'occidents'=>[
					'occidants',
				],
				'occipita'=>[
					'ocipita',
				],
				'occipital'=>[
					'ocipital',
				],
				'occiput'=>[
					'ociput',
				],
				'occiputs'=>[
					'ociputs',
				],
				'occlude'=>[
					'oclude',
				],
				'occluded'=>[
					'ocluded',
				],
				'occludent'=>[
					'occludant',
				],
				'occludes'=>[
					'ocludes',
				],
				'occlusal'=>[
					'oclusal',
				],
				'occlusion'=>[
					'occluison',
					'oclusion',
				],
				'occlusions'=>[
					'occluisons',
				],
				'occlusive'=>[
					'occluisve',
					'oclusive',
				],
				'occlusives'=>[
					'occluisves',
				],
				'occult'=>[
					'ocult',
				],
				'occultation'=>[
					'ocultation',
				],
				'occulted'=>[
					'oculted',
				],
				'occulter'=>[
					'oculter',
				],
				'occultism'=>[
					'ocultism',
				],
				'occults'=>[
					'ocults',
				],
				'occupancy'=>[
					'occupansy',
					'ocupancy',
				],
				'occupant'=>[
					'occupent',
					'ocupant',
				],
				'occupation'=>[
					'ocupation',
				],
				'occupational'=>[
					'ocupational',
				],
				'occupationally'=>[
					'occupationalally',
					'occupationalaly',
					'occupationalely',
					'occupationallly',
					'ocupationally',
				],
				'occupied'=>[
					'ocupied',
				],
				'occupy'=>[
					'ocupy',
				],
				'occur'=>[
					'occour',
					'occur occur',
					'occur occur occur',
					'occurr',
					'ocur',
					'ocurr',
				],
				'occurred'=>[
					'occured',
					'occurrod',
					'occurrud',
					'ocurred',
				],
				'occurrence'=>[
					'occurance',
					'occurence',
					'occurrance',
					'ocurrance',
					'ocurrence',
				],
				'occurrences'=>[
					'occurances',
					'occurences',
					'occurrances',
				],
				'occurring'=>[
					'occuring',
					'ocuring',
					'ocurring',
				],
				'occurs'=>[
					'occours',
					'ocurrs',
					'ocurs',
				],
				'ocean'=>[
					'ocean ocean',
					'ocean ocean ocean',
					'ocen',
				],
				'ocean-based'=>[
					'ocean based',
				],
				'oceanfront'=>[
					'ocenfront',
				],
				'oceangoing'=>[
					'ocengoing',
				],
				'oceanic'=>[
					'ocenic',
				],
				'oceanographical'=>[
					'ocenographical',
				],
				'oceanography'=>[
					'ocenography',
				],
				'ocellar'=>[
					'oceller',
				],
				'ochlocracy'=>[
					'ochlocrasy',
				],
				'octagon'=>[
					'octogon',
				],
				'octagonal'=>[
					'octogonal',
				],
				'octahedra'=>[
					'octaedra',
					'octohedra',
				],
				'octahedral'=>[
					'octaedral',
					'octohedral',
				],
				'octahedrally'=>[
					'octaedrally',
				],
				'octahedron'=>[
					'octaedron',
					'octohedron',
				],
				'octahedrons'=>[
					'octaedrons',
				],
				'octant'=>[
					'octent',
				],
				'octastyle'=>[
					'octostyle',
				],
				'octennial'=>[
					'octenial',
				],
				'october'=>[
					'ocober',
					'ocotber',
					'ocotober',
					'octber',
					'octeber',
					'octobber',
					'octobe',
					'octoer',
					'octomber',
					'octtober',
					'octuber',
					'ootober',
				],
				'octodecillion'=>[
					'octodecilion',
				],
				'octogenarian'=>[
					'octogenaran',
				],
				'octonary'=>[
					'octonery',
				],
				'octosyllable'=>[
					'octosylable',
					'octosyllible',
				],
				'ocular'=>[
					'oculer',
				],
				'odah'=>[
					'oda',
				],
				'odahs'=>[
					'odas',
				],
				'odd fellows'=>[
					'oddfellows',
				],
				'odd-shaped'=>[
					'odd shaped',
				],
				'oddball'=>[
					'oddbal',
				],
				'oddities'=>[
					'oddites',
				],
				'oddly'=>[
					'oddally',
					'oddaly',
					'oddlly',
				],
				'odea'=>[
					'ode',
				],
				'odious'=>[
					'odous',
				],
				'odiously'=>[
					'odously',
				],
				'odontoglossum'=>[
					'odontoglosum',
				],
				'odorant'=>[
					'odorent',
				],
				'odoriferous'=>[
					'odouriferous',
				],
				'odorless'=>[
					'odorles',
				],
				'odorous'=>[
					'odourous',
				],
				'odyssey'=>[
					'odysey',
				],
				'oeuvre'=>[
					'ouevre',
				],
				'of'=>[
					'od',
					'of of',
					'of of of',
					'opf',
					'ot',
				],
				'of being'=>[
					'of been',
				],
				'of course'=>[
					'ofcourse',
				],
				'of the'=>[
					'fo the',
					'fo the', 'ofthe',
					'o fthe',
					'of the of the',
					'ofthe',
				],
				'of their'=>[
					'oftheir',
				],
				'of these'=>[
					'ofthese',
				],
				'of this'=>[
					'ofthis',
				],
				'of those'=>[
					'ofthose',
				],
				'off'=>[
					'off off',
					'off off off',
				],
				'offence'=>[
					'offance',
				],
				'offender'=>[
					'offendor',
				],
				'offense'=>[
					'offence',
				],
				'offensively'=>[
					'offensivly',
				],
				'offer'=>[
					'offer offer',
					'offer offer offer',
				],
				'office'=>[
					'offce',
					'office office',
					'office office office',
				],
				'officer'=>[
					'offcier',
					'officier',
				],
				'officers'=>[
					'officiers',
				],
				'official'=>[
					'offcial',
					'offical',
					'official->offical',
					'officiall',
					'officla',
					'oficcial',
					'oficial',
				],
				'officially'=>[
					'offcially',
					'offically',
					'officaly',
					'officialy',
					'officlaly',
					'ofically',
				],
				'officials'=>[
					'offcials',
					'officals',
				],
				'officiary'=>[
					'officiery',
				],
				'officiate'=>[
					'officate',
				],
				'officinal'=>[
					'officinil',
				],
				'officious'=>[
					'officous',
				],
				'officiously'=>[
					'officiousally',
					'officiousaly',
					'officiousely',
					'officiouslly',
					'officously',
				],
				'offline'=>[
					'offlini',
				],
				'offscourings'=>[
					'offcourings',
					'offcsourings',
					'offsourings',
				],
				'offscreen'=>[
					'offcreen',
					'offcsreen',
					'offsreen',
				],
				'offshoot'=>[
					'offshot',
				],
				'often'=>[
					'fte',
					'offen',
					'often often',
					'often often often',
					'oftenly',
					'oftern',
				],
				'oftentimes'=>[
					'oftantimes',
				],
				'ogress'=>[
					'ogres',
				],
				'oh'=>[
					'oh oh',
					'oh oh oh',
				],
				'ohmmeter'=>[
					'ohmneter',
				],
				'ohmmeters'=>[
					'ohmneters',
				],
				'oil'=>[
					'oil oil',
					'oil oil oil',
				],
				'ointment'=>[
					'ointmant',
				],
				'okhrana'=>[
					'okrana',
				],
				'oklahoma'=>[
					'okalahoma',
					'oklohoma',
				],
				'old'=>[
					'old old',
					'old old old',
				],
				'oldie'=>[
					'oldei',
					'oldi',
				],
				'oldsquaw'=>[
					'oldsqauw',
				],
				'olea'=>[
					'ole',
				],
				'oleic'=>[
					'oliec',
				],
				'olein'=>[
					'olien',
				],
				'oleomargarine'=>[
					'oleomargarini',
				],
				'oligopoly'=>[
					'oligopoally',
					'oligopoaly',
					'oligopoely',
					'oligopolly',
				],
				'oligosaccharide'=>[
					'oligosacharide',
				],
				'olivary'=>[
					'olivery',
				],
				'olivine'=>[
					'olivini',
				],
				'olivinitic'=>[
					'olivinatic',
				],
				'olla'=>[
					'ola',
				],
				'omani-occupied'=>[
					'omani occupied',
				],
				'omelet'=>[
					'omelette',
				],
				'omen'=>[
					'oruen',
				],
				'omened'=>[
					'omend',
				],
				'omentum'=>[
					'omantum',
				],
				'ominous'=>[
					'omnious',
				],
				'omissible'=>[
					'omissable',
				],
				'omission'=>[
					'omision',
					'ommision',
					'ommission',
				],
				'omit'=>[
					'omitt',
					'ommit',
				],
				'omitted'=>[
					'omited',
					'ommited',
					'ommitted',
				],
				'omitting'=>[
					'omiting',
					'ommiting',
					'ommitting',
				],
				'ommatidia'=>[
					'omnatidia',
				],
				'ommatidium'=>[
					'omnatidium',
				],
				'omnicompetence'=>[
					'omnicompetance',
				],
				'omnicompetent'=>[
					'omnicompetant',
				],
				'omnifarious'=>[
					'omnifarous',
				],
				'omnipotence'=>[
					'omnipotance',
				],
				'omnipresence'=>[
					'omnipresance',
				],
				'omnipresent'=>[
					'omnipresant',
				],
				'omniscience'=>[
					'omnisciance',
				],
				'omniscient'=>[
					'omnicient',
					'omnicsient',
					'omnisceint',
					'omniscint',
					'omnisient',
				],
				'omnivorous'=>[
					'omniverous',
				],
				'omnivorously'=>[
					'omniverously',
				],
				'on'=>[
					'on on',
					'on on on',
				],
				'on board'=>[
					'onboard',
				],
				'on its'=>[
					'on it\'s',
				],
				'on the'=>[
					'on the on the',
					'onthe',
				],
				'on top'=>[
					'ontop',
				],
				'once'=>[
					'once once',
					'once once once',
				],
				'one'=>[
					'one one',
					'one one one',
				],
				'one\'s rights'=>[
					'ones\' rights',
				],
				'oneiric'=>[
					'onieric',
				],
				'oneiromancies'=>[
					'onieromancies',
				],
				'oneiromancy'=>[
					'oneiromansy',
					'onieromancy',
				],
				'oneness'=>[
					'onenes',
				],
				'online'=>[
					'onlini',
				],
				'only'=>[
					'olny',
					'oniy',
					'only only',
					'only only only',
					'onyl',
				],
				'onomastician'=>[
					'onomastican',
				],
				'onomatopoeia'=>[
					'onomatopoiea',
				],
				'onomatopoeias'=>[
					'onomatopoieas',
				],
				'onscreen'=>[
					'oncreen',
					'oncsreen',
					'onsreen',
				],
				'oompah'=>[
					'oompa',
				],
				'oompahed'=>[
					'oompaed',
				],
				'oompahing'=>[
					'oompaing',
				],
				'oompahs'=>[
					'oompas',
				],
				'opah'=>[
					'opa',
				],
				'opahs'=>[
					'opas',
				],
				'opalescence'=>[
					'opalescance',
				],
				'opalescent'=>[
					'opalecent',
					'opalecsent',
					'opalesent',
				],
				'opaquely'=>[
					'opaquly',
				],
				'open'=>[
					'open open',
					'open open open',
					'oppen',
				],
				'opened'=>[
					'opend',
					'openned',
					'oppened',
				],
				'openhandedly'=>[
					'openhandedally',
					'openhandedaly',
					'openhandedely',
					'openhandedlly',
				],
				'openhearted'=>[
					'openherted',
				],
				'openheartedness'=>[
					'openhertedness',
				],
				'opening'=>[
					'oppening',
				],
				'openly'=>[
					'openely',
				],
				'openmouthed'=>[
					'opemouthed',
					'openouthed',
				],
				'openmouthedly'=>[
					'opemouthedly',
					'openouthedly',
				],
				'openmouthedness'=>[
					'opemouthedness',
					'openouthedness',
				],
				'operable'=>[
					'operible',
				],
				'operant'=>[
					'operent',
				],
				'operate'=>[
					'oparate',
					'operate operate',
					'operate operate operate',
					'opperate',
				],
				'operatio'=>[
					'operaton',
				],
				'operation'=>[
					'opertion',
					'opperation',
				],
				'operations'=>[
					'operatons',
				],
				'operator'=>[
					'operater',
				],
				'opercular'=>[
					'operculer',
				],
				'operetta'=>[
					'operette',
				],
				'operosely'=>[
					'operosly',
				],
				'ophidian'=>[
					'ophidan',
				],
				'ophthalmic'=>[
					'opthalmic',
				],
				'ophthalmologist'=>[
					'opthalmologist',
					'opthamologist',
					'opthomologist',
				],
				'ophthalmology'=>[
					'opthalmology',
					'opthamology',
					'opthomology',
				],
				'ophthalmoscope'=>[
					'ophthalmocope',
					'ophthalmocsope',
					'ophthalmosope',
				],
				'ophthalmoscopes'=>[
					'ophthalmocopes',
					'ophthalmocsopes',
					'ophthalmosopes',
				],
				'ophthalmoscopic'=>[
					'ophthalmocopic',
					'ophthalmocsopic',
					'ophthalmosopic',
				],
				'opine'=>[
					'opinate',
					'opini',
				],
				'opining'=>[
					'opinang',
				],
				'opinion'=>[
					'opinaon',
					'opionion',
					'oppinion',
				],
				'opinionated'=>[
					'opinaonated',
				],
				'opinionatedly'=>[
					'opinaonatedly',
				],
				'opinionatedness'=>[
					'opinaonatedness',
				],
				'opinionative'=>[
					'opinaonative',
				],
				'opinionatively'=>[
					'opinaonatively',
					'opinionativly',
				],
				'opioid'=>[
					'opiod',
				],
				'opioids'=>[
					'opiods',
				],
				'opossum'=>[
					'opposum',
				],
				'opponency'=>[
					'opponensy',
				],
				'opponent'=>[
					'oponent',
					'opponant',
					'opponet',
				],
				'opponents'=>[
					'oponents',
				],
				'opportune'=>[
					'oportune',
				],
				'opportunely'=>[
					'opportunly',
				],
				'opportuneness'=>[
					'oportuneness',
				],
				'opportunenesses'=>[
					'oportunenesses',
				],
				'opportunism'=>[
					'oppourtunism',
				],
				'opportunisms'=>[
					'oportunisms',
				],
				'opportunist'=>[
					'oportunist',
				],
				'opportunistic'=>[
					'oportunistic',
				],
				'opportunists'=>[
					'oportunists',
				],
				'opportunities'=>[
					'oportunities',
					'opportuinities',
					'opportunites',
					'oppourtunities',
				],
				'opportunity'=>[
					'opertunity',
					'oportunity',
					'oppertunity',
					'opportuinity',
					'opportunitey',
					'opportunty',
					'opportxmity',
					'oppotunity',
					'oppourtunity',
					'oppurtunity',
				],
				'opposabilities'=>[
					'oposabilities',
				],
				'opposability'=>[
					'oposability',
				],
				'opposable'=>[
					'oposable',
					'opposible',
				],
				'oppose'=>[
					'opose',
				],
				'opposed'=>[
					'opposcd',
					'opposctl',
					'oppossed',
				],
				'opposite'=>[
					'oposite',
					'opposit',
					'opposite opposite',
					'opposite opposite opposite',
				],
				'oppositely'=>[
					'opposately',
					'oppositly',
				],
				'oppositeness'=>[
					'opositeness',
				],
				'oppositenesses'=>[
					'opositenesses',
				],
				'opposition'=>[
					'oposition',
					'oppositiom',
					'oppositon',
				],
				'oppositional'=>[
					'opositional',
				],
				'oppositionist'=>[
					'opositionist',
				],
				'oppositionists'=>[
					'opositionists',
				],
				'oppress'=>[
					'oppres',
					'opress',
				],
				'oppressed'=>[
					'oppremed',
					'opressed',
				],
				'oppresses'=>[
					'opresses',
				],
				'oppressing'=>[
					'opressing',
				],
				'oppression'=>[
					'oppresion',
					'oppresision',
					'opresion',
					'opression',
				],
				'oppressive'=>[
					'oppresive',
					'opressive',
				],
				'oppressively'=>[
					'oppressivly',
				],
				'oppressiveness'=>[
					'opressiveness',
				],
				'oppressor'=>[
					'opressor',
				],
				'oppressors'=>[
					'opressors',
				],
				'opprobrious'=>[
					'opprobrous',
					'oprobrious',
				],
				'opprobriously'=>[
					'opprobriousally',
					'opprobriousaly',
					'opprobriousely',
					'opprobriouslly',
					'opprobrously',
					'oprobriously',
				],
				'opprobriousness'=>[
					'oprobriousness',
				],
				'opprobrium'=>[
					'oprobrium',
				],
				'oppugn'=>[
					'opugn',
				],
				'oppugnant'=>[
					'opugnant',
				],
				'oppugners'=>[
					'opugners',
				],
				'oppugning'=>[
					'opugning',
				],
				'optatively'=>[
					'optativly',
				],
				'optician'=>[
					'optican',
				],
				'optimism'=>[
					'optomism',
				],
				'optimist'=>[
					'optomist',
				],
				'optimistic'=>[
					'optomistic',
				],
				'optimistically'=>[
					'optimisticalally',
					'optimisticalaly',
					'optimisticalely',
					'optimisticallly',
				],
				'option'=>[
					'opfion',
				],
				'opulence'=>[
					'opulance',
				],
				'opulency'=>[
					'opulensy',
				],
				'opulent'=>[
					'opulant',
				],
				'opulently'=>[
					'opulentally',
					'opulentaly',
					'opulentely',
					'opulentlly',
				],
				'opuscular'=>[
					'opusculer',
				],
				'oquassa'=>[
					'oqaussa',
				],
				'or'=>[
					'lor',
					'or or',
					'or or or',
				],
				'oracular'=>[
					'oraculer',
				],
				'orbicular'=>[
					'orbiculer',
				],
				'orbicularly'=>[
					'orbicularally',
					'orbicularaly',
					'orbicularely',
					'orbicularlly',
				],
				'orbital'=>[
					'oribital',
				],
				'orcein'=>[
					'orcien',
				],
				'orchestra'=>[
					'orchester',
					'orchestera',
				],
				'orchestral'=>[
					'orchesteral',
				],
				'ordainment'=>[
					'ordaiment',
					'ordainent',
				],
				'ordainments'=>[
					'ordaiments',
					'ordainents',
				],
				'ordeal'=>[
					'ordel',
				],
				'order'=>[
					'order order',
					'order order order',
				],
				'ordered'=>[
					'orderes',
				],
				'orderly'=>[
					'orderally',
					'orderaly',
					'orderely',
					'orderlly',
				],
				'ordinal'=>[
					'ordinil',
				],
				'ordinals'=>[
					'ordinils',
				],
				'ordinance'=>[
					'ordience',
					'ordinence',
					'ordinince',
				],
				'ordinand'=>[
					'ordinind',
				],
				'ordinarily'=>[
					'ordinarially',
					'ordinarialy',
					'ordinariely',
					'ordinarilly',
					'ordinirily',
				],
				'ordinarinesses'=>[
					'ordinirinesses',
				],
				'ordinary'=>[
					'ordinery',
					'ordiniry',
				],
				'ordinate'=>[
					'ordinite',
				],
				'ordination'=>[
					'ordinition',
				],
				'ordnance'=>[
					'ordnence',
				],
				'ordonnance'=>[
					'ordonance',
					'ordonnence',
				],
				'oreide'=>[
					'oriede',
				],
				'organ'=>[
					'organ organ',
					'organ organ organ',
				],
				'organic'=>[
					'organical',
				],
				'organism'=>[
					'organim',
					'organisim',
				],
				'organisms'=>[
					'organisims',
				],
				'organization'=>[
					'orgainization',
					'organiation',
					'organizaton',
					'orginization',
				],
				'organization\'s'=>[
					'orginization\'s',
				],
				'organizations'=>[
					'organizatons',
					'orginizations',
				],
				'organize'=>[
					'orgainize',
					'orginize',
				],
				'organochlorine'=>[
					'organochlorini',
				],
				'organometallic'=>[
					'organometalic',
				],
				'oriel'=>[
					'oreil',
					'oril',
				],
				'orient'=>[
					'oreint',
					'oriant',
					'orint',
				],
				'oriental'=>[
					'oreintal',
					'oriantal',
					'orintal',
				],
				'orientalize'=>[
					'oreintalize',
					'orintalize',
				],
				'orientate'=>[
					'oreintate',
					'orintate',
				],
				'orientation'=>[
					'oreintation',
					'oriantation',
					'orienation',
					'oriention',
					'orintation',
				],
				'orienteering'=>[
					'oreinteering',
					'orianteering',
					'orinteering',
				],
				'oriflamme'=>[
					'oriflamne',
				],
				'origin'=>[
					'orgin',
					'orginin',
				],
				'original'=>[
					'orginal',
					'origanal',
					'origial',
					'original original',
					'original original original',
					'originial',
					'originil',
					'originnal',
					'origional',
					'orignal',
					'orignial',
					'origonal',
					'orriginal',
				],
				'originalities'=>[
					'originilities',
				],
				'originality'=>[
					'originility',
				],
				'originally'=>[
					'orginally',
					'origially',
					'origially', 'originaly',
					'originalally',
					'originalaly',
					'originalely',
					'originallly',
					'originaly',
					'originilly',
					'originnally',
					'origionally',
					'orignally',
					'orriginally',
				],
				'originate'=>[
					'orginate',
					'originiate',
					'originite',
					'orignate',
				],
				'originatively'=>[
					'originativly',
					'originitively',
				],
				'orinasal'=>[
					'orinisal',
				],
				'ornament'=>[
					'ornamant',
				],
				'ornamental'=>[
					'ornamantal',
				],
				'ornamentation'=>[
					'ornamantation',
				],
				'ornately'=>[
					'ornatly',
				],
				'ornithine'=>[
					'ornithini',
				],
				'ornithischian'=>[
					'ornithichian',
					'ornithicshian',
					'ornithischan',
					'ornithishian',
				],
				'orpine'=>[
					'orpini',
				],
				'orquesta revé'=>[
					'orquesta reve',
				],
				'orra'=>[
					'ora',
				],
				'orrery'=>[
					'orery',
				],
				'orris'=>[
					'oris',
				],
				'orthogonal'=>[
					'orthagonal',
					'orthgonal',
				],
				'orthogonally'=>[
					'orthagonally',
					'orthogonaly',
				],
				'orthomolecular'=>[
					'orthomoleculer',
				],
				'osar'=>[
					'oser',
				],
				'oscillate'=>[
					'ocillate',
					'ocsillate',
					'oscilate',
					'osillate',
				],
				'oscillation'=>[
					'ocillation',
					'ocsillation',
					'oscilation',
					'osillation',
				],
				'oscillograph'=>[
					'ocillograph',
					'ocsillograph',
					'oscilograph',
					'osillograph',
				],
				'oscillographies'=>[
					'ocillographies',
					'ocsillographies',
					'osillographies',
				],
				'oscilloscope'=>[
					'oscillocope',
					'oscillocsope',
					'oscillosope',
					'osciloscope',
				],
				'oscine'=>[
					'ocine',
					'ocsine',
					'oscini',
					'osine',
				],
				'oscitance'=>[
					'oscitence',
				],
				'oscitancy'=>[
					'oscitansy',
				],
				'oscula'=>[
					'ocsula',
					'ocula',
					'osula',
				],
				'oscular'=>[
					'osculer',
				],
				'osier'=>[
					'oseir',
					'osir',
				],
				'osmious'=>[
					'osmous',
				],
				'osmolar'=>[
					'osmoler',
				],
				'osmoregulation'=>[
					'osmouregulation',
				],
				'osmoregulations'=>[
					'osmouregulations',
				],
				'osmoregulatory'=>[
					'osmouregulatory',
				],
				'oss'=>[
					'oses',
				],
				'ossa'=>[
					'osa',
				],
				'ossein'=>[
					'ossien',
				],
				'ossia'=>[
					'osia',
				],
				'ossicular'=>[
					'ossiculer',
				],
				'ossification'=>[
					'osification',
				],
				'ossify'=>[
					'osify',
				],
				'ossuary'=>[
					'ossaury',
					'ossuery',
				],
				'osteitis'=>[
					'ostietis',
				],
				'ostensible'=>[
					'ostensable',
				],
				'ostensively'=>[
					'ostensivly',
				],
				'ostentatious'=>[
					'ostantatious',
					'ostentatous',
				],
				'ostentatiously'=>[
					'ostentatiousally',
					'ostentatiousaly',
					'ostentatiousely',
					'ostentatiouslly',
					'ostentatously',
				],
				'ostiary'=>[
					'ostiery',
				],
				'ostinati'=>[
					'ostiniti',
				],
				'ostinato'=>[
					'ostinito',
				],
				'ostiolar'=>[
					'ostioler',
				],
				'other'=>[
					'otehr',
					'othel',
					'other other',
					'other other other',
					'othere',
				],
				'other hand'=>[
					'otherhand',
				],
				'other side'=>[
					'otherside',
				],
				'otherness'=>[
					'othernes',
				],
				'others'=>[
					'otehrs',
					'otheres',
					'tohers',
				],
				'otherworldly'=>[
					'otherworldally',
					'otherworldaly',
					'otherworldely',
					'otherworldlly',
				],
				'otiosely'=>[
					'otiosly',
				],
				'otosclerosis'=>[
					'otoclerosis',
					'otocslerosis',
					'otoslerosis',
				],
				'otoscope'=>[
					'otocope',
					'otocsope',
					'otosope',
				],
				'ottar'=>[
					'otter',
				],
				'ottawa'=>[
					'ottowa',
				],
				'ottoman'=>[
					'ottaman',
				],
				'ouabain'=>[
					'oaubain',
				],
				'our'=>[
					'our our',
					'our our our',
				],
				'out'=>[
					'out out',
					'out out out',
				],
				'out loud'=>[
					'outloud',
				],
				'outbalance'=>[
					'outbalence',
				],
				'outbargaining'=>[
					'outbargainang',
				],
				'outbegging'=>[
					'outbeging',
				],
				'outbragged'=>[
					'outbraged',
				],
				'outbragging'=>[
					'outbraging',
				],
				'outbrazened'=>[
					'outbrazend',
				],
				'outbreak'=>[
					'outbrek',
				],
				'outcast'=>[
					'outcasted',
				],
				'outcome'=>[
					'outcone',
				],
				'outcropped'=>[
					'outcroped',
				],
				'outdance'=>[
					'outdence',
				],
				'outdatedly'=>[
					'outdatedally',
					'outdatedaly',
					'outdatedely',
					'outdatedlly',
				],
				'outdistance'=>[
					'outdistence',
				],
				'outdoorsy'=>[
					'outdoorcy',
				],
				'outdragged'=>[
					'outdraged',
				],
				'outdragging'=>[
					'outdraging',
				],
				'outdropped'=>[
					'outdroped',
				],
				'outer'=>[
					'outter',
				],
				'outerwear'=>[
					'outerweer',
					'outerwer',
				],
				'outfence'=>[
					'outfance',
				],
				'outfield'=>[
					'outfeild',
					'outfild',
				],
				'outfielder'=>[
					'outfeilder',
					'outfilder',
				],
				'outfly'=>[
					'outfally',
					'outfaly',
					'outfely',
					'outflly',
				],
				'outgaining'=>[
					'outgainang',
				],
				'outgrinned'=>[
					'outgrined',
				],
				'outgunning'=>[
					'outguning',
				],
				'outhumor'=>[
					'outhumour',
				],
				'outhumored'=>[
					'outhumoured',
				],
				'outhumoring'=>[
					'outhumouring',
				],
				'outhumors'=>[
					'outhumours',
				],
				'outjuggled'=>[
					'outjugled',
				],
				'outjuggles'=>[
					'outjugles',
				],
				'outjuggling'=>[
					'outjugling',
				],
				'outlier'=>[
					'outleir',
					'outlir',
				],
				'outline'=>[
					'outlini',
				],
				'outliner'=>[
					'outlinir',
				],
				'outlying'=>[
					'outlaying',
				],
				'outmanning'=>[
					'outmaning',
				],
				'outpatient'=>[
					'outpateint',
					'outpatiant',
					'outpatint',
				],
				'outplacement'=>[
					'outplacemant',
				],
				'outpreened'=>[
					'outpreend',
				],
				'outquote'=>[
					'outqote',
				],
				'outquoted'=>[
					'outqoted',
				],
				'outquotes'=>[
					'outqotes',
				],
				'outquoting'=>[
					'outqoting',
				],
				'outrageous'=>[
					'outragous',
				],
				'outrance'=>[
					'outrence',
				],
				'outreach'=>[
					'outrech',
				],
				'outrigger'=>[
					'outriger',
				],
				'outriggers'=>[
					'outrigers',
				],
				'outrigging'=>[
					'outriging',
				],
				'outrunners'=>[
					'outruners',
				],
				'outrunning'=>[
					'outruning',
				],
				'outscore'=>[
					'outcore',
					'outcsore',
					'outsore',
				],
				'outshine'=>[
					'outshini',
				],
				'outshining'=>[
					'outshinang',
				],
				'outside'=>[
					'ouside',
					'oustide',
				],
				'outsinning'=>[
					'outsining',
				],
				'outsnore'=>[
					'outsnoure',
				],
				'outsnored'=>[
					'outsnoured',
				],
				'outsnores'=>[
					'outsnoures',
				],
				'outsnoring'=>[
					'outsnouring',
				],
				'outsoar'=>[
					'outsoer',
				],
				'outspanned'=>[
					'outspaned',
				],
				'outspent'=>[
					'outspant',
				],
				'outspokenness'=>[
					'outspokeness',
				],
				'outspokennesses'=>[
					'outspokenesses',
				],
				'outstanding'=>[
					'oustanding',
				],
				'outtake'=>[
					'outake',
				],
				'outthrobbed'=>[
					'outthrobed',
				],
				'outthrobbing'=>[
					'outthrobing',
				],
				'outward'=>[
					'outword',
				],
				'outwardly'=>[
					'outwardally',
					'outwardaly',
					'outwardely',
					'outwardlly',
				],
				'outwards'=>[
					'outwords',
				],
				'outwear'=>[
					'outweer',
				],
				'outweary'=>[
					'outweery',
				],
				'outweigh'=>[
					'outwiegh',
				],
				'outweighed'=>[
					'outweighted',
				],
				'ovarian'=>[
					'ovaran',
				],
				'ovariectomy'=>[
					'ovareictomy',
					'ovarictomy',
				],
				'ovary'=>[
					'overy',
				],
				'ovately'=>[
					'ovatly',
				],
				'over'=>[
					'over over',
					'over over over',
				],
				'overabundance'=>[
					'overabundence',
				],
				'overabundant'=>[
					'overabundent',
				],
				'overaccentuate'=>[
					'overaccentaute',
					'overacentuate',
				],
				'overaccentuated'=>[
					'overaccentauted',
					'overacentuated',
				],
				'overaccentuates'=>[
					'overaccentautes',
					'overacentuates',
				],
				'overachieve'=>[
					'overacheive',
					'overachive',
				],
				'overaggressive'=>[
					'overaggresive',
					'overagressive',
				],
				'overall'=>[
					'overal',
				],
				'overambitious'=>[
					'overambitous',
				],
				'overanxious'=>[
					'overanxous',
				],
				'overapplication'=>[
					'overaplication',
				],
				'overarranged'=>[
					'overaranged',
				],
				'overarranges'=>[
					'overaranges',
				],
				'overbalance'=>[
					'overbalence',
				],
				'overbear'=>[
					'overbeer',
				],
				'overbearing'=>[
					'overbering',
				],
				'overborrowed'=>[
					'overborowed',
				],
				'overburdened'=>[
					'overburdend',
				],
				'overbusy'=>[
					'overbucy',
				],
				'overcautious'=>[
					'overcautous',
				],
				'overclear'=>[
					'overcleer',
				],
				'overcommit'=>[
					'overcomnit',
				],
				'overcommitment'=>[
					'overcomnitment',
				],
				'overcommitments'=>[
					'overcomnitments',
				],
				'overcommitting'=>[
					'overcomnitting',
				],
				'overcommunicate'=>[
					'overcomnunicate',
				],
				'overcompliance'=>[
					'overcomplience',
				],
				'overconfidence'=>[
					'overconfidance',
				],
				'overconfident'=>[
					'overconfidant',
				],
				'overconfidently'=>[
					'overconfidantly',
				],
				'overconscious'=>[
					'overconscous',
				],
				'overcorrect'=>[
					'overcorect',
				],
				'overcorrecting'=>[
					'overcorecting',
				],
				'overcorrects'=>[
					'overcorects',
				],
				'overdependence'=>[
					'overdependance',
				],
				'overdependent'=>[
					'overdependant',
				],
				'overdiscounting'=>[
					'overdicounting',
					'overdicsounting',
					'overdisounting',
				],
				'overdominance'=>[
					'overdominence',
					'overdominince',
				],
				'overdominances'=>[
					'overdomininces',
				],
				'overdubbed'=>[
					'overdubed',
				],
				'overdubbing'=>[
					'overdubing',
				],
				'overeagernesses'=>[
					'overegernesses',
				],
				'overeasy'=>[
					'overeacy',
				],
				'overenamored'=>[
					'overenamoured',
				],
				'overengineering'=>[
					'overenginiering',
				],
				'overentertained'=>[
					'overentertainid',
				],
				'overenthusiasm'=>[
					'overanthusiasm',
					'overenthuisasm',
				],
				'overenthusiasms'=>[
					'overenthuisasms',
				],
				'overevaluation'=>[
					'overevalaution',
				],
				'overevaluations'=>[
					'overevalautions',
				],
				'overexaggerate'=>[
					'overexagerate',
				],
				'overexaggerated'=>[
					'overexagerated',
				],
				'overexaggerates'=>[
					'overexagerates',
				],
				'overexplaining'=>[
					'overexplainang',
				],
				'overfamiliar'=>[
					'overfamilar',
					'overfamilier',
				],
				'overfastidious'=>[
					'overfastidous',
				],
				'overfly'=>[
					'overfally',
					'overfaly',
					'overfely',
					'overflly',
				],
				'overfocusing'=>[
					'overfocuisng',
				],
				'overfussy'=>[
					'overfuscy',
				],
				'overgenerously'=>[
					'overgenerousally',
					'overgenerousaly',
					'overgenerousely',
					'overgenerouslly',
				],
				'overglamorize'=>[
					'overglamourize',
				],
				'overglamorized'=>[
					'overglamourized',
				],
				'overglamorizes'=>[
					'overglamourizes',
				],
				'overglamorizing'=>[
					'overglamourizing',
				],
				'overhead'=>[
					'overhed',
				],
				'overhear'=>[
					'overheer',
				],
				'overhonor'=>[
					'overhonour',
				],
				'overhonored'=>[
					'overhonoured',
				],
				'overhonoring'=>[
					'overhonouring',
				],
				'overhonors'=>[
					'overhonours',
				],
				'overidentified'=>[
					'overidantified',
				],
				'overidentifies'=>[
					'overidantifies',
				],
				'overidentify'=>[
					'overidantify',
				],
				'overidentifying'=>[
					'overidantifying',
				],
				'overimaginative'=>[
					'overimaginitive',
				],
				'overindulgence'=>[
					'overindulgance',
				],
				'overingenious'=>[
					'overingenous',
				],
				'overintense'=>[
					'overintence',
				],
				'overissuance'=>[
					'overissaunce',
					'overissuence',
				],
				'overissuances'=>[
					'overissaunces',
				],
				'overkill'=>[
					'overkil',
				],
				'overlaid'=>[
					'overlayed',
				],
				'overlapped'=>[
					'overlaped',
				],
				'overlapping'=>[
					'overlaping',
				],
				'overlengthened'=>[
					'overlengthend',
				],
				'overlie'=>[
					'overlei',
					'overli',
				],
				'overliterary'=>[
					'overliterery',
				],
				'overly'=>[
					'overally',
					'overaly',
					'overely',
					'overlly',
				],
				'overmanned'=>[
					'overmaned',
				],
				'overmining'=>[
					'overminang',
				],
				'overobvious'=>[
					'overobvous',
				],
				'overopinionated'=>[
					'overopinaonated',
				],
				'overparticular'=>[
					'overparticuler',
					'overperticular',
				],
				'overpass'=>[
					'overpas',
				],
				'overpersuade'=>[
					'overpersaude',
				],
				'overpersuaded'=>[
					'overpersauded',
				],
				'overpersuades'=>[
					'overpersaudes',
				],
				'overpersuading'=>[
					'overpersauding',
				],
				'overpersuasion'=>[
					'overpersausion',
				],
				'overpersuasions'=>[
					'overpersausions',
				],
				'overprescribe'=>[
					'overprecribe',
					'overprecsribe',
					'overpresribe',
				],
				'overprescribing'=>[
					'overprecribing',
					'overprecsribing',
					'overpresribing',
				],
				'overpressure'=>[
					'overpresure',
				],
				'overprogrammed'=>[
					'overprogramned',
				],
				'overprogramming'=>[
					'overprogramning',
				],
				'overqualified'=>[
					'overqaulified',
					'overqualifeid',
					'overqualifid',
				],
				'overran'=>[
					'overan',
				],
				'overrate'=>[
					'overate',
				],
				'overrated'=>[
					'overated',
				],
				'overreach'=>[
					'overeach',
				],
				'overreachers'=>[
					'overeachers',
				],
				'overreaching'=>[
					'overeaching',
				],
				'overreact'=>[
					'overeact',
				],
				'overreacting'=>[
					'overeacting',
				],
				'overreaction'=>[
					'overeaction',
				],
				'overrefinement'=>[
					'overefinement',
				],
				'overrefinements'=>[
					'overefinements',
					'overrefiniments',
				],
				'overregulate'=>[
					'overegulate',
				],
				'overregulating'=>[
					'overegulating',
				],
				'overregulation'=>[
					'overegulation',
				],
				'overregulations'=>[
					'overegulations',
				],
				'overreliance'=>[
					'overeliance',
					'overrelience',
				],
				'overreported'=>[
					'overeported',
				],
				'overrepresented'=>[
					'overepresented',
					'overrepresanted',
				],
				'overresponding'=>[
					'overesponding',
				],
				'overresponds'=>[
					'overesponds',
				],
				'override'=>[
					'over-ride',
					'overide',
				],
				'overrides'=>[
					'over-rides',
				],
				'overriding'=>[
					'overiding',
				],
				'overripe'=>[
					'overipe',
				],
				'overroasting'=>[
					'overoasting',
				],
				'overrode'=>[
					'overode',
				],
				'overruff'=>[
					'overuff',
				],
				'overrule'=>[
					'overule',
				],
				'overrun'=>[
					'overun',
				],
				'overscrupulous'=>[
					'overcrupulous',
					'overcsrupulous',
					'oversrupulous',
				],
				'overseas'=>[
					'overses',
				],
				'overserious'=>[
					'overserous',
				],
				'overseriously'=>[
					'overseriousally',
					'overseriousaly',
					'overseriousely',
					'overseriouslly',
					'overserously',
				],
				'overshadowed'=>[
					'overshaddowed',
				],
				'oversight'=>[
					'oversite',
				],
				'overstirring'=>[
					'overstiring',
				],
				'overstraining'=>[
					'overstrainang',
				],
				'oversubscribe'=>[
					'oversubcribe',
					'oversubcsribe',
					'oversubsribe',
				],
				'oversubscribing'=>[
					'oversubcribing',
					'oversubcsribing',
					'oversubsribing',
				],
				'oversupped'=>[
					'oversuped',
				],
				'oversupply'=>[
					'oversuply',
					'oversuppally',
					'oversuppaly',
					'oversuppely',
					'oversupplly',
				],
				'oversupplying'=>[
					'oversuplying',
				],
				'oversuspicious'=>[
					'oversuspicous',
				],
				'oversweetened'=>[
					'oversweetend',
				],
				'overthrown'=>[
					'overtnrown',
				],
				'overtightened'=>[
					'overtightend',
				],
				'overtipped'=>[
					'overtiped',
				],
				'overtopped'=>[
					'overtoped',
				],
				'overtraining'=>[
					'overtrainang',
				],
				'overture'=>[
					'oveture',
				],
				'overusing'=>[
					'overuisng',
				],
				'overvaluation'=>[
					'overvalaution',
				],
				'overvaluations'=>[
					'overvalautions',
				],
				'overview'=>[
					'overveiw',
					'overviw',
				],
				'overwary'=>[
					'overwery',
				],
				'overwear'=>[
					'overweer',
				],
				'overweary'=>[
					'overweery',
				],
				'overweened'=>[
					'overweend',
				],
				'overweigh'=>[
					'overwiegh',
				],
				'overweight'=>[
					'overwieght',
				],
				'overweighting'=>[
					'overwieghting',
				],
				'overwhelmed'=>[
					'overwelmed',
					'overwhemed',
					'overwhemed', 'overwelmed',
				],
				'overwhelming'=>[
					'overwelming',
					'ovrwhelming',
				],
				'overzealous'=>[
					'overzelous',
				],
				'overzealousness'=>[
					'overzelousness',
				],
				'ovine'=>[
					'ovini',
				],
				'ovipara'=>[
					'ovipera',
				],
				'oviparity'=>[
					'oviperity',
				],
				'oviparous'=>[
					'oviperous',
				],
				'ovoviviparous'=>[
					'ovoviviperous',
				],
				'ovoviviparously'=>[
					'ovoviviperously',
				],
				'ovular'=>[
					'ovuler',
				],
				'ovulary'=>[
					'ovulery',
				],
				'own'=>[
					'own own',
					'own own own',
					'pwn',
				],
				'ownable'=>[
					'ownible',
				],
				'oxen'=>[
					'oxens',
					'oxes',
				],
				'oxidant'=>[
					'oxident',
				],
				'oxidants'=>[
					'oxidents',
				],
				'oxidatively'=>[
					'oxidativly',
				],
				'oxygen'=>[
					'oxigen',
					'oxyen',
					'oxygen oxygen',
					'oxygen oxygen oxygen',
				],
				'oxygenated'=>[
					'oxigenated',
				],
				'oxygenation'=>[
					'oxigenation',
				],
				'oxymora'=>[
					'oxymoura',
				],
				'oxymoron'=>[
					'oximoron',
					'oxymouron',
				],
				'oxymoronic'=>[
					'oxymouronic',
				],
				'oxymoronically'=>[
					'oxymouronically',
				],
				'oxymorons'=>[
					'oxymourons',
				],
				'oxytetracycline'=>[
					'oxytetracyclini',
				],
			];
		}
	}

?>